### ISSUE TITLE
文件上传PHP8  语法分析绕过

### ISSUE THREAD

**Issue by weaweawe01** [chaitin/safeline#1]
在后端为PHP8.0 的时候。
![577c33ce64e4c0db154b1364afc7d3f](https://user-images.githubusercontent.com/111571429/231960921-aa3d75e9-753e-45f2-b702-56da08d2a24e.png)

内置应该是支持了5.6-7.4 的语法。
发现8.0 以上的语法糖 没有被检测到

**Comment by xiaoputaoya** [comment]
我们后续会尽快修复，感谢提交！
