### ISSUE TITLE
希望能支持nginx、traefik等网关型应用内部扩展

### ISSUE THREAD

**Issue by w7team** [chaitin/safeline#10]
真正罕见的数据集来源于大型项目，但是中间有一次tcp、http转发在中大型项目无法落地，会造成不必要的性能损耗。希望能支持内部lua、go扩展，这样才能贡献出更多高质量的大数据样本

**Comment by naocanmonster** [comment]
雷池的企业版是支持 SDK 方式接入的，社区版暂时还不支持，有兴趣的话欢迎了解一下雷池企业版
