### ISSUE TITLE
[Bug] 动态防护失效问题

### ISSUE THREAD

**Issue by Peter1303** [chaitin/SafeLine#1002]
### What happened?

在开启了对 JS 脚本防护时，动态防护失效
雷池版本：6.2.4
detector：tcp 模式

开启动态防护，未开启 JS 动态混淆
![1](https://github.com/user-attachments/assets/6e75f400-42a9-4a78-9fd6-a859dc045418)

开启动态防护，开启 JS 动态混淆
![2](https://github.com/user-attachments/assets/af44e141-91f4-40ac-8b99-3cb3fb5c9626)

### How we reproduce?

1. 对 A 网站开启动态防护
2. 对 A 网站开启 JS 动态混淆

### Expected behavior

动态防护应该生效，同时 JS 动态混淆也要生效

**Comment by safe1ine** [comment]
你界面上怎么配的,截图看一下

**Comment by Peter1303** [comment]
![image](https://github.com/user-attachments/assets/bad9784e-63a1-407e-88ba-51f12ada46d1)
是指这个动态防护的界面吗

**Comment by xbingW** [comment]
6.4.0 已修复
