### ISSUE TITLE
[Bug] Abnormal CPU usage

### ISSUE THREAD

**Issue by NuanRMxi** [chaitin/SafeLine#1003]
### What happened?

在未知情况下，一个叫 `engine` 的进程异常的占用了我的CPU，经过我的检查，它来自WAF，因为它含有以下环境变量
![QQ_1721840783060](https://github.com/user-attachments/assets/81743b50-7d00-449e-9e71-a59fc01550f6)
全屏如下
![QQ_1721840817151](https://github.com/user-attachments/assets/f9937e13-4833-461b-8481-ee2d4e42d27f)
在docker中，所有的容器均未有CPU占用异常的容器，所以很抱歉我无法提供更多内容，以上就是我所有能提供的细节，我不会重启让此情况消失，如需要提供更多信息请告诉我怎么做，直至问题被解决

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by safe1ine** [comment]
这个看起来应该是雷池云托管应用的进程, 我们需要排查一下具体问题

**Comment by xbingW** [comment]
目前 agent 应该已经推送自动更新，麻烦确认一下新版本是否还有此问题
