### ISSUE TITLE
[Suggestion] 功能建议

### ISSUE THREAD

**Issue by SkyCat7798** [chaitin/SafeLine#1005]
### What would you like to be added or improved?

以下功能不知道能不能实现，，谢谢哦

1、数据统计
1.1 可以查看独立ip和攻击ip的信息
      可以更方便的获取访问者和攻击ip，不然还要从日志里过滤
1.2 增加自动刷新，可以指定多久刷新一次
      可以当成大屏看，，实时关注访问和攻击信息
1.3 增加访问日志统计和查询
      方便查询

2、攻击事件
2.1 事件增加导出功能
2.2 攻击事件和攻击日志增加自动刷新功能，可以指定多久刷新一次
      方便实时关注访问和攻击信息

3、防护配置
3.1 自定义规则的条件中增加or选项
      方便创建规则，减少相似规则数量
3.2 通用配置里增加ip地址组更新时间的设置，可以设置在指定时间更新或者每隔多长时间自动更新
      可以更快的更新ip地址列表
3.4 自定义规则里是否可以增加生效时间的条件，比如某个规则仅在几点到几点生效
      例如网站需要在特定时间关闭，或者启用特定策略

4、系统设置
4.1 攻击告警增加邮件告警功能
      方便更快获得攻击信息

**Comment by Lorna0** [comment]
Please search the [open issues](https://github.com/chaitin/SafeLine/issues) and [discussion](https://github.com/chaitin/SafeLine/discussions) for duplicate issue first.
Please rise only one suggestion in an issue.

**Comment by safe1ine** [comment]
中文版的需求可以直接提在 https://rivers.chaitin.cn/discussion
