### ISSUE TITLE
[Suggestion] Output the attack IPs to the firewall to block the IPs

### ISSUE THREAD

**Issue by congqian3** [chaitin/SafeLine#1008]
### What would you like to be added or improved?

> 1、增加触发高频攻击拦截的同时，联动防火墙服务器系统防火墙的Deny策略，从而达到在封禁期内彻底阻断攻击源IP对防火墙的访问；
> 2、增加自定义规则库导出导入功能（还可以考虑允许分享自定义规则）；
> 3、建议增加针对站点的数据统计功能，可以显示独立访客、独立IP明细。

Output the attack IPs to the firewall to block the IPs

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
