### ISSUE TITLE
[Bug] 数据统计-基础统计-30拦截情况无数据

### ISSUE THREAD

**Issue by congqian3** [chaitin/SafeLine#1009]
### What happened?

数据统计-基础统计-30拦截情况无数据，WAF服务器时间已确认无偏差
![微信图片_20240726121102](https://github.com/user-attachments/assets/96d56cb3-770d-42d7-a88b-c537504b0c6b)
![微信截图_20240726121048](https://github.com/user-attachments/assets/18aeea82-e3d6-4789-ab74-c129d10fd333)

**Comment by safe1ine** [comment]
这是一个bug,目前最新版本已经解决了,升级试试看
