### ISSUE TITLE
[Bug] 动态防护的容器报错，功能异常

### ISSUE THREAD

**Issue by wkeylin** [chaitin/SafeLine#1010]
### What happened?

配置动态防护功能，接口报错，并且容器也有报错
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/4d7e6790-64ce-4f7b-8d24-2e12888dc427">
```bash
cannot create regular file '/app/chaos/config.toml': No such file or directory
```

### How we reproduce?

版本: 6.3.0
功能：动态防护

### Expected behavior

动态防护功能可以正常

### Error log

```json
{"data":{},"msg":"create chaos rule failed"}
```
```bash
cannot create regular file '/app/chaos/config.toml': No such file or directory
```

**Comment by xbingW** [comment]
看下安装目录的 /data/safeline/resources/chaos 下有没有这个 config.toml

**Comment by wkeylin** [comment]
> 看下安装目录的 /data/safeline/resources/chaos 下有没有这个 config.toml

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/eab794f5-648e-4610-a2c4-ce8bf06142bb">
是有的

**Comment by wkeylin** [comment]
> ![image](https://private-user-images.githubusercontent.com/150229899/353051367-ef1bcc72-bfe3-4f4d-9635-1b93bd743d4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTcxODQsIm5iZiI6MTcyMjI1Njg4NCwicGF0aCI6Ii8xNTAyMjk4OTkvMzUzMDUxMzY3LWVmMWJjYzcyLWJmZTMtNGY0ZC05NjM1LTFiOTNiZDc0M2Q0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMjQxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjUwNGZhODcxMzk2MDcwMDJlMGIyZjVjMWIzODM5N2EwOThlMzAwN2MxN2YyM2I4YmUyOTNiODQ1OGNmMTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TyZeAQF3lulysgWm7zskH8cQDceImMcTlAklWBrXAYM) 检查下是否正确挂载了

感谢，解决了
