### ISSUE TITLE
[Suggestion] 改进切换控制台界面证书时默认自签证书的删除流程

### ISSUE THREAD

**Issue by whx61** [chaitin/SafeLine#1012]
### What would you like to be added or improved?

希望能在切换雷池控制台证书时有选项选择是否删除默认的自签证书

### Why is it needed?

在切换雷池控制台的证书时会自动把原来的默认自签证书给删掉且没有任何关于删除证书的提示，只有一个保存。。。
在需要原来证书的时候就很难受了

**Comment by safe1ine** [comment]
中文版的需求可以直接提在 https://rivers.chaitin.cn/discussion
