### ISSUE TITLE
[Suggestion] 黑白名单生效机制

### ISSUE THREAD

**Issue by Newbananl** [chaitin/SafeLine#1014]
### What would you like to be added or improved?

配置黑白名单后，无论站点是否处于“防护模式”都可生效，或在黑白名单配置处进行提示：只在“防护模式”下生效

### Why is it needed?

生产站点部署WAF后处于观察模式，需要优化调整误报规则，若是直接实施防护模式，影响业务正常运行；在观察模式验证时，发现黑白名单无效，经多次验证排查发现仅在“防护模式”下生效，页面也无特别说明，不利日常维护。

**Comment by safe1ine** [comment]
![image](https://github.com/user-attachments/assets/4aee1c26-d2fe-4cab-8e96-91e05b152d3d)
