### ISSUE TITLE
[Suggestion] 功能建设（专业版本）

### ISSUE THREAD

**Issue by tiwer** [chaitin/SafeLine#1015]
### What would you like to be added or improved?

1、人机验证、身份认证页面，希望可以自定义，不要展示雷池的LOGO及相关的信息。（专业版本）
2、动态防护-快速加解密（跳过解密页面），还是会有提示页面，也展示了雷池的LOGO及相关的信息。希望可以自定义（专业版本）
3、相关漏洞扫描器-会扫很多Nginx的漏洞，希望可以通过雷池waf来屏蔽这些漏洞。因为会被客户通报。

### Why is it needed?

1、自定义可以让客户看不到，我们用的安全防护waf是什么品牌，及安全扫描时不被发现产品类型。
2、漏洞扫描器扫出很多漏洞，会被客户单位通报处理。

**Comment by Lorna0** [comment]
Please search the [open issues](https://github.com/chaitin/SafeLine/issues) and [discussion](https://github.com/chaitin/SafeLine/discussions) for duplicate issue first.
Please rise only one suggestion in an issue.

**Comment by safe1ine** [comment]
中文版的需求可以直接提在 https://rivers.chaitin.cn/discussion

**Comment by safe1ine** [comment]
all is fixed in release 6.9.0
