### ISSUE TITLE
社区版频率限制规则

### ISSUE THREAD

**Issue by jzhao20230918** [chaitin/SafeLine#1018]
### Content

请问社区版怎么配置限制高频访问规则？只在防护日志下找到了频率限制的日志栏，但是没找到如何配规则的地方。谢谢。

**Comment by jzhao20230918** [comment]
使用的是6.3.0版本，通过在线安装脚本装的，我看文档里有配置频率限制的：
![image](https://github.com/user-attachments/assets/8bfb4d0f-fdc1-47c7-a652-c2700581c477)

但我的界面是这样的：
![1722484063484](https://github.com/user-attachments/assets/8e20399b-b691-4372-afc9-02d78eb3f885)
是我漏装了什么吗？谢谢。

**Comment by safe1ine** [comment]
在防护站点页面
![image](https://github.com/user-attachments/assets/6c8ed4e5-5748-4a76-a9da-ede33b0dcd37)
