### ISSUE TITLE
[Suggestion] 如果一个ip短时间内ua变化可以认为是恶意攻击

### ISSUE THREAD

**Issue by xiyuvi** [chaitin/SafeLine#1019]
### What would you like to be added or improved?

如果一个ip短时间内ua变化可以认为是恶意攻击，请团队考虑是否在cc防护里添加这条规则

### Why is it needed?

如果一个ip短时间内ua变化可以认为是恶意攻击，请团队考虑是否在cc防护里添加这条规则

**Comment by safe1ine** [comment]
这会严重误报，有可能是因为这个 IP 下是个大内网，有很多不同的用户。
