### ISSUE TITLE
检测日志添加日期筛选 / 按时间筛选

### ISSUE THREAD

**Issue by huangyitong** [chaitin/safeline#102]
检测日志添加日期筛选，类似如下图：
![image](https://github.com/chaitin/safeline/assets/67935454/e7edacb1-d7e8-4ed5-b556-6b6cb6733680)
![image](https://github.com/chaitin/safeline/assets/67935454/6f06bb1e-4823-48d8-96e3-d7db686830c0)
![image](https://github.com/chaitin/safeline/assets/67935454/694cb362-8ea5-45a6-a21d-94415a097b71)

**Comment by DeronW** [comment]
这个可以有

**Comment by Lorna0** [comment]
其他反馈建议中，也有提及按时间筛选的，在这里一块记录

**Comment by Lorna0** [comment]
2.3 已实现
