### ISSUE TITLE
chaitin和apisix的集成问题

### ISSUE THREAD

**Issue by jzhao20230918** [chaitin/SafeLine#1022]
### Content

根据文档 https://waf-ce.chaitin.cn/docs/practice/apisix   的描述
`curl <http://127.0.0.1:9180/apisix/admin/plugin_metadata/chaitin-waf> -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "nodes":[
     {
       "host": "192.168.99.11",
       "port": 8000
     }
  ]
}'`
已将apisix流量转发到chaitin 8000端口。
我的问题是，接下来在雷池的管理界面，添加站点的时候，监听端口该填什么？如果也填8000，会报接口已使用。
谢谢！

**Comment by jzhao20230918** [comment]
因为好像只有在 添加站点之后才能加访问频率控制之类的功能。

**Comment by safe1ine** [comment]
sdk 接入方式可以不配置站点直接使用。
频率限制功能后续我们会加入一个全局配置，最近的版本中就会发布。
