### ISSUE TITLE
新人小白请教下，雷池下方的服务器为什么叫上游服务器，是因为画架构图的时候从下向上画的吗

### ISSUE THREAD

**Issue by peakliuz** [chaitin/SafeLine#1023]

**Comment by safe1ine** [comment]
这是个行业专有名词，在 nginx 中叫做 upstream。

**Comment by HONG277** [comment]
这是相对于用户或浏览器来说，客户端是下游，当 Nginx 接收到来自下游的请求时，它会根据配置的规则将请求转发给上游服务器组中的某个服务器

**Comment by Lorna0** [comment]
“上” “下” 不是根据请求方向，而是根据资源传递的方向的来标识的。可以这样理解，网站之所以成为网站，是因为网站提供各种资源数据服务，而不是因为我们向服务器发起了请求。这些数据的传递方向就是从网站到客户端，所以网站服务器才是 “上游”，客户端才是 “下游”。

**Comment by HONG277** [comment]
> “上” “下” 不是根据请求方向，而是根据资源传递的方向的来标识的。可以这样理解，网站之所以成为网站，是因为网站提供各种资源数据服务，而不是因为我们向服务器发起了请求。这些数据的传递方向就是从网站到客户端，所以网站服务器才是 “上游”，客户端才是 “下游”。

受教了，感谢指正
