### ISSUE TITLE
tengine容器无法启动[Bug] 

### ISSUE THREAD

**Issue by DleCu** [chaitin/SafeLine#1024]
### What happened?

我是在unraid 7.0.0-beta.2版本的docker下，以compose运行的。
docker 版本信息：
Client:
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

compose环境变量：
SAFELINE_DIR=/mnt/user/appdata/SafeLine
IMAGE_TAG=latest
MGT_PORT=9443
POSTGRES_PASSWORD=xxxxxxxxxx
SUBNET_PREFIX=172.22.222
IMAGE_PREFIX=chaitin

compose文件：
networks:
  safeline-ce:
    name: safeline-ce
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: ${SUBNET_PREFIX:?SUBNET_PREFIX required}.1
          subnet: ${SUBNET_PREFIX}.0/24
    driver_opts:
      com.docker.network.bridge.name: safeline-ce

services:
  postgres:
    container_name: safeline-pg
    image: ${IMAGE_PREFIX}/safeline-postgres:15.2
    volumes:
      - ${SAFELINE_DIR}/resources/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=safeline-ce
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?postgres password required}
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.2
    command: [postgres, -c, max_connections=600]
    healthcheck:
      test: pg_isready -U safeline-ce -d safeline-ce
  mgt:
    container_name: safeline-mgt
    image: ${IMAGE_PREFIX}/safeline-mgt:${IMAGE_TAG:?image tag required}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SAFELINE_DIR}/resources/mgt:/app/data
      - ${SAFELINE_DIR}/logs/nginx:/app/log/nginx:z
    ports:
      - ${MGT_PORT:-9443}:1443
    healthcheck:
      test: curl -k -f https://localhost:1443/api/open/health
    environment:
      - MGT_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
    depends_on:
      - postgres
      - fvm
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.4
  detect:
    container_name: safeline-detector
    image: ${IMAGE_PREFIX}/safeline-detector:${IMAGE_TAG}
    volumes:
      - ${SAFELINE_DIR}/resources/detector:/resources/detector
      - ${SAFELINE_DIR}/logs/detector:/logs/detector
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_DIR=/logs/detector
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.5
  mario:
    container_name: safeline-mario
    image: ${IMAGE_PREFIX}/safeline-mario:${IMAGE_TAG}
    volumes:
      - ${SAFELINE_DIR}/resources/mario:/resources/mario
      - ${SAFELINE_DIR}/logs/mario:/logs/mario
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_DIR=/logs/mario
      - GOGC=100
      - DATABASE_URL=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.6
  tengine:
    container_name: safeline-tengine
    image: ${IMAGE_PREFIX}/safeline-tengine:${IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - ${SAFELINE_DIR}/resources/nginx:/etc/nginx
      - ${SAFELINE_DIR}/resources/detector:/resources/detector
      - ${SAFELINE_DIR}/resources/chaos:/resources/chaos
      - ${SAFELINE_DIR}/logs/nginx:/var/log/nginx:z
      - ${SAFELINE_DIR}/resources/cache:/usr/local/nginx/cache
    environment:
      - TCD_MGT_API=https://${SUBNET_PREFIX}.4:1443/api/open/publish/server
      - TCD_SNSERVER=${SUBNET_PREFIX}.5:8000
      # deprecated
      - SNSERVER_ADDR=${SUBNET_PREFIX}.5:8000
    ulimits:
      nofile: 131072
    network_mode: host
  luigi:
    container_name: safeline-luigi
    image: ${IMAGE_PREFIX}/safeline-luigi:${IMAGE_TAG}
    environment:
      - MGT_IP=${SUBNET_PREFIX}.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SAFELINE_DIR}/resources/luigi:/app/data
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - detect
      - mgt
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.7
  fvm:
    container_name: safeline-fvm
    image: ${IMAGE_PREFIX}/safeline-fvm:${IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.8
  bridge:
    container_name: safeline-bridge
    image: ${IMAGE_PREFIX}/safeline-bridge:${IMAGE_TAG}
    command:
      - /app/bridge
      - serve
      - -n
      - unix
      - -a
      - /app/run/safeline.sock
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run:/app/run
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.9
    depends_on:
      - mgt
  chaos:
    container_name: safeline-chaos
    image: ${IMAGE_PREFIX}/safeline-chaos:${IMAGE_TAG}
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    volumes:
      - ${SAFELINE_DIR}/resources/chaos:/app/chaos
    networks:
      safeline-ce:
        ipv4_address: ${SUBNET_PREFIX}.10

发生的问题：
tengine容器始终启动不了，容器和镜像删除之后重新拉取和创建也没法启动。手动重启n次都不行。

### How we reproduce?

1. ...
2. ...
3. ...

### Error log

![Uploading log.png…]()
text  error  warn  system  array  login  

2024/08/03 06:20:54 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false
nginx: [emerg] invalid IPv6 address in resolver "[fe80::4a05:e2ff:fea9:4a1b%br0]" in /etc/nginx/nginx.conf:132
2024/08/03 06:21:12 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false
nginx: [emerg] invalid IPv6 address in resolver "[fe80::4a05:e2ff:fea9:4a1b%br0]" in /etc/nginx/nginx.conf:132
2024/08/03 06:21:46 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false
nginx: [emerg] invalid IPv6 address in resolver "[fe80::4a05:e2ff:fea9:4a1b%br0]" in /etc/nginx/nginx.conf:132
2024/08/03 06:21:53 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false
nginx: [emerg] invalid IPv6 address in resolver "[fe80::4a05:e2ff:fea9:4a1b%br0]" in /etc/nginx/nginx.conf:132
2024/08/03 06:22:02 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false
nginx: [emerg] invalid IPv6 address in resolver "[fe80::4a05:e2ff:fea9:4a1b%br0]" in /etc/nginx/nginx.conf:132
2024/08/03 06:22:30 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false
nginx: [emerg] invalid IPv6 address in resolver "[fe80::4a05:e2ff:fea9:4a1b%br0]" in /etc/nginx/nginx.conf:132
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
![log](https://github.com/user-attachments/assets/ef99fa88-f81e-437f-ac44-0dfa09bee626)

[GIN-debug] Listening and serving HTTP on 127.0.0.1:65508
current region china
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /forbidden_response       --> tcd/client.ReturnForbiddenResponse (1 handlers)
[GIN-debug] GET    /acl_response             --> tcd/client.ReturnAclResponse (1 handlers)
[GIN-debug] GET    /not_found_response       --> tcd/client.ReturnNotFoundResponse (1 handlers)
[GIN-debug] GET    /offline_response         --> tcd/client.ReturnOfflineResponse (1 handlers)
[GIN-debug] GET    /bad_gateway_response     --> tcd/client.ReturnBadGatewayResponse (1 handlers)
[GIN-debug] GET    /gateway_timeout_pages    --> tcd/client.ReturnGatewayTimeoutPages (1 handlers)
[GIN-debug] GET    /auth_defense_pages       --> tcd/client.ReturnAuthDefensePages (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 127.0.0.1:65508
current region china
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /forbidden_response       --> tcd/client.ReturnForbiddenResponse (1 handlers)
[GIN-debug] GET    /acl_response             --> tcd/client.ReturnAclResponse (1 handlers)
[GIN-debug] GET    /not_found_response       --> tcd/client.ReturnNotFoundResponse (1 handlers)
[GIN-debug] GET    /offline_response         --> tcd/client.ReturnOfflineResponse (1 handlers)
[GIN-debug] GET    /bad_gateway_response     --> tcd/client.ReturnBadGatewayResponse (1 handlers)
[GIN-debug] GET    /gateway_timeout_pages    --> tcd/client.ReturnGatewayTimeoutPages (1 handlers)
[GIN-debug] GET    /auth_defense_pages       --> tcd/client.ReturnAuthDefensePages (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 127.0.0.1:65508
current region china
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /forbidden_response       --> tcd/client.ReturnForbiddenResponse (1 handlers)
[GIN-debug] GET    /acl_response             --> tcd/client.ReturnAclResponse (1 handlers)
[GIN-debug] GET    /not_found_response       --> tcd/client.ReturnNotFoundResponse (1 handlers)
[GIN-debug] GET    /offline_response         --> tcd/client.ReturnOfflineResponse (1 handlers)
[GIN-debug] GET    /bad_gateway_response     --> tcd/client.ReturnBadGatewayResponse (1 handlers)
[GIN-debug] GET    /gateway_timeout_pages    --> tcd/client.ReturnGatewayTimeoutPages (1 handlers)
[GIN-debug] GET    /auth_defense_pages       --> tcd/client.ReturnAuthDefensePages (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 127.0.0.1:65508
current region china
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /forbidden_response       --> tcd/client.ReturnForbiddenResponse (1 handlers)
[GIN-debug] GET    /acl_response             --> tcd/client.ReturnAclResponse (1 handlers)
[GIN-debug] GET    /not_found_response       --> tcd/client.ReturnNotFoundResponse (1 handlers)
[GIN-debug] GET    /offline_response         --> tcd/client.ReturnOfflineResponse (1 handlers)
[GIN-debug] GET    /bad_gateway_response     --> tcd/client.ReturnBadGatewayResponse (1 handlers)
[GIN-debug] GET    /gateway_timeout_pages    --> tcd/client.ReturnGatewayTimeoutPages (1 handlers)
[GIN-debug] GET    /auth_defense_pages       --> tcd/client.ReturnAuthDefensePages (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 127.0.0.1:65508
current region china
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /forbidden_response       --> tcd/client.ReturnForbiddenResponse (1 handlers)
[GIN-debug] GET    /acl_response             --> tcd/client.ReturnAclResponse (1 handlers)
[GIN-debug] GET    /not_found_response       --> tcd/client.ReturnNotFoundResponse (1 handlers)
[GIN-debug] GET    /offline_response         --> tcd/client.ReturnOfflineResponse (1 handlers)
[GIN-debug] GET    /bad_gateway_response     --> tcd/client.ReturnBadGatewayResponse (1 handlers)
[GIN-debug] GET    /gateway_timeout_pages    --> tcd/client.ReturnGatewayTimeoutPages (1 handlers)
[GIN-debug] GET    /auth_defense_pages       --> tcd/client.ReturnAuthDefensePages (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 127.0.0.1:65508

**Comment by HONG277** [comment]
#689 
我刚刚按照这个修改后能启动了

**Comment by DleCu** [comment]
> #689 因 docker 未知 bug 导致首次启动后界面报错 “.....invalid IPv6 address in resolver ......” 的解决办法 我刚刚按照这个修改后能启动了

感谢，按照这个方法，我删除"%"符号以及后面字符可以了。非常感谢

**Comment by DleCu** [comment]
上面的方法目前只能解决当前的tengine启动问题，一但tengine容器重新启动仍然会继续报错，还是需要手动删除/etc/resolv.conf中ipv6地址中多余的字符(每次改完之后会自己恢复)，现在有以下方案可解决上述问题：
tengine容器中会映射主机的/etc/resolv.conf文件到容器中以供自己使用，所以我们只需要把主机上的该文件，复制一份，然后手动该好ipv6地址，把这一份resolv.confg文件映射给容器使用。
不知道官方能不能给优化一下。
