### ISSUE TITLE
[Suggestion] 雷池WAF增加多IP监听功能

### ISSUE THREAD

**Issue by maskerTUI** [chaitin/SafeLine#1026]
### What would you like to be added or improved?

雷池WAF配置监听多个IP，可自由配置不同IP端口的防护规则，方便处理不同业务需要配置相同端口号的情况。

### Why is it needed?

雷池WAF防护多个业务的时候，为了安全和应用体验，业务需要在雷池和公网出口配置相同的端口，当有多个应用需要需要相同端口的时候（比如两个业务都必须使用8080端口），这样雷池WAF就需要多部署一套。在这种情况下，如果雷池能监听多个IP就好了。

**Comment by safe1ine** [comment]
对于你描述的这种情况
你在填域名的地方直接填 IP 就行。
