### ISSUE TITLE
社区版防护站点数量达到上限

### ISSUE THREAD

**Issue by muziqiu2** [chaitin/SafeLine#1027]
### Content

升级到最新版之后发现无法新增站点，提示防护站点达到上限，查看文档升级日志并没有提到防护站点数量上限，这是最近新加的规则吗？之前旧版本是可以正常添加站点的。

**Comment by safe1ine** [comment]
站点限制数量一开始就有，免费版允许创建 50 个站点。
之前有一些版本存在一些bug导致这个限制没有生效，6.3 版本修复了这个问题
