### ISSUE TITLE
[Bug] 访问非80端口时错误跳转到其他端口

### ISSUE THREAD

**Issue by 1298345095** [chaitin/SafeLine#1029]
### What happened?

内网监听端口为x，外网y端口映射到内网x端口，在内网通过网址xxx.domain.com:y访问Alist观看图片或视频时，会错误跳转到xxx.domain.com:x，导致无法正常观看。在外网访问时会错误跳转到xxx.domain.com。

**Comment by zclaiqcc** [comment]
感觉像是前端代码的问题，前端代码固定写了去 xxx.domain.com:x 来加载图片，所以不会访问 xxx.domain.com:y

**Comment by 1298345095** [comment]
> 得看你的软件是如何拼接这个朓转地址的。 有可能是根据自己 listen 的端口来拼接，也有可能是根据 Host 字段来拼接，或者通过 x-forwarded-port 之类的 Header。。 总之就是你的软件在反向代理之后把地址给拼错了，你可以看看软件的后台有没有相关的根地址的配置，大部分软件都是有这个配置的。。。
> 
> 不管再怎么说，这是反向代理的常见问题，不是雷池的 bug，issue 我关了。

根据https://github.com/alist-org/alist/issues/726等，是X-Forwarded-Host的问题，但我开启着雷池中的“传递客户端连接的 host 和协议”
