### ISSUE TITLE
日志详情里将源 IP 加入 IP 组的时候，支持直接加一个网段

### ISSUE THREAD

**Issue by Lorna0** [chaitin/safeline#103]
收集下意见，有需要的点个  👍

**Comment by luweijun1992** [comment]
可以做成添加到组的时候是一个编辑状态，如果没有需要直接确定，有时候的时候自行修改下。
网段的话，那是用 /24 还是 /16，不好定。

**Comment by DeronW** [comment]
![image](https://github.com/chaitin/safeline/assets/780596/02d26bf4-5918-4dd1-940f-fd26e9d9d776)

2.0 版本新增了这个功能
