### ISSUE TITLE
[Bug] 根据文档接入k8s后，防护似乎都失效了

### ISSUE THREAD

**Issue by Gourds** [chaitin/SafeLine#1030]
### What happened?

根据文档https://docs.waf-ce.chaitin.cn/zh/%E6%9B%B4%E5%A4%9A%E6%8A%80%E6%9C%AF%E6%96%87%E6%A1%A3/K8S-ingress-nginx%E4%B8%AD%E9%9B%86%E6%88%90%E9%9B%B7%E6%B1%A0WAF%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

修改后，原来正常的防护站点似乎都失效了，比如身份验证和加密这个，看不到雷池的页面和处理过程

detector 报错

```
[2024-08-05 16:30:34.886] [1] [INFO ] all thread shutdown
'/detector/snserver.yml' -> '/detector/detector.yml'
/resources/detector/detector.yml
'/detector/libfusion2.so' -> '/detector/config/libfusion2.so'
2024/08/07 10:47:07 ERROR wait command failed, wait to retry err="signal: hangup"

```

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by xbingW** [comment]
符合预期，请参考 https://docs.waf-ce.chaitin.cn/%E6%9B%B4%E5%A4%9A%E6%8A%80%E6%9C%AF%E6%96%87%E6%A1%A3/%E8%81%94%E5%8A%A8APISIX#%E8%AE%A9-waf-%E6%9C%AC%E8%BA%AB%E7%9A%84%E7%AB%99%E7%82%B9%E6%8B%A6%E6%88%AA%E5%90%8C%E6%97%B6%E5%B7%A5%E4%BD%9C
