### ISSUE TITLE
微信支付回调被拦截

### ISSUE THREAD

**Issue by leosun620** [chaitin/SafeLine#1031]
### What happened?

1. niginx日志显示回调请求有返回
101.226.103.15 - - [07/Aug/2024:13:04:23 +0800] "POST /prod-api/h5/hx/cupidcode/notify/order HTTP/1.1" 200 800 "-" "Mozilla/4.0" "-"
2. 但是如上请求给雷池处理后，就被丢弃了。我后端一直没有收到响应数据。同时我在雷池面板上也看不出它是否把上述的请求丢弃了。
3. 如果我把雷池改成观察者模式，那么上述问题就不会发生。
请问应该是如何解决？是我雷池配置不对，还是其他bug？
### How we reproduce?

1. ...
2. ...
3. ...

**Comment by xbingW** [comment]
nginx 日志是 waf 的还是你自己服务的

**Comment by leosun620** [comment]
1. nginx的日志是我自己的。
2. 已经解决了，是我开启人机验证，所以来自微信服务器的回调请求被雷池拦截了

> nginx 日志是 waf 的还是你自己服务的
