### ISSUE TITLE
升级后proxy_set_header Accept-Encoding ""配置丢失

### ISSUE THREAD

**Issue by qiyigang** [chaitin/SafeLine#1033]
### Content

前天从6.2升级到6.4后原来代理的nacos应用程序调用全部报错，后来废了老大劲 和以前版本的配置文件对比 发现site-enabled里站点的配置文件6.4版本没有proxy_set_header Accept-Encoding "";配置，翻了翻6.2到6.4的更新记录没有发现有相关的更新啊 。

**Comment by xbingW** [comment]
nacos 为啥不让传 Accept-Encoding  呢

**Comment by Lorna0** [comment]
relate to :
* https://github.com/chaitin/SafeLine/issues/991

**Comment by Lorna0** [comment]
这个变更是为了解决 https://github.com/chaitin/SafeLine/issues/991 中遇到的问题。可以在后台修改 nginx 配置解决。我们准备在专业版控制台上增加自定义 Header 的功能，改起来会更方便点。

**Comment by xbingW** [comment]
最新版 6.9.0 已支持修改 header
