### ISSUE TITLE
[Bug] 6.2.4版本升级至6.5.0版本intercepts接口报错

### ISSUE THREAD

**Issue by HolyGu** [chaitin/SafeLine#1036]
### What happened?

从6.2.4版本升级到6.5.0以后，登录进系统主页中间上方就会弹出“basic trend intercept failed: database disk image is malformed (11)”错误提示
![image](https://github.com/user-attachments/assets/367ed6da-1552-4505-a12b-9e6af16a6a79)
查看请求信息是/api/dashboard/intercepts接口抛出的
![image](https://github.com/user-attachments/assets/1c77ebe6-83eb-43cb-803a-70b5b6d8c81b)
且在点击主页“高级统计”功能时，页面会出现js报错
![image](https://github.com/user-attachments/assets/2ddbca91-5d09-4384-ac26-16c6f0a09831)
![image](https://github.com/user-attachments/assets/7b426864-2b2c-4124-9b76-9ed316c62d6a)

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by Lvshujun0918** [comment]
尝试先停止并删除已有docker，删除本地镜像，但保留安装目录重新装一遍

**Comment by HolyGu** [comment]
> 尝试先停止并删除已有docker，删除本地镜像，但保留安装目录重新装一遍

尝试过删除所有容器和镜像，保留目录使用安装脚本安装会提示目录存在，使用升级脚本重装后问题依旧

**Comment by safe1ine** [comment]
这报错是 luigi 依赖的 sqlite 数据库损坏了, 里面存的是雷池首页的统计信息, 不需要的话可以把 sqlite 文件删除以后重启容器
