### ISSUE TITLE
[Suggestion] 建议将通过人机验证的IP记录到系统中，该IP在访问其它站点时跳过人机验证环节

### ISSUE THREAD

**Issue by ligongfu** [chaitin/SafeLine#1038]
### What would you like to be added or improved?

建议将通过人机验证的IP记录到系统中，该IP在访问其它站点时跳过人机验证环节。能够共享到云端就更好了。

### Why is it needed?

重复进行人机验证影响用户体验

**Comment by safe1ine** [comment]
这么做是有安全风险的。
人机验证目前是基于 session 进行的，IP 的重要参考条件，但不是主要决定因素。
有的 IP 出口是多人共享的，大一点的出口甚至有成千上万人公用同一个 出口 IP。

不能因为有一个人的人机验证通过了就无条件相信这个 IP 的所有行为
