### ISSUE TITLE
[Suggestion] 希望可以根据达到限制的qps数/请求数来开启人机验证

### ISSUE THREAD

**Issue by Gaimoydev** [chaitin/SafeLine#1039]
### What would you like to be added or improved?

希望可以根据达到限制的qps数/请求数来开启人机验证
自动开盾 总是开盾又觉得影响用户体验
也可以添加先无感验证然后检测阈值超过就切换为人机验证
建议多添加几种人机验证模式

### Why is it needed?

服务器被cc后速率限制起到的作用不够

**Comment by safe1ine** [comment]
默认不就是你想要的效果么。

![image](https://github.com/user-attachments/assets/448cada9-64e8-4b58-9848-02bcd8b9cda5)
