### ISSUE TITLE
支持暗色模式

### ISSUE THREAD

**Issue by Lorna0** [chaitin/SafeLine#104]
收集下意见，期望加的点个 👍

**Comment by DeronW** [comment]
多主题做起来太麻烦了

**Comment by luweijun1992** [comment]
刚想发Issues，发现已经有了。
习惯所有都是Dark模式了。最近两次新版本一下子全白，好不习惯啊。

+1

**Comment by colaone** [comment]
+1

**Comment by DeronW** [comment]
以目前按周迭代的速度来看，功能和稳定性在现在的阶段重要性更高，主题色的支持更适合在 UI 相对稳定的阶段实现，而且实际上颜色的设计，尤其是数据展示的配色上，深色的对比度比浅色的对比度的调色更复杂一些。人力有限的情况下，花时间在 UI 上得到的回报，比不上花时间在功能上。毕竟现在本来用户还不多，一个 bug 引起的用户流失，靠再优雅的颜色也拉不回来。

所以，大家换一个功能类的想法，更容易实现。

**Comment by PoisonGZ** [comment]
+1

**Comment by Lorna0** [comment]
@colaone @PoisonGZ @luweijun1992 提示下在评论里 +1 是无法被统计到的。

**Comment by safe1ine** [comment]
专业版应该要有黑金暗色模式了
