### ISSUE TITLE
如何设置自定义IP组的更新时间？或者如何用命令行更新IP组？

### ISSUE THREAD

**Issue by clion007** [chaitin/SafeLine#1040]

**Comment by safe1ine** [comment]
6.6.0 版本开放了 api token，可以自己调 API 来实现 
![image](https://github.com/user-attachments/assets/a95a8d2e-1de1-40c0-9df2-95006c8ef028)

**Comment by clion007** [comment]
能说详细一点吗？具体如何调用？
