### ISSUE TITLE
[Feature] supports multi files uploading when serve a web service as static files

### ISSUE THREAD

**Issue by wu-sv** [chaitin/SafeLine#1043]
### What would you like to be added or improved?

supports multi files uploading when serve a web service as static files

### Why is it needed?

It is very troublesome to upload every time you want to update the file.

**Comment by safe1ine** [comment]
that's good, we will implement it

**Comment by safe1ine** [comment]
you can just operate files by ssh, statis files sit at {safeline}/resources/nginx/static/static_{site_id}

**Comment by Lorna0** [comment]
you can upload a zip file and choose 'Unzip and overwrite the current directory' now:
![image](https://github.com/user-attachments/assets/ef96de07-725d-4895-a40e-23f46281b3d7)
