### ISSUE TITLE
[Suggestion]  国际化（I18N）什么时候支持

### ISSUE THREAD

**Issue by ZhiweiWu0425** [chaitin/SafeLine#1044]
### What would you like to be added or improved?

提供第三方语言（如越南文）的公开仓库，（如json，yaml语言包），官方可不翻译成第三方，由开发者贡献第三方语言。
翻译的完整度不强制，对于漏翻译或者软件升级的新翻译，以官方维护的英文为准，使用者发现漏翻译的可以慢慢提交完善。
推荐使用[crowdin](https://crowdin)，或者专门的一个github仓库存放语言包
![image](https://github.com/user-attachments/assets/4fcde64e-863e-48dc-b9b1-4addb612a984)

### Why is it needed?

非英文的朋友不了解中文和英文，放弃使用。想让国际化更广泛需要考虑语言的扩展功能

**Comment by safe1ine** [comment]
暂时（短期内）不会考虑开放自定义 i18n。

原因是除了管理员控制台以外，还涉及很多模块要一起跟着改造才能实现有效的国际化
- 不同地区会连接不同的云服务，云服务也要一起跟着做翻译
- nginx 内置的拦截页面也要跟着做翻译
- AI 主助手也要跟着一起做翻译

目前雷池的标准版本提供了中文版和英文国际版，海外用户可以考虑试用国际版。
