### ISSUE TITLE
[Bug] 申请二级域名免费证书失败

### ISSUE THREAD

**Issue by wuxiaoxuna** [chaitin/SafeLine#1046]
### What happened?

添加证书报错提示这个，请问一下要怎么解决啊，目前的雷池版本是最新的，前两天刚拉取的最新的镜像，二级域名xxx.xxx.top也能ping的通  error: one or more domains had a problem: [xxx.xxx.top] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: xx.xx.xx.xx: Invalid response from http://xxx.xxx.top/.well-known/acme-challenge/xxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxx: 403

**Comment by safe1ine** [comment]
```
Invalid response from http://xxx.xxx.top/.well-known/acme-challenge/xxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxx: 403
```

这是 acme 失败了。。
你的域名是不是没有指向雷池。

**Comment by wuxiaoxuna** [comment]
雷池和其他服务都是在一个服务器上的，我创建了几个二级域名，已经有一个二级域名去申请这个免费证书成功了，雷池本身也成功通过这个申请免费证书成功的二级域名代理出来了，但是我是想代理其他服务的时候，再去用另外的二级域名去申请免费证书就失败了。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
