### ISSUE TITLE
[Feature] supports auto migration or clean logs

### ISSUE THREAD

**Issue by rainpaper-bs** [chaitin/SafeLine#1047]
### What would you like to be added or improved?

攻击日志当前不能删除，应该可以让用户设置保留几天前的日志，比如保留14天，就自动删除14天前的日志

### Why is it needed?

这样可以节省数据库空间，提高运行效率，频繁攻击日志都刷爆了

**Comment by safe1ine** [comment]
最新版已经支持这个功能了。
![image](https://github.com/user-attachments/assets/726d8fca-059e-4f2c-ab7f-2a90d19dd2fa)
