### ISSUE TITLE
[Suggestion] 'Serve as Static Files' Allow Vue Router History mode / 静态文件搭建网站支持 Vue history 的路由模式

### ISSUE THREAD

**Issue by wu-sv** [chaitin/SafeLine#1049]
### What happened?

在 Vue router 中使用 history 模式时，刷新页面可能会导致 404 错误。这是因为在 history 模式下，Vue 路由器通过修改浏览器的历史记录来实现路由切换，但是当用户直接访问某个 URL 时，服务器端没有相应的处理逻辑，于是就会返回 404。

### How we reproduce?

创建一个路由模式为history的vue项目，打包后放到静态页面，主页面能正常访问，但是其他页面全都为404

### Expected behavior

添加配置：try_files $uri $uri/ /index.html;

**Comment by Lorna0** [comment]
看起来这个配置需要根据业务开启，只有对应的单页面应用才启用。需要做个功能开关。
