### ISSUE TITLE
[Bug] Wrong Display of region

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#1051]
### What happened?

如图，台湾省不知道为何在后面显示了undefined
![Screenshot_20240821_134922](https://github.com/user-attachments/assets/0cafcd21-25d2-4d83-89f9-3545c7f496ef)

### How we reproduce?

在最新版本6.6.1中台湾IP即可复现

**Comment by awesomeYG** [comment]
3q！we will fix it in next version

**Comment by Lvshujun0918** [comment]
已修复

**Comment by Lvshujun0918** [comment]
但希望在显示上能够再优化显示为“中国-xx省”，毕竟国外IP属地只显示到国家，中国显示到省，把两者并列有些奇怪

**Comment by Lorna0** [comment]
> 但希望在显示上能够再优化显示为“中国-xx省”，毕竟国外IP属地只显示到国家，中国显示到省，把两者并列有些奇怪

主要考虑中文版大部分是国内流量，隐藏 “中国” 界面整洁一些。英文版两者是对齐的，都显示到国家。
