### ISSUE TITLE
[Bug] 全局配置：“代理时修改请求中的 Host 头”，在保存时报错：invalid host $http_host:$server_port

### ISSUE THREAD

**Issue by xxdahai** [chaitin/SafeLine#1054]
### What happened?

![image](https://github.com/user-attachments/assets/e3d344f2-73ed-4a7d-bdeb-f4932cb3d41b)

想要实现：host:port ，报错。

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by safe1ine** [comment]
首先，这里不支持输入变量，带 $ 的字符串被禁用了，这并不是 bug。。。。

其次，Host 的值本来就是 host:port，不用修改
