### ISSUE TITLE
[Bug] Wrong Tip Word

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#1055]
### What happened?

![Screenshot_20240827_171657](https://github.com/user-attachments/assets/97ca12f2-dc87-44b8-83de-acd680f15c13)
这里应该是“访问”而非“攻击”，来自高频日志

### How we reproduce?

1. 最新版本出发高频访问即可复现

**Comment by safe1ine** [comment]
中文版的需求可以直接提在 https://rivers.chaitin.cn/discussion

**Comment by safe1ine** [comment]
has fixed in release 6.9.0
