### ISSUE TITLE
[Bug] 从5.4.x升级到6.7.0后，控制台全部变成英文了

### ISSUE THREAD

**Issue by fslongjin** [chaitin/SafeLine#1057]
### What happened?

从5.4.x升级到6.7.0后，控制台从中文全部变成英文了，我应该怎么修改语言？

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by safe1ine** [comment]
那你是装错版本了，你之前装的是国际版吧。。。。
6.0.0 以后国际版不在提供中文翻译功能了。。

你跑一遍中文版的升级命令就能回到中文版。
https://docs.waf-ce.chaitin.cn/zh/%E4%B8%8A%E6%89%8B%E6%8C%87%E5%8D%97/%E5%8D%87%E7%BA%A7%E9%9B%B7%E6%B1%A0

**Comment by mosuzi** [comment]
似乎把 `/data/safeline/.env` 文件里的 `REGION=-g` 改为 `REGION=` 也可以。我的服务器无法执行中文版脚本里的下载命令，只能装国际版
