### ISSUE TITLE
[Suggestion]  希望后期支持 aarch64 平台

### ISSUE THREAD

**Issue by wuuyun** [chaitin/SafeLine#1058]
### What would you like to be added or improved?

希望后期支持 aarch64 平台

### Why is it needed?

希望后期支持 aarch64 平台

**Comment by safe1ine** [comment]
中文版的需求可以直接提在 https://rivers.chaitin.cn/discussion

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/56
