### ISSUE TITLE
升级到6.7.0以后，部分功能异常，以下是截图

### ISSUE THREAD

**Issue by xxdahai** [chaitin/SafeLine#1059]
### Content

![屏幕截图 2024-08-29 125400](https://github.com/user-attachments/assets/4c86035d-72d6-4bb0-837e-1caff5282f9f)
![屏幕截图 2024-08-29 125654](https://github.com/user-attachments/assets/b2a3a4dd-93d0-4d3d-b5a9-65d58d107c3e)
![屏幕截图 2024-08-29 125817](https://github.com/user-attachments/assets/6c70be56-ed80-4603-87d8-62bbd95b027f)
![屏幕截图 2024-08-29 130115](https://github.com/user-attachments/assets/e1400258-3da2-4935-b342-51d266b6518f)
![屏幕截图 2024-08-29 125952](https://github.com/user-attachments/assets/8b68c1e1-7bc2-4e82-938c-424d214bb5a7)

**Comment by xbingW** [comment]
升级到 6.8.0 再看下

**Comment by xxdahai** [comment]
6.8.0没有以上的问题了
