### ISSUE TITLE
代理 结构是 http://ip/url  无法直接代理访问。只能代理http://ip

### ISSUE THREAD

**Issue by yanggeya** [chaitin/SafeLine#1060]
### What would you like to be added or improved?

代理 结构是 http://ip/url  无法直接代理访问。只能代理http://ip.
例如真实业务http://1.1.1.1/admin
代理ip 2.2.2.2 或者2.2.2.2/admin 都无法代理到真实业务。

### Why is it needed?

真实业务只能通过IP加路径访问 ，直接IP无法访问业务

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/792
