### ISSUE TITLE
[Suggestion] 请问可以支持CORS设置吗？

### ISSUE THREAD

**Issue by willow-god** [chaitin/SafeLine#1061]
### What would you like to be added or improved?

您好，尊敬的开发者，请问可以支持CORS设置吗？

### Why is it needed?

由于需要接入到雷池，我并没有设置宝塔面板自带的nginx，所以也没有设置CORS，近期发现一个项目需要CORS保证安全，但是由于项目本身的局限性，只能设置一个地址，请问可以添加一个CORS的设置吗？我想用雷池NGINX的CORS接管项目自带的防跨域设置来达到多个防跨域安全地址的目的，如果还有防盗链设置就更好啦！

**Comment by safe1ine** [comment]
中文版的需求可以直接提在 https://rivers.chaitin.cn/discussion

**Comment by safe1ine** [comment]
release 6.9.0 support set http header with safeline
