### ISSUE TITLE
[Bug] 网页跳转的时候总是会把nginx的端口泄露出来

### ISSUE THREAD

**Issue by 08Tang** [chaitin/SafeLine#1062]
### What happened?

网页跳转的时候总是会把nginx的端口泄露出来，本来是443到雷池然后到7443的nginx服务器，里面有个网页跳转比如"/admin"，然后变成了"7443/admin"，真的很难受

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by safe1ine** [comment]
这个得看你的服务器是如何实现朓转代码的。。

大概率是从 `Host` 头里取的地址，这种情况可以直接在雷池的站点高级配置里修改 Host 的传递信息。

**Comment by safe1ine** [comment]
另外，中文版的需求可以直接提在这里 https://rivers.chaitin.cn/discussion
