### ISSUE TITLE
[Bug] 自动清理 30 天前的防护日志和统计数据功能没办法关闭

### ISSUE THREAD

**Issue by kingru005511** [chaitin/SafeLine#1064]
当你将勾选去掉以后
![image](https://github.com/user-attachments/assets/a5c8db2b-ebd3-4f20-af31-52fcae7dacba)

F5刷新页面，就会发现他又自动启动了
![image](https://github.com/user-attachments/assets/632f20fd-923c-41a8-9e7c-09ebdf7253e4)

此功能的关闭好像有点问题，没法关闭

**Comment by safe1ine** [comment]
收到，感谢反馈。。

**Comment by safe1ine** [comment]
另外，中文版的需求建议提到 https://rivers.chaitin.cn/discussion

**Comment by safe1ine** [comment]
has fixed in release 6.9.0
