### ISSUE TITLE
[Bug] 开启了监听ipv6协议导致ipv4无法访问

### ISSUE THREAD

**Issue by X142150** [chaitin/SafeLine#1065]
### What happened?

![image](https://github.com/user-attachments/assets/bfad24bf-09e4-4e90-a152-6c2a481f8ac0)
在设置开启了监听ipv6之后 出现了一个bug
能使用pv6访问面板和站点的情况下 ipv4无法访问站点和面板了 ipv4可以ping通
在ipv4正常访问的情况下 ipv6无法访问 暂时不知道两种情况怎么切换

### How we reproduce?

1. ...打开监听ipv6
2. ...使用ipv6访问面板
3. ...再使用ipv4访问面板

### Expected behavior

两者都可以访问

### Error log

![image](https://github.com/user-attachments/assets/452e26bd-3c9d-47e5-8761-e34f39f7e395)
![image](https://github.com/user-attachments/assets/171f32c3-9bbb-415b-b953-c68188a87aa4)
![image](https://github.com/user-attachments/assets/06113a0d-187a-4f4a-ac4f-4831958b09c4)
可以ping通雷池的ipv4

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
