### ISSUE TITLE
[Bug] https://chaitin.cn/dev/go/errors?go-get=1: 404 Not Found

### ISSUE THREAD

**Issue by LSunQQ** [chaitin/SafeLine#1066]
### What happened?

运行management目录下的makefile报错

### How we reproduce?

1. cd management
2. make

### Error log

api/detectlog.go:11:2: unrecognized import path "chaitin.cn/dev/go/errors": reading https://chaitin.cn/dev/go/errors?go-get=1: 404 Not Found
api/detectlog.go:17:2: unrecognized import path "chaitin.cn/dev/go/log": reading https://chaitin.cn/dev/go/log?go-get=1: 404 Not Found

**Comment by xbingW** [comment]
这个是内部依赖，无法安装
