### ISSUE TITLE
[Bug] nginx illegal config file

### ISSUE THREAD

**Issue by fred913** [chaitin/SafeLine#1068]
### What happened?

When creating a new site the request failed showing the following error message:

```
nginx: [emerg] cannot load certificate \"/etc/nginx/certs/cert_7.crt\": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/certs/cert_7.crt, r) error:10000080:BIO routines::no such file)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n: exit status 1
```

### How we reproduce?

1. try to create a new website: type the domain, and open the "SSL certs" dropdown
2. see there's a link to create certificates? click on it and then create a certificate
3. go back to the website creation page, click on the "ssl certs" dropdown again

Now the new cert shows. Choose it and create the website. It failed in my case showing the error message above.

### Expected behavior

have the website created

**Comment by xbingW** [comment]
run `/data/safeline/resources/reset_tengine`, then retry it

**Comment by fred913** [comment]
problem solved by manually removing the two retired tengine configuration files
