### ISSUE TITLE
[Bug] nginx: [emerg] invalid number of arguments

### ISSUE THREAD

**Issue by LSunQQ** [chaitin/SafeLine#1070]
### What happened?

![Snipaste_2024-09-15_11-46-55](https://github.com/user-attachments/assets/85e71feb-383a-4e4f-ade7-e66dcde4b030)

### How we reproduce?

1. 防护模块中的站点管理
2. 添加站点后报错

### Error log

nginx: [emerg] invalid number of arguments in "server" directive in /etc/nginx/sites-enabled/IF_backend_2:5 nginx: configuration file /etc/nginx/nginx.conf test failed : exit status 1

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
