### ISSUE TITLE
[Bug] mgt容器的ip组任务报错和luigi健康检测报错

### ISSUE THREAD

**Issue by clion007** [chaitin/SafeLine#1072]
### What happened?

更新到6.9.0版本后，发现mgt容器的日志中存在ip组任务报错，但是不知道为什么在管理面板中IP组的默认两个IP的更新时间又是更新了的，而自定义的IP组好像不会自动更新。同时发现，mgt日志中，有luigi容器的健康检测报错。

### Error log
2024/09/17 00:37:42 [INFO] luigi/luigi.go:101 wait luigi healthy Get "http://safeline-luigi/api/ping": dial tcp *.*.*.*:80: connect: connection refused
2024/09/17 01:00:00 [ERROR] ipgroup/ip_group.go:53 Get "": unsupported protocol scheme ""
2024/09/17 01:00:00 [ERROR] ipgroup/ip_group.go:53 Get "": unsupported protocol scheme ""
2024/09/17 01:00:00 [ERROR] cron/ip_group_info.go:33 get ip_group 1 failed: Get "": unsupported protocol scheme ""
2024/09/17 01:00:00 [ERROR] ipgroup/ip_group.go:53 Get "": unsupported protocol scheme ""
2024/09/17 01:00:00 [ERROR] cron/ip_group_info.go:33 get ip_group 5 failed: Get "": unsupported protocol scheme ""
2024/09/17 01:00:00 [ERROR] ipgroup/ip_group.go:53 Get "": unsupported protocol scheme ""
2024/09/17 01:00:00 [ERROR] cron/ip_group_info.go:33 get ip_group 6 failed: Get "": unsupported protocol scheme ""

**Comment by xbingW** [comment]
问题反馈请移步到 https://rivers.chaitin.cn/discussion
