### ISSUE TITLE
[Suggestion] 希望增加检测到扫描器攻击，自动拦截和阻断攻击的功能

### ISSUE THREAD

**Issue by clion007** [chaitin/SafeLine#1078]
### What would you like to be added or improved?

希望增加在检测到服务器正在遭受扫描器攻击时，自动进行拦截和阻断进一步攻击，比如自动要求攻击IP进行人机验证。

### Why is it needed?

我发现一个问题，在默认不开人机验证的情况下，WAF即便检测到了有IP在进行扫描器攻击，也不会采取任何行动来阻止攻击，哪怕是自动让这个IP进行人机验证都没有，建议是不是应该增加一个这样的功能。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
