### ISSUE TITLE
6.7.0及以上版本与阿里云CLB兼容性问题

### ISSUE THREAD

**Issue by Sven133** [chaitin/SafeLine#1079]
### Content

从6.6.1升级6.7.0及以后版本，会与阿里云CLB负载均衡有兼容性问题，经过排查发现，在CLB监听配置中，只要开启监听端口的健康检查，就导致CLB与WAF连接存在异常情况。白名单添加HEAD请求+CLB回源网段100.64.0.0/10，及调试其他配置均无法解决。而低于6.7.0以下版本则不存在此问题。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
