### ISSUE TITLE
IP can remove duplicates

### ISSUE THREAD

**Issue by dggvps1** [chaitin/SafeLine#1080]
### What would you like to be added or improved?

![image](https://github.com/user-attachments/assets/f2bfd4ea-c931-4a2f-95ae-3ac172eaba0d)

### Why is it needed?

Remove duplicate IPs and add the number of interceptions to rank them, making it easy to add IPs to IP groups.

**Comment by xbingW** [comment]
需求建议移步 https://rivers.chaitin.cn/discussion?rc=BROLVA7K37F74FM6KTVTNK5ADURC6CIL&sort=new
