### ISSUE TITLE
[Suggestion] 可否增加关闭上游检测的开关选项

### ISSUE THREAD

**Issue by ygrdsj** [chaitin/SafeLine#1081]
### What would you like to be added or improved?

可否增加关闭站点上游服务器健康检测的选项，或者提供修改配置文件方式关闭上游站点健康检测

### Why is it needed?

平白增加网站日志量和系统资源

**Comment by xbingW** [comment]
需求建议移步 https://rivers.chaitin.cn/discussion?rc=BROLVA7K37F74FM6KTVTNK5ADURC6CIL&sort=new
