### ISSUE TITLE
[Suggestion] 纯ipv6服务器无法更新ip组

### ISSUE THREAD

**Issue by bestzyq** [chaitin/SafeLine#1082]
### What would you like to be added or improved?

建议增加对纯ipv6服务器的支持

### Why is it needed?

在ipv6普及的大背景下，支持纯ipv6服务器还是很有需要的，非常感谢

**Comment by xbingW** [comment]
需求建议移步论坛 https://rivers.chaitin.cn/discussion?rc=BROLVA7K37F74FM6KTVTNK5ADURC6CIL&sort=new
