### ISSUE TITLE
[Bug] 当后端多个域名的时候，代理到其中一个https域名ssl证书有问题

### ISSUE THREAD

**Issue by lyy910203** [chaitin/SafeLine#1083]
### What happened?

当我后面是另外一个https域名的时候
我代理的时候发现proxy_ssl_name是$host导致后端服务无法拿到正确https证书

![image](https://github.com/user-attachments/assets/3f18afbe-db60-4ce1-9e4a-0360c6964d20)

### How we reproduce?

1. ...
2. ...
3. ...

### Expected behavior

更改proxy_ssl_name为后端ssl的域名后正常

### Error log

2024/10/10 15:16:31 [error] 34#0: *28 SSL_do_handshake() failed (SSL: error:0A000410:SSL routines::ssl/tls alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 27.10.200.75, server: _, request: "GET / HTTP/1.1", upstream: "https://3.168.86.69:443/", host: "120.25.146.165:38080"

**Comment by xbingW** [comment]
证书在 waf 上配置就行了，上游走 http
