### ISSUE TITLE
[Suggestion] 证书文件命名可否规范或者自定义

### ISSUE THREAD

**Issue by ZTfred** [chaitin/SafeLine#1084]
### What would you like to be added or improved?

![image](https://github.com/user-attachments/assets/4d158476-0d60-482e-a230-b062407ab74d)
真实l落盘的证书文件，看着都是随机字符串加域名命名的，可否直接用真实域名信息，取消随机字符串，或者改为上传日期

### Why is it needed?

waf默认支持的自签证书，网站程序都是打包好的，暂时不支持文件验证，目前需要结合其他证书续签工具，续签后手动覆盖waf上的真实证书，实现证书续签。
目前waf上的证书文件，无法判断哪些是在用的，看下这块是否可以优化一下，或者是否可以开放接口进行调用上传证书

**Comment by xbingW** [comment]
7.2.3 版本支持接口方式上传了
