### ISSUE TITLE
[Suggestion] 2fa question

### ISSUE THREAD

**Issue by rolikeusch** [chaitin/SafeLine#1086]
### What would you like to be added or improved?

not sure where I should place this question. but when I enable 2fa i always see this message after login with username/password. what is the reason for this?

<img width="554" alt="Screenshot 2024-10-18 at 18 50 09" src="https://github.com/user-attachments/assets/a3fb9182-59c6-4661-838b-222126e0d1d3">

<br><br>
I think it would be enough if this came up:

<img width="572" alt="Screenshot 2024-10-18 at 18 50 25" src="https://github.com/user-attachments/assets/6ca62447-6bc6-41be-9b56-6ac1aaf21239">

### Why is it needed?

not sure if I don't not understand the workflow

**Comment by xbingW** [comment]
This is a bug, we will fix it soon

**Comment by xbingW** [comment]
What version do you have? The latest version 7.2.3 has fixed this problem.
