### ISSUE TITLE
[Bug] qq里打开链接无法跳转网站，显示正在调试

### ISSUE THREAD

**Issue by James904141** [chaitin/SafeLine#1087]
### What happened?

其他浏览器都可以正常打开，就是qq里打开后无法跳转
https://github.com/user-attachments/assets/2c7d8cdd-ccc2-442c-8b0f-1e37a90ceaa8

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by safe1ine** [comment]
这个问题已经解决了
