### ISSUE TITLE
关联微信公众号进行攻击告警提示

### ISSUE THREAD

**Issue by Badboyswxl** [chaitin/SafeLine#109]
我觉得应该关联公众号做一些事情：
1：攻击消息提醒，这个提醒不需要每次攻击都需要提醒，比如频繁或者一个时间节点内多次攻击等；
2：根据攻击类型进行提醒；
3：等等。
这样既关注了公众号又让用户收到了提醒，百利而无一害。

**Comment by Lorna0** [comment]
浅研究了一下，微信公众号定向推送消息的话，需要完成微信号的认证，后者需要有个域名接收微信的认证消息（也合理），没办法在本地的雷池社区版实现。

目前想到的办法是关联长亭百川云平台（https://rivers.chaitin.cn/ ），因为百川支持公众号通知。大致流程是：
1. 管理员注册百川账号，在百川上配置微信公众号通知
2. 管理员把百川账号的 token 配到本地的 waf
3. waf 检测到攻击后，发信到百川，百川触发微信公众号通知

可能会有点麻烦，而且需要百川平台进行一些适配开发。大家觉得能接受的话可以点赞讨论下。

**Comment by chenvd** [comment]
或者能支持web hook，通过别的系统来完成通知

**Comment by YongJie-Xie** [comment]
提几个关键词，钉钉机器人，企业微信，飞书，邮件

**Comment by nixingshiguang** [comment]
只要支持webhook以及自定义请求头和请求体，就可以让用户自己实现很多推送方式，例如企业微信机器人/电报等，希望未来可以下放到社区版

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
