### ISSUE TITLE
[Suggestion] 在站点防护的身份认证中，这个密码能否支持设置TOTP的6为验证码作为密码

### ISSUE THREAD

**Issue by Firfr** [chaitin/SafeLine#1092]
### What would you like to be added or improved?

在站点防护的身份认证中，这个密码能否支持设置单独的TOTP的6为验证码作为密码？

### Why is it needed?

这样可以避免密码太复杂不好记忆，且TOTP每30秒变换一次的验证码也足够安全

**Comment by xbingW** [comment]
功能建议移步论坛 https://rivers.chaitin.cn/discussion
