### ISSUE TITLE
防护站点很多，希望优化管理界面

### ISSUE THREAD

**Issue by huangyitong** [chaitin/safeline#110]
防护站点界面优化：
1.【域名】可以添加排序（升序/降序方式）
2.【今日访问/拦截量】可以添加排序（根据数值大小）
3.【添加站点】旁边添加一个【刷新】按钮，可以手动刷新内容
4.【添加站点】旁边添加一个搜索框，可以快速定位某个域名

**Comment by DeronW** [comment]
你的业务场景下添加了多少个 “站点”？ 已经需要搜索或刷新才能检索了吗？

**Comment by dhfsqxz** [comment]
顶一个
说下我们的需求
本身我们是一个开发团队，每个人都有多个自己的域名，只是为了测试使用
每个域名的访问量都非常小，但是最终域名量很大
不支持自定义排序就有点难受

**Comment by Lorna0** [comment]
2.1 版本已发布，站点列表可以按照域名、端口、今日访问量进行排序了。通过排序能快速找到定位到访问量最大的站点，和特定域名、端口的站点，应该能提升不少大量站点的管理体验。

刷新和搜索，因为每页可以显示 100 个站点，所以 200 个内应该都还能直接浏览器刷新和搜索，师傅们先将就用用。

其实我们原来设想中，站点配置好就不怎么会改，所以列表没有考虑加太多功能，保证界面简洁。可能是因为现在站点列表承载了一点统计能力（今日访问/拦截），所以师傅们想多加一些管理功能。之后我们也综合考虑一下怎么优化。这边先关闭，师傅们有想法可以再评论或者建 issue。
