### ISSUE TITLE
[建议] 出一个证书夹功能 / 证书管理

### ISSUE THREAD

**Issue by lbroot** [chaitin/SafeLine#111]
有些站点是共用的一个Wildcard通配符证书，有个证书夹直接选已保存的证书就行了，不用一个个复制粘贴/上传。而且，更重要的，更换新证书的时候只要到证书夹里更新一次对应的证书就可以啦，不用重复操作。

**Comment by naocanmonster** [comment]
支持

**Comment by luweijun1992** [comment]
+1
证书管理，然后防护站点关联绑定对应证书。

**Comment by nmgliangwei** [comment]
+1

**Comment by jobsgxx** [comment]
建议出个证书夹，增加站点可以直接引用

**Comment by dossec** [comment]
+1

**Comment by D0n9** [comment]
希望有证书过期前 x 天提醒

**Comment by dossec** [comment]
建议增加证书管理模块，集中管理证书，里面可以导入已有的证书，并显示过期时间，在域名配置里可以增加一个证书绑定的选项

**Comment by Lorna0** [comment]
3.1 版本已支持
