### ISSUE TITLE
[Suggestion] 格局能不能再大点？Could you be any more narrow-minded?

### ISSUE THREAD

**Issue by simplove** [chaitin/SafeLine#1117]
### What would you like to be added or improved?

雷池 WAF 社区免费版明确禁止用于商业用途
用得好自然会付费，还开通举报邮箱，可真有你们的。
就冲这点，打死不会用你们的。
想赚钱不是你们这么搞的

The free community version of LeiChi WAF explicitly prohibits commercial use. If it works well, people will naturally pay for it, but opening a reporting email? That’s something else. Just for this reason, I’ll never use your product. If you want to make money, this is not the way to do it.

### Why is it needed?

雷池 WAF 社区免费版明确禁止用于商业用途
用得好自然会付费，还开通举报邮箱，可真有你们的。
就冲这点，打死不会用你们的。
想赚钱不是你们这么搞的

The free community version of LeiChi WAF explicitly prohibits commercial use. If it works well, people will naturally pay for it, but opening a reporting email? That’s something else. Just for this reason, I’ll never use your product. If you want to make money, this is not the way to do it.

**Comment by Lorna0** [comment]
雷池社区版禁用的是侵害长亭软件研发版权、商标和知识产权的商业行为，它们不仅会危害普通的用户，还会阻碍软件产业的持续创新。这类行为在官方免费版使用协议中有明确陈述：https://docs.waf-ce.chaitin.cn/zh/%E4%B8%8A%E6%89%8B%E6%8C%87%E5%8D%97/%E4%BD%BF%E7%94%A8%E5%8D%8F%E8%AE%AE

如果你认为可以和我们达成官方合作，欢迎与我们联系。

**Comment by ct-jaryn** [comment]
欢迎大家使用社区版，有条件的企业推荐购买专业版。
详情查看雷池商用参考文档：https://docs.waf-ce.chaitin.cn/zh/%E4%B8%8A%E6%89%8B%E6%8C%87%E5%8D%97/%E4%BD%BF%E7%94%A8%E5%8D%8F%E8%AE%AE
如有疑问，社区群内咨询群主
