### ISSUE TITLE
[Suggestion] ARM版本能否免费使用 Can the ARM version be used for free

### ISSUE THREAD

**Issue by 1ctrl-cv** [chaitin/SafeLine#1119]
### What would you like to be added or improved?

如题
As the title

树莓派用户两眼一黑
装完发现还得买授权才能用
Raspberry Pi users fainted
After installation, I found it was found that authorization is required to use it

### Why is it needed?

我认为这很有用
I think this is very useful

**Comment by devhaozi** [comment]
免费用了他卖啥，哈哈。

现在连免费版都不给商用了，建议换别的waf。

**Comment by ct-jaryn** [comment]
arm版本比较特殊，目前策略是商用，后续可能会调整，想要体验可以换一个系统～
如有疑问，社区群内咨询群主
