### ISSUE TITLE
希望新增一个功能对所有访问进行展示

### ISSUE THREAD

**Issue by hope-li279** [chaitin/safeline#112]
目前检测日志只记录可疑日志，希望后续能有一个可选功能给予我们对全部日志进行记录及展示

**Comment by zclaiqcc** [comment]
可以基于 nginx access log 自己 DIY 一下

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/safeline/issues/145

145 下面的点赞和评论多一些，集中到那边讨论吧。
