### ISSUE TITLE
许可证问题，建议大家迁移用替代款

### ISSUE THREAD

**Issue by hale177** [chaitin/SafeLine#1121]
### What would you like to be added or improved?

恶心的许可证，哪怕你限制开源能配置的防护 site 数量也行，直接不给用 
建议大家迁移到  https://github.com/samwafgo/SamWaf/blob/main/README_ch.md，

我生产部署跑了2周，大差不差，挺好用的。

### Why is it needed?

nothings

**Comment by hale177** [comment]
南墙也可以，社区免费版本限制不多，小微企业用用足够了
https://waf.uusec.com/#/guide/?id=fire-%e5%8a%9f%e8%83%bd%e5%af%b9%e6%af%94

**Comment by ct-jaryn** [comment]
欢迎大家使用雷池社区版，不同厂商的waf也欢迎对比
有条件的企业推荐购买专业版。
详情查看雷池商用参考文档：https://docs.waf-ce.chaitin.cn/zh/%E4%B8%8A%E6%89%8B%E6%8C%87%E5%8D%97/%E4%BD%BF%E7%94%A8%E5%8D%8F%E8%AE%AE
如有疑问，社区群内咨询群主
