### ISSUE TITLE
白名单中的IP地址被拦截问题

### ISSUE THREAD

**Issue by xiaofg** [chaitin/safeline#113]
1、通用漏洞规则 开启高强度防护后白名单中的IP地址还是被拦截。
2、不开启 高强度防护 非白名单地址也被放行。

**Comment by naocanmonster** [comment]
我怀疑你没配对，截图看一下拦截日志和规则？

**Comment by xiaofg** [comment]
@> 



> 我怀疑你没配对，截图看一下拦截日志和规则？

我刚才重新测试了一下，应该不是我配置的问题。我把容器重启了一遍后就正常了，不过我查看了一下容器的nginx日志 日志里面有很多upstream response is buffered to a temporary file /usr/local/nginx/proxy_temp 这样的报错。

**Comment by zclaiqcc** [comment]
这些报错信息好像不太影响，看起来不是稳定复现的问题，issue 先关闭了
