### ISSUE TITLE
这个能集成nginx插件模式不？

### ISSUE THREAD

**Issue by vvring** [chaitin/safeline#115]
nginx 老用户，用了很多第三方插件，你这个能集成nginx插件源码编译不，源代码你闭源都好，只求能集成nginx插件模式

**Comment by zclaiqcc** [comment]
嵌入式部署呗，2.0 刚发布带上的 https://github.com/chaitin/lua-resty-t1k 满足师傅需求么？具体集成和使用方式会发布一篇文章

企业版支持 .so 动态编译进去的嵌入式方案，代码闭源

**Comment by tree12138** [comment]
血书求嵌入式部署文档

**Comment by vvring** [comment]
> 嵌入式部署呗，2.0 刚发布带上的 https://github.com/chaitin/lua-resty-t1k 满足师傅需求么？具体集成和使用方式会发布一篇文章
> 
> 企业版支持 .so 动态编译进去的嵌入式方案，代码闭源

没有文档啊，社区版支持静态动态.so不？

**Comment by Lorna0** [comment]
有具体操作文章了，可以参考：https://stack.chaitin.com/techblog/detail?id=120
