### ISSUE TITLE
黑白名单列表页里中列名包含 “名字”，防护站点列表页面中列表包含 “备注”，希望统一

### ISSUE THREAD

**Issue by DeronW** [chaitin/safeline#117]
不同列表页面中列名不够统一，有的用 “名字”，有的用 “备注”

@芦苇菌

**Comment by luweijun1992** [comment]
+1 统一各个模块上的名称或者备注以及对应位置，现在有的在前，有的在中，有的在后~

**Comment by DeronW** [comment]
https://github.com/chaitin/safeline/issues/122 重复问题

**Comment by zclaiqcc** [comment]
重复问题先 close 了，隔壁 issue 跟进
