### ISSUE TITLE
建议检测日志列表更换排列，例如把时间放在第一列

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/SafeLine#119]
个人建议，检测日志中的类型进行排序下。因为在很多日志中，时间都是第一列的。
![image](https://github.com/chaitin/safeline/assets/58923704/38ba47b2-9925-45a9-a6b8-a238a1348d96)

另外在右上角可以增加筛选时间，比如我需要看哪个时间段检测日志。
![0aebb5b13f51a7672f67400511b1cb4](https://github.com/chaitin/safeline/assets/58923704/fdd0eb2f-412d-448e-ad4b-b9db7d551a09)

**Comment by Lorna0** [comment]
检测日志按日期 / 时间筛选 有重复 issue：https://github.com/chaitin/safeline/issues/102，这里就不讨论了。

另外建议需求单独提，方便跟踪进度。“UI 建议” 这样标题容易被社区用户忽略，可能只有开发者会翻出来看一看，收集不到点赞。

**Comment by pusidun** [comment]
这个不如在页面上提供列的下拉框，勾选上的列显示。
下拉框的列可以上下拖拽来调整顺序

**Comment by luweijun1992** [comment]
> 这个不如在页面上提供列的下拉框，勾选上的列显示。 下拉框的列可以上下拖拽来调整顺序

没错，让用户自定义。
但是自定义后最好浏览器记住了。不要说浏览器关了重开又恢复默认了。
