### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by leexuan** [chaitin/safeline#12]
安装出现以下错误，请问如何解决呢
root@DESKTOP-3SP76CV:/home/ubuntu/safeline# ./safeline-ce.sh
Success!
[+] Running 4/5
 ✔ Container safeline-postgres  Running0.0s
 ✔ Container safeline-mario     Running0.0s
 ✔ Container safeline-mgt-api   Running0.0s
 ✔ Container safeline-detector  Running0.0s
 ⠋ Container safeline-tengine   Starting0.1s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Start safeline-ce with

**Comment by zclaiqcc** [comment]
`cat /etc/localtime` 看下机器上是否存在这个文件。ubuntu 系统版本也提供一下吧

**Comment by leexuan** [comment]
1、存在这个文件，安装前，是一个软连接文件。后来安装时报错，于是备份了下这个软连接，另外创建了localtime目录。但还是报上述错误：
root@DESKTOP-3SP76CV:/home/ubuntu/safeline# ll /etc | grep localtime
drwxr-xr-x  2 root root    4096 Apr 15 06:43 localtime/
lrwxrwxrwx  1 root root      33 Apr 15 03:31 localtime.bk -> /usr/share/zoneinfo/Asia/Shanghai

2、ubuntu信息：WLS ubuntu 22.04

**Comment by zclaiqcc** [comment]
预期来说 /etc/localtime 就是个软连接，不应该是一个目录。看上去师傅这边把 localtime.bk 恢复回去应该就行了

**Comment by leexuan** [comment]
恢复回去后，执行./safeline-ce.sh报下面的错误：
root@DESKTOP-3SP76CV:/home/ubuntu/safeline# ./safeline-ce.sh
Success!
[+] Running 4/0
 ✔ Container safeline-mgt-api   Running0.0s
 ✔ Container safeline-detector  Running0.0s
 ✔ Container safeline-postgres  Running0.0s
 ✔ Container safeline-mario     Running0.0s
 ⠋ Container safeline-tengine   Starting0.1s
Error response from daemon: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists
Start safeline-ce with

之前安装时，也是因为报这个错误，所以才尝试创建/etc/loclatime目录的

**Comment by zclaiqcc** [comment]
保持软连接的状态，尝试重启 docker desktop

refer: https://stackoverflow.com/questions/50817985/docker-tries-to-mkdir-the-folder-that-i-mount

**Comment by leexuan** [comment]
谢谢。我这里把safeline-tengine和safeline-mgt-api中待映射的宿主机地址'/etc/localtime‘换成了“/usr/share/zoneinfo/UTC”，就正常启动了
refer: [https://stackoverflow.com/questions/50817985/docker-tries-to-mkdir-the-folder-that-i-mount](https://stackoverflow.com/questions/50817985/docker-tries-to-mkdir-the-folder-that-i-mount
