### ISSUE TITLE
管理页面 多条件&内容 显示 UI建议

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/safeline#120]
如下图多个内容，默认不显示，需要点击编辑进去才能看到内容；
![96a1913a2ddaebb46d9aea893adec5f](https://github.com/chaitin/safeline/assets/58923704/dc8b9d54-aa59-4c01-9305-20e19fa50515)
![138c2f107740518b3c25780b43e3b1a](https://github.com/chaitin/safeline/assets/58923704/4a568465-0e39-412f-8352-dae7a9e5cdd3)

建议做成鼠标放着时候给展示内容出来；
效果如下图，当条目数很多的情况下，默认只展示前面N条，超过...省略；
![7ce3f9a4cf7e8aafd4c02f5b874032c](https://github.com/chaitin/safeline/assets/58923704/cf9538dc-da11-4ec1-b326-ebd3e3370fc3)
![image](https://github.com/chaitin/safeline/assets/58923704/84b03cea-398d-4160-9d81-de0f9f6cfeee)

**Comment by DeronW** [comment]
这个可以有

**Comment by DeronW** [comment]
![image](https://github.com/chaitin/safeline/assets/780596/864e7738-6674-4371-ae6e-cb6cc2da928d)

**Comment by luweijun1992** [comment]
不错哦~
弹框的底色最好有点差异，跟背景相似了。

**Comment by zclaiqcc** [comment]
哦看上去没有加完，IP 组内容的提示没有

**Comment by luweijun1992** [comment]
> ![image](https://user-images.githubusercontent.com/780596/250011065-864e7738-6674-4371-ae6e-cb6cc2da928d.png)

建议当存在多条的时候，只显示前面10条。
![image](https://github.com/chaitin/safeline/assets/58923704/a4ae8ef6-723d-4b4e-88c9-801a483f45ac)

**Comment by Lorna0** [comment]
> > ![image](https://user-images.githubusercontent.com/780596/250011065-864e7738-6674-4371-ae6e-cb6cc2da928d.png)
> 
> 建议当存在多条的时候，只显示前面10条。 ![image](https://user-images.githubusercontent.com/58923704/250054164-a4ae8ef6-723d-4b4e-88c9-801a483f45ac.png)

目前单个规则内的多个条件是 “且” 的关系，配这么多个的情况其实不多，比如图中这个示例就没有实际意义。

**Comment by luweijun1992** [comment]
> > > ![image](https://user-images.githubusercontent.com/780596/250011065-864e7738-6674-4371-ae6e-cb6cc2da928d.png)
> > 
> > 
> > 建议当存在多条的时候，只显示前面10条。 ![image](https://user-images.githubusercontent.com/58923704/250054164-a4ae8ef6-723d-4b4e-88c9-801a483f45ac.png)
> 
> 目前单个规则内的多个条件是 “且” 的关系，配这么多个的情况其实不多，比如图中这个示例就没有实际意义。

是的，单个规则多多个条件且类型一致确实没有意思；
其实可以限制单个规则内某种类型只允许出现一次，比如“源IP”和“Host”只允许出现一次，这样这个规则才是有效得；
其他类型可以出现多次；

**Comment by Lorna0** [comment]
于 2.1.0 实现
