### ISSUE TITLE
管理页面 名称 or 备注 建议统一

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/safeline#122]
当前页面中有的是备注，有的是名称。
建议统一一下，看是适用备注还是名称，或者两个都存在（名称必填，备注可选）。
防护站点：
![image](https://github.com/chaitin/safeline/assets/58923704/437dc67e-db51-4fba-9b28-a12709b92977)
黑白名单：
![image](https://github.com/chaitin/safeline/assets/58923704/bc99ef8e-3866-4af3-beed-9883007ca473)
人机验证：
![image](https://github.com/chaitin/safeline/assets/58923704/ba257e8e-d162-4456-90c0-74366f70ea6c)
IP组：
![image](https://github.com/chaitin/safeline/assets/58923704/d6567adf-bb0f-4e53-90a0-92dde36857fa)

个人感觉使用名称会更加合适，比如IP组，如果用备注，那在黑白名单的时候，规则引用的是一个“备注”，感觉不合适。
且名称在页面的排序应该在前，不适合中间或者后面。

有名称+备注更好。

**Comment by Lorna0** [comment]
“名称” 和 “备注” 确实不太一样。“名称” 一般必填。“备注” 选填。IP 组的 “备注” 不符合这个规律，将会更正。

名称的排序不在第一个，一般是有更重要一些的字段，例如 黑名单/白名单、状态。

**Comment by Lorna0** [comment]
于 2.1.0 实现
