### ISSUE TITLE
根据EventID查询拦截详情

### ISSUE THREAD

**Issue by fivek55** [chaitin/safeline#124]
WAF支持根据EventID查询拦截详情

**Comment by Lorna0** [comment]
是否是 https://github.com/chaitin/safeline/issues/74 提及的问题？如果是的话可以在那边一块讨论

**Comment by pusidun** [comment]
#74 是我提的，我在那里详细说了下场景。

**Comment by Lorna0** [comment]
粗略判断应该和 https://github.com/chaitin/safeline/issues/74 是一个问题，这边先关闭了哈，方便大家讨论。

不太一样的话可以再补充下细节。
