### ISSUE TITLE
dockerfile能不能也开源啊？

### ISSUE THREAD

**Issue by fengzhao** [chaitin/safeline#126]
想看一下 management，detector，mario，tengine 各自的实现？

**Comment by DeronW** [comment]
Dockerfile 的作用只是准备运行环境，只是为了让服务运行安装了一些程序，如果想了解运行环境，直接登录到容器查看就可以了。而 Dockerfile 本身开源作用不大，因为 Dockerfile 当中除了环境，就只有 bin 文件。

**Comment by fengzhao** [comment]
想基于雷池定制化自己的规则，怎么制作自己的bin文件啊

**Comment by zclaiqcc** [comment]
> 想基于雷池定制化自己的规则，怎么制作自己的bin文件啊

1. 雷池各个服务都是基于容器的，里面运行的 .bin 存放的更多是业务相关的逻辑
2. 雷池是基于语义分析，而不是基于规则。

从需求出发，只是想自定义一些规则（比如加白 or 加黑），页面上已有功能支持。是说有什么页面功能无法覆盖的场景么？可以具体来一个看看

**Comment by zclaiqcc** [comment]
尽量围绕原始需求来聊，谨防 X-Y 问题聊偏了。https://coolshell.cn/articles/10804.html

**Comment by fengzhao** [comment]
比如，雷池通用配置中的各种配置，仅有各种检测模式的开关，没有看到这些模式的定义。按照你说的语义分析，比如，
我想知道，什么样的请求是`机器人检测`。我想看到这些东西的详细定义。针对这些进行自定义，适配自己的业务场景。

**Comment by fengzhao** [comment]
> > 想基于雷池定制化自己的规则，怎么制作自己的bin文件啊
> 
> 1. 雷池各个服务都是基于容器的，里面运行的 .bin 存放的更多是业务相关的逻辑
> 2. 雷池是基于语义分析，而不是基于规则。
> 
> 从需求出发，只是想自定义一些规则（比如加白 or 加黑），页面上已有功能支持。是说有什么页面功能无法覆盖的场景么？可以具体来一个看看


比如，雷池通用配置中的各种配置，仅有各种检测模式的开关，没有看到这些模式的定义。按照你说的语义分析，比如，
我想知道，什么样的请求是机器人检测。我想看到这些东西的详细定义。针对这些进行自定义，适配自己的业务场景。

**Comment by zclaiqcc** [comment]
> > > 想基于雷池定制化自己的规则，怎么制作自己的bin文件啊
> > 
> > 
> > 
> > 1. 雷池各个服务都是基于容器的，里面运行的 .bin 存放的更多是业务相关的逻辑
> > 2. 雷池是基于语义分析，而不是基于规则。
> > 
> > 从需求出发，只是想自定义一些规则（比如加白 or 加黑），页面上已有功能支持。是说有什么页面功能无法覆盖的场景么？可以具体来一个看看
> 
> 比如，雷池通用配置中的各种配置，仅有各种检测模式的开关，没有看到这些模式的定义。按照你说的语义分析，比如， 我想知道，什么样的请求是机器人检测。我想看到这些东西的详细定义。针对这些进行自定义，适配自己的业务场景。

问题就是，基于语义引擎给不出来一个“详细定义”。师傅可以观察模式上线之后，看下日志有没有误报，有的话对应加白（自定义规则）就行了。

语义引擎的介绍可以查看：https://waf-ce.chaitin.cn/posts/about_syntaxanalysis
