### ISSUE TITLE
能不能添加一个自动封锁IP的功能

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/safeline#127]
1、可以设定一个条件，比如一个IP连续发起几次攻击就自动封锁这个ip 30分钟等。
2、当过了封锁时间自动解封这个ip地址。
3、能不能将40x 50x 请求的url信息也记录一下。

**Comment by zclaiqcc** [comment]
duplicated with https://github.com/chaitin/safeline/issues/93

3. 可以开启 nginx access log 自行处理。默认开启的话，短时间大量被刷攻击（返回 403）可能导致整机负载飙升

**Comment by Lorna0** [comment]
3  @zclaiqcc 所说的，记录全部日志的方法可见文档中的 “如何记录所有访问雷池的请求”：
 https://waf-ce.chaitin.cn/posts/faq_other#%E5%A6%82%E4%BD%95%E8%AE%B0%E5%BD%95%E6%89%80%E6%9C%89%E8%AE%BF%E9%97%AE%E9%9B%B7%E6%B1%A0%E7%9A%84%E8%AF%B7%E6%B1%82

不过确实比较容易导致整机负载飙升、硬盘被刷满。不知道记录 40x 50x 具体是啥场景？

PS. issue 中提多个需求的话，次要的需求比较容易被大家忽略。师傅比较需要的话，建议分开提

**Comment by Lorna0** [comment]
* 1、2 重复：https://github.com/chaitin/safeline/issues/109
* 3 ：有临时解决办法，暂未收集到更多信息

所以先关闭了，师傅需求比较强的话可以再单独提一下。
