### ISSUE TITLE
管理页面 禁用&启动提示

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/safeline#130]
Version 2.0.1
当前“黑白名单”禁用启用会有提示框。
![image](https://github.com/chaitin/safeline/assets/58923704/968209ad-a4bd-4bd4-8a16-a764a1e93521)

而人机验证无提示框。

建议统一。

**Comment by DeronW** [comment]
这个可以有

**Comment by DeronW** [comment]
![image](https://github.com/chaitin/safeline/assets/780596/cbd1f2fc-1d4a-4a03-8381-1330842f0497)

**Comment by Lorna0** [comment]
于 2.1.0 实现
