### ISSUE TITLE
支持同一域名按照不同路径设置不同的上游服务器

### ISSUE THREAD

**Issue by allen12921** [chaitin/SafeLine#131]
有时候由于域名紧缺我们会通过不同的访问路径来对应不同的后端服务，例如:
test.com/api,test.com/oauth 这两个路径分别对应api和oauth服务，目前的”防护站点“一个域名只能设置一个上游服务器，无法满足此场景,希望能在添加站点的页面增加一个路径选项。

**Comment by luweijun1992** [comment]
可以使用以下：终端用户 --> WAF --> Nginx（自定义路径转发到不同上游）--> 站点

**Comment by zclaiqcc** [comment]
理论上现在可以自己 DIY 一个出来，大概的步骤是：
1. 在 resources/nginx/site-enabled/ 下增加 IF_backend_custom 文件
2. 内容上随便 copy 一个其他的 IF_backend_X 文件
3. 修改 location 为匹配 api 或者 oauth
4. 修改 upstream，把 backend_1 改名为 backend_custom，把 server 换成 location 对应的业务
5. （可选）删掉 t1k_append_header SL-CE-SUID 1; 这一行，站点的检测模式跟这个字段有关系，不传就按照「防护」模式生效

这个 IF_backend_custom 不会被覆盖，所以师傅可以随意写。总之就是自己配置 nginx，页面上看不到这个站点，但是底层能转发到雷池的检测服务，同时会记录日志和统计（有点嵌入式模式的感觉）

**Comment by allen12921** [comment]
@zclaiqcc 
这样并不行了，配置不会生效，因为两个配置里都是相同的server name,我添加配置reload nginxn得到下面的提示
nginx: [warn] conflicting server name "test.com" on 0.0.0.0:8888, ignored

**Comment by microqs** [comment]
渴望此功能

**Comment by beimingxue123** [comment]
这个功能等好久了

**Comment by upbeat-backbone-bose** [comment]
渴望此功能+1，今天刚在微信群问过，不想再因为个例套娃多增加一层nginx了

**Comment by upbeat-backbone-bose** [comment]
> 确实是很实用的功能。 强烈建议增加。 另外再增加个本地目录映射就更好了。
> 
> 可以考虑开发自定义内容，自己将需要的内容往里面写，放在对应的 server 下。这样好多需要的功能都不用再开发。 ![微信图片_20231123095056](https://user-images.githubusercontent.com/59783960/285080781-6186eccf-88e6-433d-b6ff-eab3354da98c.png)

您这个截图来源是哪里的呀？盲猜Nginx Proxy Manager?

**Comment by lendy98** [comment]
> > 确实是很实用的功能。 强烈建议增加。 另外再增加个本地目录映射就更好了。
> > 可以考虑开发自定义内容，自己将需要的内容往里面写，放在对应的 server 下。这样好多需要的功能都不用再开发。 ![微信图片_20231123095056](https://user-images.githubusercontent.com/59783960/285080781-6186eccf-88e6-433d-b6ff-eab3354da98c.png)
> 
> 您这个截图来源是哪里的呀？盲猜Nginx Proxy Manager? @lendy98

你这猜它干嘛，确实从Proxy角度，他绝对还是强大的。 他有模板能直接修改，我就把 safeline 的 t1k 功能 放他那去了，安全过滤，黑白名单都能用，就是 人机验证用不了。把 [safeline-tengine] 停了。 

反过来说safeline的这个问题：
include /etc/nginx/custom_params/backend_36; 这个直接放在 server 下，自己直接修改这个文件好了，对应 有没有其他include，修改 /etc/nginx/sites-enabled/IF_backend_36 又会被覆盖。 
![微信图片_20231123105038](https://github.com/chaitin/SafeLine/assets/59783960/881f9233-f89e-4f80-9f8d-127ce32acfca)

**Comment by lendy98** [comment]
我自己曲线救国成果，custom_confs目录为 server里面增加内容。

做个脚本定时1分钟运行一次，运行脚本如下：
`#!/bin/bash

# 设定目标目录
target_directory="/data/safeline/resources/nginx/sites-enabled"

found_file=0

find "$target_directory" -type f -name IF_backend_* -mmin -60 | while read file
do
  # 修改文件内容，可以使用 sed 命令修改
  echo "Edit $file"
  index=$(echo "$file" | awk -F 'IF_backend_' '{print $2}')
  sed -i "s/location ^~ \/ {/include \/etc\/nginx\/custom_confs\/backend_$index;\n    location ^~ \/ {/g" "$file"
  touch -m -t 200703311230.09 "$file"
  touch /data/safeline/resources/nginx/custom_confs/backend_$index
  found_file=1
done

if [ $found_file -eq 1 ]; then
  echo "Find file"
  docker exec safeline-tengine sh -c 'nginx -t && nginx -s reload'
fi
`

如果编辑custom_confs目录下对应的 backend_x 文件
`  location /webalizer {
    alias /var/www/usage;
    autoindex on;
  }
  location /status {
    stub_status on;
    #allow 127.0.0.1;
    #deny all;
  }
  location /mrtg {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass       http://192.168.0.1:80/mrtg/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
  }
`

安全问题也可以放一个
    # Authorization
    auth_basic            "Authorization required";
    auth_basic_user_file  /etc/nginx/access/1;
    proxy_set_header Authorization "";
    # Access Rules: 1 total
    allow 0.0.0.0/0;
    deny all;
或者在
/data/safeline/resources/nginx/custom_params/backend_x 统一放一个也行。
`   
    # Authorization
    auth_basic            "Authorization required";
    auth_basic_user_file  /etc/nginx/access/1;
    proxy_set_header Authorization "";
    # Access Rules: 1 total
    allow 0.0.0.0/0;
    deny all;
`

**Comment by lendy98** [comment]
`不知道为什么，这个代码功能无效`

**Comment by fsyxhua** [comment]
强烈期待此功能

**Comment by hemingzhe1991** [comment]
backed_* 文件只能修改 location内的配置 外的配置 没法修改 每次一有改动马上被覆盖 好得很

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
