### ISSUE TITLE
登录方式可以配置为本地账号密码的形式吗？

### ISSUE THREAD

**Issue by freegit9527** [chaitin/safeline#132]
如题

**Comment by DeronW** [comment]
账号密码登录方式，虽然容易记录，但是也存在弱密码、撞库、长期不更新等等问题，如果开放了，就无法约束使用方式。潜在风险还是挺大的。

**Comment by jinhaozcp** [comment]
是否可以改为多用户模式，多用户模式，我觉得使用动态口令挺好，毕竟管理员有可能有2个人以上

**Comment by zclaiqcc** [comment]
> 是否可以改为多用户模式，多用户模式，我觉得使用动态口令挺好，毕竟管理员有可能有2个人以上

现在的方案也可以多人使用，参考 https://waf-ce.chaitin.cn/posts/faq_login

**Comment by zclaiqcc** [comment]
> 如题

体感登录高属于低频场景，通过小程序等 OTP 绑定 + 验证十分方便。账号密码存在弱口令等问题，后续即使增加账号功能，大概率也会强制 OTP 登录。毕竟雷池反代接入，一旦被登录后台，调整或者删除站点配置，会导致严重问题。
