### ISSUE TITLE
人机验证为什么一定要去访问 https://challenge.rivers.chaitin.cn？

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/safeline#134]
1、人机验证模块始终会去访问长亭的网址https://challenge.rivers.chaitin.cn/
2、这种远程调用让人觉得存在数据泄露
3、内网业务系统不能访问互联网这个功能直接不能正常使用。

**Comment by zclaiqcc** [comment]
1. 从云平台获取人机验证需要的一些信息
2. 敏感的话可以不使用
3. WAF 部署在内网也可以使用，只要业务是对公网提供服务的。纯内网服务（即访问来源也都局限于内网）确实不支持，这种也没必要上人机验证吧

放在云平台的考虑是，人机验证是一个攻防对抗，双方不断升级手段的过程。如果放在雷池版本镜像里面，对于没更新的用户，很容易就失去有效的防护能力了。在云平台可以实时更新对抗手段，不断迭代人机识别的算法。

**Comment by James-ci-git** [comment]
1、但是目前这样远程调用还存在一个BUG  我在部署一个环境测试的时候，开启人机验证后业务不能正常使用。
2、部署环境为  互联网--->雷池（开启人机验证）--->Nginx(可以访问互联网)--->雷池（不开启人机验证，不能连接互联网）--->(Nginx,不能访问互联网)--->业务服务器 
3、部署环境为  互联网--->雷池（开启人机验证）--->Nginx(可以访问互联网)--->(Nginx,不能访问互联网)--->业务服务器  这样就可以正常使用。

**Comment by zclaiqcc** [comment]
为啥是两台雷池？看上去仅有一台雷池，切开启人机验证的时候是可以使用的哈？

雷池在验证阶段不会请求外部服务，所以和能否访问互联网倒是没啥关系。2.0.0 版本雷池上需要正常配置「源 IP 获取方式」，能获取到客户端的公网 IP，否则验证不通过。2.0.1 版本对这里做了优化。不确定师傅的版本是多少，可能这里的问题？

**Comment by James-ci-git** [comment]
1、互联网出口部署的雷池版本是2.0.1，内网雷池部署的版本为2.0.0
2、我的业务场景需求，一个需要防护从互联网过来的，另一个需要防护从分支机构过来的内网流量。
3、按照你的说法是需要获取客户端的公网IP才能验证通过，如果我内网有DNS服务器解析，客户端请求并没有互联网IP这种情况下就不能开启这个人机验证模块了吧。【客户端分为：互联网用户，内部DNS域名解析客户端，纯内网客户端】
4、我的防护对象为来自互联网用户需要进行人机验证，目前我配置的是url路径+HOST 的复合方式进行匹配 。

**Comment by zclaiqcc** [comment]
嗯了解，师傅把内网雷池升级到 2.0.1 应该就可以测试通过上面的第二个场景了。2.0.1 对客户端 IP 的校验做了优化。

互联网--->雷池（开启人机验证）--->Nginx(可以访问互联网)--->雷池（不开启人机验证，不能连接互联网）--->(Nginx,不能访问互联网)--->业务服务器
