### ISSUE TITLE
【功能】希望SSL支持自动申请续期签发Let's Encrypt的https证书

### ISSUE THREAD

**Issue by ezjbc** [chaitin/safeline#135]
【功能】
1、希望SSL支持自动申请续期签发Let's Encrypt的https证书
2、前端页面站点配置，增加 497 强制http转https复选框。

**Comment by Lorna0** [comment]
1. 与 https://github.com/chaitin/safeline/issues/92 重复，可以在那边继续讨论
2. 大概是指 https://github.com/chaitin/safeline/issues/67 ？不过 497 是啥呢，打错了？

PS. 多个功能需求建议分开提 issue，方便大家搜索和讨论

**Comment by ezjbc** [comment]
error_page 497 https://$host:1951$request_uri;

> 1. 与 [关于使用免费的SSL证书 #92](https://github.com/chaitin/safeline/issues/92) 重复，可以在那边继续讨论
> 2. 大概是指 [希望增加HTTPS跳转功能，谢谢 #67](https://github.com/chaitin/safeline/issues/67) ？不过 497 是啥呢，打错了？
> 
> PS. 多个功能需求建议分开提 issue，方便大家搜索和讨论

error_page 497 https://$host:$request_uri;

**Comment by Lorna0** [comment]
> error_page 497 https://$host:$request_uri;

大致理解了，那应该还是同一个需求。可以在那边继续讨论。

不过这种情况我们一般采用的是 301、302 的方式，类似于：

```
return 302 https://$host$request_uri;
```


497 这个好像有点 hack，对业务服务器有些要求。
