### ISSUE TITLE
首页数据统计显示4xx、5xx的功能问题

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/SafeLine#136]
![total](https://github.com/chaitin/safeline/assets/42514273/e4c0d392-ed82-45d4-b81d-567de0c6f65c)
1、目前首页统计中只显示了一个错误数量、错误率。只是进行统计显示这样的数据实用性不大。
2、希望这个位置可以调整为在对应的4xx错误数量和5xx错误数量提供一个详细数据，点击这个位置的时候可以直接把具体的url地址源IP等信息给列出来。

**Comment by Lorna0** [comment]
如果单纯把 4xx、5xx 请求都记录下来，会带来比较大的存储压力。极端情况下，网站如果挂了，这里就相当于记录全部访问日志，磁盘可能很快就打满了。

其实 4xx、5xx 错误情况原本是希望让管理员快速了解一下网站运行是否正常。即，如果错误率非常高，则代表网站很可能运行不正常，需要进行排查处理。如图的 2.54% 和 0.13% 还是比较正常的，不太需要关注。

看起来这个展示形式不那么容易理解，倒是可以想个更好的办法。

**Comment by weihms** [comment]
可以设置日志记录阈值，例如7天-30天，30天-180天，需升级企业版，你看我把盈利手段都告诉大家了，兄弟们，加把劲。要不都知道具体是被墙了，还是真报错了。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
