### ISSUE TITLE
支持配置管理页面允许登录的 IP 地址 / 登录 IP 白名单 / Restrict Admin Access by IP Address

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/SafeLine#137]
1、管理页面在客户端IP地址无变化的情况下，未点击退出系统。下一次登录雷池的时候直接免密码登录到系统中了。
2、建议对于管理页面增加一个只允许哪些IP地址可以访问的限制。
3、强制登录后多少分钟之后无操作自动退出管理页面。

**Comment by zclaiqcc** [comment]
1、3 其实都是有的，只不过过期时间比较长，后面看要不要加一个功能可以自定义。（貌似是三级等保要求的一项）
2 也合理，不过配置在页面的话，如果写错了 IP，可能就访问不到了，得想想有没有更优雅的配置方式

**Comment by James-ci-git** [comment]
关于这个写错IP的问题有两种解决方案
1、可以在配置选项中默认设置一条默认规则允许宿主机本机的IP地址永久访问。当配置IP地址写错了的时候可以通过SSH 到宿主机做一个socket 代理转发。
2、可以借鉴重新绑定动态口令的方式 重置管理页面可登录的源IP地址。

**Comment by Lorna0** [comment]
1、3 都有，我限定一下 issue 的标题和讨论范围，方便大家检索。

**Comment by zhuanmentiwen** [comment]
希望优先增加后台登陆日志记录功能。。这个便于个人查看。

**Comment by xbingW** [comment]
商业版已支持此功能
