### ISSUE TITLE
防护站点比较多，建议增加防护站点分组功能

### ISSUE THREAD

**Issue by anquanscan** [chaitin/SafeLine#139]

**Comment by zclaiqcc** [comment]
多少个？具体分成哪些组？

**Comment by anquanscan** [comment]
> 多少个？具体分成哪些组？

就比如有很多业务部门，都放在一起了也不方便区分，我新增站点可以把这个站点都设置为 部门A的，或者其他站点设置部门B的，这样看起来清楚一些

**Comment by zcbxxx1** [comment]
想要调整顺序的功能！！！
强迫证患者好难受！
球球了
