### ISSUE TITLE
Web管理后台展示内容建议

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/safeline#14]
当前防护站点，可看到的信息只有：域名、备注、端口。但是实际可配置的项目不止前面说的3个。且对应顺序还是乱的。
建议可把上游服务器也加上。
考虑到后面版本功能会有优化增加，所以这个位置可以做成可选列显示的方式，根据用户自己需要进行展示。
![image](https://user-images.githubusercontent.com/58923704/232272317-ec8e4752-9516-445b-a1f3-61d5667156b6.png)

自定义列显示（且支持排序哪个在前哪个在后的自定义）：
![image](https://user-images.githubusercontent.com/58923704/232272491-0ecacc57-8d5c-4352-ae87-b611bfba4356.png)

**Comment by luweijun1992** [comment]
另外对防护站点的启用、禁用操作。
还有就是防护站点的只记录，不拦截功能。

**Comment by DeronW** [comment]
这个可以有

**Comment by DeronW** [comment]
已添加到 2.1 版本中，发布后会关闭该问题

**Comment by DeronW** [comment]
![image](https://github.com/chaitin/safeline/assets/780596/34d66c91-061f-46c7-9acc-9e7473481f12)

**Comment by Lorna0** [comment]
提到的内容有点多，基本已经完成或暂时不考虑，我统一回复下：
1. 当前防护站点，可看到的信息只有：域名、备注、端口。但是实际可配置的项目不止前面说的3个。且对应顺序还是乱的，建议可把上游服务器也加上
     * ——社区版的目标是保持精简易用。上游服务器的展示优先级不是很高，而且如果要做负载均衡，上游服务器可能改为多个，直接展示在列表上不太美观，所以目前暂不考虑。顺序的这个问题已经改好了。
2. 考虑到后面版本功能会有优化增加，所以这个位置可以做成可选列显示的方式，根据用户自己需要进行展示。
    * ——列表字段目前还不多，为保持精简，暂不考虑自定义展示字段。等到列表内容多的时候会考虑
3. 另外对防护站点的启用、禁用操作
    * ——“禁用” 我理解是保存配置，但不监听端口。v1.10.0 起，站点支持设为 “维护” 模式，只返回一个维护中页面。在此基础上，禁用功能对社区版用处应该不大了。师傅觉得很有必要的话可以单独提一个 issue 让大家点赞，就不混在这条 issue 里讨论了
4. 还有就是防护站点的只记录，不拦截功能
    * ——v1.10.0 起，已支持将站点设为 “观察” 模式，满足这个需求

师傅可以确认一下，issue 会在 2.1 发布时 close。

另外提交 issue 的时候，建议将每个需求拆分开来，这样其他人有类似需求的时候，更容易找到，有利于收集社区意见。合并在一起的话，容易被一起 close 了。

**Comment by Lorna0** [comment]
2.1 已发布，站点列表支持按照域名、端口、访问量排序。这里先 close 了哈，有问题可以再评论。
