### ISSUE TITLE
首页 访问来源地区-仅拦截 支持跳转到相应检测日志 / 检测日志支持按地理位置筛选

### ISSUE THREAD

**Issue by anquanscan** [chaitin/SafeLine#140]
![image](https://github.com/chaitin/safeline/assets/5724472/a837dacb-3958-45d1-abe5-5cdc16b59d09)
比如我现在压根查不到  山东、湖北等地区的日志，太多拉。

**Comment by Lorna0** [comment]
这里涉及两个需求，因为首页统计包含两类信息：网站访问情况、网站拦截情况。

如果是需要网站拦截情况的进一步分析，那似乎检测日志支持筛选地理位置可以解决。

网站访问情况则不太一样，因为访问的数据（如图的 “全部请求” 的地理位置统计数据）全记录下来太容易把磁盘写满了。所以目前只在首页这里存了一些统计信息，帮助管理员分析一下网站运营情况。之后我们会继续尝试做一些网站访问、运营情况分析的能力，然后以这些为基础优化首页相关的交互，应该会更好用一些。

原描述稍微有点模糊，我先限定为攻击检测日志支持搜索地区吧。师傅有想法的话可以继续讨论。

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
