### ISSUE TITLE
咨询：仓库中的代码如何构建

### ISSUE THREAD

**Issue by chennqqi** [chaitin/safeline#141]
有没有Dockerfile后者构建、安装文档

**Comment by zclaiqcc** [comment]
暂不支持，构建的目标是啥？建议围绕原始需求来沟通，谨防 [X-Y 问题](https://coolshell.cn/articles/10804.html)

**Comment by chennqqi** [comment]
已看到官方回复，建议注明【免费非开源】避免学习者浪费时间
