### ISSUE TITLE
防护站点页配置希望增加强制https选项

### ISSUE THREAD

**Issue by ZTfred** [chaitin/safeline#144]
当前网站全量https化，添加防护站点，选择SSL，会自动https，但是http的请求会被refused，不会自动跳转至https协议网站上，影响用户访问体验

希望勾选SSL后，新增选择  强制HTTPS，实现自动301跳转，优化用户体验感

对标阿里云waf部分功能
![image](https://github.com/chaitin/safeline/assets/53425107/83cf6012-5382-4ae4-b967-e0397be50a40)
![image](https://github.com/chaitin/safeline/assets/53425107/42196420-911c-41ed-815f-999ce5ee90d3)

**Comment by nmgliangwei** [comment]
+1

**Comment by Belkuy** [comment]
这个好像可以自己做下，开个80端口的同名站点，在自定义配置上加上 return 301 https://$host$request_uri;

**Comment by clqs803** [comment]
> 这个好像可以自己做下，开个80端口的同名站点，在自定义配置上加上 return 301 https://$host$request_uri;

确实可以，但是升级之后配置就不见了 需要重新添加

**Comment by Belkuy** [comment]
> > 这个好像可以自己做下，开个80端口的同名站点，在自定义配置上加上 return 301 https://$host$request_uri;
> 
> 确实可以，但是升级之后配置就不见了 需要重新添加

2.1.0 版本之后官方做了个可以自定义的配置，可以看下文档中的其他问题页面最后一项。

**Comment by Lorna0** [comment]
看上去和 https://github.com/chaitin/safeline/issues/67 是类似需求，可以集中到那边讨论。这边先关闭。

感谢 @Belkuy 的回复，我也在那边补充下。
