### ISSUE TITLE
增加自定义规则将恶意攻击IP加入黑名单

### ISSUE THREAD

**Issue by ZTfred** [chaitin/safeline#147]
针对检测日志信息，是仅拦截当前的一次请求，无法对恶意攻击IP持久化禁用。
建议支持根据请求量或者攻击频率，自动将攻击IP拉入黑名单，或者开放自定义的策略规则，可以按照自己的规则实现自动拉黑攻击方

目前黑名单都是手动添加IP，局限较大，需要一直去维护这个名单

或者可以通过检测日志，增加处理选项，可以一键关联黑名单，将请求方拉黑，或者创建关于请求方式的黑名单策略

**Comment by DeronW** [comment]
是不是和 https://github.com/chaitin/safeline/issues/93 描述的是相同的问题？

**Comment by Lorna0** [comment]
看起来和限频/防CC是相同的问题，可以集中在这边讨论：

- https://github.com/chaitin/safeline/issues/29
