### ISSUE TITLE
通过已有的地区进行筛选

### ISSUE THREAD

**Issue by wxzNO1** [chaitin/safeline#149]
![image](https://github.com/chaitin/safeline/assets/70799095/cf0c6fce-2050-4c7f-9c52-7bc84263b1ca)
通过已有的地区进行筛选
![image](https://github.com/chaitin/safeline/assets/70799095/b24f907b-3b64-45d1-b850-702eb0122007)
就把这的地区加到筛选中

**Comment by Lorna0** [comment]
duplicates：
* https://github.com/chaitin/safeline/issues/140
