### ISSUE TITLE
咱们这目录结构有讲解的文档么？

### ISSUE THREAD

**Issue by wenhao-in-chengdu** [chaitin/safeline#151]
咱们这目录结构和框架结构不是特别清晰，作为没玩过waf的我来讲，一上来看着感觉很混乱。

**Comment by zclaiqcc** [comment]
是说 GitHub 的目录么？师傅是想了解啥内容呢

**Comment by Lorna0** [comment]
太长时间无信息，先 close 了哈，有需要可以再反馈。
