### ISSUE TITLE
[建议] 内网搭建waf很麻烦，能否有新的方案

### ISSUE THREAD

**Issue by suhunshiye** [chaitin/safeline#160]
### 背景与遇到的问题

现在主要问题就是雷池的解决方案就是映射出另外一个端口，然后真正自己有个端口无waf的端口放在内网，所以感觉依旧风险点还是存在，万一我要把这个搭建内网，内网形成一个全部端口的waf现在实现起来是比较费劲的。

### 建议的解决方案

以上问题就是能否不用映射另外一个端口或者说可以手动选择这个端口能否看见可见，现在需要手动禁止掉。

**Comment by zclaiqcc** [comment]
我理解师傅是说，自己原先有一个服务部署在内网的 :80 端口，现在接入雷池 WAF 之后，需要把这个服务改到 :8080，雷池去监听 80。这样的话就比之前多占用了一个端口。同时 :8080 在内网，感觉还是有一定风险的？

tl;dr 
1. 为了更高的安全性，师傅可以让业务只允许雷池 IP 的访问（内网 IP or 127.0.0.1），其他都禁用掉。如果我的理解没错的话，没有师傅希望的那种，设置端口不可见的方式，太玄乎了。 😅 
2. 不用监听额外端口就可以把流量发给雷池进行检测的方案也是有的，但是现在雷池社区版仅支持软件反代（基于 nginx）的方式接入，所以目前没法做不到。

详细版本：

雷池社区版是通过 nginx 反代串联接入用户的网络拓扑，所以是需要额外监听一个端口。企业版支持透明桥的方式接入流量，相当于整个链路不需要做任何修改，雷池就能够实现检测。但是这种接入方式原理上和 nginx 反代差异很大，所以社区版暂时没法支持。

端口没有“不可见”一说，只要有服务监听了，那就能被访问到。无非是限制访问 IP，比如只允许雷池所在机器的 IP 来访问（如果部署在同一台机器上，那就是 127.0.0.1）。对其他 IP 来说，就好像不可见一样。但是这种需要手动禁止，通过 iptables 或者在服务启动的时候设置 IP 白名单。

额外也提一下内网监听端口感觉依旧有风险的问题，业务直接裸奔在公网，肯定要比跑在内网 + 前面有一个雷池的风险要高很多。所以除了流量接入雷池的时候可能稍微需要调整一些网络拓扑之外，在安全性上肯定是不用太担心的。

**Comment by Lorna0** [comment]
太长时间无反馈，先 close 了哈，有需要可以再反馈。
