### ISSUE TITLE
[建议] 对于开启SSL证书无HTTP2协议选项

### ISSUE THREAD

**Issue by ylwzbk** [chaitin/safeline#161]
### 背景与遇到的问题

当WAF站点使用了SSL证书时无 http2协议开启的选项，只能通过手动修改，但进行过重启或者升级手动修改的配置会丢失，仅能使用http1.1协议 享受不到H2带来的特性

### 建议的解决方案

在防护站点域名界面 ssl开启时  加入是否使用HTTP2协议

**Comment by dhfsqxz** [comment]
或者开了ssl就自动支持h2呢
反正没啥影响

**Comment by zclaiqcc** [comment]
> 或者开了ssl就自动支持h2呢 反正没啥影响

不是吧，比如参考这个 https://www.zhihu.com/question/310263956

**Comment by dhfsqxz** [comment]
> > 或者开了ssl就自动支持h2呢 反正没啥影响
> 
> 不是吧，比如参考这个 https://www.zhihu.com/question/310263956

绝了哦
我是认为这种老古董的东西不用考虑
就算负优化也没问题
就算不负优化性能也高不到哪去

**Comment by Lorna0** [comment]
在 3.0 中支持：
![image](https://github.com/chaitin/safeline/assets/56920727/8de9adec-a162-4a34-a15f-f035bc2a8a1a)
