### ISSUE TITLE
多个站点同一个源站如何合并成1个

### ISSUE THREAD

**Issue by qq8554650** [chaitin/SafeLine#162]
### 背景与遇到的问题

http://a.com
http://www.a.com
https://a.com
https://www.a.com
要配置4个站点，实际对应后面1个。有什么办法简化吗

**Comment by zclaiqcc** [comment]
能简化成两个，但是没法简化成 1 个，核心问题是端口。

创建一个站点，域名写 a.com，监听 80 端口，上游写你的业务服务器；创建另一个站点，域名也写 a.com，监听 443 端口，开启 ssl，上传证书，上游写你的业务服务器即可

**Comment by zclaiqcc** [comment]
可以考虑的进一步的方案是：
1. 在页面上支持配置多个端口，每个端口可以单独配置是否开启 ssl。这样上游服务器填一次就行。
2. 支持 http 转到 https，https://github.com/chaitin/safeline/issues/67，这样也可以只配置一个站点，把 http 的流量都转到 https

感觉没必要，也就是把两个站点优化成了一个，实际上没啥太大区别，先 open 着看看情况吧。

**Comment by clqs803** [comment]
![2023-07-18_08-59](https://github.com/chaitin/safeline/assets/80808022/09f1ce3e-fc48-4678-a89f-f1d6ccc950f3)
多个站点同一个源站的情况下可以写多个，中间用空格隔开。 HTTPS证书也可以多合一

**Comment by luweijun1992** [comment]
> 

多个站点使用,隔开支持把，支持多种方式。
```
a.com,b.com,c.com,d.com
```
