### ISSUE TITLE
[建议] 添加定时从url更新IP组的功能（方便与蜜罐联动）

### ISSUE THREAD

**Issue by DoyoDia** [chaitin/safeline#164]
### 背景与遇到的问题

![image](https://github.com/chaitin/safeline/assets/79502694/a8f61c8a-e346-43ef-9141-bb94f32ff657)
希望能添加定时从url更新IP组的功能
这样从多渠道收集来的风险IP能被及时屏蔽

至于响应数据需要是什么样子看开发者了，是直接传TXT文件里面一行一个IP还是传JSON我觉得都可以
在这里我放一个HFISH的API：https://hfish.net/#/detail-api
![image](https://github.com/chaitin/safeline/assets/79502694/8eedc2eb-fa5b-4df5-a51c-5770a26b0f1d)

如果看issue的你也觉得这个功能很有用请点个赞

**Comment by zclaiqcc** [comment]
WAF 定期拉取 URL 方案太复杂了，涉及到数据格式、同步周期、URL 配置、公网可访问（以及域名解析）等等问题。

更直接的方式是有更新的情况下，师傅自己来推送，或者定时推送都行。扒一下接口就行，应该是 PUT /api/IPGroup。
