### ISSUE TITLE
[建议] 可以自定义设置拦截响应

### ISSUE THREAD

**Issue by Peter1303** [chaitin/SafeLine#165]
### 背景与遇到的问题

我的业务是返回接口响应的结果，返回类型为 JSON，如果拦截了希望可以返回自定义的 JSON，这个在宝塔的 Nginx 防火墙中是有的
![image](https://github.com/chaitin/safeline/assets/13428400/1acc4dd4-55d8-4623-9836-2001e5b428c7)

### 建议的解决方案

添加统一拦截响应或单独的规则拦截响应数据（页面）功能

**Comment by zclaiqcc** [comment]
师傅具体想自定义一些什么信息上去呢？

**Comment by Peter1303** [comment]
可以自定义返回的数据就行了，比如可以自行设置业务响应数据
```json
{
  "code": 403,
  "msg": "请求被拦截"
}
```

**Comment by James-ci-git** [comment]
这个功能还是非常实用的，建议增加一下这个功能。

**Comment by wuzhizhan** [comment]
有用！并且自定义返回也可以让攻击者无法判断出是使用了哪个waf

**Comment by Lorna0** [comment]
@wuzhizhan 
> 有用！并且自定义返回也可以让攻击者无法判断出是使用了哪个waf

这个 issue 主要讨论目前的拦截页面不方便 API 业务处理的问题。而拦截时的雷池标识是社区版的重要传播途径之一，除非有实际影响使用的问题，暂不会考虑抹除。
另外市面上有很多识别 waf 的工具，“让攻击者无法判断出是使用了哪个waf” 其实没有那么大意义的。

**Comment by xbingW** [comment]
目前支持自定义响应页面，其他问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
