### ISSUE TITLE
[建议] 在web控制台中添加“监听IPV6”开关

### ISSUE THREAD

**Issue by SuzuhaOtoha** [chaitin/SafeLine#166]
### 背景与遇到的问题

雷池默认不监听IPV6，只能手动修改nginx的配置文件来实现IPV6的监听，这就产生了两个问题：
1.站点量较多时每个站点都需要手动修改配置文件，效率较低
2.每次重启或从web控制台修改网站配置将导致手动修改的配置失效

### 建议的解决方案

在web控制台中添加“监听IPV6”开关，将nginx配置文件中有关IPV6的部分交由雷池来进行管理

**Comment by RabbitJun** [comment]
支持，同建议添加“监听ipv6”选项

**Comment by Lorna0** [comment]
在 3.0 中支持了，可以升个级：
![image](https://github.com/chaitin/safeline/assets/56920727/8de9adec-a162-4a34-a15f-f035bc2a8a1a)
