### ISSUE TITLE
[建议] 希望增加自定义Nginx参数功能，或融合nginxWebUI等工具

### ISSUE THREAD

**Issue by maskerTUI** [chaitin/SafeLine#167]
### 背景与遇到的问题

safeline社区版使用nginx反代的方式进行防护，直接融合了nginx，对于资产不多的网站，这非常实用。但是有一些网站需要自定义nginx的反代参数，希望nginx能自定义反代参数。
市面上已经有很多非常优秀的调nginx参数的ui项目，比如nginxWebUI，希望能直接把这种项目融合进safeline。

### 建议的解决方案

融合nginxWebUI项目

**Comment by dhfsqxz** [comment]
真有特殊情况的可以考虑人工改
融合了webui说不准哪天waf直接爆漏洞直接让人干穿了

**Comment by zclaiqcc** [comment]
> 真有特殊情况的可以考虑人工改 融合了webui说不准哪天waf直接爆漏洞直接让人干穿了

有道理，应该不会直接内置进去，可以参考他们的交互设计和功能

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
