### ISSUE TITLE
[建议] 增加批量拉黑的功能

### ISSUE THREAD

**Issue by ceciliaaii** [chaitin/SafeLine#168]
### 背景与遇到的问题

某个时间段 恶意请求过多 手工拉黑过于繁琐

### 建议的解决方案

可以针对某个模块(SQL，XSS)拦截的IP进行批量拉黑；或者可以针对某个时间段拦截的IP进行批量拉黑

**Comment by dhfsqxz** [comment]
+1

**Comment by safe1ine** [comment]
这不就是 IP 情报的功能嘛

**Comment by ceciliaaii** [comment]
恶意请求被拦截后，会产生日志，我的需求为对日志中的恶意IP可以进行批量拉黑操作

**Comment by pldinfo** [comment]
我建议拉黑国外ip

**Comment by ceciliaaii** [comment]
> 我建议拉黑国外ip

国外IP也有正常请求，不能一概而论

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
