### ISSUE TITLE
希望平台可以给日志加一个返回包状态码列，更方便判断

### ISSUE THREAD

**Issue by zhoupeng0721** [chaitin/SafeLine#170]
**希望平台可以给日志加一个返回包状态码列，更方便判断、查看**

这样可以更直观的有时判断，刚好首页展示页面也会展现3xx、4xx、5xx，这里也更方便查看

### **雷池WAF真的很好用！希望越来越好！**

![image](https://github.com/chaitin/safeline/assets/73821692/85c62e14-a233-4758-8624-6c6ec13b9c01)

**Comment by Lorna0** [comment]
没太理解需求背景。目前攻击检测日志里，拦截的响应都是 403，只有放行的还算有响应码。看这个有啥用呢。

**Comment by Lorna0** [comment]
时间有点长，先关闭。有更多信息的话可以补充一下，再 reopen。
