### ISSUE TITLE
希望细化一下许可证，当前许可证是禁止修改禁止商用的

### ISSUE THREAD

**Issue by dhfsqxz** [chaitin/safeline#171]
### 反馈内容

以我们自身为例
我们是一个十几个人的开发团队，部署雷池只是为了防止有人直接打在我们开发机上
不上生产环境也不图盈利，部署也属于私人行为
但是实际上我们也算部署在公司了
这种也算违反许可了吧

**Comment by dhfsqxz** [comment]
像waf这类产品
绝大多数用户多少应该和商用沾点边
如果按照许可证的话最多只能允许部分个人站长自用
可用范围极小
所以这确实是你们的初衷么？

**Comment by dhfsqxz** [comment]
还有一些比如个人爬接口、做sdk甚至迁移k8s的
官方鼓励的行为
这种应该也算违反许可吧

**Comment by dhfsqxz** [comment]
为了社区版能够健康发展
希望官方能够考虑一下

**Comment by Lorna0** [comment]
感谢建议。能理解师傅的顾虑，不过社区版目前的重心还是软件开发，许可证问题牵涉较多，只临时写了一个，还没有精力完善。后续的版本我们尽量逐步优化，等推出专业版后真正解决这个问题（打个预告，应该也快了）。
能明确的是社区版肯定不是为了收割大家法务问题而做的（不然干嘛打长亭招牌，开个空壳公司不好么hh），只是确实还处在更需要推广和开发的不成熟阶段，希望理解。有啥问题可以继续在交流群中讨论，再次感谢反馈～
