### ISSUE TITLE
[建议] 提供基于ip段的攻击统计

### ISSUE THREAD

**Issue by dhfsqxz** [chaitin/safeline#173]
### 背景与遇到的问题

根据现有攻击情况看
很多扫描会使用一整个ip段来扫描，导致攻击事件里攻击ip一堆相似
希望可以出一个筛选条件 ip/24 或者 ip/16这样的合并统计
好几十页的相似ip看的头大
![image](https://github.com/chaitin/safeline/assets/74221255/4b064c1b-1bb9-4ab9-ae10-80987f6ba685)

**Comment by DeronW** [comment]
是说搜索 IP 的时候可以搜索：  10.1.0.0/16 , 然后把这个网段下面所有的 IP 都搜出来是吗？

**Comment by dhfsqxz** [comment]
> 是说搜索 IP 的时候可以搜索： 10.1.0.0/16 , 然后把这个网段下面所有的 IP 都搜出来是吗？

一个是搜索 ip/16可以把对应网段下的都搜出来
另一个可以认为是聚合开关，例如选择 /16，那么将把所有ip以 ip/16的形式显示，并将相同的聚合

**Comment by Lorna0** [comment]
搜索 IP 时支持搜索一个范围，这个需求确实有可能出现，可以考虑下。不过感觉跟这个 issue 关系不大，没法解决原始问题。

聚合方面，攻击事件为了降低查询开销，是单独记录的一个数据表，不是临时查出来的。要是想聚合，得在 原始日志->攻击事件 上再加一层聚合功能。一些大型的 soc、siem 或者重数据的产品确实会有更完善的数据聚合能力，对目前的社区版则显得有些复杂，短期内估计不太会考虑。

btw 扫描问题我是更建议先通过 限频、防bot、人机验证 之类的能力来防护，优化日志管理的性价比确实不咋高。

**Comment by dhfsqxz** [comment]
> 搜索 IP 时支持搜索一个范围，这个需求确实有可能出现，可以考虑下。不过感觉跟这个 issue 关系不大，没法解决原始问题。
> 
> 聚合方面，攻击事件为了降低查询开销，是单独记录的一个数据表，不是临时查出来的。要是想聚合，得在 原始日志->攻击事件 上再加一层聚合功能。一些大型的 soc、siem 或者重数据的产品确实会有更完善的数据聚合能力，对目前的社区版则显得有些复杂，短期内估计不太会考虑。
> 
> btw 扫描问题我是更建议先通过 限频、防bot、人机验证 之类的能力来防护，优化日志管理的性价比确实不咋高。

那换种思路，增加ip攻击次数统计可行？
默认按照攻击次数排序，每个ip只出现一次
再加上多选和批量加入ip组

**Comment by Lorna0** [comment]
> > 搜索 IP 时支持搜索一个范围，这个需求确实有可能出现，可以考虑下。不过感觉跟这个 issue 关系不大，没法解决原始问题。
> > 聚合方面，攻击事件为了降低查询开销，是单独记录的一个数据表，不是临时查出来的。要是想聚合，得在 原始日志->攻击事件 上再加一层聚合功能。一些大型的 soc、siem 或者重数据的产品确实会有更完善的数据聚合能力，对目前的社区版则显得有些复杂，短期内估计不太会考虑。
> > btw 扫描问题我是更建议先通过 限频、防bot、人机验证 之类的能力来防护，优化日志管理的性价比确实不咋高。
> 
> 那换种思路，增加ip攻击次数统计可行？ 默认按照攻击次数排序，每个ip只出现一次 再加上多选和批量加入ip组

没太理解，增加 IP 次数统计是为了解决啥问题呢。如果出现 issue 背景里，“攻击者使用多个 IP 扫描” 的情况，IP 次数统计里这些 IP 排名肯定也不会很高，好像不解决原始问题呀。

感觉有点跑题了，最好能明确下想要的功能所对应的原始问题。

**Comment by dhfsqxz** [comment]
> > > 搜索 IP 时支持搜索一个范围，这个需求确实有可能出现，可以考虑下。不过感觉跟这个 issue 关系不大，没法解决原始问题。
> > > 聚合方面，攻击事件为了降低查询开销，是单独记录的一个数据表，不是临时查出来的。要是想聚合，得在 原始日志->攻击事件 上再加一层聚合功能。一些大型的 soc、siem 或者重数据的产品确实会有更完善的数据聚合能力，对目前的社区版则显得有些复杂，短期内估计不太会考虑。
> > > btw 扫描问题我是更建议先通过 限频、防bot、人机验证 之类的能力来防护，优化日志管理的性价比确实不咋高。
> > 
> > 
> > 那换种思路，增加ip攻击次数统计可行？ 默认按照攻击次数排序，每个ip只出现一次 再加上多选和批量加入ip组
> 
> 没太理解，增加 IP 次数统计是为了解决啥问题呢。如果出现 issue 背景里，“攻击者使用多个 IP 扫描” 的情况，IP 次数统计里这些 IP 排名肯定也不会很高，好像不解决原始问题呀。
> 
> 感觉有点跑题了，最好能明确下想要的功能所对应的原始问题。

1.简单去一下重能爬接口统计一下，现有的方式数据量会比较多，并且很多重复
2.增加批量加入ip组，减少工作量
3.限频、防bot、人机验证等操作会影响正常用户体验和搜索引擎爬虫

**Comment by Lorna0** [comment]
1. 

> > > > 搜索 IP 时支持搜索一个范围，这个需求确实有可能出现，可以考虑下。不过感觉跟这个 issue 关系不大，没法解决原始问题。
> > > > 聚合方面，攻击事件为了降低查询开销，是单独记录的一个数据表，不是临时查出来的。要是想聚合，得在 原始日志->攻击事件 上再加一层聚合功能。一些大型的 soc、siem 或者重数据的产品确实会有更完善的数据聚合能力，对目前的社区版则显得有些复杂，短期内估计不太会考虑。
> > > > btw 扫描问题我是更建议先通过 限频、防bot、人机验证 之类的能力来防护，优化日志管理的性价比确实不咋高。
> > > 
> > > 
> > > 那换种思路，增加ip攻击次数统计可行？ 默认按照攻击次数排序，每个ip只出现一次 再加上多选和批量加入ip组
> > 
> > 
> > 没太理解，增加 IP 次数统计是为了解决啥问题呢。如果出现 issue 背景里，“攻击者使用多个 IP 扫描” 的情况，IP 次数统计里这些 IP 排名肯定也不会很高，好像不解决原始问题呀。
> > 感觉有点跑题了，最好能明确下想要的功能所对应的原始问题。
> 
> 1.简单去一下重能爬接口统计一下，现有的方式数据量会比较多，并且很多重复 2.增加批量加入ip组，减少工作量 3.限频、防bot、人机验证等操作会影响正常用户体验和搜索引擎爬虫

1. 所以为啥要统计？最好能描述一下具体的场景。“统计攻击最多的 IP” 其实更像个蜜罐的需求。waf 和蜜罐不一样，拦了就结束了，一个 IP 拉黑之后请求再多次也没必要看了。btw 接口的话其实现在也能爬
2. 听上去有点像其它师傅提的自动拉黑？师傅觉得能用这个解决么
3. 搜索引擎爬虫可以直接加白。这些功能确实是要从正常请求中检查并剥离恶意请求，但是防护软件总归是要往这方面努力的，总不能让管理员每 10 分钟过来拉黑一次 IP 呀

**Comment by dhfsqxz** [comment]
> > > > > 搜索 IP 时支持搜索一个范围，这个需求确实有可能出现，可以考虑下。不过感觉跟这个 issue 关系不大，没法解决原始问题。
> > > > > 聚合方面，攻击事件为了降低查询开销，是单独记录的一个数据表，不是临时查出来的。要是想聚合，得在 原始日志->攻击事件 上再加一层聚合功能。一些大型的 soc、siem 或者重数据的产品确实会有更完善的数据聚合能力，对目前的社区版则显得有些复杂，短期内估计不太会考虑。
> > > > > btw 扫描问题我是更建议先通过 限频、防bot、人机验证 之类的能力来防护，优化日志管理的性价比确实不咋高。
> > > > 
> > > > 
> > > > 那换种思路，增加ip攻击次数统计可行？ 默认按照攻击次数排序，每个ip只出现一次 再加上多选和批量加入ip组
> > > 
> > > 
> > > 没太理解，增加 IP 次数统计是为了解决啥问题呢。如果出现 issue 背景里，“攻击者使用多个 IP 扫描” 的情况，IP 次数统计里这些 IP 排名肯定也不会很高，好像不解决原始问题呀。
> > > 感觉有点跑题了，最好能明确下想要的功能所对应的原始问题。
> > 
> > 
> > 1.简单去一下重能爬接口统计一下，现有的方式数据量会比较多，并且很多重复 2.增加批量加入ip组，减少工作量 3.限频、防bot、人机验证等操作会影响正常用户体验和搜索引擎爬虫
> 
> 1. 所以为啥要统计？最好能描述一下具体的场景。“统计攻击最多的 IP” 其实更像个蜜罐的需求。waf 和蜜罐不一样，拦了就结束了，一个 IP 拉黑之后请求再多次也没必要看了。btw 接口的话其实现在也能爬
> 2. 听上去有点像其它师傅提的自动拉黑？师傅觉得能用这个解决么
> 3. 搜索引擎爬虫可以直接加白。这些功能确实是要从正常请求中检查并剥离恶意请求，但是防护软件总归是要往这方面努力的，总不能让管理员每 10 分钟过来拉黑一次 IP 呀

1.统计是为了批量加入人机校验&整理需要拦截的ip段&其他waf同步配置
2.自动拉黑可以解决，只是统计界面还是太多太乱，不容易看
3.加白倒是没问题，护网期间基本每天至少看两次拉黑两次

**Comment by Lorna0** [comment]
> 1.统计是为了批量加入人机校验&整理需要拦截的ip段&其他waf同步配置
> 2.自动拉黑可以解决，只是统计界面还是太多太乱，不容易看 
> 3.加白倒是没问题，护网期间基本每天至少看两次拉黑两次

hvv 场景比较特殊，平时很难有人力盯着一个安全设备的攻击看的。
我觉得 waf 的事件多一些其实影响不大，反正都拉黑了，防护能力已经生效了，再看 IP 攻击量排名没有很大意义。

btw 对 waf 来说还有个问题是，规则类拦截会在内置攻击检测算法之前生效，包括黑名单、自动拉黑、防cc，以提高检测性能。这样 “IP 攻击量排名” 统计就会变得有点尴尬，不算规则拦截的好像少了，算上规则拦截的可能多了，总体不那么准确。这也是为啥我说这像个蜜罐的需求，因为蜜罐流量少、不需要拦截请求，分析攻击 IP 情况更加准确。

总的来说自动拉黑听上去还是能一定程度上解决原始问题，师傅可以先等等自动拉黑，到时候再感受一下。

**Comment by dhfsqxz** [comment]
> Collaborator

好的
感谢
