### ISSUE TITLE
[建议] 【攻击事件】支持 分类/排序，搭配预警通知

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#174]
### 背景与遇到的问题

![1e55accd5bbd3360fab1c110e12fdc7](https://github.com/chaitin/safeline/assets/51684966/4042e89e-39b7-4fbf-a0a9-0c7ca5052153)

希望能对【攻击事件】进行分类/排序（升序降序），有时候大量的低频（1次拦截）事件会刷屏，把正在进行中的高频攻击事件刷到后面几页去。
最好是能对功【攻击事件】分级，然后搭配预警通知。

**Comment by dhfsqxz** [comment]
+1

**Comment by Lorna0** [comment]
攻击事件本质上不是一个统计信息，而是 “攻击者的一次攻击行为”，更像一个特殊的日志列表，底层也是个独立的数据表。这么做强调时效性，查询开销低，长期使用后数据量会比较大。

这样的数据除了时间正序或倒序排列之外，其他排序都是不太合适的。可以类比一下，就像日志列表一般都只支持时间降序一样。

btw 光看图其实没有低频事件刷屏的问题，已经能展示到前一天的数据。背景问题是已经出现的情况么，如果是预测的话其实建议等出现了再具体反馈，因为有些场景是想象不出来的，很可能真的出现问题时，期望的解决方案又不太一样了。

**Comment by chuqiao8250** [comment]
界面上应该有访问日志展现，方便用户追溯，如果担心存储空间问题，可以增加日志保留控制，安全产品基本规范：一定要可追溯

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
