### ISSUE TITLE
同服务器宝塔和waf组合问题

### ISSUE THREAD

**Issue by jiespring** [chaitin/safeline#175]
### 反馈内容

宝塔ninx和waf在同一台服务器。网站之前是正常，然后解除了nginx对80和443端口的占用，宝塔nginx设置网站端口800和4430，waf设置80到127,0,0,1:800，设置443到127,0,0,1:4430，结果http和https，电脑上不正常。显示302错误，点开英文名高级选项，显示ssl域名证书是同服务器其他域名的ssl证书，加4430超时。手机上http正常，https显示证书错误或过期。

**Comment by DeronW** [comment]
宝塔强占了 80/443，并且会反复覆盖 nginx 配置，因为宝塔**托管了服务器**，这种宝塔占主动权的情况下，要么避开端口，要么避开宝塔。

备注：不止宝塔，运维面板都有类似的问题，灵活配置和方便管理很难兼顾

**Comment by jiespring** [comment]
1、如果增加1台云服务器，总共2台服务器，那个第2台在网络上是暴露的，需要特别设置，也增加成本。
2、如果不增加，可以把宝塔一类面板也装进docker内，然后用waf去代理容器内的web服务器，对外服务 ？

**Comment by DeronW** [comment]
1. 网络拓扑如何设计看你自己的实际情况，宝塔和waf 对于服务来说是必须还是可选，也根据你的实际情况来定
2. 宝塔是托管服务，这意味着，必须按照宝塔的要求安装，它才能托管，不能把宝塔装进 docker 里（个人觉得宝塔做的很好，很实用，但选择宝塔就必须按照它的规则操作）

宝塔和 waf 的矛盾在于争抢 80 和 443 端口，所以关键是避开这两个端口，端口冲突不能通过修改部署方式来解决。所以你的需求是：

- 只用一台服务器
- 安装宝塔
- 安装 waf
- 业务服务的地址上不显示端口号（也就是业务服务需要通过 80 或 443 端口方法）

以上 4 个条件，去掉一个就可以了，无法全部满足

**Comment by jiespring** [comment]
好的，感谢指导

**Comment by Gingmzmzx** [comment]
您可以把`/www/server/panel/vhost/nginx/*.conf`以及nginx.conf中的80端口和443端口替换成别的端口就可以了，但是用宝塔修改站点配置的时候可能会再自动加上`listen: 80;`，需要自己再删掉。
