### ISSUE TITLE
[建议] 能否自定义拦截规则

### ISSUE THREAD

**Issue by minghuinet** [chaitin/safeline#177]
### 背景与遇到的问题

当遇到0day或者绕过时，及时通过添加payload关键字进行自定义规则进行拦截

**Comment by zclaiqcc** [comment]
啥意思？黑白名单不能够满足需求？

**Comment by minghuinet** [comment]
哦，忘了这茬了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaitin/safeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月28日(星期五) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chaitin/safeline] [建议] 能否自定义拦截规则 (Issue #177)





 
啥意思？黑白名单不能够满足需求？
