### ISSUE TITLE
[Bug] waf被绕过，前台页面显示拦截信息错误。

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/safeline#178]
### 问题描述

雷池版本：2.3.2

1、前台页面显示已拦截并且已阻断，实际上数据包已经打到后端服务器中。
**后端服务器日志**
![image](https://github.com/chaitin/safeline/assets/42514273/ddb4c7c4-d191-49e1-a505-9af8273cee3c)
**2、雷池前端显示已拦截**
![image](https://github.com/chaitin/safeline/assets/42514273/8b1dbf6a-4fe9-45f9-bdc2-fcd51176f094)
![image](https://github.com/chaitin/safeline/assets/42514273/3b6d4c36-dbd0-4074-bee3-9ab6ac184c8d)

**Comment by yrluke** [comment]
师傅这个截图的这个攻击载荷和师傅日志中截图的看上去不是同一条命令，日志里的也不是全部都是攻击的请求

**Comment by zclaiqcc** [comment]
不好意思，没有太看出来被绕过，求细化一下？

看上去是扫描器构造了很多不同的 UserAgenet，有的有攻击 payload，有的没有。有攻击的已经拦截了，过去的那些都没有攻击，雷池工作一切正常 😄

**Comment by James-ci-git** [comment]
现在主要问题是正常雷池这边提示拦截、阻断，那么后端服务器中是不会产生日志，如果雷池提示了拦截而后端服务器中又产生了请求日志这样的情况不属于软件BUG？

**Comment by Lorna0** [comment]
现有信息无法继续排查了，issue 先关闭，师傅有更多信息的话可以再评论一下
