### ISSUE TITLE
[建议] 对于新版的tengine

### ISSUE THREAD

**Issue by ylwzbk** [chaitin/SafeLine#179]
### 背景与遇到的问题

雷池使用tengine作为代理 前几天时隔多年 tengin终于发布了tengine3.0.0 并同步更新nginx1.24 ，希望雷池官方也跟进一下版本  发布一个tengine3.0.0的beta版本 用于广大同胞 提前尝鲜并反馈遇到新版本的问题

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/524
