### ISSUE TITLE
Cento7安装报错：* error decoding 'Volumes[2]': invalid spec: :/logs: empty section between colons 排错文档中未找到解决方法，请大佬解答下

### ISSUE THREAD

**Issue by Co1t5f0ot** [chaitin/safeline#18]
![image](https://user-images.githubusercontent.com/78132218/232368883-06bbf34d-a7f9-466f-b236-20908fbe5ae7.png)

**Comment by zclaiqcc** [comment]
setup.sh 执行失败了？看起来 .env 文件没有生成

**Comment by luweijun1992** [comment]
> ![image](https://user-images.githubusercontent.com/78132218/232368883-06bbf34d-a7f9-466f-b236-20908fbe5ae7.png)

执行的时候去掉sudo，直接docker compose up -d

**Comment by Co1t5f0ot** [comment]
> 



> > ![image](https://user-images.githubusercontent.com/78132218/232368883-06bbf34d-a7f9-466f-b236-20908fbe5ae7.png)
> 
> 执行的时候去掉sudo，直接docker compose up -d

不行哦
![image](https://user-images.githubusercontent.com/78132218/232464317-a0b9b673-2c83-42ea-9fd8-c3dc90992f66.png)

**Comment by Co1t5f0ot** [comment]
> > ![image](https://user-images.githubusercontent.com/78132218/232368883-06bbf34d-a7f9-466f-b236-20908fbe5ae7.png)
> 
> 执行的时候去掉sudo，直接docker compose up -d

谢谢大佬们解答，重新拉取一下可以安装了，估计之前的安装包有问题
