### ISSUE TITLE
建议弄一个SSL证书库

### ISSUE THREAD

**Issue by miaowmint** [chaitin/safeline#180]
### 背景与遇到的问题

现在的SSL证书部署起来很繁琐，站点多了之后更新证书需要每个站点都单独进行配置

### 建议的解决方案

希望能推出一个证书库功能，直接把证书通过文件或直接输入的方式上传到证书库，然后SSL证书可以直接一键使用证书库里的证书，具体可以参考宝塔面板的证书夹

**Comment by Lorna0** [comment]
duplicate https://github.com/chaitin/safeline/issues/111
