### ISSUE TITLE
[建议] 支持更多证书格式 / 支持上传 CER 证书

### ISSUE THREAD

**Issue by wenskys** [chaitin/safeline#181]
### 背景与遇到的问题

1.目前似乎只支持crt格式，不少项目是cer格式，上传会报错
2.增加证书库，方便有域名的接入

### 建议的解决方案

1.支持DER、PEM、CER、CRT等格式
2.增加证书库，方便有域名的接入

**Comment by Lorna0** [comment]
1. 目前 pem、crt 本身就可以直接上传，cer 我们之后加一下，应该下两个版本就能用上。der 和其他的就暂不考虑了，证书格式太多，支持起来有点麻烦，可以手动转一下 pem 使用，确实需要的话另外再提个 issue 跟进吧
2. 证书库需求 duplicate https://github.com/chaitin/safeline/issues/111

**Comment by wenskys** [comment]
@Lorna0 嗯嗯，麻烦师傅支持下，能支持cer就够了

**Comment by zclaiqcc** [comment]
.cer 已支持
