### ISSUE TITLE
[建议] 独立的SSL证书管理

### ISSUE THREAD

**Issue by ttttmr** [chaitin/safeline#182]
### 背景与遇到的问题

有多个业务站点
```
w1.a.com
w2.a.com
w3.a.com
...
```
他们都使用`*.a.com`证书，每个站点都要上传一次证书，创建站点和证书更新都比较麻烦

### 建议的解决方案

独立的证书管理

站点可以直接引用里面的证书，并自动同步证书管理中的更新

不过如果能实现#92 也能变相解决问题

**Comment by Lorna0** [comment]
duplicate : 
* https://github.com/chaitin/safeline/issues/111
