### ISSUE TITLE
[建议] 人机校验页面优化

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#184]
### 背景与遇到的问题

![image](https://github.com/chaitin/safeline/assets/51684966/7f2b0442-161b-4e0e-aa28-fdaf0cdbe0b1)

1、适老化#字体放大，页面篇幅够的

2、交互按钮放大，按钮背景颜色是灰色，
不够突出

3、hash计算验证时间过长，7/8秒会导致
消费者误认为页面卡死。
可以参考cloudflare 5秒盾一样的倒计时。
倒计时起到安慰剂作用，不至于退出页面。

4、上方空白区域较大，可以加个雷池LOGO丰满一下，还挺好看的。

**Comment by Lorna0** [comment]
1. 文字比较小是因为主要适配的 pc，可以针对移动端优化一下，把文字放大
2. 同上
3. 目前的 hash 计算时间是不确定的，可能从 1s 内到十几秒不等，所以没办法倒计时，我们还没想到比较好的优化方案。另外总是 7/8 秒的话有可能是网络有些问题，师傅可以具体排查下
4. 感谢认可。这个页面比较简单的原因是人机验证容易被正常用户触发，样式太丰富的话容易和实际网站的风格差别太大，给网站用户造成比较强的割裂感。我们尝试美化一下

**Comment by Lorna0** [comment]
2.5 版本适配了移动端，文字和图案不会太小了

**Comment by gospider007** [comment]
能不能无感验证啊，等待时间这么长没有意义吧

**Comment by DeronW** [comment]
@ezjbc  人机验证已升级，现在是否还有疑问？ 如没有的话，准备关闭这个问题了

**Comment by ezjbc** [comment]
> @ezjbc 人机验证已升级，现在是否还有疑问？ 如没有的话，准备关闭这个问题了

关闭吧
