### ISSUE TITLE
[建议] 开启ssl后支持开启强制https模式

### ISSUE THREAD

**Issue by deric0314** [chaitin/SafeLine#186]
### 背景与遇到的问题

原系统使用自义定端口，原端口为http协议，加上证书后原端口会报【The plain HTTP request was sent to HTTPS port】，建议支持强制将497状态，重定向到https协议

**Comment by Lorna0** [comment]
已加到 3.0 版本中：
![image](https://github.com/chaitin/safeline/assets/56920727/18e5a3cd-814a-442c-b293-6b4260281f7a)
