### ISSUE TITLE
[Bug] 超长URL地址未被拦截

### ISSUE THREAD

**Issue by James-ci-git** [chaitin/safeline#188]
### 问题描述

**1、现象**
![image](https://github.com/chaitin/safeline/assets/42514273/06b5ae53-82ed-48ac-9b5d-40e5ae9e0cc1)

**2、后端服务器日志**
![image](https://github.com/chaitin/safeline/assets/42514273/c6f96767-9106-4a64-946c-3bf2eea5f067)
![image](https://github.com/chaitin/safeline/assets/42514273/2ebb6f76-02f1-43fa-866b-dafb4e22c2aa)

3、雷池版本：2.3.2

**Comment by James-ci-git** [comment]
哈哈、看来这是一种绕过waf的好方法。

**Comment by Lorna0** [comment]
这个本质上就是超大数据包绕过，大包绕过是一个众所周知又难以解决的问题，原因是 WAF 检测大包会消耗过量的 CPU、内存资源。

补充一下技术背景，

为啥很多 WAF 都存在大包绕过问题，而大家不赶紧攻克呢。因为 “WAF 绕过” 只是业务攻击的第一步，实际上这个大数据包必须得业务处理了、产生恶意效果才有可能造成威胁。而很多业务根本就不处理大包，像这个 issue 里的业务就直接返回了 400。所以 WAF 大包绕过很难实际用于攻击，虽然长亭企业版仍然在攻坚这个问题，但是对于社区版 waf，搞这个实在没啥必要。
