### ISSUE TITLE
[建议] 网站处于维护模式下，系统能自定义维护标语

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#191]
### 背景与遇到的问题

![image](https://github.com/chaitin/safeline/assets/51684966/bc91a7da-bf22-4126-b05e-9c1922f649d9)
网站处于维护模式下，系统能自定义维护标语。
比如，告知用户预计恢复时间及维护原因。

**Comment by luweijun1992** [comment]
让商业版支持下自定义页面。

**Comment by safe1ine** [comment]
专业版已支持自定义
