### ISSUE TITLE
[建议] 希望在拦截页面，可以显示自定义管理员联系方式

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#192]
### 背景与遇到的问题

![image](https://github.com/chaitin/safeline/assets/51684966/b64a0630-3281-43e4-86dc-783a7004ca40)
希望在拦截页面，可以显示自定义管理员联系方式，方便排查误拦截

**Comment by pusidun** [comment]
这个在tengine里改下拦截页面的response body就行吧

**Comment by ezjbc** [comment]
> 这个在tengine里改下拦截页面的response body就行吧

升级后，配置还能保留么

**Comment by zclaiqcc** [comment]
> > 这个在tengine里改下拦截页面的response body就行吧
> 
> 升级后，配置还能保留么

可能不只是升级，修改完都保留不了 :P

**Comment by luweijun1992** [comment]
让商业版支持下自定义页面。

**Comment by calvin-git-hub** [comment]
自己改完之後,一分鐘內會自動回復到原來頁面,可能有保護?

**Comment by zhuanmentiwen** [comment]
能增加管理员邮箱是最好的。。这样业务拦截后知道联系谁。确实有用。。不过最好不要修改配置文件，能在后台有这个更改邮箱的功能，如果不设置默认就是空。

**Comment by linkangren** [comment]
拦截页面不能自定义真的很烦

**Comment by zhuanmentiwen** [comment]
能让在这个页面下面或上面给我们留一行空位能添加文字即可。

**Comment by Lorna0** [comment]
3.3 版本已发布：

**Comment by luweijun1992** [comment]
> 3.3 版本已支持： ![image](https://user-images.githubusercontent.com/56920727/266543469-b66af2f0-7781-41a3-94c3-0b5ac683c18d.png)

附加说明有点跟下面ID、时间相视了，感觉两者有点差别会比较好看。个人意见
![image](https://github.com/chaitin/SafeLine/assets/58923704/60dce16d-4277-4f9b-a505-f8f80166e2cb)

**Comment by Lorna0** [comment]
> > 3.3 版本已支持
>  @luweijun1992 
> 附加说明有点跟下面ID、时间相视了，感觉两者有点差别会比较好看。个人意见

是有点，下期调一下字号和字色

**Comment by Lorna0** [comment]
3.4 中调整了拦截页面的样式细节：
![image](https://github.com/chaitin/SafeLine/assets/56920727/39921f1f-1e80-44c4-b2d1-ee2e93200062)

issue 可以算完成了。
