### ISSUE TITLE
[建议] 建议增加 端口 的攻击事件搜索项

### ISSUE THREAD

**Issue by DevilHunterXX** [chaitin/safeline#193]
### 背景与遇到的问题

当防护的站点为 ip + port 的形式时，无法单独搜索某个站点的攻击情况，目前相关的搜索项只有 域名、域名，无法按 端口 进行搜索

### 建议的解决方案

建议增加 端口 的搜索项

**Comment by Lorna0** [comment]
2.6 版本可以按照端口搜索日志了，可以试试
