### ISSUE TITLE
一键脚本的wget错误提示优化

### ISSUE THREAD

**Issue by miaowmint** [chaitin/safeline#194]
### 反馈内容

有的人的服务器上没有wget命令，会导致compose.yaml下载失败，但是对于很多小白来说提示不够明显，只有系统默认的`command not found` 和脚本提示的`下载compose.yaml脚本失败`
希望在出现这个错误的时候脚本会在最后标红打印类似“服务器上没有wget指令，请使用XXX命令安装wget软件包”这样的提示
（这几天在群里看到好几个这样的了）

**Comment by luweijun1992** [comment]
v2.6.0 更新已优化

**Comment by yrluke** [comment]
是的，这个版本改成了直接使用curl下载，相比于wget会有更高的兼容性
