### ISSUE TITLE
[建议] 希望增加自定义DNS功能

### ISSUE THREAD

**Issue by penndu** [chaitin/safeline#195]
### 背景与遇到的问题

容器内nameserver缓存时间较长，DDNS变动时，新IP生效速度较慢，希望可以自定义容器nameserver，或者直接使用系统的nameserver。

**Comment by zclaiqcc** [comment]
现在应该就是使用的 /etc/resolv.conf 吧，是说希望自定义成别的么？可以看下 compose.yaml 中 safeline-tengine 的 volume 配置

**Comment by penndu** [comment]
> 

收到，感谢！
