### ISSUE TITLE
[建议] 希望可以通过API修改回源IP / OpenAPI

### ISSUE THREAD

**Issue by penndu** [chaitin/SafeLine#196]
### 背景与遇到的问题

回源地址域名绑定了DDNS，变动时新IP生效速度慢，希望可以增加API修改回源IP功能，方便快速生效~

**Comment by HookSafe** [comment]
感觉你的这需求不像是waf能做到的吧？不应该是找你ddns服务商吗？要想解析的快拿钱出来买收费套餐呀

**Comment by Lorna0** [comment]
Open API 类的需求短期内不会考虑，主要是因为目前功能迭代还很快，API 常常有小改动，不容易固定下来。

不过雷池后台开放的接口都是基于 Restful 架构开发的，也没有特地做什么限制，使用登录后的 Cookie 就可以调用（登录接口本身也可以调用，就是麻烦点），只是不保证稳定。非常需要的话可以自行研究一下现有接口，官方就不提供技术支持了。

**Comment by ws20940548** [comment]
用这个方案就不需要ddns了 https://www.bilibili.com/video/BV1X94y1x76i/?share_source=copy_web&vd_source=647325f36d551afb632dd48c70e03587

**Comment by Lvshujun0918** [comment]
> 用这个方案就不需要ddns了 https://www.bilibili.com/video/BV1X94y1x76i/?share_source=copy_web&vd_source=647325f36d551afb632dd48c70e03587

这个和ddns还是有本质区别的

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
