### ISSUE TITLE
[建议] 增加告警的对接（邮件、短信、微信等）以及大屏展示

### ISSUE THREAD

**Issue by lizhiyuan0122** [chaitin/safeline#197]
### 背景与遇到的问题

我在使用waf监控的时候，需要一直盯着系统页面，希望能增加告警的对接（邮件、短信、微信等）以及大屏展示，这样全面的显示waf的能力与效果。

### 建议的解决方案

增加告警的对接（邮件、短信、微信等）以及大屏展示

**Comment by Lorna0** [comment]
关于告警：
* 微信 duplicate https://github.com/chaitin/safeline/issues/109
* 短信的服务商非常多，没办法一一支持，最多通过 webhook 做，有个 issue 是 https://github.com/chaitin/safeline/issues/138

我们会优先考虑上面两种告警方式。邮件需要配置 SMTP 服务器，会有些复杂，而且体感用邮件的人好像没有那么多了。

关于大屏，大屏是一个非常企业的需求，做起来也比较麻烦，社区版估计不会考虑。目前 “数据统计” 页面是特地适配了 1920*1080 的屏幕大小，师傅可以先用这个顶一下（目前好像不会自动刷新，回头可以加一个）。

PS. 一个 issue 里提多个需求，会让人分不清大家点赞的具体是哪个，更建议师傅分开提，比较容易集中讨论。issue 我先关了，邮件告警、大屏 师傅确实有需要的话可以单独提一下，我们看看社区啥意见。
