### ISSUE TITLE
[建议] 频率限制增加IP地址归属地显示

### ISSUE THREAD

**Issue by luis265165gonzalez327** [chaitin/safeline#198]
### 背景与遇到的问题

我们主要面对的是本地用户，因此很多本地的IP可能被误封，为了优化策略需要判断封禁列表里的用户IP地址来源，因此希望在频率限制列表里增加IP地址归属地显示

**Comment by luweijun1992** [comment]
意思是在IP后面加上地区地段，这个应该不复杂，毕竟当前攻击事件已经有了。
![image](https://github.com/chaitin/safeline/assets/58923704/897e3296-3221-43b5-8630-ad17d369389d)
![image](https://github.com/chaitin/safeline/assets/58923704/d8712ae1-d2b7-40af-b791-49a84d831197)

**Comment by luweijun1992** [comment]
@luis265165gonzalez327 v2.6.0 已增加，请升级使用。
