### ISSUE TITLE
[建议] 地理区域封禁

### ISSUE THREAD

**Issue by sxliuxianlin** [chaitin/safeline#199]
### 背景与遇到的问题

一键封禁来自特定区域的客户端IP，比如公司OA网站，只允许北京客户端IP地址访问，那么除北京以为的中国其他省市和境外全部拒绝访问。

![image](https://github.com/chaitin/safeline/assets/135944875/31c73c90-55e1-4b94-9c5e-2d05a8e8f782)

**Comment by luweijun1992** [comment]
挂代理去访问呢，治标不治本。
但也是一个不错功能，提高了非法用户的攻击成本。
这个地区库也要准确及时更新~

**Comment by Lorna0** [comment]
集中到这里讨论吧：
- https://github.com/chaitin/safeline/issues/88

地理位置目前的主要问题是准确度，免费的库准确性都一般，封禁到省份这个纬度，问题会更加明显，很容易误拦或者漏拦。
