### ISSUE TITLE
如何修改流量解析部分的源码？

### ISSUE THREAD

**Issue by wangdawai** [chaitin/safeline#20]
目前仓库自有一个docker安装脚本，运行也是基于docker远行，如何获取源码，进行自定义修改和部署了？

**Comment by zclaiqcc** [comment]
SafeLine 源码不开源，直接下载 docker 镜像运行即可。并不支持功能上的二次开发，参考 LICENSE https://github.com/chaitin/safeline/blob/main/LICENSE.md

如果是想自定义安装或者部署参数等，可以参考 [FAQ](https://github.com/chaitin/safeline/blob/main/FAQ.md#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89-safeline-%E5%AE%89%E8%A3%85%E8%B7%AF%E5%BE%84)
