### ISSUE TITLE
[建议] 新增黑名单订阅功能

### ISSUE THREAD

**Issue by edu-hui** [chaitin/safeline#200]
### 背景与遇到的问题

能不能增加一个黑名单订阅的功能，就是一个txt文件的地址，里面写的都是黑名单，然后可以通过链接获取ip自动解析生效这种，这样便于维护以及分享黑名单

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/safeline/issues/164

可以参考下相关回复
