### ISSUE TITLE
[建议] waf证书配置 / 界面修改管理后台的证书

### ISSUE THREAD

**Issue by qq8554650** [chaitin/SafeLine#201]
### 背景与遇到的问题

已知配置目录 /data/safeline/resources/management/certs，crt格式
一般申请的证书为cer，需要转换
能不能把证书配置弄到界面上来呢

**Comment by Lorna0** [comment]
证书在 2.5 版本就支持 cer 格式了。

难道是指 9443 管理后台的证书吗？

**Comment by qq8554650** [comment]
> 证书在 2.5 版本就支持 cer 格式了：
> 
> * [[建议] 支持更多证书格式 / 支持上传 CER 证书 #181](https://github.com/chaitin/safeline/issues/181)
> 
> 难道是指 9443 管理后台的证书吗？

是。我想在界面上配置https://a:9443的证书

**Comment by Lorna0** [comment]
3.1 版本已支持
