### ISSUE TITLE
[建议] 异常流量转发蜜罐

### ISSUE THREAD

**Issue by baibaiii** [chaitin/SafeLine#202]
### 背景与遇到的问题

1、目前社区2.5.0版本，频率限制，仅支持实现封禁IP功能。
想实现检测到异常流量。实现无感知重定向蜜罐，和自动风险判断触发 人机验证功能，避免正常访问用户被误封禁。影响正常访问。

2、后台开启waf误报 申诉功能，后台此功能由管理员定义是否开启。当正常用户被封禁，提交申请理由一键申诉

**Comment by Lorna0** [comment]
看起来有异常流量转发蜜罐、异常流量触发人机验证、后台 waf 误报申诉 三个需求。
建议拆成不同的 issue，每个 issue 只描述一件事，这样社区讨论、官方跟踪才能比较集中。
这个 issue 就只讨论第一个 “异常流量转发蜜罐” 吧，其他有需要的话麻烦师傅单独提一下。

**Comment by qystudio0** [comment]
异常流量转发到蜜罐感觉还是很实用的

**Comment by TScci** [comment]
一般来讲蜜罐应该对正常业务零打扰，这类网络架构放正式环境不合适吧

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
