### ISSUE TITLE
[建议] 增加负载均衡功能

### ISSUE THREAD

**Issue by warmsheep** [chaitin/safeline#203]
### 背景与遇到的问题

想用雷池代替Nginx，但是发现没有这块功能，在最前端安装雷池后，连接后面的多台业务系统服务器，中间还是得加一个Nginx服务器来做负载均衡才行。建议增加负载均衡功能。

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/safeline/issues/46

搜一下 “负载均衡” 就能搜到了。
