### ISSUE TITLE
[建议] 增加证书管理管理

### ISSUE THREAD

**Issue by warmsheep** [chaitin/safeline#204]
### 背景与遇到的问题

在添加站点时,xxx.a.com,yyy.a.com,ccc.a.com都是同一域名的证书，建议增加一个证书管理模块，自动匹配域名证书，不用在添加站点时反复上传同一个文件。

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/safeline/issues/111

搜 “证书管理” 就可以找到了。
