### ISSUE TITLE
webscoket协议是否支持

### ISSUE THREAD

**Issue by hzl7652** [chaitin/safeline#206]
### 反馈内容

站点有使用 webscoket 协议，是否支持 webscoket  代理，站点带有 webscoket  如何进行站点配置

**Comment by Trenck** [comment]
/data/safeline/resources/nginx/sites-enabled 下边是每个站点的配置文件，有一行 include proxy_params;
这个proxy_params里默认已经开启了websocket

**Comment by zclaiqcc** [comment]
师傅直接配置站点就行，webscoket 是包含在 HTTP 和 HTTPS 协议里面的。

对于 websocket 请求，支持转发，但是只支持对第一个建立连接的包进行检测，后续的包不会进行检测。

**Comment by hzl7652** [comment]
@zclaiqcc @Trenck 知道了，谢谢
