### ISSUE TITLE
你好, 请问雷池对127.0.0.1有没有起防护效果?

### ISSUE THREAD

**Issue by cachexy123** [chaitin/safeline#207]
### 反馈内容

比如我的服务器部署了应用网关, 这个网关防护效果并不是那么好, 所以也部署了雷池(同一服务器), 现在流量是先经过网关然后转发127.0.0.1:81, 81这个口是雷池监听的端口,雷池再将流量转发到业务网站, 请问, 这中间雷池起到了防护效果吗?

**Comment by DeronW** [comment]
有效果，只要流量经过雷池，就能起到防护效果。雷池的防护能力来自语义引擎，它的优势就是通过访问中的内容来判断是否存在威胁，不论流量来自内网还是外网。

补充：
并且网关转发流量的时候可以把原始 IP 添加到 header 中，这样雷池能获取到原始 IP，这样与 IP 防护相关的功能也可以继续使用，并且这种用法也比较常见

**Comment by cachexy123** [comment]
> 有效果，只要流量经过雷池，就能起到防护效果。雷池的防护能力来自语义引擎，它的优势就是通过访问中的内容来判断是否存在威胁，不论流量来自内网还是外网。
> 
> 补充： 并且网关转发流量的时候可以把原始 IP 添加到 header 中，这样雷池能获取到原始 IP，这样与 IP 防护相关的功能也可以继续使用，并且这种用法也比较常见

感谢解答!!!
