### ISSUE TITLE
[Bug] 攻击 IP 识别为了内网 IP

### ISSUE THREAD

**Issue by hmilyfyj** [chaitin/safeline#208]
### 问题描述

我配置了通过 header （x-forwarded-for）获取源 ip，如图 1。当 x-forwarded-for 中包含两个 IP 时，攻击 IP 就会被识别为内网 IP （100.127.132.97，是上游阿里云 alb 的内网 IP ），如图 2。

<img width="441" alt="image" src="https://github.com/chaitin/safeline/assets/10796377/7e6ae722-23d8-48a9-a177-d4371f79f9f6">

<img width="936" alt="image" src="https://github.com/chaitin/safeline/assets/10796377/5ee79208-dfb9-4920-9966-d7063167e003">

### 复现方法

请求报文

```
GET /?sql=select%20*%20from%20test HTTP/1.1
RemoteIp: 112.254.203.1111
X-Forwarded-For: 1.1.1.1, 112.254.203.111

```

### 期望的结果

攻击 IP 识别为 112.254.203.1111。

**Comment by Lorna0** [comment]
112.254.203.1111 不是一个合法 IP。
师傅 “源 IP 获取方式” 配的是 “RemoteIp”，我猜测是 waf 先取了 RemoteIp 里的 112.254.203.1111，发现并不合法，所以转而取了 socket IP，也就是原本的直接源 IP。

师傅可以把请求体里的 112.254.203.1111 改成 112.254.203.111 再试一次

**Comment by zclaiqcc** [comment]
我这边找了两个环境实测了一下，都是可以正常从 `RemoteIp` 中解析出来源 IP 的，截图如下：

![image](https://github.com/chaitin/safeline/assets/6045228/f76e1c60-eb1b-4bb4-894f-1c44f59cae37)

师傅最开始提问的时候说自己配置的是 `X-Forwarded-For` 作为源 IP 获取方式的字段，但是截图中是 RemoteIp，不知道是哪个地方没有对齐。如果是用的 `X-Forwarded-For`，当出现多个的时候，目前确实不会解析成功。因为没有配置解析倒数或者正数第几个 IP，会整体当作 IP 解析。解析失败之后就默认使用 socket ip。

如果配置的是 `RemoteIp`，那确实有点奇怪了。我有一个脑洞的猜测，有没有可能是字母写错了，因为 `I`（字母 i 的大写） 和 `l`（字母 L 的小写）在系统的字体下看起来是一样的（下面截图一个是 `I` 一个是 `l`）。不知道师傅要不要复制一下 `RemoteIp` 这个字符串，粘贴到源 IP 获取方式配置的输入框里面保存，再试一下呢？
![image](https://github.com/chaitin/safeline/assets/6045228/4ceacb11-37d7-4952-ad04-2e371f2d6951)

**Comment by shanjunmei** [comment]
毫无诚意，明明因为程序员知识储备不足写的bug，天天讲什么社区版企业版，不想着把产品做好，靠这能绑架用户付费？
