### ISSUE TITLE
[suggestion] Config Rate Limiting by host or website or urlpath / 频率限制基于 host 或站点或 URL

### ISSUE THREAD

**Issue by onlyaiai0516** [chaitin/SafeLine#209]
### 背景与遇到的问题

目前只能基于时间和访问次数判断高频攻击，希望高频策略加入host和URL维度，这样就可以对重点接口进行CC防御

**Comment by tn919871** [comment]
希望能增加此功能，單純by pass ip頻率限制，但仍保有攻擊防護機制

**Comment by cddqssc** [comment]
家人们，点点赞，👍高的优先解决

**Comment by qq280948982** [comment]
这场真的很急需，希望能优先开发。因为爬虫大多数都是针对某个或某些页面抓取的，所以希望能针对特定URL的页面做高频监控和拦截，再拜托了！！

**Comment by xbingW** [comment]
目前已经支持站点级别的频率限制， 其他问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
