### ISSUE TITLE
[建议] 希望可以提供修改日志存储时间范围的功能

### ISSUE THREAD

**Issue by Cyrus74** [chaitin/safeline#211]
### 背景与遇到的问题

比如攻击日志和访问日志可以设定存储最近15天，最近7天等范围，超出时间的自动清理，目前日志手动清理比较麻烦呢

**Comment by luweijun1992** [comment]
是的，可以设置保留天数。
比如有的只需要1个月、3个月、6个月等。

**Comment by Lorna0** [comment]
跟这个 issue 差不多：
* https://github.com/chaitin/safeline/issues/63

合并到那边集中讨论吧
