### ISSUE TITLE
[建议] 上游服务器支持多 Host 负载均衡

### ISSUE THREAD

**Issue by D0n9** [chaitin/safeline#212]
### 背景与遇到的问题

接入层中使用到多台 Nginx 负载业务流量，Safeline 添加站点时 “上游服务器” 只支持单 IP 

虽然也可以用 LB 的方式实现负载均衡，但毕竟又多了一层转发，不够优雅

### 建议的解决方案

1. Safeline 添加站点时 “上游服务器” 支持多 IP 负载均衡、源站存活检查。

**Comment by dossec** [comment]
建议不错，期待

**Comment by luweijun1992** [comment]
等后续版本更新把。
或者上长亭雷池企业版，支持的。
https://www.chaitin.cn/zh/safeline

**Comment by Lorna0** [comment]
负载均衡的 issue 已经有了，先搜索一下啦：
* https://github.com/chaitin/safeline/issues/46
