### ISSUE TITLE
请问safeline-detector 模块的代码在哪个git？

### ISSUE THREAD

**Issue by heqiqi** [chaitin/SafeLine#213]
### 反馈内容

想要学习下。

**Comment by luweijun1992** [comment]
长亭雷池社区版只是免费使用，不开源。

**Comment by heqiqi** [comment]
> 

谢谢，了解了。

**Comment by Lorna0** [comment]
waf 不会完全开源，但是语义分析检测引擎的核心代码长亭是有开源的，可以看这里：https://github.com/chaitin/yanshi
