### ISSUE TITLE
问一下如果是这种应用是否能使用

### ISSUE THREAD

**Issue by GOOLDOVE** [chaitin/safeline#214]
### 反馈内容

我是一个游戏服的服主，我想在一个命名为gameserver.exe上，他会有四个端口对外链接，游戏客户端，另一个后台面板和其他两个程序需要访问这四个端口，请问能在safeline上部署吗？

**Comment by D0n9** [comment]
safeline 是七层防火墙，主要应对的是 Http/s 层的应用防火墙。

游戏服务器不适合用 safeline

**Comment by Lorna0** [comment]
WAF 是 Web Application Firewall，专注于防护 Web 应用。你说的后台面板或程序如果是 Web 网站，那么可以使用雷池代理和防护，如果非 Web ，那无法进行代理和防护。

PS. 非 Web 如果不需要防护，只想转发的话，有一个相关 issue，可以在里面讨论：
* https://github.com/chaitin/safeline/issues/123
