### ISSUE TITLE
[建议] 攻击事件攻击IP应标记已加入IP组

### ISSUE THREAD

**Issue by sxliuxianlin** [chaitin/SafeLine#215]
### 背景与遇到的问题

在分析攻击事件中时，无法确定哪些攻击IP已加入IP组

### 建议的解决方案

方案一：增加一列字段是否加入IP组
方案二：鼠标移动到攻击IP上，目前提示加入IP组，如果已加入IP组，提升已加入IP组。

**Comment by jssolo** [comment]
其实可以在现有的IP那一列中加入一个图标来标识改ip属于IP组，等鼠标移入到ip时，展示所归属的所有IP组，这样可以最小程度影响现有的展示结构

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
