### ISSUE TITLE
[建议] 增加基于token或其令牌方式的api认证

### ISSUE THREAD

**Issue by onedaycodes** [chaitin/SafeLine#216]
### 背景与遇到的问题

目前想通过现有的黑白名单，人机验证功能的API实现通过编写工具，来批量添加黑白名单，或者修改站点运行模式。
添加黑名单，修改站点运行模式使用现有API可以实现上述功能，但是就是无法通过现有身份认证机制自动完成获取身份凭证，只能手工添加身份认证凭证才可以，而且还存在过期失效问题。

### 建议的解决方案

建议增加针对使用api的身份认证机制，比如token等方式，可以动态管理token，以及设置token访问限制，基于IP或者自定义请求头字段的方式来做安全限制。最后补充：雷池WAF 世界上最好用的社区WAF

**Comment by Lorna0** [comment]
OpenAPI 相关问题可以先参考这个 issue 下的回复，估计短期内不会考虑：
* https://github.com/chaitin/safeline/issues/196#issuecomment-1667510507

**Comment by LHC12580** [comment]
大佬能不能做一个抖音绕过实名认证模块插件？

**Comment by xbingW** [comment]
最新版 6.9.0 已支持 api token 的方式
