### ISSUE TITLE
[建议] 防护站点模块增加禁用状态

### ISSUE THREAD

**Issue by onedaycodes** [chaitin/SafeLine#217]
### 背景与遇到的问题

我需要在某段时间里面，先关停某个已添加的站点，不想删除站点，但是还不想暴露端口在外面（维护模式不行），只想保留站点配置记录，等需要启用站点时，直接启用该站点即可。

### 建议的解决方案

建议”防护站点“增加站点启用和禁用功能，禁用功能只删除站点运行配置，保留站点记录配置记录（包括SSL，端口等参数）。禁用后再启用可以重新创建站点代理运行配置。

**Comment by Lorna0** [comment]
啥情况下关停站点还不想暴露端口在外面呢，有没有具体一些的场景。

btw 企业版是支持直接禁用的。

**Comment by onedaycodes** [comment]
比如Hvv情况下，或者import time情况下等需求

**Comment by Lorna0** [comment]
> 比如Hvv情况下，或者import time情况下等需求

听起来比较企业，社区版估计不会优先支持。看看大家的意见。

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
