### ISSUE TITLE
[建议] 增加后台登录日志

### ISSUE THREAD

**Issue by onedaycodes** [chaitin/SafeLine#218]
### 背景与遇到的问题

想了解雷池是否被恶意尝试登录过，好做恶意IP封禁操作，以及知道雷池登录时间的日志信息

### 建议的解决方案

建议增加雷池的登录事件日志信息，包括常见的登录IP，时间，失败和成功情况，useragent等信息；如果是尝试恶意登录，建议做源IP限制措施，比如禁止登录10分钟。
建议增加登录源IP白名单。

**Comment by Lorna0** [comment]
访问源 IP 限制已有重复 issue，集中到那边讨论吧：
* https://github.com/chaitin/safeline/issues/137

这个 issue 里只讨论 “增加后台登录日志”

**Comment by Lorna0** [comment]
感觉登录日志对背景中的 “了解雷池是否被恶意尝试登录过，好做恶意IP封禁操作” 帮助不是很大，用起来略麻烦了点，还得手动翻日志然后加黑。
“访问源 IP 限制” 要直接方便直接一些。

**Comment by onedaycodes** [comment]
我感觉是两种不同维度的需求，对于经常变动源IP用户，只需要关系恶意IP拉黑即可，对于固定IP的用户，只需要做登录源IP限制即可。不同业务场景，需求自然不同。

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
