### ISSUE TITLE
[建议] 增加系统配置备份导出功能

### ISSUE THREAD

**Issue by onedaycodes** [chaitin/SafeLine#219]
### 背景与遇到的问题

配置了站点，百名单，黑名单，人机验证机制。因为某些原因，配置信息遭遇删除，重新部署了雷池，想通过导入备份配置方式一键恢复上述配置。

### 建议的解决方案

建议增加配置一键导入备份，一键导入备份文件恢复配置。

**Comment by Lorna0** [comment]
直接备份文件就行了，参考：https://github.com/chaitin/safeline/issues/90

**Comment by clqs803** [comment]
直接备份目录到新服务器上，然后进去新服务器的safeline目录执行升级的命令 完美克隆~

**Comment by onedaycodes** [comment]
直接备份安装目录的确是一个方法，但是过于重操作，如果是手动，还要登录服务器，如果是定时脚本，还得找一个机器来存备份。页面上的配置信息通过页面方式直接导出备份，导入还原，很轻便。对于嫌麻烦的用户来说也方便。

**Comment by Lorna0** [comment]
> 直接备份安装目录的确是一个方法，但是过于重操作，如果是手动，还要登录服务器，如果是定时脚本，还得找一个机器来存备份。页面上的配置信息通过页面方式直接导出备份，导入还原，很轻便。对于嫌麻烦的用户来说也方便。

如果想界面上导出导入 + 定期备份的话，也得找一个机器来存。区别似乎只在于需不需要登录服务器而已。

**Comment by Lorna0** [comment]
合并到 #90 吧，意见集中一些：
* https://github.com/chaitin/SafeLine/issues/90

**Comment by jssolo** [comment]
如果是对于参加beta版本，或者是自己测试一些功能之类的，如果页面上有导入导出配置的功能，可以再更改之间把原始配置导出，出现问题之后，可以很方便的重装
