### ISSUE TITLE
[建议] 增加单站点高频率、高次数访问拦截。

### ISSUE THREAD

**Issue by blogzonr** [chaitin/safeline#220]
### 背景与遇到的问题

遇到的问题:不能使用单站点次数、频率限制的配置。

### 建议的解决方案

建议增加单站点能够设置高频率和高次数访问的限制（防cc）功能即可。谢谢！

**Comment by Lorna0** [comment]
似乎和这个 issue 相同：
* https://github.com/chaitin/safeline/issues/209

一起集中到那边讨论吧。
