### ISSUE TITLE
[Bug] 网站开启维护模式后，微信内访问会缓存维护页面 即使关闭依然显示维护页面

### ISSUE THREAD

**Issue by nanxuanmoke** [chaitin/SafeLine#221]
### 问题描述

雷池开启维护模式后，微信访问显示维护页面，再切换回防护模式，微信内访问依然显示维护页面。
浏览器不会缓存，唯独微信内访问会缓存页面。

我在其他雷池服务器上测试均复现这种情况。
这种情况是大坑，不然开启维护后，用户访问，即使你关闭依然显示维护。
我是昨晚发现的这个问题，直到现在打开依然提示维护页面，只有清除微信缓存后才可解决。

**处理方式：维护页面的HTTP响应头应该增加一条 “cache-control max-age=0”，这样就可以避免该情况。**

**Comment by luweijun1992** [comment]
场景抓紧修复下，不然确实影响。

@nanxuanmoke 微信内置浏览器右上角三个点，有个刷新按钮应该能解决。

**Comment by 1731563584** [comment]
这是微信内置浏览器的问题，内置浏览器默认就是缓存页面的

**Comment by nanxuanmoke** [comment]
> 这是微信内置浏览器的问题，内置浏览器默认就是缓存页面的

但雷池需要去解决啊，不然这就是一个坑。
维护页面http响应条加一个 cache-control max-age=0 就好了。

**Comment by Lorna0** [comment]
3.1 版本已修复
