### ISSUE TITLE
[建议] 高频访问这里增加访问的域名

### ISSUE THREAD

**Issue by bboysoulcn** [chaitin/SafeLine#223]
### 背景与遇到的问题

知道对应的 ip 有高频访问，但是不知道访问了什么的服务

### 建议的解决方案

添加高频访问的域名字段

**Comment by Lorna0** [comment]
高频访问记数据的话，性能会比较差。
看看大家想法。

**Comment by zclaiqcc** [comment]
> ### 背景与遇到的问题
> 知道对应的 ip 有高频访问，但是不知道访问了什么的服务
> 
> ### 建议的解决方案
> 添加高频访问的域名字段

好奇问一下，如果知道了是哪个服务，下一步动作是什么？感觉有点 [X-Y 问题](https://coolshell.cn/articles/10804.html) 了。只说了 Y 解决方案，但是没有说 X 问题本身是什么。

**Comment by bboysoulcn** [comment]
> > ### 背景与遇到的问题
> > 知道对应的 ip 有高频访问，但是不知道访问了什么的服务
> > ### 建议的解决方案
> > 添加高频访问的域名字段
> 
> 好奇问一下，如果知道了是哪个服务，下一步动作是什么？感觉有点 [X-Y 问题](https://coolshell.cn/articles/10804.html) 了。只说了 Y 解决方案，但是没有说 X 问题本身是什么。


比如我知道这个 ip 在频繁访问我的某一个服务，我就可以把这个 ip 放在我这个服务的黑名单中，而不是所有服务的黑名单中

**Comment by zclaiqcc** [comment]
> > > ### 背景与遇到的问题
> > > 知道对应的 ip 有高频访问，但是不知道访问了什么的服务
> > > ### 建议的解决方案
> > > 添加高频访问的域名字段
> > 
> > 
> > 好奇问一下，如果知道了是哪个服务，下一步动作是什么？感觉有点 [X-Y 问题](https://coolshell.cn/articles/10804.html) 了。只说了 Y 解决方案，但是没有说 X 问题本身是什么。
> 
> 比如我知道这个 ip 在频繁访问我的某一个服务，我就可以把这个 ip 放在我这个服务的黑名单中，而不是所有服务的黑名单中

还是好奇哈哈哈，更进一步问，为啥不是放在所有服务的黑名单里面呢？这个 IP 都高频扫你的其中一个服务了，把其他服务给他，是预期一些不一样的结果么？

**Comment by xbingW** [comment]
现在频率限制会显示站点信息了
