### ISSUE TITLE
[建议]  在数据库中增加访问源IP、目的IP的GEO地理位置信息，方便大屏展示

### ISSUE THREAD

**Issue by j4ckzh0u** [chaitin/safeline#225]
### 背景与遇到的问题

目前需要将攻击日志中的数据做进一步的加工，然后在大屏上做可视化。
在前端的地图上显示攻击动态信息，需要源IP、目的IP的GEO信息，现在我们是对数据做了二次处理，加上了GEO信息。

### 建议的解决方案

建议，直接在数据库中增加GEO信息字段。

**Comment by zclaiqcc** [comment]
既然是要自己 DIY 做大屏，找个 IP 库查一下不就行了

**Comment by zclaiqcc** [comment]
现在已经有这个信息了吧？攻击日志中有 country province 呀？

**Comment by j4ckzh0u** [comment]
@zclaiqcc  我看到数据库中有城市的信息， 但是里面没有地理位置的经纬度信息
![image](https://github.com/chaitin/SafeLine/assets/38179297/d9c8c1ae-bbe6-49da-9a29-9b662bc126b3)

这是我使用 GEOIP数据库做了一层转换
![image](https://github.com/chaitin/SafeLine/assets/38179297/c0212f88-e1b6-4231-8edd-f45d37204fb0)
