### ISSUE TITLE
[建议] 频率限制后仅触发人机验证

### ISSUE THREAD

**Issue by Hejacky** [chaitin/SafeLine#226]
### 背景与遇到的问题

1.访问频率直接封堵会有部分误挡，影响体验
2.拦截返回页不能自定义
3.所有站点统一策略生效，不够灵活

### 建议的解决方案

1.CC 联动人机交互验证，首次单位时间内触发CC的,弹出人机交互验证，人机交互验证通过后，再次触发的，按设定阈值进行ip拦截和释放
2.拦截展示页面自定义
3. 每个站点的策略能单独配置，增强策略配置的灵活性

**Comment by Lorna0** [comment]
提示： **创建前请搜索一下是否有重复问题。一个 issue 尽量只描述一个问题。** 简洁、准确的描述有助于集中大家的意见，推进问题尽快解决

1. 
3. duplicate，请在这里讨论：
    * https://github.com/chaitin/safeline/issues/83

**Comment by Lorna0** [comment]
提示： **创建前请搜索一下是否有重复问题。一个 issue 尽量只描述一个问题。** 简洁、准确的描述有助于集中大家的意见，推进问题尽快解决

这个 issue 只讨论 1 。

1. LGTM，不过估计不会做这么复杂。可能是触发限频后人机验证，通过人机验证则重新统计频率
2. 拦截页是社区版的重要传播途径，暂不考虑自定义。如果因此遇到使用上的问题可以单独提个 issue 具体描述一下
3. duplicate：
    * https://github.com/chaitin/safeline/issues/83

**Comment by Hejacky** [comment]
建议，可以增加动作选项，触发后的动作，观察、拦截、人机验证，每个站点可以单独进行设置

**Comment by nmgliangwei** [comment]
强烈建议人机验证结合高频攻击和高频访问

**Comment by 5566dst** [comment]
+1

**Comment by jssolo** [comment]
高频访问添加人机验证 这个功能还是可以的，毕竟正常用户如果被误伤了可以尽可能减少对业务的影响

**Comment by Lorna0** [comment]
3.3 版本已支持：
![image](https://github.com/chaitin/SafeLine/assets/56920727/fdaa47e4-30de-4aa0-9aef-42de7a6c88f2)
