### ISSUE TITLE
[建议] 增加负载转发

### ISSUE THREAD

**Issue by Hejacky** [chaitin/safeline#228]
### 背景与遇到的问题

当前一个站点，后端只能配置1个节点

### 建议的解决方案

能否将Nginx的负载转发添加进去，将WAF+负载均衡，添加站点--上游服务器可以设置多个进行轮询

**Comment by zclaiqcc** [comment]
issue 合并一下，集中在一起讨论和点赞吧，别分票，https://github.com/chaitin/safeline/issues/46
