### ISSUE TITLE
[建议] 关闭健康检查日志

### ISSUE THREAD

**Issue by dossec** [chaitin/SafeLine#230]
### 背景与遇到的问题

开户nginx日志时，健康检查会在nginx日志里生成很多日志，这些日志没啥作用，而且还影响正常日志查看，占用存储空间。

### 建议的解决方案

建议健康检查配置里加上关闭日志记录

# generated health-check
server {
    listen 65443;
    server_name _;
    access_log off;   # 增加
    location / {
        return 200;
    }
    location /health_check/ {
        check_status json;
    }
    location /stub_status/ {
        stub_status on;
    }
    t1k_intercept off;
    tx_intercept off;
}

**Comment by myname365** [comment]
+1

**Comment by myname365** [comment]
还有/api/dashboard/qps请求产生大量日志记录

**Comment by zclaiqcc** [comment]
以上提到的两个大量日志记录的问题在 3.1.0 版本做了优化了
