### ISSUE TITLE
[建议] 建议增加每日邮件功能

### ISSUE THREAD

**Issue by jiejiao6** [chaitin/safeline#231]
### 背景与遇到的问题

安装的机器太多 ，看不过来，建议增加每日邮件功能，发送 攻击事件到 指定邮箱

### 建议的解决方案

建议增加每日邮件功能，发送 每日攻击事件到 指定邮箱

**Comment by Lorna0** [comment]
跟这个相似，集中在这里讨论吧：
* https://github.com/chaitin/safeline/issues/187
