### ISSUE TITLE
[建议] 防护网站可以添加多个上游服务器地址

### ISSUE THREAD

**Issue by sdxzwd** [chaitin/safeline#236]
### 背景与遇到的问题

我的配置大概是 nginx->waf->业务上游,所以同一个网站就要写好几个防护地址

### 建议的解决方案

可以添加多个上游服务器地址
可以做几个单选按钮选择nginx默认几种负载方式

**Comment by 1731563584** [comment]
我的想法也是这样，可以理解为增加负载均衡，轮询方式可选择ip hash或者权重

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/safeline/issues/46
