### ISSUE TITLE
雷池waf怎么设置只能127.0.0.1本地访问,不监听0.0.0.0呀？

### ISSUE THREAD

**Issue by kk066** [chaitin/safeline#238]

**Comment by zclaiqcc** [comment]
直接问「如何操作 xxx 」都按照 [X-Y 问题](https://coolshell.cn/articles/10804.html) 理解。这里想了解的是解决方案 Y 如何实现，师傅到底遇到了啥问题 X？

**Comment by Lorna0** [comment]
直接解答问题的话，一般是用 iptables、防火墙，可以自行搜索。

issue 没有更多反馈，先关闭了，有其他疑问的话可以再补充。
