### ISSUE TITLE
[建议] 在界面中無法查看訪問日誌

### ISSUE THREAD

**Issue by calvin-git-hub** [chaitin/safeline#239]
### 背景与遇到的问题

在查看或分析CC時,無得在界面中很易看到訪問日誌,無法直觀地分析

### 建议的解决方案

可否增加訪問日誌記錄,要訪問的真實IP,和URL

**Comment by jssolo** [comment]
https://github.com/chaitin/safeline/issues/235
我也提了这个需求

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/safeline/issues/145
