### ISSUE TITLE
用的宝塔面板

### ISSUE THREAD

**Issue by pinklinux** [chaitin/safeline#24]
宝塔面板安装的 nginx,在本机用,是不是要重新编译 nginx,加入upstream,才能用啊?上游服务器写 127.0.0.1 好像不行

**Comment by zclaiqcc** [comment]
需要修改 nginx conf 把流量引到 SafeLine，或者是让流量先到 SafeLine 再转到 nginx，不太清楚在宝塔这边如何操作。

使用上的问题先参考 [FAQ](https://github.com/chaitin/safeline/blob/main/FAQ.md) 初步排查一下，也可以扫码加入社群交流问题
