### ISSUE TITLE
[建议] 站点多端口交互优化建议

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/SafeLine#240]
### 背景与遇到的问题

当前如果存在多个端口的情况下需要每个端口一行。
![image](https://github.com/chaitin/safeline/assets/58923704/79505b19-1b31-45bc-aca2-4c835e706310)

### 建议的解决方案

建议分为2个，一个为HTTP，一个为HTTPS；多个用, ; 空格隔开，跟多域名方式一样。
建议如下：
![image](https://github.com/chaitin/safeline/assets/58923704/ae6139fb-d9b5-4bc3-80fc-04b13089fd52)

**Comment by Lorna0** [comment]
感觉需要添加多个 http 或多个 https 端口的情况应该不是很多。

看看大家意见。

**Comment by luweijun1992** [comment]
> 感觉需要添加多个 http 或多个 https 端口的情况应该不是很多。
> 
> 看看大家意见。

配置做成统一，毕竟多域名方式支持一行写多个域名。
那多端口不是应该看齐，且看起来更合理。

**Comment by Lorna0** [comment]
可能因为雷池企业版是这么做的， 我已经看习惯了啊哈哈哈哈。看看有没有其他人也这么想

**Comment by luweijun1992** [comment]
> > 配置做成统一，毕竟多域名方式支持一行写多个域名。
> > 那多端口不是应该看齐，且看起来更合理。
> 
> 可能因为雷池企业版是这么做的， 我已经看习惯了啊哈哈哈哈。看看有没有其他人也这么想

既然防护站点配置域名的时候也是通过一行写多个域名方式，那端口不是也可以照抄，形成一个统一规范。

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
