### ISSUE TITLE
[建议] 高频攻击封禁优化现有机制和选项

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#245]
### 背景与遇到的问题

我的业务是管理信息系统，一般只有基层工作人员访问，只会使用浏览器正常打开，平时碰到只要匹配到攻击类型中的一般都需要进行封禁，目前系统设置成经过时间30秒，拦截次数超时1次。本想着只要攻击ip有一次匹配到攻击事件的就封禁，但咱系统的逻辑是超过1次，也就是说需要30秒内触发2次才可以封禁。经常会碰到1分钟一次触发或更长时间一次才会触发的慢速攻击，无法有效拦截。

### 建议的解决方案

建议：拦截次数超过1次改为 拦截次数是1次就拦截，而不是2次才封禁拦截。  如果设置是2，那就是一定时间内2次就拦截。不要用超过。

**Comment by zhuanmentiwen** [comment]
设置超过不能小于1。。。0次设置不了。。我用的是V3.0.1版本。

**Comment by luweijun1992** [comment]
> 设置超过不能小于1。。。0次设置不了。。我用的是V3.0.1版本。

让官方优化优化。
@Lorna0

**Comment by luweijun1992** [comment]
感觉这个应该设置为“大于等于”更加合适；
看下怎么优化

**Comment by Lorna0** [comment]
3.2 版本中，限频的生效阈值由 “超过 xx 次” 改为 “达到 xx 次”，师傅可以再试一下
