### ISSUE TITLE
能否增加一个全量流量的日志记录，默认不开启，用户自己选择是否开启[建议] 

### ISSUE THREAD

**Issue by anquanscan** [chaitin/safeline#246]
### 背景与遇到的问题

有的时候，不知道攻击时候成功，还不能看清楚整体的攻击链条

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/safeline/issues/145

btw 真实使用中，网站每天几十万几百万访问，就算有未知的攻击成功，waf 没检测出来的话，手动翻也没什么可能翻得到的。
