### ISSUE TITLE
建议添加能查看当天的访问ip，和访问地址

### ISSUE THREAD

**Issue by tangngaiwen1** [chaitin/SafeLine#247]
### 背景与遇到的问题

查看当天访问ip和地址的时候无法精准查看，需要翻查日志才能知道，那个地址访问过来。

### 建议的解决方案

建议点击30 天访问情况的时候能查看到当天的访问ip 和 访问地址，方便精准查看，和有效拦截

**Comment by Lorna0** [comment]
访问 IP，不是攻击 IP 么？为啥需要看这个，具体是什么背景和什么问题呢？

**Comment by Lorna0** [comment]
@jssolo 
> 支持，这个需求蛮需要的，因为有的请求并不是攻击请求，有的时候需要看请求url是否存在问题 

这个场景完全不现实呀，网站每天成千上万个受访 url，其中 99%+ 都是完全正常的访问，难道管理员就每天过来从这几万条 url 里一个个翻着看有啥威胁吗。这样的话还不如直接翻服务器日志呢，上 waf 就没用了啊。

**Comment by jssolo** [comment]
> @jssolo
> 
> > 支持，这个需求蛮需要的，因为有的请求并不是攻击请求，有的时候需要看请求url是否存在问题
> 
> 这个场景完全不现实呀，网站每天成千上万个受访 url，其中 99%+ 都是完全正常的访问，难道管理员就每天过来从这几万条 url 里一个个翻着看有啥威胁吗。这样的话还不如直接翻服务器日志呢，上 waf 就没用了啊。

这个需求主要是适用于流量不大的场景，如果在访问日志里发现恶意请求，可以直接就做相应的处理，比较方便，如果担心访问数据量大，可以设置哪些请求忽略写入日志，或者仅保留几天内或者指定条数

**Comment by Lorna0** [comment]
> 这个需求主要是适用于流量不大的场景，如果在访问日志里发现恶意请求，可以直接就做相应的处理，比较方便，如果担心访问数据量大，可以设置哪些请求忽略写入日志，或者仅保留几天内或者指定条数

具体啥流量不大的场景呢。体感来说可能只有 1% 左右的流量是恶意的，哪怕每天只有 100 个请求，就找那 1 个请求也够麻烦的呀。

**Comment by 5566dst** [comment]
支持增加访问日志

**Comment by Lorna0** [comment]
@5566dst 

> 支持增加访问日志

* https://github.com/chaitin/SafeLine/issues/145

**Comment by Lorna0** [comment]
时间有点久，没有更多信息，先关闭。有需要可以补充一下更多信息，我们再 reopen。
