### ISSUE TITLE
[建议] 黑白名单和IP组的规则名称不唯一

### ISSUE THREAD

**Issue by hl90211** [chaitin/SafeLine#249]
### 背景与遇到的问题

WAF黑白名单和IP组的功能，名称是可以重复创建的。
我可以创建2个名称为 “test”的IP组

### 建议的解决方案

黑白名单和IP组的名称改为唯一，避免出现重复利用。

**Comment by luweijun1992** [comment]
> ### 背景与遇到的问题
> WAF黑白名单和IP组的功能，名称是可以重复创建的。 我可以创建2个名称为 “test”的IP组
> 
> ### 建议的解决方案
> 黑白名单和IP组的名称改为唯一，避免出现重复利用。

是的，并没有校验名称是否重复。

**Comment by DeronW** [comment]
@Lorna0

**Comment by zclaiqcc** [comment]
手动改成不一样的不就行了，别纠结，对自己好一点
