### ISSUE TITLE
[建议] 站点列表显示上游服务器

### ISSUE THREAD

**Issue by topsage** [chaitin/SafeLine#250]
### 背景与遇到的问题

![image](https://github.com/chaitin/safeline/assets/51810073/229d8ab3-6501-4c22-b9e2-314370fe1415)

### 建议的解决方案

1：建议在添加站点的显示列中，设置可选展示上游服务器，比较直观展示
2：建议增加一个搜索框，可以检索端口、站点、上游服务器，比如站点过多的情况下，查找比较麻烦
3：增加分组文件夹，比如我业务，包含api、app等接口分组，加一个分组会比较好归类和查找

_No response_

**Comment by Lorna0** [comment]
长时间没有更多信息，这个 issue 就不讨论上述分歧点了，仅讨论 “展示上游服务器” 这个需求吧。

**Comment by luweijun1992** [comment]
同样需要上游服务器展示出来

**Comment by dossec** [comment]
需求+1

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
