### ISSUE TITLE
[建议] 证书管理同步原来网站的证书

### ISSUE THREAD

**Issue by FPDADA** [chaitin/SafeLine#252]
### 背景与遇到的问题

更新到3.1.0后 新增的证书管理功能，没有同步原来网站的证书。
建议能够自动同步到证书管理，方便统一查看
![image](https://github.com/chaitin/SafeLine/assets/59437473/e835d010-d50b-48e3-bee2-2aa646a218f4)

### 建议的解决方案

建议能够自动同步到证书管理，方便统一查看

**Comment by Lorna0** [comment]
为啥类？证书管理主要是为了解决 “泛域名证书得重复上传好多次” 的问题，要是没有这需求的话，还不如直接在站点那边一个个传。不然还得 站点列表-证书列表 来回跳转，感觉也很麻烦呀。

**Comment by luweijun1992** [comment]
直接重新上传下，然后引用就好了。

**Comment by zclaiqcc** [comment]
之前已经上传的证书 + 自签名证书比较多，旧数据就不做迁移了。师傅升级之后自己手动上传一次就行了
