### ISSUE TITLE
[建议] 在安装脚本中添加检测容器网络和容器镜像

### ISSUE THREAD

**Issue by EmptyZeroRain** [chaitin/SafeLine#253]
### 背景与遇到的问题

我以前装过1.0版本，后面因为某些原因直接删除了容器，并没有删除镜像和网络，后续安装过程中，发现雷池安装过程中pull 的镜像，始终版本都为latest，导致我实际安装的版本还是1.0，所以建议安装程序中添加版本号，以及添加对容器网络，容器镜像的检测。

### 建议的解决方案

查看本地是否存在雷池创建的docker网络

docker network ls |grep safeline*

如果存在，请执行下面的命令删除雷池创建的docker网络

docker network rm   |  grep safeline*

查看本地是否存在雷池镜像

docker images |grep haitin/safeline*

如果存在请执行下面命令删除雷池遗留的docker镜像

docker rmi $(docker images | grep “safeline” | awk ‘{print $3}’)

**Comment by zclaiqcc** [comment]
docker compose 管理的情况下，应该是会自动删除和创建的

**Comment by EmptyZeroRain** [comment]
这个问题 ，我在安装的时候遇到了这个问问题，并没有手动删除，直接run的的 我本地的images  版本为latest
