### ISSUE TITLE
[建议] 上游服务器支持设置IPV6地址

### ISSUE THREAD

**Issue by Moon-du** [chaitin/SafeLine#254]
### 背景与遇到的问题

上游服务器地址后续会考虑支持ipv6地址吗
![WX20230825-131430](https://github.com/chaitin/SafeLine/assets/69743019/7216fcbf-761e-462b-9c51-f2f8543d05af)

**Comment by luweijun1992** [comment]
应该是支持的，毕竟v3版本新增了“监听 IPv6（[#166](https://github.com/chaitin/safeline/issues/166)）”

**Comment by zclaiqcc** [comment]
只要师傅自己的服务器开启了 IPv6 支持，这里就可以配置（底层是 NGINX）
