### ISSUE TITLE
[建议] 安装或升级中检测本地是否支持docker 中的seccomp 

### ISSUE THREAD

**Issue by EmptyZeroRain** [chaitin/SafeLine#255]
### 背景与遇到的问题

在3.1版本更新时，upgrade.sh并没有检测地是否支持docker 中的seccomp 
Error response from daemon: seccomp profiles are not supported on this daemon, you cannot specify a custom seccomp profile

### 建议的解决方案

参考文档：https://docs.docker.com/engine/security/seccomp/#pass-a-profile-for-a-container
查看内核是否支持docker中的seccomp特性。
grep CONFIG_SECCOMP= /boot/config-$(uname -r)
如果出现如下则支持
CONFIG_SECCOMP=y
提示报错则不支持。

**Comment by zclaiqcc** [comment]
这个我们会优化一下，准备去掉这个依赖

**Comment by Lorna0** [comment]
引入 seccomp 原本是为了兼容低版本 docker，但我们发现社区用户的环境复杂，也不是所有的能通过配置 seccomp 来解决，而且还会带来额外的报错。所以决定去掉这个依赖，更新 docker 依赖版本为 >= 20.10.14。如果低版本 docker 遇见不能启动的情况可尝试升级 docker 或者自行配置。

**Comment by Lorna0** [comment]
3.2.0 已去掉对 docker 的 seccomp 特性的依赖
