### ISSUE TITLE
请问，为什么我使用Let’s Encrypt的证书会出现私钥解析错误（Private Key Parsed Error）？ / 证书夹中无法上传ecc类型的证书

### ISSUE THREAD

**Issue by pogame** [chaitin/SafeLine#257]
### 反馈内容

问题如图：
![image](https://github.com/chaitin/SafeLine/assets/53455682/4b0d1685-34c8-4cfd-8d5c-4f8f956115fc)

**Comment by luweijun1992** [comment]
证书目录下是不是有个fullchain.cer ，试试用这个看看。

**Comment by pogame** [comment]
> 证书目录下是不是有个fullchain.cer ，试试用这个看看。

![image](https://github.com/chaitin/SafeLine/assets/53455682/aa18d37e-a145-4630-96c2-1368b447e9d2)
用fullchain.cer，一样的错误

**Comment by junleus** [comment]
digicert 的证书一样问题
<img width="377" alt="image" src="https://github.com/chaitin/SafeLine/assets/37057723/6715ff56-4cf4-4fca-a84a-04607817b5a4">

**Comment by junleus** [comment]
要转为pcks1 格式
openssl rsa -in newkey.pem -out newkey.pem

**Comment by pogame** [comment]
> 要转为pcks1 格式 openssl rsa -in newkey.pem -out newkey.pem

非常感谢，可以用了

**Comment by dundunHa** [comment]
目前证书管理上传会校验私钥的格式，3.1.1 版本仅支持了以 ”----BEGIN RSA PRIVATE KEY-----“ 开头的私钥，下个版本会支持pksc1 pkcs8 和ec 格式

**Comment by Lorna0** [comment]
3.2 版本已支持在证书管理支持上传 PKCS1、PKCS8、ECC 私钥格式的证书。
