### ISSUE TITLE
[建议] 人机交互界面希望可以添加倒计时功能

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#258]
### 背景与遇到的问题

目前人机交互时间比较长，容易让用户觉得页面卡死，造成流量流失

### 建议的解决方案

添加一个倒计时功能，可以告知用户请求正在处理，倒计时不一定要完全准确，相当于一个提示

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
