### ISSUE TITLE
如何修改默认的9443端口

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#259]
### 反馈内容

部署到公网环境，默认端口可能会被扫描到，打算更换一个端口，但是没有找到相关教程，官网上的教程不详细，没有找到要修改的文件

**Comment by creeper2020** [comment]
compose.yaml
ports:
    - ${MGT_PORT:-9443}:1443

**Comment by jssolo** [comment]
> compose.yaml ports: - ${MGT_PORT:-9443}:1443

我修改之后，重启服务器，端口号并没有修改

**Comment by creeper2020** [comment]
那你就直接改环境变量
修改.env里面的端口为你想要的端口

**Comment by creeper2020** [comment]
我经过测试是没问题的[
![image](https://github.com/chaitin/SafeLine/assets/30111010/215d0adb-bc43-4793-97d4-81b67a81ff06)，并且你部署到公网的话你直接只允许本地ip访问9443然后nginx反代不就好了吗

**Comment by jssolo** [comment]
> 

![image](https://github.com/chaitin/SafeLine/assets/40593549/78eef546-6bdf-4d7b-84bc-fc5b085374f7)
是修改这个文件吗

**Comment by creeper2020** [comment]
你可以直接在当前目录下输入nano .env 或者vi .env 来修改端口，或者也可以修改compose.yaml中的MGT_PORT为你想要的端口。我的建议是用第一种方法

**Comment by jssolo** [comment]
> 你可以直接在当前目录下输入nano .env 或者vi .env 来修改端口，或者也可以修改compose.yaml中的MGT_PORT为你想要的端口。我的建议是用第一种方法

我找到了env文件，也修改了端口号，我重启服务器之后新端口号没有生效，还需要执行哪些操作吗？

**Comment by creeper2020** [comment]
docker compose down
再docker compose up -d应该就行了，没用的话有没有可能你没开端口

**Comment by jssolo** [comment]
> docker compose down 再docker compose up -d应该就行了，没用的话有没有可能你没开端口

成功修改了端口号，非常感谢

**Comment by jssolo** [comment]
索性写了个教程，后面有修改端口需求的同学可以参考下[https://www.jssolo.com/note/1498](https://www.jssolo.com/note/1498)
