### ISSUE TITLE
社区版后续考虑开放告警查询接口，或者导出功能，供二次开发吗

### ISSUE THREAD

**Issue by pusidun** [chaitin/safeline#26]
例如下列场景：
- 告警接入微信消息
- 有告警时派单负责人处理

**Comment by zclaiqcc** [comment]
未计划开放二次开发，参考 [LICENSE](https://github.com/chaitin/safeline/blob/main/LICENSE.md)

告警功能属于后续会开发的功能，比如微信、钉钉等 webhook。派单负责人这类功能，我理解基于 webhook，师傅再做一层自己的封装就好

**Comment by pusidun** [comment]
got it
close this issue
