### ISSUE TITLE
[Bug] 证书夹中上传ecc类型的证书错误

### ISSUE THREAD

**Issue by dhfsqxz** [chaitin/SafeLine#261]
### 问题描述

![c5ea09a850af8dec1ba85cc50aee82c](https://github.com/chaitin/SafeLine/assets/74221255/59795543-151f-4fc5-9603-10908b4e74ad)
证书夹中上传提示错误
但是在站点中直接上传没问题

日志
time="2023/08/25 11:51:47" level=info msg="Init database" file=main.go func=main.InitDependencies line=53 logger=main
time="2023/08/25 11:51:47" level=info msg="Init models" file=main.go func=main.InitDependencies line=57 logger=main
time="2023/08/25 11:51:47" level=info msg="Migration Up Success, Version: 2023082401, Dirty: false" file=init.go func=/patronus/safeline-2/management/webserver/initialize.Migration line=37 logger=init
time="2023/08/25 11:51:47" level=info msg="Init FVM bytecode" file=main.go func=main.InitDependencies line=65 logger=main
time="2023/08/25 11:51:47" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=139 logger=fvm
time="2023/08/25 11:51:47" level=info msg=Staring... file=main.go func=main.main line=216 logger=main
time="2023/08/25 11:51:48" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=126 logger=grpc
time="2023/08/25 11:51:48" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=126 logger=grpc
time="2023/08/25 11:51:50" level=info msg="Update fsl bytecode" file=update_policy.go func=/patronus/safeline-2/management/webserver/pkg/cron.CheckAndUpdatePolicy line=104 logger=cron
time="2023/08/25 11:52:49" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=139 logger=fvm
time="2023/08/25 11:52:49" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/08/25 11:52:49" level=info msg="Get update length 59705, 59705" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/08/25 11:52:49" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/08/25 11:54:06" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=126 logger=grpc
time="2023/08/25 11:54:06" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=139 logger=fvm
time="2023/08/25 11:54:06" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/08/25 11:54:06" level=info msg="Get update length 60552, 60552" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/08/25 11:54:06" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/08/25 11:54:06" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=126 logger=grpc
time="2023/08/25 11:55:51" level=error msg="Parsed PrivateKey Error" file=cert_service.go func=/patronus/safeline-2/management/webserver/pkg/cert.loadPrivateKeyFromPem line=74 logger=cert
time="2023/08/25 11:55:51" level=error msg="Private Key Parsed Error" file=cert.go func=/patronus/safeline-2/management/webserver/api.UpsertSSLCert line=103 logger=api
time="2023/08/25 11:56:02" level=error msg="Parsed PrivateKey Error" file=cert_service.go func=/patronus/safeline-2/management/webserver/pkg/cert.loadPrivateKeyFromPem line=74 logger=cert
time="2023/08/25 11:56:02" level=error msg="Private Key Parsed Error" file=cert.go func=/patronus/safeline-2/management/webserver/api.UpsertSSLCert line=103 logger=api
time="2023/08/25 11:56:28" level=error msg="Parsed PrivateKey Error" file=cert_service.go func=/patronus/safeline-2/management/webserver/pkg/cert.loadPrivateKeyFromPem line=74 logger=cert
time="2023/08/25 11:56:28" level=error msg="Private Key Parsed Error" file=cert.go func=/patronus/safeline-2/management/webserver/api.UpsertSSLCert line=103 logger=api
time="2023/08/25 11:56:43" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=139 logger=fvm
time="2023/08/25 11:56:43" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/08/25 11:56:43" level=info msg="Get update length 60414, 60414" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/08/25 11:56:43" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/08/25 11:56:43" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=126 logger=grpc
time="2023/08/25 11:56:55" level=error msg="Parsed PrivateKey Error" file=cert_service.go func=/patronus/safeline-2/management/webserver/pkg/cert.loadPrivateKeyFromPem line=74 logger=cert
time="2023/08/25 11:56:55" level=error msg="Private Key Parsed Error" file=cert.go func=/patronus/safeline-2/management/webserver/api.UpsertSSLCert line=103 logger=api

### 复现方法

1.acme使用zerossl生成的泛域名证书，默认为ecc类型
2.在证书夹上传

**Comment by dundunHa** [comment]
目前证书管理上传会校验私钥的格式，3.1.1 版本仅支持了以 ”----BEGIN RSA PRIVATE KEY-----“ 开头的私钥，下个版本会支持pksc1 pkcs8 和ec 格式

**Comment by Lorna0** [comment]
和 https://github.com/chaitin/SafeLine/issues/257 是同一问题，这边先关闭，后续会那边更新进度。
