### ISSUE TITLE
[建议] 希望增加黑白名单的事件计数

### ISSUE THREAD

**Issue by dddddddddd000nnnnnnnnnn** [chaitin/SafeLine#262]
### 背景与遇到的问题

某些攻击语句可能存在短期放白的，在加白这段期间又要采集数据访问频率和请求内容分析放白是否合理。当前加白名单后不记录事件则无法进一步分析。

### 建议的解决方案

希望记录已加白名单或黑名单的触发事件记录和事件计数

**Comment by Lorna0** [comment]
记录白名单似乎不太能解决这个问题。加白的一般是真实业务，因此访问量都比较大，比如每天几千、几万次。那管理员真的能从日志里分析出来啥么，这个排查工作量有点大啊，不太现实。

另外这里有几个相似的 issue，如果有你觉得是相同需求的，最好集中到之前的 issue 里讨论，避免分票：
* https://github.com/chaitin/SafeLine/issues/34
* https://github.com/chaitin/SafeLine/issues/105
* https://github.com/chaitin/SafeLine/issues/142

**Comment by luweijun1992** [comment]
建议可以增加黑白名单“计数”即可，用于验证这个黑白名单当存在多个条件的复合条件下的配置是否正确且是否匹配上进行观察。

**Comment by luweijun1992** [comment]
> 记录白名单似乎不太能解决这个问题。加白的一般是真实业务，因此访问量都比较大，比如每天几千、几万次。那管理员真的能从日志里分析出来啥么，这个排查工作量有点大啊，不太现实。
> 
> 另外这里有几个相似的 issue，如果有你觉得是相同需求的，最好集中到之前的 issue 里讨论，避免分票：
> 
> * [自定义规则（黑白名单）可选择是否记录日志 #34](https://github.com/chaitin/SafeLine/issues/34)
> * [希望支持黑名单的日志和其他攻击的日志拆分开展示 or 存储 #105](https://github.com/chaitin/SafeLine/issues/105)
> * [添加自定义规则仅观察模式 / 支持添加记录日志但不拦截的规则 #142](https://github.com/chaitin/SafeLine/issues/142)

@Lorna0 
可以在配置白名单的位置增加一个选项，是否记录日志，默认不勾选。如果用户需要可以开启。
这样可以确定配置的白名单是否正确。
![image](https://github.com/chaitin/SafeLine/assets/58923704/40700d80-8547-4fb6-a603-47b3c3e913ba)

**Comment by Lorna0** [comment]
> @luweijun1992 
> 可以在配置白名单的位置增加一个选项，是否记录日志，默认不勾选。如果用户需要可以开启。
> 这样可以确定配置的白名单是否正确。

这不就是我列出来的第一个相关 issue https://github.com/chaitin/SafeLine/issues/34 么 lol，集中讨论吧

**Comment by luweijun1992** [comment]
> > @luweijun1992
> > 可以在配置白名单的位置增加一个选项，是否记录日志，默认不勾选。如果用户需要可以开启。
> > 这样可以确定配置的白名单是否正确。
> 
> 这不就是我列出来的第一个相关 issue #34 么 lol，集中讨论吧，避免分散提交太多重复内容

哈哈，有时候忘记之前说过了。但是当前黑名单默认会记录。白名单不会。
建议白名单增加下日志记录，不然配置的白名单规则是否符合预期都不知道。

**Comment by Lorna0** [comment]
这个 issue 讨论黑白名单的事件的 “计数”。

其他需求在对应 issue 中讨论：

* https://github.com/chaitin/SafeLine/issues/34
* https://github.com/chaitin/SafeLine/issues/105
* https://github.com/chaitin/SafeLine/issues/142

**Comment by Lorna0** [comment]
重复 issue，待参考：
* https://github.com/chaitin/SafeLine/issues/361

**Comment by Lorna0** [comment]
已在 5.5.0 中支持

**Comment by luweijun1992** [comment]
> 已在 5.5.0 中支持

可以直接命中数量就好，也不用今日命中数量。
另增加清除命中数量重新计数。
