### ISSUE TITLE
[建议] 增加不同的网站添加不同的防护配置的功能

### ISSUE THREAD

**Issue by mahaijie** [chaitin/SafeLine#263]
### 背景与遇到的问题

我们目前把waf用于防护多个网站，发现防护配置对所有网站都生效，有的网站不需要防护规则，有的网站需要防护规则，无法满足多网站自定义防护配置的需求

### 建议的解决方案

建议增加不同的网站添加不同的防护配置的功能，将防护配置页面增加一个选择网站的选项，添加的规则只对配置时选择的网站有效

**Comment by Lorna0** [comment]
看起来和这个 issue 是一个意思，麻烦集中到这里讨论：
* https://github.com/chaitin/SafeLine/issues/83

btw，师傅的背景说的还不够清楚。比如 “有的网站不需要防护规则”，那把站点 “运行模式” 配制成 “观察” 就行了，现在就支持。

**Comment by Lorna0** [comment]
太长时间没有更多信息，先 close。师傅有补充可以再提交一个 issue
