### ISSUE TITLE
[建议] 提供国内的镜像仓库下载地址

### ISSUE THREAD

**Issue by EmptyZeroRain** [chaitin/SafeLine#264]
### 背景与遇到的问题

     国内的网络，由于存在GFW，导致在docker pull的时候 docker 官方的镜像仓库 经常抽风，时而快，时而慢，导致升级版本需要30分钟-1个小时不等。

### 建议的解决方案

在docker 镜像pull 的时候 添加国内的镜像仓库下载。
例如阿里云镜像仓库等。

**Comment by 373250346** [comment]
这个建议非常好 ，说到痛点上去了。

**Comment by zhuanmentiwen** [comment]
这个建议好

**Comment by zclaiqcc** [comment]
建议自己添加国内的源？

**Comment by EmptyZeroRain** [comment]
镜像仓库，建议是支持国内的 可以pull的时候 不会因为GFW的原因 导致下周出现问题

**Comment by EmptyZeroRain** [comment]
镜像仓库，建议是支持国内的 可以pull的时候 不会因为GFW的原因 导致下载出现问题，pull 时间很长

**Comment by nmgliangwei** [comment]
雷池镜像分别pull到docker.io和国内的仓库比如阿里云等，安装和更新的时候可以加个参数是否使用国内镜像源

**Comment by zclaiqcc** [comment]
> 雷池镜像分别pull到docker.io和国内的仓库比如阿里云等，安装和更新的时候可以加个参数是否使用国内镜像源

感觉很奇怪，这些都属于运维相关的范围了，不太属于标准安装需要解决的问题🤔

**Comment by Lorna0** [comment]
* https://github.com/chaitin/SafeLine/issues/313

**Comment by EmptyZeroRain** [comment]
标准安装中，也应该支持网络环境不是很好的吧

**Comment by zclaiqcc** [comment]
> 标准安装中，也应该支持网络环境不是很好的吧

标准安装中，有离线安装的呀
