### ISSUE TITLE
[建议] 请增加访问控制面板的方法

### ISSUE THREAD

**Issue by VBPush** [chaitin/SafeLine#267]
### 背景与遇到的问题

请增加访问控制面板的方式，例如可以在初次登录雷池控制面板后在设置中**切换**后续访问雷池控制面板的方式为使用账号密码登录而不是一直使用TOPO口令登录（主要是因为这样登录还需要下载格外的TOPO生成器，在一定的情况下不方便使用）

### 建议的解决方案

1.增加登录方式，如使用账号密码。
2.该功能点可设置在控制面板中进行切换。

**Comment by Lorna0** [comment]
可以参考这些 issue 底下的回复：
* https://github.com/chaitin/SafeLine/issues/28
* https://github.com/chaitin/SafeLine/issues/132

**Comment by Lorna0** [comment]
补充一句，登录过期时间有 7 天，只要 7 天内登录过一次就不需要再次输口令。
