### ISSUE TITLE
[建议] 优化日志筛选的交互 / 排除筛选

### ISSUE THREAD

**Issue by Gr-1m** [chaitin/SafeLine#269]
### 背景与遇到的问题

每次在选择日志中，攻击类型这项时要反复的点击各种类型，

而且没有全选功能，当我想要排除一些选项（比如扫描器，反序列化）要一个一个全选然后删掉排除项。

### 建议的解决方案

建议优化功能 --- 日志筛选功能细节

1、攻击类型：增加全选按钮，或者增加反选功能（选中一次正选，选中二次为反选，第三次取消）

2、优化前端：可以在红色方框位置展开攻击类型复选框，便于筛选的可视化，该框还可以收起，便于查看。

![图片](https://github.com/chaitin/SafeLine/assets/57427356/e383766c-507b-4271-8fb7-15e32ce97d46)

**Comment by Lorna0** [comment]
2 没理解，好像没解决啥问题。可以具体说说么

**Comment by Gr-1m** [comment]
2可以说是对1的一种解决方案，就是可以把攻击类型这个选项放在红色方框中，然后设置一个展开和收起的功能。

毕竟攻击类型较多，放在原来那个小框框里比较难操作

**Comment by luweijun1992** [comment]
另外建议时间的筛选提供更多选项，而不是当前开始时间-结束时间。
如下图，可以时间范围，也可以一个快捷方式，当天，7天等。最后多久。提供几个常用选项。
![image](https://github.com/chaitin/SafeLine/assets/58923704/d09c0822-a2f5-40b0-bd81-4939cb42c157)

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
