### ISSUE TITLE
websocket的代理时候出现了认证参数没有带过去

### ISSUE THREAD

**Issue by dddddddddd000nnnnnnnnnn** [chaitin/safeline#27]
用waf代理群晖的控制台端口，手机访问会卡在loading，我用同类开源Modsecurity产品测试，在nginx加上代理参数即可访问。希望长亭能够支持websocket的代理参数设置
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $remote_addr;
![1c0a61ac1fe4b3a0fa652d7ad046d71](https://user-images.githubusercontent.com/30204678/232667026-4ef205fc-3b25-414e-b04c-7348029f01fd.jpg)

**Comment by zclaiqcc** [comment]
OK this bug will be fixed in the next release

**Comment by zclaiqcc** [comment]
诶刚看了下 nginx conf，目前是已经有这两个参数的？师傅看下 `/path/to/safeline-ce/resources/nginx/proxy_params`

**Comment by dddddddddd000nnnnnnnnnn** [comment]
目前我看到包含这两个参数的状态是注释掉的，是不是解除注释后重新构建容器就能生效？
![image](https://user-images.githubusercontent.com/30204678/232977768-2aa3ad51-8efa-46f4-aee2-5c4c001c083d.png)

**Comment by zclaiqcc** [comment]
XFF 在 server 中包含了，这里就注释掉了。看下 `/path/to/safeline-ce/resources/nginx/site-enabled/IF_backend_xxx`

**Comment by dddddddddd000nnnnnnnnnn** [comment]
我按照路径打开了配置文件，确实只有XFF。那如果说XFF包含了，那就有可能出现故障的是proxy_set_header Host ，我能否将其参数由$host_fixed改为$host？会不会产生其他的影响？

![image](https://user-images.githubusercontent.com/30204678/232979579-dc6d9527-b175-4c70-9fa1-d91fe64488af.png)

**Comment by zclaiqcc** [comment]
可以先把 `proxy_params` 改成 $host 试试，影响是说哪方面的？因为需要 nginx reload，所以有可能会断流？

**Comment by dddddddddd000nnnnnnnnnn** [comment]
根据您的指引，我修改了参数后重启容器，目前显示容器是健康状态的，WAF管理后台也能正常访问，但所有的代理设置均不生效，无法访问业务页面。

![image](https://user-images.githubusercontent.com/30204678/233020209-e13f1be7-b6f6-4ede-ad04-dc84772de745.png)

![image](https://user-images.githubusercontent.com/30204678/233018452-2b3acb07-f0f2-4042-88ca-687fa7ed6a93.png)

**Comment by dddddddddd000nnnnnnnnnn** [comment]
复原设置后就WAF功能就恢复正常了

**Comment by zclaiqcc** [comment]
是说，复原到默认设置的情况下，websocket 代理也正常了哈？

**Comment by zclaiqcc** [comment]
> 根据您的指引，我修改了参数后重启容器，目前显示容器是健康状态的，WAF管理后台也能正常访问，但所有的代理设置均不生效，无法访问业务页面。
> 
> ![image](https://user-images.githubusercontent.com/30204678/233020209-e13f1be7-b6f6-4ede-ad04-dc84772de745.png)
> 
> ![image](https://user-images.githubusercontent.com/30204678/233018452-2b3acb07-f0f2-4042-88ca-687fa7ed6a93.png)

师傅这个地方 nginx conf 改得有问题。不是 include $host，而是 proxy_set_header $host;

**Comment by dddddddddd000nnnnnnnnnn** [comment]
按照您上述说的三个步骤执行完毕后，故障现象依旧，未得到解决。我现在都整不会了。
另外回答你结尾的问题：WAF IP不是192.168.11.11。目前我的架构顺序是：互联网-NGINX-防火墙-WAF-内网防火墙-真实服务器。排除端口冲突问题

![image](https://user-images.githubusercontent.com/30204678/233233893-c91b0168-234b-422e-95c3-4fbba5ea859d.png)

![image](https://user-images.githubusercontent.com/30204678/233233402-72207e10-724c-48a9-a3f7-0f8df01bc62e.png)

**Comment by dddddddddd000nnnnnnnnnn** [comment]
我再次比较了我自建的NGINX与长亭WAF中的配置，发现长亭中缺少proxy_http_version 1.1;这个参数才导致故障的。我尝试将这个参数加入长亭内置的nginx但不成功，会报错。

![image](https://user-images.githubusercontent.com/30204678/233241128-89e84a49-d335-4a9d-9df5-78a73e1fc765.png)

![image](https://user-images.githubusercontent.com/30204678/233241560-89df6f7b-7855-474e-befa-6058570ee215.png)

![image](https://user-images.githubusercontent.com/30204678/233241700-40d0c899-2eda-4b06-9284-721ea83baf00.png)

**Comment by dddddddddd000nnnnnnnnnn** [comment]
我当前的NGINX配置文件如下，按照这个配置来代理真是服务器，结果是一切正常的（当前已经关闭Modsecurity，即便是开启Modsecurity也是正常的）。但是我即便绕过自建的nginx，互联网端口直接映射到雷池WAF来代理真实服务器，结果是不正常的。



worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server_tokens  off;

    sendfile        on;

    keepalive_timeout  65;
    
    #全局开启Modsecurity
    modsecurity off;
    modsecurity_rules_file /usr/local/nginx/conf/modsecurity/modsecurity.conf;

    #GEOIP区分地理区域
    access_log  /usr/local/nginx/logs/geoip-access.log;

    geoip2 /usr/local/geoip_data/GeoLite2-Country.mmdb {
	auto_reload 5m;
        $geoip2_country_code source=$remote_addr country iso_code;
    }

    geoip2 /usr/local/geoip_data/GeoLite2-City.mmdb {
	auto_reload 5m;
        $geoip2_city_names location time_zone;
    }


    #map的功能是将前面的值赋给后面的变量
    map $geoip2_country_code $allowed_country {
        default no;
        CN  yes;
        HK  yes;
    }

    map $geoip2_city_names $allowed_city {
        default no;
        Beijing  yes;
        #HK  yes;
    }


    # HTTPS server
	#群晖DSM
        server {
            listen 5001 ssl;
            server_name          donn.com.cn;
            ssl_certificate      /usr/local/nginx/conf/cert/donn.com.cn_bundle.crt;  
            ssl_certificate_key  /usr/local/nginx/conf/cert/donn.com.cn.key; 

                #GeoIP
            if ($allowed_country = no) {
                return 403;
            }
            
            location / {
                # 这里的 ip 是后端 服务器 的 ip及端口
                proxy_pass https://192.168.11.15:5001;
                proxy_http_version 1.1;
                proxy_set_header Host $http_host;
				proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #WAF白名单
                #modsecurity_rules_file /usr/local/nginx/conf/modsecurity/whitelist_dsm.conf;
            }

        }



}

**Comment by dddddddddd000nnnnnnnnnn** [comment]
我当前的NGINX配置文件如下，按照这个配置来代理真是服务器，结果是一切正常的（当前已经关闭Modsecurity，即便是开启Modsecurity也是正常的）。但是我即便绕过自建的nginx，互联网端口直接映射到雷池WAF来代理真实服务器，结果是不正常的。


`worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server_tokens  off;

    sendfile        on;

    keepalive_timeout  65;
    
    #全局开启Modsecurity
    modsecurity off;
    modsecurity_rules_file /usr/local/nginx/conf/modsecurity/modsecurity.conf;

    #GEOIP区分地理区域
    access_log  /usr/local/nginx/logs/geoip-access.log;

    geoip2 /usr/local/geoip_data/GeoLite2-Country.mmdb {
	auto_reload 5m;
        $geoip2_country_code source=$remote_addr country iso_code;
    }

    geoip2 /usr/local/geoip_data/GeoLite2-City.mmdb {
	auto_reload 5m;
        $geoip2_city_names location time_zone;
    }


    #map的功能是将前面的值赋给后面的变量
    map $geoip2_country_code $allowed_country {
        default no;
        CN  yes;
        HK  yes;
    }

    map $geoip2_city_names $allowed_city {
        default no;
        Beijing  yes;
        #HK  yes;
    }


    # HTTPS server
	#群晖DSM
        server {
            listen 5001 ssl;
            server_name          donn.com.cn;
            ssl_certificate      /usr/local/nginx/conf/cert/donn.com.cn_bundle.crt;  
            ssl_certificate_key  /usr/local/nginx/conf/cert/donn.com.cn.key; 

                #GeoIP
            if ($allowed_country = no) {
                return 403;
            }
            
            location / {
                # 这里的 ip 是后端 服务器 的 ip及端口
                proxy_pass https://192.168.11.15:5001;
                proxy_http_version 1.1;
                proxy_set_header Host $http_host;
				proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #WAF白名单
                #modsecurity_rules_file /usr/local/nginx/conf/modsecurity/whitelist_dsm.conf;
            }

        }



}
`

**Comment by Trenck** [comment]
我在用的版本是2.5版本，这个版本的配置文件里多了一个 include custom_params/backend_x;
看起来可以在这个文件里自定义一些配置
