### ISSUE TITLE
[建议] 增加同一域名下不同目录映射不同源站的功能

### ISSUE THREAD

**Issue by zsinba** [chaitin/SafeLine#271]
### 背景与遇到的问题

同一个域名,不同目录对应不同产品线的业务, 例如:
https://www.abc.com/line1----1.1.1.1:80
https://www.abc.com/line2----2.2.2.2:80
https://www.abc.com/line3----3.3.3.3:80

一个企业下面,同一个域名,通过不同子目录映射到不同的应用. 

Nginx下面这个比较好配,但是waf就不支持. 
沟通回复说企业版本支持, 希望社区版本也能加入此功能.

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/131
