### ISSUE TITLE
[建议] 增加站点或整体配置导出功能

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#278]
### 背景与遇到的问题

运维失误，系统瘫痪，升级故障等原因导致waf重装，站点需要配置需要一个一个的增加。

### 建议的解决方案

建议增加站点配置导出功能，重装以后能够导入站点配置信息。

**Comment by luweijun1992** [comment]
一样需要，除日志外。其他防护站点，黑白名单等配置一起导出导入。

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/90
* https://github.com/chaitin/SafeLine/issues/219

**Comment by zhuanmentiwen** [comment]
补充一下，如果先给个站点配置、ip组的备份也行，其他的反正自己在点一下即可。。但这个站点来回配置太不方便。
