### ISSUE TITLE
[Bug] 统计信息不准确

### ISSUE THREAD

**Issue by nmgliangwei** [chaitin/SafeLine#279]
### 问题描述
版本：3.2.0

1.执行日志清理（docker exec safeline-mgt-api cleanlogs），首页"今日独立访客(UV)"  统计不对，应该是没有清理掉，一直在累加历史
2.攻击事件中的拦截数和原始日志选择已拦截动作，数据对不上，原始日志中拦截的数据和首页统计拦截数据是对应的
攻击事件：
<img width="742" alt="image" src="https://github.com/chaitin/SafeLine/assets/7336263/a5e41066-f7e4-450b-aace-ad6ebd1e5782">

选择“原始日志”->动作选择“已拦截”
<img width="566" alt="image" src="https://github.com/chaitin/SafeLine/assets/7336263/67716e1f-fdcc-45b2-857d-6e453f304ea7">

首页统计数据
<img width="460" alt="image" src="https://github.com/chaitin/SafeLine/assets/7336263/1784480b-fdcf-4148-85a3-250ebee20a19">

3.防护站点中今日访问和站点详情里面的今日请求量数据不一致
防护站点页
<img width="889" alt="image" src="https://github.com/chaitin/SafeLine/assets/7336263/8ad84fa2-093e-4325-b5fc-dd89c4a9b7c2">
站点详情详情
<img width="904" alt="image" src="https://github.com/chaitin/SafeLine/assets/7336263/6ff90bdc-c13a-455c-9e8b-c50232b171a6">

4.首页数据统计的“今日拦截独立 IP”和攻击事件-》原始日志-》动作选择“已拦截” 数据不一致，首页数据统计的独立 ip 比攻击事件中的多。  攻击事件中的独立 ip 是我挨个数的。。

应该是统计的口径不一致导致的吧。建议保持一致。

上周有在微信群反馈，更新到最新版后发现还是有问题。

### 期望的结果

数据统计口径保持一致

**Comment by Lorna0** [comment]
> > 3. 防护站点中今日访问和站点详情里面的今日请求量数据不一致
> 
> 这个确实是因为统计口径不一致，站点详情里的 “今日请求总量” 目前是下面资源的请求量的总和，所以会少一些。之后版本会统一成整个站点的请求量。

3.3 版本已修复
