### ISSUE TITLE
[建议] 防护站点 上游服务器

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/SafeLine#282]
### 背景与遇到的问题

1、当前防护站点上游服务器没有直观展示出来，需要进入编辑才能看到。

2、多上游服务器负载

### 建议的解决方案

1、上游服务器展示
![image](https://github.com/chaitin/SafeLine/assets/58923704/f314ee47-1bd9-43bb-90f2-60af3ea8fc22)

2、支持多个上游服务器，且负载方式的多选择性。比如主备，负载权重等。

**Comment by Lorna0** [comment]
这个有重复 issue 了：
* https://github.com/chaitin/SafeLine/issues/250
* https://github.com/chaitin/SafeLine/issues/46
