### ISSUE TITLE
[建议] 攻击类型统计

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/SafeLine#286]
### 背景与遇到的问题

数据统计首页当前没有“攻击类型”统计

### 建议的解决方案

增加攻击类型统计，见下图
![image](https://github.com/chaitin/SafeLine/assets/58923704/c94f39bb-53a8-4800-91fe-f26726107252)

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
