### ISSUE TITLE
[建议] 攻击事件-原始日志中的攻击类型如果是黑名单希望改成黑名单的名称 / 日志列表展示黑名单日志的命中规则名称

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#287]
### 背景与遇到的问题

如题，如果黑名单里既有路径黑名单和IP黑名单，这个地方是没有办法区分开的，只会显示黑名单

### 建议的解决方案

希望这个地方如果是黑名单的话，可以展示黑名单的名称而不是类型

**Comment by luweijun1992** [comment]
可以在详情页看到是哪个黑名单匹配到了。
![image](https://github.com/chaitin/SafeLine/assets/58923704/b702ad02-6af5-4a36-93b1-948ddfc31c09)

**Comment by jssolo** [comment]
这样倒也可以，不过个人觉得还是放到外面更加直观一些，看官方怎么安排吧，我这个也只是个小建议

**Comment by luweijun1992** [comment]
> 这样倒也可以，不过个人觉得还是放到外面更加直观一些，看官方怎么安排吧，我这个也只是个小建议

放在外面的话会影响UI，比如黑名单名称很长，好几十个字符。那攻击类型就要占很长位置。影响美观。

**Comment by jssolo** [comment]
> > 这样倒也可以，不过个人觉得还是放到外面更加直观一些，看官方怎么安排吧，我这个也只是个小建议
> 
> 放在外面的话会影响UI，比如黑名单名称很长，好几十个字符。那攻击类型就要占很长位置。影响美观。

确实，不过可以考虑鼠标移入时气泡展示具体黑名单内容

**Comment by Lorna0** [comment]
主要问题就是 UI，日志列表位置有限，感觉优先级不太高。

**Comment by Lorna0** [comment]
btw 能顺便分享下为啥需要区分路径黑名单和 IP 黑名单么，因为有几个相关 issue，似乎大家的想法有些分歧：
* https://github.com/chaitin/SafeLine/issues/183
* https://github.com/chaitin/SafeLine/issues/105

**Comment by jssolo** [comment]
> 不过可以考虑鼠标移入时气泡展示具体黑名单内容

可以考虑鼠标移入到黑名单这三个字的时候气泡展示具体黑名单的名称，这个需求的话仅仅是为了可以更加直观的看到具体拦截的是哪个黑名单，和#183和#105并不冲突

**Comment by nanxuanmoke** [comment]
> 放在外面的话会影响UI，比如黑名单名称很长，好几十个字符。那攻击类型就要占很长位置。影响美观。

赞同👍

**Comment by nanxuanmoke** [comment]
> > 不过可以考虑鼠标移入时气泡展示具体黑名单内容
> 
> 可以考虑鼠标移入到黑名单这三个字的时候气泡展示具体黑名单的名称，这个需求的话仅仅是为了可以更加直观的看到具体拦截的是哪个黑名单，和#183和#105并不冲突

你这个建议也不错！

**Comment by jssolo** [comment]
> btw 能顺便分享下为啥需要区分路径黑名单和 IP 黑名单么，因为有几个相关 issue，似乎大家的想法有些分歧：
> 
> * [[建议] 已经在黑名单列表里的IP，希望不要显示在攻击事件日志里。 #183](https://github.com/chaitin/SafeLine/issues/183)
> * [希望支持黑名单的日志和其他攻击的日志拆分开展示 or 存储 #105](https://github.com/chaitin/SafeLine/issues/105)

因为只显示一个黑名单，这种情况下不清楚到底是不是IP黑名单，如果需要把恶意请求路径黑名单的ip拉入黑名单，这种情况下就没法知道这个拦截到底是拦截的路径还是IP

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
