### ISSUE TITLE
[建议] 攻击事件 - 原始日志 默认过滤条件

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/SafeLine#288]
### 背景与遇到的问题

当前默认过滤条件为：攻击IP、开始时间、结束时间
需要经常用到的域名需要每次都去勾选出来，效率慢

### 建议的解决方案

建议增加：攻击类型、域名；这两个会更常用。
建议删减：开始时间、结束时间；时间反而用的更少，可能以后日志量多了查询慢会更有用，但是可以设置页面默认只展示1个月内日志，超过的话需要去输入开始时间和结束时间的过滤条件进行查询。
![image](https://github.com/chaitin/SafeLine/assets/58923704/2615e27c-e760-4938-af2b-728ba36f5d7c)

**Comment by DeronW** [comment]
这个可以有

**Comment by Lorna0** [comment]
目前展示 动作、攻击IP、开始时间、结束时间，是因为从攻击事件打开原始日志时的筛选项是这几个：
![image](https://github.com/chaitin/SafeLine/assets/56920727/49345a9c-109b-4e55-b77f-47d625ff2a7a)
![image](https://github.com/chaitin/SafeLine/assets/56920727/830b1bb1-a3b3-4caf-affd-ca4263be5b55)

这个操作比较常用，直接改的话，跳转之后的筛选条件比较多，会总是需要换行：
![image](https://github.com/chaitin/SafeLine/assets/56920727/f8092156-e9d7-437d-8d61-e636575f1a67)

**Comment by luweijun1992** [comment]
> 目前展示 动作、攻击IP、开始时间、结束时间，是因为从攻击事件打开原始日志时的筛选项是这几个： ![image](https://user-images.githubusercontent.com/56920727/265890247-49345a9c-109b-4e55-b77f-47d625ff2a7a.png) ![image](https://user-images.githubusercontent.com/56920727/265890375-830b1bb1-a3b3-4caf-affd-ca4263be5b55.png)
> 
> 这个操作比较常用，直接改的话，跳转之后的筛选条件比较多，会总是需要换行： ![image](https://user-images.githubusercontent.com/56920727/265891352-f8092156-e9d7-437d-8d61-e636575f1a67.png)

应该还是分辨率问题，我在原本基础增加：攻击类型、域名。还是只有一行。
![image](https://github.com/chaitin/SafeLine/assets/58923704/377d4869-468a-4977-98ec-8ce2026adbcc)
可以考虑前面所说：去掉开始时间、结束时间，默认展示1个月内数据，当需要更早的日志手动选择时间进行筛选。

或者用户手动定义哪些筛选项能保存下来，页面来回切换或者下次打开还是之前定义的筛选项。

**Comment by Lorna0** [comment]
3.8 版本已修改默认筛选条件：
![image](https://github.com/chaitin/SafeLine/assets/56920727/c56a21fb-f252-460a-ad09-dba8a5f7e1a6)
