### ISSUE TITLE
自动封禁高频攻击 IP / IP 访问频率限制 / 限频 / 防 CC

### ISSUE THREAD

**Issue by zznotebackup** [chaitin/safeline#29]

**Comment by zhuanmentiwen** [comment]
顶一下，自动封禁可以带上选择高危级别连续多少次攻击自动封ip。、

**Comment by 494645654** [comment]
连续多少次攻击自动封ip。这种容易造成误判。如 一个出口ip,多人同时工作。     建议针对检测出为攻击行为ip，单位时间内连续攻击多少次后 封禁15/30分钟的这种操作。

**Comment by 494645654** [comment]
此条需要先规避 工作时间内高频访问这条。

**Comment by Lorna0** [comment]
重复反馈：https://github.com/chaitin/safeline/issues/93 https://github.com/chaitin/safeline/issues/127

**Comment by Mr-lzzzzz** [comment]
顶一下

**Comment by dhfsqxz** [comment]
![image](https://github.com/chaitin/safeline/assets/74221255/0d6af1aa-96d6-4c8c-a67f-b7f31a062f86)
认为应该参考这个

**Comment by dhfsqxz** [comment]
1.根据攻击自动拉黑ip(攻防演练)
2.根据访问频率拉黑ip(防cc)，最好支持自定义url，针对某个接口单独防护
3.根据在线的 “威胁情报源” +以上两种方式，可作为可选项之一，例如威胁等级高的ip采用更严格的限制

**Comment by Lorna0** [comment]
相关反馈：

- https://github.com/chaitin/safeline/issues/147

**Comment by zclaiqcc** [comment]
频率限制功能已经加了，自动封禁高频 IP 也在做了，预计很快就发版啦

**Comment by zhuanmentiwen** [comment]
咱这个自动封禁功能不是好像我之前说的需求功能，我更新了最新版本，咱这个是根据访问频次来自动封ip。


我当时提的是想可以设置一个ip一定时间内超过几次触发了攻击事件，然后自动封他IP多少分钟的设置。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaitin/safeline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 晚上8:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chaitin/safeline] 自动封禁高频攻击 IP / IP 访问频率限制 / 限频 / 防 CC (Issue #29)





 
频率限制功能已经加了，自动封禁高频 IP 也在做了，预计很快就发版啦

**Comment by suruozhong** [comment]
频率限制功能，可以加一个针对某个URL，而不是所有URL

**Comment by Lorna0** [comment]
> 咱这个自动封禁功能不是好像我之前说的需求功能，我更新了最新版本，咱这个是根据访问频次来自动封ip。 @zhuanmentiwen 

频率限制功能已经加了，自动封禁高频攻击 IP 也在做了，预计很快就发版啦

**Comment by Lorna0** [comment]
2.6 版本增加了自动封禁高频攻击 IP：
![image](https://github.com/chaitin/safeline/assets/56920727/15d153e8-be4f-4e17-88f3-10c1ee9cbea0)
这个 issue 涉及的主要内容已经支持啦，后续大家可以再继续提交优化建议，例如：
* https://github.com/chaitin/safeline/issues/209
