### ISSUE TITLE
[建议] 建议调高nginx默认允许监听的主域名数量。

### ISSUE THREAD

**Issue by clqs803** [chaitin/SafeLine#290]
### 背景与遇到的问题

现在添加超过32个主域名就会报错了，希望可以提高默认监听的数量，或者允许后台配置，谢谢
nginx conf reload error: nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size

### 建议的解决方案

http {
    ......
    ......
    server_names_hash_bucket_size 64; # 这里可以控制添加多少域名
}

**Comment by clqs803** [comment]
> 有需要自己加就行吧，这种配置不合适默认都调高，会影响性能

现在就是自己加的，不过不知道升级后是否会被覆盖。这才是我所担心的，如果被覆盖 那么超出的域名是否会无法访问或者程序无法正常启动之类的问题

**Comment by jiespring** [comment]
> > 有需要自己加就行吧，这种配置不合适默认都调高，会影响性能
> 
> 现在就是自己加的，不过不知道升级后主配置是否会被覆盖。这才是我所担心的，如果配置被覆盖 那么超出的域名是否会无法生效或者程序无法正常启动之类的问题

遇到同样的问题，如何解决？

**Comment by clqs803** [comment]
/data/safeline/resources/nginx/nginx.conf
在http段里加上一行
http {
    server_names_hash_bucket_size 128;
}
然后重载nginx配置，更新也不会被覆盖掉
docker exec -it safeline-tengine nginx -t
docker exec -it safeline-tengine nginx -s reload

**Comment by clqs803** [comment]
> > > 有需要自己加就行吧，这种配置不合适默认都调高，会影响性能
> > 
> > 
> > 现在就是自己加的，不过不知道升级后主配置是否会被覆盖。这才是我所担心的，如果配置被覆盖 那么超出的域名是否会无法生效或者程序无法正常启动之类的问题
> 
> 遇到同样的问题，如何解决？

/data/safeline/resources/nginx/nginx.conf
在http段里加上一行
http {
server_names_hash_bucket_size 128;
}
然后重载nginx配置，更新也不会被覆盖掉
docker exec -it safeline-tengine nginx -t
docker exec -it safeline-tengine nginx -s reload
