### ISSUE TITLE
[部署] 配置seccomp无效问题

### ISSUE THREAD

**Issue by wujie6166** [chaitin/SafeLine#291]
### 反馈内容

safelint-mgt-api 出现 Operation not permitted
docker logs -f safelint-mgt-api 容器日志中看到 runtime/cgo: pthread_create failed: Operation not permitted 报错，这个错误一般会在 docker 20.10.9 及以下发生。

最推荐的方式是升级 docker 到最新版本尝试解决这个问题。
或您的系统支持配置 seccomp （执行 grep CONFIG_SECCOMP= /boot/config-$(uname -r) 输出 CONFIG_SECCOMP=y 则为支持）, 则可以在雷池工作目录下载 [seccomp](https://waf-ce.chaitin.cn/release/latest/seccomp.json) 并且编辑 compose.yaml 文件， 在 management 下加入如下配置项，然后执行 docker compose down && docker compose up -d 来尝试解决这个问题:
security_opt:  
- seccomp=./seccomp.json

已经按照这个步骤添加了对应的配置
![image](https://github.com/chaitin/SafeLine/assets/3970925/616d0b47-d1c6-4fbd-9019-bc33c66b50a4)

但是容器启动的时候还是会出现
![image](https://github.com/chaitin/SafeLine/assets/3970925/00a2a026-950c-4d2a-a189-899d08392fe4)

请问如何处理

**Comment by luweijun1992** [comment]
> ### 反馈内容
> safelint-mgt-api 出现 Operation not permitted docker logs -f safelint-mgt-api 容器日志中看到 runtime/cgo: pthread_create failed: Operation not permitted 报错，这个错误一般会在 docker 20.10.9 及以下发生。
> 
> 最推荐的方式是升级 docker 到最新版本尝试解决这个问题。 或您的系统支持配置 seccomp （执行 grep CONFIG_SECCOMP= /boot/config-$(uname -r) 输出 CONFIG_SECCOMP=y 则为支持）, 则可以在雷池工作目录下载 [seccomp](https://waf-ce.chaitin.cn/release/latest/seccomp.json) 并且编辑 compose.yaml 文件， 在 management 下加入如下配置项，然后执行 docker compose down && docker compose up -d 来尝试解决这个问题: security_opt:
> 
> * seccomp=./seccomp.json
> 
> 已经按照这个步骤添加了对应的配置 ![image](https://user-images.githubusercontent.com/3970925/265946844-616d0b47-d1c6-4fbd-9019-bc33c66b50a4.png)
> 
> 但是容器启动的时候还是会出现 ![image](https://user-images.githubusercontent.com/3970925/265946990-00a2a026-950c-4d2a-a189-899d08392fe4.png)
> 
> 请问如何处理

v3.2.0版本已经去掉seccomp

**Comment by wujie6166** [comment]
那低版本的docker （20.10.7） 如何运行起来？有没有临时的方案，暂时不想升级docker

**Comment by luweijun1992** [comment]
> 那低版本的docker （20.10.7） 如何运行起来？有没有临时的方案，暂时不想升级docker

升级下最新，去掉seccomp依赖了。
```
bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/upgrade.sh)"
```

**Comment by dundunHa** [comment]
SecurityOpt 里面搜索一下 clone ,看是clone3 还是clone。
顺便贴一下docker info 的结果

**Comment by wujie6166** [comment]
> > 那低版本的docker （20.10.7） 如何运行起来？有没有临时的方案，暂时不想升级docker
> 
> 升级下最新，去掉seccomp依赖了。
> 
> ```
> bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/upgrade.sh)"
> ```

我用的已经是最新的版本了
![image](https://github.com/chaitin/SafeLine/assets/3970925/e42f6599-039d-498e-a0b7-73fd2993df06)


> SecurityOpt


SecurityOpt 里面的是  clone  不是clone3
![image](https://github.com/chaitin/SafeLine/assets/3970925/8c5a2e50-51e4-4119-913b-e7ff9518e014)

docker info内容为：
![image](https://github.com/chaitin/SafeLine/assets/3970925/576f2e3d-a4fb-4088-ab60-d91d0a6c7c24)

@dundunHa @luweijun1992

**Comment by dundunHa** [comment]
在宿主机上输入 grep CONFIG_SECCOMP= /boot/config-$(uname -r)  看是否有输出 ： CONFIG_SECCOMP=y。

ubuntu22.04上安装同样的docker 指定seccomp后可以运行，怀疑是和系统或内核方面的限制有关系。
暂时可以先通过给予容器特权模式运行的方式来启动，在 compose 文件里 management下加入配置。
`
privileged: true
`
后面会尝试一个更好的解决方式来解决此类问题。

**Comment by wujie6166** [comment]
是有输出CONFIG_SECCOMP=y ， 后面还是升级了docker版本

**Comment by JrDw0** [comment]
从2.5.0（运行正常）升级至3.5.1时遇到了同样问题

`grep CONFIG_SECCOMP= /boot/config-$(uname -r) `
有输出`CONFIG_SECCOMP=y`
