### ISSUE TITLE
[Bug] 人机验证无法加载页面

### ISSUE THREAD

**Issue by sunxiaolong321** [chaitin/SafeLine#297]
### 问题描述

Edge浏览器出现无法ufw 人机交互验证防火墙无法加载现象。

具体表现：
1. 开启防火墙后，同一台电脑chrome正常，但是edge浏览器出现问题；
2. edge浏览器正常模式下，无法加载页面内容；
3. ege浏览器隐私模式下，无法快速通过ufw人机交互验证，需要再点一次才行。
![image](https://github.com/chaitin/SafeLine/assets/30573534/64176cc7-9f96-47d6-8985-99771c4f3e10)

![image](https://github.com/chaitin/SafeLine/assets/30573534/168f7779-2f36-46a9-b570-384d1935e313)
![image](https://github.com/chaitin/SafeLine/assets/30573534/76fab725-d7e2-44a4-90b0-efec19e44ad8)

目前已知，只有我个人电脑出现问题，其他电脑均无这种现象。
edge版本：116.0.1938.69

### 复现方法

这个bug没有复现过

**Comment by sunxiaolong321** [comment]
初步验证是浏览器Vue Telescope插件影响页面加载和验证通过。
![image](https://github.com/chaitin/SafeLine/assets/30573534/4f798af0-cbec-43f7-85a8-5396abe8f48c)

开启插件后，无法加载页面，同样的隐私模式会出现加载出页面，但是无法通过验证的问题。

**Comment by DeronW** [comment]
@sunxiaolong321  人机验证功能已经升级到了 v2 版本，可以重新测试一下

**Comment by DeronW** [comment]
新版人机验证，自测没有出现这个问题。 @sunxiaolong321  是否又遇到了这个情况，如果没有的话，我们会关闭该问题
