### ISSUE TITLE
TOTP

### ISSUE THREAD

**Issue by deluxghost** [chaitin/safeline#30]
1. 绑定 TOTP 时，除了二维码，还可以提供文字版密钥用来导入
2. 登录时的 TOTP 输入框好像不能粘贴？

**Comment by zclaiqcc** [comment]
1. 二维码解析工具识别一下就是可导入的？
2. 一共 6 位 code，感觉也不算复杂到需要 paste？😃

**Comment by deluxghost** [comment]
这样能对密码管理器友好

**Comment by zclaiqcc** [comment]
有道理，收到。不过体感登录场景比较低频，优先级不高，先凑合凑合 😸

**Comment by DeronW** [comment]
已添加到 2.1 版本中
