### ISSUE TITLE
[建议] 在站点通用配置中提供配置ssl_protocols

### ISSUE THREAD

**Issue by Belkuy** [chaitin/SafeLine#302]
### 背景与遇到的问题

安全扫描表示使用TLSv1.0和TLSv1.1 是不安全的。

### 建议的解决方案

建议在站点通用配置中提供配置ssl_protocols

**Comment by gougui** [comment]
赞同

**Comment by zclaiqcc** [comment]
自行修改 nginx.conf 去掉相关代码即可。企业级安全需求建议使用雷池企业版。既然选择了社区版，还是需要一些 DIY 能力的，这种配置就先不考虑做到页面上了。感谢师傅的反馈
