### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by partnerSun** [chaitin/SafeLine#305]
### 问题描述

compose.yaml存在一处语法错误：
![image](https://github.com/chaitin/SafeLine/assets/35442573/7b50d07a-6336-462d-a2aa-2aab8aa5200a)

### 复现方法
docker-compose up -d

### 期望的结果
${SAFELINE_DIR:?safeline dir required}/resources/management:/resources/management
_No response_

**Comment by zclaiqcc** [comment]
看不懂，不过盲猜 99% 是师傅自己安装步骤的问题，师傅可以先搜索一下官方文档，先 Close 了。

**Comment by zclaiqcc** [comment]
看到师傅的编辑补充了，全文只需要有一个地方写上 :? 就可以了，目的是给 compose 检查并报错。

所以是师傅在安装的时候遇到什么问题了么？

**Comment by partnerSun** [comment]
已解决 谢谢

**Comment by zclaiqcc** [comment]
嗯好的，不确定这个 compose.yaml 是哪个版本或者从哪拉取到的。看了下 git 历史记录，官方配置文件版本确实是师傅建议的写法，感谢反馈。
