### ISSUE TITLE
[建议] 防护站点的域名改成多行编辑器 / 站点输入域名时的交互优化

### ISSUE THREAD

**Issue by uuwang** [chaitin/SafeLine#306]
### 背景与遇到的问题

防护站点允许多个域名用","分割，但是单行编辑器十分不方便。

### 建议的解决方案

最好改成多行编辑器不用逗号分割，一个域名一行，更加便捷。

**Comment by Lorna0** [comment]
域名有多到这个程度么，我理解一般最多就 example.com、www.example.com 这样 2 个？

**Comment by Lorna0** [comment]
relate to 
* https://github.com/chaitin/SafeLine/issues/240

**Comment by Lorna0** [comment]
3.8 版本起把域名输入框改成了标签形式。输完一个域名，回车会就增加进去。应该会更加方便易懂了：

![image](https://github.com/chaitin/SafeLine/assets/56920727/39d0fe46-60a7-4e99-8d8c-71fd6c7aa2a9)
