### ISSUE TITLE
更改DNS后突然网页访问连接不上了

### ISSUE THREAD

**Issue by lcl-yn** [chaitin/SafeLine#308]
### 反馈内容

更换了新的dnpod，并我的服务一切正常，我重启了network，DNS我的也正常了，端口也是开放的，防火墙也是开放的，但是长亭雷池页面就是进不去,还有就是本机telnet 9443 也不通

**Comment by zclaiqcc** [comment]
https://github.com/chaitin/SafeLine/issues/310#issuecomment-1716945898
