### ISSUE TITLE
[Bug] 防护的如果是流式请求，那么返回的信息并不是流畅的返回

### ISSUE THREAD

**Issue by hanpenggit** [chaitin/SafeLine#309]
### 问题描述

比如部署的ChatGLM2-6B服务中有类似于openai_api的接口，通过咱们的防护之后，返回的信息会出现短暂的停留，比如问你好，正常的返回是1个字或者2个字或者3个字之类的流式返回

通过防护之后，访问防护的端口，会等待，直接返回十几个字符，后续的都是正常的

### 复现方法

可以用openai的流式接口测试，应该跟chatglm的现象一致

### 期望的结果

代理前和代理后效果一致，正常的流式返回即可

**Comment by zclaiqcc** [comment]
refer: https://github.com/chaitin/SafeLine/issues/189#issuecomment-1713539803 or https://github.com/chaitin/SafeLine/issues/283
