### ISSUE TITLE
更改DNS后登录页面进入不进去

### ISSUE THREAD

**Issue by lcl-yn** [chaitin/SafeLine#310]
### 反馈内容

DNS更改后我的服务一切正常，我看了防护墙和iptables 都对9433没有限制 ，但是我本机telnet 9433 超时，
我随后  在服务器执行 curl -vv https://154.19.70.105:9443 -k 显示如下 ，请问什么问题？？

* About to connect() to 154.19.70.105 port 9443 (#0)
*   Trying 154.19.70.105...
* Connected to 154.19.70.105 (154.19.70.105) port 9443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=WAF Management Server,OU=Service Infrastructure Department,O="Beijing WAF Technology Co., Ltd.",L=Beijing,ST=Beijing,C=CN
* 	start date: Sep 05 18:29:37 2023 GMT
* 	expire date: Sep 02 18:29:37 2033 GMT
* 	common name: WAF Management Server
* 	issuer: CN=WAF Management Server,OU=Service Infrastructure Department,O="Beijing WAF Technology Co., Ltd.",L=Beijing,ST=Beijing,C=CN
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 154.19.70.105:9443
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 13 Sep 2023 04:00:25 GMT
< Content-Type: text/html
< Content-Length: 1656
< Last-Modified: Thu, 07 Sep 2023 08:35:18 GMT
< Connection: keep-alive
< ETag: "64f98b46-678"
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-SSL-Client-Verify: NONE
< Accept-Ranges: bytes
< 
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.png" type="image/png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="commit" content="23.09.07_9851f7ad" />
    <title>SafeLine Waf Community Edition</title>
    <style type="text/css">
      @font-face {
        font-family: "Mono";
        src: url("/fonts/Mono.ttf");
        font-weight: normal;
        font-style: normal;
      }
      @font-face {
        font-family: "Mono-Bold";
        src: url("/fonts/JetBrainsMono-Bold.ttf");
      }
    </style>
    <script src="/echarts/echarts.5.4.1.min.js"></script>
    <script src="/echarts/china.js"></script>
    <script src="/echarts/world.js"></script>
    <script src="/highlight/highlight.min.js"></script>
    <link rel="stylesheet" href="/highlight/styles/a11y-light.min.css" />
    <script type="module" crossorigin src="/assets/index-64dede47.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/react-dd6c8665.js">
    <link rel="modulepreload" crossorigin href="/assets/mui-366bf44e.js">
    <link rel="modulepreload" crossorigin href="/assets/animated-svg-f13f7b45.js">
    
  </head>
  <body>
    <div id="root"></div>
    
    <script>
      // define resize throttle event
      (function () {
        var timer = 0;
        var event = new Event("lazy_resize");
        window.addEventListener("resize", function () {
          clearTimeout(timer);
          timer = setTimeout(function () {
            window.dispatchEvent(event);
          }, 1000);
        });
      })();
    </script>
  </body>
</html>

**Comment by zclaiqcc** [comment]
如果是本地访问不通，但是在 WAF 这台机器上直接 curl -vv -k https://127.0.0.1:9443/ 返回 200（WAF 服务正常）的话，那只能是本地到 WAF 中间的防火墙问题了，建议师傅再排查一下。不行就重启试试

**Comment by lcl-yn** [comment]
怎么重启？直接把 那结果  docker容器全都重启一遍么？还是服务器重启？

**Comment by lcl-yn** [comment]
重启防火墙好了，防护墙从没动过啥也没动 就重启下好了 卧槽 真tm离谱
