### ISSUE TITLE
[建议] 数据库同时支持mysql

### ISSUE THREAD

**Issue by lip215591601** [chaitin/SafeLine#314]
### 背景与遇到的问题

部分个人或公司已经购买云厂商的mysql作为业务数据库使用，同时支持mysql可以给用户多种数据库存储方式的选择

**Comment by ylwzbk** [comment]
我记得更改一些相关配置就行了

**Comment by lip215591601** [comment]
怎么修改？

**Comment by zclaiqcc** [comment]
暂时不考虑，这种层面的 DIY 没有啥意义哈哈哈
