### ISSUE TITLE
[Bug] Version 3.4.0 自动获取网站图标和标题的问题

### ISSUE THREAD

**Issue by jamebal** [chaitin/SafeLine#316]
### 问题描述

版本： Version 3.4.0
1. 自动获取图标失败。
2. 自动获取网站标题。标题中的`'`会变成`&#39;`

<img width="261" alt="截屏2023-09-15 14 13 01" src="https://github.com/chaitin/SafeLine/assets/49510841/e8317a48-12b4-448a-9227-1ed767c88025">

### 复现方法

1. 定义一个不含favicon的网站
2. 网站title设置为`SafeLine's site`

### 期望的结果

1. 建议可以自定义图标
2. 当备注不为空时，显示备注而不是网站title

**Comment by Lorna0** [comment]
1. 图标未正常显示，一般是 waf 获取到了图标，但图标的格式没有适配，导致无法正常显示。之后会多适配几个图片格式
2. 图标如果未成功获取到，会显示一个默认图标，保证美观。自定义图标会增加界面操作的复杂度，不太考虑支持
3. “当备注不为空时，显示备注而不是网站title” 这个在 3.4.1 中改了，可以升级一下

这个 issue 会在上述 “图标支持更多图片格式” 完成之后关闭。

**Comment by Lorna0** [comment]
3.5 版本对图标获取进行了优化，支持更多图片格式了。
