### ISSUE TITLE
[Bug]  v3.4.0 删除防护站点报错 ，无法删除

### ISSUE THREAD

**Issue by hale177** [chaitin/SafeLine#317]
### 问题描述

添加完站点之后，我点击删除，直接报错 ，且UI 站点没有被删除掉
但是后续反复请求访问此防护站点，在【今日防护情况】{请求} 这个字段就不再更新了  ，一直保持在删除前最后一次的数据 

![图片](https://github.com/chaitin/SafeLine/assets/116779418/89405fe0-5bb8-42a4-9cee-618107b73dd8)

### 复现方法

1，添加站点
2，测试站点访问一切正常，【请求】的total 统计累加显示正常
3，UI 上点击删除站点，直接报错，【请求】total 统计不再更新

### 期望的结果

点击删除，应该正常删除站点

**Comment by zclaiqcc** [comment]
升级到 3.4.1 试试

**Comment by zclaiqcc** [comment]
有问题师傅再开启吧
