### ISSUE TITLE
[Bug] https串证书？

### ISSUE THREAD

**Issue by ylwzbk** [chaitin/SafeLine#318]
### 问题描述

版本 3.4.1 
当 添加ip +https证书的时候  设置了自签名证书的情况下 访问https://ip  时查看证书发现证书并不是自己设置的自签名 而且证书夹的第一个证书。
在3.3.0 之前是没有窜https的情况 后面是不是更改了什么

**Comment by zclaiqcc** [comment]
没太理解，是否可以具体点？看了下 3.3.0 和 3.4.1 的 ChangeLog，都没有包含证书相关的改动。师傅重新绑定一下证书试试呢🤔

**Comment by ylwzbk** [comment]
> 没太理解，是否可以具体点？看了下 3.3.0 和 3.4.1 的 ChangeLog，都没有包含证书相关的改动。师傅重新绑定一下证书试试呢🤔
证书管理中有一个 自签证书域名 a.com及b.com证书
一、在3.3.0的版本  我给https://ip 添加了一个自签空白证书   访问 https://ip  没有携带a.com的证书信息 是正常的。
二、当我升级完3.4.0之后再去访问 https://ip   证书设置的还是个自签空白证书  但通过访问 https://ip  发现会出现a.com 的证书信息 ，我里面在站点设置的情况下重新设置了其他证书 依旧显示a.com的证书 
三、在这情况下我还是去另一个3.3.0版本的机器上就没有以上问题

**Comment by ylwzbk** [comment]
现在是明白不是啥情况 就是蹿了

**Comment by netyum** [comment]
基于ip的ca证书，无法在证书管理中添加， 提示找不到域名

直接在站点里加入可以

**Comment by JrDw0** [comment]
@zclaiqcc 遇到类似情况，具体场景是我从3.5升3.6以及3.6升3.7重启之后，站点的https证书就变成了雷池自带默认的证书，但进入管理后台查看防护站点页面显示的还是配置的证书，点开再次提交确认一下之后能够解决。

**Comment by Lorna0** [comment]
可能跟这个 issue 原因相同，已经修复：
* https://github.com/chaitin/SafeLine/issues/426

可以试试
