### ISSUE TITLE
[建议] nginx中添加http_set_misc模块

### ISSUE THREAD

**Issue by jamebal** [chaitin/SafeLine#319]
### 背景与遇到的问题

部分网站需要添加额外的认证,需要配合[authelia](https://github.com/authelia/authelia)使用, [authelia](https://github.com/authelia/authelia)需要用到`http_set_misc`模块

**Comment by zclaiqcc** [comment]
估计这个需求的优先级非常低，这种特殊场景只能先建议师傅自己额外加一个 NGINX 来处理。需求先 Open 吧，有这个场景的师傅点个 👍

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
