### ISSUE TITLE
[Bug] 误拦截本机发起的请求

### ISSUE THREAD

**Issue by basel-zhang** [chaitin/SafeLine#320]
### 问题描述

我在更新自己wordpress的文章的时候，被WAF拦截了。

![image](https://github.com/chaitin/SafeLine/assets/24664872/6795d84b-a719-43cf-9683-20a3662be6fb)

### 复现方法

1. 编辑已有的文章
2. 修改后，点“更新”按钮

### 期望的结果

应该能正常更新成功。

**Comment by basel-zhang** [comment]
我在文章里面有一些代码块，也被误报为命令注入而拦截了。

![image](https://github.com/chaitin/SafeLine/assets/24664872/8abed872-5684-4086-b2a8-138f8c6bad1f)

**Comment by Lorna0** [comment]
第一个被拦截是因为 UA 为 go-http-client/1.1，这是扫描器特征。

第二个被拦截是因为请求体中存在命令，属于命令注入的特征。

这些都是比较显著的攻击特征，WAF 不可能直接删掉功能，也没办法自动判断网站的业务需要，只能全部拦截。如果你能确认这些请求无风险，加一下白就行了。

**Comment by Lorna0** [comment]
担心风险的话可以加得严格一些，例如如果是自己更新博客文章，可以加源 IP、域名、URL 的白，甚至可以加一些请求头的限制。

**Comment by basel-zhang** [comment]
可否加入设置<pre>里面的代码白名单？理论上<pre>里面的代码是不会执行的。

**Comment by medasz** [comment]
> 第一个被拦截是因为 UA 为 go-http-client/1.1，这是扫描器特征。
> 
> 第二个被拦截是因为请求体中存在命令，属于命令注入的特征。
> 
> 这些都是比较显著的攻击特征，WAF 不可能直接删掉功能，也没办法自动判断网站的业务需要，只能全部拦截。如果你能确认这些请求无风险，加一下白就行了。
大佬问个问题，他编辑文章的请求UA 为什么会是 go-http-client/1.1，而且用的wordpress：-）

**Comment by zclaiqcc** [comment]
> 可否加入设置`\<pre\>`里面的代码白名单？理论上`\<pre\>`里面的代码是不会执行的。

不安全，不考虑统一会加这个逻辑。极端点说 pre 里面的代码也能被执行？不能小看攻击者的绕过手段。从检测的角度，无法区分后端业务如何处理这段代码，这种请求就是应该被拦截，因为包含可能的攻击行为。
