### ISSUE TITLE
[建议] 本机安装WAF是否可以使用localhost作为上游？

### ISSUE THREAD

**Issue by basel-zhang** [chaitin/SafeLine#322]
### 背景与遇到的问题

关于
https://github.com/chaitin/SafeLine/issues/320
的建议

### 建议的解决方案

如果可以使用`https://localhost:port`作为上游，就不会有127.0.0.1的问题了。

**Comment by Lorna0** [comment]
1. waf 可以用 `https://localhost:port` 作为上游。为什么不自己配下试试呢？
2. waf 用 `https://localhost:port` 作为上游和 #320 有啥关系？后者拦截与 127.0.0.1 无关

**Comment by Lorna0** [comment]
打脸了，新版本确实没办法配置 https://localhost:port，因为这里只支持 x.x 这样的域名，下期就改。

不过这个问题跟 #320 还是没啥关系。

**Comment by zclaiqcc** [comment]
都会拦截，无论是否 localhost

**Comment by basel-zhang** [comment]
不是说下期就改吗？怎么就关闭了呢？

**Comment by basel-zhang** [comment]
> 试了下打脸了，新版本确实没办法配置 https://localhost:port ，因为这里只支持 x.x 这样的域名，下期就改。

不是说下期就改吗？怎么就关闭了呢？

**Comment by DeronW** [comment]
3.7.2 版本支持了这个功能
