### ISSUE TITLE
[建议] 证书管理可以选择不做校验

### ISSUE THREAD

**Issue by 4kword** [chaitin/SafeLine#323]
### 背景与遇到的问题

将域名托管到cloudflare，使用cloudflare签发的ssl证书时，无法在雷池的证书管理界面里上传该证书。会显示“current certificate domain is empty”。

### 建议的解决方案

因为cloudflare签发的证书是cloudflare和源站通信所用，所以其中并无domain和dns域名信息，这导致无法在证书管理界面上传证书。是否可以添加一个设置关闭证书校验。我想要在配置多个二级域名时能快速的选择已上传的证书，而不是每次都要在添加域名时重新上传

**Comment by Lorna0** [comment]
雷池需要对证书进行校验解析，不然界面展示不出来证书信息。你的需求可能是 “支持上传空域名的证书”。

不过说起来，不能签一个 ”*“ 的证书么。

**Comment by 4kword** [comment]
因为cloudflare签发的证书就是空域名证书，但也是可用的证书

**Comment by zclaiqcc** [comment]
> 因为cloudflare签发的证书就是空域名证书，但也是可用的证书

是否可以解析一下证书，截个图看看？

**Comment by Lorna0** [comment]
在 3.6 版本中已经支持上传统配域名的证书了，可以试试
