### ISSUE TITLE
[其他问题与反馈] 404 Not Found!

### ISSUE THREAD

**Issue by Omoinemie** [chaitin/SafeLine#324]
### 问题描述

我有个应用程序有webui，用宝塔反代后对外开放http://bt.*******.com:70**，外网能正常访问，再用雷池反代，就出现了404错误，雷池是在另一个服务器上的

**Comment by Lorna0** [comment]
网站配置问题请先看官网这个文档：[https://waf-ce.chaitin.cn/docs/guide/config#配置后网站无法访问，如何排查](https://waf-ce.chaitin.cn/docs/guide/config#%E9%85%8D%E7%BD%AE%E5%90%8E%E7%BD%91%E7%AB%99%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5) ，根据文档步骤获取到对应的执行日志后再反馈。

**Comment by zclaiqcc** [comment]
有问题再开启吧
