### ISSUE TITLE
[Bug] 当发送的请求头中不带User-Agent时，日志中User-Agent变成Go-http-client/1.1

### ISSUE THREAD

**Issue by medasz** [chaitin/SafeLine#325]
### 问题描述

当发送的请求头中不带User-Agent时，日志中User-Agent变成Go-http-client/1.1
![image](https://github.com/chaitin/SafeLine/assets/26796210/1008ea75-726d-4eca-a730-c17b28e11524)

### 复现方法

1. 通过postman发送触发规则的请求，并且请求头中不要带有User-Agent字段
2. waf上查看攻击日志详情显示，User-Agent: Go-http-client/1.1

### 期望的结果

waf上查看攻击日志详情不应该显示User-Agent字段，或者该字段的值为空

**Comment by zclaiqcc** [comment]
建议排查 POSTMAN？或者看下 WAF 前面有没有别的设备又转发了一次，目前没有识别到 WAF 会在日志里添加 UserAgent

**Comment by Lorna0** [comment]
未复现。大概率是Postman自己加的，在 waf 前抓个包就能看出来了。

**Comment by gitamorning** [comment]
用burpsuite发去掉UA的包 发现在WAF的拦截告警详情里UA依旧是go-client
