### ISSUE TITLE
[Bug] 重启docker后IP组失效

### ISSUE THREAD

**Issue by ieayoio** [chaitin/SafeLine#326]
### 问题描述

版本：社区版3.4.1
ip组里的条数多了以后，重启docker ip组会加载不上。我们配置了一个大陆ip组，3000多条，配置了一个黑名单，当不属于大陆ip组时候不允许访问，每次重启docker就会失效，禁用再启用一下黑名单才可以

### 复现方法

1. 添加大陆ip组，约3000多条

![image](https://github.com/chaitin/SafeLine/assets/7099604/4ad636f1-43ed-42a4-b02d-0cdba8e86a66)
2. 添加黑名单

![image](https://github.com/chaitin/SafeLine/assets/7099604/6211feeb-78ff-41a1-8f1c-fddb9da11058)
3.  重启docker
4. 尝试在大陆范围访问防护站点，被拦截，攻击事件里也显示被该黑名单拦截
![image](https://github.com/chaitin/SafeLine/assets/7099604/359e7807-6cae-4ad8-b1aa-9c45f5320690)

5. 禁用再启用一下规则，变为可以正常访问状态
![image](https://github.com/chaitin/SafeLine/assets/7099604/a0e204d4-9c22-49d2-b0a8-736461a93c71)

### 期望的结果

重启docker后，ip组不会失效

**Comment by dundunHa** [comment]
重启docker是指执行 systemctl restart docker 吗？
在 3.4.1 上尝试复现，创建 2 个 IP 组 ：大陆内ip组随机生成的1 万个 IP 元素，和一个内网组 1 个元素。按照上述的重启 docker 方式目前没有复现出来，能否提供更多的参考信息？
如果有更多的信息或其他人遇见此类问题提供更多的信息再reopen
![image](https://github.com/chaitin/SafeLine/assets/132465056/bd890fe2-3023-4867-91d6-d9d4132cb52d)
![image](https://github.com/chaitin/SafeLine/assets/132465056/ddc78e96-3d8c-4e47-a0f8-5ef08b783a76)

**Comment by 5icorgi** [comment]
碰到类似的问题，出现在升级后。
现象描述：原先做的IP组是中国IP组，黑名单设置匹配源IP非中国IP，结果升级完中国IP组内的正常IP也无法访问，匹配到的黑名单就是源IP非中国IP，把黑名单规则禁用启用后恢复正常访问。
版本：3.5/3.5.1均碰到过这个问题
