### ISSUE TITLE
[建议] 希望可以增加清空xx天之前的日志

### ISSUE THREAD

**Issue by ieayoio** [chaitin/SafeLine#327]
### 背景与遇到的问题

我查询了文档目前可以通过`docker exec safeline-mgt-api cleanlogs`方式清理日志，但是直接完全清空的方式并不方便，希望增加“清空xx天之前的日志”方式

### 建议的解决方案

可以为命令添加参数的例如`docker exec safeline-mgt-api cleanlogs 30`，实现清理30天之前的日志

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/63
