### ISSUE TITLE
[建议] Include ipv6 geo database with mario docker image / 日志识别 ipv6 地址的地理位置

### ISSUE THREAD

**Issue by brentmjohnson** [chaitin/SafeLine#329]
### 背景与遇到的问题

Mario currently includes an ip_v4_db for geo-locating requests / denials.  It does not look like an ip_v6_db is included.

### 建议的解决方案

Please consider including an ipv6 geo database and related config in the community chaitin/safeline-mario image.

**Comment by zclaiqcc** [comment]
Is there any IPv6 geo db and why you need that?

**Comment by zclaiqcc** [comment]
As far as I know, there is no IPv6 geo location database because of the large address range of IPv6.

If you still need this function, please explain why you need this and reopen this issue.
