### ISSUE TITLE
[建议] IP黑白名单设置建议添加区域设置

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#330]
### 背景与遇到的问题

如果相关的业务只需要某一区域的可以访问的情况下，IP黑白名单如果支持区域设置的话，就很方便

### 建议的解决方案

IP黑白名单设置时增加所属区域，比如，每个省份或者每个城市之类的
![image](https://github.com/chaitin/SafeLine/assets/40593549/31c9787c-22e7-45eb-8f48-433ed38f6cb8)

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/88
