### ISSUE TITLE
[建议] 需要ipv6识别国家

### ISSUE THREAD

**Issue by CangShui** [chaitin/SafeLine#331]
### 背景与遇到的问题

目前产品似乎没有ipv6的地理数据库，可能精确到城市比较困难，但是识别到具体国家是有现成的地理库的，希望能添加这一功能

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/329

**Comment by zclaiqcc** [comment]
IPv6 目前普及率太低了，短期估计不会支持，师傅先导出日志自己比对吧

**Comment by D0n9** [comment]
> IPv6 目前普及率太低了，短期估计不会支持，师傅先导出日志自己比对吧

中国大陆使用手机移动网络，基本都是双栈了
