### ISSUE TITLE
重启6个容器，其中1个报错

### ISSUE THREAD

**Issue by helloyilin** [chaitin/SafeLine#332]
### 反馈内容

初始启动之后添加站点报错:
![image](https://github.com/chaitin/SafeLine/assets/50045847/7e9f5714-1793-414e-a1d3-8d5f522dad4a)
尝试重新启动6个容器，只有一个safeline-mgt-api启动报错
` docker start safeline-mgt-api 
Error response from daemon: driver failed programming external connectivity on endpoint safeline-mgt-api (2a826b5efb3fea97e1a5057d606d52ca7318909e9a56a045174460c7b01e53c0):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9443 -j DNAT --to-destination 172.22.222.4:1443 ! -i safeline-ce: iptables: No chain/target/match by that name.
 (exit status 1))
Error: failed to start containers: safeline-mgt-api`
有大哥遇到过这种情况么

**Comment by zclaiqcc** [comment]
不建议单独重启容器，估计是没有创建相应的 docker network。如果需要重启服务的话，在 compose.yaml 同级目录下执行 docker compose down && docker compose up -d 即可。

**Comment by helloyilin** [comment]
重启` docker compose up -d
[+] Running 1/0
 ✘ Network safeline-ce  Error                                                                                                                                                                             0.0s 
failed to create network safeline-ce: Error response from daemon: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i safeline-ce -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))`
这个network报错，怎么解决

**Comment by helloyilin** [comment]
> 重启` docker compose up -d [+] Running 1/0 ✘ Network safeline-ce Error 0.0s failed to create network safeline-ce: Error response from daemon: Failed to Setup IP tables: Unable to enable SKIP DNAT rule: (iptables failed: iptables --wait -t nat -I DOCKER -i safeline-ce -j RETURN: iptables: No chain/target/match by that name. (exit status 1))` 这个network报错，怎么解决

重启docker之后，成功且成功添加站点
