### ISSUE TITLE
[优化建议] 高频攻击限制时长延长

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#334]
### 背景与遇到的问题

当出现网络攻防演练时或者重大时期，需要永久封禁ip或者根据演练和活动时长对攻击行为封禁一个时间范围，目前时长限制最大只能1440，也就是一天自动解封，想设置更长时间无法设置。

![批注 2023-09-22 112309](https://github.com/chaitin/SafeLine/assets/71305096/5a96c3eb-91e9-42c9-bfa5-25371ca0c44c)

### 建议的解决方案

建议能够自定义时间不受限制。或者最大时长能够允许封禁一个月的时间也行。

**Comment by zclaiqcc** [comment]
限频的场景是如果被 CC 高频访问/攻击则限制一段时间，师傅提到的场景更多是通过黑白名单来解决吧？

限频这部分黑名单的限制时长越大，对机器负载的压力就越大，极端情况下会导致宕机，所以为了避免大家误用这个功能，专门设计成比较短的「限制时长」

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
