### ISSUE TITLE
[建议] 登录时输入完6位验证码自动登录

### ISSUE THREAD

**Issue by hi-yu** [chaitin/SafeLine#335]
### 背景与遇到的问题

可能就是因为晚点了那么1s就刷新了

### 建议的解决方案

输入完6位验证码后可以自动登录，验证码错误直接清空

**Comment by cfwl1111** [comment]
目前新版已经实现了，但问题又来了，登录按钮成为了摆设😂

**Comment by huhaku** [comment]
感觉不至于吧,30秒足够了啊 two-factor authentication 的算法是支持你输入前一个验证码然后通过验证的,哪怕他已经不显示在屏幕上了

**Comment by DeronW** [comment]
@hi-yu  新版本 雷池 waf 已经支持输入完验证码自动登录
