### ISSUE TITLE
[建议] 黑白名单可批量导入

### ISSUE THREAD

**Issue by hi-yu** [chaitin/SafeLine#336]
### 背景与遇到的问题

例如搜索屏蔽关键词，存量高危ip等。

### 建议的解决方案

支持excel等方式批量导入

**Comment by zclaiqcc** [comment]
比如有多少规则需要导入么？有没有一些样例能发出来看看？

**Comment by hi-yu** [comment]
> 比如有多少规则需要导入么？有没有一些样例能发出来看看？

例如这种违规词库：https://github.com/cjh0613/tencent-sensitive-words，内含上万条数据
如果想要搜索时屏蔽就需要批量导入

**Comment by Lorna0** [comment]
违规词正则拼一下不就能直接合并成一条么

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
