### ISSUE TITLE
[Bug] 雷池无法正确获取网站标题和图标

### ISSUE THREAD

**Issue by hayasugihayato** [chaitin/SafeLine#337]
### 问题描述

系统版本：Version 3.5.0
![image](https://github.com/chaitin/SafeLine/assets/79904825/65de90c3-aeec-487a-825b-883f4340eae0)
源站服务器使用宝塔面板，且打开了HTTPS防窜站功能，如果直接访问源站会出现404错误。

### 期望的结果

图标和标题不通过直接访问源站，而是通过访问域名的方式获取。

**Comment by zclaiqcc** [comment]
这个问题感觉应该问下 bt。

建议是 bt 上的服务去掉 HTTPS，雷池通过 127.0.0.1 访问 bt 服务即可。
