### ISSUE TITLE
[Bug] 雷池反代另一个雷池网站会被拦截

### ISSUE THREAD

**Issue by Omoinemie** [chaitin/SafeLine#339]
### 问题描述

我内网部署有一个雷池，公网服务器部署有一个雷池，内网搭建的web对外开放因为有端口，所以想用公网雷池去端口，但是会被内网的雷池拦截。

**Comment by zclaiqcc** [comment]
拦截的话看看拦截日志

**Comment by Omoinemie** [comment]
> 拦截的话看看拦截日志

![image](https://github.com/chaitin/SafeLine/assets/31991443/c60d77b4-2f58-483a-b9c1-2d9ed10c33ce)

**Comment by zclaiqcc** [comment]
UA 里面拦截的，排查下 WAF 中间还有什么转发服务吧。或者简单的，把后面内网的雷池上机器人检测模块关闭

**Comment by Omoinemie** [comment]
我在内网虚拟机装的宝塔搭建的网站，80端口，用另一个虚拟机安装的雷池代理，80端口，通过路由器的端口转发出去，7080端口，在外面直接访问7080网站正常，再用腾讯云服务器上的雷池代理，直接被拦截提示网站不存在

**Comment by zclaiqcc** [comment]
> 网站不存在

是因为雷池里面「域名」字段和实际请求到达 WAF 时候的 host 不匹配，简单的，把后面内网的雷池站点里面的「域名」置空就行
