### ISSUE TITLE
[建议] nginx 重定向 / 支持设置站点响应方式为重定向

### ISSUE THREAD

**Issue by a12cn** [chaitin/SafeLine#340]
我想把我的顶级域名 xx.com 跳转到二级域名 www.xx.com 我该如何设置呢？

**Comment by Lorna0** [comment]
暂不支持重定向，短期内可以把 xx.com 和 www.xx.com 都配置成一个站点的域名

**Comment by zclaiqcc** [comment]
> 我想把我的顶级域名 xx.com 跳转到二级域名 [www.xx.com](http://www.xx.com) 我该如何设置呢？

好奇，为什么需要跳转过去呢？比如配置站点，域名填 xx.com 和 www.xx.com，这样访问任何一个都能获取到网站信息？

**Comment by a12cn** [comment]
> > 我想把我的域名xx.com转移到域名[www.xx.com](http://www.xx.com)我该如何设置呢？
> 
> 好奇，为什么过去呢？比如配置站点，需要填写 xx.com 和[www.xx.com，这样可以访问任何一个获取信息的网站吗？](http://www.xx.com%EF%BC%8C%E8%BF%99%E6%A0%B7%E8%AE%BF%E9%97%AE%E4%BB%BB%E4%BD%95%E4%B8%80%E4%B8%AA%E9%83%BD%E8%83%BD%E8%8E%B7%E5%8F%96%E5%88%B0%E7%BD%91%E7%AB%99%E4%BF%A1%E6%81%AF%EF%BC%9F)

以为我备案是在www so？手撸nginx了QAQ

**Comment by xbingW** [comment]
最新版已支持添加重定向站点
