### ISSUE TITLE
[Bug] 添加和更新证书都会报错。

### ISSUE THREAD

**Issue by clqs803** [chaitin/SafeLine#341]
### 问题描述

![2023-09-23_19-04](https://github.com/chaitin/SafeLine/assets/80808022/e8b2d705-132d-4e50-9b5b-e5e0a76bb24f)
版本 3.5.0，升级之后到最新版遇到的，之前都正常

### 复现方法

1. 上传最新证书
2. 点击防护站点
3. 选择要更新的域名点编辑
4. 选择新上传的证书就会报错

### 期望的结果

希望可以正常更新证书

**Comment by zclaiqcc** [comment]
看下下面三个日志信息吧，尤其关注 error 的部分，或者直接粘贴上来也行
1. docker logs -f safeline-tengine
2. logs/management/webserver.log
3. logs/management/tcd.log

**Comment by clqs803** [comment]
> 看下下面三个日志信息吧，尤其关注 error 的部分，或者直接粘贴上来也行
> 
> 1. docker logs -f safeline-tengine
> 2. logs/management/webserver.log
> 3. logs/management/tcd.log

1.

**Comment by zclaiqcc** [comment]
@clqs803 不好意思，3 应该是 logs/nginx/tcd.log

**Comment by clqs803** [comment]
> @clqs803 不好意思，3 应该是 logs/nginx/tcd.log

没有和证书相关的报错信息。。

**Comment by yrluke** [comment]
师傅，能加一下我们的企业微信吗，我们已经发现了这个问题，希望师傅配合我们排查一下

**Comment by clqs803** [comment]
> 师傅，能加一下我们的企业微信吗，我们已经发现了这个问题，希望师傅配合我们排查一下

进群了，25群
