### ISSUE TITLE
[建议] 针对不同站点可以单独限制访问频率

### ISSUE THREAD

**Issue by myname365** [chaitin/SafeLine#342]
### 背景与遇到的问题

如题

**Comment by zhuanmentiwen** [comment]
支持。这个统一全局设置容易误伤，有些站点确实不需要控制频率，需要一个站点一个站点设置。

**Comment by jssolo** [comment]
支持一下，包括一些黑名单规则啥的，如果可以按站点分开，会更好

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/209
