### ISSUE TITLE
[建议+bug] 支持http3和自定义支持的连接版本等建议及修复HSTS问题

### ISSUE THREAD

**Issue by skyhhjmk** [chaitin/SafeLine#343]
### 背景与遇到的问题

# 希望支持http3与自定义支持的TLS连接版本
## 这是使用防火墙后不支持关闭TLS1.0：
![image](https://github.com/chaitin/SafeLine/assets/78078552/e5b9ef15-1b35-4317-aac0-83c8899b5c47)

[http3check](https://http3check.net/)
## 这是使用防火墙后不支持http3
![image](https://github.com/chaitin/SafeLine/assets/78078552/189981b3-4c14-44da-a197-6e12cf5d98e2)
# 这是使用防火墙后HSTS检测不通过
![image](https://github.com/chaitin/SafeLine/assets/78078552/3cab76e9-8786-483c-aaf9-59d4c5c40a72)
![image](https://github.com/chaitin/SafeLine/assets/78078552/a2e2c3b4-ca60-42c1-8f5d-eb7af73d52b2)
# 建议增加一个获取IP测试与HTTP头预设，以及支持从多个头中获取IP
![image](https://github.com/chaitin/SafeLine/assets/78078552/2081b1c2-2d7a-4026-b77a-e65dfb98aadc)

### 建议的解决方案

使用支持quic版本的nginx并增加udp-443端口的要求
支持自定义Nginx配置文件或使用其他web server（apache，op，litespeed等）

**Comment by skyhhjmk** [comment]
关于HSTS的补充：
分别尝试过
关闭防火墙强制HTTPS，使用服务器HSTS头，发现无法继承
开启防火墙强制HTTPS，服务器不添加HSTS头，无法通过检测
开启防火墙强制HTTPS，服务器使用add_header添加HSTS头，无法通过检测
---
DNS服务使用CloudFlare，关闭了CF流量代理，且配置了HSTS
![image](https://github.com/chaitin/SafeLine/assets/78078552/23956987-48aa-4688-9793-085beb90fdee)

**Comment by skyhhjmk** [comment]
![image](https://github.com/chaitin/SafeLine/assets/78078552/b55795ee-a2c4-4422-92fd-1b05c1b9073e)
上游服务器使用https://IP

**Comment by zclaiqcc** [comment]
1. 支持的 TLS 可以修改 resources/nginx/nginx.conf
2. 自定义 NGINX conf 可以参考：https://waf-ce.chaitin.cn/docs/faq/other#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9-nginx-conf
