### ISSUE TITLE
[建议] 站点显示具体的ID编号

### ISSUE THREAD

**Issue by topsage** [chaitin/SafeLine#345]
### 背景与遇到的问题

![image](https://github.com/chaitin/SafeLine/assets/51810073/2dd490e3-b5b2-4806-9dac-dbd00d5c55e5)

在配置站点自定义参数的时候，站点文件：backend_num  无法直接和界面站点匹配，站点一多，可能需要一个个打开再匹配是不是选中的站点

### 建议的解决方案

建议在web界面，显示具体的num id，和配置文件关联下，这样直接可以找到需要修改的自定义站点

**Comment by Lorna0** [comment]
自定义 nginx 配置暂时还不是一个标准操作。有需要的话可以直接在站点列表的 /api/website 中获取站点 id：
![image](https://github.com/chaitin/SafeLine/assets/56920727/e1a7f9e8-9c91-491e-9794-06f456910d56)
