### ISSUE TITLE
[建议] 支持重大会议及活动期间，夜间定时自动开启维护模式

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#346]
### 背景与遇到的问题

[建议] 支持重大会议及活动期间（护网、亚运等重大会议），夜间定时自动开启维护模式。

**Comment by Lorna0** [comment]
这个需求好企业，而且在企业的需求里也算比较特殊的。社区版支持的可能性很小。

**Comment by ezjbc** [comment]
> 这个需求好企业，而且在企业的需求里也算比较特殊的。社区版支持的可能性很小。

好的，龙哥。

**Comment by zhuanmentiwen** [comment]
这个功能我之前提过。在顶一下。

**Comment by sifanx** [comment]
如果能支持后台命令行关闭、开启某个站点也行，这样在Liunx里做自动任务

**Comment by upbeat-backbone-bose** [comment]
自己写个定时任务改一下参数，然后做个reload？

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
