### ISSUE TITLE
[建议] 添加站点是检测上游服务器的网络是否联通功能

### ISSUE THREAD

**Issue by feifei8688** [chaitin/SafeLine#348]
### 背景与遇到的问题

添加站点的场景下，有上游服务器的端口，有被防火墙拦截，或填写错误的的情况

### 建议的解决方案

建议增加，添加上游服务器的时候，增加检测的功能。

**Comment by feifei8688** [comment]
添加标题

**Comment by Lorna0** [comment]
站点到上游 “无法连通” 的情况有点多，例如：端口拒绝链接，端口超时，http 拒绝访问，http 连接超时，http 404 500 等状态码错误，http 响应内容错误。

另外，网站业务的一些特殊性也让雷池难以判断联通情况：
* 上游返回 302 的时候，有些情况是正常的，就是期望 302 跳转；有些情况是异常的，是配置有问题
* 上游可能要求请求带上一些特殊的 header， 网站用户实际访问的时候是正常的。但是雷池不知道这些配置，直接去测试会被拒绝，做到产品上就会导致误报

暂时没想到怎样能方便可靠地自动判断。

**Comment by xbingW** [comment]
最新版已支持
