### ISSUE TITLE
[建议] 对于高频攻击已被封禁的ip 返回444 无需返回拦截界面 降低资源消耗

### ISSUE THREAD

**Issue by CV-Devlau** [chaitin/SafeLine#349]
### 背景与遇到的问题

当前当某ip持续攻击并被封禁后，雷池依然每次请求都会返回拦截页面，但是实际上高频攻击一般使用脚本或工具进行，拦截页面并无作用，也消耗一些系统资源。

### 建议的解决方案

对用高频攻击不响应，或者通过nginx 的 444响应码

**Comment by jssolo** [comment]
支持下，后台只记录攻击次数，不返回信息，减少服务器开销

**Comment by Lorna0** [comment]
高频攻击如果误拦的话，需要给网站用户一个提示信息，直接不返回拦截页面可能不是很好的做法。

**Comment by CV-Devlau** [comment]
> 高频攻击如果误拦的话，需要给网站用户一个提示信息，直接不返回拦截页面可能不是很好的做法。

比如说 如果设置高频60 次，封禁后 显示提示信息， 再继续访问 到 70次就不返回了。再超就说不上是正常用户了

**Comment by Lorna0** [comment]
> @CV-Devlau 
> 比如说 如果设置高频60 次，封禁后 显示提示信息， 再继续访问 到 70次就不返回了。再超就说不上是正常用户了

很多网页会自动发请求获取 jss、 css，如果会自动发 80 个，就是 80 次访问。这样配置用户在第一次访问就会有 20 个资源获取不到，再次访问就是拦截且无任何提示。网站业务各不相同，管理员有地方没配对导致误拦也正常，最好还是留一些余地。

**Comment by jssolo** [comment]
> > @CV-Devlau
> > 比如说 如果设置高频60 次，封禁后 显示提示信息， 再继续访问 到 70次就不返回了。再超就说不上是正常用户了
> 
> 很多网页会自动发请求获取 jss、 css，如果会自动发 80 个，就是 80 次访问。这样配置用户在第一次访问就会有 20 个资源获取不到，再次访问就是拦截且无任何提示。网站业务各不相同，管理员有地方没配对导致误拦也正常，最好还是留一些余地。

这种情况会发生，但是一般的正常获取css或者js的请求不会被拦截，就算是被拦截，前端也并不会有任何提示，因为请求是网页自动请求的，除非F12看返回，但是一般用户并不会打开F12  如果担心会出现误拦，可以考虑加个开关，自己控制是否直接444关闭连接

**Comment by Lorna0** [comment]
> @jssolo 
> 这种情况会发生，但是一般的正常获取css或者js的请求不会被拦截，就算是被拦截，前端也并不会有任何提示，因为请求是网页自动请求的，除非F12看返回，但是一般用户并不会打开F12 如果担心会出现误拦，可以考虑加个开关，自己控制是否直接444关闭连接

都是 HTTP 请求，只要配了限频都一样计数和拦截，为啥说正常获取 css、js 的请求就不会被拦截呢。目前的版本，如果自动的 20 个请求被误拦了，往往用户看到的网页内容已经出错了，用户再刷新一下，就能看到限频拦截提示页了。要是改成不返回，刷新后就会看不到提示。

另外目前的拦截页面毕竟只是个静态页面，加了图片也只有几 k，服务器开销其实没多大。

**Comment by jssolo** [comment]
> > @jssolo
> > 这种情况会发生，但是一般的正常获取css或者js的请求不会被拦截，就算是被拦截，前端也并不会有任何提示，因为请求是网页自动请求的，除非F12看返回，但是一般用户并不会打开F12 如果担心会出现误拦，可以考虑加个开关，自己控制是否直接444关闭连接
> 
> 都是 HTTP 请求，只要配了限频都一样计数和拦截，为啥说正常获取 css、js 的请求就不会被拦截呢。目前的版本，如果自动的 20 个请求被误拦了，往往用户看到的网页内容已经出错了，用户再刷新一下，就能看到限频拦截提示页了。要是改成不返回，刷新后就会看不到提示。
> 
> 另外目前的拦截页面毕竟只是个静态页面，图片可能可以再压缩一下，但是不压缩也只有几 k，服务器开销其实没多大。

确实，是我考虑片面了 哈哈

**Comment by dundunHa** [comment]
时间较久，先关闭，有更多信息 reopen
