### ISSUE TITLE
[Bug] 3.5.1版 站点详情 - 今日请求 依旧是0

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#352]
### 问题描述

3.5.1版 防护站点里显示请求1万多，但是站点详情 - 今日请求 依旧是0
![zdxq](https://github.com/chaitin/SafeLine/assets/42561369/62dac11f-fb27-4083-a644-1495f29837e6)

### 复现方法

十几个站点都这样

### 期望的结果

修复次问题

**Comment by chettestwef** [comment]
+1，我也存在此问题，所有站点都是这样
![image](https://github.com/chaitin/SafeLine/assets/99162086/6af2f4c2-f6ce-44c7-9df3-3449301d0759)
![image](https://github.com/chaitin/SafeLine/assets/99162086/78713c18-650e-4201-8df9-022fe8c2db04)
![image](https://github.com/chaitin/SafeLine/assets/99162086/b819b5a1-540b-4963-9224-d1524a69cc5c)
![image](https://github.com/chaitin/SafeLine/assets/99162086/7f17b85c-9684-4bd3-8957-ddd83c084c90)

**Comment by Lorna0** [comment]
已在 3.6.3 中修复
