### ISSUE TITLE
[建议] 自定义维护页

### ISSUE THREAD

**Issue by chettestwef** [chaitin/SafeLine#354]
### 背景与遇到的问题

[建议] 自定义维护页功能，雷池的对外访问页面很多都无法配置

### 建议的解决方案

建议增加维护页的管理功能，可自定义维护页，显示信息等

**Comment by zclaiqcc** [comment]
比如说希望显示什么类型的信息？类似「拦截页面附加说明」么

**Comment by chettestwef** [comment]
如可以在想用户显示的维护页的文本内容，可以自行定义，维护开始时间等，或是可以修改logo等这些

**Comment by chettestwef** [comment]
> 比如说希望显示什么类型的信息？类似「拦截页面附加说明」么

**Comment by chettestwef** [comment]
> 比如说希望显示什么类型的信息？类似「拦截页面附加说明」么

如可以在想用户显示的维护页的文本内容，可以自行定义，维护开始时间等，或是可以修改logo等这些

**Comment by Lorna0** [comment]
和这个相似，集中讨论吧：
* https://github.com/chaitin/SafeLine/issues/354
