### ISSUE TITLE
[建议] 443端口支持UDP

### ISSUE THREAD

**Issue by basel-zhang** [chaitin/SafeLine#356]
### 背景与遇到的问题

HTTPS/3需要开放UDP 443端口，是否可以在SSL勾选项里再给出TCP和UDP的选项？

**Comment by ylwzbk** [comment]
现有的雷池nginx版本并不支持http3 开了没意义

**Comment by basel-zhang** [comment]
nginx只是个反向代理，UDP转发给后面支持HTTP3的web server就好了呀。

**Comment by lendy98** [comment]
> nginx只是个反向代理，UDP转发给后面支持HTTP3的web server就好了呀。

TCP/UDP转发可以用stream模块，这个不在这个nginx的Proxy模块里。
但stream模块转发在4层，就无法解析主机名了，也就用不了相关waf功能了。
这个是冲突的，只能选其一了。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
