### ISSUE TITLE
[建议] 人机验证时间太长

### ISSUE THREAD

**Issue by gougui** [chaitin/SafeLine#357]
### 背景与遇到的问题

麻烦问下，人机验证时间太长了，基本都是10s以上，有什么优化方法么？

**Comment by chettestwef** [comment]
+1，建议可以自行设置人机验证的通过时间

**Comment by gougui** [comment]
或者能像拦截页面那样自定提示也好？移动端经常没有转圈动画，用户直接以为网站挂了

**Comment by DeronW** [comment]
新版人机验证已经在开发中，预计过两个版本发布。人机验证的时间主要花费在计算过程，后面会降低计算量，加快速度

**Comment by Lorna0** [comment]
relate to ：
* https://github.com/chaitin/SafeLine/issues/258

**Comment by safe1ine** [comment]
优化了一波, 目前即使在低端手机上, 也能在5秒内完成验证
