### ISSUE TITLE
[建议] 高频访问限制 / 频率限制支持设置排除的资源类型

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#358]
### 背景与遇到的问题

我的门户网站默认页面里css，js加上图片会有共计104个链接，按照目前默认10秒，100次链接刚好每次访问站点的人都需要人脸识别一次，导致严重影响用户体验。

### 建议的解决方案

建议在高频访问限制的右侧增加几个排除选项能够供选择：
1、排除JPG
2、排除gif
3、排除css
4、排除js
5、排除png

选择哪个类型排除，就可以打对勾选择，这样可以解决门户网站类型的站点导致高频访问触发。

**Comment by Lorna0** [comment]
默认配置只是建议，不用完全遵守。这里提供自定义就是因为不同网站的情况不一样，需要根据实际情况配置。设置成 “网站用户正常访问时比较难达到” 的程度就可以了。

另外网站返回 jpg、css 这些静态资源的时候也会有一定消耗的（资源文件越大，消耗越高）。攻击者完全可以特地高频访问这些图片资源，进而对设备负载、带宽造成压力。直接放开不是个很好的办法。

**Comment by zhuanmentiwen** [comment]
当然，高频访问和高频攻击要是能分站点单独设置，那就是完美的了。

**Comment by Lorna0** [comment]
> @zhuanmentiwen 
> 当然，高频访问和高频攻击要是能分站点单独设置，那就是完美的了。

可以集中到这里讨论和跟进：
* https://github.com/chaitin/SafeLine/issues/209

**Comment by 888go** [comment]
> 默认配置只是建议，不用完全遵守。这里提供自定义就是因为不同网站的情况不一样，需要根据实际情况配置。设置成 “网站用户正常访问时比较难达到” 的程度就可以了。
> 
> 另外网站返回 jpg、css 这些静态资源的时候也会有一定消耗的（资源文件越大，消耗越高）。攻击者完全可以特地高频访问这些图片资源，进而对设备负载、带宽造成压力。直接放开不是个很好的办法。
赞成

**Comment by linzyjx** [comment]
专业版好像已经支持喽
![image](https://github.com/user-attachments/assets/622b279e-c3ff-48d0-a0f3-f3f6b9730829)
