### ISSUE TITLE
[建议] 期望支持 header 中有多个 ip 的情况

### ISSUE THREAD

**Issue by hmilyfyj** [chaitin/SafeLine#360]
我们在配置获取客户端真实 ip 时遇到了问题：

```
GET /website.zip HTTP/1.1
RemoteIp: 47.95.190.153
X-Forwarded-For: 119.27.174.182, 47.95.190.153
```

上述 headers 中：
- 只有 X-Forwarded-For 中包含访问者 ip，但是此字段包含多个 ip，雷池未支持 header 中有多个 ip 的情况。
- RemoteIp 中的 ip 是 cdn 的 ip， 非访问者 ip。

具体访问链路：客户端 =》阿里云 cdn =》阿里云 slb =》真实服务器，真实 ip 被插入到 X-Forwarded-For 中。

### 建议的解决方案

识别 X-Forwarded-For 这种包含多个 ip 的情况：包含多段 ip 时，取第一个 ip 作为真实 ip。

我们的访问模式较为常见，期待您的支持。

<img width="841" alt="image" src="https://github.com/chaitin/SafeLine/assets/10796377/8ca4e587-ffab-498f-87d4-05c8eb8e9db7">

**Comment by zclaiqcc** [comment]
看起来和 https://github.com/chaitin/SafeLine/issues/301#issuecomment-1714875984 是相同的问题，合并在一起讨论吧。优先还是推荐通过解析某个固定 IP 字段来实现：https://waf-ce.chaitin.cn/docs/faq/other#%E6%BA%90-ip-%E6%98%BE%E7%A4%BA%E4%B8%8D%E6%AD%A3%E7%A1%AE

不过阿里云 CDN 竟然不支持把客户端源 IP 写入一个固定的 Header，感觉应该去那边提个需求让他们支持一下，这个我理解是基础功能。

**Comment by devhaozi** [comment]
> 看起来和 [#301 (comment)](https://github.com/chaitin/SafeLine/issues/301#issuecomment-1714875984) 是相同的问题，合并在一起讨论吧。优先还是推荐通过解析某个固定 IP 字段来实现：https://waf-ce.chaitin.cn/docs/faq/other#%E6%BA%90-ip-%E6%98%BE%E7%A4%BA%E4%B8%8D%E6%AD%A3%E7%A1%AE
> 
> 不过阿里云 CDN 竟然不支持把客户端源 IP 写入一个固定的 Header，感觉应该去那边提个需求让他们支持一下，这个我理解是基础功能。

阿里云 cdn 是支持的，它这个应该是经过阿里云 slb 以后，被 slb 去除了。
