### ISSUE TITLE
[建议] 黑白名单增加命中数量来判断生效情况

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#361]
### 背景与遇到的问题

版本：3.5.1
防护配置 - 黑白名单 里的规则无法直观的看到是否生效，尤其是符合条件。

### 建议的解决方案

防护配置 - 黑白名单 里的规则，建议增加命中数量，这样能直观的看到该规则是否生效，以及总共触发了多少次。

**Comment by Lorna0** [comment]
有个重复的 issue，合并到一起跟进吧：
* https://github.com/chaitin/SafeLine/issues/262
