### ISSUE TITLE
[建议] 增加前台拦截页面多语种显示 / 拦截页面支持英文 / 人机页面支持英文

### ISSUE THREAD

**Issue by wish-cloud** [chaitin/SafeLine#363]
### 背景与遇到的问题

我的业务主要是外贸网站，访问人群主要是国外用户，目前的拦截页面是写死的中文显示。

### 建议的解决方案

建议增加根据浏览器识别语言，或者在后台增加相关页面的标题及文本设置。

**Comment by DeronW** [comment]
这个可以有

**Comment by jssolo** [comment]
拦截的提示语可以完全自定义，在保留雷池图标和外链的情况下，其余文字可以自定义html格式的，这样自由度会高一些

**Comment by Lorna0** [comment]
> @jssolo 
> 拦截的提示语可以完全自定义，在保留雷池图标和外链的情况下，其余文字可以自定义html格式的，这样自由度会高一些

放开成 html 格式的话挺容易 hack。

**Comment by Lorna0** [comment]
3.15 版本中，拦截页面会根据客户端语言自动显示 中文/英文了，可以试一下。
