### ISSUE TITLE
[Bug] 人机验证被绕过

### ISSUE THREAD

**Issue by gougui** [chaitin/SafeLine#364]
### 问题描述

用的无交互，被传token绕过，现在换成交互还在测试中

### 复现方法

def get_cookies(cookie_domain: str) -> Dict[str, str]:
    if cookie_domain not in _cookies:
        _cookies[cookie_domain] = {}
        try:
            for cookie in browser_cookie3.load(cookie_domain):
                _cookies[cookie_domain][cookie.name] = cookie.value
        except:
            pass
    return _cookies[cookie_domain]

### 期望的结果

修复被绕过

**Comment by zclaiqcc** [comment]
没太理解。是说先以无交互的方式通过人机验证，然后执行上面的脚本，可以绕过？进一步换成交互之后，也是“绕过”的状态？

无交互确实更容易绕过一些，但是对用户比较友好。如果是已经通过了一次人机验证，在 Token 有效期内确实是不进行验证的。所以感觉师傅说这个不算是个 bug 🤔 

不过我们正在优化人机验证的交互逻辑了，这部分后面会有一个小改版，师傅可以期待一下。

**Comment by gougui** [comment]
> 没太理解。是说先以无交互的方式通过人机验证，然后执行上面的脚本，可以绕过？进一步换成交互之后，也是“绕过”的状态？
> 
> 无交互确实更容易绕过一些，但是对用户比较友好。如果是已经通过了一次人机验证，在 Token 有效期内确实是不进行验证的。所以感觉师傅说这个不算是个 bug 🤔
> 
> 不过我们正在优化人机验证的交互逻辑了，这部分后面会有一个小改版，师傅可以期待一下。

就是之前网站使用的无交互，盗刷者能用脚本获取token绕过人机验证。现在改成交互后，好像还是有绕过的概率，还在验证中。期待新版本

**Comment by DeronW** [comment]
人机验证已经升级，原方法已经不可用
