### ISSUE TITLE
[建议] 站点详情易用度问题 / 通配站点的图标和业务资源会合并显示的问题

### ISSUE THREAD

**Issue by dhfsqxz** [chaitin/SafeLine#365]
### 背景与遇到的问题

当前站点允许配置泛域名，也允许多域名
但是站点详情中并没有区分

例如
我配置了一个站点为   *.example.com,example.com
然后我访问了
https://a.example.com/test
https://b.example.com/test
https://example.com/test
在站点详情中根本没法区分到底是哪个域名访问的，复制完整路径也只能获取到  /test

### 建议的解决方案

如有多域名或者泛域名的情况，在站点详情中以单个域名为顶级，每个域名下再单独列举包含资源

**Comment by zclaiqcc** [comment]
既然配置到了一个站点（上游服务器都是同一个），那么无论是 a/b/c 等二级域名下的 /test，实际上都是同一个 uri？

**Comment by Lorna0** [comment]
站点详情目前的思路是 “一个站点代表一个实际运行的网站”，所以只展示一个 favicon、网站标题，不同域名的同一路径也是同一内容。这样使用下来比较简洁，否则站点内再分若干网站，层级就有点多。

**Comment by dhfsqxz** [comment]
考虑到waf放在最外层，直接通过waf转发的话还需要登录配置，所以现在使用的是泛域名
waf后面还有个nginx负责转发，每个站点都是不一样的

实际上我们是一个web开发团队，内部有很多站点都是给用户演示，每个都是不同的
考虑到安全和管理问题没有把管理权限开放给所有人，但是所有人都有配置站点的需求

**Comment by Lorna0** [comment]
一时没想到很好的办法。先留着讨论讨论。

企业版那边的 “代理配置的站点” 和 “API 管理模块的站点” 确实是区分开的。但是配置起来就复杂多了，社区版需要更简洁的做法。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
