### ISSUE TITLE
[Bug] 站点详情批量删除无法一次删干净

### ISSUE THREAD

**Issue by dhfsqxz** [chaitin/SafeLine#366]
### 问题描述

在站点详情中，选择左上角全选，然后批量删除
删除多次无法删干净

### 复现方法

![image](https://github.com/chaitin/SafeLine/assets/74221255/c5f35922-6b1d-4924-96f9-4942dd844ea0)

### 期望的结果

全选批量删除都删干净

**Comment by zclaiqcc** [comment]
因为有流量持续访问吧，还是说没有任何请求的情况下，批量删除之后会自动出现一批资源和路径？

**Comment by dhfsqxz** [comment]
没有任何请求的情况下批量删除后还会自动出现一批

目前考虑到两种可能
1.这个页面分页了，全选实际上只选了一页内容，后面的没选，自然就没删干净
2.数量太大，做的异步删除，还没删完就刷新了，导致有一些没来得及删的还能读出来

**Comment by xbingW** [comment]
最新版已修复

**Comment by Lorna0** [comment]
5.1.0 版本修复
