### ISSUE TITLE
[建议] 输入验证码自动登录

### ISSUE THREAD

**Issue by faritor** [chaitin/SafeLine#367]
### 背景与遇到的问题

当登陆时，输入完验证码，还需要手动点击登陆按钮进行登陆

### 建议的解决方案

当输入完验证码以后，自动触发登陆，当验证失败后返回重新输入，短时间内的频繁错误，可以使用「高频攻击限制」

**Comment by Lorna0** [comment]
看起来和这个是一个建议，合并到一起讨论跟进吧：
* https://github.com/chaitin/SafeLine/issues/335
