### ISSUE TITLE
[Bug] 站点使用泛域名证书时，证书管理会误报不匹配

### ISSUE THREAD

**Issue by YangQiGuiKong** [chaitin/SafeLine#368]
### 问题描述

![1696851475918](https://github.com/chaitin/SafeLine/assets/101174061/d28f562c-18f3-41ef-bd3b-d6018c81cbf1)
这里站点使用的泛域名证书，但是后面会有警示提示不匹配，似乎是bug

### 复现方法

打开证书管理一直都是报错状态

### 期望的结果

二级域名使用*.example.com不应该报错不匹配

**Comment by dundunHa** [comment]
尝试升级到 3.6.4

**Comment by gougui** [comment]
我今天升级到3.6.4也遇到了，之前3.5.1没提示

**Comment by DeronW** [comment]
通配域名现在只判断了 *，没有判断子域名的 *.x.com 这种格式。下个版本会修复上。

**Comment by dundunHa** [comment]
在 3.7.1 上修复了这个问题
