### ISSUE TITLE
[建议] 希望可以添加一些接口，比如通过Post请求实现封禁IP

### ISSUE THREAD

**Issue by PoisonGZ** [chaitin/SafeLine#369]
### 背景与遇到的问题

目前我项目使用的是SpringBoot，目前想把项目和雷池Waf做个联动，实现项目检测到一些不符合规则的请求直接通过请求Waf接口实现Waf封禁

### 建议的解决方案

建议增加一些接口，比如封禁指定IP的接口

**Comment by PoisonGZ** [comment]
![图片](https://github.com/chaitin/SafeLine/assets/101829490/f5c6a090-260a-481b-8827-33142daeb79a)
能否添加一个不等于，而不是只有完全相等和正则，比如我可能想设置是除了xxx.xx.com的Host全部拉黑，感觉使用起来不是很方便，也可能是我正则写的不太习惯的缘故，谢谢

**Comment by Lorna0** [comment]
“将某 IP 加入到某 IP 组” 的 API 目前是有的，可以到 “攻击事件” 那个页面扒：
![image](https://github.com/chaitin/SafeLine/assets/56920727/2dc42550-2f68-4304-8ef5-1e0f6e894fb6)

再结合黑名单就能实现了。

PS. 扒 API 方法暂不提供技术支持，可以自行研究，参考 https://github.com/chaitin/SafeLine/issues/196#issuecomment-1667510507 

> @PoisonGZ 
> 能否添加一个不等于，而不是只有完全相等和正则，比如我可能想设置是除了xxx.xx.com的Host全部拉黑，感觉使用起来不是很方便，也可能是我正则写的不太习惯的缘故，谢谢

可以考虑，不过最好建一个新 issue 来讨论和跟进。
