### ISSUE TITLE
[建议] 站点增加访问黑白名单，类似nginx allow、deny功能

### ISSUE THREAD

**Issue by BOBYou** [chaitin/SafeLine#370]
### 背景与遇到的问题

某些站点并不是允许所有人访问，比如仅允许某个机构访问。
对机构的出口IP白名单，其他拒绝访问。

白名单如果能 解析 ddns域名就更好了。

### 建议的解决方案

增加类似nginx allow、deny功能

**Comment by zclaiqcc** [comment]
现在的黑名单已经可以满足了？黑名单配置 IP 组不属于 xxx 看上去就是做这个的
