### ISSUE TITLE
[建议] 建议增加钉钉机器人告警功能

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#371]
### 背景与遇到的问题

WAF拦截攻击后，不能第一时间获取到信息，需要登录WAF以后才能看到。

### 建议的解决方案

希望能增加 除黑名单以外的 攻击拦截声音提醒，以及钉钉机器人告警功能，也就是黑名单不做提醒，其他攻击类型都做提醒，或者可以选择哪类攻击才做提醒。
![攻击](https://github.com/chaitin/SafeLine/assets/42561369/3aacbf89-1dca-4269-9da2-b850f71da1df)

**Comment by jssolo** [comment]
我认为 高频攻击通知的话还可以，如果普通攻击都通知的话，会比较多，因为网上有好多扫描器

**Comment by zclaiqcc** [comment]
dup https://github.com/chaitin/SafeLine/issues/138
