### ISSUE TITLE
[建议] 希望控制台的SSL证书可以下载后安装

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#372]
### 背景与遇到的问题

每次通过ip访问控制台时，都会提示不安全的链接，需要再次点击继续前往才可以

### 建议的解决方案

希望和宝塔面板类似的，可以把证书下载导入到电脑里，这样就可以直接访问控制台了

**Comment by DeronW** [comment]
浏览器会记录 “允许” 行为，应该不是每次都需要信任。证书下载功能，暂时还未添加，目前推荐的处理方法是，上传一个电脑可以信任的证书，并将雷池管理后台改为这个证书

**Comment by DeronW** [comment]
@jssolo  当前问题是否已解决，如果已经解决，过段时间会关闭这个问题

**Comment by jssolo** [comment]
> 浏览器会记录 “允许” 行为，应该不是每次都需要信任。证书下载功能，暂时还未添加，目前推荐的处理方法是，上传一个电脑可以信任的证书，并将雷池管理后台改为这个证书

雷池管理的后台证书可以随便设置吗

**Comment by DeronW** [comment]
> > 浏览器会记录 “允许” 行为，应该不是每次都需要信任。证书下载功能，暂时还未添加，目前推荐的处理方法是，上传一个电脑可以信任的证书，并将雷池管理后台改为这个证书
> 
> 雷池管理的后台证书可以随便设置吗

可以

**Comment by QYG2297248353** [comment]
我有相同的问题，上游服务器使用 443 端口开启 HTTPS，但是证书是雷池申请的免费证书
1. 找不到下载位置
2. 没有续签功能
3. 与上游服务器同步是个问题
都要手动操作，我认为这是最基础的基础服务

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
