### ISSUE TITLE
[Bug] proxmox中CT安装失败

### ISSUE THREAD

**Issue by Omoinemie** [chaitin/SafeLine#376]
### 问题描述
Docker version 24.0.6, build ed223bc

[+] Running 6/6
 ✔ Container safeline-redis     Created                                                                                                                    35.8s 
 ✔ Container safeline-detector  Created                                                                                                                    37.6s 
 ✔ Container safeline-mgt-api   Created                                                                                                                    73.1s 
 ✔ Container safeline-tengine   Created                                                                                                                    60.0s 
 ✔ Container safeline-mario     Created                                                                                                                    63.2s 
 ✔ Container safeline-postgres  Created                                                                                                                    66.2s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown

### 复现方法

bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/setup.sh)"

### 期望的结果

无

**Comment by Omoinemie** [comment]
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/core/somaxconn: no such file or directory: unknown

**Comment by tarimoe** [comment]
@Omoinemie 师傅你好，请问你解决了吗
