### ISSUE TITLE
[Bug] 切换防护模式时报错，Rules compile error,please check your params

### ISSUE THREAD

**Issue by JrDw0** [chaitin/SafeLine#377]
### 问题描述

切换防护模式时存在报错

### 复现方法

切换防护模式时存在报错Rules compile error,please check your params
<img width="440" alt="image" src="https://github.com/chaitin/SafeLine/assets/37445725/198111f4-cc3c-4044-9c29-f6ef178097dc">
端点500报错如下
<img width="489" alt="image" src="https://github.com/chaitin/SafeLine/assets/37445725/022214cf-cd19-460e-b268-a2acd3c06591">

查询日志有如下日志
![image](https://github.com/chaitin/SafeLine/assets/37445725/3e309a37-f312-4fa9-bd3b-9f7fd98be3a7)
<img width="768" alt="image" src="https://github.com/chaitin/SafeLine/assets/37445725/a3762cc2-dab9-41e3-a94f-caa539629d4e">

### 期望的结果

能否提供排查方向，消除报错

**Comment by zclaiqcc** [comment]
safeline-mgt-api 无法访问到 safeline-detector 容器了，可以排查下容器网络。比如容器 DNS、iptables 等。也可以尝试重启 dockerd 试试
