### ISSUE TITLE
[建议] 攻击事件、原始事件里的IP搜索能支持模糊查询

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#378]
### 背景与遇到的问题

有时候攻击IP有很多个，而且是同一个网段的，我想快速搜索IP前3位，看看有几个IP，然后好加入防火墙里，但是目前不支持模糊查询，必须输入完整IP查询，不太方便。
![001](https://github.com/chaitin/SafeLine/assets/42561369/2b995e05-2298-4354-b384-e5ccf09b40fd)
![002](https://github.com/chaitin/SafeLine/assets/42561369/54ae4533-e193-46b7-8e2e-c52f873ca834)
![003](https://github.com/chaitin/SafeLine/assets/42561369/de73bf24-c0d8-42f8-b9fd-4bc18042b480)

### 建议的解决方案

建议IP栏支持模糊查询

**Comment by DeronW** [comment]
这个功能可以有

**Comment by xbingW** [comment]
6.10.2 已支持
