### ISSUE TITLE
[Bug] 黑名单规则失效

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#379]
### 问题描述

今天升级到3.7.2以后，黑名单规则失效，我这个规则是希望IP组之外的IP全部阻断，升级前是好的，升级后发现拦截多起来了，一看这些IP都在IP组里的。

### 复现方法

![001](https://github.com/chaitin/SafeLine/assets/42561369/b44692b8-5f04-4fd9-b6ee-5fe81569379e)
![002](https://github.com/chaitin/SafeLine/assets/42561369/93eef132-c13d-4073-b35f-68ccd98b3624)
![003](https://github.com/chaitin/SafeLine/assets/42561369/a4423267-fb82-4d1d-bb7a-fc88ffd85b3e)

### 期望的结果

希望修复该BUG

**Comment by 5icorgi** [comment]
一样的问题，之前反馈过，在3.5的时候应该就有了

**Comment by dundunHa** [comment]
会在 3.7.3 修复这个问题 今天或明天关注一下

**Comment by yrluke** [comment]
已修复，感谢反馈
