### ISSUE TITLE
[Bug] 防护站点页面修改提交失败

### ISSUE THREAD

**Issue by WvvvWv** [chaitin/SafeLine#380]
### 问题描述

防护站点页面修改提交失败：Service is abnormal, and the nginx conf cannot be updated for the time being. Please go to the shell to check the relevant logs
![{AEFDF666-6A58-48ac-8FC1-19145D8F0689}](https://github.com/chaitin/SafeLine/assets/40822202/0c5ff55f-90ca-4f22-85c8-e75c955f1078)

### 复现方法

防护站点页面修改提交失败，
修改站点信息，点击提交报错。

### 期望的结果

修复一下

**Comment by k-fire** [comment]
+1 修改系统配置也会报错  这.....
![image](https://github.com/chaitin/SafeLine/assets/40354487/c603f7d0-4bcb-4c1a-b00a-b034ce046236)

**Comment by GYLQ** [comment]
+1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8e2fb7]

goroutine 1581 [running]:
git.in.chaitin.net/patronus/safeline-2/management/tcontrollerd/service.GetTitleAndIcon({0xc00042a100?, 0x0?, 0x641f40?})
        /builds/patronus/safeline-ce/management/tcontrollerd/service/upstream.go:163 +0x9b7
git.in.chaitin.net/patronus/safeline-2/management/tcontrollerd/controller.websiteHandler.func1()
        /builds/patronus/safeline-ce/management/tcontrollerd/controller/website.go:255 +0x49
created by git.in.chaitin.net/patronus/safeline-2/management/tcontrollerd/controller.websiteHandler
        /builds/patronus/safeline-ce/management/tcontrollerd/controller/website.go:254 +0x17fb

**Comment by dundunHa** [comment]
麻烦检查一下tcd 和 mana的日志，截取一些信息上床
tcd:  safeline/logs/nginx/tcd.log

**Comment by GYLQ** [comment]
goroutine 1581 [running]:
git.in.chaitin.net/patronus/safeline-2/management/tcontrollerd/service.GetTitleAndIcon({0xc00042a100?, 0x0?, 0x641f40?})
&nbsp; &nbsp; &nbsp; &nbsp; /builds/patronus/safeline-ce/management/tcontrollerd/service/upstream.go:163 +0x9b7
git.in.chaitin.net/patronus/safeline-2/management/tcontrollerd/controller.websiteHandler.func1()
&nbsp; &nbsp; &nbsp; &nbsp; /builds/patronus/safeline-ce/management/tcontrollerd/controller/website.go:255 +0x49
created by git.in.chaitin.net/patronus/safeline-2/management/tcontrollerd/controller.websiteHandler
&nbsp; &nbsp; &nbsp; &nbsp; /builds/patronus/safeline-ce/management/tcontrollerd/controller/website.go:254 +0x17fb







孤桜懶契
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaitin/SafeLine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月16日(星期一) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chaitin/SafeLine] [Bug] 防护站点页面修改提交失败 (Issue #380)





 
麻烦检查一下tcd 和 mana的日志，截取一些信息上床
 tcd:  safeline/logs/nginx/tcd.log

**Comment by WvvvWv** [comment]
> management/webserver.log

webserver.log:

**Comment by WvvvWv** [comment]
> 麻烦检查一下tcd 和 mgt的日志，截取一些信息上传一下 tcd: safeline/logs/nginx/tcd.log mgt: safeline/logs/management/webserver.log
webserver.log

**Comment by WvvvWv** [comment]
> 麻烦检查一下tcd 和 mgt的日志，截取一些信息上传一下 tcd: safeline/logs/nginx/tcd.log mgt: safeline/logs/management/webserver.log
tcd.log:
![image](https://github.com/chaitin/SafeLine/assets/40822202/65a1147f-5c4a-4cda-91f6-464380b29f0a)

webserver.log:
![image](https://github.com/chaitin/SafeLine/assets/40822202/0f3375fc-5638-424e-a49a-d09ad80fcfca)

**Comment by GYLQ** [comment]
time="2023/10/15 23:16:04" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:16:04" level=info msg="Get update length 80057, 80057" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:16:04" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:16:04" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:16:12" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:16:12" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:16:12" level=info msg="Get update length 75631, 75631" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:16:12" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:16:12" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:17:27" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:17:27" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:17:27" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:17:27" level=info msg="Get update length 78021, 78021" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:17:27" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:17:27" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:17:31" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:17:31" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:17:31" level=info msg="Get update length 75846, 75846" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:17:31" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:17:31" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:18:32" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:18:32" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:18:33" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:18:33" level=info msg="Get update length 77989, 77989" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:18:33" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:18:33" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:18:45" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:18:45" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:18:45" level=info msg="Get update length 76424, 76424" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:18:45" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:18:45" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:19:14" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:19:14" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:19:14" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:19:14" level=info msg="Get update length 78396, 78396" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195
time="2023/10/15 23:19:14" level=info msg="full push success, version: 1" file=helper.go func=/patronus/safeline-2/management/webserver/pkg/fvm.CompileAndPush line=129 logger=fvm
time="2023/10/15 23:19:14" level=info msg="Recv updating website rsp: err(false), msg()" file=website.go func="/patronus/safeline-2/management/webserver/rpc.(*StreamClient).recvLoop" line=130 logger=grpc
time="2023/10/15 23:19:18" level=info msg="Generate FSL" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.GenerateFullFSL line=142 logger=fvm
time="2023/10/15 23:19:18" level=info msg="Push FSL to http://safeline-detector:8001" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=190
time="2023/10/15 23:19:18" level=info msg="Get update length 77960, 77960" file=fvm.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*FVM).PushFsl" line=195



&nbsp;


孤桜懶契
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月16日(星期一) 中午11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chaitin/SafeLine] [Bug] 防护站点页面修改提交失败 (Issue #380)





  
麻烦检查一下tcd 和 mgt的日志，截取一些信息上传一下 tcd: safeline/logs/nginx/tcd.log mgt: safeline/logs/management/webserver.log
 tcd.log:
 
  
webserver.log:

**Comment by WvvvWv** [comment]
> 麻烦检查一下tcd 和 mgt的日志，截取一些信息上传一下 tcd: safeline/logs/nginx/tcd.log mgt: safeline/logs/management/webserver.log

tcd.log:
![image](https://github.com/chaitin/SafeLine/assets/40822202/65a1147f-5c4a-4cda-91f6-464380b29f0a)

webserver.log:
![image](https://github.com/chaitin/SafeLine/assets/40822202/0f3375fc-5638-424e-a49a-d09ad80fcfca)

**Comment by dundunHa** [comment]
定位到了问题，会在下个版本修复。

**Comment by WvvvWv** [comment]
> 定位到了问题，会在下个版本修复。

好的，辛苦：）

**Comment by dundunHa** [comment]
尝试升级到 3.7.3看看

**Comment by WvvvWv** [comment]
> 尝试升级到 3.7.3看看

升级了，目前修改配置已无问题，感谢:)

**Comment by wslf1995** [comment]
Service is abnormal, and the nginx conf cannot be updated for the time being. Please go to the shell to check the relevant logs报错
