### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 1764364648** [chaitin/SafeLine#381]
### 问题描述

[我现在去防火墙里面删掉站点击提交一直都不能提交而且都会把cpu的占用率拉满直接导致服务器卡死然后防火墙就进不去和网站也进不去我就必须去重启才能解决之前的版本都没有这样过
![a05fc0d05c06c841b268e4150e55a9fe](https://github.com/chaitin/SafeLine/assets/123971622/ec5c700d-d441-4084-99cd-26c1f2a7f03e)
![c84f332f91447541ce373e952b9da9e8](https://github.com/chaitin/SafeLine/assets/123971622/2a1807c8-ae3d-4bc5-bfbb-2f77124ee52e)
![7cccbecf0403099f57927d88e848f89c](https://github.com/chaitin/SafeLine/assets/123971622/fc8738f9-0f19-4b31-9566-5745ce2b1434)

### 复现方法

去防火墙里面删掉站点点击提交就会一直在哪里转圈圈然后服务器占用率是百分之100了

### 期望的结果

我希望能解决一下这个问题

**Comment by yrluke** [comment]
师傅是配置了很多ip黑名单以及白名单吗

**Comment by Lorna0** [comment]
推测有可能是站点或者规则数量比较大，设备资源比较少，编辑的时候构建引擎跑满了。但是信息不太够，不能确定。

目前问题还存在么？可以先升级一下版本、增加设备资源试试

**Comment by Lorna0** [comment]
时间有点久，先关闭了。有更多信息的话可以补充一下。
