### ISSUE TITLE
端口转发获取到的地址是内网地址，获取不到用户的真实IP

### ISSUE THREAD

**Issue by Omoinemie** [chaitin/SafeLine#382]
### 反馈内容

我有一台服务器，安装了虚拟机，虚拟机上安装雷池，将服务器的公网80端口转发到雷池80，但雷池获取不到用户的真实IP，一直都是10.0.0.1，有什么方法或者工具可以解决吗
服务器公网Ip：*.*.*.*
服务器内网IP：10.0.0.1
雷池内网IP：10.0.0.2
![image](https://github.com/chaitin/SafeLine/assets/31991443/3184031f-87bd-4d49-b4d4-00af9b3742d5)

**Comment by yrluke** [comment]
目前没想到比较好的办法，这个问题的逻辑大概是：
