### ISSUE TITLE
[建议] 主控和节点功能

### ISSUE THREAD

**Issue by wwdmy123** [chaitin/SafeLine#383]
### 背景与遇到的问题

多个服务器部署雷池管理比较麻烦，比如10个服务器添加站点修改配置啥的就需要挨个登录，很麻烦

### 建议的解决方案

希望出一个主控和节点类似的功能，一个后台可以管理多个节点。在主控添加后，全部雷池都生效。在主控添加节点后，就可以全部生效，期待。

**Comment by wwdmy123** [comment]
具体就是主控安装，节点装完后。共用一个后台

**Comment by wwdmy123** [comment]
添加节点后，主控修改全部节点都生效

**Comment by yrluke** [comment]
欢迎师傅在我们的官网留手机号，我们的企业版支持集群部署，社区版就不做重复的工作了，感谢师傅支持
