### ISSUE TITLE
[建议] DDNS域名回源场景优化 / 动态解析 upstream 的域名

### ISSUE THREAD

**Issue by bh1xaq** [chaitin/SafeLine#384]
### 背景与遇到的问题

默认情况下，Nginx只会在启动的时候解析一次upstream块里配置的域名。
原站为DDNS域名，当DDNS域名变化时，Nginx还会缓存原来的解析记录，导致链接超时，希望可以在Nginx配置上做一下兼容。

### 建议的解决方案

Tengine 是支持这种模式的，参考文档。http://tengine.taobao.org/document_cn/http_upstream_dynamic_cn.html

**Comment by garrettdo** [comment]
加上了吗

**Comment by homestoo** [comment]
> 加上了吗

resolver 114.114.114.114 valid=24h;
resolver 8.8.8.8 valid=12h;
resolver_timeout 5s;
应该可以这样

**Comment by bh1xaq** [comment]
> > 加上了吗
> 
> resolver 114.114.114.114 valid=24h; resolver 8.8.8.8 valid=12h; resolver_timeout 5s; 应该可以这样

Tengine 是支持这种模式的，参考文档。http://tengine.taobao.org/document_cn/http_upstream_dynamic_cn.html

需要在 upstream {} 块中增加 dynamic_resolve fallback=stale fail_timeout=30s;

**Comment by homestoo** [comment]
> > > 加上了吗
> > 
> > 
> > 解析器114.114.114.114有效=24小时；解析器8.8.8.8有效=12h；解析器超时5秒；应该可以这样
> 
> Tengine 是支持此类模式的，参考文档。http://tengine.taobao.org/document_cn/http_upstream_dynamic_cn.html
> 
> 需要在上游{}块中增加dynamic_resolvefallback=stalefail_timeout=30s;

前面的dns填错了，实际是这样，亲测可用 resolver 填入你的动态域名 valid根据你自己的需求填缓存时间

http {  里面填入
resolver xxxx.com valid=600s;
    resolver_timeout 5s;

我的是软路由每天定时5点重拨，如果还不放心的话，做一个定时任务我做的是5：30和6:00定时定时任务重启 docker restart safeline-tengine 启动这个容器

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
