### ISSUE TITLE
[Bug] 开启ssl_stapling后的异常

### ISSUE THREAD

**Issue by killsky** [chaitin/SafeLine#385]
### 问题描述

在默认nginx.conf配置## SSL Settings里添加：
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_dhparam /etc/nginx/certs/dhparam.pem;
    ssl_trusted_certificate /etc/nginx/certs/cert_1.crt;
执行docker exec safeline-tengine nginx -t测试配置无任何输出，docker log也无报错，测试网站OCSP已正常开启
![image](https://github.com/chaitin/SafeLine/assets/24229821/26aff901-5a45-4d44-a48c-a3e0c1da04a7)
然而此时添加和修改站点报错：
![image](https://github.com/chaitin/SafeLine/assets/24229821/785199c6-c534-4266-9885-e20e37a86620)

### 复现方法

1.删除添加配置，逐条倒序添加都可正常输出结果
2.唯独添加ssl_stapling on后无输出结果
3.删除ssl_stapling on行
4.在backend_1添加亦是如此
5.测试正常输出则添加修改站点无问题，只要添加选项开启就无法使用

### 期望的结果

添加ssl_stapling on选项后可以正常使用

**Comment by Lorna0** [comment]
雷池的目标不是替代 nginx。提供后台配置  nginx.conf 主要是想解决一些小众需求，或者临时支持一些不太好做的需求，实际支持的程度肯定有限。建议还是回到需求本身，讨论为什么需要支持这些配置。

**Comment by Lorna0** [comment]
时间有点长，先关闭。有关于 ssl_stapling 的需求的更多信息的话可以补充下，我们可以再 reopen。

**Comment by eagleyan888** [comment]
这就是为何要开启 OCSP stapling 的原因：
https://cloud.tencent.com/developer/article/1965319
建议站点配置页面增加一个checkbox勾选项：开启OCSP stapling ，用户勾选了就在server这一层增加：
        ssl_stapling on;
        ssl_stapling_verify on;

**Comment by Lvshujun0918** [comment]
遇到了与 @killsky 同样的问题

**Comment by xbingW** [comment]
目前引擎不支持此参数，需要等等
