### ISSUE TITLE
[Bug] 新版本防护站点无法添加，对数据库操作报错

### ISSUE THREAD

**Issue by zhoupeng0721** [chaitin/SafeLine#386]
### 问题描述

执行reload报错如下
 docker exec safeline-tengine nginx -s reload

nginx: [emerg] cannot load certificate "/etc/nginx/certs": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)

![afce93f8b65146a3371c62abf05f29c](https://github.com/chaitin/SafeLine/assets/73821692/eb78c6c6-3383-4378-a358-16d7b229d15b)

![0c3b5e75004b85a91f823085094541f](https://github.com/chaitin/SafeLine/assets/73821692/b71821cd-23cb-4d83-8cc4-5aba84f067f3)

### 复现方法

原因不明

### 期望的结果

修复漏洞

**Comment by DeronW** [comment]
这是管理 nginx 服务的异常导致的，可以尝试重启服务，推荐升级到新版本 3.10.1

**Comment by Lorna0** [comment]
时间有点久，先关闭。有更多信息可以补充下再 reopen。
