### ISSUE TITLE
社区版自定义请求被拒后返回的状态码

### ISSUE THREAD

**Issue by OnionTop** [chaitin/SafeLine#387]
## 业务场景
微信模板消息推送后，微信服务器会进行大量回调请求，告知服务器推送用户是否成功等信息，但因为站点性能问题，实在是扛不住微信分钟级近十万的并发回调

### 希望借助雷池的能力，保障自身业务
希望通过雷池的黑名单功能，将海量的微信回调请求拒绝掉，然后返回200状态码。因为社区版可以自己动手来进行返回页面自定义，所以想通过自定页面并返回200状态码，给微信回调请求一个确认的消息。当然该功能也是属于企业版的范畴，所以想知道有什么办法或者后续更新可以通过用户自己处理，使雷池社区版能达到自定义返回状态的功能

**Comment by zclaiqcc** [comment]
感觉 WAF 不是干这个事的。这种偏业务了，我个人觉得 nginx 直接写一个 server，直接 return 200，开一个 access.log 留个痕迹就行了。
