### ISSUE TITLE
[建议] 高频访问建议能针对不同的站点单独设置

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#388]
### 背景与遇到的问题

现在高频访问设置是通用的，有些网站资源多的，打开一次，访问次数就增加几十，很容易触碰限制，就得调高请求次数的限制，但是这样无疑会增加资源较少的网站风险。

### 建议的解决方案

高频访问建议能针对不同的站点单独设置

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/209
