### ISSUE TITLE
[建议]希望增加显示访问者IP地址及地域的功能 

### ISSUE THREAD

**Issue by omanikk** [chaitin/SafeLine#389]
### 背景与遇到的问题

我的业务涉及到用户画像，会统计在哪个地区的用户更感兴趣，如果从日志里获取ip再去寻找归属地比较麻烦，希望增加访问者IP属地功能，感谢

### 建议的解决方案

希望增加访问者IP属地功能，感谢

**Comment by zclaiqcc** [comment]
感觉不是 WAF 的能力范围呀，虽然流量过了 WAF，但是也不能啥都要在 WAF 上看到吧哈哈哈。WAF 还是更侧重于「安全检测」，师傅的场景更偏向于业务统计、用户数据建模等，不建议期待一个 all-in-one 的产品。或者换句话说，WAF 这边统计出来一个访问 IP 的地图，能对咱们网站的安全防护能力的建设提供哪些方面的支持？🤔 

issue 留着吧看看有多少师傅需要这个能力

**Comment by DeronW** [comment]
IP 地址库是付费的数据资料，并不算法能搞定的，如果用免费的 IP 地址库，数据准确性保证不了，还无法校验数据来源是否合法。免费软件的开发者不会考虑这个功能。

**Comment by Lorna0** [comment]
看起来跟首页 “30天访问来源地区” 也挺像的，满足不了么：
![image](https://github.com/chaitin/SafeLine/assets/56920727/b5bb86bc-e92b-4ad0-915b-04d6f5c0cb08)

**Comment by Lorna0** [comment]
时间有点久，先关闭。有更多信息的话可以再补充一下。
