### ISSUE TITLE
[建议] windows serve能装吗

### ISSUE THREAD

**Issue by wintsa123** [chaitin/SafeLine#391]
### 背景与遇到的问题

公司服务器是window served

**Comment by Kwaain** [comment]
目前必然不能，官方文档里已经明确：[安装问题 | 长亭雷池 WAF 社区版](https://waf-ce.chaitin.cn/docs/faq/install)；

雷池依赖 Docker。以后支持的概率也极小。

**Comment by zclaiqcc** [comment]
> 目前必然不能，官方文档里已经明确：[安装问题 | 长亭雷池 WAF 社区版](https://waf-ce.chaitin.cn/docs/faq/install)；
> 
> 雷池依赖 Docker。以后支持的概率也极小。

✅

企业级的需求暂时先排除，很少有社区用户会把网站假设在 Windows server 吧
