### ISSUE TITLE
[建议] 手机访问WAF，圆圈中间三个点的按钮点了没反应

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#392]
### 背景与遇到的问题
手机访问WAF，圆圈中间三个点的按钮点了没反应，运行模式那里的防护按钮，点击有反应，会有下拉列表弹出来。
![001](https://github.com/chaitin/SafeLine/assets/42561369/db4b93c4-f6fa-4456-a54d-b834e106e0b1)
![002](https://github.com/chaitin/SafeLine/assets/42561369/96ff84ef-ec5c-4e8b-ad6b-5aa2658bc4ac)
![003](https://github.com/chaitin/SafeLine/assets/42561369/14e40d61-d2df-4288-97fc-1c5d3bc027ab)

### 建议的解决方案

建议手机也能进行操作

**Comment by DeronW** [comment]
现在的管理页面是基于桌面浏览器设计的，手机操作的情况很多吗？手机操作的时候，OTP 密码登录页不太方便吧

**Comment by sifanx** [comment]
> 现在的管理页面是基于桌面浏览器设计的，手机操作的情况很多吗？手机操作的时候，OTP 密码登录页不太方便吧

手机操作，OTP输入密码没问题，就是白名单规则、黑名单规则或者人机认证导致访问网站被拦截，我想临时禁用规则，就无法在手机上操作。

**Comment by Little-King2022** [comment]
长按可以点击

**Comment by sifanx** [comment]
> 长按可以点击

长按的确可以，谢谢了
