### ISSUE TITLE
[Bug]  安卓手机 alook 浏览器无法通过人机识别

### ISSUE THREAD

**Issue by DeronW** [chaitin/SafeLine#393]
### 问题描述
![df79a6f5f78a105214677760b7a79e38](https://github.com/chaitin/SafeLine/assets/780596/fa484373-4f08-4c6e-921e-d4b32b899c50)

### 复现方法

1. 用 alook 浏览器通过人机识别
2. 部分国产手机自带浏览器也有这个问题

### 期望的结果

通过人机识别

**Comment by DeronW** [comment]
3.9 版本中已修复，问题原因是通过加载 iframe 获取 userAgent 导致 alook 浏览器发生跳转。

**Comment by Lorna0** [comment]
注：云端人机验证服务修复，3.8 版本不更新本地 waf 也会自动修复
