### ISSUE TITLE
[建议] 可以在频率限制页面加一个刷新按钮吗？

### ISSUE THREAD

**Issue by flacce** [chaitin/SafeLine#396]
### 背景与遇到的问题

当频率限制规则设置的容易命中时，需要手动放行。每次需要重新进入该页面，才有被限制的IP信息。
![图片](https://github.com/chaitin/SafeLine/assets/64127000/725f6625-15b8-41ec-b0fe-a699bfe58365)

### 建议的解决方案

建议在防护配置------>频率限制里面增加一个刷新按钮，方便查看被拦截信息。

**Comment by jssolo** [comment]
你是要一直盯着这个页面吗？高频限制本来就是防止恶意攻击请求的，如果误拦的多，你可以重新设置规则，靠人工解封不现实吧

**Comment by Lorna0** [comment]
确实这种情况应该先调整规则、降低误拦概率。

**Comment by Lorna0** [comment]
时间有点久，先关闭了。有更多信息可以再补充一下。
