### ISSUE TITLE
[Bug] 人机验证在 iframe 中会陷入循环验证

### ISSUE THREAD

**Issue by DeronW** [chaitin/SafeLine#397]
### 问题描述

iframe 嵌套的子页面进行人机识重复验证直到失败

### 复现方法

任意 iframe 中测试

### 期望的结果

通过认证

**Comment by DeronW** [comment]
3.9 版本中已修复，iframe 中可以通过 cookie 进行人机验证，但必须在 https 下

**Comment by Lorna0** [comment]
注：云端人机验证服务修复，3.8 版本不更新本地 waf 也会自动修复
