### ISSUE TITLE
[建议] 在人机验证配置页面增加更多选项：

### ISSUE THREAD

**Issue by chettestwef** [chaitin/SafeLine#398]
### 背景与遇到的问题

如，在命中这块，可以加入一个请求量，这个请求量可以设置，大于或等于这个请求量会开启人机验证，这个判断的是web站点的总请求量

### 建议的解决方案

如：站点xxxx.com 在60秒被访问次数超过 xxx次，自动开启人机验证，并在xx分内没有被再次触发自动关闭

**Comment by DeronW** [comment]
已经有了，可以设置 “高频访问”

<img width="983" alt="iShot_2023-10-21_20 51 21" src="https://github.com/chaitin/SafeLine/assets/780596/444e8365-e2be-4200-a483-9a388a554874">

**Comment by chettestwef** [comment]
> 已经有了，可以设置 “高频访问”
> 
> <img alt="iShot_2023-10-21_20 51 21" width="983" src="https://user-images.githubusercontent.com/780596/277109062-444e8365-e2be-4200-a483-9a388a554874.png">
不是，这个是针对单个ip做的限制，因为大部分cc攻击都是分布式，若是分布式更多，单个ip请求量少的话是不会触发这个规则的，我的意思是在这个页面：
![image](https://github.com/chaitin/SafeLine/assets/99162086/24cfc28b-ecb5-468a-b0de-c4355b09ef25)
新增一个规则：访问频率，这个访问频率是按照当前站点的所有请求量判断的

**Comment by Lorna0** [comment]
>> 已经有了，可以设置 “高频访问”
> @chettestwef 
> 不是，这个是针对单个ip做的限制，因为大部分cc攻击都是分布式，若是分布式更多，单个ip请求量少的话是不会触发这个规则的，我的意思是在这个页面：
> 新增一个规则：访问频率，这个访问频率是按照当前站点的所有请求量判断的

“高频访问限制” 就是针对所有请求量判断的呀。

**Comment by chettestwef** [comment]
> > > 已经有了，可以设置 “高频访问”
> > > @chettestwef
> > > 不是，这个是针对单个ip做的限制，因为大部分cc攻击都是分布式，若是分布式更多，单个ip请求量少的话是不会触发这个规则的，我的意思是在这个页面：
> > > 新增一个规则：访问频率，这个访问频率是按照当前站点的所有请求量判断的
> 
> “高频访问限制” 就是针对所有请求量判断的呀。还是没理解你想要的效果。

**Comment by chettestwef** [comment]
> > > > 已经有了，可以设置 “高频访问”
> > > > @chettestwef
> > > > 不是，这个是针对单个ip做的限制，因为大部分cc攻击都是分布式，若是分布式更多，单个ip请求量少的话是不会触发这个规则的，我的意思是在这个页面：
> > > > 新增一个规则：访问频率，这个访问频率是按照当前站点的所有请求量判断的
> > 
> > 
> > “高频访问限制” 就是针对所有请求量判断的呀。还是没理解你想要的效果。

啊这，没事了，谢谢大佬解答
