### ISSUE TITLE
容器ip和腾讯云内置ip冲突

### ISSUE THREAD

**Issue by xishir** [chaitin/safeline#40]
Safeline默认ip段和腾讯云内置ip冲突，导致服务器网络异常
safeline Gateway: "169.254.0.1",

ping mirrors.tencentyun.com
PING mirrors.tencentyun.com (169.254.0.3) 56(84) bytes of data
From xxx (169.254.0.1) icmp_seq=40 Destination Host Unreachable

尝试修改compose.yaml中的169.254为其他网段，但是没有用，可能镜像里有hardcode

**Comment by luweijun1992** [comment]
> Safeline默认ip段和腾讯云内置ip冲突，导致服务器网络异常 safeline Gateway: "169.254.0.1",
> 
> ping mirrors.tencentyun.com PING mirrors.tencentyun.com (169.254.0.3) 56(84) bytes of data From xxx (169.254.0.1) icmp_seq=40 Destination Host Unreachable
> 
> 尝试修改compose.yaml中的169.254为其他网段，但是没有用，可能镜像里有hardcode

docker compose down 之后再up -d 看看，应该可以的。
或者你down之后看看safeline-ce的网络是否被移除；docker network ls

**Comment by xishir** [comment]
> > Safeline默认ip段和腾讯云内置ip冲突，导致服务器网络异常 safeline Gateway: "169.254.0.1",
> > ping mirrors.tencentyun.com PING mirrors.tencentyun.com (169.254.0.3) 56(84) bytes of data From xxx (169.254.0.1) icmp_seq=40 Destination Host Unreachable
> > 尝试修改compose.yaml中的169.254为其他网段，但是没有用，可能镜像里有hardcode
> 
> docker compose down 之后再up -d 看看，应该可以的。 或者你down之后看看safeline-ce的网络是否被移除；docker network ls

 docker compose down 之后再up -d ，服务可以正常启动，但是添加站点的时提示No subscriber，看日志里还是有往169.254.发请求

logs/nginx/tcd.log:time="2023/04/25 22:31:21" level=error msg="Error occurred when handling controller: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 169.254.0.4:9002: connect: connection refused\"" file=main.go func=main.handleLoop line=42 logger=main

**Comment by luweijun1992** [comment]
> 

想起来了，你修改compose.yaml中的网段没用，因为配置文件配置静态IP地址了
这个等厂家优化配置文件把。
因为里面可能还有其他调用用的是静态IP。

**Comment by zclaiqcc** [comment]
嗯有一个服务硬编码了 169.254.0.x，已经优化了，本周发布的版本带上这个优化

**Comment by yrluke** [comment]
又改了一下，选择了一个小段，选择172.22.222.0/24的原因是：
1. 172内网段
2. 避开docker 默认网段
3. 避开常见的腾讯云的default vpc网段
