### ISSUE TITLE
[建议] 申请免费证书可否用ecc算法

### ISSUE THREAD

**Issue by basel-zhang** [chaitin/SafeLine#400]
### 背景与遇到的问题

目前是RSA算法

### 建议的解决方案

改为ECC或者提供ECC选项

**Comment by DeronW** [comment]
免费证书使用 acme 申请，并不需要配置证书算法，都是服务自动维护的，手动干预会变得复杂，要求算法是有什么特殊场景吗？

**Comment by basel-zhang** [comment]
ECC算法也是自动的呀。只要在申请的命令行加上ECC参数就行了。
`--keylength ec-256`

> 采用ECC算法的SSL证书是256位，密钥长度只有RSA的2048位的八分之一。赛门铁克（Symantec）曾做过专题研究，Apache服务器部署256位的ECC SSL证书和部署同等加密强度的3072位RSA SSL证书，Web服务器对ECC算法的响应速度是RSA的18倍。ECC算法由于密钥更短，不仅能改进用户体验，还能降低用户手机的CPU能耗和流量，并且能降低网站服务器的CPU和内存资源，还能节省带宽费用，并且还能全面支持完美全向加密（PSF），具有更好的抗攻击能力。正因为ECC算法有这么多优秀特点，各大互联网巨头如内容分发服务巨头CloudFlare官网和其用户都是部署ECC SSL证书。谷歌官网和油管（YouTube）等网站也都是部署ECC SSL证书。

**Comment by samiux** [comment]
@basel-zhang 

Let's Encrypt 的证书已经是 ECC 算法了。

**Comment by basel-zhang** [comment]
但是雷池申请的仍然是RSA算法

![image](https://github.com/chaitin/SafeLine/assets/24664872/3b85becd-2d97-4717-99f5-fdc6e95ad56c)

**Comment by DeronW** [comment]
@basel-zhang   

证书算法的选择是出于安全和普遍这两点来考虑的，RSA 或者 ECC 目前都是安全的，所以在选择证书算法的时候选择更加普遍的 RSA 算法，雷池 waf 并非一个激进的颠覆者，而是一个安全的保护者。关于 ECC 的兼容性，可以参考 https://support.globalsign.com/ssl/ssl-certificates-life-cycle/ecc-compatibility 。

因为 acme 自动申请的，雷池的初衷也是简化 sa 的工作，因为在使用过程中，不同的证书算法是没有用户体验上的差别的，所以没有保留可选的 acme 配置参数

**Comment by basel-zhang** [comment]
ECC-256bit 的强度大约相当于 RSA-3072bit，意味着同等大小下安全性的提升和加密解密速度的加快，何乐而不为呢？

你给出的参考链接已经覆盖了很古老的操作系统和浏览器了。时至今日，这样的兼容性已经非常足够了。


> @basel-zhang
> 
> 证书算法的选择是出于安全和普遍这两点来考虑的，RSA 或者 ECC 目前都是安全的，所以在选择证书算法的时候选择更加普遍的 RSA 算法，雷池 waf 并非一个激进的颠覆者，而是一个安全的保护者。关于 ECC 的兼容性，可以参考 https://support.globalsign.com/ssl/ssl-certificates-life-cycle/ecc-compatibility 。
> 
> 因为 acme 自动申请的，雷池的初衷也是简化 sa 的工作，因为在使用过程中，不同的证书算法是没有用户体验上的差别的，所以没有保留可选的 acme 配置参数

**Comment by williamtsang88** [comment]
如果您很需要acme 的配置参数，您可以自行单独配置 acme。然后将对应的证书覆盖雷池的证书位置，然后通过定时任务 crontab 进行雷池 Nginx 的重启。

**Comment by DukeFox** [comment]
我也建议加上ECC算法的选项，不仅是安全性问题，这也能减少一定的性能开销。

**Comment by yuannancheng** [comment]
> 如果您很需要acme 的配置参数，您可以自行单独配置自己的 acme证书申请服务。然后将对应的证书覆盖雷池的证书位置，然后通过定时任务 crontab 进行雷池 Nginx 的重启。

你好，我目前相要使用这种方式来配置自己的ssl证书，请问我应该如何操作呢？是否需要先将雷池控制台里的现有证书全部删除，然后需要覆盖到哪个目录，覆盖之后如何在雷池控制台设置使用该证书，如果能有稍微更详细点的操作方法对我会有很大的帮助，谢谢。
因为我有很多个二级域名的网站需要配置ssl证书，但是雷池的ssl证书不能申请通配符证书，导致现在只能逐一为每个二级域名网站申请一次ssl证书，颇为繁琐。我现在已经在主机中配置好了自己的脚本通过DNS验证的方式申请通配符证书，只是不知道要如何应用到雷池上面。

**Comment by basel-zhang** [comment]
> 如果您很需要acme 的配置参数，您可以自行单独配置自己的 acme证书申请服务。然后将对应的证书覆盖雷池的证书位置，然后通过定时任务 crontab 进行雷池 Nginx 的重启。

我现在用的是这个方法。但是证书更新以后，雷池的证书管理不会随着acme证书的更新而更新。实际证书文件已经更新至5月1日，而这个证书貌似是存储与数据库，到期时间仍然是2月17日。我还是要手动更新它才行。

![image](https://github.com/chaitin/SafeLine/assets/24664872/f79cc217-6f90-4130-be47-c3024e00c362)

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
