### ISSUE TITLE
[建议]  人机验证页面增加响应码 Cache-Control，避免 cdn 缓存导致每次访问都是人机验证

### ISSUE THREAD

**Issue by DeronW** [chaitin/SafeLine#402]
静态资源路径开启了人机识别，同时路径被 cloudflare 缓存，导致被缓存静态资源固定为人机页面的内容

<img width="1196" alt="iShot_2023-10-21_19 03 58" src="https://github.com/chaitin/SafeLine/assets/780596/551d1d4a-5fdd-4f8c-b892-61c8020adef9">

**Comment by BLxcwg666** [comment]
建议 cloudflare 另外写规则绕过该url的缓存

**Comment by jssolo** [comment]
这个是你CDN缓存的问题

**Comment by Lorna0** [comment]
3.9 版本起，人机验证会加上响应头 Cache-Control，CDN 如果遵循协议的话就不会再缓存了。
