### ISSUE TITLE
[建议] 后台增加深色模式

### ISSUE THREAD

**Issue by BLxcwg666** [chaitin/SafeLine#403]
### 背景与遇到的问题

大晚上打开后台，能给眼睛闪瞎了（x

### 建议的解决方案

如题，增加一个按钮切换深色和浅色模式，或者定时切换（早6 / 晚6），或者根据用户浏览器判断

**Comment by DeronW** [comment]
精力有限，主题色现在没时间做

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/104
