### ISSUE TITLE
配置 400+ 个站点后，添加站点提示context canceled异常

### ISSUE THREAD

**Issue by huangyitong** [chaitin/SafeLine#404]
### 问题描述

添加站点之后提示context canceled

### 复现方法

添加站点（目前有400+站点，非通配符域名，主要是二级域名）
![image](https://github.com/chaitin/SafeLine/assets/67935454/a838c547-032e-44df-8e02-4d31a1cda089)
日志输出
![image](https://github.com/chaitin/SafeLine/assets/67935454/fcda57ea-84cc-403f-a65a-d43263d8b83e)

### 期望的结果

可以正常添加站点

**Comment by zhoupeng0721** [comment]
我这边也和你遇到同样问题了，添加站点达到这个数量后，整个雷池就自动所有功能无法使用。所有按钮都是报错

**Comment by zhoupeng0721** [comment]
最新版本
![image](https://github.com/chaitin/SafeLine/assets/73821692/3b3245f2-cac0-4898-9bfb-3e66950e30f2)

不仅站点无法添加
![image](https://github.com/chaitin/SafeLine/assets/73821692/1aee5342-e886-42e6-bbe7-b4e279b4587e)

配置的雷池的那个所有站点全部都没法访问了。端口都死了

所有雷池內的操作全都无法使用，防护也全失效了。
![image](https://github.com/chaitin/SafeLine/assets/73821692/9af19fb9-5eb4-46cd-a544-a5c9aeed9742)

**Comment by zhoupeng0721** [comment]
我也是400站点左右就雷池就全停止了。只能登录，不知道啥时候能更新出结果

**Comment by BLACKxZONE** [comment]
同样经常出现报错和这种情况。是不是只能重装雷池？  站点一多 那个反代到上游地址那个也无法访问了

**Comment by BLACKxZONE** [comment]
来个修复方案!!!

**Comment by BLACKxZONE** [comment]
![image](https://github.com/chaitin/SafeLine/assets/76398587/3e3752a9-89bc-49e8-84e4-ebc007599e81)

**Comment by kingru005511** [comment]
+1，同上，这个是不是达到一定量就无法支撑了

**Comment by kingru005511** [comment]
感觉日志正常，但程序就 是凉了

**Comment by Lorna0** [comment]
能顺便分享下啥情况需要这么多个站点吗？感觉已经超出了正常配置的范围了，即使这个问题能解决，估计还会有其他地方不好用。

**Comment by huangyitong** [comment]
有内部项目、外部项目，一个项目有演示环境、测试环境、预发布环境、正式环境，项目一多，二级域名数量不就上来了，而且有的项目光一个环境就好几个域名了

**Comment by huangyitong** [comment]
waf不用通配符域名配置，主要是想看每个二级域名的站点详情，包括访问量啊、资源情况啊

**Comment by Lorna0** [comment]
那数量也太多了，配上得花好长时间，配完了也不太容易管理，比如日常上线、调整策略、回收啥的。

是内部没有什么网站运营和运维的工具，希望用雷池顺便做简单的运营么。

relate to:
* https://github.com/chaitin/SafeLine/issues/365

**Comment by huangyitong** [comment]
我们waf是在最上游的一层，基本上是一次性配置的，也就二级域名作废才需要删掉二级域名而已。之后要上线、修改什么都在第二层nginx进行的。平时也就看看二级域名的攻击情况、访问量，来看看网站是不是有存在被攻击行为，不是拿雷池来当运营工具哈。

**Comment by Lorna0** [comment]
> 我们waf是在最上游的一层，基本上是一次性配置的，也就二级域名作废才需要删掉二级域名而已。之后要上线、修改什么都在第二层nginx进行的。平时也就看看二级域名的攻击情况、访问量，来看看网站是不是有存在被攻击行为，不是拿雷池来当运营工具哈。

但是上游那边新上线一个项目、测试环境的话，好像还是得在 WAF 上加个站点？提到运营是因为只防护的话其实配一级域名就差不多了，配么多二级域名只为了看访问量好像有点亏。因为每个站点在后台得单独建个 nignx 代理配置，多了就容易出现一些非预期现象。加上社区版希望尽量保持简单好用，功能交互上可能不会对这种情况有太多优化。不介意的话，倒也能用...

**Comment by huangyitong** [comment]
其实我觉得你们修复达到一定站点就报错的问题就行，维护和运行我们都可以管控。配二级域名还有一个好处就是，我要某个二级域名处于【防护】、【观察】还是【维护】模式都很方便。

**Comment by Lorna0** [comment]
> 其实我觉得你们修复达到一定站点就报错的问题就行，维护和运行我们都可以管控。配二级域名还有一个好处就是，我要某个二级域名处于【防护】、【观察】还是【维护】模式都很方便。

嗯报错问题会修的，上面讨论的是题外话。
站点配置模式的这个问题，其实就是 “功能交互上对多站点进行优化” ，现在很多配置没有做到站点级上，就是因为还没太考虑多站点的情况。

**Comment by Lorna0** [comment]
v3.11 应该已经修复，可以试一试

**Comment by huangyitong** [comment]
目前是可以继续添加站点了

**Comment by Lorna0** [comment]
OK，之后还会再提升一下站点管理这里的稳定性，有问题可以再报告
