### ISSUE TITLE
[建议] 能否针对不同站点有不同的私有配置

### ISSUE THREAD

**Issue by nooneaaaa** [chaitin/SafeLine#406]
### 背景与遇到的问题

1、黑白名单
2、频率限制
目前都是全局配置，是否可以优化为站点的个性化配置，毕竟不同站点场景差别很大。

**Comment by jssolo** [comment]
支持支持

**Comment by gougui** [comment]
频率限制能配置 请求路径 就完美了，毕竟只有部分路径需要限制

**Comment by Lorna0** [comment]
1. 黑白名单配置 host 就可以了
2. 限频 duplicate：
    * https://github.com/chaitin/SafeLine/issues/209
