### ISSUE TITLE
[建议] 可单独控制HSTS开关

### ISSUE THREAD

**Issue by fangpsh** [chaitin/SafeLine#407]
### 背景与遇到的问题

存在http:80 能自动跳转 https:443 的需求，但是打开强制 HTTPS 后，自动开启了HSTS：
```
Strict-Transport-Security:
max-age=63072000; includeSubdomains; preload
```
包含子域名，HSTS 应该谨慎开启。
另外是否支持includeSubDomains ，还需要根据证书的作用域判断，或者让用户自行选择。

### 建议的解决方案

HTTPS跳转功能和HSTS 拆分为2个选项，HSTS 可以再细化一下，例如判断是否要添加。可参考云CDN厂商的配置，
例如阿里云：
<img width="563" alt="image" src="https://github.com/chaitin/SafeLine/assets/1650540/c7485192-91f1-4fd4-a7fb-8dadbae6daa9">

**Comment by Lorna0** [comment]
能具体说下开启 HSTS 会出现什么问题么

**Comment by fangpsh** [comment]
> 能具体说下开启 HSTS 会出现什么问题么

实际生产环境，不一定所有子域名能够打开https。这个返回的头信息，会让浏览器直接拒接所有http请求。

**Comment by fangpsh** [comment]
>运维同学在刚刚做HTTPS 的时候，开启了HSTS，甚至加了includeSubDomains，某些老客户端访问HTTP的接口的时候跳到HTTS，由于SNI、加密套件兼容性等问题出现故障。HSTS 和HPKP 都是通过头信息传递给浏览器，浏览器都会根据max-age 缓存起来，所以在添加了HSTS 和HPKP 了之后，想要回滚，就没有在服务端回滚程序那么方便了。

**Comment by cpms** [comment]
建议 max-age 可以由用户指定，max-age 的值如果低于 15552000（6个月）的话，在一些检测 SSL 部署合规性的网站中，可能会导致降低评级。

**Comment by Lorna0** [comment]
> 1. 把 max-age 改为 5184000
> 2. 删去 includeSubDomains

已在 3.11 中修改

**Comment by Lvshujun0918** [comment]
[https://cszj.wang/2247.html](我的文章)，里面写了一种迂回自定义HSTS头的方法

**Comment by xbingW** [comment]
最新版 6.9.0 已支持站点级别配置
