### ISSUE TITLE
[建议] 啊，那我win server就用不了？

### ISSUE THREAD

**Issue by wintsa123** [chaitin/SafeLine#408]

**Comment by JiaqinKang** [comment]
安装个docker不就好了？

**Comment by clqs803** [comment]
Windows Server 还是老老实实跑图形化程序吧

**Comment by DeronW** [comment]
具体是指什么功能用不了？

**Comment by wintsa123** [comment]
> 安装个docker不就好了？

win server 2012 好像用不了docker

**Comment by shadow1163** [comment]
> > 安装个docker不就好了？
> 
> win server 2012 好像用不了docker

装一个windows server 2023吧

**Comment by Lorna0** [comment]
link
* https://github.com/chaitin/SafeLine/issues/391
