### ISSUE TITLE
t1k 协议是否开放？

### ISSUE THREAD

**Issue by downtown12** [chaitin/safeline#41]
项目里tengine（nginx）和detector之间通信用到的t1k协议，这个协议是否可以开放源码或者协议说明书？

**Comment by zclaiqcc** [comment]
t1k 暂不开源，社区版不提供二次开发的能力，建议联系企业版咨询，我们有 SDK 的方式可以进行流量接入。

**Comment by blaisewang** [comment]
here you go https://github.com/chaitin/safeline
