### ISSUE TITLE
[Bug] 站点详情中资源的今日请求量总和大于站点今日请求量

### ISSUE THREAD

**Issue by Hiram-Wong** [chaitin/SafeLine#410]
### 问题描述

每个资源访问量相加!==今日请求总量
<img width="1276" alt="image" src="https://github.com/chaitin/SafeLine/assets/30908279/880df55a-2002-4927-967e-ba3343fdd223">

### 复现方法

正常访问资源

### 期望的结果

每个资源访问量相加=今日请求总量

**Comment by DeronW** [comment]
应该是统计数据出错了，需要修复

**Comment by Lorna0** [comment]
老版本这里是存在问题的，后面修复过一次。能确认下是不是最新版么

**Comment by Hiram-Wong** [comment]
最新版本3.9.0

**Comment by Hiram-Wong** [comment]
更新 3.10.0 版本依然不对应，看了 changelog 是说修复该 bug

**Comment by dundunHa** [comment]
可以麻烦再截取一下你那边的图吗？

**Comment by Hiram-Wong** [comment]
> 可以麻烦再截取一下你那边的图吗？

<img width="1256" alt="image" src="https://github.com/chaitin/SafeLine/assets/30908279/8e6c88fe-5e4c-4047-bd71-fe8155e552a9">

**Comment by Lorna0** [comment]
每个资源访问量相加<=今日请求总量 是正常的，因为这里没有显示站点所有的资源。一是资源目前有 250 个的数量上限，一个是右上角采集设置可以配置排除采集的资源。

issue 原问题中 每个资源访问量相加>=今日请求总量 了，这是不正常的，3.10 修复的是这个。

**Comment by Hiram-Wong** [comment]
> 每个资源访问量相加<=今日请求总量 是正常的，因为这里没有显示站点所有的资源。一是资源目前有 250 个的数量上限，一个是右上角采集设置可以配置排除采集的资源。
> 
> issue 原问题中 每个资源访问量相加>今日请求总量 了，这是不正常的，3.10 修复的是这个。

没有配置排除采集

**Comment by xbingW** [comment]
最新版已修复
