### ISSUE TITLE
[建议] 希望能支持x86平台的openwrt

### ISSUE THREAD

**Issue by 52lemon6** [chaitin/SafeLine#412]
### 背景与遇到的问题

希望能支持x86平台的openwrt，比如我现在都是通过openwrt的端口映射来将内网的业务穿透到外网上去的，发生了啥攻击都不知道，希望后面能支持x86平台的openwrt

**Comment by DeronW** [comment]
可以描述具体的业务场景吗？如果是个人研究用途的话，这个功能的优先级会排在其他高优先任务的后面

**Comment by Lorna0** [comment]
精力有限只能测试主流的几个操作系统。其他的一般能装 docker 就都可以用（Linux x86 下），可以先试试，遇到问题好处理的话我们改改，就不承诺支持了。

**Comment by SIPC** [comment]
docker-compose.yml 改一下就能跑了，就是数据统计显示的时间可能有点问题

具体步骤

1. 去 [compose.yml](https://waf-ce.chaitin.cn/release/latest/compose.yaml) 下载 `compose.yml` 文件，重命名为 `docker-compose.yml`
2. 打开 `docker-compose.yml` 文件，删除所有  `- /etc/localtime:/etc/localtime:ro`  以及 fvm 容器的 volumes 参数
3. 运行官网的安装脚本，在下载镜像的时候替换脚本下载的 `docker-compose.yml` 文件即可
