### ISSUE TITLE
[Bug] 人机验证在 iframe 中验证成功后，请求一次就会失效

### ISSUE THREAD

**Issue by gougui** [chaitin/SafeLine#413]
### 问题描述

人机验证在 iframe 中验证成功后，请求一次就会失效，需要重新验证

### 版本号

3.9.0

### 复现方法

iframe中访问必现

### 期望的结果

修复

**Comment by DeronW** [comment]
3.9 版本中修复了该问题，可以升级后再试。但需要注意的是，因为浏览器的限制（比如 chrome），iframe 中的地址必须是 https 开头的，才允许传 cookie，现在的人机验证结果是通过 cookie 传递的。

**Comment by gougui** [comment]
> 3.9 版本中修复了该问题，可以升级后再试。但需要注意的是，因为浏览器的限制（比如 chrome），iframe 中的地址必须是 https 开头的，才允许传 cookie，现在的人机验证结果是通过 cookie 传递的。

我就是用的3.9版本哟，是用的https地址。成功后只能请求一次，后面又要重新认证才行

**Comment by DeronW** [comment]
![iShot_2023-10-31_16 49 40](https://github.com/chaitin/SafeLine/assets/780596/9ffb68bd-fcc9-47a7-b4b2-3f23141c0e7e)

这是 cookie 不生效导致的。原因是跨域名的 cookie 设置存在浏览器安全限制问题，只有在 https 下设置 SameSite=None ，才能跨域名设置 cookie

**Comment by DeronW** [comment]
![iShot_2023-10-31_16 49 40](https://github.com/chaitin/SafeLine/assets/780596/004675de-49bc-48d5-bad5-0a2cb9789b6c)
这是 cookie 不生效导致的。原因是跨域名的 cookie 设置存在浏览器安全限制问题，只有在 https 下设置 SameSite=None ，才能跨域名设置 cookie

**Comment by DeronW** [comment]
3.10 版本中已经修复该问题
