### ISSUE TITLE
[建议] 建议IP组支持拉取自定义链接的ip

### ISSUE THREAD

**Issue by fgbfgerbb2** [chaitin/SafeLine#414]
### 背景与遇到的问题

例如自动拉取中国大陆ip：https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt

例如自动拉取CloudFlare的ip：https://www.cloudflare.com/ips-v4

同时支持和长亭社区恶意 IP 情报一样定时拉取更新

**Comment by DeronW** [comment]
迟迟没做 IP 地理库主要还是数据来源的问题，需要长期、稳定、准确的 IP 地理库，这两个倒是可以考虑

**Comment by Lorna0** [comment]
relate to:
* https://github.com/chaitin/SafeLine/issues/374

**Comment by fangpsh** [comment]
需要IP库的支持，可以让用户导入自行购买的商业库或者免费库。maxmind，ip2location，ipip等。

**Comment by fangpsh** [comment]
+1，请求支持IP 组从外部链接订阅。

**Comment by fangpsh** [comment]
关联 issue: https://github.com/chaitin/SafeLine/issues/557

**Comment by Lorna0** [comment]
4.0.0 已发布，可以尝试一下。
