### ISSUE TITLE
[建议] 频率限制合并统计某 IP 已限制情况，方便直接拉黑

### ISSUE THREAD

**Issue by gougui** [chaitin/SafeLine#415]
### 背景与遇到的问题

建议将频率限制日志中还在封禁中的信息行优先显示在最前面，方便快速管理。如果能合并统计单个IP总共已限制请求数那就更好了，频繁的触发限制就可以毫不犹豫拉进黑名单。

### 建议的解决方案

新增功能

**Comment by Lorna0** [comment]
这好像是两个需求，分开列吧，方便收集意见

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
