### ISSUE TITLE
[建议] 加入黑名单的IP地址再访问应该与攻击日志区分展示。

### ISSUE THREAD

**Issue by vikiName** [chaitin/SafeLine#416]
### 背景与遇到的问题

最近把很多IP加入黑名单了，但是 日志展示不太友好，黑名单IP触发的访问和攻击还是展示在原来攻击事件日志里面，我还以为是新的攻击IP或者没拉黑成功。并且已经拉黑的IP关注度没那么高了，其实可以分开展示。

### 建议的解决方案

拉黑IP的日志与攻击事件IP的日志区分展示。

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/183

一些相关的：
* https://github.com/chaitin/SafeLine/issues/105
* https://github.com/chaitin/SafeLine/issues/34
* https://github.com/chaitin/SafeLine/issues/142
* https://github.com/chaitin/SafeLine/issues/262
* https://github.com/chaitin/SafeLine/issues/287
