### ISSUE TITLE
在wp中https访问http的问题

### ISSUE THREAD

**Issue by fenglindubu** [chaitin/SafeLine#418]
### 反馈内容

你好，我在搭建的时候访问wordpress站点，https请求，网页需要访问有些http的css js的文件，导致无法访问，chrome提示（已屏蔽：mixed-content） ，请教一下 有没有什么办法 强行https的

**Comment by clqs803** [comment]
在 wp-config.php 配置文件里插入一行HTTPS配置试试，不知道你要的是不是这个
```
$_SERVER['HTTPS'] = 'on';
```

**Comment by fenglindubu** [comment]
如果请求网站https://aaa.com 里面有js或者css http://aaa.com/main.css 会导致失败，有没有什么办法 使http重定向到https

**Comment by Lorna0** [comment]
> 如果请求网站https://aaa.com 里面有js或者css http://aaa.com/main.css 会导致失败，有没有什么办法 使http重定向到https

这是 雷池 waf 社区版项目，wordpress 相关的问题可以在 wordpress 项目中提问。
