### ISSUE TITLE
是否有基准测试or on kubernetes 与ingress的结合示例呢？

### ISSUE THREAD

**Issue by duiniwukenaihe** [chaitin/safeline#42]
希望能有基准的性能测试的对比文档？ 能有部署在kubernetes上与ingress结合的示例就更好了。毕竟云原生时代

**Comment by blaisewang** [comment]
雷池商业版提供 Ingress / Istio SDK，同时雷池本身可以部署在 Kubernetes 作为一个云应用。Ingress / Istio 业务可以无感接入安全防护，商业版采购详询：https://www.chaitin.cn/zh/contact-us
