### ISSUE TITLE
[建议] 希望增加可配置 proxy_protocol

### ISSUE THREAD

**Issue by CoolStars1** [chaitin/SafeLine#421]
### 背景与遇到的问题

因为我的Web业务目前放在内网，借助反向代理工具(frp) 使项目能被外部直接访问，因直接暴露不安全, 雷池waf单独部署。
但在使用过程中 发现 雷池Nginx并不支持 proxy_protocol, 例如我在`frpc config`中配置如下:
```ini
[https]
type = https
local_ip = (内网)雷池ip
local_port = (内网)雷池port
proxy_protocol_version = v2
```
雷池配置好站点后 访问时出现 `ERR_SSL_PROTOCOL_ERROR`

- 雷池站点以及上游Web站点均配置好了 SSL

### 建议的解决方案

希望能增加可配置 proxy_protocol

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/359
