### ISSUE TITLE
[建议] IP组数据 增加国外IP组数据，当业务系统只面向国内用户时

### ISSUE THREAD

**Issue by huangye123** [chaitin/SafeLine#423]
### 背景与遇到的问题

根据部署的蜜罐显示，很多扫描机器人IP来源国外，对于业务系统使用者不存在国外使用时，通过禁用国外访问可以有效提升安全性，减少被扫描的。

### 建议的解决方案

增加国外IP组数据源，支持将国外IP拉黑名单，直接减少被国外机器人扫描

**Comment by DeronW** [comment]
关联 
https://github.com/chaitin/SafeLine/issues/414
https://github.com/chaitin/SafeLine/issues/374

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/88
* https://github.com/chaitin/SafeLine/issues/414
