### ISSUE TITLE
[建议]支持自定义静态文件网站部署和自定义后端接口转发 

### ISSUE THREAD

**Issue by huangye123** [chaitin/SafeLine#424]
### 背景与遇到的问题

目前请求流程 WAF==>Nginx前端服务===》后端服务

相当于有两层Nginx，希望可以减少一层

### 建议的解决方案

希望请求流程WAF===>后端服务

可以将WAF直接将为Web前端服务器，有利于产品推广使用，又安全，又高效

**Comment by cfwl1111** [comment]
这个需求还是很有必要的

**Comment by Lorna0** [comment]
relate to:
* https://github.com/chaitin/SafeLine/issues/131
* https://github.com/chaitin/SafeLine/issues/266

**Comment by cfwl1111** [comment]
@Deron

> 现在的 waf 中配置 “上游服务” 的时候，就是配置后端服务的，至于是否需要额外的 nginx ，看业务要求。现在是哪里卡住了？无法去掉额外的 nginx 吗？ @cfwl1111

比如PHP项目就需要额外的web环境来支撑

**Comment by DeronW** [comment]
是指 PHP 的运行时吗？  如果是指 web 服务器的话，那么 waf 是不能代替 nginx 、apache、httpd 这样的服务的。它们不是重复，而是定位不同，甚至 waf 的安装是建议占用一台独立服务器的。虽然雷池的 waf 看起来是对nginx 的改造，但实际上，雷池waf 使用的 tengine 的改造版本，是专门针对 waf 做了优化，如果做负载均衡是可以的，但同时程度托管服务是不合适的。 waf 的目的不是代替 web 服务，是保护 web 服务。如果你的服务很简单，那么在 waf 的上游服务地址上直接配置 服务地址就可以了。嵌套多层 nginx 并不会给服务代理明显的副作用，不会变得更高效，去掉一层 nginx 也不会让服务变得更安全。

**Comment by Lorna0** [comment]
主要是要支持的话，界面配置会比较复杂。nginx 配置非常丰富，要完全替代的话还是有很大难度的。

留着看看社区意见。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion

**Comment by xbingW** [comment]
另外目前最新版 6.9.0 支持了静态文件建站，可以体验一下
