### ISSUE TITLE
[Bug] SSL证书窜站，出错绑成别的网站证书

### ISSUE THREAD

**Issue by 1355228922** [chaitin/SafeLine#426]
### 问题描述
![111](https://github.com/chaitin/SafeLine/assets/45515018/3747d4c6-599f-48cf-8ecf-9bff92555ea7)
雷池证书

![222](https://github.com/chaitin/SafeLine/assets/45515018/2e390270-c2a7-455c-b417-7ea6b4c03f27)
设置好后

![333](https://github.com/chaitin/SafeLine/assets/45515018/8772a7f6-2731-4294-bc44-4e55d4ec9f2b)
打开站上变成我另外一个其它的ssl

### 版本号

3.10.1

### 复现方法

多个ssl证书
多个ssl站和单http站
多个不同域名

### 期望的结果

防止

**Comment by ylwzbk** [comment]
刚好我也想提这个  
我这边给ip 域名绑定了一个 空白证书 按理说是没有任何域名信息的、但是我在ip证书夹再添加一个有域名信息的ssl证书之后访问那个绑定的ip  居然有显示域名的ssl证书 按理说 是不能被获得啊

**Comment by windghoul** [comment]
我也遇到过覆盖证书，升级之后出现证书回滚了，新的证书一直无法生效

**Comment by Lorna0** [comment]
经排查，问题原因是近期版本修改了证书的数据格式，系统中保留了部分历史格式的数据，不易彻底清除。在正常编辑和配置站点证书时，一切表现正常。但在 mgt 服务重启（包括升级时的重启）后，系统会按旧方法加载站点证书，导致加载成了历史版本上所引用的证书。

本 bug 在 3.10.3 中修复：

![image](https://github.com/chaitin/SafeLine/assets/56920727/1d3bc82b-7006-4335-b1e4-a0480cfb55eb)
