### ISSUE TITLE
[建议] 攻击事件的更新有点延迟

### ISSUE THREAD

**Issue by 1764364648** [chaitin/SafeLine#427]
### 问题描述

拦截是没有问题就是更新攻击事件哪里有延迟要过一会才会更新出来
![d5417b4d56fc8a8009dee32ed4d43808](https://github.com/chaitin/SafeLine/assets/123971622/41d38b88-76a3-4e66-a246-8c7fd7709c44)
![image](https://github.com/chaitin/SafeLine/assets/123971622/146d7c6d-fbc4-4eef-983a-a6aab555788e)

### 版本号

3.10.1

### 复现方法

拦截是没有问题就是更新攻击事件哪里有延迟要过一会才会更新出来

### 期望的结果

修复更新更新攻击事件哪里的延迟

**Comment by 1764364648** [comment]
在补充一下原始日志是会马上更新的攻击事件要等一会才会更新

**Comment by DeronW** [comment]
攻击事件是按是吗定期聚合的，聚合的间隔期间不产生新的事件。
日志，是实时的
事件，是带延迟聚合的

**Comment by Lorna0** [comment]
这个是期望的，因为事件需要从日志数据分析得出，会消耗一定资源。所以不是完全同步，否则会影响 waf 的实时检测性能。

改起来稍有点费功夫，大家体感延时很长么？

**Comment by Lorna0** [comment]
时间有点久，结论仍不太确定，先关闭。有关于延迟感受的更多信息可以补充下，我们可以再 reopen。
