### ISSUE TITLE
[建议] 频率限制增加自动加入黑名单 / 高频访问或攻击后永久封禁

### ISSUE THREAD

**Issue by gougui** [chaitin/SafeLine#428]
### 背景与遇到的问题

恶意请求在拦截后，也会持续访问，这种可以添加自动加入黑名单选项配置，在拦截内访问一定次数直接加入黑名单。
还有我高频攻击配置的60秒20次，这种情况没有触发有点懵呀？
![image](https://github.com/chaitin/SafeLine/assets/30085847/10cb7a0a-81fa-45ac-af3a-96d5593891ae)

### 建议的解决方案

新增功能

**Comment by Lorna0** [comment]
relate to :
* https://github.com/chaitin/SafeLine/issues/334
* https://github.com/chaitin/SafeLine/issues/415

关于下面的那个问题，如果 “高频访问” “高频攻击” 都配置的是 “直接封禁”，然后某 IP 先触发了其中一个，那么封禁结束前不会再次触发第二个限频封禁。师傅的可能是这个原因。

**Comment by kedyao** [comment]
对哦 恶意的IP 多次攻击达到频率限制次数后就直接加入到黑名单里   就不用对恶意IP拉黑又等时间解封了 如果有误封手动在去黑名单解开就好

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
