### ISSUE TITLE
建议丰富一下功能，提高WAF登陆使用率[建议] 

### ISSUE THREAD

**Issue by yuweihuihui** [chaitin/SafeLine#429]
### 背景与遇到的问题

现在的问题是，雷池WAF社区版功能太单薄，除了看下攻击大概情况，没有其他可以看的了，建议丰富一下，新增如下的功能：
1、使用优化，凡有列表的地方，增加排序功能；凡有可分析内容的地方，新增导出功能。
2、不知道谁访问了自己和不知道访问者具体干了什么，首页只展示了大概的访问情况，但看不到具体的独立访问IP地址及地理位置信息，访问了些系统哪些页面等信息，建议新增每日访问独立IP统计列表，附带具体IP地址、地理位置信息、具体访问的页面URL。
3、建议提供自动永久封止IP地址功能，比如有些IP地址会使用不同方法几千上万次去尝试攻击信息系统，可以新增设定一个攻击阀值 ，当雷池WAF检测到这种攻击次数超过用户设定的受攻击阀值时，自动将其IP丢到黑名单，永久封禁，而不是仅仅阻断其每次的攻击行为，避免同一个恶意IP持续不断的攻击。
4、提供一个地区黑名单功能，什么意思呢？一个单位或公司有很多系统，但并不是每个系统需要全世界都能访问，完全可以根据IP地址库，根据系统根据访问需求，将合法访问地区限制在一个市、一个省、一个国家，比如我有一个系统，仅仅只需要武汉市内的用户能访问，如果有这个功能，我就能将其访问区域限制在武汉市内，这样用最低的成本，最简单的方法，从非技术层面提高了我的系统安全性，并不仅仅依靠检测规则和程序分析等技术手段。

**Comment by DeronW** [comment]
感谢建议，顺便关注了一下题主的账号，发现是昨天刚刚注册的，而且只有一个活动事件，就是给雷池提了这个 issue。所以大胆猜测，题主是专门到 Github 上提供建议的，而且还注册了新账号，并且真的是体验过雷池 waf 产品的。

这几点建议，我分别解释一下
1.  关于网页列表，目前一共有：事件列表、日志列表、站点列表、黑白名单列表、人机列表、证书列表、IP组列表。其中 “事件” 和 “日志” 以外的都是配置项列表，雷池的产品定位是中小客户，所以我们认为配置项不会太多，所以除 “事件” 和 “日志” 外的列表内容都不多，因此没有复杂的列表操作。然后是 “事件” 和 “日志”，处于降低对系统硬件配置要求的原因，没有做做复杂的日志分析功能，也确实导致分析能力不强。将来会增加日志导出、syslog 功能，已经在计划中，只是优先级不高 
2. waf 的分析功能目前还不完善，是出于 2 个原因，首先是期望 waf 专注做 waf 的事情，保护业务；其次是安全分析在行业内的趋势是集中分析，把 waf、扫描、情报、资产 等所有数据汇总分析，单独的数据分析维度不够已经不适应现在险恶的网络环境了（长亭也有自己的数据平台分析工具  https://www.chaitin.cn/zh/cosmos 欢迎咨询）。
3. 封禁 IP 的功能现在已经支持，根据攻击频率可以自动封禁，但不能永久封禁，不是做不到，而是容易误伤，国内在人口密度比较大的社区， IP 分配往往以一栋楼为单位的，如果因为一栋楼里的一个人做了危险操作，把整栋楼的 IP 永久封禁了，误伤太严重，所以现在采用的是临时封禁方案。
4. 地区黑名单的功能，也有其他用户提出过，是比较合理的需求，我们会提高这个任务的优先级，尽快实现。

**Comment by Lorna0** [comment]
感谢建议。另外如果需求比较明确，建议分开提交 issue，一个 issue 只描述一个问题和建议。这样能方便单独点赞和评论，我们能收集更好地到社区的倾向，也更方便向大家同步开发进展。

以下是之前已经提交过的相关建议，建议集中到对应 issue 中讨论：
* https://github.com/chaitin/SafeLine/issues/334
* https://github.com/chaitin/SafeLine/issues/415
* https://github.com/chaitin/SafeLine/issues/428
* https://github.com/chaitin/SafeLine/issues/88
