### ISSUE TITLE
[建议] 希望白名单可以针对某一攻击类型加白

### ISSUE THREAD

**Issue by Fz-github** [chaitin/SafeLine#430]
### 背景与遇到的问题

类似开发文档的站点容易触发XSS告警，但加白的时候，把整个url都加白了，其他攻击类型也检测不到了。所以希望加白名单的时候可以针对某一攻击类型加白。

### 建议的解决方案

加白名单的时候可以针对某一攻击类型加白。

**Comment by DeronW** [comment]
![iShot_2023-11-08_10 45 11](https://github.com/chaitin/SafeLine/assets/780596/a65b1d66-1b3a-4f84-ad96-11f80897eed6)

可以的，在 “防护配置”》“语义分析” 里把 “XSS检测” 禁用就可以了

**Comment by Fz-github** [comment]
@DeronW 但我只想这一个路径加白XSS，而不是整一个站点都加白XSS。

**Comment by Fz-github** [comment]
@DeronW  在 “防护配置”》“语义分析” 里把 “XSS检测” 禁用，并没有效果，一样会有XSS告警。
![image](https://github.com/chaitin/SafeLine/assets/28009927/0d7bf25d-8526-401c-a8a7-05fbf28cf580)
![image](https://github.com/chaitin/SafeLine/assets/28009927/aad39c5e-f3e8-4b9b-a418-ada6bf6b107c)

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
