### ISSUE TITLE
[Bug] 人机验证问题

### ISSUE THREAD

**Issue by xqw8889** [chaitin/SafeLine#431]
### 问题描述

failed to load html from https://challenge.rivers.chaitin.cn/recaptcha/api/index.html?%0.7965894470900767

### 版本号

3.10.3

### 复现方法

目前任何人机页面均会出现

### 期望的结果

在什么情况下出现此类错误！

**Comment by Little-King2022** [comment]
是人机验证api接口的ssl证书问题，群里说在修复了

**Comment by DeronW** [comment]
如果人机验证服务出现问题，就允许用户继续访问，这种逻辑是否可行

**Comment by Lorna0** [comment]
人机验证服务线上故障，已在昨日修复。
后续我们会考虑一下如何规避类似问题，或者尽量减小影响。

**Comment by xqw8889** [comment]
> 如果人机允许验证服务出现问题，就用户继续访问，这种逻辑是否支持

这种逻辑不建议使用 容易被利用绕过，是否可以采用冗余线路方案
