### ISSUE TITLE
[Bug] 跳转到一个未知的链接

### ISSUE THREAD

**Issue by liulinlin** [chaitin/SafeLine#432]
### 问题描述

正常使用中，发现，网站显示这个内容了。
![image](https://github.com/chaitin/SafeLine/assets/8653966/8ce4044d-c2cc-4ae1-978d-fd4b52db8515)

### 版本号

3.10.0

### 复现方法

偶然的，无法复现，目前也不知道怎么恢复。

### 期望的结果

了解是什么原因导致的，如何防范。

**Comment by liulinlin** [comment]
目前观察模式下，可以正常的使用。

**Comment by Little-King2022** [comment]
是人机验证api接口的ssl证书问题，群里说在修复了

**Comment by liulinlin** [comment]
> 是人机验证api接口的ssl证书问题，群里说在修复了

没有在群里，我看网页上面的链接点击不进去，可以拉进群吗？

**Comment by Little-King2022** [comment]
dashboard页面右上角有讨论组的按钮，扫码就可以加企业微信群
