### ISSUE TITLE
[建议] 能否在站点配置中增加https强制跳转，而非全局。

### ISSUE THREAD

**Issue by lendy98** [chaitin/SafeLine#434]
### 背景与遇到的问题

强制https现在很流程，能否增加强制跳转到https

目前是一个域名代理后台一台设备，能否做目录级别的代理，如一个目录代理一台服务器

当然，更好的功能是nginx还有负载功能。

目前的功能还不如直接直接配置nginx反代理，在自己增加个过滤模块。

**Comment by Lorna0** [comment]
> 强制https现在很流程，能否增加强制跳转到https

没理解，目前支持一键跳转 https 呀

> 目前是一个域名代理后台一台设备，能否做目录级别的代理，如一个目录代理一台服务器

duplicate，请集中到之前的 issue 中讨论: 
    * https://github.com/chaitin/SafeLine/issues/131

> 当然，更好的功能是nginx

目前支持后台自定义niginx 配置，可以查阅官网文档

> 还有负载功能。

duplicate，请集中到之前的 issue 中讨论: 
    * https://github.com/chaitin/SafeLine/issues/46

提示：创建前可以搜索一下是否已有 issue。一个 issue 尽量只描述一个问题，方便集中大家的意见。

**Comment by lendy98** [comment]
搜索了下，没这个需求，估计大家都不是很感兴趣，但实际很多放代理上和waf上都把强制https跳转放到了站点配置，而不是全局。

以下是几个其他产品的截图，供参考。

![微信图片_20231123095554](https://github.com/chaitin/SafeLine/assets/59783960/151bc6d2-7669-41fc-92a3-5ef26c10aabb)

![微信图片_20231123095722](https://github.com/chaitin/SafeLine/assets/59783960/490cc207-88fd-4ca8-b30c-4f2d65b92c44)

**Comment by Lorna0** [comment]
“站点配置中增加https强制跳转，而非全局。” 吗？

也有的：
* https://github.com/chaitin/SafeLine/issues/241
