### ISSUE TITLE
升级Version 3.11.1，添加站点显示timeout超时问题

### ISSUE THREAD

**Issue by zhoupeng0721** [chaitin/SafeLine#435]

**Comment by 5icorgi** [comment]
一样的问题，添加，编辑，删除均提示timeout

**Comment by zhoupeng0721** [comment]
更新之后直接挂了，今日请求为0，无任何数据了

**Comment by DeronW** [comment]
@zhoupeng0721  有更详细的错误日志吗？ 可以加雷池官网微信群（在官网底部有），描述一下消息错误

**Comment by onelooker** [comment]
HTTP/2 500 Internal Server Error
Date: Wed, 15 Nov 2023 08:16:41 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 52
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
X-Xss-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Ssl-Client-Verify: NONE

{"data":null,"err":"internal-error","msg":"timeout"}
