### ISSUE TITLE
[Bug] 重启主机后访问https站点会无限重定向

### ISSUE THREAD

**Issue by AAAAAAAAAdai** [chaitin/SafeLine#438]
### 问题描述

在重启服务器后，访问https站点会无限重定向，然后在 「通用配置」 -「其他」-「站点通用配置」重新设置一下才正常。

### 版本号

3.11.1

### 复现方法

1.重启服务器
2.访问站点

### 期望的结果

修复问题

**Comment by DeronW** [comment]
有更详细的错误信息吗？ 这种一句话描述很难定位问题

**Comment by AAAAAAAAAdai** [comment]
> 有更详细的错误信息吗？ 这种一句话描述很难定位问题

再次测试了一下，两个https站点，一个站点的上游端口是80，一个站点的上游端口是443，上游443的重启服务器后正常，上游80的站点就会重定向的次数过多，需要在「雷池」-「通用配置」 -「其他」-「站点通用配置」-「使用 HTTP/2」开关一下设置恢复正常。

(猜测:有点像之前套了CDN后http无限跳https)

**Comment by cfwl1111** [comment]
这问题3.10.1也出现过，没找到原因，但只要重启服务器基本会复现，重启雷池服务恢复正常

**Comment by clqs803** [comment]
我也遇到过类似问题，不过是掉证书。 重启程序之后必然会有几个站点的证书失效，需要进入到站点再次手动选择一下证书才行。因为这个已经弃用雷池了，差点被搞死。。

**Comment by 5icorgi** [comment]
碰到过类似的问题，就是升级或者重启后配置失效，需要重新保存一下相关配置然后才生效，之前勾选了强制https，但是访问http不跳转https，去掉勾选，再重新勾上才能生效

**Comment by 404-502** [comment]
升级3.12.1版本后我也遇到了这个问题，我说去掉勾选HTTP/2再重新勾上就恢复正常，进wordpress后台一直在反复重定向进不去，一开始还以为网站炸了，搞半天原来是雷池出问题了

**Comment by 404-502** [comment]
升级3.12.1版本后我也遇到了这个问题，进wordpress后台一直在反复重定向进不去，一开始还以为网站炸了，搞半天原来是雷池出问题了，我是去掉勾选HTTP/2再重新勾上就恢复正常的

**Comment by dundunHa** [comment]
尝试升级到 3.12.2 解决这个问题

**Comment by AAAAAAAAAdai** [comment]
> 尝试升级到 3.12.2 解决这个问题

昨晚上升级后，还是会有这种问题。解决办法是，所有上游都走443了。

**Comment by AAAAAAAAAdai** [comment]
更新后问题已经解决。
