### ISSUE TITLE
[建议] 请问能否增加对于lua脚本的支持

### ISSUE THREAD

**Issue by Exi1Sh0w** [chaitin/SafeLine#439]
### 背景与遇到的问题

遇到安全事件，可能需要临时写一条针对性的策略用于过度

**Comment by DeronW** [comment]
现在的 黑白名单、限频、防御级别，这些规则还不能满足需求吗？  

lua 功能过于危险，用 “配置规则” 代替 “程序逻辑” 可以很大程度上防止 “逻辑失误”，我本来是这个意思，但是代码的逻辑表达却成了另一个意思，并且这种错误的逻辑影响无法估计，而且很难排查。

如果临时性策略的需求很强，可以在 waf 前面添加一个支持 lua 的负载均衡，这种防护服务是可以互相嵌套的

**Comment by Lorna0** [comment]
其实已经有 issue 了，就是大家兴趣似乎一般，没有啥讨论：
* https://github.com/chaitin/SafeLine/issues/129

主要是难配置、难 debug，能实际用起来的人很少，我们也没办法保证给每个用户足够的技术支持。其实语义分析引擎、黑名单补充已经能很大程度上解决安全事件了，社区版还是希望门槛低一点，尽量界面配置或不配置。
