### ISSUE TITLE
[建议] 访问日志文档过大，操作耗时长

### ISSUE THREAD

**Issue by ceciliaaii** [chaitin/SafeLine#442]
### 背景与遇到的问题

safeline打开访问记录所有访问雷池的请求后，单个日志文档过大，打开筛选之类操作需要损耗过长

### 建议的解决方案

是否可以提供日志切割功能，如按时间切割，减少单个日志文件的大小，提高效率

**Comment by Lorna0** [comment]
官网记访问日志的指南，其实就是用的 nginx 的 access_log，有需求的话直接根据 access_log 的参数改配置就可以。

没具体做更多功能是因为在 waf 上记录访问日志本身还有争议，可参考：

* https://github.com/chaitin/SafeLine/issues/145
