### ISSUE TITLE
[Bug] 攻击事件中的请求报文并没有展示所有请求信息

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#443]
### 问题描述

攻击事件中的请求报文里面的请求头信息只有几个基础常见的，并没有包含所有的请求头

### 版本号

3.11.1

### 复现方法

攻击事件-原始日志，点击详情查看

### 期望的结果

希望可以记录所有的请求头信息

**Comment by Lorna0** [comment]
没有复现：
![image](https://github.com/chaitin/SafeLine/assets/56920727/69d26d69-e409-415a-95c1-b17c69f4cb87)

师傅能抓包确认一下么

**Comment by jssolo** [comment]
哈哈，提这个的时候没有研究全面，既然是攻击就可以伪装请求头
