### ISSUE TITLE
[建议] 希望长亭能增加通知功能

### ISSUE THREAD

**Issue by huhaku** [chaitin/SafeLine#444]
### 背景与遇到的问题

因为错误配置了一个策略,导致正常的请求被当成了攻击,直到有用户反馈上来才发现,已经拦截了很长一段时间了

### 建议的解决方案

希望能像拉黑ip那样,当某个拦截策略或者攻击被触发到达一个阈值之后调用某个POST接口(内网用)或者是发送邮件通知到运维,让运维能及时介入响应

**Comment by Lorna0** [comment]
duplicate，可以到之前 issue 中讨论，方便集中意见：
* https://github.com/chaitin/SafeLine/issues/109
* https://github.com/chaitin/SafeLine/issues/138

不过看背景问题，可能比较接近这些：

* https://github.com/chaitin/SafeLine/issues/262
* https://github.com/chaitin/SafeLine/issues/142
