### ISSUE TITLE
我就写完博客点击发布新文章他就拦截了[Bug] 

### ISSUE THREAD

**Issue by 1764364648** [chaitin/SafeLine#445]
### 问题描述

我刚刚写完博客点击发布文章他就拦截了服了 
![55071b4088880b28e2c333a6fed07669](https://github.com/chaitin/SafeLine/assets/123971622/fcd9c169-91a8-445b-968b-f142d5d94ab3)
![a9e6c8c9287a6c5fca44f0483d55e291](https://github.com/chaitin/SafeLine/assets/123971622/ce97454e-aef7-42b0-b5f2-979ea130bcb0)
![7e54fd44399efc3eb5a09172d535cfb7](https://github.com/chaitin/SafeLine/assets/123971622/04b7766e-df92-42e2-ba52-d50ed7658bd9)

### 版本号

 3.12.1

### 复现方法

我刚刚写完博客点击发布文章他就拦截

### 期望的结果

我希望能赶紧修复

**Comment by Lorna0** [comment]
这个请求中确实有代码执行内容，这种富文本提交的请求很难分辨是正常还是攻击，市面上也没有很好的解决办法。

可以给这个提交请求的路径加白名单。如果只有管理员需要提交，可以给管理员 IP 加白。

**Comment by gotlab** [comment]
先给自己IP、UA加白名单

**Comment by Lorna0** [comment]
好像没问题了，先关闭，有其他信息可以补充一下哦
