### ISSUE TITLE
[Bug] 多家CDN造成WAF误封问题

### ISSUE THREAD

**Issue by lywlbk** [chaitin/SafeLine#447]
### 问题描述

您好，软件目前没有多个Header头的功能，我的场景是多多个厂商的CDN，CDN1用的Header是client-ip，CDN2用的Header是X-Forwarded-For，两家cdn没有对家的Header，但是WAF目前只能配置一个Header就会造成很多ip的误拦截。
![1b4d9889aa65ca0fe3cd13207300405](https://github.com/chaitin/SafeLine/assets/46261377/09e0c403-d5ff-46c8-b11c-b44cffa57f06)

### 版本号

3.12.1

### 复现方法

多家CDN只能加一家的Header

### 期望的结果

增加多个Header功能

**Comment by Lorna0** [comment]
有一个重复 issue，可以集中在一起讨论：
* https://github.com/chaitin/SafeLine/issues/436
