### ISSUE TITLE
[Bug] 登录页动态密码一个按键输入了两次,无法登陆

### ISSUE THREAD

**Issue by huhaku** [chaitin/SafeLine#449]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/3396694/5fb40020-ad20-4ecd-ac22-1e5a9624cb39)
如图所示我按了一个1,就直接输入了两次,然后之前因为密码不是自动提交的,我还有机会输入一位然后往前删除一位,最后再点登录,现在导致我永远都输不对最后一位
![image](https://github.com/chaitin/SafeLine/assets/3396694/bd0adc38-3cb5-431b-ac46-adeaf8f63c97)
控制台没打印什么特别的内容,所有扩展停用了没用

### 版本号

[3.12.2] - 2023-11-17

### 复现方法

测试了几款浏览器,只有chrome核心的会这样,包括edge,firefox106.0.2就不会
出现问题的chrome版本119.0.6045.160（正式版本）（64 位）,地址是内网地址,有外网连接

### 期望的结果

密码没必要搞自动提交,输错了不用清空掉全部内容

**Comment by DeronW** [comment]
![iShot_2023-11-20_17 34 40](https://github.com/chaitin/SafeLine/assets/780596/372c0e15-5362-4eaa-b0f4-482d8deae5a7)

我的 Chrome 更新到最新，还是 xxx.159，你的为什么到 160了？ 是 Chrome 正式版吗？ 因为我本地没复现错误，所以暂时不确定原因

**Comment by DeronW** [comment]
自动登录也是有用户反馈的

https://github.com/chaitin/SafeLine/issues/367

https://github.com/chaitin/SafeLine/issues/335

**Comment by huhaku** [comment]
![image](https://github.com/chaitin/SafeLine/assets/3396694/6a78690f-3f18-465f-9586-33898006a46f)
是稳定版的,感觉自动登录是挺鸡肋的,其实懒得从键盘移向鼠标的话将enter绑定提交按钮就好了

**Comment by huhaku** [comment]
> 自动登录也是有用户反馈的
> 
> #367
> 
> #335

其实七牛这二步验证页面提供了一个灵感,直接输完验证码+enter就行了,对方没用过的话根本不知道你密码是多少位的,更安全点,前端还没有那么复杂的交互逻辑
![image](https://github.com/chaitin/SafeLine/assets/3396694/36f84ce2-35d8-4a50-952d-a493b65d8f43)

**Comment by xqw8889** [comment]
这个我也遇到过 无法复现 也是在谷歌浏览器概率出现的 无需做什么他就会自己恢复 原因未知

**Comment by DeronW** [comment]
@xqw8889  自己就能恢复？

**Comment by lendy98** [comment]
> ![image](https://user-images.githubusercontent.com/3396694/284260046-6a78690f-3f18-465f-9586-33898006a46f.png) 是稳定版的,感觉自动登录是挺鸡肋的,其实懒得从键盘移向鼠标的话将enter绑定提交按钮就好了

同样是这个版本的chrome 版本 119.0.6045.160（正式版本） 也是Win10 电脑，我有一台就这样，另一台却很正常。确实很奇葩。 感觉不一定是这个版本的chrome的问题。

**Comment by cyril-cheng** [comment]
> 这个我也遇到过 无法复现 也是在谷歌浏览器概率出现的 无需做什么他就会自己恢复 原因未知

中文输入状态必现，小键盘输入必现。

**Comment by huhaku** [comment]
@DeronW 复现了，怀疑是控件的问题，开着中文输入法必出现
不光是你们，飞书的框也炸了，切换成英文状态就没影响
![image](https://github.com/chaitin/SafeLine/assets/3396694/3db186d4-e619-4593-b145-778e0e8ad484)

**Comment by huhaku** [comment]
本地试图复现了下可能的原因
当我开着输入法，按下1还没松手，你看当前输入框的焦点
![image](https://github.com/chaitin/SafeLine/assets/3396694/41569472-890b-4cc0-9960-2eca950b38fe)
有点类似这样子，你还没按空格确定输入，这个字已经预填写在这了
![image](https://github.com/chaitin/SafeLine/assets/3396694/dd87b6e4-91d3-46e2-9cb6-d45beb9283a7)

单步调试了我好久。。。。。

解决思路：当输入框有值和按键释放两个事件同时成立才进入是否要判断移动输入光标到下一个输入框的处理逻辑

**Comment by huhaku** [comment]
> @huhaku 找了 mac 和 windows 的原生中文输入法，没能复现出来。猜测是动态密码输入框不适配部分 操作系统 & 输入法 的文本输入逻辑。比方说输入框监听了键盘按下，结果按键释放完操作系统又强制输入一个字符，之类。
> 
> 说实话不是很好解决，考虑还有自动登录的需求，准备改成 “6 位数字输入完后自动提交，但失败时不清空已输入内容”

这样也可以,允许在输入错误自动登录失败的时候再次修改然后手动点击登录就好
