### ISSUE TITLE
[建议] 建议增加一键屏蔽国外ip和额外排除指定国家ip的功能

### ISSUE THREAD

**Issue by Takumikama** [chaitin/SafeLine#455]
### 建议的解决方案

大佬们，建议增加一键屏蔽国外ip和额外排除指定国家ip的功能

**Comment by upbeat-backbone-bose** [comment]
需要这个功能，本身业务不涉及跨境情况的是可以一杆子把外部来源屏蔽掉，降低不必要的风险，以及资源消耗

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/88
