### ISSUE TITLE
[建议] 通用配置-IP组内增加针对IP地址的排序功能

### ISSUE THREAD

**Issue by upbeat-backbone-bose** [chaitin/SafeLine#457]
### 背景与遇到的问题

当维护IP组内数据多了之后，存在误杀或者漏放的IP无法快速找到目标，观感上也不美观
![image](https://github.com/chaitin/SafeLine/assets/438092/e96508cd-3393-4b24-b46e-dbb52e8c2f8d)

### 建议的解决方案

手动新增、删除IP组内信息时，自动针对IP/CIDR做个排序
![image](https://github.com/chaitin/SafeLine/assets/438092/4bb2ab30-4168-4c20-8b73-67561fd01ac4)

**Comment by upbeat-backbone-bose** [comment]
![image](https://github.com/chaitin/SafeLine/assets/438092/62517cab-68dc-4e57-8554-9f27d1e064cf)

**Comment by Lorna0** [comment]
IP 组目前是有行间注释的功能的，自动排序会打乱注释，并不太推荐：
![image](https://github.com/chaitin/SafeLine/assets/56920727/ed8d49fe-61b9-4e35-be14-bfb5102147d7)

有整理需要的话，更建议手动重新排序一下。

**Comment by upbeat-backbone-bose** [comment]
> IP 组目前是有行间注释的功能的，自动排序会打乱注释，并不太推荐： ![image](https://user-images.githubusercontent.com/56920727/284807587-ed8d49fe-61b9-4e35-be14-bfb5102147d7.png)
> 
> 有整理需要的话，更建议手动重新排序一下。

是不是可以考试把IP/CIDR与注释定义一个标准格式，这样就能同时解决排序与注释的需求，类似

`192.168.1.1//这是一个注释`
`192.168.1.2^这是一个注释`
`192.168.1.3 - //这是一个注释`

**Comment by DeronW** [comment]
@upbeat-backbone-bose  如果在页面上添加一个  “排序” 按钮，是不是可以解决这个问题？

**Comment by upbeat-backbone-bose** [comment]
> @upbeat-backbone-bose 如果在页面上添加一个 “排序” 按钮，是不是可以解决这个问题？

感觉也不是不可以，这样可以按需要触发是否需要进行排序。不需要的也就无感了。
