### ISSUE TITLE
希望上游服务器支持添加多个地址 / 站点负载均衡

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#46]
咱这个waf本来就是基于nginx的，能否站点添加的时候后端服务器可以添加多个服务器地址？实现本身的站点负载均衡功能？

**Comment by zclaiqcc** [comment]
嗯收到，后面会加多个 upstream server 的支持

**Comment by zhuanmentiwen** [comment]
回复效率杠杠的！！！点赞！

**Comment by zhuanmentiwen** [comment]
> 嗯收到，后面会加多个 upstream server 的支持

如果能带上执行/目录 到后端服务器，就更牛了。。

**Comment by zclaiqcc** [comment]
没有理解「执行/目录 到后端服务器」，能具体说一下场景么？是说直接代理到某个目录下的静态资源文件？

**Comment by zhuanmentiwen** [comment]
> 没有理解「执行/目录 到后端服务器」，能具体说一下场景么？是说直接代理到某个目录下的静态资源文件？

具体场景：
站点www.xxx.com对应的是10.0.0.2服务器
网址www.xxx.com/houtai 对应的是10.0.0.3服务器

这种我们经常碰到。在nginx上很好实现，但因为waf只能以域名为单位统一到一个固定服务器上，而二级目录是需要到其他服务器上，是根据url后面的目录进行转发的。

**Comment by zclaiqcc** [comment]
OK 理解了，是说希望不只是配置域名+端口，还希望配置 urlpath（或者在 nginx 里面是 location），收到我们考虑一下，其他用户有类似需求的话也欢迎评论或者点个赞。

**Comment by jinhaozcp** [comment]
> OK 理解了，是说希望不只是配置域名+端口，还希望配置 urlpath（或者在 nginx 里面是 location），收到我们考虑一下，其他用户有类似需求的话也欢迎评论或者点个赞。

是的，这种需求类似API网关分流，如果能带上那是最好了！还是强烈希望加入上游服务器功能，传统部署方案是WAF-->SLB-->ECS,但是如果没有资源放WAF，可能会存在雷池和ECS放一起的场景，那么就变成SLB-->WAF-->ECS,这样需要雷池具备分流功能。谢谢！

**Comment by luweijun1992** [comment]
什么时候支持多上游服务器，且支持上游服务器的状态检测；负载方式；

**Comment by ahzx1106205262** [comment]
什么时候上线，负载均衡坐等

**Comment by pangziyimei** [comment]
同等此功能上线！！！！

**Comment by yanest** [comment]
加油

**Comment by D0n9** [comment]
这个需求应该是最高呼声了吧

**Comment by upbeat-backbone-bose** [comment]
同等支持配置urlpath功能，还是存在比较多因为各种原因共用域名的情况

**Comment by cos800** [comment]
强烈附议！这功能得有，不然还得另外部署一个nginx太麻烦了

**Comment by RyeZJCWhiskey** [comment]
强烈附议！

**Comment by JimmyLiang-lzm** [comment]
附议附议，这个上游服务器真的太需要了！否则多部署个Nginx太不优雅了哈哈哈😁

**Comment by jklZy1** [comment]
强烈附议！

**Comment by DeronW** [comment]
@zhuanmentiwen  4.3 开始以后，雷池专业版已经支持上游负载均衡了

**Comment by baiachen** [comment]
> @zhuanmentiwen 4.3 开始以后，雷池专业版已经支持上游负载均衡了

社区版可以上

**Comment by mike-hor** [comment]
所以现在是支持了 还是没支持？ 我看是需要升级专业版才支持
