### ISSUE TITLE
[建议] 通用配置-源IP获取方式建议增加备用header

### ISSUE THREAD

**Issue by jssolo** [chaitin/SafeLine#461]
### 背景与遇到的问题

在使用多个CDN时，不同的CDN传递的源站IP的header会有不同，很难统一固定的header

### 建议的解决方案

在获取源站IP的时候，建议加一个或者多个备用的header请求头的配置，这样在第一个获取不到源站IP的时候，可以在设置的第二个header请求头里获取
![微信截图_20231122212350](https://github.com/chaitin/SafeLine/assets/40593549/de14e1d2-ef78-4781-b916-9fb7654b963f)

**Comment by Lorna0** [comment]
集中到一起讨论吧：
https://github.com/chaitin/SafeLine/issues/436
