### ISSUE TITLE
动态ip解析域名后会缓存之前的ip解析，ip变化后不会自动更新

### ISSUE THREAD

**Issue by homestoo** [chaitin/SafeLine#466]
### 背景与遇到的问题

Nginx 会在启动时解析上游服务器的域名，并缓存解析结果。如果上游服务器的 IP 地址改变了，Nginx 不会自动更新，在使用动态的上游服务需要实现 Nginx 的动态域名解析。
目前上游域名如果是动态的话会缓存解析之前的IP导致网站无法访问，ip变化后，Nginx不会自动更新再次解析域名指向的ip

### 建议的解决方案

建议增加个域名请求后，检查上游域名当前解析的ip并更新缓存解析。

**Comment by DeronW** [comment]
nginx 文档  https://nginx.org/en/docs/http/ngx_http_core_module.html#resolver

**Comment by garrettdo** [comment]
加上了吗？

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/384

**Comment by homestoo** [comment]
> duplicate：
> 
> * [[建议] DDNS域名回源场景优化 / 动态解析 upstream 的域名 #384](https://github.com/chaitin/SafeLine/issues/384)

感谢
resolver 114.114.114.114 valid=24h;
resolver 8.8.8.8 valid=12h;
resolver_timeout 5s;

可以
