### ISSUE TITLE
[Bug] app/main.go:29 env is required MGT_API

### ISSUE THREAD

**Issue by f0re1gnKey** [chaitin/SafeLine#468]
### 问题描述

最新的docker安装，启动后safeline-tengine报错
app/main.go:29 env is required MGT_API

### 版本号

3.13.2

### 复现方法

一键脚本安装

### 期望的结果

正常运行

**Comment by 21307369** [comment]
我的 chaitin/safeline-tengine:3.13.1  3.13.2 会报这个错误
2023/11/27 00:38:27 [ERROR] app/main.go:29 env is required MGT_API
2023/11/27 00:38:32 [ERROR] client/secret.go:110 asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
2023/11/27 00:38:32 [ERROR] client/secret.go:40 exchange secret error asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2

**Comment by f0re1gnKey** [comment]
> 把 MGT_ADDR 更改为 MGT_API 参数

感谢你的回答，已经按照要求修改了MGT_API环境变量，现在的变量是`- MGT_API=${SUBNET_PREFIX}.4:9002`
不过还是无法启动，报错为
```
[ERROR] client/secret.go:104 parse "10.11.132.4:9002?kind=secret": first path segment in URL cannot contain colon
[ERROR] client/secret.go:40 exchange secret error parse "10.11.132.4:9002?kind=secret": first path segment in URL cannot contain colon
```
于是我再次修改MGT_API为`MGT_API=http://${SUBNET_PREFIX}.4:9002/`
依然无法启动，报错为
```
[ERROR] client/secret.go:104 Post "http://10.11.132.4:9002/?kind=secret": dial tcp 10.11.132.4:9002: connect: connection refused
[ERROR] client/secret.go:40 exchange secret error Post "http://10.11.132.4:9002/?kind=secret": dial tcp 10.11.132.4:9002: connect: connection refused
```
查找容器，发现是`10.11.132.4`是`safeline-mgt-api`容器，日志为
`INFO success: webserver entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)`
通过进入`safeline-mgt-api`容器，发现其监听1080, 1443, 9001端口，其中1080, 1443为控制台界面，猜测是9001端口，使用9001代替9002，依然无法启动，报错为
```
[ERROR] client/secret.go:110 asn1: structure error: tags don't match (16 vs {class:0 tag:20 length:48 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
[ERROR] client/secret.go:40 exchange secret error asn1: structure error: tags don't match (16 vs {class:0 tag:20 length:48 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
```
请问我还需要修改什么才能正常启动？

**Comment by qif580231** [comment]
同样问题，而且用的谷歌验证登录不上。

**Comment by DeronW** [comment]
> 同样问题，而且用的谷歌验证登录不上。

服务没有启动，所以登录也用不了

**Comment by DeronW** [comment]
> 我的 chaitin/safeline-tengine:3.13.1 3.13.2 会报这个错误 2023/11/27 00:38:27 [ERROR] app/main.go:29 env is required MGT_API 2023/11/27 00:38:32 [ERROR] client/secret.go:110 asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue: tag: stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2 2023/11/27 00:38:32 [ERROR] client/secret.go:40 exchange secret error asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue: tag: stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2

这个错误日志跟这个 issue 无关，这是服务没有正常启动，建议重新安装

**Comment by DeronW** [comment]
> > 把 MGT_ADDR 更改为 MGT_API 参数
> 
> 感谢你的回答，已经按照要求修改了MGT_API环境变量，现在的变量是`- MGT_API=${SUBNET_PREFIX}.4:9002` 不过还是无法启动，报错为
> 
> ```
> [ERROR] client/secret.go:104 parse "10.11.132.4:9002?kind=secret": first path segment in URL cannot contain colon
> [ERROR] client/secret.go:40 exchange secret error parse "10.11.132.4:9002?kind=secret": first path segment in URL cannot contain colon
> ```
> 
> 于是我再次修改MGT_API为`MGT_API=http://${SUBNET_PREFIX}.4:9002/` 依然无法启动，报错为
> 
> ```
> [ERROR] client/secret.go:104 Post "http://10.11.132.4:9002/?kind=secret": dial tcp 10.11.132.4:9002: connect: connection refused
> [ERROR] client/secret.go:40 exchange secret error Post "http://10.11.132.4:9002/?kind=secret": dial tcp 10.11.132.4:9002: connect: connection refused
> ```
> 
> 查找容器，发现是`10.11.132.4`是`safeline-mgt-api`容器，日志为 `INFO success: webserver entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)` 通过进入`safeline-mgt-api`容器，发现其监听1080, 1443, 9001端口，其中1080, 1443为控制台界面，猜测是9001端口，使用9001代替9002，依然无法启动，报错为
> 
> ```
> [ERROR] client/secret.go:110 asn1: structure error: tags don't match (16 vs {class:0 tag:20 length:48 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
> [ERROR] client/secret.go:40 exchange secret error asn1: structure error: tags don't match (16 vs {class:0 tag:20 length:48 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
> ```
> 
> 请问我还需要修改什么才能正常启动？

不需要修改 compose.yaml 的配置，配置本身是经过测试的，这个服务没有启动不是 配置的问题，需要再检查其他问题，可以在企业微信群里私聊一下，可能需要远程协助

**Comment by HADB** [comment]
一样的问题，全新安装试过多次都报错：

2024/06/12 17:21:33 [ERROR] client/secret.go:110 asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
2024/06/12 17:21:33 [ERROR] client/secret.go:40 exchange secret error asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
