### ISSUE TITLE
[建议] 建议新增一个功能，检测到同一个IP多次攻击后，自动丢到用户指定的黑名单。

### ISSUE THREAD

**Issue by Temp996869365** [chaitin/SafeLine#470]
### 背景与遇到的问题

常常遇到一个问题，就是半夜遭受到来自同一源IP多次多种攻击方法的攻击，但雷池仅仅是阻断 ，不会自动将攻击IP加入黑名单，这是一个大隐患，因为雷池不可能百分百阻断所有攻击方法，为什么不一劳永逸将其丢到用户指定的黑名单呢？如果是怕误封，可以设置允许手动移除啊。

### 建议的解决方案

建立新增功能，可以设置--当检测到同一源IP多次攻击后，自动将此IP丢进指定的黑名单，老化时间可以有多个选项，比如小时计、永久等，可以移除黑名单。

**Comment by Lorna0** [comment]
看起来和这个是一个意思，集中讨论和跟进吧：
* https://github.com/chaitin/SafeLine/issues/428
