### ISSUE TITLE
[建议] 支持配置 websocket 的开启和关闭

### ISSUE THREAD

**Issue by DeronW** [chaitin/SafeLine#473]
### 建议的解决方案

reverse proxy enable websocket:  https://nginx.org/en/docs/http/websocket.html

**Comment by redzl** [comment]
这个帮助文件拉到底部，有具体的方式。
https://waf-ce.chaitin.cn/docs/faq/other

**Comment by Lorna0** [comment]
目前已经默认支持了，只是不允许关闭
