### ISSUE TITLE
nginx 监听 ipv6 端口，报错  

### ISSUE THREAD

**Issue by DeronW** [chaitin/SafeLine#474]
### 反馈内容

监听 ipv6 失败

`[nginx] starting...
nginx: [emerg] invalid IPv6 address in resolver "[fe80::46d9:e7ff:fe95:e3db%br0]`

![d44588c4d7a82c444a074504e061354b](https://github.com/chaitin/SafeLine/assets/780596/bd29b5f7-5bed-4cc3-a4a5-6608f046dcea)

相关问题：
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1015
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/392

**Comment by xbingW** [comment]
暂无解决方案
