### ISSUE TITLE
[Bug] 2C1G配置的 Oracle云服务器 在部署雷池后卡死

### ISSUE THREAD

**Issue by Moon-du** [chaitin/SafeLine#475]
### 问题描述

[Bug] 2C1G配置的 Oracle云服务器 在部署雷池后如果不添加证书或者网站可以正常访问后台，一旦添加防护站点或者申请证书，后台就卡死超时，看负载CPU占用很低，内存占用在 700M左右。
![WechatIMG6289](https://github.com/chaitin/SafeLine/assets/69743019/1492cdcf-0e95-4772-97b7-337aba1b24a4)
![WechatIMG6291](https://github.com/chaitin/SafeLine/assets/69743019/4483e667-cbf6-49f9-a224-66354ecd61ec)

### 版本号

3.13.2

### 复现方法

ubuntu22.04系统 什么都不安装只安装雷池，添加防护站点或者申请证书就卡死了

### 期望的结果

2C1G 的oracle服务器可以正常使用

**Comment by yrluke** [comment]
麻烦提供一下logs/management/webserver.log的内容

**Comment by DeronW** [comment]
内存不足，导致容器起不来，这个问题看着是 postgres 没启动，导致所有服务无法使用。 在 3.14 版本以后，去掉了 redis 容器，可以重新尝试一下。 配置太低，即时勉强运行，也起不到防护作用，流量大的时候也是很耗资源的
