### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chettestwef** [chaitin/SafeLine#476]
### 问题描述

雷池的自动升级脚本出现故障，无法升级：`bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/upgrade.sh)"`
![image](https://github.com/chaitin/SafeLine/assets/99162086/2e923fb2-eec8-4201-89a2-4add15221ef7)
![image](https://github.com/chaitin/SafeLine/assets/99162086/d11c8127-0643-45a2-9efb-4da8c0856d1e)
![image](https://github.com/chaitin/SafeLine/assets/99162086/eaaa1ac9-d9f6-4211-9f63-2c2ff894296b)

### 版本号

null

### 复现方法

null

### 期望的结果

修复

**Comment by yrluke** [comment]
可以试试使用docker 国内源，或者使用离线安装试试
