### ISSUE TITLE
[建议] 1panel 兼容问题

### ISSUE THREAD

**Issue by 21307369** [chaitin/SafeLine#477]
### 背景与遇到的问题

希望出给兼容1panel 的docker composer

**Comment by okxlin** [comment]
https://github.com/okxlin/appstore/tree/localApps/apps/safeline

**Comment by 21307369** [comment]
> https://github.com/okxlin/appstore/tree/localApps/apps/safeline

latest 容器只有一个启动

**Comment by gotlab** [comment]
> > 
> 
> latest 和 带版本号的 容器只有一个启动 ![image](https://private-user-images.githubusercontent.com/47931342/287322396-6ec63565-3cab-4095-b739-ed131d968df0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDgwOTIsIm5iZiI6MTcwMTQ0Nzc5MiwicGF0aCI6Ii80NzkzMTM0Mi8yODczMjIzOTYtNmVjNjM1NjUtM2NhYi00MDk1LWI3MzktZWQxMzFkOTY4ZGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2MjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNjkwODc0YmEwNzYxOGVjZWIzY2JjYzkxOGQyZGZiNmFhODQyYWRmNTUwMjRkZjBlMzhhMTlhYjMyNjdlZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q2oiWuBo2e8tkVXGE8IT5Ght21OnVnceVHEHDl7asLs) 手动启动 ![image](https://private-user-images.githubusercontent.com/47931342/287322712-da3536c2-4ab4-45df-b687-c8d930cbb3ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDgwOTIsIm5iZiI6MTcwMTQ0Nzc5MiwicGF0aCI6Ii80NzkzMTM0Mi8yODczMjI3MTItZGEzNTM2YzItNGFiNC00NWRmLWI2ODctYzhkOTMwY2JiM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2MjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOGNmYzg0YzQ4OTQwYzMzODBiMzgzODFjNWRjMDJkYjc4MzUzMTQxNmZkMzg4Y2VmOGY2ZWM3NDc2NzE1MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dg3ZFtXptrERECE0vpQ-rW3R6Thp1a5sm3YycAlCCTk)

重启docker服务后重建，或者用newnet latest那个

**Comment by 21307369** [comment]
502错误. 环境是新装的   系统Anolis 8  AHCK
![image](https://github.com/chaitin/SafeLine/assets/47931342/8b5dbb53-b2a9-4190-b272-361640d5609a)

**Comment by 21307369** [comment]
level=error msg="FVM Complie Error :rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup safeline-fvm-manager on 127.0.0.11:53: no such host\"" file=grpc_helper.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*GRPCHelper).Compile" line=79 logger=fvm

**Comment by okxlin** [comment]
> 502错误. 环境是新装的 系统Anolis 8 AHCK ![image](https://private-user-images.githubusercontent.com/47931342/287325266-e27cd688-e844-4c73-9328-55f451a300f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDg0NjMsIm5iZiI6MTcwMTQ0ODE2MywicGF0aCI6Ii80NzkzMTM0Mi8yODczMjUyNjYtZTI3Y2Q2ODgtZTg0NC00YzczLTkzMjgtNTVmNDUxYTMwMGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2MjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OTYyYWE1NjBkNGViOWQ4ZWY3MzNmYjk1Mzk1ODcyZjMwMTViOTA1ZmNmNDFjODM5MmU1NjczNjZiYzEyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vQSEekF2dvxY7FIQtNRxZvvoHy0eWcJHeoYN-WF0TU8)

看看容器状态是否正常？

debian一切正常的

**Comment by 21307369** [comment]
centos ,aliyunos ,试试吧

**Comment by okxlin** [comment]
> centos ,aliyunos ,试试吧

docker就是通用的呀，原则上对系统依赖不大

看看容器状态是否正常

**Comment by 21307369** [comment]
![image](https://github.com/chaitin/SafeLine/assets/47931342/370e847b-8665-4ffd-96d4-c3ab1732046c)

**Comment by 21307369** [comment]
webserver.log 
time="2023/12/02 00:41:46" level=info msg=Staring... file=main.go func=main.main line=220 logger=main
time="2023/12/02 00:41:46" level=error msg="FVM Complie Error :rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup safeline-fvm-manager on 127.0.0.11:53: no such host\"" file=grpc_helper.go func="/patronus/safeline-2/management/webserver/pkg/fvm.(*GRPCHelper).Compile" line=79 logger=fvm
time="2023/12/02 00:41:46" level=fatal msg="Failed to compile and save fsl rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup safeline-fvm-manager on 127.0.0.11:53: no such host\"" file=generator.go func=/patronus/safeline-2/management/webserver/pkg/fvm.InitFVMBytecode.func1 line=63 logger=fvm
[proc_wrapper 2023-12-02 00:41:45.754924] Running '/app/webserver/webserver', backoff file name: /tmp/c2f32b173bca8a1fab48a53a0591faba.backoff
[proc_wrapper 2023-12-02 00:41:46.336467] Command '/app/webserver/webserver' exited with status 256, sleep 5s

**Comment by 21307369** [comment]
是的 看上去是相同的问题 .

**Comment by okxlin** [comment]
那降低一下到旧版本看看，这个问题很奇怪，好像有个1panel群友好像也是这个问题，主要我用debian都正常

在`/opt/1panel/resource/apps/local/safeline`复制粘贴一个版本文件夹，然后重命名，然后粘贴这个旧历史记录里的data.yml和docker-compose.yml

https://github.com/okxlin/appstore/tree/ef9f657ba386b81b56f58c037c8af863b40322bd/apps/safeline

**Comment by okxlin** [comment]
> 是的 看上去是相同的问题 . transport: Error while dialing: dial tcp: lookup safeline-fvm-manager on 127.0.0.11:53: no such host

找不到特定容器的原因，也可以，试试新建雷池时容器名去除local

原则上用的hostname不应该找不到特定容器的……改改容器名死马当活马医
![image](https://github.com/chaitin/SafeLine/assets/61420215/65bf0507-9ef8-45b2-9f80-3efcb0617e54)

**Comment by 21307369** [comment]
安装的时候指定容器名字,问题得到解决. 真奇葩

**Comment by okxlin** [comment]
那就是找不到特定容器的原因了……

可能没找主机名而是找了容器名作为默认连接吧……挠头
