### ISSUE TITLE
[Bug] 配置黑名单后无法实现拦截

### ISSUE THREAD

**Issue by redzl** [chaitin/SafeLine#478]
### 问题描述

我在黑名单处参考雷池的demo，配置了 路径-> 完全相等 -> /wp-login.php，这样的设置禁止直接请求WordPress后台登录界面，结果发现这个页面还是可以正常访问。但是在登录界面点登录按钮，变为POST表单提交后，却可以拦截，是不是意味着只拦截了POST没拦截GET？

### 版本号

3.13.2

### 复现方法

1. 黑名单配置：路径-> 完全相等 -> /wp-login.php
2. 直接GET方式请求 /wp-login.php，未拦截

### 期望的结果

直接拦截GET访问

**Comment by Lorna0** [comment]
目前的 “路径” 是包含 query 参数的部分的：
![image](https://github.com/chaitin/SafeLine/assets/56920727/603db0c9-a0f8-4383-9dcf-cce414611be5)

可以检查一下请求里是不是有 query 参数。而且确实只有 get 请求会有 query 参数，post 请求不会有。

你可以直接用 “前缀关键字” 来匹配：
![image](https://github.com/chaitin/SafeLine/assets/56920727/93334687-55af-495a-a154-ecb28bac2c2c)

**Comment by yrluke** [comment]
这个时间很久了，由于没有进一步提供所需信息，issue暂时关闭，有需要再打开
