### ISSUE TITLE
[Bug] 已正确配置防护站点，后续编辑站点更改域名时出现环路现象

### ISSUE THREAD

**Issue by ZionLoh90** [chaitin/SafeLine#479]
### 问题描述

1、原来：已正确配置防护站点，测试正常，稳定运行两个星期。
2、现在：后因业务需要将原先防护站点由适配所有域名（*）更改为内部自定义域名，在更改域名保存后，防护站点页面无法访问，WAF后台访问量瞬间暴涨，部署WAF机器CPU飙升。
3、分析：
      3.1、重启docker无效
      3.2、重启网络服务/重启WAF机器后解决
4、可能原因：更改防护站点适配域名后，域名解析未生效，导致环路，重启网络服务/重启设备后DNS重新解析生效。

### 版本号

3.13.2

### 复现方法

1、配置防护站点，不配置域名
2、测试防护站点正常
3、新建内部DNS到防护站点IP
4、修改防护站点适配域名为新建DNS域名

### 期望的结果

因部分小业务系统在用，没时间截图，做了快速恢复，希望大神帮忙测试下是否真有此类问题

**Comment by ZionLoh90** [comment]
该现象复现时类似环路现象，WAF统计页面访问量瞬间飙升几十倍，网页访问返回 400 Request Header Or Cookie Too Large

**Comment by xbingW** [comment]
配置问题不予解决
