### ISSUE TITLE
[建议] 在使用APISIX chaitin-waf插件实现检测且有自定义防护规则时，不再需要配置站点

### ISSUE THREAD

**Issue by zsmlinux** [chaitin/SafeLine#480]
### 背景与遇到的问题

在使用APISIX chaitin-waf插件实现检测且有自定义防护规则时，默认自定义防护规则是不生效的，需要配置站点。

在使用APISIX情况下，不希望再到waf管理后台重新设置站点。

**Comment by xbingW** [comment]
最新版支持不需要额外配置站点了
