### ISSUE TITLE
]我希望可以在数据统计可以添加上实时回源和实时网站流量不是只能看实时 QPS [建议]

### ISSUE THREAD

**Issue by 1764364648** [chaitin/SafeLine#481]
### 背景与遇到的问题

我希望能实时看到waf访问web服务器的延迟这样当访问网站慢的时候可以更方便的找到问题还有添加上实时网站流量我可以直接在waf里面看了我就没有必要去服务器的管理面板看了流量了

### 建议的解决方案

在数据统计哪里添加上实时回源和实时网站流量

**Comment by Lorna0** [comment]
可以具体说一下希望有什么统计数据么。

PS. 求标点符号。

**Comment by yrluke** [comment]
这个时间很久了，由于没有进一步提供所需信息，issue暂时关闭，有需要再打开

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
