### ISSUE TITLE
[建议] 建议能查看来访IP。。

### ISSUE THREAD

**Issue by Temp996869365** [chaitin/SafeLine#487]
### 背景与遇到的问题

现在看不到来访的独立IP地址有哪些。。

**Comment by huhaku** [comment]
这玩意又不是统计分析系统，waf不是干这活的

**Comment by Lorna0** [comment]
为什么需要在 waf 上看来访 IP 呢，能具体说说么？

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
