### ISSUE TITLE
[Bug] 从3.13开始雷池tengine就疯狂报错了，完全不能用

### ISSUE THREAD

**Issue by cyril-cheng** [chaitin/SafeLine#488]
### 问题描述

从更新3.13开始，雷池后台就完全不能用了，全新安装也不能用。
tengine疯狂报错，控制台里面全是502错误。一切设置都无法读取。控制台完全失控。
![image](https://github.com/chaitin/SafeLine/assets/49748357/2a5125b0-4b52-4f9b-a4ba-86445c71dc54)

![image](https://github.com/chaitin/SafeLine/assets/49748357/c674babc-70f1-40bd-a79a-c80cb2d1802b)

### 版本号

3.14.1

### 复现方法

全新安装直接报错

### 期望的结果

能正常。

**Comment by cyril-cheng** [comment]
mgt-api也在无限重启
![image](https://github.com/chaitin/SafeLine/assets/49748357/16fd6981-07fd-4d51-b4d7-5f8677323a43)

**Comment by Yogile** [comment]
我是遇到了 Web 登录时动态口令需要重新获取的问题，当时检查防护站点功能正常。
发现进行了版本更新，升级到 v3.14.1 ： [版本更新记录 | 雷池 WAF 社区版 (chaitin.cn)](https://waf-ce.chaitin.cn/docs/about/changelog)  。
升级过程中宿主LXC容器异常，导致 PVE 系统崩溃。
通过重启关机后，强行恢复备份，离线更新后：配置正常，访问正常。目前尚在观察中。
记录： [雷池 WAF（SafeLine）异常处理：Web需要绑定动态口令，系统异常崩溃 - Yogile - 博客园 (cnblogs.com)](https://www.cnblogs.com/Yogile/p/17871103.html) 。

**Comment by okxlin** [comment]
1panel的话，尝试安装时填写特定容器名前缀，

可能没找主机名而是找了容器名作为默认连接吧……挠头

![image](https://github.com/chaitin/SafeLine/assets/61420215/c7b6547f-c9b7-44cd-a3d0-282ecb27a253)

https://github.com/chaitin/SafeLine/issues/477

**Comment by cyril-cheng** [comment]
> 1panel的话，尝试安装时填写特定容器名前缀，
> 
> 可能没找主机名而是找了容器名作为默认连接吧……挠头
> 
> ![image](https://private-user-images.githubusercontent.com/61420215/287336980-c7b6547f-c9b7-44cd-a3d0-282ecb27a253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTI3MjcsIm5iZiI6MTcwMTQ1MjQyNywicGF0aCI6Ii82MTQyMDIxNS8yODczMzY5ODAtYzdiNjU0N2YtYzliNy00NGNkLWEzZDAtMjgyZWNiMjdhMjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE3NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNTNkNzdiMDdmZWI5NjQyZGUxOTJmZWFhZjJhMjAzNDdiYTBlZTM1MzE4OTdjMTZhN2M1MzFlNjIxOWUxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4LtxWpuoEs9WCLa59MePwB4WWTMCddQ-6e0N0co_pO4)
> 
> #477

我靠，还真是，设置了容器名就不报错了。
