### ISSUE TITLE
[Bug] rocky linux 用官网提供的脚本在线安装雷池后，safeline-mario无法启动 API 等全报错

### ISSUE THREAD

**Issue by fooyii** [chaitin/SafeLine#492]
### 问题描述

环境:rocky linux 8.9 ,centos 8 
根据官网文档操作后，safeline-mario无法启动 API 等全报错
bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/setup.sh)"

怀疑是版本未更新最新脚本：
执行升级脚本后问题解决
bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/upgrade.sh)"

### 版本号

3.14.1

### 复现方法

环境:rocky linux 8.9 ,centos 8 
直接执行bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/setup.sh)"

### 期望的结果

执行后所有服务正常启动

**Comment by yrluke** [comment]
能提供一下报错吗，目前猜不出来到底是因为什么

**Comment by yrluke** [comment]
看上去pg没拉起来
