### ISSUE TITLE
数据统计里面的数据不对[Bug] 

### ISSUE THREAD

**Issue by 1764364648** [chaitin/SafeLine#493]
### 问题描述

在凌晨是有攻击的可是在数据统计哪里他把这波攻击算成昨天的呢
![image](https://github.com/chaitin/SafeLine/assets/123971622/d0999ebc-ddb1-4da7-bc2c-f1c9f12ab0b9)
![image](https://github.com/chaitin/SafeLine/assets/123971622/5e1eeb24-3f5f-4311-957a-4a3ba1c525c3)
![image](https://github.com/chaitin/SafeLine/assets/123971622/96063f1b-61a8-4e61-8953-e763a752abd9)

### 版本号

3.14.1

### 复现方法

.

### 期望的结果

赶紧修复这个问题

**Comment by xbingW** [comment]
升级到最新版看看是否解决吧
