### ISSUE TITLE
[建议] 攻击事件列表显示优化-前端展示攻击 ip 的 ip 组信息

### ISSUE THREAD

**Issue by lnk2005** [chaitin/SafeLine#495]
### 背景与遇到的问题

概述：希望在攻击事件列表中标注这个 ip 属于哪个 ip 组

在目前的使用过程中发现攻击事件列表中 ip 并不能显示出这个 ip 在哪个 ip 组。当某一天积攒的日志过多的时候，将 ip 添加到 ip 组会很苦恼，不知道这个 ip 是否预期的在 ip 组中，人肉去 ip 组里查会更加苦恼。希望能在前端添加相关的显示信息来解决这个令人苦恼的事情……

列表中没有 ip 组信息
![image](https://github.com/chaitin/SafeLine/assets/43910502/9456772c-6b7c-42e7-adf3-a36b1d6a35f1)

添加 ip 组的时候也没有 ip 组信息
![image](https://github.com/chaitin/SafeLine/assets/43910502/f6872f67-c7ad-414b-b42c-090838fe83a9)

### 建议的解决方案

期待能在攻击事件列表中展示相关的 ip 组信息
（顺便问一句，有没有 management 的开源计划，或者搞个插件系统或者 plugin store 来 diy 一些小功能

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
