### ISSUE TITLE
[建议] 提升人机验证防护能力

### ISSUE THREAD

**Issue by gougui** [chaitin/SafeLine#497]
### 背景与遇到的问题

用这种方式貌似能绕过人机验证，希望增加防护，谢谢
            driver.get("https://blank.page/")
            wait.until(EC.visibility_of_element_located((By.ID, "sheet")))
            driver.execute_script(f"""
    document.getElementById('sheet').addEventListener('click', () => {{
        window.open('{url}', '_blank');
    }});
    """)
            driver.find_element(By.ID, "sheet").click()
            time.sleep(10)

            original_window = driver.current_window_handle
            for window_handle in driver.window_handles:
                if window_handle != original_window:
                    driver.close()
                    driver.switch_to.window(window_handle)
                    break

            wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "textarea.n-input__textarea-el")))

### 建议的解决方案

增加防护能力

**Comment by DeronW** [comment]
@gougui  目前使用的是什么版本的 雷池 waf ？

雷池 waf 的人机识别已经升级到了 2.0 版本，新版本中没有 “点击” 通过的功能，这段代码像是 1.0 版本的人机识别功能。但是即使在 1.0 版本里，也不是通过简单的 “点击” 就可以通过的。这段代码确定已经成功通过了人机识别吗？

**Comment by gougui** [comment]
> @gougui 目前使用的是什么版本的 雷池 waf ？
> 
> 雷池 waf 的人机识别已经升级到了 2.0 版本，新版本中没有 “点击” 通过的功能，这段代码像是 1.0 版本的人机识别功能。但是即使在 1.0 版本里，也不是通过简单的 “点击” 就可以通过的。这段代码确定已经成功通过了人机识别吗？

雷池版本 3.10.0
感觉就是它通过 https://blank.page/ 作为跳板来过人机验证，然后就能脚本访问waf内的网站内容了
