### ISSUE TITLE
[Bug] 部署或升级时会往 resolv.conf 中添加一个错误的IPv6地址

### ISSUE THREAD

**Issue by buzhichou** [chaitin/SafeLine#499]
### 问题描述

部署或升级时会往 resolv.conf 中添加一个错误的IPv6记录，导致服务无法正常启动，手动删除resolv.conf 中的配置后，升级后又会添加回去
错误日志： invalid IPv6 address in resolver "[fe80::1%enp3s0]"

### 版本号

3.14.1

### 复现方法

1.操作系统Debian
2.ipv4与ipv6双栈网络
3.存在多个虚拟网卡

### 期望的结果

不生成错误的ipv6配置或获取到正确的ipv6地址
国内ipv6都是以240开头的，电信为240e开头的（240e::/20）；移动为2409开头的（2409:8000::/20）；联通为2408开头的（2408:8000::/20）

**Comment by yrluke** [comment]
这个是nginx添加的，我们目前也找不到好办法解决这个问题

**Comment by ashuai** [comment]
nginx添加完，用sed fix一下？会不会有副作用就要多多测试了
