### ISSUE TITLE
检测日志-攻击IP字段识别有误

### ISSUE THREAD

**Issue by jinhaozcp** [chaitin/safeline#5]
![image](https://user-images.githubusercontent.com/32815759/231988930-e279637b-1041-4536-9f6c-11cf8d3b828b.png)
![image](https://user-images.githubusercontent.com/32815759/231989246-89b72f4e-1911-4fc4-b4ee-e87ab4f48356.png)
网络架构：
客户端-->七层SLB-->雷池WAF-->server
按照此架构，雷池获取到的攻击IP是七层SLB的转发客户端IP，而非真实客户端IP，需要获取http_x_forward_ip.

**Comment by zclaiqcc** [comment]
嗯，XFF 这部分还可能存在从倒数第几层获取的问题，可能需要加一个更灵活的配置项来实现。

**Comment by zclaiqcc** [comment]
v1.2.0 可以自定义获取源 IP 了，师傅可以更新试一下

**Comment by jinhaozcp** [comment]
![image](https://user-images.githubusercontent.com/32815759/235038950-e1c0bbe4-a51f-41a6-a37f-1527538ce642.png)
测试了，已经解决~！
