### ISSUE TITLE
[Bug] 非标端口SSL，开了维护模式的bug

### ISSUE THREAD

**Issue by H1447005189** [chaitin/SafeLine#500]
### 问题描述

维护模式下 维护页面 对非标端口HTTPS支持不完善

### 版本号

3.15.2

### 复现方法

![微信图片_20231207222952](https://github.com/chaitin/SafeLine/assets/111737191/66eb3c54-2174-44ce-8168-a51dc4b9d113)如果没有497 那么就会这样
<img width="784" alt="微信图片" src="https://github.com/chaitin/SafeLine/assets/111737191/6f926e6d-d1ff-4413-bcef-e63a04433630">

### 期望的结果

server块 可自定义

**Comment by yrluke** [comment]
看上去并不能复现师傅的这个配置文件，能具体说一下如何配置的吗，仅页面操作

**Comment by H1447005189** [comment]
1. 管理页面上 站点配置SSL 端口40404（使用非标） 站点运行模式：防护
此时 curl 这个站点 curl http://dsm.oio.ink:40404  返回302 说明正常 

2. 管理页面上将 站点运行模式：维护
此时 curl 这个站点 curl http://dsm.oio.ink:40404  返回400 The plain HTTP request was sent to HTTPS port

3.管理页面上将 站点运行模式：防护
此时 curl 这个站点 curl http://dsm.oio.ink:40404  返回400 The plain HTTP request was sent to HTTPS port，开了强制https，不重定向

**Comment by yrluke** [comment]
按照师傅说的操作方式我这边尝试配置了一下，返回全部为400 The plain HTTP request was sent to HTTPS port
这个目前在最新版本下为预期的
