### ISSUE TITLE
[建议] 在配置文件中控制各容器的最大资源使用率

### ISSUE THREAD

**Issue by ACoolOctober** [chaitin/SafeLine#502]
### 背景与遇到的问题

![image](https://github.com/chaitin/SafeLine/assets/61481593/3082df47-9359-4117-a61f-ca737d4ed12d)
日志容器占用CPU、IO过高导致服务器宕机
此时没发现有明显的攻击行为，且重启服务后也没有相关攻击记录 
kill掉 日志容器后，服务器CPU与IO直接下降 但是不久容器重启 CPU继续百分百

### 建议的解决方案

建议在配置文件中控制各容器的最大资源使用率，相对于服务器宕机 丢弃或限制部分请求会更好

**Comment by yrluke** [comment]
能发一下雷池版本吗，或者直接升级雷池版本之后再试一下

**Comment by ACoolOctober** [comment]
你好，多个版本都是这样，现在用的最新版本也是如此。昨天也发生了多次宕机 但是后面看访问数据和攻击事件都是正常的。 是否需要其他详细的日志用于分析呢？ 可以提供我操作说明


| |
whereyou_lx_520
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月8日 18:30 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chaitin/SafeLine] [建议] 在配置文件中控制各容器的最大资源使用率 (Issue #502) |

能发一下雷池版本吗，或者直接升级雷池版本之后再试一下

**Comment by yrluke** [comment]
是否是轻量服务器呢

**Comment by ACoolOctober** [comment]
是的，是用的阿里云轻量服务器，
配置如下：2核4GB6MB带宽
服务器内核信息：Linux version 5.10.134-15.2.al8.x86_64 (mockbuild@a12i03132.na61) (gcc (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3.5 2.32), GNU ld version 2.35-12.2.al8) #1 SMP Thu Sep 14 03:42:13 UTC 2023

**Comment by yrluke** [comment]
师傅可以看一下轻量服务器的概念，可能看上去的cpu以及内存较高的样子，但其实没啥负载

**Comment by ACoolOctober** [comment]
并不是看着高，而是实打实的高占用 甚至会导致服务器离线。请问有没有什么方法查看 雷池日志高负载的原因？
如下是阿里云后台监控数据:
![image](https://github.com/chaitin/SafeLine/assets/61481593/a2986254-3e4d-4e47-aa20-4896b7962700)
凌晨时还发生过服务器离线:
![image](https://github.com/chaitin/SafeLine/assets/61481593/48383516-067e-46a5-bfad-3ccb8f8e20e1)

**Comment by yrluke** [comment]
嗯，这个问题主要出在：轻量服务器并不会是不会保证有足够多的算力，也就是说看上去是2c，但其实算力根本不够2c，或者说2c的cpu单个算力不足，我自己的站点1c1g也可以跑的很稳定，群里也有大量的用户反馈类似的问题，如果条件允许的话，师傅可以买一台正常的非轻量服务器试一下
