### ISSUE TITLE
上游服务器如何获得是从http还是https来的？

### ISSUE THREAD

**Issue by saigyouyou** [chaitin/SafeLine#506]
### 反馈内容
我的服务器后台上传内容会根据$_SERVER['REQUEST_SCHEME']来拼接返回的地址，部署waf之后上游服务器是ip:port的形式，从上游服务器中获取$_SERVER['REQUEST_SCHEME']就永远是http了，有没有办法获得路径中是http还是https?

**Comment by yrluke** [comment]
有办法
<img width="614" alt="截屏2023-12-11 上午11 28 39" src="https://github.com/chaitin/SafeLine/assets/42405631/df7d26a3-3738-4c96-80c4-60a4d394d220">
可以尝试打开这个地方，然后在php代码里尝试获取这个header
