### ISSUE TITLE
[Bug] Firefox 缺少所需的 TLS 功能

### ISSUE THREAD

**Issue by qingshanking** [chaitin/SafeLine#507]
### 问题描述

配置SSL后，Firefox 浏览器会提示 “缺少所需的 TLS 功能”
错误代码：MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

这个错误，需要调整nginx配置，但是页面没有修改的地方，是不是后期更新把这个异常给优化一下？
![image](https://github.com/chaitin/SafeLine/assets/22401257/025afc00-73ed-43f8-a7f8-e2ce8b36e90e)

### 版本号

3.15.3

### 复现方法

1.配置ssl证书后，
2.访问配置的ssl网站

### 期望的结果

解决Firefox 浏览器显示“缺少所需的 TLS 功能”，使网站访问正常

**Comment by yrluke** [comment]
证书是不是使用的自签名证书呢

**Comment by qingshanking** [comment]
> 证书是不是使用的自签名证书呢

非自签证书，证书使用的是 TrustAsia RSA DV TLS CA G2

**Comment by qingshanking** [comment]
补充一下，这个问题解决方案

https://blog.csdn.net/myarche/article/details/102976751
