### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sdxzwd** [chaitin/SafeLine#509]
### 问题描述

直接用https://ip 访问
ssl证书是用户上传的某个证书

### 版本号

3.15.3

### 复现方法

在浏览器输入 https://ip
查看ssl证书

### 期望的结果

直接用ip访问,可以设置成默认证书 或者自签的ip证书

**Comment by yrluke** [comment]
这个目前确实做不了，因为本身waf是一个7层的应用，如果想做这个的话要在4层ssl交换密钥的时候就做出行动，目前看太复杂了，师傅可以在前面配置nginx来解决这个问题
