### ISSUE TITLE
Limit IP access to admin page

### ISSUE THREAD

**Issue by mvh97hg** [chaitin/SafeLine#510]
### 背景与遇到的问题

I want to limit ip access to waf admin page

**Comment by Lorna0** [comment]
Duplicate，可以到这里集中讨论和跟进:
* https://github.com/chaitin/SafeLine/issues/137

不过这个可以通过防火墙规则等方式实现，所以目前优先级不是很高。But it can be achieved through other methods such as firewall, so the priority is not very high at present.
