### ISSUE TITLE
[Bug] 国际化英文模式下，攻击 IP 的地理位置如果在中国内，没有正确显示成英文

### ISSUE THREAD

**Issue by upbeat-backbone-bose** [chaitin/SafeLine#512]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/438092/4cfac09e-9479-45db-aa29-7ca0e448666a)

### 版本号

3.15.3

### 复现方法

1.右上角，选择"en"切换英文语言环境
2."event"清单查看攻击来源IP列表，中国区显示的为中文地址的省份或者直辖市，英文显示的为英文的国家

### 期望的结果

无论来源是否中国，如果是国家化地址的情况应该全部以英文语言来显示

**Comment by upbeat-backbone-bose** [comment]
@Issues-translate-bot

**Comment by DeronW** [comment]
@upbeat-backbone-bose  4.2.0 版本已经修复这个问题

**Comment by upbeat-backbone-bose** [comment]
@DeronW 确定修复了吗？我试了下好像没什么变化啊
![image](https://github.com/chaitin/SafeLine/assets/438092/0e0ed21c-033a-4612-82e2-24156694c83d)

**Comment by upbeat-backbone-bose** [comment]
![image](https://github.com/chaitin/SafeLine/assets/438092/1bf3b687-5d33-4115-a2e1-6be5b8d65b7a)

**Comment by upbeat-backbone-bose** [comment]
@DeronW 可以关闭了.
