### ISSUE TITLE
[建议] 增加对网站文本流式输出的支持

### ISSUE THREAD

**Issue by nobody0222** [chaitin/SafeLine#513]
### 背景与遇到的问题

我在chatgpt服务网站上部署了雷池waf，但因为雷池目前引擎其实是不支持流式的（讨论群中官方回复），所以每次用户输入后需要等待很长时间才能看到整段回复而不是看到内容一直输出。

### 建议的解决方案

希望考虑加入流式的支持

**Comment by Lorna0** [comment]
流式是指 Websocket 么？

**Comment by nobody0222** [comment]
你好，不是指websocket；我的网站用nodejs开发，流式内容用的是 stream-http "2.8.2"模块实现的
> 流式是指 Websocket 么？

**Comment by Lorna0** [comment]
有些理解了，设计上雷池内部会缓存一段时间响应，目的是为响应的检测作准备。如果你的服务是在单个 http 请求一直输出响应，那雷池就会缓存起来，到最后整段一起响应。

这个缓存排除了一些常见的大体积或流式 content-type，比如视频和文件下载啥的（如下图），没有考虑 chatgpt 这种文本流式响应。可以加一下，响应的 content-type 是 text/event-stream 吗？求抓个包看一看。

![image](https://github.com/chaitin/SafeLine/assets/56920727/4c07bb92-b505-4132-ac48-1fbdde4481ed)

**Comment by nobody0222** [comment]
你好，（抱歉这么久没回）
没错，响应的 content-type 是  text/event-stream
附：输出文本的标头截图
![image](https://github.com/chaitin/SafeLine/assets/91100239/58df5bd0-b0d9-45c1-b628-c7c32e692580)

**Comment by Lorna0** [comment]
在 4.0.0 以上版本支持了，可以试试

**Comment by nobody0222** [comment]
已经用上了，辛苦啦

**Comment by kenliu-SH** [comment]
麻烦问一下，这个是社区版本的解决方案，企业版是否有新的方案？

**Comment by Lorna0** [comment]
> 麻烦问一下，这个是社区版本的解决方案，企业版是否有新的方案？

这个 issue 是网站文本流式返回导致的，没太理解师傅指的是需要有什么新的方案。或者企业版的话可以直接咨询对接的销售/售前/售后。

**Comment by kenliu-SH** [comment]
> > 麻烦问一下，这个是社区版本的解决方案，企业版是否有新的方案？
> 
> 这个 issue 是网站文本流式返回导致的，没太理解师傅指的是需要有什么新的方案。或者企业版的话可以直接咨询对接的销售/售前/售后。

客户不允许我们禁用WAF缓存，我们要确保在传输 text/event-stream 内容时及时传递。

**Comment by itg4202** [comment]
Version 7.4.0是默认支持了嘛？在防护Dify的时候没有流式输出。Content-Type是text/event-stream; charset=utf-8

**Comment by Kikujir** [comment]
新版本8.x已经支持了，请在这里配置

![Image](https://github.com/user-attachments/assets/cdf811ea-1340-4e40-8f48-15a8777f1d4b)
