### ISSUE TITLE
[Bug]  间隔几个小时NGINX日志就出现大量错误日志

### ISSUE THREAD

**Issue by mu0641** [chaitin/SafeLine#515]
### 问题描述

 间隔几个小时雷池的NGINX就出现大量错误日志，然后雷池这台服务器就卡死几分钟，服务器ssh也连不上去，后端的网站是没有问题的，绕过雷池可以正常访问
![微信图片_20231212092241](https://github.com/chaitin/SafeLine/assets/71642/17327cbb-9121-4f6f-b2c5-f4a47b2a01bc)
![微信图片_20231212092255](https://github.com/chaitin/SafeLine/assets/71642/74af3088-86a3-41a4-bae2-28b5fda31d6c)

2023/12/12 07:17:00 [error] 1216314#0: *2208493 connect() to unix:/resources/detector/snserver.sock failed (11: Resource temporarily unavailable) while connecting to upstream,
磁盘IO跑满了

### 版本号

3.14.1

### 复现方法

不能复现

### 期望的结果

能否提示怎么调试，查找问题

**Comment by yrluke** [comment]
轻量云服务器吗，看上去io并没有想象中的那么高啊

**Comment by mu0641** [comment]
阿里云的2核2G，cpu才10%以内，磁盘看整个曲线，相比正常300-400KB，90M的读取很高了吧。这台服务器只安装了雷池，unix:/resources/detector/snserver.sock failed 后为啥磁盘飙那么高

**Comment by yrluke** [comment]
我看了一下阿里云的云盘文档，iops如果是20G的高效云盘可能已经快到顶了，读取速度都是300M起啊，如果是轻量云服务器的话，那可能确实有这种可能，因为阉割了很多东西，fail之后磁盘很高的话，是因为tengine会不断尝试重连引擎。

**Comment by yrluke** [comment]
所以说师傅是不是买的99一年的轻量服务器呢，群内以及issue内有大量的用户反馈类似的问题，如果是轻量服务器的话，由于性能远不能达到其标注的标准，其实是不太能把雷池跑起来的，如果有需要的话，可以开一台1c1g的服务器试一下应该是够用的

**Comment by mu0641** [comment]
好吧 。我试试
