### ISSUE TITLE
[建议] 建议修改数据统计页 4xx错误率 和5xx错误率 的显示值

### ISSUE THREAD

**Issue by HolyGu** [chaitin/SafeLine#517]
### 背景与遇到的问题

数据统计页面在没有出现4xx错误和5xx错误的时候，显示的值是-%，可否修改成0%
![image](https://github.com/chaitin/SafeLine/assets/28488437/0a08c3cd-6035-48f1-8bb4-c72314d6da02)

**Comment by DeronW** [comment]
下个版本（3.16）增加该功能

**Comment by DeronW** [comment]
@HolyGu  3.16.1 版本修改了
