### ISSUE TITLE
[建议] 

### ISSUE THREAD

**Issue by zhangbing317** [chaitin/SafeLine#518]
### 背景与遇到的问题

能否把申请好的SSL证书文件 用域名作为文件名

### 建议的解决方案

比如www.abc.com.crt   www.abc.com.key

**Comment by yrluke** [comment]
可以考虑，但是短时间内可能没有时间做这件事，而且会增加升级风险，如果不是很紧急的话，还是通过nginx配置来查看证书吧，或者直接使用acme.sh
