### ISSUE TITLE
[建议] 新增metrics接口，便于在grafana及prometheus接入及展示

### ISSUE THREAD

**Issue by nondevops** [chaitin/SafeLine#521]
### 背景与遇到的问题

WAF被拦截的域名，显示被拦截的信息，当前只能在站内显示，不能在集中监控平台统一展示，能否考虑暴露响应的监控指标，便于prometheus采集及上报。

**Comment by DeronW** [comment]
@nondevops  都需要哪些监控指标？

**Comment by DeronW** [comment]
@nondevops  prometheus 可以收集日志，但更推荐的方式是通过 syslog 对接，syslog 的功能也在开发当中。
