### ISSUE TITLE
[建议] 增加arm版本的WAF

### ISSUE THREAD

**Issue by j4ckzh0u** [chaitin/SafeLine#522]
### 背景与遇到的问题

在国产化项目上，只有arm服务器。当前雷池 只有x86版本，无ARM版本。

### 建议的解决方案

建议增加ARM版本的WAF安装镜像

**Comment by yrluke** [comment]
这个需求实在是过于企业需求了，社区版主要面向中小站长，如果师傅真的有arm需求，可以去官网留个手机号，会有专人联系您

**Comment by wang4386** [comment]
强烈希望支持ARM架构
