### ISSUE TITLE
[建议] 文档中WAF检测效果对比添加宝塔云WAF

### ISSUE THREAD

**Issue by devhaozi** [chaitin/SafeLine#525]
### 背景与遇到的问题

宝塔最近新出的一个产品https://www.bt.cn/new/btwaf.html

也是可以免费使用的，想看下和咱们雷池的对比数据。

### 建议的解决方案

添加宝塔云WAF的测试数据。

**Comment by yrluke** [comment]
哈哈，这个我们确实没办法出，就算是出了是不是也有点不客观？
师傅可以用https://github.com/chaitin/blazehttp 来自行测试一下吧，我们就做好功能开发迭代就好。
感谢支持

**Comment by devhaozi** [comment]
宝塔云WAF测试结果：

1. 默认配置下
2. 调整配置到全严格模式下

![d43db958f3519d8daaf308a79b96941e](https://github.com/chaitin/SafeLine/assets/115467771/0b2d10e0-6d3c-4f0b-a129-a3e0f261fe7b)

![a9c6be50cec75b86eb5380baeaa77f95](https://github.com/chaitin/SafeLine/assets/115467771/1b17fb07-541d-4d1e-b785-ea0229907a9f)

雷池：

1. 默认配置下
2. 调整配置到全高强度防护下

![8872f8c10754f645b3593aa8018cf620](https://github.com/chaitin/SafeLine/assets/115467771/5b60d291-ec5a-4cf5-bea4-bae60c2795ed)

![bf1f28842a5b0c7ada4374f44a38fc27](https://github.com/chaitin/SafeLine/assets/115467771/470d4a3e-9c4b-46b5-8110-5bd528673b53)

顺便测试了 [ngx_waf](https://github.com/ADD-SP/ngx_waf) 不带 ModSecurity 的版本，使用 FULL 配置：

![e34363044222eef96400ea6fcebac462](https://github.com/chaitin/SafeLine/assets/115467771/12ecbce2-25d6-4ba9-bc17-aead54ef5717)
