### ISSUE TITLE
[建议] 支持自定义站点监听的 ip 地址

### ISSUE THREAD

**Issue by fooyii** [chaitin/SafeLine#527]
### 背景与遇到的问题

背景：
我在前端用的 nginx 四层代理到 WAF，再到后端 caddy 。我希望WAF 和后端业务都能获取到真实 IP。不然 WAF 就是去作用了。后端业务的日志分析也比较难。
诉求：
1、想让WAF 只监听 127.0.0.1。不然外边也可以通过 WAF 的监听端口去访问。配置防火墙会比较麻烦。
2、需要后端获取到真实的 ip 地址。nginx 四层代理的时候需要借用 proxy_protocol 才能获取 ip 地址。 

### 建议的解决方案

方案 1：
增加监听 ip 地址自定义，增加端口和协议自定义。
目前我的配置是
listen 127.0.0.1:port ssl proxy_protocol;
改完以后我都要 chattr +i 锁住配置文件。

方案2：
web 增加可选项，比如监听地址可以点一下选择，proxy_protocol 可以点勾选择。

**Comment by Lorna0** [comment]
第二点 duplicate：
* https://github.com/chaitin/SafeLine/issues/359

这里就不讨论了

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
