### ISSUE TITLE
[建议] 编辑站点增加站点ID的显示

### ISSUE THREAD

**Issue by ashuai** [chaitin/SafeLine#528]
### 背景与遇到的问题

```
ls resources/nginx/custom_params/
backend_1  backend_2  backend_3  backend_4  backend_5  backend_6  backend_7  backend_8
```

编辑自定义脚本时，想分清谁是谁比较麻烦，希望能在界面直接显示站点ID

### 建议的解决方案

希望能在界面直接显示站点ID
![20231218120251](https://github.com/chaitin/SafeLine/assets/76211/07410e33-c0ba-4d06-a7ac-ff5ae89cfd28)

**Comment by Lorna0** [comment]
站点详情就有的：
![image](https://github.com/chaitin/SafeLine/assets/56920727/d85e5650-756d-4f72-b2e3-62f49e93e19d)

**Comment by Lorna0** [comment]
似乎能解决，先关闭了，有需要可以再评论
