### ISSUE TITLE
[建议] 建议原始日志详情增加复制到curl功能，便于调试

### ISSUE THREAD

**Issue by ashuai** [chaitin/SafeLine#531]
### 背景与遇到的问题

建议原始日志详情增加复制到curl功能，便于互相交流和重现攻击

### 建议的解决方案

增加复制到curl按纽
![20231218144148](https://github.com/chaitin/SafeLine/assets/76211/bb620be8-5ed1-4a9e-8adb-5e250950ddc9)

**Comment by Lorna0** [comment]
4.1 增加了复制为 cURL，可以试试：
![image](https://github.com/chaitin/SafeLine/assets/56920727/33f8efd6-c495-422f-abf7-449d34222b83)
