### ISSUE TITLE
新版本nginx无法使用allowed_origin变量

### ISSUE THREAD

**Issue by jamebal** [chaitin/SafeLine#533]
### 反馈内容

Version: 3.16.1
如果在custom_params设置了allowed_origin，则safeline-tengine 无法启动：
```log
nginx: [emerg] unknown "allowed_origin" variable
```

**Comment by yrluke** [comment]
nginx本身就没有这个变量啊

**Comment by jamebal** [comment]
不好意思，记错了，这是我之前在`nginx.conf`中定义的变量，升级后之前编辑的nginx.conf被重置了，请现在的版本如何自定义nginx http下的内容
