### ISSUE TITLE
[建议] 证书编辑提交后，自动重载nginx

### ISSUE THREAD

**Issue by ayellowcat** [chaitin/SafeLine#534]
### 背景与遇到的问题

在证书管理——证书编辑，上传替换了证书后，提交后雷池的nginx没有自动重载，新替换的证书没有生效

### 建议的解决方案

希望能在点击提交后，nginx能够自动重载，让新的证书改动生效。
毕竟nginx对于证书的操作，都需要重载才能生效，希望点击提交后，雷池能够自动完成这个过程，免去手动调用雷池容器的nginx重载的繁琐过程

**Comment by DeronW** [comment]
非常有道理

**Comment by Lorna0** [comment]
4.0.0 已发布，可以尝试一下。
