### ISSUE TITLE
站点防护模式切，防护失效，二次切换才生效

### ISSUE THREAD

**Issue by ForgetStarwish** [chaitin/SafeLine#535]
### 问题描述

今天在测试的时候发现，在编辑防护站点的运行模式会出现切换状态显示正常，功能无法实现的情况
将运行模式改为“观察”，测试完成后修改模式为“防护”（此时防护功能时失效的）如下图所示
![1703041165837](https://github.com/chaitin/SafeLine/assets/112318544/f1eac10c-26dc-4df0-9c4b-03110ce60cb2)
当再次切换成“观察”-->“防护”（此时防护功能时生效了）
![1703041165868](https://github.com/chaitin/SafeLine/assets/112318544/6529a634-1c0e-40ea-926e-f10605e5ab32)

### 版本号

3.16.1

### 复现方法

本地搭建sql-lab靶机，雷池添加对应防护站点。
通过将运行模式改为“观察”后改回“防护”时，使用手动注入测试，发现防护功能不生效。攻击事件也无对应安全防护日志。
二次切换后，站点防护功能恢复正常。

### 期望的结果

希望站点防护功能可以实现单次切换就能实现对应功能。

**Comment by yrluke** [comment]
按照上述步骤，没有复现，麻烦检查一下是否是配置错了，例如：请求实际被转发到其他的防护站点上了

**Comment by xbingW** [comment]
最新版 6.9.0 已经修复
