### ISSUE TITLE
[Bug] 删除/添加站点失败

### ISSUE THREAD

**Issue by huangyitong** [chaitin/SafeLine#536]
### 问题描述

当前站点400+，现在删除某一个站点或者添加某一个站点均失败
![image](https://github.com/chaitin/SafeLine/assets/67935454/9b2c0cf5-4586-43de-aa22-8d131d982325)

### 版本号

3.16.1

### 复现方法

当前站点400+，现在删除某一个站点或者添加某一个站点就会提示报错，无法操作成功

### 期望的结果

可以正常添加站点和删除站点

**Comment by yrluke** [comment]
按照提示修改一下这个配置文件就好了，或者再部署一个新的waf
