### ISSUE TITLE
[建议] 配置导出、转换

### ISSUE THREAD

**Issue by huyushao521** [chaitin/SafeLine#539]
### 背景与遇到的问题

1.建议新增商业版和社区版配置是否可以导出导入
2.建议新增工具可以实现友商配置可以互相转换

**Comment by dossec** [comment]
需要这个功能，docker配置直接拷贝使用不了，重新添加太麻烦

**Comment by Lorna0** [comment]
> 1.建议新增商业版和社区版配置是否可以导出导入

雷池企业版的基础配置是可以和社区版互相导出导入的，可以联系一下项目的技术支持。

> 2.建议新增工具可以实现友商配置可以互相转换

这个不太现实，友商的配置格式我们也不知道啊。

**Comment by lem0ke** [comment]
> > 1.建议新增商业版和社区版配置是否可以导出导入
> 
> 雷池企业版的基础配置是可以和社区版互相导出导入的，可以联系一下项目的技术支持。
> 
> > 2.建议新增工具可以实现友商配置可以互相转换
> 
> 这个不太现实，友商的配置格式我们也不知道啊。

那针对社区版本身配置的导入导出呢，重新配置太麻烦了

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
