### ISSUE TITLE
[建议] 希望能支持使用自定义URL的mysql数据库

### ISSUE THREAD

**Issue by zhanying233** [chaitin/SafeLine#540]
### 背景与遇到的问题

现在用docker拉起来的数据库占用了太多的磁盘空间和内存
所以我这的内网有一个专门独立出来的mysql数据库服务器
这边希望能支持mysql
便于能让数据能够通过内网传输并保存到专门独立出来的mysql服务器
以节省docker所在服务器的磁盘空间和内存

### 建议的解决方案

希望能够支持使用MySQL服务器

**Comment by DeronW** [comment]
现在服务用的是 postgres ，不能平滑迁移到 MySQL 。可以独立启动一个 postgres，然后在 compose.yaml 配置中修改 数据库链接地址，改到自己的独立服务上。

备注：
数据库占用的问题已经在新的调研当中，直接使用 postgres 确实占用太大，正在考虑 embed db + syslog 转发的方案。如果有更具体的业务场景，也请提出

**Comment by zhanying233** [comment]
非常感谢您的回复，
那么以后有希望支持mysql吗？

**Comment by ws20940548** [comment]
支持！我现在搭建的1台服务器共存模式，nginx用的非标端口，mysql是租的独享的
postgres占用太大了
也希望能自主迁移到mysql
只要不是postgres，embed db也可以

**Comment by xbingW** [comment]
暂不考虑支持
