### ISSUE TITLE
[建议] 指定ip不加入 IP 情报共享计划

### ISSUE THREAD

**Issue by BIMiracle** [chaitin/SafeLine#541]
### 背景与遇到的问题

我下载了blazehttp和测试样本，尝试自动化测试防护效果，已经产生了很多攻击事件，IP情报共享计划会不会把当天发生攻击事件的ip都上传？如何避免自己的测试ip上传？

### 建议的解决方案

建议增加功能 指定ip不加入 IP 情报共享计划

**Comment by yrluke** [comment]
不会的，相比于社区的流量，师傅可能打出来的流量并不会导致进入黑名单
