### ISSUE TITLE
[建议] 是否能根据黑白名单自定义返回内容的格式？

### ISSUE THREAD

**Issue by saigyouyou** [chaitin/SafeLine#543]
### 背景与遇到的问题

我的项目不大，app和网站是共用一个域服务器和域名的，如果网站跳转被拦截打开的是雷池的页面倒是没啥问题，但是app的接口路径返回的默认是json格式。当app的接口的请求被拦截的时候，json解析失败在某些机器上甚至会闪退。现在我只能把app路径设为白名单，又自建了一个lua的waf来防app这边的攻击，显得有点多此一举。

### 建议的解决方案

有没有办法按照一定的规则例如黑白名单，来定制拦截返回的提示格式？

**Comment by DeronW** [comment]
@saigyouyou  如果根据 http header 中的 Accept 头来设置返回格式内容是否可以解决这种问题？

例如，http request header 中标记了
Accept: application/json
那么拦截响应，会以 json 格式返回

**Comment by saigyouyou** [comment]
@DeronW 这样也可以。虽然我这边的项目目前是服务端决定返回格式的，不过客户端可以到时候改。
能约定返回的字段就更好了，那样人机验证相关逻辑也能显示。比方说这样的
```
{
    code: 403,
    msgType: 'html',
    msgContent: 'xxxxxx'
}
```

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
