### ISSUE TITLE
[Bug] 从普通版升级到Beta版本后，统计数据异常

### ISSUE THREAD

**Issue by testnet0** [chaitin/SafeLine#546]
### 问题描述

使用在线脚本升级，升级后统计数据异常：
![image](https://github.com/chaitin/SafeLine/assets/18673513/01eaf27e-3950-400d-bf31-fde0cd91e599)

### 版本号

4.0.0-beta.1

### 复现方法

使用在线脚本升级

### 期望的结果

统计数据正常

**Comment by DeronW** [comment]
@testnet0  今天更新了 4.0.0-beta.2 更新试一下

可能得错误原因是 postgres 使用了 alpine 镜像，导致时区错误，导致统计数据异常

**Comment by DeronW** [comment]
@testnet0  这个问题是否解决，如果解决了可以关闭这个问题

**Comment by testnet0** [comment]
> @testnet0 这个问题是否解决，如果解决了可以关闭这个问题

![image](https://github.com/chaitin/SafeLine/assets/18673513/43bf630a-07f9-4293-945b-65385ee55f47)
并没有解决，已经升级到最新版本
