### ISSUE TITLE
关于打开 nginx access_log 的问题

### ISSUE THREAD

**Issue by LisonFan** [chaitin/SafeLine#547]
### 背景与遇到的问题

按照文档（[https://waf-ce.chaitin.cn/docs/faq/test](https://waf-ce.chaitin.cn/docs/faq/test)）的说明，在 `resources/nginx/nginx.conf ` 把日志打开

但是文档同时也说了 `雷池每次修改站点或者重启服务时，都会重新生成 resources/nginx/sites-enabled/ 下的 nginx conf 文件。` （[https://waf-ce.chaitin.cn/docs/faq/other](https://waf-ce.chaitin.cn/docs/faq/other)）

我该如何设置才能永久开启？

我一个家庭用户，实在没必要再加一层 APISIX😅

**Comment by DeronW** [comment]
可以打开。4.0 版本以后，nginx.conf 是根配置，其中有一个引用路径，自定义的修改都放在引用路径里，这样不会冲突，也不会被覆盖。具体引用路局，看 nginx.conf 的最后几行配置

**Comment by DeronW** [comment]
@LisonFan  这个问题是否解决，如果解决了，可以关闭这个问题
