### ISSUE TITLE
对于黑名单ip最多可以添加多少个

### ISSUE THREAD

**Issue by fus0397** [chaitin/SafeLine#548]
### 反馈内容

![image](https://github.com/chaitin/SafeLine/assets/34109364/440348fd-151f-4a33-b6a6-23cd0c4ac3f4)
我有三个ip组
两个黑名单（预估16815个ip）
一个白名单（预估8649个ip）
设置黑名单的时候，总是无法设置，会导致添加失败，就是上面图片的样式反馈

**Comment by DeronW** [comment]
@fus0397  目前的限制是 10_000 个，如果太多，请分开添加。 服务出现 504 情况，应该是服务异常了，可能规则编译失败，有没有更详细的错误信息，后台日志？

**Comment by DeronW** [comment]
@fus0397  问题是否已解决？
