### ISSUE TITLE
[建议] 希望支持在waf界面查看所有Nginx的访问日志，而不是仅能查看疑似攻击行为的日志

### ISSUE THREAD

**Issue by zcbxxx1** [chaitin/SafeLine#550]
### 背景与遇到的问题

发现站点地图有外地访问，但是看不到详细的日志，例如何时访问，IP来源，访问内容等等
当前仅能查看疑似攻击行为的日志

### 建议的解决方案

希望增加Nginx访问日志开关
即支持在waf界面查看所有Nginx的访问日志

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/145
