### ISSUE TITLE
[建议] 希望增加首页访问来源地图可以点进去进一步查看IP归属地等与对应访问日志功能 

### ISSUE THREAD

**Issue by zcbxxx1** [chaitin/SafeLine#551]
### 背景与遇到的问题

站点访问地图只能看到省一级来源，但IP地址实际上定位可以更加精确，可以点进去看到市级甚至区级等等

### 建议的解决方案

希望增加首页访问来源地图可以点进去进一步查看IP归属地等与对应访问日志功能

**Comment by DeronW** [comment]
@zcbxxx1  我们目前还没有这么精确的 IP 库，暂时无法实现
