### ISSUE TITLE
[建议] 希望可以在防护站点编辑页面增加分组、调整顺序等功能 

### ISSUE THREAD

**Issue by zcbxxx1** [chaitin/SafeLine#552]
### 背景与遇到的问题

针对防护站点较多的情况，希望可以在防护站点编辑页面增加分组、调整顺序等功能

### 建议的解决方案

![图片](https://github.com/chaitin/SafeLine/assets/56199489/b0248937-4071-4a5d-befe-a5de59cb9676)

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/139
