### ISSUE TITLE
[Bug] 雷池控制台证书 接口数据异常

### ISSUE THREAD

**Issue by 0Knot** [chaitin/SafeLine#554]
### 版本号

3.16.1

### 复现方法

1. 全新安装`3.16.1`
2. 通用配置管理-> 证书管理 加入自定义证书
3. 通用配置管理-> 雷池控制台证书 切换证书 -> 保存

提示 接口数据异常

### 期望的结果

解决该问题

**Comment by DeronW** [comment]
@0Knot  是否有更详细的错误信息或者 docker 的服务日志？
