### ISSUE TITLE
没有事实的记录攻击时间[Bug] 

### ISSUE THREAD

**Issue by 1764364648** [chaitin/SafeLine#555]
### 问题描述

攻击日志没有实时的记录下来
![0feaa1e7213e427c238d0fa6f1571b33](https://github.com/chaitin/SafeLine/assets/123971622/2f119fa3-e30b-4e7e-8e52-122e7b9c48b0)

### 版本号

 4.0.0-beta.2

### 复现方法

No response

### 期望的结果

希望能修复可以事实记录攻击日志

**Comment by DeronW** [comment]
@1764364648  是否有更详细的描述，或者复现问题的步骤？或者报错日志等信息？

**Comment by 1764364648** [comment]
就是在我博客上面的搜索框进行注入的话waf是会拦截但是不会有任何攻击的日子在其他地方进行注入都是有日志的就很奇怪
![image](https://github.com/chaitin/SafeLine/assets/123971622/b3733755-dfaa-4ce8-8fc8-75657ce27f19)
![image](https://github.com/chaitin/SafeLine/assets/123971622/36a2089c-e112-4e33-aec9-82c197a5f634)
![image](https://github.com/chaitin/SafeLine/assets/123971622/ad06a711-4e34-4ae3-bb60-018e3ab8b598)
