### ISSUE TITLE
是否有迁移功能呢

### ISSUE THREAD

**Issue by woodchen-ink** [chaitin/SafeLine#556]
### 背景与遇到的问题

现有的配置很多，我要迁移到另一台服务器，目前应该怎么迁移呢

### 建议的解决方案

增加导入导出功能

**Comment by zhaohai1024** [comment]
支持

**Comment by jssolo** [comment]
强烈支持，刚重装了一遍，配置啥的太麻烦了，特别是黑白名单

**Comment by ylwzbk** [comment]
雷池仅需要把设置的雷池安装的路径相关移动即可迁移

**Comment by ylwzbk** [comment]
#219

**Comment by DeronW** [comment]
@woodchen-ink  waf 本身目前还没有迁移功能，如果从运维角度来说的话，直接复制 resources 目录就可以实现 备份、迁移的功能

**Comment by Lorna0** [comment]
直接备份安装目录就行了，参考：https://github.com/chaitin/safeline/issues/90
