### ISSUE TITLE
[建议] IP 组支持订阅远程链接

### ISSUE THREAD

**Issue by LisonFan** [chaitin/SafeLine#557]
### 背景与遇到的问题

![image](https://github.com/chaitin/SafeLine/assets/9424775/6e014936-e3b7-455f-a4c4-083882c1a1f1)

我是家庭用户，目前的一个应用场景是对所有非大陆 IP 强制人机验证

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/414
