### ISSUE TITLE
[Bug] 腾讯云更新失败

### ISSUE THREAD

**Issue by Omoinemie** [chaitin/SafeLine#559]
### 问题描述

能不能做一个国内的加速源啊

### 版本号

v2.21.0

### 复现方法

/upgrade.sh)":~# bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/
  ____             __          _       _                
 / ___|    __ _   / _|   ___  | |     (_)  _ __     ___ 
 \___ \   / _` | | |_   / _ \ | |     | | | '_ \   / _ \
  ___) | | (_| | |  _| |  __/ | |___  | | | | | | |  __/
 |____/   \__,_| |_|    \___| |_____| |_| |_| |_|  \___|

[SafeLine] 脚本调用方式确认正常
[SafeLine] 发现 Docker 环境: '/usr/bin/docker'
[SafeLine] Docker 工作状态正常
Docker Compose version v2.21.0
[SafeLine] 发现 Docker Compose Plugin
[SafeLine] 发现位于 '/data/safeline' 的雷池环境
[SafeLine] 下载 compose.yaml 脚本成功
[SafeLine] 升级 .env 脚本成功
[SafeLine] 即将开始下载新版本 Docker 镜像
[+] Pulling 6/6
 ✘ fvm-manager Error                                                      14.7s 
 ✘ management Error                                                       14.7s 
 ✔ mario Pulled                                                            9.6s 
 ✘ postgres Error                                                         14.7s 
 ✔ tengine Pulled                                                         10.3s 
 ✘ detector Error                                                         14.7s 

### 期望的结果

Error response from daemon: Head "https://registry-1.docker.io/v2/chaitin/safeline-detector/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Achaitin%2Fsafeline-detector%3Apull&service=registry.docker.io": net/http: TLS handshake timeout

**Comment by ylwzbk** [comment]
自己参考百度的docker 加速教程不就行了

**Comment by DeronW** [comment]
@Omoinemie  在线安装遇到问题，可以使用离线安装方法 https://waf-ce.chaitin.cn/docs/guide/install#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85

镜像加速这个问题，建议自行更换源
