### ISSUE TITLE
[Bug] 使用同一个令牌软件扫码绑定多个WAF主机令牌，导致上一个令牌覆盖失效;

### ISSUE THREAD

**Issue by xmantom** [chaitin/SafeLine#560]
### 问题描述

当你使用一个令牌软件，扫码绑定第二台WAF主机令牌时，会提示用户admin令牌已经存在，选择是将会覆盖老的令牌，选择否则无法生成令牌

### 版本号

3.16.1

### 复现方法

1.手机安装谷歌或者微软令牌软件；
2.安装第一台WAF并且扫码绑定令牌；
3.安装第二台WAF并且扫码绑定令牌；

### 期望的结果

经过尝试对二维码内容解析得到结果为：
otpauth://totp/长亭雷池 WAF 社区版:admin?algorithm=SHA1&digits=6&issuer=长亭雷池 WAF 社区版&period=30&secret=key；
建议修改二维码生成字符串，在admin后面增加"@主机IP"；
例如修改为：
otpauth://totp/长亭雷池 WAF 社区版:admin@192.168.0.1?algorithm=SHA1&digits=6&issuer=长亭雷池 WAF 社区版&period=30&secret=key；
之后再进行二维码的生成，个人测试此方法可以有效避免令牌覆盖问题，同时也可以使用户在令牌软件中轻易分辨令牌归属；

**Comment by fgbfgerbb2** [comment]
社区版只是简单使用，支持多台服务器还是商业版吧。这个功能多台服务器肯定也有商业需求了。。。感觉没必要

**Comment by DeronW** [comment]
@xmantom  这听起来像是令牌应用的问题，可以换一个，比如微信小程序工具，我自己用的工具绑多个 waf 是没有问题的。 waf 的登录使用的令牌是标准算法，并没有对实例数量有限制。

这个 issue 中问题产生的原因，可能是因为 app 应用不允许重名，解决方法就是换一个应用

**Comment by huhaku** [comment]
其实你可以手动改下这个名字，然后再扫描再绑定就不会冲突了

**Comment by xmantom** [comment]
@DeronW 或许真如你所说是令牌软件不允许重名导致的，我知道如何处理也给出了从二维码生成串码改进的建议

**Comment by DeronW** [comment]
@xmantom  问题是有已解决？ 如果已解决，可以 close 这个 issue 了
