### ISSUE TITLE
更新 beta3 后登录失败

### ISSUE THREAD

**Issue by ZTfred** [chaitin/SafeLine#564]
### 反馈内容

使用官方命令更新后，登录雷池失败，提示 HTTP/2 协议错误

开发者选项提示：POST https://waf.alialili.cn/api/Login net::ERR_HTTP2_PROTOCOL_ERROR

日志：2024/01/02 10:27:57 [warn] 24#0: *10 an upstream response is buffered to a temporary file /usr/local/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 39.98.196.179, server: waf.alialili.cn, request: "GET /assets/index-8d2006b9.js HTTP/2.0", upstream: "https://10.0.24.7:9443/assets/index-8d2006b9.js", host: "waf.alialili.cn", referrer: "https://waf.alialili.cn/settings/general"

**Comment by ZTfred** [comment]
目前测试，仅雷池页面http2访问失败了，其他后端站点都正常，是不是beta3版本雷池不支持http2协议请求了

**Comment by DeronW** [comment]
@ZTfred  beta 版少配置了 http2 标记，问题已修复，下个版本更新

**Comment by Lorna0** [comment]
4.0.0 已修复
