### ISSUE TITLE
[建议] 为防护站点增加用户名密码访问验证

### ISSUE THREAD

**Issue by topkof** [chaitin/SafeLine#565]
### 背景与遇到的问题

在用户打开防护站点时需输入用户名、密码才可访问网站(可设置多组)

**Comment by DeronW** [comment]
@topkof  能再详细描述功能吗？ 什么时候输入账号密码？ 希望怎么配置账号密码？

**Comment by Lorna0** [comment]
relate to: 
* https://github.com/chaitin/SafeLine/issues/565

**Comment by Lorna0** [comment]
4.3.0 更新了 防护配置->身份认证 功能，可以给站点配置用户密码登录了：
![image](https://github.com/chaitin/SafeLine/assets/56920727/fe8919ca-9803-45e0-a4e7-59922d87f017)

**Comment by topkof** [comment]
感谢添加此功能！是否可以再迭代一个可以添加多用户账号访问的功能，场景是当删除某个访问账号权限后，其他用户仍可通过自己的独立账号访问网站
![独立访问](https://github.com/chaitin/SafeLine/assets/26196829/ceb08894-1777-4ba5-a24c-9892e695e050)

**Comment by topkof** [comment]
> 4.3.0 更新了 防护配置->身份认证 功能，可以给站点配置用户密码登录了： ![image](https://private-user-images.githubusercontent.com/56920727/302237144-fe8919ca-9803-45e0-a4e7-59922d87f017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjY2MTUsIm5iZiI6MTcwNzgyNjMxNSwicGF0aCI6Ii81NjkyMDcyNy8zMDIyMzcxNDQtZmU4OTE5Y2EtOTgwMy00NWUwLWE0ZTctNTk5MjJkODdmMDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEyMTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNjIwZDIyNjZmNGI2MGViZjA4MDIyN2IwMWE5MjBlMzJmMDM0ZGVmMTlkOTM1ZDhmMzFkNTVhZGZmNzllYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GooE1YxUlpXor-6KfJqQ2y10jqqc6m7maSaP1z4ibBM)

感谢添加此功能！是否可以再迭代一个可以添加多用户账号访问的功能，场景是当删除某个访问账号权限后，其他用户仍可通过自己的独立账号访问网站
![独立访问](https://github.com/chaitin/SafeLine/assets/26196829/ceb08894-1777-4ba5-a24c-9892e695e050)
