### ISSUE TITLE
[Bug] grpc proxy pass流量不能正常通过

### ISSUE THREAD

**Issue by JunyanHex** [chaitin/SafeLine#566]
### 问题描述

对于需要使用grpc(http2)协议的backend不能正常访问。
黑名单可以被拦截，不加黑名单接口不通。

### 版本号

4.0.0.beta3

### 复现方法

1、在site-enabled-stream/IF_backend_X或者custom_params/backend_X添加grpc_prox_pass的backend url (我部署的是Zitadel [https://zitadel.com/docs/self-hosting/manage/reverseproxy/nginx](url)  )
![image](https://github.com/chaitin/SafeLine/assets/91401252/6eda7b90-2178-45e1-9ef7-7830ed093a15)
2.容器内nginx -s reload
3.测试网站接口连通性，对应的接口一直在等待respone

### 期望的结果

能够正常访问。

**Comment by yrluke** [comment]
目前确实是不支持grpc，并且即使是能够连通，也没办法检测内容

**Comment by JunyanHex** [comment]
> 目前确实是不支持grpc，并且即使是能够连通，也没办法检测内容

好的 请问可以提供一下能用grpc的方法吗 需要修改哪个配置呢 谢谢
