### ISSUE TITLE
[Bug] 部分用户反馈无法人机验证图片对齐

### ISSUE THREAD

**Issue by mu0641** [chaitin/SafeLine#567]
### 问题描述

![20240104151536](https://github.com/chaitin/SafeLine/assets/71642/e7a24955-458d-489a-8042-308e9492bea1)

### 版本号

3.15.3

### 复现方法

低版本360浏览器，还有部分浏览器都无法旋转对其图片，认证通过

### 期望的结果

能够兼容低版本的浏览器

**Comment by kedyao** [comment]
我也遇到了同样问题 滑动时候 图片不跟着旋转 使用的是 百分浏览器
版本 5.0.1002.354（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)
