### ISSUE TITLE
升级版本后“源 IP 获取方式”配置失效

### ISSUE THREAD

**Issue by pusidun** [chaitin/safeline#57]
升级前版本：1.2.0
升级后版本：1.3.0

升级前配置：
源 IP 获取方式：从HTTP Header中获取
X-Forwarded-For

在升级版本后失效，需要重新保存才行。

其余配置都正常，SAFELINE_DIR环境变量在.env中
```
/home/ops/safeline
├── compose.yaml
├── .env

cat .env
SAFELINE_DIR=/home/ops/safeline
IMAGE_TAG=latest
MGT_PORT=9443
POSTGRES_PASSWORD=xxxxxx
```
升级方式
`docker compose down && docker compose pull && docker compose up -d`

**Comment by luweijun1992** [comment]
我是正常的，不知道是不是个例。看看其他用户反馈。

**Comment by zclaiqcc** [comment]
理论上 1.2 升级 1.3 是没有调整 nginx conf 的动作，这个我们内部确认一下，先挂个 bug 标记，看看有没有其他师傅也遇到类似的问题

**Comment by zclaiqcc** [comment]
先暂时关闭了，有其他师傅遇到再 open 吧，内部尝试了几次未复现
