### ISSUE TITLE
[Bug] client timeout 

### ISSUE THREAD

**Issue by artemus717** [chaitin/SafeLine#570]
### 问题描述

3.0.1升级3.15.3，修改站点，提示client timeout

management api 日志
time="2024/01/04 00:52:23" level=error msg="client timeout" file=tcd.go func=/patronus/safeline-2/management/webserver/lib/tcd.ReloadWebsite line=221 logger=tcd
time="2024/01/04 00:52:23" level=error msg="client timeout" file=website.go func=/patronus/safeline-2/management/webserver/api.PutWebsite line=192 logger=api
time="2024/01/04 00:57:34" level=error msg="client timeout" file=tcd.go func=/patronus/safeline-2/management/webserver/lib/tcd.ReloadWebsite line=221 logger=tcd
time="2024/01/04 00:57:34" level=error msg="client timeout" file=website.go func=/patronus/safeline-2/management/webserver/api.PutWebsite line=192 logger=api
time="2024/01/04 01:02:09" level=error msg="client timeout" file=tcd.go func=/patronus/safeline-2/management/webserver/lib/tcd.ReloadWebsite line=221 logger=tcd
time="2024/01/04 01:02:09" level=error msg="client timeout" file=website.go func=/patronus/safeline-2/management/webserver/api.PutWebsite line=192 logger=api

web页面request
{"id":55,"ports":["80"],"server_names":["*.scio.org.cn"],"email":"","cert_id":0,"upstreams":["http://192.168.255.19"],"comment":"mall"}

web页面response
{"data":null,"err":"internal-error","msg":"client timeout"}

### 版本号

3.15.3

### 复现方法

请见描述

### 期望的结果

正常添加

**Comment by yrluke** [comment]
是不是没有更新compose.yml
如果不成功，麻烦升级至最新版本，我们暂时只对最新版本进行维护

**Comment by artemus717** [comment]
不知道是不是因为我使用Kubernetes部署的，有些端口没开导致的。现在使用官方的安装方式就没问题了。谢谢！
