### ISSUE TITLE
[建议] 1、增加用户权限管理或者增加多用户登录模式；2、增加webhook发送攻击事件与IP限制记录；

### ISSUE THREAD

**Issue by JayLeeNull** [chaitin/SafeLine#573]
### 背景与遇到的问题

1、实际对于安全运维不会限于一人，但是mfa绑定是一人手上，不方便多人运维使用；
2、对于日常WAF的动态拦截跟封堵IP形为只能是在WEB上登录时能看，实时性太差，建议可以增加联动webhook来实现事件的实时告警发送；

### 建议的解决方案

1、用户管理跟权限管理可能会比较复杂，前期可以通过实现可以增加绑定多个mfa密钥来实现多用户登录；
2、webhook现成最简单的方案是企业微信、钉钉的机器人，微信公众号复杂点但是可以达到吸粉的成效；

**Comment by yrluke** [comment]
2的话官网有教程，可以尝试按照官网的教程自己diy

**Comment by yrluke** [comment]
雷池社区版这边主要是个人中小站长使用的，如果师傅的环境需要多位安全或者运维人员同时使用，可以去官网留个手机号，会有专人联系您试用企业版
