### ISSUE TITLE
[建议] 4.0.2 搜索引擎爬虫白名单强制添加不能删除

### ISSUE THREAD

**Issue by LisonFan** [chaitin/SafeLine#575]
### 背景与遇到的问题

![image](https://github.com/chaitin/SafeLine/assets/9424775/8877c9cd-bd78-41c4-bcb3-2db2905a0ab3)

只能禁用，不能删除

### 建议的解决方案

支持删除

**Comment by yrluke** [comment]
禁用就不会生效了，可以放心禁用
