### ISSUE TITLE
请问黑白名单的配置是怎么样的生效顺序？

### ISSUE THREAD

**Issue by LisonFan** [chaitin/SafeLine#576]
### 反馈内容

从上至下？还是从下至上？
能否提供修改顺序的功能？
![image](https://github.com/chaitin/SafeLine/assets/9424775/c31f4f3d-f6c6-4558-ba78-5c45801874c1)

**Comment by yrluke** [comment]
官网有相关文档，麻烦师傅移步官网

**Comment by yrluke** [comment]
https://waf-ce.chaitin.cn/docs/about/challenge

**Comment by yrluke** [comment]
规则间是OR啊，顺序没有意义

**Comment by saigyouyou** [comment]
> 规则间是OR啊，顺序没有意义

是否有办法改成按照顺序来判断命中。
比方说我rss的路径是白名单，不需要验证是不是爬虫，省的搜索引擎的爬虫被封。但是我又不想要攻击过我网站的ip访问网站的内容，就会很难办。
