### ISSUE TITLE
[Bug] IP组订阅无法提交保存

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#577]
### 问题描述

IP组订阅地址
https://ipv4.fetus.jp/

中国大陆：https://ipv4.fetus.jp/cn.txt
中国香港：https://ipv4.fetus.jp/hk.txt
中国台湾：https://ipv4.fetus.jp/tw.txt
中国澳门：https://ipv4.fetus.jp/mo.txt

【Python】循环请求20次，均成功。
![PixPin_2024-01-07_13-04-52](https://github.com/chaitin/SafeLine/assets/51684966/2be3180d-3ae0-4527-bc8a-d46c4afed0a6)
【雷池web订阅IP组】能加载订阅内容，但是提交保存报错“Get Reference Failed”（非必现，疯狂提交偶尔能成功）
![a2e8f2d69f0cebf0ecbb0b30c7fe4ed](https://github.com/chaitin/SafeLine/assets/51684966/9df6a9ab-8d1a-4844-a51d-1939f57dd923)

### 版本号

Version 4.0.2

### 复现方法

![a2e8f2d69f0cebf0ecbb0b30c7fe4ed](https://github.com/chaitin/SafeLine/assets/51684966/a8093691-4e69-475a-ac66-8e532b583104)

### 期望的结果

希望能正常提交保存订阅IP组

**Comment by yrluke** [comment]
我脚本测试了大约500次，没有复现成功
页面上测试了月20次，也没有复现成功
看了一下代码，盲猜是你的waf宿主机网络问题，你用的ipv4.fetus.jp在境外，由于一些原因导致访问失败，目前猜测是这样的
我的测试机器位于香港，目前测试没有这个问题
