### ISSUE TITLE
[Bug] 中文环境下，攻击方IP区域显示为英文

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#578]
### 问题描述

中文环境下，攻击方IP区域显示为英文

![image](https://github.com/chaitin/SafeLine/assets/51684966/8bee72c8-4331-44c3-b28d-f57f706f34eb)

### 版本号

Version 4.0.1

### 复现方法

![image](https://github.com/chaitin/SafeLine/assets/51684966/c810d63a-ab1f-4242-bb51-8357814eed0d)

### 期望的结果

中文环境下显示中文，全世界都在说中国话。

**Comment by upbeat-backbone-bose** [comment]
v4.0.2版本同样存在该问题
![image](https://github.com/chaitin/SafeLine/assets/438092/c28f5237-23f4-4e0e-93bd-254dbe1a67e9)
