### ISSUE TITLE
[建议] nginx反代的功能比较弱

### ISSUE THREAD

**Issue by baalchina** [chaitin/SafeLine#579]
### 背景与遇到的问题

不知道是产品策略还是？比如：

- 反代常见的负载均衡功能不支持（其实就是几条参数也不算什么高端配置）
- 证书不支持自动申请let'ecnrypt，得手动配置自己的
- 比如，不支持反代自己配置acl访问列表，这个也是几条参数的事情

我测试雷池是把它当做替代反代的，是否雷池开源版的推荐做法是把雷池放在反代和真实服务器中间？（中间是因为有https证书问题，我一般用反代来挂https证书）。总感觉这个架构属于多此一举了。。。

### 建议的解决方案

建议基础的nginx功能可以放开给用户使用

**Comment by Lorna0** [comment]
雷池的 web 管理涉及一部分 nginx 配置，这部分配置必须和后台的 nginx 配置保持同步，不然会出现数据冲突，进而出现各种不可预期的故障。所以雷池不会开放完整的 nginx 配置，目的就是优先保证 Web 管理端上涉及的配置正常工作。

目前雷池开放了一部分站点和全局的配置，有需要的话，可以根据官网相关文档修改。

如果认为开放的部分不足够，可以再提交反馈。例如：
* https://github.com/chaitin/SafeLine/issues/580

如果认为目前开放的部分需要界面 UI 配置，duplicate:
* https://github.com/chaitin/SafeLine/issues/167

另外，涉及的其他问题：
* 反代常见的负载均衡功能，目前已在专业版中官方正式支持
* 23 年 10 月的 3.6 版本证书就支持自动申请 let'ecnrypt 了，不知道师傅遇到了什么问题？如果是没有自动续期，后续我们有持续修复线上问题，可以升级一下试试
* “反代配置acl访问列表” 如果指的是 location 块里的 deny、allow 的话，目前是支持的，同上根据官方文档修改即可
