### ISSUE TITLE
default_server 站点（IP+Port）的拒绝访问建议

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/SafeLine#58]
当前存在2个域名，如下：
1、aaa.example.com 80
2、bbb.example.com 80
以上配置都正常且waf防护生效。
当使用http://waf-IP:80形式进行访问的时候，会落到以上两个站点的其中一个。
这并不是希望看到的效果，只希望通过域名+端口可以访问，IP+端口不允许访问。

希望厂家这边有什么好的办法来解决这种。

**Comment by zhuanmentiwen** [comment]
同上。

**Comment by zclaiqcc** [comment]
可以直接配置黑名单，Host 模糊匹配 「\d+.\d+.\d+.\d+(:80|443)?」，端口号改成自己的就可以了

**Comment by luweijun1992** [comment]
> 可以直接配置黑名单，Host 模糊匹配 「\d+.\d+.\d+.\d+(:80|:443)?」，端口号改成自己的就可以了

**Comment by Lorna0** [comment]
3.0 做成了默认配置：
![image](https://github.com/chaitin/safeline/assets/56920727/dc5e50fd-eae4-4b26-aa67-21cafb31acd5)

不过发版几天见到配错域名的用户超乎预料地多，而且这个错误不是特别好查到，之后可能会考虑做成个默认关闭的配置。

**Comment by luweijun1992** [comment]
> 3.0 做成了默认配置： ![image](https://user-images.githubusercontent.com/56920727/262640799-dc5e50fd-eae4-4b26-aa67-21cafb31acd5.png)
> 
> 不过发版几天见到配错域名的用户超乎预料地多，而且这个错误不是特别好查到，之后可能会考虑做成个默认关闭的配置。

也是可以，默认关闭。
然后在配置站点的页面增加个复选框选项：“只允许通过域名访问该站点”

**Comment by Lorna0** [comment]
3.3 将域名不正确的响应改为了 “网站不存在”，这样再遇到问题就比较好排查了：
![image](https://github.com/chaitin/SafeLine/assets/56920727/881ab8be-66ba-4429-8b61-119b8a7f24e6)

这个 issue 的问题基本上可以解决了。

**Comment by luweijun1992** [comment]
> 3.3 将域名不正确的响应改为了 “网站不存在”，这样再遇到问题就比较好排查了： ![image](https://user-images.githubusercontent.com/56920727/266542731-881ab8be-66ba-4429-8b61-119b8a7f24e6.png)
> 
> 这个 issue 的问题基本上可以解决了。

点赞~
这个提示页面能够自定义就更好了，毕竟页面不存在的提醒不属于WAF的。

**Comment by Lorna0** [comment]
> > 3.3 将域名不正确的响应改为了 “网站不存在”，这样再遇到问题就比较好排查了
> > 这个 issue 的问题基本上可以解决了。
> 
> 点赞~ 这个提示页面能够自定义就更好了，毕竟页面不存在的提醒不属于WAF的。

应该问题不大，这个页面正常只在域名没配对的情况下会看到，即只有管理员会看到，配好了就看不到了。
