### ISSUE TITLE
[建议] 新增server块自定义配置文件

### ISSUE THREAD

**Issue by QAQ5555** [chaitin/SafeLine#580]
### 背景与遇到的问题

需要增加批量设置客户端证书和验证功能，无法批量自定义server块配置，面板也无该选项建议增加

**Comment by devhaozi** [comment]
+1，还建议添加 http 块的自定义配置以便添加 map 之类的指令。

**Comment by QAQ5555** [comment]
我建议是学习nginx proxy manager的自定义配置功能
自定义 Nginx 配置
如果你是一个更高级的用户，你可能渴望额外的 Nginx 可定制性。

NPM 能够在不同位置包含不同的自定义配置片段。

您可以按如下方式添加自定义配置代码段文件：/data/nginx/custom

/data/nginx/custom/root.conf：包含在 nginx.conf 的末尾
/data/nginx/custom/http_top.conf：包含在主 http 块的顶部
/data/nginx/custom/http.conf：包含在主 http 块的末尾
/data/nginx/custom/events.conf：包含在事件块的末尾
/data/nginx/custom/stream.conf：包含在主流块的末尾
/data/nginx/custom/server_proxy.conf：包含在每个代理服务器块的末尾
/data/nginx/custom/server_redirect.conf：包含在每个重定向服务器块的末尾
/data/nginx/custom/server_stream.conf：包含在每个流服务器块的末尾
/data/nginx/custom/server_stream_tcp.conf：包含在每个 TCP 流服务器块的末尾
/data/nginx/custom/server_stream_udp.conf：包含在每个 UDP 流服务器块的末尾

**Comment by baalchina** [comment]
是的。当前雷池的反代功能太弱了，实际上很多功能都是nginx自带的就可以完成了，“应该”不牵涉到产品策略的问题吧。如果能gui配置最好，如果不行，开放配置文件也不是不可以。

**Comment by jamebal** [comment]
+1

**Comment by clqs803** [comment]
+1 上游服务器负载均衡这么久了都没做

**Comment by peng2289** [comment]
希望能增加自定义配置server的自定义，这样我的ssl双向证书认证也能走防火墙了，不然我还单独走nginx来实现
[https://github.com/chaitin/SafeLine/issues/655](url)

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
