### ISSUE TITLE
[Bug] SSL证书路径变了

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#581]
### 问题描述

SSL证书的路径变了
不知道哪个版本复制了一份证书出来
原来都是证书名+随机字符的，现在变成了cert_1，cert_2的形式

### 版本号

Version 4.0.2

### 复现方法

![image](https://github.com/chaitin/SafeLine/assets/51684966/fe838d00-d98b-487a-b931-4eae72846d53)

### 期望的结果

统一一下，是按顺序还是随机字符串

**Comment by yrluke** [comment]
之后是会按照cert_ID的形式了，之后不会变了
