### ISSUE TITLE
[建议] 建议添加对防护站点单个限速的设置，因为单个防护站点的流量过大会影响其他站点的访问

### ISSUE THREAD

**Issue by qq761861** [chaitin/SafeLine#582]
### 背景与遇到的问题

[建议] 建议添加对防护站点单个限速的设置，因为单个防护站点的流量过大会影响其他站点的访问

### 建议的解决方案

[建议] 建议添加对防护站点单个限速的设置，因为单个防护站点的流量过大会影响其他站点的访问

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/209
