### ISSUE TITLE
添加mobi后缀的域名时报错

### ISSUE THREAD

**Issue by jiespring** [chaitin/SafeLine#583]
### 问题描述

添加时弹出以下错误：
nginx conf reload error: nginx: [warn] could not build optimal server_names_hash, you should increase either
server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size
nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size:
512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size

### 版本号

4.0.2

### 复现方法

添加 cyqqqqpace.mobi

### 期望的结果

添加成功

**Comment by yrluke** [comment]
这个是因为你添加的域名过多导致的，请按照提示修改配置

**Comment by jiespring** [comment]
> 这个是因为你添加的域名过多导致的，请按照提示修改配置

我单独添加.mobi 还是错误，添加其他域名，是正常的。

**Comment by jiespring** [comment]
![Quicker_20240109_143917](https://github.com/chaitin/SafeLine/assets/12294630/5d435d0f-fdc3-4683-8784-ed880b68c02c)

**Comment by yrluke** [comment]
不妨按照提示试试呢？

**Comment by jiespring** [comment]
> 不妨按照提示试试呢？

怎么样修改？
你们的文档不全面，试过还是错误：
1、在修改 /data/safeline/resources/nginx/custom_params/backend_1文件内容为
server_names_hash_max_size      1024;  
server_names_hash_bucket_size   512; 
或者重命名backend_1为IF_backend_1 
nginx未报错，waf还是出现原来的错误。

2、修改resources/nginx/proxy_params文件，添加上面2行代码后nginx报错。

**Comment by jiespring** [comment]
问题已解决：重新执行升级命令，强制刷新waf页面。（错误可能跟hash无关，因为其他域名可以添加。）
