### ISSUE TITLE
安装目录下配置文件compose.yml和.env文件不在了

### ISSUE THREAD

**Issue by RyeZJCWhiskey** [chaitin/SafeLine#589]
### 反馈内容

为什么在我部署好waf之后一段时间后登陆到服务器上发现安装目录下compose.yml和.env文件都不在了，但是服务还正常运行。能恢复吗，尤其是看不到pgsql的密码了，也没办法docker compose down和docker compose up -d重启waf了

**Comment by yrluke** [comment]
docker compose ls看一下路径，盲猜是进错路径了
