### ISSUE TITLE
[建议] 免费证书申请增加 DNS-01 验证支持，并支持通配符证书申请

### ISSUE THREAD

**Issue by best** [chaitin/SafeLine#590]
### 背景与遇到的问题

1. 免费证书仅支持 HTTP-01 方法，在多节点部署时灵活性较差（如主备部署时仅主节点可以申请免费证书）；
2. HTTP-01 下无法支持通配符证书申请，多站点情况下需要多次申请证书无法，易用性不足。

### 建议的解决方案

1. “免费证书申请” 支持 DNS-01 方法；
2. DNS-01 方法支持申请通配符证书；
3. DNS-01 方法支持阿里云DNS、DNSPod、CloudFlare 等国内使用广泛的 DNS 厂商。

**Comment by Kendarou** [comment]
支持，因为没有80和443端口可用，现在在雷池部署的服务器上使用acme.sh自动申请泛域名证书，然后每隔2个月手动更新到雷池里，真的是很麻烦。acme.sh本来是支持自动安装到nginx并自动重载的。

**Comment by yrluke** [comment]
既然都已经是多节点部署了，要不要考虑来一套企业版，安全公司都要饿死了

**Comment by best** [comment]
> 既然都已经是多节点部署了，要不要考虑来一套企业版，安全公司都要饿死了

没办法呀，个人爱好拿来玩一玩上不了企业版，但是你们的专业版肯定支持，昨晚上在你们的直播也刷了些礼物支持。

**Comment by best** [comment]
希望如果开源版本因为人力无法做到的话，你们的专业版可以支持 DNS-01 方法

**Comment by Kendarou** [comment]
我觉得DNS验证的方式恰恰是更适合于个人用户吧，企业用户都是购买商业证书而不会使用这种稳定性和兼容性都很低的免费证书，以及需要自行进行DNS验证。acme申请的免费的泛域名证书，只支持3个月，需要频繁更新，有哪个生产环境的站点会使用这种证书？

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/563
