### ISSUE TITLE
[建议] 云图的扫描节点IP加入白名单

### ISSUE THREAD

**Issue by Nouko61** [chaitin/SafeLine#594]
### 背景与遇到的问题

云图的扫描节点一直告警，部分节点甚至在社区恶意IP情报黑名单里

### 建议的解决方案

云图的扫描节点IP加入搜索引擎爬虫白名单

**Comment by Lorna0** [comment]
云图的扫描不属于常规的搜索引擎爬虫，不一定所有用户都愿意加白。

感觉还是让大家自己来按需加白比较好。

**Comment by Lorna0** [comment]
和云图的开发者确认了一下，云图的扫描节点有很多，而且会定期换，不需要也不建议特地加白。用的时候当云图不存在就可以，云图会根据扫描结果判断是否存在暴露面。
