### ISSUE TITLE
[建议] 希望可以实现自动ssl跳转

### ISSUE THREAD

**Issue by 52lemon6** [chaitin/SafeLine#595]
### 背景与遇到的问题

添加站点的时候希望能设置是否开启强制ssl跳转的一个按钮

**Comment by DeronW** [comment]
![image](https://github.com/chaitin/SafeLine/assets/780596/a6247766-f3d6-4a1c-9edf-5d109a90ae2d)

这个功能可以解决问题吗？

**Comment by Lorna0** [comment]
时间有点久，先关闭了，仍有问题的话可以再反馈。
