### ISSUE TITLE
[Bug] 域名和证书相同在证书页面仍会提示域名不匹配

### ISSUE THREAD

**Issue by 52lemon6** [chaitin/SafeLine#596]
### 问题描述

域名和证书相同在证书页面仍会提示域名不匹配
![image](https://github.com/chaitin/SafeLine/assets/40059643/a1ebe4ec-4e6f-4bcd-921e-9cc7408a950f)

### 版本号

4.0.2

### 复现方法

1，先申请域名A的证书并创建域名A将域名A的证书绑定
2，创建站点使用域名B，使用域名A的证书
3，申请域名B的证书
4，将域名B绑定的A域名的证书更换为B域名的证书
5，在证书页面仍会提示域名不匹配

### 期望的结果

希望不会在显示不匹配了

**Comment by Lorna0** [comment]
最新环境没有复现该问题了，师傅再试试呢。

**Comment by fslongjin** [comment]
> 最新环境没有复现该问题了，师傅再试试呢。

我今天新安装的版本仍然有这个问题。复现方法不太一样。

触发方式：从宝塔面板的网页上面复制这样的内容：
```
(网址前面貌似有1个tab和1个空格）example.com
```

然后粘贴到雷池的ssl申请页面，接着申请完证书后，把这个地址粘贴到添加站点的页面。

然后就能触发这个问题。

**Comment by Lorna0** [comment]
@fslongjin 在 5.6.2 版本中进行了修复，可以确认一下。
