### ISSUE TITLE
[建议]添加高频拦截和人机验证拦截的IP排名

### ISSUE THREAD

**Issue by zhxind** [chaitin/SafeLine#597]
### 背景与遇到的问题

高频访问拦截和人机验证拦截添加今天TOP50 IP排名情况，方便用户处理CC等攻击是能在更上层设备进行IP拦截，同时也方便用户了解当前攻击情况

### 建议的解决方案

高频访问拦截和人机验证拦截添加今天TOP50 IP排名榜单，并给出每个TOP 50 IP的具体拦截次数

**Comment by jssolo** [comment]
这个想法不错，顶一顶

**Comment by Lvshujun0918** [comment]
我觉得不错！

**Comment by Lorna0** [comment]
relate to:
* https://github.com/chaitin/SafeLine/issues/415

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
