### ISSUE TITLE
防护站点显示资源被访问的请求数，只有总的路径对应的资源请求数，为什么不能根据域名分类再显示各个域名哪些路径被访问了多少量

### ISSUE THREAD

**Issue by gitamorning** [chaitin/SafeLine#599]
### 背景与遇到的问题

我添加了一个业务A名称的站点防护，域名定于的*.admin.com，虽然如此，当我点进去与业务A的防护情况，发现里面只有笼统的路径-请求量，我没办法看到a.admin.com哪些路径被攻击了，攻击量是多少(尽管我在/api/ApiAsset?id=x的接口里发现了，响应的json数据里遍其实是按照域名分类号了路径和供给量的）但是前端就是没显示

### 建议的解决方案

按照域名分别显示攻击路径，和供给量

**Comment by Lorna0** [comment]
正常情况下一个站点对应的是一个实际的业务，所以不需要再按域名分类了。

如果你的站点和实际的业务并不一致，可能你说的是：https://github.com/chaitin/SafeLine/issues/365

**Comment by gitamorning** [comment]
> 正常情况下一个站点对应的是一个实际的业务，所以不需要再按域名分类了。
> 
> 如果你的站点和实际的业务并不一致，可能你说的是：
> 
> * [[建议] 站点详情易用度问题 / 通配站点的图标和业务资源会合并显示的问题 #365](https://github.com/chaitin/SafeLine/issues/365)

对，我和他说的一个情况。在api/assets的接口里其实发现data键下有各个域名分别对应的路径和攻击访问量，但是在前端却上统一列出路径-攻击量，没法分清哪些路径是属于哪个域名的，事实上正常的业务系统，常常都是一个业务/系统，由很多域名对应服务支撑，这些服务又是被不同的研发团队所开发，知道哪些路径属于哪些域名，这点对用户来说很重要

**Comment by Lorna0** [comment]
> 事实上正常的业务系统，常常都是一个业务/系统，由很多域名对应服务支撑，这些服务又是被不同的研发团队所开发，知道哪些路径属于哪些域名，这点对用户来说很重要

没太理解，“一个业务/系统” 是指一个业务服务比如一个 OA、一个博客 吗，啥一个业务要提供多个域名、多个服务呀？

如果这些域名都是不一样的业务，而且没那么多的话，可以直接把它们全部分开配置：添加多个站点，每个站点分别对应一个域名，上游服务器分开的话就分开配置，是一个的话就配置成同一个，就可以完全解决了。


 https://github.com/chaitin/SafeLine/issues/365 的问题在于站点太多且变化快，所以希望按 * 统一添加站点，进而希望反向代理的配置和业务站点的管理展示分开。如果是这个问题的话，可以集中到  https://github.com/chaitin/SafeLine/issues/365 一起讨论，这个我们还没有想到很好的办法（如果想要保持现有的易用性），如果你有什么点子，欢迎在那边评论。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
