### ISSUE TITLE
[Bug] 添加防护站点时，提示解析参数错误 rules compile error, please check your params

### ISSUE THREAD

**Issue by lxk1066** [chaitin/SafeLine#601]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/53557084/a5042f38-6afb-4904-bad2-8ca0f15646c7)

1. 第一次添加某个端口时，点击提交会提示解析参数错误，同时接口报错如下：
![3d6a4a94cc65be72acdfcd901677a4e](https://github.com/chaitin/SafeLine/assets/53557084/8f22e46a-e3e1-44b7-b1cf-62102326260d)

2. 如果此时再点一次提交按钮，会提示80端口占用，如下：
![image](https://github.com/chaitin/SafeLine/assets/53557084/2827236e-2b9f-4eb0-adc4-707d2c1499c0)

3. 接着在服务器上使用lsof -i:80 查看端口占用，发现有nginx进程，猜想是雷池自己处理的，使用kill -9 杀掉进程后，可以再次点击提交按钮，又会提示解析参数错误，我反复测试过多次，也换了好几个监听端口，但是结果都一样。

我的前端站点是使用nginx反向代理的本地HTML目录，同时二级域名和多个三级域名都指向了同一台服务器的80端口，比如：nightkitty.top、test.nightkitty.top等等这些域名都会经过我的前端服务器的nginx，通过配置nginx的server为不同的域名地址实现一天服务器分配多个子域名，我不知道是不是这个东西影响到了雷池，但我猜大概率不是。

### 版本号

4.0.2

### 复现方法

复现方法已经在上面说过了，使用kill -9 杀掉占用端口进程后，第一次提交会提示解析参数错误，第二次提交会提示端口占用，测试多个端口都一样。

### 期望的结果

已经被折腾麻了，死马当活马医吧

**Comment by yrluke** [comment]
docker ps看一下是不是有服务挂了

**Comment by lxk1066** [comment]
> docker ps看一下是不是有服务挂了

![image](https://github.com/chaitin/SafeLine/assets/53557084/cc58262b-498e-4940-a69d-d8ef445f7663)
没看出来哪个挂了

**Comment by ylwzbk** [comment]
FVM 一直显示重启  你这机器是不是内存不够还是之前改了什么

**Comment by yrluke** [comment]
<img width="800" alt="截屏2024-01-11 下午7 47 46" src="https://github.com/chaitin/SafeLine/assets/42405631/690e1f0c-9398-4bfe-902a-cd25ec9880a4">
docker logs -tf safeline-fvm
看看，你是不是docker版本过低的那哥们

**Comment by lxk1066** [comment]
> <img alt="截屏2024-01-11 下午7 47 46" width="800" src="https://private-user-images.githubusercontent.com/42405631/295901461-690e1f0c-9398-4bfe-902a-cd25ec9880a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzM5OTAsIm5iZiI6MTcwNDk3MzY5MCwicGF0aCI6Ii80MjQwNTYzMS8yOTU5MDE0NjEtNjkwZTFmMGMtOTM5OC00YmZlLTkwMmEtY2QyNWVjOTg4MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDExNDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjY5MWQ0ZDNmN2Q3ZmEwM2IwZmU0ZTc4NjAwODYxNmQ3NWY0ZWFlMDQ1ZDA4NjcyNWQ2OWI0NGRlODRlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._7pdS5Qv2EH561v2GWzapEJjFVBZqNzJty3TkBK7iZE"> docker logs -tf safeline-fvm 看看，你是不是docker版本过低的那哥们


![image](https://github.com/chaitin/SafeLine/assets/53557084/b459fbf7-26ea-4c83-8c77-c063571a7b55)

这里好像有个错误

**Comment by lxk1066** [comment]
> <img alt="截屏2024-01-11 下午7 47 46" width="800" src="https://private-user-images.githubusercontent.com/42405631/295901461-690e1f0c-9398-4bfe-902a-cd25ec9880a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzM5OTAsIm5iZiI6MTcwNDk3MzY5MCwicGF0aCI6Ii80MjQwNTYzMS8yOTU5MDE0NjEtNjkwZTFmMGMtOTM5OC00YmZlLTkwMmEtY2QyNWVjOTg4MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDExNDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjY5MWQ0ZDNmN2Q3ZmEwM2IwZmU0ZTc4NjAwODYxNmQ3NWY0ZWFlMDQ1ZDA4NjcyNWQ2OWI0NGRlODRlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._7pdS5Qv2EH561v2GWzapEJjFVBZqNzJty3TkBK7iZE"> docker logs -tf safeline-fvm 看看，你是不是docker版本过低的那哥们

![image](https://github.com/chaitin/SafeLine/assets/53557084/453ebbce-6faa-41e2-b63a-63f623acd53d)

**Comment by lxk1066** [comment]
> FVM 一直显示重启 你这机器是不是内存不够还是之前改了什么

大概率是内存不够了，之前在另一台服务器上跑得好好的

**Comment by lxk1066** [comment]
> <img alt="截屏2024-01-11 下午7 47 46" width="800" src="https://private-user-images.githubusercontent.com/42405631/295901461-690e1f0c-9398-4bfe-902a-cd25ec9880a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzY5NDUsIm5iZiI6MTcwNTAzNjY0NSwicGF0aCI6Ii80MjQwNTYzMS8yOTU5MDE0NjEtNjkwZTFmMGMtOTM5OC00YmZlLTkwMmEtY2QyNWVjOTg4MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA1MTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzVmZTcyYTQ1MWZjNGEyMWFhMDBmNGIzZmMxZTQ5NTBmYzBhOTUxYmQ3MjUzMWRjMTBlMmUxZDNlNjUwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kXELE28oK5qUYtWOr7o8YGu2upPnxwUm76hHYF3D7ns"> docker logs -tf safeline-fvm 看看，你是不是docker版本过低的那哥们

更新docker版本后，之前的问题解决了，但是又有新的问题：
![image](https://github.com/chaitin/SafeLine/assets/53557084/faefc058-de87-40ff-856f-e7e8d3fac194)
这个镜像启动一直有问题，重启了也不行。Web UI可以添加防护站点了，但是当我尝试模拟攻击请求时，貌似雷池直接罢工了，直接拒绝访问，按照示例应该展示拦截的页面：
![image](https://github.com/chaitin/SafeLine/assets/53557084/0227cd1c-77cb-49e7-ad77-35a8384c5e93)
