### ISSUE TITLE
我根据官方文档将waf日志通过fluentd容器吐到syslog server时容器总是报错

### ISSUE THREAD

**Issue by RyeZJCWhiskey** [chaitin/SafeLine#603]
### 反馈内容

fluent.conf文件配置如下：
![image](https://github.com/chaitin/SafeLine/assets/33591840/1a6d3629-3884-4a8a-ba92-f4ae6fbf7139)
Dockerfile如下
![image](https://github.com/chaitin/SafeLine/assets/33591840/87bcfb0d-c981-4a35-aa46-71db6b41e28c)

容器日志如下
![image](https://github.com/chaitin/SafeLine/assets/33591840/a1504aa0-4a31-4295-b4c1-4109e90f063f)
![image](https://github.com/chaitin/SafeLine/assets/33591840/676eae51-68f7-480f-a157-6d32669193b8)

请教大家何解？

**Comment by yrluke** [comment]
我猜是因为这个容器里面没有这个文件，这个你最好volume出来，防止因为容器挂了导致重复grep的问题

**Comment by RyeZJCWhiskey** [comment]
容器中有这个文件
![image](https://github.com/chaitin/SafeLine/assets/33591840/48ceaa2e-8318-4ee8-a538-bd529dfe7cab)

**Comment by zzzskd** [comment]
1. 格式问题， `sql_state` 文件不能为空文件
2. 文档里给的 dockerfile 编译出镜像运行时会报错缺依赖（不能执行 `apk del` ）

具体操作步骤：
1. 编写镜像，并打包，此时镜像内无配置文件
  ```Dockerfile
  FROM fluent/fluentd:v1.16-1
  USER root
  RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
  RUN apk add --no-cache --update --virtual .build-deps \
          sudo build-base ruby-dev \
   && apk add libpq-dev \
   && apk add libpq \
   && apk add tzdata \
   && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
   && echo "Shanghai/Asia" > /etc/timezone \
   && apk del tzdata \
   && fluent-gem install fluent-plugin-sql --no-document \
   && sudo gem install pg --no-document \
   && sudo gem install fluent-plugin-remote_syslog \
   && sudo gem sources --clear-all \
   && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
  
  USER fluent
  ```
2. 创建相关目录
  ```shell
  cd /data/safeline/
  mkdir fluent
  chmod 777 fluent
  cd fluent
  ```
3. 编写配置文件，将配置文件保存为 `/data/safeline/fluent/fluent.conf`, 收集两个事件表中的数据，并转化为 json 格式，分别增加 `log_type` 字段用于区分 ，detail 表中的值 为 detail，basic 中的值为 basic
  ```
  <source>
    @type sql
    host safeline-postgres
    port 5432
    database safeline-ce
    adapter postgresql
    username safeline-ce
    password YOUR_PASSWORD
    
    select_interval 60s  # optional
    select_limit 500     # optional
  
    state_file /var/run/fluentd/sql_state
    <table>
       table mgt_detect_log_basic
       tag basic
       update_column timestamp
    </table>
  
    <table>
       table mgt_detect_log_detail
       tag detail
       update_column id
    </table>   
  </source>
  
  <filter *>
    @type record_transformer
    <record>
      log_type ${tag}
    </record>
  </filter>
  
  <match *>
    @type remote_syslog
    protocol tcp
    host 10.192.70.122
    port 5532
    packet_size 999999
    <format>
      @type json
    </format>
  </match>
  ```
4. 启动容器 `docker run -d --restart=always --name safeline-fluentd --net safeline-ce -v ./:/var/run/fluentd/ -v ./fluent.conf:/fluentd/etc/fluent.conf fluentd-waf:no_config`，将配置文件 `fluent.conf` 及 `sql_state` 文件都映射进容器

**Comment by RyeZJCWhiskey** [comment]
感谢分享解决方法
