### ISSUE TITLE
[Bug] 英文状态下，Events页面对齐问题

### ISSUE THREAD

**Issue by Coalmeow** [chaitin/SafeLine#604]
### 问题描述

目前此处文字为左对齐，其他场景都是居中对齐
附上截图
![QQ截图20240111202700](https://github.com/chaitin/SafeLine/assets/115446771/64e29a66-f4da-4fbb-ace3-7e0e054f0e73)
![QQ截图20240112002822](https://github.com/chaitin/SafeLine/assets/115446771/8551c5c8-6d6c-4018-98e5-4c07bafdb8a9)

### 版本号

4.1.1

### 复现方法

打开Events页面，切换到LOGS选项卡

### 期望的结果

LOGS文字居中对齐

**Comment by DeronW** [comment]
@Coalmeow 细致 ~

**Comment by DeronW** [comment]
@Coalmeow  下个版本更新

**Comment by DeronW** [comment]
@Coalmeow  4.2.0 版本已经修复这个问题
