### ISSUE TITLE
[Bug] 升级到4.1.1后，mario 镜像不断重启

### ISSUE THREAD

**Issue by yankeeshcn** [chaitin/SafeLine#607]
### 问题描述 Mario 镜像不断重启

我是使用 docker-compose 来升级雷池WAF，升级之前是3.1.2，升级到4.1.1
Docker 镜像safeline-mario反复重启
![safeline-mario](https://github.com/chaitin/SafeLine/assets/45564413/b807647b-3959-41a6-9abb-761b934dabc2)

日志报错如下：
time="2024/01/12 10:43:31" level=fatal msg="Failed to start persistence after 0 times retry" error="REDIS_URL is required" file=utils.go func=/patronus/safeline-ce/mario/server/registry.Boot line=38
time="2024/01/12 10:43:33" level=fatal msg="Failed to start persistence after 0 times retry" error="REDIS_URL is required" file=utils.go func=/patronus/safeline-ce/mario/server/registry.Boot line=38
time="2024/01/12 10:43:37" level=info msg="service:plumber summary  start" file=handler.go func="/patronus/safeline-ce/mario/server/plumber.(*Handler).Start" line=98
time="2024/01/12 10:43:37" level=fatal msg="Failed to start persistence after 0 times retry" error="REDIS_URL is required" file=utils.go func=/patronus/safeline-ce/mario/server/registry.Boot line=38
time="2024/01/12 10:43:44" level=fatal msg="Failed to start persistence after 0 times retry" error="REDIS_URL is required" file=utils.go func=/patronus/safeline-ce/mario/server/registry.Boot line=38
time="2024/01/12 10:43:58" level=info msg="service:plumber summary  start" file=handler.go func="/patronus/safeline-ce/mario/server/plumber.(*Handler).Start" line=98
time="2024/01/12 10:43:58" level=fatal msg="Failed to start persistence after 0 times retry" error="REDIS_URL is required" file=utils.go func=/patronus/safeline-ce/mario/server/registry.Boot line=38
time="2024/01/12 10:44:24" level=fatal msg="Failed to start persistence after 0 times retry" error="REDIS_URL is required" file=utils.go func=/patronus/safe:

### 版本号

4.1.1

### 复现方法

从3.1.2 升级到4.1.1

### 期望的结果

解决数据库镜像的问题。

**Comment by yrluke** [comment]
还有更多的报错信息吗，多截一点，目前没看到可能的原因

**Comment by yrluke** [comment]
麻烦再提供一下logs/mario/mario.log

**Comment by yankeeshcn** [comment]
> 麻烦再提供一下logs/mario/mario.log

[mario.log](https://github.com/chaitin/SafeLine/files/13915733/mario.log)
已经上传，请查看。谢谢

**Comment by yankeeshcn** [comment]
@yrluke 请问有没有什么进展？

**Comment by xbingW** [comment]
released in 6.4.0
