### ISSUE TITLE
[建议] 攻击事件日志清理功能

### ISSUE THREAD

**Issue by x8899** [chaitin/SafeLine#608]
### 背景与遇到的问题

攻击事件日志清理功能 
![QQ截图20240112152722](https://github.com/chaitin/SafeLine/assets/156409175/c2e0bdf2-2667-4c05-b53b-bd233133d1ed)

### 建议的解决方案

建议可以设置定时清理日志功能 或者一键清理命令 不然日积月累下来服务器硬盘空间会占用很多  望采纳！

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/63

可以集中到一个issue讨论和跟进
