### ISSUE TITLE
[Bug] 上游无法解析sni信息

### ISSUE THREAD

**Issue by ChaojuWang** [chaitin/SafeLine#609]
### 问题描述

雷池上游设置为apisix搭建的多站点https反代，流量经过雷池后，apisix无法解析出其中的sni信息，无法将包代理给apisix的上游站点
雷池监听ssl请求，雷池和apisix配置的是同一个证书
雷池日志：
![image](https://github.com/chaitin/SafeLine/assets/14054604/7b2500fa-516f-44c1-9d69-9ff7f85fb6d8)
apisix报错如下
![image](https://github.com/chaitin/SafeLine/assets/14054604/89bd2ff0-9fb2-4ef2-b99c-a67111eff161)

### 版本号

4.1.1

### 复现方法

1. 部署apisix 基于域名的https反代
2. 部署雷池
3. 雷池添加ssl站点，上游为apisix ip+端口，证书和apisix相同
4. 通过雷池访问，提示源站点错误

### 期望的结果

流量能通过雷池和apisix正常访问后端站点

**Comment by ChaojuWang** [comment]
在`resources/nginx/proxy_params`中添加如下配置以传递sni信息后问题解决
```
proxy_ssl_server_name on;
proxy_ssl_name $http_host;
```

**Comment by DeronW** [comment]
@ChaojuWang  4.2.0 版本已经添加了，可以升级后使用
