### ISSUE TITLE
[Bug]标题显示错误

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#610]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/41245552/ee1527a5-eb0b-4961-af16-db73b75f2fde)
如上图，在**防护配置 / 人机验证**页面中点击删除，询问框标题不对

### 版本号

4.1.1

### 复现方法

1. 进入防护配置 / 人机验证页面
2. 选择任意一个条件点击删除

### 期望的结果

修改正确

**Comment by DeronW** [comment]
@Lvshujun0918 4.2.0 版本已经修复这个问题
