### ISSUE TITLE
腾讯云外网访问失败

### ISSUE THREAD

**Issue by dabai2017** [chaitin/SafeLine#611]
### 反馈内容

我腾讯云防火墙给了9443允许，但外网访问不进雷池，各位大佬知道是咋回事吗，或者应该先从哪排查。80是正常的。

**Comment by dabai2017** [comment]
也有可能是docker网络问题

**Comment by DeronW** [comment]
@dabai2017  如果是端口访问不了，一般是防火墙没有放行，可以这样测试，自己开一个 9443 端口的测试服务，看能不能正常访问

**Comment by dabai2017** [comment]
感谢回复，已经可以了，问题是docker好像是没安装完整，但safeline显示已经安装docker，我把卸载干净自己装的docker，再装的safeline就好了












BAI
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chaitin/SafeLine] 腾讯云外网访问失败 (Issue #611)




 
@dabai2017  如果是端口访问不了，一般是防火墙没有放行，可以这样测试，自己开一个 9443 端口的测试服务，看能不能正常访问
