### ISSUE TITLE
[建议] 建议添加IPV6的归属地显示

### ISSUE THREAD

**Issue by WJHXD1B** [chaitin/SafeLine#612]
### 背景与遇到的问题

建议添加IPV6的归属地显示，可以更直观的看到IP信息

**Comment by DeronW** [comment]
@WJHXD1B  有推荐的 IPv6 地理库吗？ 现在我们只有 IPv4 的

**Comment by cmradix** [comment]
> @WJHXD1B 有推荐的 IPv6 地理库吗？ 现在我们只有 IPv4 的

MaxMind GeoLite2或者ipip吧

**Comment by WJHXD1B** [comment]
> @WJHXD1B 有推荐的 IPv6 地理库吗？ 现在我们只有 IPv4 的

IPIP或者是
api.aa1.cn/special/chinaip/

**Comment by Lorna0** [comment]
> MaxMind GeoLite2或者ipip吧

> IPIP或者是 api.aa1.cn/special/chinaip/

IPIP 的 IPv6 似乎必须付费，社区版没能力上....
api.aa1.cn/special/chinaip/ 上的几个似乎是一次性查询接口，不方便集成
MaxMind GeoLite2 听说对 ipv6 的精度一般，我们改天试试

**Comment by WJHXD1B** [comment]
> > MaxMind GeoLite2或者ipip吧
> 
> > IPIP或者是 api.aa1.cn/special/chinaip/
> 
> IPIP 的 IPv6 似乎必须付费，社区版没能力上.... api.aa1.cn/special/chinaip/ 上的几个似乎是一次性查询接口，不方便集成 MaxMind GeoLite2 听说对 ipv6 的精度一般，我们改天试试

感谢，辛苦了

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
