### ISSUE TITLE
[建议] 人机验证拦截的数据希望攻击日志能够查看

### ISSUE THREAD

**Issue by peng2289** [chaitin/SafeLine#613]
### 背景与遇到的问题

现在人机拦截的数据只显示一个数字，不利于分析攻击情况，因为设置了关键字拦截和正则拦截，不清楚具体的攻击形式，不好根据数据去完善程序，希望能正常显示拦截的攻击日志

### 建议的解决方案

人机拦截的数据能正常查看攻击日志，而不是只是一个数量【今日验证情况】，特别是放假，看不到攻击情况

**Comment by DeronW** [comment]
@peng2289  具体都希望查看哪些人机拦截的数据？

**Comment by Lorna0** [comment]
人机验证拦截的更多是扫描器，请求量可能非常大，记录全量日志的话可能会影响到 waf 的性能，或者占用过多的设备资源

**Comment by peng2289** [comment]
![image](https://github.com/chaitin/SafeLine/assets/18732497/e1f19a07-0138-48a0-b93a-6e767c2666a5)


> @peng2289 具体都希望查看哪些人机拦截的数据？

主要是注入类的，扫描的可能意义不大，注入的，有些可能只是没找到入口，并不代表我的没问题，之前我发现有些疑似注入的也放行了，可以在人机验证时加入记录日志选项，这样就更加灵活了

**Comment by peng2289** [comment]
> 人机验证拦截的更多是扫描器，请求量可能非常大，记录全量日志的话可能会影响到 waf 的性能，或者占用过多的设备资源

可以在添加人机验证时，自己勾选是否记录拦截日志，有些配置确实不需要记录日志，有些我是 拦截注入类的可能需要记录下日志，方便分析注入漏洞情况进行分析

**Comment by xbingW** [comment]
最新版 6.9.0 已支持显示人机记录
