### ISSUE TITLE
[Bug] 4.1.1 版本更新后卡顿

### ISSUE THREAD

**Issue by topsage** [chaitin/SafeLine#614]
### 问题描述

safeline-mario  cpu波动比较大，前端页面访问所有标签页面卡顿2-3秒，应该非个人环境问题，官方demo也是卡顿

### 版本号

4.1.1 

### 复现方法

![25a7300f9eb91811c643fd82655c1eb](https://github.com/chaitin/SafeLine/assets/51810073/9286f67f-0d4f-4f69-ba52-db8daf1e6b85)
![cfe42aa89780c2aaaaa3d1f3994f6f7](https://github.com/chaitin/SafeLine/assets/51810073/20d78893-08e4-4f5c-8982-6f8c690653d4)

### 期望的结果

优化mario容器资源占用，加速页面访问

**Comment by yrluke** [comment]
mario已经在优化的列表中了，但是访问卡顿我这边并没有复现
