### ISSUE TITLE
[建议] 请求let's encrypt DNS验证模式和相应的泛解析申请支持

### ISSUE THREAD

**Issue by cmradix** [chaitin/SafeLine#615]
### 背景与遇到的问题

let's encrypt的HTTP模式有单个IP每3小时只允许申请5份证书的限制。

### 建议的解决方案
因此请求加入DNS验证模式和相应的泛解析证书管理与续订，供用户选择，参考行业及相关产品。
可能需要存储解析服务提供商的用户认证信息，但仍应作为一种可能选项提供用户，供其视需要选择。

我需要以下DNS服务：
Cloudflare
DNSPod

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/563
