### ISSUE TITLE
[建议] 建议高频访问限制可以单独制定参数做防御

### ISSUE THREAD

**Issue by luanande** [chaitin/SafeLine#619]
### 背景与遇到的问题

例如我全站cc访问量60秒100次就拦截 但是我有些路径比如github.com/login这个登陆路径设置成60秒访问10次拦截，该功能可以适用于所有没有部署前后端分离的站点，登陆接口设置访问量过大会导致爆破行为，而站点设置访问量过小而又会导致误拦截正常访问用户。

### 建议的解决方案

建议高频访问限制可以单独制定参数做防御

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/209
