### ISSUE TITLE
[建议] 当前版本刚果（金）和刚果（布）的国名汉化不完全

### ISSUE THREAD

**Issue by Coalmeow** [chaitin/SafeLine#620]
### 背景与遇到的问题

![QQ截图20240115202638](https://github.com/chaitin/SafeLine/assets/115446771/947b4b7d-aca5-45df-9605-832bd3a6ddbb)
![QQ截图20240115202632](https://github.com/chaitin/SafeLine/assets/115446771/eb1590a3-c458-4dfa-a374-deeef00b9d3e)

截图中的Dem. Rep. Congo 是刚果民主共和国，首都是金沙萨，国内一般使用刚果（金）作为其国名简称，目前雷池对应的中文字段为“刚果”。
而另一个截图中的Congo是刚果共和国，首都是布拉柴维尔，国内使用刚果（布）作为其国名简称，目前雷池没有对刚果（布）的字段进行汉化，直接显示了原文Congo

### 建议的解决方案

建议对这两个国家的文本使用刚果（金）、刚果（布）做区分

**Comment by DeronW** [comment]
@Coalmeow  兄弟，你是怎么发现这个问题的？

**Comment by Coalmeow** [comment]
> @Coalmeow 兄弟，你是怎么发现这个问题的？

每次都是我发这种奇奇怪怪的问题，每次都是你回哈哈哈哈哈 @DeronW

**Comment by DeronW** [comment]
@Coalmeow 4.2.0 版本已经修复这个问题
