### ISSUE TITLE
[Bug] IP组订阅手动更新为限制的1001，每天自动更新则数量是正常

### ISSUE THREAD

**Issue by zonas0574** [chaitin/SafeLine#621]
### 问题描述

 IP组订阅手动更新为限制的1001，每天自动更新则数量是正常
![2](https://github.com/chaitin/SafeLine/assets/6995509/55384bf7-82fc-47c1-9080-b558abd27ee4)
![1](https://github.com/chaitin/SafeLine/assets/6995509/d8613e41-851e-43ea-84f9-3ee197f5c258)

### 版本号

4.1.1

### 复现方法

1. 每天凌晨自动更新，数量正常
2. 当手动点击更新则限制到1001
3. 第二天又恢复到正常

### 期望的结果

希望一直是没限制数量

**Comment by zonas0574** [comment]
相似issues #602

**Comment by ezjbc** [comment]
![image](https://github.com/chaitin/SafeLine/assets/51684966/797894f0-00d4-4baf-bb3e-06f9755bc235)
上限993

**Comment by gearfox** [comment]
是的，显示最多1001

**Comment by zonas0574** [comment]
我更新版本后，每日更新也变成1001，然后增加专业版，可以按国家或地区进行黑名单，在我看来是反向修复bug，需要花钱才能享受，自定义订阅故意限死

**Comment by zonas0574** [comment]
专业版可以按国家或地区进行黑白名单，刚好满足我要求，收费能理解，我先将就着用，我也考虑分多组订阅，这个bug修复无望 @gearfox  @ezjbc
