### ISSUE TITLE
[Bug] Captcha 

### ISSUE THREAD

**Issue by mvh97hg** [chaitin/SafeLine#623]
### 问题描述

Safeline Waf CE indexes the site on search engines
Safeline Waf CE shows up on google search results when searching by domain name

### 版本号

Version 4.1.1

### 复现方法

Safeline Waf CE indexes websites on search engines when captcha is enabled

![image](https://github.com/chaitin/SafeLine/assets/88535301/1f0b8ba8-6712-4d87-9511-5b54f0d02c11)

### 期望的结果

Search results are not affected by WAF

**Comment by Lorna0** [comment]
Enabling this Built-in Rules might help, it just means "Search engine crawler whitelist", including crawler IPs published by Google  (translation has something wrong and we'll fix it later https://github.com/chaitin/SafeLine/discussions/592): 
![image](https://github.com/chaitin/SafeLine/assets/56920727/950471b5-78fe-40e7-8536-12d12f7bc18f)
