### ISSUE TITLE
[建议] 希望可以支持经过身份验证的来源拉取

### ISSUE THREAD

**Issue by NeptuneIsTheBest** [chaitin/SafeLine#624]
### 背景与遇到的问题

之前搭配Cloudflare，使用时在Nging配置了`ssl_client_certificate`和`ssl_verify_client`项，在遇到非CDN节点（在访问时没有带上Cloudflare节点的CA证书）访问时会直接抛出400。

我目前是源站和WAF装在一台服务器上，似乎是直接访问服务器IP地址也会返回一个带有域名的证书，这样有可能会导致源站的IP泄露。

### 建议的解决方案

希望能增加类似于Nginx中的`ssl_reject_handshake`或者`ssl_client_certificate`和`ssl_verify_client`配置项，在未被授权的来源访问时阻断连接。

**Comment by QAQ5555** [comment]
支持，现在急需这个功能

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
