### ISSUE TITLE
[建议] 是否能在搜索中增加ip段的搜索，或者智能ip段分析

### ISSUE THREAD

**Issue by saigyouyou** [chaitin/SafeLine#626]
### 背景与遇到的问题

攻击日志里经常会出现一大批同一ip段的分散攻击，搜索和统合基本都是靠手动，然后全复制出来整理成a.b.c.0/24的形式再手动添加到黑名单

### 建议的解决方案

是否能提供一个简单的分析统计，比方说统合成一个ip段的形式直接添加到黑名单，或者至少在搜索的时候可以只搜ip前三位而不是整个ip

**Comment by Lorna0** [comment]
relate:
* https://github.com/chaitin/SafeLine/issues/378

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
