### ISSUE TITLE
[建议] 增加拦截上游服务器返回的4xx/5xx状态页面的功能

### ISSUE THREAD

**Issue by isxpy** [chaitin/SafeLine#629]
### 背景与遇到的问题

访问网站过程中，大家都经常会遇到服务器返回的4xx或5xx状态码页面，然而4xx/5xx状态码页面有时候会不可避免的泄露一些敏感信息，比如说：在没有配置自定义的重定向页面时，服务器返回4xx/5xx默认页面时会泄露中间件版本/报错源代码/网站路径等或更多信息。
可能这些信息对普通访问者不敏感，但是从入侵者视角获取到这些信息，就有可能是提供入侵思路了。

### 建议的解决方案

希望雷池WAF可以增加拦截上游服务器返回的4xx/5xx状态页面的功能，让雷池WAF代替上游服务器返回相应状态码的页面给客户端。
拦截日志也记录上游服务器的HTTP响应包信息，方便排查相应故障。

描述的可能有点潦草，欢迎各位师傅补充

**Comment by Lorna0** [comment]
黑名单里匹配条件增加响应码是不是能解决这个问题呢

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
