### ISSUE TITLE
能否增加检测日志删除功能 / 自动清理历史日志 / 设置日志保留时间

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#63]
检测日志越来越多，能否增加一个日志占用百分比自动删除，或者手动可以按照时间批量删除日志的功能？

**Comment by huangyitong** [comment]
附议，可以自定义设置日志保留时间，比如日志保留30天、180天等等

**Comment by zclaiqcc** [comment]
V1.6 支持了命令行删除全部的日志和统计，能满足部分测试之后清理日志的场景

**Comment by DeronW** [comment]
这个可以有

**Comment by DeronW** [comment]
可以与 https://github.com/chaitin/safeline/issues/119 关联，一个负责查询，一个负责删除

**Comment by xsbod** [comment]
附议，可以自定义设置日志保留时间，比如日志保留30天、180天等等

**Comment by xsbod** [comment]
> 检测日志越来越多，能否增加一个日志占用百分比自动删除，或者手动可以按照时间批量删除日志的功能？
