### ISSUE TITLE
[Bug] 重启后今日拦截独立 IP数据会被重置

### ISSUE THREAD

**Issue by hope250** [chaitin/SafeLine#630]
### 问题描述

[Bug] 重启后今日拦截独立 IP数据会被重置
不论是直接重启docker服务，还是在升级过程中重启docker服务，今日拦截独立 IP数据都会被重置。
这个问题一直存在，不是 4.x.x 出现的，之前就一直都存在

### 版本号

4.2.1

### 复现方法

重启docker服务即可复现

### 期望的结果

今日拦截独立 IP数据持久化，重启等能保持数据不丢失

**Comment by upbeat-backbone-bose** [comment]
复议，有发现相同的问题，版本号v4.2.0

**Comment by Lvshujun0918** [comment]
bug复现

**Comment by xbingW** [comment]
released in 6.4.0
