### ISSUE TITLE
[建议] 增加弱口令识别控制功能，特别是admin 123456一类的口令

### ISSUE THREAD

**Issue by 888hou** [chaitin/SafeLine#631]
### 背景与遇到的问题

因为弱口令被上级主管部门通报，建议增加弱口令识别和防控功能设置为记录模式和防护模式。

### 建议的解决方案
建议增加弱口令识别和防控功能设置为记录模式可以记录弱口令情况，方便后期进行质控对非管辖系统进行安全防范，设置为防护模式，当检测到弱口令登录即断开链接，识别成风险项目，防止因为弱口令导致的网络安全事件发生。

**Comment by 888hou** [comment]
设置为记录模式可以记录弱口令情况，设置为防护模式，当检测到弱口令登录即断开链接，识别成风险项目，防止因为弱口令导致的网络安全事件发生。

**Comment by Lvshujun0918** [comment]
但是不同的系统传参方法不一样啊，而且密码也不可能明文传输，WAF怎么解密呢

**Comment by eKil** [comment]
这种奇怪的需求，只能商业版了吧

**Comment by yrluke** [comment]
确实，这个问题感觉还是让扫描器来解决类似的问题更为合适

**Comment by saigyouyou** [comment]
密码都是加密存储的，不好判断吧。
弱口令最好是输入的是时候鉴定。让所有人在某个期限内修改密码，不修改直接冻结。然后重新在提交修改的密码的时候判读是否弱口令，是的话让他们修改。

**Comment by Lorna0** [comment]
不同服务的传参方法不一样，而且密码的传输一般会在 https 的基础上再次加密，加密的方式也是各个系统都不一样，雷池原理上比较难支持。还有就是 WAF 只能防护 Web 网站，但是像 ssh、mysql、RDP 等很多服务都可能存在弱密码，这些雷池也覆盖不到。

要想减少弱口令问题，首先是进行扫描检查，比如长亭的牧云（主机探针扫描）、云图（互联网暴露面扫描）、洞鉴 xray（漏洞扫描器）之类的产品。然后是服务本身尽量制定一些密码安全策略，比如密码复杂度要求、强制定期更改密码。

**Comment by xbingW** [comment]
目前升级到商业版支持解决弱口令问题
