### ISSUE TITLE
[Bug] IP组订阅更新上限993条

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#632]
### 问题描述

禁用国外IP访问，把中国的也禁用了
![image](https://github.com/chaitin/SafeLine/assets/51684966/ae64fb57-bcf4-47c0-878f-47942e32dc14)

![image](https://github.com/chaitin/SafeLine/assets/51684966/3d330d15-39ba-4a9d-a4ae-5c9e8d4b666e)
实际有5400个IP，但是订阅更新就同步了993个IP，是不是IP组有上限。

### 版本号

4.2.0

### 复现方法

实际有5400个IP，但是订阅更新就同步了993个IP，是不是IP组有上限。

### 期望的结果

。

**Comment by bf1942** [comment]
### 问题复现
![IP组上限问题](https://github.com/chaitin/SafeLine/assets/29229412/1c6368bf-ebcf-4ba0-8c63-ce6b589b357f)
### 版本号
4.2.0
### 操作系统
Ubuntu 2204
### 配置
4C 4G 200G

**Comment by zonas0574** [comment]
#621

**Comment by TScci** [comment]
## 问题复现
![WX20240130-145227@2x](https://github.com/chaitin/SafeLine/assets/47475807/c2216cfb-7204-4e1a-ba36-adccad5409fb)
## 版本号
4.2.0
## 操作系统
Alibaba Cloud Linux 3.2104
## 复现方法
总计1600+个地址的IP组，自动/手动更新订阅都只能获取到1001个地址

* 临时多组订阅解决

**Comment by xbingW** [comment]
released in 6.4.0
