### ISSUE TITLE
[建议] 新增“在线订阅IP组自定义更新时间”功能

### ISSUE THREAD

**Issue by nixingshiguang** [chaitin/SafeLine#633]
### 背景与遇到的问题

对于网站的后台，一般都只需要管理员可以访问，然而由于家庭宽带均使用动态公网，并且经常变，基本每天一变，如果得不到及时更新，就需要自己手动更新了，略显笨拙

### 建议的解决方案

建议新增以下其中一个功能：
1. 缩短在线订阅IP组自动更新时间
2. 增加**自定义**在线订阅IP组更新时间
当然，第二种方案会更加灵活

**Comment by DeronW** [comment]
@nixingshiguang  现在是每天一次，再缩短的话，具体期望是多长时间？

**Comment by nixingshiguang** [comment]
> @nixingshiguang  现在是每天一次，再缩短的话，具体期望是多长时间？

根据最近的观察，一般运营商更换动态IP多在凌晨1点，早上6点，晚上9点左右，或者半天一次较为适宜，早上8点最好更新一次

**Comment by clion007** [comment]
建议增加自定义计划任务可以更新IP组

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
