### ISSUE TITLE
[建议] 增加“频率限制”的资源文件（js、css、jpg……等）的白名单

### ISSUE THREAD

**Issue by eagleyan888** [chaitin/SafeLine#635]
### 背景与遇到的问题

一般网页中都会引用大量的图片、js、css……等静态资源文件，用户访问一个页面往往会瞬时发起几十甚至几百个请求，而往往需要重点保护的请求只有少数几个动态页面（例如：php、jsp、xxx.do ……等）。目前的“频率限制”会把所有请求都计算在内，导致用户访问一两个页面就会被封禁，导致用户访问不流畅，体验不佳。
虽说可以放大频率限制的阈值，但是又会导致要保护的动态资源得不到保护。

### 建议的解决方案

建议增加：“**频率限制**”的**资源文件白名单**，用户可以选择添加或输入要放行的资源文件的扩展名（以 , 分隔）如：txt,cur,ico,gif,jpg,jpeg,png,webp,bmp,swf,flv,js,css,apk,xml,json,mp3,zip,htm,html,pdf 。

雷池根据配置，自动在配置里加入如下命令：
```
location ~ .*\.(txt|cur|ico|gif|jpg|jpeg|png|bmp|swf|flv|js|css|apk|xml|json|mp3|zip|htm|html|pdf)$ {
    proxy_pass http://backend_x;
    ……
}
```

这样，可以让用户根据实际情况灵活配置，在用户体验和带宽保护上自行做取舍。

**Comment by Lorna0** [comment]
之前有个类似的，合并到一起讨论吧：
* https://github.com/chaitin/SafeLine/issues/358

这个有个问题是，还是可能被 CC，比如攻击者就一直访问 .js，相当于绕过了，限频就没有意义了。
其实更建议直接把 “经过时间” “和请求次数达到” 都调大一点，这样用户就不会触发了。本身会对服务器造成压力的 CC 也不会只打几秒钟。
