### ISSUE TITLE
[Bug] 更新 4.2.1 版本后，动态登录口令报错 "The time gap betwwen Server and Browser is over 30s"

### ISSUE THREAD

**Issue by Lichil** [chaitin/SafeLine#636]
### 问题描述

更新 4.2.1 版本后，动态登录口令报错 "The time gap betwwen Server and Browser is over 30s"
如下如：
![image](https://github.com/chaitin/SafeLine/assets/24882992/e17087fb-382c-4857-99e3-41144d706ebd)

回滚到 4.1.1 版本则正常登录

### 版本号

4.2.1

### 复现方法

1、安装 4.1.1 版本
2、升级至 4.2.1 版本
3、访问 waf 管理端 （9443）
4、填入正确的动态口令（错误口令也是一样报错）

### 期望的结果

使用正确的动态口令，登录到 waf 管理页面

**Comment by Lichil** [comment]
add

**Comment by focusTouch** [comment]
我猜测你服务器的时间与北京时不一致，同步一下就好

**Comment by Lichil** [comment]
时间是一致的，重置了 OTP 认证，然后就正常了。奇怪的问题
