### ISSUE TITLE
自定义规则已设置但未生效

### ISSUE THREAD

**Issue by ossplus** [chaitin/safeline#64]
自定义规则，设置拒绝所有访问wp-login.php；
但实际并未生效
![image](https://github.com/chaitin/safeline/assets/1935044/0733dca2-1171-4ea1-8353-dd05964e20fb)

**Comment by zclaiqcc** [comment]
少了前面的 /

完全相等的话，/wp-login.php 试试

**Comment by zclaiqcc** [comment]
师傅测一下，有问题再 open 吧
