### ISSUE TITLE
[建议] 希望可以使用 ! 筛选排除日志

### ISSUE THREAD

**Issue by smallxu038** [chaitin/SafeLine#640]
### 背景与遇到的问题

在日志中，很多来自同一IP或攻击同一URL的请求，加入排除以提高信息分析效率。

### 建议的解决方案

加入!筛选日志，如!1.1.1.1，筛选IP不包含1.1.1.1的日志。这对于日志分析很重要，可以快速排除无效信息。
![!safe](https://github.com/chaitin/SafeLine/assets/47671569/acfd3262-ec5a-4429-ab24-95018f6f605f)
![捕获!](https://github.com/chaitin/SafeLine/assets/47671569/1b939af4-2329-444c-9464-4880a90b0434)

**Comment by Lvshujun0918** [comment]
请问最后这张截图是怎么实现统计的？

**Comment by smallxu038** [comment]
> 请问最后这张截图是怎么实现统计的？
您好，这个是UTM设备FortiGate的日志查询页面，不是我自己开发的系统。
![!](https://github.com/chaitin/SafeLine/assets/47671569/7d9a85c5-f447-44ed-bbd5-64f2e01a0e19)

**Comment by Lvshujun0918** [comment]
感谢 确实是一个很好的功能提议 不知道开发者怎么想

**Comment by DeronW** [comment]
现在的日志搜索项已经有 9 个了
![image](https://github.com/chaitin/SafeLine/assets/780596/9a74124b-4c89-4763-9d57-b6df933dacd4)

如果添加 “不包含” 条件，开发者认为搜索方式需要改变才可以，如果只添加一个 感叹号 操作会不够方便

**Comment by Lorna0** [comment]
之前有个类似 issue，可以一起讨论：
* https://github.com/chaitin/SafeLine/issues/269

**Comment by smallxu038** [comment]
> 现在的日志搜索项已经有 9 个了 ![image](https://private-user-images.githubusercontent.com/780596/300319234-9a74124b-4c89-4763-9d57-b6df933dacd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTcyMjgsIm5iZiI6MTcwNjUxNjkyOCwicGF0aCI6Ii83ODA1OTYvMzAwMzE5MjM0LTlhNzQxMjRiLTRjODktNDc2My05ZDU3LWI2ZGY5MzNkYWNkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwODI4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTkyOTQ5NGM4MDE4NDZjZjQyMGEwZjVjNmYxZGFmNmRkN2M2ZGQwZGQ5Y2Q3NzAzZDU2MWU5ZmY0YmE5ZjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qYlCessuD2vivP0KyweyWupHS-Czo3E4QcKLULoIA9g)
> 
> 如果添加 “不包含” 条件，开发者认为搜索方式需要改变才可以，如果只添加一个 感叹号 操作会不够方便

因为发现有大量攻击来自同一IP地址，或者攻击同一路径，为了方便筛选分析日志建议加上不包含选项，另外，”!"筛选日志是（至少我用过的）网络设备/系统的通用方式。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
