### ISSUE TITLE
[建议] 提供一个 GitHub 镜像版本脚本

### ISSUE THREAD

**Issue by hour-keeper** [chaitin/SafeLine#641]
### 背景与遇到的问题

我在美国的vps无法使用官网的脚本下载 compose.yaml 文件

### 建议的解决方案

如果可以指定 GitHub 为文件源，拉取可能更容易一些

**Comment by DeronW** [comment]
@yenfeng-shetiko   反向被墙了吗？ 

可以直接下载 github 上的 compose 文件安装 https://github.com/chaitin/SafeLine/blob/main/release/latest/compose.yaml

升级脚本的国外镜像，还需要改些内容才能用

**Comment by yenfeng-shetiko** [comment]
> @yenfeng-shetiko 反向被墙了吗？
> 
> 可以直接下载 github 上的 compose 文件安装 https://github.com/chaitin/SafeLine/blob/main/release/latest/compose.yaml
> 
> 升级脚本的国外镜像，还需要改些内容才能用

天知道，在洛杉矶区域的linode不能连接，ping也ping不通
