### ISSUE TITLE
[建议] 在 compose.yaml 中添加com.centurylinklabs.watchtower.enable="false" 标签

### ISSUE THREAD

**Issue by yenfeng-shetiko** [chaitin/SafeLine#642]
### 背景与遇到的问题

使用 watchtower 时会自动更新所有容器，safeline 的 compose.yaml 脚本却不能按时更新，导致有时文件损坏

### 建议的解决方案

在 compose.yaml 中为每个容器添加 com.centurylinklabs.watchtower.enable="false"

**Comment by chenvd** [comment]
在watchtower排除掉吧
WATCHTOWER_DISABLE_CONTAINERS=safeline-detector safeline-fvm safeline-luigi safeline-mario safeline-mgt safeline-pg safeline-tengine

**Comment by yenfeng-shetiko** [comment]
> 在watchtower排除掉吧 WATCHTOWER_DISABLE_CONTAINERS=safeline-detector safeline-fvm safeline-luigi safeline-mario safeline-mgt safeline-pg safeline-tengine

雷池还在开发中吧，有时会增加或减少容器

**Comment by DeronW** [comment]
watch tower 实现了自动升级容器，它其实托管了原来需要手动升级的这个流程。这种情况下，建议在托管工具本身上进行配置，如果真的某种情况下，希望 watch tower 自动升级这些容器，依然可以通过工具配置实现，而不是被容器本身的设置禁用掉

**Comment by yenfeng-shetiko** [comment]
> watch tower 实现了自动升级容器，它其实托管了原来需要手动升级的这个流程。这种情况下，建议在托管工具本身上进行配置，如果真的某种情况下，希望 watch tower 自动升级这些容器，依然可以通过工具配置实现，而不是被容器本身的设置禁用掉

好的
