### ISSUE TITLE
[Bug] websocket无法连接

### ISSUE THREAD

**Issue by Tristan0430** [chaitin/SafeLine#643]
### 问题描述

雷池旧版本（忘了是哪一个）代理过code-server，并且可以正常连接，更新到4.2.0后，无法连接websocket服务器，需手动更改雷池代理的nginx配置文件，很不方便。
<img width="1244" alt="3e5de3f30e748b517a02b0772229ae5" src="https://github.com/chaitin/SafeLine/assets/113957665/c81996ac-6e43-40bc-89ff-54f1f004bc20">

### 版本号

4.2.0

### 复现方法

1. 在雷池上代理websocket应用
2. 出现websocket连接失败的报错

### 期望的结果

不需要手动更改nginx配置文件就可以支持websocket连接

**Comment by yrluke** [comment]
所以是旧版本还是4.2.0呢，如果是4.2.0,应该是默认支持，麻烦确认一下版本

**Comment by yrluke** [comment]
https://github.com/microsoft/vscode/issues/187360

**Comment by yrluke** [comment]
看上去vscode那边也没查清到底是因为啥websocket close了，能抓包看一下是什么情况吗

**Comment by yrluke** [comment]
可以google一下看看有没有解决办法

**Comment by Lvshujun0918** [comment]
这个问题好像是偶发的，而且与linux版本有关，CentOS遇到的多，你可以在vscode的issue里面搜一下，好像有解决方法

**Comment by Tristan0430** [comment]
> 看上去vscode那边也没查清到底是因为啥websocket close了，能抓包看一下是什么情况吗

https://github.com/coder/code-server/issues/4443
这个应该是雷池的nginx的配置问题，群里也有类似的情况

**Comment by Tristan0430** [comment]
> 这个问题好像是偶发的，而且与linux版本有关，CentOS遇到的多，你可以在vscode的issue里面搜一下，好像有解决方法

我不是个例，群里也有其他人有类似的问题
<img width="438" alt="1706664567691" src="https://github.com/chaitin/SafeLine/assets/113957665/0362cae8-2aa1-4dbb-926e-a4485053137b">

**Comment by octopus2181** [comment]
我也发现这个问题了，我试过swag和Nginx-Proxy-Manager这个两个代理，都有这个问题。如果我在swag或者Nginx-Proxy-Manager的docker compose文件中，将端口映射设置成443:443 ， code server 是工作正常的。但是如果其它端口映射到443（比如9999:443），就是出现1006的错误，已经困扰我几天了

**Comment by Tristan0430** [comment]
> 我也发现这个问题了，我试过swag和Nginx-Proxy-Manager这个两个代理，都有这个问题。如果我在swag或者Nginx-Proxy-Manager的docker compose文件中，将端口映射设置成443:443 ， code server 是工作正常的。但是如果其它端口映射到443（比如9999:443），就是出现1006的错误，已经困扰我几天了

我的code-server的端口映射是40013:8443，本地是没问题的，代理才有websocket报错，内外端口改成一致也是一样的。

**Comment by LikeNeko** [comment]
我也遇到了，老哥们都咋改的nginx配置，我是部署的snapdrop，报连不上wss

**Comment by octopus2181** [comment]
> > 我也发现这个问题了，我试过swag和Nginx-Proxy-Manager这个两个代理，都有这个问题。如果我在swag或者Nginx-Proxy-Manager的docker compose文件中，将端口映射设置成443:443 ， code server 是工作正常的。但是如果其它端口映射到443（比如9999:443），就是出现1006的错误，已经困扰我几天了
> 
> 我的code-server的端口映射是40013:8443，本地是没问题的，代理才有websocket报错，内外端口改成一致也是一样的。

是的，我也是这个问题，在code server中端口可以映射，但代理中如果非443端口映射443，就会出现1006

**Comment by octopus2181** [comment]
我的问题已经解决，这样设置
proxy_set_header X-Forwarded-Host $http_host
之前是$host，这个是不带端口转发，$http_host带端口转发。供参考！

**Comment by piwawa** [comment]
> 我的问题已经解决，这样设置 proxy_set_header X-Forwarded-Host $http_host 之前是$host，这个是不带端口转发，$http_host带端口转发。供参考！

这个在 npm 里面咋设置啊？我域名是 cs.a.com ，npm 映射是 8443:443，这样还是报错

![image](https://github.com/user-attachments/assets/18209d24-8b87-42c8-bbf9-d1e1582c1b9d)

![image](https://github.com/user-attachments/assets/9f95db64-7e36-4e65-9ffe-a874e62079ba)

![image](https://github.com/user-attachments/assets/d779462e-e748-4f39-9178-4fecaafbebe5)
