### ISSUE TITLE
雷池的防护站点的HTTPS配置既然只能全局配置，不能按防护站点独立定义[Bug] 

### ISSUE THREAD

**Issue by d960124** [chaitin/SafeLine#644]
### 问题描述

正常所有的web服务器HTTPS的强制配置，一般都是在站点里面单独定义
毕竟不同站点，对于强制HTTPS是有不一样的需求的
雷池在这一点处理逻辑上面设计有BUG的，只允许全局统一配置！！！
![image](https://github.com/chaitin/SafeLine/assets/48110764/450b41ff-769e-44df-92d9-e6402090e837)

### 版本号

4.0.2

### 复现方法

![image](https://github.com/chaitin/SafeLine/assets/48110764/c9ab8f1e-dfe7-4551-bcd4-8ef2aeefe5c8)

### 期望的结果

期望能 把强制HTTPS配置，迁移到站点里面，这样能实现各站点独立配置！！

**Comment by DeronW** [comment]
@d960124  社区版暂时还不支持独立配置站点

**Comment by Lorna0** [comment]
Duplicate:
* https://github.com/chaitin/SafeLine/issues/241
