### ISSUE TITLE
防护站点大量域名添加的困扰及建议[Bug] 

### ISSUE THREAD

**Issue by d960124** [chaitin/SafeLine#645]
### 问题描述

本人有几台CDN节点，绑定了近100个域名，域名指向内容均一样
现在准备迁移到雷池，碰到了二个非常纠结的问题
1、雷池防护站点域名的添加，只能一个一个的输入，不能支持批量输入，近100个域名，几台服务器，这个工作量还是不小的，建议能批量输入，比如用换行，或者空格，或者TAB，或者某符号间隔的方式，一次性输入进去，输入之后，在防护站点列表里面，也不用全部显示出来，一个站点能把页面占完！！！
![image](https://github.com/chaitin/SafeLine/assets/48110764/26aa161c-72a2-4591-b62e-f5fc7ea3ee04)
![image](https://github.com/chaitin/SafeLine/assets/48110764/09d242c0-d12b-4ce0-9d0c-8658a16f09e1)

2、防护站点添加了域名之后，还是需要在上游源站里面去添加一次域名，重复的工作需要做2次，按正常的反向代理/CDN，可以配置回源域名，这样只需要在雷池里面配置添加域名，不用到上游里面去操作一次域名配置，能大大减轻运维的工作！

### 版本号

4.0.2

### 复现方法

随时可以复现

### 期望的结果

1、编辑/新建站点能实现批量输入域名
2、列表里面展示部分域名即可，域名展示太多，影响列表美观度
3、能在防护站点里面配置 回源 上游的固定域名，这样增删域名不用再重复在上游去配置一次

**Comment by DeronW** [comment]
@d960124  第三点，回源上游的固定域名，期望的操作是什么样的？

**Comment by d960124** [comment]
> @d960124 第三点，回源上游的固定域名，期望的操作是什么样的？

现在回源上游的域名是跟随用户访问的域名，也就是用户用 a.chaitin.cn 访问雷池waf，雷池会用 a.chaitin.cn 这个域名去访问上游
如果我在雷池防护站点上面增加一个域名b.chaitin.cn，需要在上游站点也同步增加一个域名，要不，上游不会返回期望的结果给雷池waf！      
这个时间应用场景来了，我这边有几台服务器，上面同一站点配置了近百个域名，并且，域名是经常需要维护的，这个时间，我维护一次域名，需要在每台服务器的雷池，还有上游站点同步去增加域名，比较麻烦！

我们也在用CDN产品，CDN产品有一个回源域名设置，回源到上游的时候，不管用户访问的域名是什么，CDN都会用我配置的统一域名去访问上游，比如：
CDN上面配置   up.chaitin.cn    a.chaitin.cn   b.chaitin.cn  c.chaitin.cn  d.chaitin.cn   *****  z.chaitin.cn N个域名，我只要在回源域名参数上面设置统一用  up.chaitin.cn 这个域名回源，不管用户用上面任意域名访问CDN，都能正确访问到上游的 up.chaitin.cn 这个站点的内容，从而实现增加域名，只需要在 CDN上面增加域名即可，不用再去在上游同步增加域名，上游只需要在回源站点绑定 up.chaitin.cn 这一个域名即可

这个参数，应该是 nginx的 ：proxy_set_header Host  $host   参数 目前雷池是 跟随用户，即访问上游域名是取自用户域名

**Comment by Lorna0** [comment]
意思是业务本身不会变化，一直是同一个服务同一个网站，而访问的域名有很多，且要频繁变化吗。

简单点配置的话，只需要在最外层的反代上配置多个域名，比如 CDN 上配置 up.chaitin.cn a.chaitin.cn b.chaitin.cn c.chaitin.cn d.chaitin.cn ***** z.chaitin.cn N 个域名，指向雷池某个端口。然后雷池上直接配置 * 统配所有域名和对应的端口，然后指向上游服务器就行了。另外更简单点，上游服务器也不用监听   up.chaitin.cn a.chaitin.cn... N 个域名，直接监听 * 统配所有域名也一样能提供服务。如果上游服务器也是个代理，有多个网站，那用端口区分就行了，不需要非得在所有设备上配置域名。

其实更建议用上面这种方法配置，更方便直接。实在有需要的话，参考官网文档在后台的 nginx config 里加一下也能实现（[https://waf-ce.chaitin.cn/docs/faq/other#自定义站点-nginx-conf](https://waf-ce.chaitin.cn/docs/faq/other#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9-nginx-conf)）

**Comment by Lorna0** [comment]
> * 能统配到所有的域名吗？  上面例子没有考虑实际，我们实际域名，是各种各样的，并不是只有一个主域名下面的各种二级域名，可以用 泛域名的方式来配置！

* 的含义就是统配所有的域名，可以配置试一下

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
