### ISSUE TITLE
[建议] 提供批量加入IP组的功能

### ISSUE THREAD

**Issue by hubyao** [chaitin/SafeLine#646]
### 背景与遇到的问题

比如遇到这种,我需要把这批ip全部拉入ip组,但是只能一个一个的点击,比较繁琐,希望优化一下,增加批量添加ip的功能
![image](https://github.com/chaitin/SafeLine/assets/32606145/8a110ac5-a8a9-4dff-a07c-67c4bc76c866)

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
