### ISSUE TITLE
[建议] waf前端可看到正常国外ip信息，但是字段里是英文简称

### ISSUE THREAD

**Issue by gitamorning** [chaitin/SafeLine#647]
### 背景与遇到的问题

waf前端上看到的是如下信息：
已拦截 | http://ec.t.tcashfree.cn/.git/config | 信息泄露 | 164.90.222.93(德国)

对waf日志提取，做的告警是如下：
【来源IP】：164.90.222.93
【来源城市】：DE

### 建议的解决方案

将DE 对应到德国，其他的等同，需要来源ip国家的中文名称字段

**Comment by yrluke** [comment]
从社区版的角度上来说感觉动力并不大，前端能够正常显示，但是后端存的时候还要翻译一下，动力并不大，看看社区的呼声吧

**Comment by DeronW** [comment]
@gitamorning 是指在数据库中保存的内容吗？ 原始数据还是应该保存国家编码的，如果保存成中文，转换的时候不方便，比如：刚果，看到这个简称后并不知道它指的是刚果金，还是刚果布，用全称又很长

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
