### ISSUE TITLE
[建议] 建议支持更多架构

### ISSUE THREAD

**Issue by Whbgz** [chaitin/SafeLine#648]
### 背景与遇到的问题

我的服务器为arm架构，看到安装文档只支持x64_x86

### 建议的解决方案

建议增加支持arm、armv8、armv7架构，麻烦了

**Comment by DeronW** [comment]
@Whbgz  这么多 arm 的不同版本架构是用什么用途吗？ waf 主要面向的是服务器用户，架构基本上都是 x86

**Comment by Lorna0** [comment]
会考虑支持 arm 架构。duplcate：
* https://github.com/chaitin/SafeLine/issues/56
