### ISSUE TITLE
[Bug] welcome to nginx这个防护站点的规则有bug

### ISSUE THREAD

**Issue by gitamorning** [chaitin/SafeLine#649]
### 问题描述

1、/api/ApiAsset?id=1，welcome to nginx这条防护站点记录，固定总有47条左右的域名数据，尽管我已经把这47条域名拖出来批量添加了站点，但是凌晨抽当天数据来看，还是有这47条左右的域名的访问量，请求量（我一共添加了120条左右的防护站点，就这47条域名很顽固）正常添加了域名站点，对应的流量就会分到添加的域名站点里，然后nginx里消失掉，但没有
2、没单独添加防护站点的域名A.COM，在waf事件里发现了对A.COM的进行了几百次请求爆破，但是当天23.59抽取当天的welcome to nginx数据来看，里面没有A.com 域名的访问和拦截数据（也就是/api/ApiAsset?id=1，这条站点记录没记录到A.COM的域名，同时waf上能查看对该域名的的攻击事件）

### 版本号

4.2.0

### 复现方法

单我遇到这个问题，可以每天定时抽取/api/ApiAsset?id=1里的数据，然后用脚本自动批量添加站点，一周不到的时间都会发现这个问题

### 期望的结果

没单独添加站点的域名，都应被welcome to nginx 这条记录到才对。单独分出去添加的站点，流量应该从welcome to nginx里消失

**Comment by yrluke** [comment]
https://waf-ce.chaitin.cn/docs/faq/other#%E6%9C%89%E5%A4%9A%E4%B8%AA%E9%98%B2%E6%8A%A4%E7%AB%99%E7%82%B9%E7%9B%91%E5%90%AC%E5%9C%A8%E5%90%8C%E4%B8%80%E4%B8%AA%E7%AB%AF%E5%8F%A3%E4%B8%8A%E5%8C%B9%E9%85%8D%E9%A1%BA%E5%BA%8F%E6%98%AF%E6%80%8E%E4%B9%88%E6%A0%B7%E7%9A%84
听上去好像是这个问题？

**Comment by gitamorning** [comment]
有点相关，但并不全是
【其他问题里说到:
以上图为例，如果用户使用 a.example.com 访问，命中 a.example.com。 如果用户使用 b.example.com，命中 *.example.com。】
问题就在这儿，1、我添加了 a.example.com，但是在/api/ApiAsset?id=1，welcome to nginx这条记录里还是会有命中a.example.com的数据

2、命中了a.exam.com，而且a.exam.com也是我们公司的域名，但是在/api/ApiAsset?id=1，welcome to nginx这条记录里没有这个命中信息（我没单独添加a.exam.com

> https://waf-ce.chaitin.cn/docs/faq/other#%E6%9C%89%E5%A4%9A%E4%B8%AA%E9%98%B2%E6%8A%A4%E7%AB%99%E7%82%B9%E7%9B%91%E5%90%AC%E5%9C%A8%E5%90%8C%E4%B8%80%E4%B8%AA%E7%AB%AF%E5%8F%A3%E4%B8%8A%E5%8C%B9%E9%85%8D%E9%A1%BA%E5%BA%8F%E6%98%AF%E6%80%8E%E4%B9%88%E6%A0%B7%E7%9A%84 听上去好像是这个问题？

**Comment by xbingW** [comment]
released in 6.4.0
