### ISSUE TITLE
[Bug] 好像误报按钮不起作用

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#651]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/41245552/f5d8acfe-1e1e-42a0-8bf3-a92a7842a25a)
如上图点击误报按钮
![image](https://github.com/chaitin/SafeLine/assets/41245552/ff65525d-2f7a-44b0-951d-06fee65ed563)
显示这个
控制台错误提示如下
![image](https://github.com/chaitin/SafeLine/assets/41245552/1ba69133-2201-4d91-bc8b-901e9c356c5c)

### 版本号

4.2.0

### 复现方法

我这边是任意一个拦截的请求点误报都显示这个

### 期望的结果

可以正常进行误报

**Comment by DeronW** [comment]
@Lvshujun0918  升级到 4.3 版本试一下

**Comment by Lvshujun0918** [comment]
不好意思回复晚了 该问题已修复
