### ISSUE TITLE
[建议] 通过配置的规则（黑白名单人机验证等）来限频

### ISSUE THREAD

**Issue by imjason** [chaitin/SafeLine#654]
### 背景与遇到的问题

![Screenshot_20240202_234917_com microsoft emmx beta_edit_156012369402235](https://github.com/chaitin/SafeLine/assets/78479629/8df45a76-32c9-43bb-9ad5-0d3d8d196cb6)
希望匹配目标可以添加一个单IP访问频率
应用场景，比如我的一个登陆可能会被爆破，在单IP访问超过5次时触发人机验证，统一的高频访问限制显然不能很好的解决这个问题

### 建议的解决方案

添加一个单IP访问次数匹配目标

**Comment by Lorna0** [comment]
高频访问限制就是根据 IP 统计的呀，我觉得你想说的是这个吧：
* https://github.com/chaitin/SafeLine/issues/209

**Comment by Lorna0** [comment]
我好像理解了，你是想通过人机验证这里灵活的匹配条件来设定规则，进而限频是吧。

企业版是能够这样设置的。社区版不这样处理，一方面是因为使用比较复杂，一方面是这样性能消耗会更大一些。因为限频需要缓存一段时间的统计数据，所以其实对性能的影响会比较明显。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
