### ISSUE TITLE
[建议] 增加勾选双向ssl证书认证

### ISSUE THREAD

**Issue by peng2289** [chaitin/SafeLine#655]
### 背景与遇到的问题

目前的站点无法开启网站的证书双向认证，也就是nginx的设置ssl_verify_client on;配置

### 建议的解决方案

nginx的设置ssl_verify_client on;
同时能获取客户端的证书信息
$ssl_client_s_dn
$ssl_client_serial
$ssl_client_fingerprint
有些网站要求严格，必须客户端发送证书才能验证，否则拒绝发送

**Comment by Lorna0** [comment]
双向认证还需要配置对应的根证书，挺麻烦的。要不试试后台 nginx config 能不能满足需要呢

**Comment by peng2289** [comment]
> 双向认证还需要配置对应的根证书，挺麻烦的。要不试试后台 nginx config 能不能满足需要呢

nginx里面配置还是很简单，就多了两个参数，只是双向验证不好接入统一走waf

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
