### ISSUE TITLE
[Bug] 仅使用 80 端口的域名，会在证书管理中提示不匹配

### ISSUE THREAD

**Issue by faritor** [chaitin/SafeLine#656]
### 问题描述

如下图，仅添加 80 端口进行转发
![image](https://github.com/chaitin/SafeLine/assets/32325325/acf87f09-baaa-4909-af92-e7815a8721a8)

在证书管理中，提示该域名与证书不匹配，这里根本用不到证书的信息
![image](https://github.com/chaitin/SafeLine/assets/32325325/6c2d4e90-fb55-4c5f-9c1e-7bbfe959edce)

### 版本号

4.2.0

### 复现方法

 如描述中所示

### 期望的结果

不使用证书的域名，不希望出现在证书管理中

**Comment by sunskyx** [comment]
![PixPin_2024-02-05_23-32-55](https://github.com/chaitin/SafeLine/assets/90336220/b064aefd-a06f-4724-bac7-36a9b08f2bc5)
![PixPin_2024-02-05_23-33-50](https://github.com/chaitin/SafeLine/assets/90336220/65c176b2-e3b6-4ce1-925f-67f755a876e3)

我的域名和证书都是匹配的，也是有这个提示，一个二级泛域名，一个三级泛域名，三级泛域名提示不匹配

**Comment by sunskyx** [comment]
版本号：4.3.2

**Comment by Lorna0** [comment]
源问题应当在 4.3.1 中修复了。

> @sunskyx 
> ![PixPin_2024-02-05_23-32-55](https://private-user-images.githubusercontent.com/90336220/302344410-b064aefd-a06f-4724-bac7-36a9b08f2bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzY5MzcsIm5iZiI6MTcwOTE3NjYzNywicGF0aCI6Ii85MDMzNjIyMC8zMDIzNDQ0MTAtYjA2NGFlZmQtYTA2Zi00NzI0LWJhYzctMzZhOWIwOGYyYmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTlhOTQ4NjYxZjU3ODQ1YzY4MmI4OGFjNGVlOWI4MjgwN2VlM2RlYTJjZDgwYzc0YTFjZGY1NjI4MWExMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2RW_3AVDsO3TSgoGiEWColrcA8iARhG9ZEuYZ56fWDE) ![PixPin_2024-02-05_23-33-50](https://private-user-images.githubusercontent.com/90336220/302344466-65c176b2-e3b6-4ce1-925f-67f755a876e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzY5MzcsIm5iZiI6MTcwOTE3NjYzNywicGF0aCI6Ii85MDMzNjIyMC8zMDIzNDQ0NjYtNjVjMTc2YjItZTNiNi00Y2UxLTkyNWYtNjdmNzU1YTg3NmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTVjNTlmYTJhNDA4YzEyYTRjMzAzMzI1ZmRkMDc2NTEwMjc3NTc3YjkyZTFiYzE5ZmUxNTE2ZGNlNTE3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Skl2u7l4guXyVEIVwcWmzHlAkP_umFvVWifUvxhLJp0)
> 
> 我的域名和证书都是匹配的，也是有这个提示，一个二级泛域名，一个三级泛域名，三级泛域名提示不匹配

这个看起来是另一个问题，我们再查查。师傅下次遇到这种情况可以新提一个 issue，不然不容易发现。

**Comment by Lorna0** [comment]
> @sunskyx 
> ![PixPin_2024-02-05_23-32-55](https://private-user-images.githubusercontent.com/90336220/302344410-b064aefd-a06f-4724-bac7-36a9b08f2bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzY5MzcsIm5iZiI6MTcwOTE3NjYzNywicGF0aCI6Ii85MDMzNjIyMC8zMDIzNDQ0MTAtYjA2NGFlZmQtYTA2Zi00NzI0LWJhYzctMzZhOWIwOGYyYmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTlhOTQ4NjYxZjU3ODQ1YzY4MmI4OGFjNGVlOWI4MjgwN2VlM2RlYTJjZDgwYzc0YTFjZGY1NjI4MWExMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2RW_3AVDsO3TSgoGiEWColrcA8iARhG9ZEuYZ56fWDE) ![PixPin_2024-02-05_23-33-50](https://private-user-images.githubusercontent.com/90336220/302344466-65c176b2-e3b6-4ce1-925f-67f755a876e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzY5MzcsIm5iZiI6MTcwOTE3NjYzNywicGF0aCI6Ii85MDMzNjIyMC8zMDIzNDQ0NjYtNjVjMTc2YjItZTNiNi00Y2UxLTkyNWYtNjdmNzU1YTg3NmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTVjNTlmYTJhNDA4YzEyYTRjMzAzMzI1ZmRkMDc2NTEwMjc3NTc3YjkyZTFiYzE5ZmUxNTE2ZGNlNTE3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Skl2u7l4guXyVEIVwcWmzHlAkP_umFvVWifUvxhLJp0)
> 
> 我的域名和证书都是匹配的，也是有这个提示，一个二级泛域名，一个三级泛域名，三级泛域名提示不匹配

这个问题我们在新版本上没有复现出来，师傅可以升级下版本。如果新版仍存在，可以新提一个 issue 或者在交流群里提供一下更多信息。
