### ISSUE TITLE
[建议] 证书自动续签

### ISSUE THREAD

**Issue by xqw8889** [chaitin/SafeLine#657]
### 背景与遇到的问题

是否考虑支持域名通过cdn解析时进行证书的续签与签发

**Comment by Lorna0** [comment]
界面的免费申请证书就是自动续签的

**Comment by xqw8889** [comment]
> 界面的免费申请证书就是自动续签的

根本不可能通过dns验证 你这个只适合没有使用cdn解析的

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
