### ISSUE TITLE
[Bug] 升级v4.3.0之后“攻击事件” - 拦截日志 - "详情"操作按钮由于触发浏览器ADG/uBlock的默认规则导致无法正常打开

### ISSUE THREAD

**Issue by upbeat-backbone-bose** [chaitin/SafeLine#658]
### 问题描述

1. 点击左侧"攻击事件"
2. 选择认一拦截日志记录
3. 点击记录右侧"详情"按钮无响应

预期行为：弹出窗口展示拦截详细信息
![image](https://github.com/chaitin/SafeLine/assets/438092/88a18316-8a3c-4e4d-9fcf-e5e56abf5e86)
![4f734a21465801fd327ac4575ebdf9d](https://github.com/chaitin/SafeLine/assets/438092/17289007-4e39-4f90-a022-e6ade77464a6)
![adfe32e420fab99e538399a720d1636](https://github.com/chaitin/SafeLine/assets/438092/0f65c566-c947-451d-b855-4677a5905500)
![ad41f85a4a9081255b15025349595a6](https://github.com/chaitin/SafeLine/assets/438092/4632f0ac-d399-4f69-8991-7518944c79be)
![image](https://github.com/chaitin/SafeLine/assets/438092/fd846a26-949a-41be-83eb-d6ee20aa868c)

### 版本号

v4.3.0

### 复现方法

1. 点击左侧"攻击事件"
2. 选择认一拦截日志记录
3. 点击记录右侧"详情"按钮无响应

### 期望的结果

可正常打开详情信息进行查看

### 补充说明

虽然每个人插件采用的过滤器可能不同，但是前序版本确实没遇到过该问题，所以新版本详情请求中的 /open/log/* 路径定义可能过于敏感容易被误伤了。

**Comment by Lvshujun0918** [comment]
那你去插件里加白一下就好了啊 感觉这个网址还是比较正常的

**Comment by DeronW** [comment]
@upbeat-backbone-bose  升级到 4.3.1 试一下，更换了日志详情的路径，在 AdBlockMax 插件上测试正常

**Comment by upbeat-backbone-bose** [comment]
> @upbeat-backbone-bose 升级到 4.3.1 试一下，更换了日志详情的路径，在 AdBlockMax 插件上测试正常

@DeronW 升级至v4.3.2在Adguard Home/uBlock Origin环境下测试均恢复正常。
