### ISSUE TITLE
[建议] 支持 Unix domain socket

### ISSUE THREAD

**Issue by mengguyi** [chaitin/SafeLine#659]
### 背景与遇到的问题

我在使用雷池waf的时候发现它并不支持 Unix domain socket 希望可以支持一下

### 建议的解决方案

希望可以支持 Unix domain socket

**Comment by yrluke** [comment]
这个domain socket是干什么用的呢

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
