### ISSUE TITLE
[建议] 两个优化点

### ISSUE THREAD

**Issue by superen7527** [chaitin/SafeLine#660]
### 背景与遇到的问题

用了一下雷池，一些小体验不友好，不过不打紧还能接受就不说了。但是有两个点让我还是放弃了，希望以后可以优化一下。

1.续签ssl目前只能通过解析ip到服务器再申请，建议可以用dns的方法申请，不然一个个改解析挺麻烦的。可以参考一下caddy和npm。

2.反向代理好像只是http反代，问题有点多，而且没有开放nginx那种高级功能。建议：如果不打算在这方面扩展的话，可以单纯改成tcp反代端口，问题会少很多。一股脑转发就好。

**Comment by yrluke** [comment]
1. 这个我们曾经讨论过，因为dns方式的话，会有适配大量不同的dns服务商的问题，所以暂时搁置了
2. 不能使用tcp反代的原因是，雷池的检测引擎需要对http请求进行过滤，tcp流量转发的话可以直接上nginx
建议：如果师傅还想抢救一下的话，可以在雷池后加个nginx，专门针对自己的环境做配置

**Comment by Lorna0** [comment]
因为反馈较多，建议创建前请搜索一下是否有重复问题。另外一个 issue 只描述一个问题的话，会比较方便跟进。例如证书通过 dns 申请、界面配置 nginx config、四层代理之前都有 issue，可以集中讨论：
* https://github.com/chaitin/SafeLine/issues/563
* https://github.com/chaitin/SafeLine/issues/167
* https://github.com/chaitin/SafeLine/issues/123

简单解释一下，反向代理是 waf 需要对 http 流量进行检测与清洗，如果反代不能正常工作的话，tcp 反代端口更可能存在问题。所以方便的话，最好是反馈一下具体遇到了什么问题，我们先 case by case 地解决一下。如果不需要 http 流量清洗，只需要 tcp 转发的话，那其实属于网关设备的需求，只是 waf 简单集成一下方便一点，那可以在上面的 https://github.com/chaitin/SafeLine/issues/123 讨论。 

不完全支持 nginx 能力是因为 nginx 的功能太复杂且灵活了，更适合专业的开发或运维使用。完全支持的话不仅成本高，还会提高软件的使用门槛。有较强的自定义 nginx config 需求的话，可以搜索官网文档 “自定义站点 nginx config” 操作，或者再加一层 nginx 反代来满足需求。当然，我们也会持续观察反馈，考虑增加一些简单的配置能力。

**Comment by cmradix** [comment]
> 因为反馈较多，建议创建前请搜索一下是否有重复问题。另外一个 issue 只描述一个问题的话，会比较方便跟进。例如证书通过 dns 申请、界面配置 nginx config、四层代理之前都有 issue，可以集中讨论：
> 
> * [[建议] 支持申请泛域名免费证书 / 支持用 dns 验证方式申请免费证书 #563](https://github.com/chaitin/SafeLine/issues/563)
> * [[建议] 希望增加自定义Nginx参数功能，或融合nginxWebUI等工具 #167](https://github.com/chaitin/SafeLine/issues/167)
> * [支持tcp和udp转发 / 支持四层代理转发 #123](https://github.com/chaitin/SafeLine/issues/123)
> 
> 简单解释一下，反向代理是 waf 需要对 http 流量进行检测与清洗，如果反代不能正常工作的话，tcp 反代端口更可能存在问题。所以方便的话，最好是反馈一下具体遇到了什么问题，我们先 case by case 地解决一下。如果不需要 http 流量清洗，只需要 tcp 转发的话，那其实属于网关设备的需求，只是 waf 简单集成一下方便一点，那可以在上面的 #123 讨论。
> 
> 不完全支持 nginx 能力是因为 nginx 的功能太复杂且灵活了，更适合专业的开发或运维使用。完全支持的话不仅成本高，还会提高软件的使用门槛。有较强的自定义 nginx config 需求的话，可以搜索官网文档 “自定义站点 nginx config” 操作，或者再加一层 nginx 反代来满足需求。当然，我们也会持续观察反馈，考虑增加一些简单的配置能力。

1.dns验证至少请提供一种短期解决方案，比如用户通过certbot或者acme.sh自动续签然后由面板cli自动更新也可以接受。
 1.1 无论是certbot还是acme.sh都提供了dns验证接口，用户只需指定所使用的DNS服务商和验证秘钥即可完成自动签发验证。
 certbot
 https://eff-certbot.readthedocs.io/en/latest/using.html#dns-plugins
 acme.sh
 https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
 个人推荐后者，因为它提供原生的dns验证接口，并支持了160家DNS服务商和主机商。
https://github.com/acmesh-official/acme.sh/wiki/dnsapi

2.可以提供类似于宝塔的nginx config编辑页供高级用户自行编辑配置文件。

**Comment by AlliotTech** [comment]
> 1.dns验证至少请提供一种短期解决方案，比如用户通过certbot或者acme.sh自动续签然后由面板cli自动更新也可以接受。

其实证书续期的问题可以曲线救国，调取外部的证书，利用接口来实现定期更新雷池里托管的证书，甚至雷池的免费证书申请都没必要， 这也有效的解耦了
参考： https://github.com/chaitin/SafeLine/issues/782#issuecomment-2031359992
