### ISSUE TITLE
[Bug] 貌似身份认证功能在有些情况下无法正常触发

### ISSUE THREAD

**Issue by chettestwef** [chaitin/SafeLine#661]
### 问题描述

貌似身份认证功能在有些情况下无法正常触发，我在edge浏览器登录后打开无痕浏览器、chrome、手机via浏览器（数据流量）、
手机via浏览器（WIFI）可以直接访问，重新禁用启用后恢复正常

### 版本号

4.3.2

### 复现方法

这个问题是玄学问题，无法复现

### 期望的结果

修复这个问题

**Comment by Lorna0** [comment]
没有复现方法，先 close，遇到再说
