### ISSUE TITLE
[建议] 可以在管理页面上可视化查询所有访问雷池的请求

### ISSUE THREAD

**Issue by xautlmx** [chaitin/SafeLine#662]
### 背景与遇到的问题

目前虽然可以通过修改`resources/nginx/nginx.conf`文件配置`access_log`参数开启记录所有访问雷池的请求的功能，但是只能通过CLI进行查看，无法在雷池管理页面上可视化查询。

### 建议的解决方案

新增访问日志菜单栏功能，将正常的访问请求（除攻击事件外的正常的访问日志）显示在此菜单栏中，并支持根据源IP等条件进行搜索。

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/145
