### ISSUE TITLE
[建议] 按量付费的服务器使用雷池后，流量消耗变大了

### ISSUE THREAD

**Issue by sunskyx** [chaitin/SafeLine#663]
### 背景与遇到的问题

猜测是gzip和brotli压缩问题，我之前gzip设置的压缩等级是5，brotli压缩等级是6，然后压缩类型额外添加了woff，woff2，ttf，otf这些字体的压缩，雷池这部分配置修改后无效，重启又还原了，还有雷池管理页面能不能也优化下，每次打开管理页面都要消耗好几兆流量

### 建议的解决方案

希望能开放gzip和brotli这部分的权限，能让用户自己设置压缩等级和压缩类型

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
