### ISSUE TITLE
[Bug]  雷池设置ssl

### ISSUE THREAD

**Issue by voctot** [chaitin/SafeLine#665]
### 问题描述

雷池设置ssl，通过域名访问，一直处于加载状态，无法进入。
<img width="1270" alt="20240207101004" src="https://github.com/chaitin/SafeLine/assets/36097179/cf85f46e-ed59-497e-85e5-d95c7aa84f4c">
<img width="1130" alt="20240207101100" src="https://github.com/chaitin/SafeLine/assets/36097179/c201559d-f433-4814-b754-6169ea0f10b7">

### 版本号

4.3.2

### 复现方法

1、防护站点
2、添加站点
3、添加雷池域名和监听的端口，上游服务器填写服务器ip加雷池服务的端口

### 期望的结果

通过域名ssl访问雷池服务。

**Comment by DeronW** [comment]
@voctot  waf 只是 http 的代理，一般来说不会出现长时间无响应状态，即使雷池 ssl 配置错误的话，浏览器也会立刻给出提示，不会卡在空白页面。请先检查防火墙配置和上游服务器是否能正常响应。也需要检查 雷池站点的 ssl 是否有正确配置。
