### ISSUE TITLE
[Bug] 经过WAF的图片会被增加No-Gzip-Compression: true，导致上传图片url解析失败

### ISSUE THREAD

**Issue by JrDw0** [chaitin/SafeLine#666]
### 问题描述

最近在测图生图的AI绘图接口功能。排查发现用任意经过WAF的OSS图片去上传图片文件给AI绘图的接口，会返回读取失败。
{"request_id":"31891d34-0113-90b4-aae2-311712e4ce9c","output":{"task_id":"646a1d6e-2b61-435d-9dc8-9e6e393a6d58","task_status":"FAILED","submit_time":"2024-02-06 09:51:55.341","scheduled_time":"2024-02-06 09:51:55.379","end_time":"2024-02-06 09:51:55.615","code":"InvalidURL","message":"The request URL is invalid, make sure the url is correct and is an image"},"usage":{"image_num":0}}
联系接口方配合调查了一下，反馈如下
![image](https://github.com/chaitin/SafeLine/assets/37445725/daf61dfb-201e-4ad7-9a40-8e391d3a755a)
换了个另外没过WAF的OSS抓包比较了一下，图片包内容基本上没区别，但是经过WAF的图片包全都会多一个No-Gzip-Compression: true的header，怀疑是这个原因，这个头是起什么作用，是否能去除？
![image](https://github.com/chaitin/SafeLine/assets/37445725/f55ef097-fe1a-4f5f-a723-7a7b1e194b9c)
![image](https://github.com/chaitin/SafeLine/assets/37445725/8dcb444d-05d6-46f4-965a-b9c23fe4ccab)

### 版本号

4.3.2

### 复现方法

搭一个经过WAF的OSS并传图片，访问图片url存在No-Gzip-Compression: true
的返回头
去上传给阿里大模型绘图API返回非法的图片url

该大模型API对应文档如下
https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-wanxiang-style-repaint?spm=a2c4g.11186623.0.0.67677defQEYJF0

curl命令如下
curl --location 'https://dashscope.aliyuncs.com/api/v1/services/aigc/image-generation/generation' \
--header 'X-DashScope-Async: enable' \
--header 'Authorization: Bearer <YOUR-DASHSCOPE-API-KEY>' \
--header 'Content-Type: application/json' \
--data '{
    "model": "wanx-style-repaint-v1",
    "input": {
        "image_url": "https://public-vigen-video.oss-cn-shanghai.aliyuncs.com/public/dashscope/test.png",
        "style_index": 3
    }
}'

### 期望的结果

经过WAF的图片文件附加的No-Gzip-Compression: true的header能够去除，图片url能够正常传给其他API使用

**Comment by xbingW** [comment]
测了下，没发现有这个 header，麻烦更新到最新版看看
