### ISSUE TITLE
[建议] 期望可以在没有tengine容器时也能正常修改配置

### ISSUE THREAD

**Issue by longjuan** [chaitin/SafeLine#668]
### 背景与遇到的问题

我通过t1k插件，与safeline进行通讯实现防护效果。
在之前的版本中，我对compose文件中的tengine容器相关部分进行了删除，可以正常使用、修改配置并拦截，能正常使用。
但是最近的版本，如果我不启动tengine容器，在修改防护模块配置时会报`TCD Service is AbNormal`错误。
tengine容器在我机器上占用了大概200M+的内存，对于我服务器资源占用较大。

### 建议的解决方案

期望可以在没有tengine容器时也能正常修改防护模块配置

**Comment by xbingW** [comment]
太特殊了，暂不考虑支持
