### ISSUE TITLE
[建议] 支持调整Gzip压缩率

### ISSUE THREAD

**Issue by yukaidi1220** [chaitin/SafeLine#669]
### 背景与遇到的问题

如题，宝塔面板的nginx就可以直接调整gzip压缩率

**Comment by DeronW** [comment]
@yukaidi1220  宝塔是托管类产品，它什么都想做，雷池是 waf，专注安全检测和防护，雷池不是套壳 nginx，如果想要灵活配置 nginx 的功能，建议独立使用一个 nginx 来实现

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
