### ISSUE TITLE
希望增加HTTPS跳转功能，谢谢 / 强制 HTTPS 访问

### ISSUE THREAD

**Issue by clqs803** [chaitin/safeline#67]
比如在防护站点里配置了相同域名的80和443的端口规则，就无需干预
如果只添加了443端口规则，则访问域名自动跳转到HTTPS，不知这样可行不？

**Comment by Lorna0** [comment]
是指访问 http://domain 时，自动跳转到 https://domain 么？

这个效果其实要求 waf 监听 80 端口。也就是说添加站点时，如果端口填写 443，系统就自动同时监听 80、443 两个端口，并且把 80 自动重定向到 443。这个操作有点黑盒，容易出问题，如果业务场景特殊，也不方便自定义。我更倾向于保持一定的可控性。

**Comment by clqs803** [comment]
> 是指访问 http://domain 时，自动跳转到 https://domain 么？
> 
> 这个效果其实要求 waf 监听 80 端口。也就是说添加站点时，如果端口填写 443，系统就自动同时监听 80、443 两个端口，并且把 80 自动重定向到 443。这个操作有点黑盒，容易出问题，如果业务场景特殊，也不方便自定义。我更倾向于保持一定的可控性。

其实也不是啥问题，就是图个方便 哈哈。可以关闭问题了

**Comment by Belkuy** [comment]
我这边也有这个问题，主要是在备案时，工作人员那边老是说必须能访问 http://domain/ 才行。

**Comment by Lorna0** [comment]
> > 是指访问 http://domain 时，自动跳转到 https://domain 么？
> > 这个效果其实要求 waf 监听 80 端口。也就是说添加站点时，如果端口填写 443，系统就自动同时监听 80、443 两个端口，并且把 80 自动重定向到 443。这个操作有点黑盒，容易出问题，如果业务场景特殊，也不方便自定义。我更倾向于保持一定的可控性。
> 
> 其实也不是啥问题，就是图个方便 哈哈。可以关闭问题了

是上面说到的这个场景吧？大致理解了，这个场景倒是挺常见的，可以先 Open，收集下更好的交互方案。

**Comment by Lorna0** [comment]
在 3.0 版本中支持：
![image](https://github.com/chaitin/safeline/assets/56920727/98c49a12-6486-4545-881b-7a962ecfa6b8)
