### ISSUE TITLE
[建议] 防护域名中增加指定目录的访问权限

### ISSUE THREAD

**Issue by faritor** [chaitin/SafeLine#670]
### 背景与遇到的问题

若用 nginx 可以配置，指定目录允许那些 ip 端访问，指定目录不允许访问

### 建议的解决方案

在雷池，nginx 配置不允许修改，当在 web 界面重新编辑防护站点时，会被覆盖 nginx 配置

所以希望迭代出该功能，用于拦截特定目录的特定使用需求

**Comment by Lorna0** [comment]
黑名单 里的  路径、源 IP 条件 能满足需要吗？

**Comment by DeronW** [comment]
@faritor  nginx 的目录访问是指 root 参数或者 alias 参数的配置吗？  有例子的话可以贴出来看一下。 因为雷池不能直接托管静态文件，雷池必须配置上游服务器，所以应该没有你描述的控制 “目录访问权限” 的问题

**Comment by Lorna0** [comment]
> 比如防护域名A，设置 [www.a.com/internal](http://www.a.com/internal) 这个路径，只允许 ip 来源 192.168.0.0/24 或者不允许 10.0.0.0/16
> 
> 在 nginx a.com 的配置文件中 增加 location /internal allow 192.168.0.0/24 或者 deny 10.0.0.0/16
> 
> 在防护域名B，设置 [www.b.com/demo](http://www.b.com/demo) 这个路径不允许任何人访问
> 
> 目前如果想要实现这个功能，只能统一在黑名单设置，路径满足 /internal 所有域名都生效，满足 /demo 所有域名生效

黑名单里有个字段是 “域名”
