### ISSUE TITLE
[Bug]  防护配置中的补充规则页面加载失败

### ISSUE THREAD

**Issue by faritor** [chaitin/SafeLine#671]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/32325325/08e79284-0838-4147-9137-d51fde2ec96b)

官网演示站点中，补充规则请求失败，错误提示是请求内部ip

### 版本号

4.3.1

### 复现方法

 官网演示站点在该目录下必现

### 期望的结果

4.3.0 版本中是正常显示的，4.3.1 版本中带入的 bug

**Comment by DeronW** [comment]
@faritor  4.3.2 版本已修复
