### ISSUE TITLE
[建议] 不同防护站点，试用不同的防护规则

### ISSUE THREAD

**Issue by faritor** [chaitin/SafeLine#673]
### 背景与遇到的问题

所有站点共享同一份频率限制，不同站点可能使用不同的规则

### 建议的解决方案

可以自定义配置不同的规则，在站点编辑中选择适用于哪种规则，默认为通用规则

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/209

**Comment by Lorna0** [comment]
还有个：
* https://github.com/chaitin/SafeLine/issues/83
