### ISSUE TITLE
[Bug] 身份认证-源ip匹配-属于ip/不属于ip匹配不能正常生效

### ISSUE THREAD

**Issue by jnczwjm** [chaitin/SafeLine#674]
### 问题描述

身份认证-源ip匹配-属于ip/不属于ip匹配不能正常生效

### 版本号

4.3.2

### 复现方法

1.本机ip添加进测试IP组;
2.添加身份认证，"等于IP"，输入本机ip。可以正常生效;
3.添加身份认证，"属于ip"，并选择测试IP组。不能正常生效。
![4e502881046ccc52533dce6c65e5a6a](https://github.com/chaitin/SafeLine/assets/33956218/df77988d-47a2-403f-8cf3-e4394cfe65cf)
![71f882203848439950b457e5a3391e9](https://github.com/chaitin/SafeLine/assets/33956218/c2a23bf1-260b-4907-a3ed-bc11e89f1563)

### 期望的结果

功能正常生效

**Comment by skyhhjmk** [comment]
把 `通用设置-其他-源 IP 获取方式` 里的从网络连接获取改成从某个http头获取试试？

**Comment by jnczwjm** [comment]
> 把 `通用设置-其他-源 IP 获取方式` 里的从网络连接获取改成从某个http头获取试试？
> 
> 或者会不会是因为你在“内容”里输入ip的时候多打了回车空格什么的，我感觉你这个输入框里的东西间距怪怪的

同一个IP组，在引用在黑白名单里是生效的

**Comment by jnczwjm** [comment]
4.4.1版本依然不能正常生效，通用设置-其他-源 IP 获取方式改过也不行。统一内网测试ip组，黑名单能正常生效，身份认证就是不行。

**Comment by jnczwjm** [comment]
4.4.1版本依然不能正常生效，通用设置-其他-源 IP 获取方式改过也不行。统一内网测试ip组，黑名单能正常生效，身份认证就是不行。

**Comment by zhuxianxian** [comment]
4.4.2版本遇到同样问题，

**Comment by zhuxianxian** [comment]
4.4.2版本遇到同样问题；ip组不存在空格；尝试切换“源IP获取方式”无效。

**Comment by xbingW** [comment]
最新版已修复

**Comment by Lorna0** [comment]
5.1.0 版本中修复
