### ISSUE TITLE
经过雷池反代后，host无法匹配

### ISSUE THREAD

**Issue by qyzhg** [chaitin/SafeLine#675]
### 反馈内容

我的链路是这样的
互联网 -> 雷池 -> nginx -> 内网业务服务器
雷池和nginx是不同的两台服务器，均暴露在公网中，nginx服务器只开了一个端口，而且ip限制了只能通过雷池的服务器访问
只开一个端口的情况下，希望通过server_name域名来区分是哪个服务
但是使用雷池进行反代后，发现host请求头变成了雷池访问的域名，无法正确的匹配服务
这个问题应该如何解决？
用curl测试了一下，强行将host改为nginx的域名之后，会返回错误页
![image](https://github.com/chaitin/SafeLine/assets/55947523/1e7a8915-b605-4635-91eb-7f5e3a8d9a86)

**Comment by a1zaza** [comment]
https://waf-ce.chaitin.cn/docs/faq/other#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9-nginx-conf

自己添加请求头试试

**Comment by Lorna0** [comment]
雷池会原样传递用户发送的 host 给上游服务器。

我理解 nginx 上直接按照互联网用户访问的域名来配置 server 不就好了么，雷池会原样往后发呀

**Comment by QYG2297248353** [comment]
我是存在相似问题，雷池转发后 Host 由原本的 https 变成了 http 似乎没有原样转发

**Comment by QYG2297248353** [comment]
> 我是存在相似问题，雷池转发后 Host 由原本的 https 变成了 http 似乎没有原样转发

![image](https://github.com/user-attachments/assets/249f20f7-e278-4503-8904-3ab637edf468)

经过雷池 443 代理到内网服务器NGINX 80 上 域名正确 协议好像丢失了，与实际不相符

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
