### ISSUE TITLE
[建议]强烈建议增加站点、黑白名单、人机验证导入导出功能 

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#677]
### 背景与遇到的问题

社区版有时升级错误，排查故障太麻烦；
有时在线升级有问题，但用一个新虚拟机装却没有问题。但这样每次要重新添加十几个站点和黑白名单，还有人机验证规则。
为了更好的为雷池社区版做测试，重装需要重新配置各种策略实在是痛苦@@@@@

### 建议的解决方案

建议增加站点、黑白名单、人机验证导入导出功能；
如果程序员大神们任务太忙，请先增加站点配置导入导出功能，如果以后有时间在能把黑白名单和人机验证加上也行。
万分感谢！

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/219

其实直接备份安装目录就可以，升级前都可以备份一下。界面的导入导出功能开发起来还挺麻烦的。
