### ISSUE TITLE
[Bug] 4.3.2版本强制https功能失效

### ISSUE THREAD

**Issue by cangkuai** [chaitin/SafeLine#678]
### 问题描述

我今天新部署了一个服务器发现新装waf后新增一个ssl站点并且开启强制https后，80端口自动跳转不生效。

### 版本号

4.3.2

### 复现方法

1.全新安装waf
2.新建ssl站点
3.打开强制https按钮
4.用非chrome浏览器打开(如360浏览器)

### 期望的结果

能正常跳转http请求到https站点

**Comment by cangkuai** [comment]
系统为debian 12
我发现连80端口都没被占用
![QQ20240218-204948](https://github.com/chaitin/SafeLine/assets/33569578/9610bf2a-3e56-4b97-b00f-ae8119b1d5de)

**Comment by Lvshujun0918** [comment]
感觉可能站点配置有问题，把你的添加站点配置页面发出来看看

**Comment by cangkuai** [comment]
站点配置：
![QQ20240219-131036](https://github.com/chaitin/SafeLine/assets/33569578/c67e7080-86f2-4e69-8f71-8eddfbc8609c)
上游nginx配置文件（已经删除nginx自带的80端口的配置文件，并且已经重启）
![QQ20240219-131244](https://github.com/chaitin/SafeLine/assets/33569578/dffa5861-9dff-450c-96f9-496d6193705e)

**Comment by cangkuai** [comment]
> 这个目前是期望的。“强制 HTTPS” 的 “80 重定向到 443/ssl”，需要站点配置了  80 和 443/ssl 端口才能生效：
> ![image](https://github.com/chaitin/SafeLine/assets/56920727/64015e53-ac2d-4ca5-a607-1501c16efe55)
> 
> 因为 “80 重定向到 443/ssl” 原理上需要 waf 先在 80 端口上收到访问该站点的流量，然后才能重定向到 443 端口。

说真的，建议写清楚一点，括号里面写明必须要有80站点才生效，现在这样太容易让人误解了，比如我理解成如果有ssl站点才生效了

**Comment by Lorna0** [comment]
> > 这个目前是期望的。“强制 HTTPS” 的 “80 重定向到 443/ssl”，需要站点配置了  80 和 443/ssl 端口才能生效：
> > 因为 “80 重定向到 443/ssl” 原理上需要 waf 先在 80 端口上收到访问该站点的流量，然后才能重定向到 443 端口。
> 
> 说真的，建议写清楚一点，括号里面写明必须要有80站点才生效，现在这样太容易让人误解了，比如我理解成如果有ssl站点才生效了

谢谢反馈，我们回头看看能不能给优化一下。上面那个站点本身多配个 80 应该就可以跳转了。
