### ISSUE TITLE
[Bug] 当上游服务器为域名的情况下，域名变更指向后不会刷新

### ISSUE THREAD

**Issue by somygame** [chaitin/SafeLine#679]
### 问题描述

防护站点当上游服务器是动态域名或域名的情况下，不会刷新DNS
编辑提交后会重新刷新一次

### 版本号

4.3.2

### 复现方法

1、将上游服务器设置为域名
2、变更域名的指向，将不会刷新DNS指向

### 期望的结果

希望可以自动更新域名的DNS指向

**Comment by Lorna0** [comment]
duplicate，可以集中讨论：
* https://github.com/chaitin/SafeLine/issues/384
