### ISSUE TITLE
[Bug] 更改Nginx.conf配置后，升级导致mario:latest容器一直重启

### ISSUE THREAD

**Issue by clover0101** [chaitin/SafeLine#680]
### 问题描述

为查看网站代理延迟情况，调整Nginx.conf，开启日志功能，增加请求延迟时间。升级后出现服务无法使用的情况，mario:latest容器一直重启
![微信图片_20240219084806](https://github.com/chaitin/SafeLine/assets/102471626/047829c4-e3ca-4052-a76b-73ca1b73b398)

### 版本号

4.3.0

### 复现方法

1、调整Nginx.conf，开启日志功能，增加请求延迟时间
2、升级版本

### 期望的结果

完善自动升级脚本，对于用户的配置改动，能够正确处理。

**Comment by xbingW** [comment]
realead in 6.4.0
