### ISSUE TITLE
[建议] 黑白名单及人机验证中添加or条件

### ISSUE THREAD

**Issue by skyhhjmk** [chaitin/SafeLine#682]
### 背景与遇到的问题

![Clip_2024-02-19_22-13-00](https://github.com/chaitin/SafeLine/assets/78078552/cc7125dd-b379-4aea-9810-ee2fb00c273d)
目前依然可以实现or条件，即把多个规则分开部署，但这样及其不方便，特别是在自定义规则特别多的情况下（如多个IP在线订阅，要求匹配任意一个就block）

### 建议的解决方案

![Clip_2024-02-19_22-15-20](https://github.com/chaitin/SafeLine/assets/78078552/9a92e312-9d00-40be-bcc1-5ec4de5f2753)
此处增加一个选择器，可选择是and还是or

**Comment by DeronW** [comment]
在摊位 OR 条件会增加一些复杂度。通过添加多个 “规则”，可以实现相同的 OR 条件的效果。对于操作的复杂性，设计上现在还是保持克制的态度

**Comment by Lorna0** [comment]
5.6 支持在单个匹配项内输入多个值，多个值之间为 “OR” 关系，很大程度上满足了该 issue 的需要：
![image](https://github.com/chaitin/SafeLine/assets/56920727/c6e030b5-dfbc-4435-b1f8-42675dc9ee89)

如果有进一步的规则优化需要，可以再提个反馈。

**Comment by xbingW** [comment]
7.3.0 已支持
