### ISSUE TITLE
Rate Limited for each website on SafeLine's management interface

### ISSUE THREAD

**Issue by huynhthanhdan1710** [chaitin/SafeLine#683]
### 背景与遇到的问题

I appreciate your rate limit function, it can be operated directly on the management interface.
However, this function will apply to all websites I have configured on the Safeline system.
For some special cases, I just want to set different limits for 1 or a few different websites on my Safeline device.
I can do it by editing it manually under the command line interface however it disappears when I edit on the management interface.
Why don't we develop this rate limit feature similar to the Captcha feature?
It allows editing and turning rate limit rules on and off for each individual website, making it easier to prevent attacks without affecting other websites.
![2024-02-21_09-24](https://github.com/chaitin/SafeLine/assets/105242569/726ad990-3505-499f-be2e-9f272eb2c877)

**Comment by xbingW** [comment]
The latest version already supports setting different restriction levels for individual websites. You can upgrade to experience it.
