### ISSUE TITLE
[建议] 可以修改header里面Server的内容

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#687]
### 背景与遇到的问题

![image](https://github.com/chaitin/SafeLine/assets/41245552/b9dff789-4d87-430b-b2c6-0e53ba882ee3)
建议可以将这里的Sever内容改成雷池或者waf之类的

**Comment by Lorna0** [comment]
目前会导致什么直接的问题么。还是说主要考虑到规范性的需求，检查方便等等长期需要呢。

**Comment by Lvshujun0918** [comment]
不会导致直接性问题，但是感觉Server头带有WAF会更规范，或者可以选择开启

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
