### ISSUE TITLE
[建议] 添加浏览器ua检测和自定义返回码

### ISSUE THREAD

**Issue by Gaimoydev** [chaitin/SafeLine#694]
### 背景与遇到的问题

由于绝大多数的扫描/爬虫需要一直切换ua防止被封禁
自定义返回码可以伪装

### 建议的解决方案

通过检测如果一个ip在一个时间段内多次换ua 就可以将他直接封禁/人机验证 现在有部分可以绕机器人检测这也是一种解决方法

**Comment by Lvshujun0918** [comment]
UA似乎是可以通过黑名单来屏蔽 至于你说的“在一个时间段内多次换ua” 感觉比较难实现

**Comment by Gaimoydev** [comment]
> UA似乎是可以通过黑名单来屏蔽 至于你说的“在一个时间段内多次换ua” 感觉比较难实现

我指的换ua是对于爬虫方来说 我们防御方可以检测这个ip(爬虫方)在一个时间段是否去多次更换了这个ua

**Comment by cli-r** [comment]
这样不太现实，因为家宽很多是共用出口ip的，很容易导致误封
