### ISSUE TITLE
[Bug] IP组中添加IP时不支持32位掩码

### ISSUE THREAD

**Issue by GodRuiAn** [chaitin/SafeLine#696]
### 问题描述

有些IP库严格按照CIDR格式，即会出现 123.123.123.123/32 表示单一IP地址。这种32位掩码的IP地址填入IP组列表时雷池会报格式错误。

### 版本号

4.3.3

### 复现方法

<img width="546" alt="image" src="https://github.com/chaitin/SafeLine/assets/13276572/5cec2cb5-02d9-4727-a8c4-f3e8cfcc604d">
添加自定义内容的IP组

### 期望的结果

IP组支持32位掩码。

**Comment by gearfox** [comment]
是的，确实有这个问题
