### ISSUE TITLE
是否可以根据时间范围筛选日志，并用饼图统计

### ISSUE THREAD

**Issue by zhudd521** [chaitin/safeline#70]
方便统计

**Comment by zclaiqcc** [comment]
饼图统计哪些信息呢？或者说饼图的每一块儿是统计的什么数据？

**Comment by myname365** [comment]
攻击类型，访问路径（Url），攻击来源、目的IP

**Comment by zhudd521** [comment]
> 攻击类型，访问路径（Url），攻击来源、目的IP

就是这样 😄

**Comment by huangyitong** [comment]
【检测日志】是否可以添加域名筛选（根据攻击地址获取到域名），然后加个时间筛选（比如选择2023/05/01-2023/05/20这个区间的日志）

**Comment by zclaiqcc** [comment]
@huangyitong 域名筛选已经添加了

**Comment by Lorna0** [comment]
多个需求混在一个 issue 不太方便跟进点赞情况和实现进度，也不方便大家讨论，这个 issue 就先关闭了。
“检测日志按日期筛选” 的需求可以在此处继续跟进： https://github.com/chaitin/safeline/issues/102
统计图表相关的需求可以在此处继续跟进：https://github.com/chaitin/safeline/issues/89
