### ISSUE TITLE
[建议] 支持api操作

### ISSUE THREAD

**Issue by xqw8889** [chaitin/SafeLine#700]
### 背景与遇到的问题

比如api维护黑白名单规则内容以及人机验证规则等热点功能，这将大大提升使用场景

**Comment by xbingW** [comment]
最新版可以使用 apitoken 了，参考文档 https://docs.waf-ce.chaitin.cn/%E6%9B%B4%E5%A4%9A%E6%8A%80%E6%9C%AF%E6%96%87%E6%A1%A3/OPENAPI
