### ISSUE TITLE
[Bug] 使用雷池代理WordPress网站样式会失效

### ISSUE THREAD

**Issue by mdhyy008** [chaitin/SafeLine#703]
### 问题描述

首先，服务器安装了雷池，如果不用雷池代理网站，直接访问域名，会提示网关错误。

我的主要问题：如果用了雷池代理WordPress网站，打开网站会发现css和js请求错误了，查看F12发现使用的http请求的，雷池开启强制https也没用。

最后迫不得已，卸载了雷池。直接使用宝塔进行网站代理才正常。
但我还是比较喜欢用雷池。希望官方能帮忙排查一下，是wordpress的问题还是雷池。😁

### 版本号

2月份的最新版

### 复现方法

安装雷池和wordpress，然后使用雷池代理wp，通过域名https进行访问，会出现部分文件(css,js)使用http访问源站并且出现被浏览器拦截的问题。

### 期望的结果

使用雷池代理wp，正常访问网站和管理后台

**Comment by Lvshujun0918** [comment]
我这里使用正常

**Comment by Lvshujun0918** [comment]
把F12控制台里的错误请求贴出来看看

**Comment by mdhyy008** [comment]
错误信息：`Even though the initial HTML page is loaded over a secure HTTPS connection, some resources like images, stylesheets or scripts are being accessed over an insecure HTTP connection. Usage of insecure resources is restricted to strengthen the security of your entire site.
To resolve this issue, load all resources over a secure HTTPS connection.`

**Comment by mdhyy008** [comment]
正确的配置可以截图给我参考一下嘛












BAI
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月29日(周四) 晚上8:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chaitin/SafeLine] [Bug] 使用雷池代理WordPress网站样式会失效 (Issue #703)




 
这个是因为 http 页面加载了 https 的资源被浏览器禁止了吧
 我猜是反向代理配的不对

**Comment by safe1ine** [comment]
你看看是不是 http 和 https 的资源混在一起来，解决这个问题就行

**Comment by skyhhjmk** [comment]
建议使用hsts头来进行http to https的重定向，网上流传着一种关于ssl插件的说法，即使用此类插件会影响性能，因为其均为动态修改链接的

**Comment by devhaozi** [comment]
反代的地址写 HTTPS 的，写 HTTP 的 wp 就会当成 HTTP 处理，不加载 HTTPS 资源。

**Comment by mdhyy008** [comment]
我是通过雷池 http:127.0.0.1&nbsp; →&nbsp; https:域名，这是错误的嘛












BAI
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月14日(周四) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chaitin/SafeLine] [Bug] 使用雷池代理WordPress网站样式会失效 (Issue #703)




 
反代的地址写 HTTPS 的，写 HTTP 的 wp 就会当成 HTTP 处理，不加载 HTTPS 资源。

**Comment by devhaozi** [comment]
> 我是通过雷池 http:127.0.0.1&nbsp; →&nbsp; https:域名，这是错误的嘛 BAI ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月14日(周四) 下午3:20 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chaitin/SafeLine] [Bug] 使用雷池代理WordPress网站样式会失效 (Issue #703) 反代的地址写 HTTPS 的，写 HTTP 的 wp 就会当成 HTTP 处理，不加载 HTTPS 资源。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

错误，应该是 `https://127.0.0.1`。

如果一定要使用 HTTP 的话，`wp-config.php` 中添加：

```php
$_SERVER['HTTPS'] = 'on';
const FORCE_SSL_LOGIN = true;
const FORCE_SSL_ADMIN = true;
```

**Comment by mdhyy008** [comment]
好的，了解！问一个 题外话，如果同一台服务器，同时安装宝塔和雷池，但雷池显示80被占用了，这种有遇到过的嘛

**Comment by devhaozi** [comment]
> 好的，了解！问一个 题外话，如果同一台服务器，同时安装宝塔和雷池，但雷池显示80被占用了，这种有遇到过的嘛

建议宝塔改 nginx 监听端口，不监听80 即可

**Comment by Lvshujun0918** [comment]
> > 我是通过雷池 http:127.0.0.1  →  https:域名，这是错误的嘛 BAI _**@**_.***
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年3月14日(周四) 下午3:20 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [chaitin/SafeLine] [Bug] 使用雷池代理WordPress网站样式会失效 (Issue #703) 反代的地址写 HTTPS 的，写 HTTP 的 wp 就会当成 HTTP 处理，不加载 HTTPS 资源。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 错误，应该是 `https://127.0.0.1`。
> 
> 如果一定要使用 HTTP 的话，`wp-config.php` 中添加：
> 
> ```
> $_SERVER['HTTPS'] = 'on';
> const FORCE_SSL_LOGIN = true;
> const FORCE_SSL_ADMIN = true;
> ```

如果改为 `https://127.0.0.1`，需要自签发证书，请注意
