### ISSUE TITLE
[Bug] safeline-luigi/api/receive 请求失败

### ISSUE THREAD

**Issue by Ne0o0o** [chaitin/SafeLine#706]
### 问题描述

mario.log 中大量请求失败信息

time="2024-xx-xx xx:xx:xx" level=error msg="请求失败:Post \"http://safeline-luigi/api/receive\": dial tcp 172.22.222.7:80: connect: cannot assign requested address" file=stat.go func=/patronus/safeline-ce/mario/server/transformer/stat.forwardToLuigi line=81

### 版本号

4.3.3

### 复现方法

./wrk -c 20 -t 8 -d 30s -R 5k

### 期望的结果

-

**Comment by yrluke** [comment]
你这是在本机上进行压测的吧，看上去是你的压测行为占满了本机的端口，导致服务无法创建新的端口了

**Comment by Ne0o0o** [comment]
> 你这是在本机上进行压测的吧，看上去是你的压测行为占满了本机的端口，导致服务无法创建新的端口了

不是本机，大概2k QPS就会出现。

**Comment by medasz** [comment]
我也遇到了同样的问题，在6.0.2版本
time="2024-06-12 11:06:08" level=error msg="请求失败:Post \"http://safeline-luigi/api/receive\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" file=stat.go func=/patronus/safeline-ce/mario/server/transformer/stat.forwardToLuigi line=101

**Comment by xbingW** [comment]
released in 6.4.0
