### ISSUE TITLE
[建议] 雷池社区版管理端页面适配手机浏览

### ISSUE THREAD

**Issue by ct-jaryn** [chaitin/SafeLine#709]
### 背景与遇到的问题

手机查看管理端

### 建议的解决方案

雷池社区版管理端页面适配手机浏览

**Comment by Lorna0** [comment]
UI 完全适配移动端的工作量比较大。现在也可以直接用，有啥明显阻碍的话我们可以先简单改一下。

**Comment by upbeat-backbone-bose** [comment]
+1

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
