### ISSUE TITLE
[建议] 源站那获取不到真实ip，要能配置后获取真实ip，建议优化一下现有功能能好用一些

### ISSUE THREAD

**Issue by ct-jaryn** [chaitin/SafeLine#710]
### 背景与遇到的问题

用雷池waf，这块填了xff，但是源站那获取真实ip是cdn的ip
并不关心中间cdn的ip，希望有便捷功能可以一键开启获取真实ip 
类问题WAF前有反代的情况

### 建议的解决方案

源站那获取不到真实ip，要能配置后获取真实ip ，建议优化一下现有功能

**Comment by Lvshujun0918** [comment]
那你应当调整源站吧，雷池会把XFF传递下来的啊（类似于：X-Forward-From:访客IP，cdnIP，按照访问顺序形成列表），如果要获取真实访客IP，应该是取第一个吧

**Comment by Lorna0** [comment]
需要在源站上调整配置。雷池会默认在 XFF 中增加自己的 IP，其他 CDN 所传递的头会原样往后传输。可以在源站上查询 header 中那个是实际的客户端 IP。
