### ISSUE TITLE
[建议] tcp连接数超多  那个luigi cpu内存占用大

### ISSUE THREAD

**Issue by ct-jaryn** [chaitin/SafeLine#714]
### 背景与遇到的问题

 使用机器配置不高，发现新版本tcp连接数超多  那个luigi cpu内存占用大 

### 建议的解决方案

优化CPU的内存占用

**Comment by yrluke** [comment]
我在测试环境测试了一下，qps 200, cpu 占用不到1核，内存 10M，能再提供更详细的复现步骤吗

**Comment by fankejing-just** [comment]
4.3.3开始的BUG，到现在4.4.2依然存在，4.3.2就很正常
