### ISSUE TITLE
[建议] 未开启SSL转发到HTTPS协议无限重定向

### ISSUE THREAD

**Issue by Borg99** [chaitin/SafeLine#718]
### 背景与遇到的问题

比如我今天用80端口走http协议转发到后端https浏览器会无限重定向

### 建议的解决方案

建议增加提醒需开启443端口并导入SSL证书实现HTTPS访问

**Comment by yrluke** [comment]
这件事确实是是一件很尴尬的问题，作为上一跳设备雷池确实没有办法预知上游服务器会给出什么样的响应，也就很难判断是否需要弹出提示
另外：很大的一部分用户，其实是不需要https的，所以如果用户只听了80的话，也没有办法强制提示他需要https和443

**Comment by Lorna0** [comment]
无限重定向的原因不在于没有开启443端口，而在于上游服务器强制 http 跳转 https 了吧。交流群里看到很多犯这个错的，把上游服务器的 http 改成 https 就不会无限重定向了。

**Comment by Lorna0** [comment]
暂时没有有更多信息，有的话可以再评论反馈一下
