### ISSUE TITLE
[建议] 后台可以修改控制台端口 或者可以给控制台加本地waf防御

### ISSUE THREAD

**Issue by dpifox** [chaitin/SafeLine#719]
### 背景与遇到的问题

保护控制台 给控制台加本地的waf
或者可以修改控制台默认端口

### 建议的解决方案

保护控制台 给控制台加本地的waf
或者可以修改控制台默认端口

**Comment by TScci** [comment]
- 想用waf给管理后台做防护的话，新增防护站点监听safeline管理端口可以实现

- 修改默认端口可以通过修改`~/safeline/.env`文件MGT_PORT参数实现

**Comment by Lorna0** [comment]
可以在后台参考官网文档修改，文档可以在技术文档右上角搜索 “端口” 找到：
![image](https://github.com/chaitin/SafeLine/assets/56920727/733ca985-9d02-4695-b83d-eb3cf1e2903e)

因需求不强，目前不会考虑在界面上做配置。
