### ISSUE TITLE
how to download source code of Safeline?

### ISSUE THREAD

**Issue by minhtribtc** [chaitin/SafeLine#720]
### 反馈内容

hi, i want to develop safeline, how and where can i download source code?

**Comment by Lvshujun0918** [comment]
May be there isn't any. Only part of them is open score.

**Comment by Lorna0** [comment]
Safeline detects attack based on semantic analysis technology. The core code of the algorithm has been open source here: https://github.com/chaitin/yanshi. 

The web manager part is not quite mature enough for it, we will try our best. Thank you very much for your support!
