### ISSUE TITLE
部署脚本中使用的Docker安装脚本不支持openEuler安装。

### ISSUE THREAD

**Issue by 888hou** [chaitin/SafeLine#721]
### 反馈内容

通用 Linux 发行版自动安装部署 Docker 的方法（curl -fsSL https://get.docker.com/ | sh），默认不支持 openEuler，当执行上面的命令时，报错如下：
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
ERROR: Unsupported distribution 'openeuler'
所以，需要选择 RPM 包手工安装部署的方案：
1、配置软件源 下载 repo 配置文件
curl -fsSL https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/docker-ce.repo -o /etc/yum.repos.d/docker-ce.repo
2、修改安装源为国内地址，适用于访问国外网络受限的环境
sed -i 's#https://download.docker.com#https://mirrors.tuna.tsinghua.edu.cn/docker-ce#' /etc/yum.repos.d/docker-ce.repo
3、openEuler 的使用方式近似 CentOS，因此，修改软件源的配置，使用 centos 7 的软件源
sed -i 's#$releasever#7#g' /etc/yum.repos.d/docker-ce.repo
4、安装 Docker
yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
5、启动 Docker
systemctl enable docker --now
systemctl start docker

**Comment by yrluke** [comment]
https://github.com/docker/docker-install/ 可以去这个地方提issue

**Comment by fankejing-just** [comment]
openEuler 先手动安装  docker 和 docker compose 之后就可以顺利安装了
