### ISSUE TITLE
[建议] 页面做个有导出导入的功能，每次升级都很怕配置丢失

### ISSUE THREAD

**Issue by ct-jaryn** [chaitin/SafeLine#724]
### 背景与遇到的问题

页面做个有导出导入的功能，每次升级都很怕配置丢失

### 建议的解决方案

增加导入导出

**Comment by gearfox** [comment]
是啊，求这个功能

**Comment by zhuanmentiwen** [comment]
同求备份站点配置导出功能。不需要备份系统整个内容，主要是站点配置先能让导出来也行。

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/90
