### ISSUE TITLE
centos7 安装失败

### ISSUE THREAD

**Issue by vela-security** [chaitin/SafeLine#727]
### 问题描述

failed to register layer: unlinkat /var/lib/apt/mirrors: invalid argument

### 版本号

latest

### 复现方法
bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/setup.sh)"

![image](https://github.com/chaitin/SafeLine/assets/7379009/6b60a412-0aa8-458b-ade9-777c643767fd)

### 期望的结果

支持centos 7

**Comment by yrluke** [comment]
使用华为云加速，或者参考https://www.chenshaowen.com/blog/pull-images-unlinkat.html
试试

**Comment by vela-security** [comment]
已经解决了

**Comment by stuaclon** [comment]
> 已经解决了

请问怎么解决的呀？
