### ISSUE TITLE
[Bug] 通过t1k插件的请求会无视语义分析的设置而进行拦截

### ISSUE THREAD

**Issue by longjuan** [chaitin/SafeLine#728]
### 问题描述

我通过OpenResty中安装t1k实现防护，最近我发现无论控制台中无论怎么设置“语义分析”为仅观察/禁用，请求都会被拦截

### 版本号

4.4.0

### 复现方法

1. OpenResty中安装t1k
2. 雷池控制台中“语义分析”全部设置为仅观察/禁用
3. 发送恶意请求
4. 请求被拦截

### 期望的结果

当“语义分析”为仅观察/禁用，请求不被拦截

**Comment by Lvshujun0918** [comment]
![image](https://github.com/chaitin/SafeLine/assets/41245552/238713f5-e0ac-479c-bcca-0325cb1a1046)
或许需要修改这个？

**Comment by longjuan** [comment]
> ![image](https://private-user-images.githubusercontent.com/41245552/312306900-238713f5-e0ac-479c-bcca-0325cb1a1046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzUzNTIsIm5iZiI6MTcxMDMzNTA1MiwicGF0aCI6Ii80MTI0NTU1Mi8zMTIzMDY5MDAtMjM4NzEzZjUtZTBhYy00NzljLWJjY2EtMDMyNWNiMWExMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNWIwNmIzOGE3YzEyODUxMTU2ZGMwNTE0NmI2NDlkNGI0YzM5OGVhNmQ0MTA2NTE4Y2E1YmIyZTIyYWRjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Anft3zd8D1AGemQ_OLDdwLIy5rS-bIHloNFoyfCH4aY) 或许需要修改这个？

确实改这个可以实现控制，之前在web ui上改也能影响t1k，可能现在的模式才是预期的？
我先关闭issuse了，谢谢。
