### ISSUE TITLE
[建议] 疑似nginx的gzip未生效

### ISSUE THREAD

**Issue by qq8554650** [chaitin/SafeLine#730]
### 背景与遇到的问题

Version 4.4.0。详见图
左边是原waf，右边为自建nginx代理并开了gzip
（
    gzip on;
gzip_types    text/plain application/javascript application/x-javascript text/javascript text/xml text/css;

）
waf中虽有gzip，但似乎不生效
<img width="759" alt="3b6c9d240cdda8194355b55e8a45f1f" src="https://github.com/chaitin/SafeLine/assets/22789241/66202531-25d4-4831-865f-00fbea433923">

**Comment by yrluke** [comment]
这个原因是：雷池默认开启了br压缩，在同时开启的情况下，nginx会默认使用br压缩，如果希望使用gzip，可以关闭br压缩

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
