### ISSUE TITLE
[Bug] safeline-luigi接口数据异常

### ISSUE THREAD

**Issue by zhxind** [chaitin/SafeLine#731]
### 问题描述

2024/03/08 10:33:06 [ERROR] rate-limit rate_limit/rateLimit.go:174 invalid character '<' looking for beginning of value
2024/03/08 10:33:06 [ERROR] rate-limit cmd/main.go:39 invalid character '<' looking for beginning of value
2024/03/08 10:33:06 [ERROR] cmd/main.go:41 invalid character '<' looking for beginning of value

### 版本号

4.4.1

### 复现方法

![image](https://github.com/chaitin/SafeLine/assets/13533768/aea0f4e2-93bb-4d48-9b8c-6aaa38bf6759)

### 期望的结果

修复问题

**Comment by yrluke** [comment]
是启动的时候还是什么时候呢

**Comment by zhxind** [comment]
从4.3.0版本使用upgrade.sh升级到4.4.1之后就一直这样。回退到4.3.0版本是正常

**Comment by yrluke** [comment]
4.4在优化限频的过程中确实是增加了这个地方，所以能说一下是在启动的时候有这个报错还是什么时候呢，感谢

**Comment by upbeat-backbone-bose** [comment]
> 4.4在优化限频的过程中确实是增加了这个地方，所以能说一下是在启动的时候有这个报错还是什么时候呢，感谢

v4.4.1遇到了同样的问题，看日志时间应该是在升级后启动时产生的。 @yrluke 
![image](https://github.com/chaitin/SafeLine/assets/438092/2c032d03-8980-4b98-8b30-1410f81c36e7)

**Comment by yrluke** [comment]
如果是启动时产生的话，我理解是预期的，只是因为各个服务启动的顺序快慢不一致导致的，可以忽略，如果大量的报这个错误，才需要重视

**Comment by zhxind** [comment]
升级后luigi接口一直没有数据返回，查看容器日志有好几条这种报错

**Comment by yrluke** [comment]
如果最后显示了Server ready at :80就证明成功拉起来了

**Comment by zhxind** [comment]
@yrluke 发现好像是配置了高频访问限制就会出现QPS显示为：0
![image](https://github.com/chaitin/SafeLine/assets/13533768/c03b91d9-84bd-4fc3-be8c-15ed2ffe5a08)

safeline-fvm 容器有以下报错：
2024/03/11 14:38:39 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
2024/03/11 14:38:53 INFO Push FSL success
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:53 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:54 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:54 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:54 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:54 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_116_63_12_12_challenge
2024/03/11 14:38:54 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
2024/03/11 14:46:16 INFO Push FSL success
2024/03/11 14:47:21 INFO Push FSL success
fvm_update(): failed to insert selector id acl_blocked_111_127_255_203_challenge
2024/03/11 14:47:21 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
fvm_update(): failed to insert selector id acl_blocked_111_127_255_203_challenge
2024/03/11 14:47:21 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed
2024/03/11 14:48:03 INFO Push FSL success
fvm_update(): failed to insert selector id acl_blocked_124_234_116_106_challenge
2024/03/11 14:48:03 [ERROR] fvm/fvm_grpc.pb.go:316 error:%v update failed: update framework failed

**Comment by xbingW** [comment]
released in 6.4.0
