### ISSUE TITLE
[Bug] 手动更新证书文件并重启容器后，【证书管理】界面的有效期时间没有同步更新

### ISSUE THREAD

**Issue by mabutou** [chaitin/SafeLine#733]
### 问题描述

- 我使用了专门的自动化脚本进行证书的自动续签，续签新证书后自动替换safeline/resources/nginx/certs/目录下的证书文件，同时重启 tengine 容器。
- 但是【证书管理】界面的有效期时间没有同步更新，还是旧证书的有效期。

### 版本号

4.4.1

### 复现方法

1. 替换 safeline/resources/nginx/certs/cert_1.crt 和 safeline/resources/nginx/certs/cert_1.key 两个文件为新证书的对应文件。
2. docker restart safeline-tengine 命令重启tengine 容器后，【证书管理界面】的有效期时间没有同步更新。
3. 换成 docker compose down && docker compose up -d 命令重启了所有容器，界面上还是没更新。

### 期望的结果

- 希望界面上也能同步检测到新的证书。

**Comment by yrluke** [comment]
目前证书的各项数据是以数据库为准，文件系统的改动并不会引发数据库数据的更新

**Comment by AlliotTech** [comment]
@mabutou , https://github.com/chaitin/SafeLine/issues/782#issuecomment-2031359992  可以看看这种方式。
