### ISSUE TITLE
添加了5组ip白名单（每组1万个）之后，后台修改任何配置都会卡,mgt进程占用cpu资源非常高

### ISSUE THREAD

**Issue by acheng-floyd** [chaitin/SafeLine#735]
### 问题描述

waf部署在4核8g的机器上，没添加ip白名单之前后台操作都很流畅，添加了5组ip白名单，每组1万个之后，后台修改任何配置都会卡，查看waf服务器发现mgt进程cpu一直很高

<img width="1439" alt="image" src="https://github.com/chaitin/SafeLine/assets/62228888/3771e428-9b11-4003-bda5-2f89e8b26caa">

<img width="871" alt="image" src="https://github.com/chaitin/SafeLine/assets/62228888/5da4a0d1-8b4a-4891-802d-ddac51b40199">

### 版本号

4.4.2

### 复现方法

1. 添加白名单
2. 修改后台任意配置

### 期望的结果

添加较多ip白名单之后，后台操作依然能较快响应

**Comment by AlliotTech** [comment]
同样可以复现。

**Comment by AlliotTech** [comment]
问题应该在于接口没有做分页，每次前端加载都查出了所有的IP列表。

**Comment by xbingW** [comment]
新版本解决了
