### ISSUE TITLE
[建议] DDNS转IP白名单规则

### ISSUE THREAD

**Issue by QYG2297248353** [chaitin/SafeLine#738]
### 背景与遇到的问题

家庭宽带IP不定期变化，使用DDNS服务映射到域名地址，我需要在白名单规则中添加自己家宽带的IP。

添加白名单时只允许 `IP地址`
我希望增加域名选项，将域名解析出IP，进行效验。
解析时机：
1. 首次请求，且保留一段有效时间(5-10分钟)
2. 距离最后一次请求超过有效时间(5-10分钟)
3. 预热解析，不定时的解析一次确保服务正常

### 建议的解决方案

建议 防护配置 >> 黑白名单 >> 匹配方式
增加DDNS域名选项

解析时机：
1. 首次请求，且保留一段有效时间(5-10分钟)
2. 距离最后一次请求超过有效时间(5-10分钟)
3. 预热解析，不定时的解析一次确保服务正常

> 当前我的解决方案为 脚本实现每5分钟，获取ip并写入 `.text` 文件由nginx服务映射远程地址出去，添加到IP订阅组，实现防护配置
> 局限：由于默认IP组规则更新为1天，所以脚本更新再及时，依旧存在时间差。

**Comment by QYG2297248353** [comment]
> 其实核心就是缩短IP组自动更新时间，但感觉可能性不大。如果每5-10分钟更新一次，服务器负荷或许会太大。 可能你可以通过家庭宽带访问带上特定的cookie，再把cookie加白来处理。

解决办法很多，但是如果主程序解决能一步达成，中间就能省下很多步骤，能采纳当然好。

**Comment by Lvshujun0918** [comment]
可是主程序达成需要耗费太多流量和资源，得不偿失，毕竟IP组10分钟更新一次可能性是很小的

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
