### ISSUE TITLE
拦截页面返回攻击类型 / 日志支持检索 eventid / 拦截页面和检测日志关联上

### ISSUE THREAD

**Issue by pusidun** [chaitin/safeline#74]
1. 拦截页面上有返回eventId，但是雷池页面又没有提供eventId检索，想要检索还得去pg数据库查询一下。
不如拦截时候多点信息，直接写上攻击类型
2. 另外发现有的时候只拦截了，返回的response body为空

**Comment by Lorna0** [comment]
功能建议单独提，方便收集大家意见。

不过 2 具体是什么情况呢，日志里的 response body 为空倒是正常的，因为被拦截了确实没有服务器响应

**Comment by pusidun** [comment]
> 功能建议单独提，方便收集大家意见。
> 
> 不过 2 具体是什么情况呢，日志里的 response body 为空倒是正常的，因为被拦截了确实没有服务器响应

嗯，1是体验问题，和2有些关联，填在一起了

2是这样的，假如我有个请求被雷池拦截了，雷池会有个拦截的页面
![image](https://github.com/chaitin/safeline/assets/6716275/9373d9c5-289f-4dc8-9e3c-a9d9ae494996)
这个拦截页面会给下这次的eventId，这个eventId呢，雷池页面不能直接检索，就是1的问题。
但是实际上呢，我发现有的时候**拦截了，但是没有返回这个页面**。

我为什么提这个问题，主要是我有这个需求，我想知道哪些请求被雷池拦截了，拦截原因是什么？
目前我是记录了这个页面上的eventId，然后到pg数据库里面一条条查。
所有我想，有没有什么方式
1. 能在拦截的时候就告诉我为什么被拦截了（注入？扫描？）
2. 我该用什么方式去雷池界面查询这次拦截详情？

**Comment by Lorna0** [comment]
1 的问题大致理解了，我们尽量处理下。

拦截后 response body 为空的问题，这个是不期望的，但是我们也没遇到过。师傅遇到的频率高么，有没有复现的方法呢。
方便的话可以单独提个 bug issue，或者在交流群里加我们排查。

**Comment by zclaiqcc** [comment]
> 我发现有的时候**拦截了，但是没有返回这个页面**。

诶那咋判断是被拦截了呢，响应码是 403？

**Comment by pusidun** [comment]
@Lorna0 这个我暂时没找到规律和复现方法，找到了我单独提个issue吧
@zclaiqcc 是的，检查返回码403，然后看看返回的body是不是雷池的

**Comment by zclaiqcc** [comment]
event_id 的筛选已经加了，页面上筛选直接叫 ID
