### ISSUE TITLE
[Bug] 填写黑名单正则匹配时提示编译出错

### ISSUE THREAD

**Issue by ZionLoh90** [chaitin/SafeLine#740]
### 问题描述

黑名单，添加body中含有out.println的匹配条件提交时提示编译错误

### 版本号

4.4.1

### 复现方法

黑名单，添加body中含有out.println的匹配条件：
![image](https://github.com/chaitin/SafeLine/assets/63135200/7418b6f2-4888-41a7-97f0-518d328caa98)

另：以前匹配条件正则支持特殊符号，现在无法支持，是否是转义问题？
例如：out.println(*

### 期望的结果

修复该问题

**Comment by yrluke** [comment]
怀疑是服务挂了，docker ps看看是不是fvm 容器不正常了

**Comment by xbingW** [comment]
请升级到最新版再试一下

**Comment by ZionLoh90** [comment]
docker ps 看了，服务没挂，可能是上一个版本的问题，目前升级到最新版本暂无发现
