### ISSUE TITLE
[建议] 在添加站点处 ， 能否增加一个日志开关按钮  ，用于统计按钮  利于业务上线测试

### ISSUE THREAD

**Issue by ywd1988** [chaitin/SafeLine#741]
### 背景与遇到的问题

![image](https://github.com/chaitin/SafeLine/assets/92080991/a7f39bc7-0c7f-4742-85eb-56853c6f71e2)
页面所示的4xx错误，无法判断是哪个站点的问题，增加一个日志开关按钮  ，用于统计按钮，这样判断哪个站点的问题。

### 建议的解决方案

 在添加站点处 ， 能否增加一个日志开关按钮  ，用于统计按钮  利于业务上线测试

**Comment by wjs-529** [comment]
支持

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
