### ISSUE TITLE
[建议] 雷池站点配置和全局配置可配置性增强

### ISSUE THREAD

**Issue by lei-mu** [chaitin/SafeLine#742]
### 背景与遇到的问题

本人想在自己的nas 上使用 雷池，来替换[npm](https://nginxproxymanager.com/screenshots/) 使用在线demo 后有如下感觉。

站点配置和全局配置 自定义项感觉和bt 的 nginx免费防火墙 软件比差点意思。（知道这2个东西不是一个量级，只说使用体验）

比如想禁止指定站点 禁止国外访问、网站局部规则配置、自定义响应内容、响应状态码

站点的nginx 自定义配置？

ssl 证书自动续费，基于秘钥的dns 验证或者http 验证。

希望能融合一下[npm](https://nginxproxymanager.com/screenshots/) 和 bt “nginx 免费防火墙” 软件的功能。

### 建议的解决方案

![PixPin_2024-03-12_14-56-59](https://github.com/chaitin/SafeLine/assets/29419129/3e67ae1d-4d25-40cc-87d6-09057f0a288d)
![PixPin_2024-03-12_14-57-43](https://github.com/chaitin/SafeLine/assets/29419129/48cfdeb5-05d7-450a-9f6f-fcaec45052fd)
![PixPin_2024-03-12_14-58-42](https://github.com/chaitin/SafeLine/assets/29419129/35ca2ce7-9d12-473d-a5ef-a30c465934cc)
![PixPin_2024-03-12_14-59-55](https://github.com/chaitin/SafeLine/assets/29419129/58eb09aa-0a9f-41d0-9af5-c1551d46a969)
![PixPin_2024-03-12_15-27-09](https://github.com/chaitin/SafeLine/assets/29419129/a23e57c5-8f19-4810-928f-2980f9548537)

**Comment by lei-mu** [comment]
![PixPin_2024-03-12_15-45-03](https://github.com/chaitin/SafeLine/assets/29419129/d6098949-5cd1-4cc8-a994-7db063b93d78)
![PixPin_2024-03-12_15-45-40](https://github.com/chaitin/SafeLine/assets/29419129/865f2e38-0429-489c-ba3f-8df54ed56f79)
![PixPin_2024-03-12_15-45-48](https://github.com/chaitin/SafeLine/assets/29419129/71c67f52-ed44-46f7-82cd-05860a695a9b)
![PixPin_2024-03-12_15-45-56](https://github.com/chaitin/SafeLine/assets/29419129/b1fd51f4-8428-4bc8-a19f-23baaca73788)

**Comment by ZionLoh90** [comment]
哈哈，直接说参考宝塔WAF就行了

**Comment by lei-mu** [comment]
> 哈哈，直接说参考宝塔WAF就行了

用户：我想要个tab 栏，一点 然后就下拉，然后一个方形渐变，向下移动......
程序员：你直接让我看抄哪个？
用户：好的

**Comment by Lorna0** [comment]
感谢反馈，不过一个 issue 范围太大并不利于后续的意见收集和进度跟进，原文中提及的不少内容已经有 issue 反馈了，可以到点赞对应的 issue 加快进度，其余的交互我们也会参考，这个 issue 难以跟进，就先关闭了。
