### ISSUE TITLE
[Suggestion] Supports HTTP/3 / 支持 HTTP3

### ISSUE THREAD

**Issue by Anyexyz** [chaitin/SafeLine#743]
### 背景与遇到的问题

> HTTP/3 的基础即谷歌多年探索的基于 UDP 的 QUIC 协议。与 TCP 相比，使用 UDP 可以提供更大的灵活性，并且可以使 QUIC 完全于用户空间中实现——对协议实现的更新不像 TCP 那样需要绑定到操作系统更新。使用 QUIC，可以简单地将 HTTP 级别的流映射到 QUIC 流的顶部，从而继承 HTTP/2 的所有优点，而不会产生队头阻塞。

### 优势

* HTTP/3 利用 QUIC 加速 HTTP 请求，QUIC 提供比 TCP 和 TLS 更高的加密和性能。
* QUIC 是一种默认加密的新传输协议，旨在加快 HTTP 传输速度以及使其更加安全。
* HTTP/3 基于 UDP，如果数据包丢失，只会中断一个流，而不会中断所有流，提高了同时获取多个对象的性能。
* 支持 0-RTT，消除服务器的 TLS 确认，使后续连接的启动速度更快。

**墙裂建议增加 HTTP/3 支持，上游 nginx 在1.25 版本中已新增此特性**

**Comment by tokpig** [comment]
我也想要http3，，，但是不会整哎

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
