### ISSUE TITLE
[建议] 增加一个模块和配置功能，配置外置数据库，攻击日志写入数据库

### ISSUE THREAD

**Issue by ZionLoh90** [chaitin/SafeLine#745]
### 背景与遇到的问题

参考：微步蜜罐HFISH
对企业私有化安全数据分析很有帮助，同时，攻击日志信息可以和其他系统联动，做到全面封禁，提高安全

### 建议的解决方案

增加一个模块和配置功能，配置外置数据库，攻击日志写入数据库
如果考虑IO和性能问题，可以增加redis/memory cache等缓存中间件方案解决

**Comment by xbingW** [comment]
后续版本会支持 syslog 方式同步到外部服务器

**Comment by Lorna0** [comment]
已支持 syslog。

配置外置数据库会影响统计分析等其他操作，开发工作量太大，不会考虑。

**Comment by Lvshujun0918** [comment]
其实只要业务系统接入雷池的数据库，读取信息即可做到
