### ISSUE TITLE
[建议] 5.0.0 强制用户使用账号密码登录，能否改为可选项功能，由使用者自己选择是否开启？

### ISSUE THREAD

**Issue by sifanx** [chaitin/SafeLine#749]
### 背景与遇到的问题

我已经习惯了以往的OTP登录方式，很实用，不用去记账号密码，密码太多了，容易忘记，现在变成强制要使用账号密码+OTP 登录，很麻烦。

### 建议的解决方案

登录方式改为可选项功能，由使用者自己选择是否开启。

**Comment by peng2289** [comment]
支持，我也是，本身是社区版，又不支持多用户，习惯了totp登录，不需要去记住密码，特别是好几个服务器，整的我都暂时不想升级到5.0了

**Comment by ashuai** [comment]
支持此建议。

如果难实现。可以做成站点模式切换，切换模式后需要重建站点

**Comment by medasz** [comment]
+1

**Comment by hekang26** [comment]
我也在issue上提了一个，看看开发组是否能接受建议吧
https://github.com/chaitin/SafeLine/issues/771

**Comment by zhuanmentiwen** [comment]
建议：登录方式默认是totp，使用者如果需要可以在后台设置开启账号密码。

**Comment by PoisonGZ** [comment]
就是现在这个真的很恶心，原本的就非常好

**Comment by luweijun1992** [comment]
+1

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
