### ISSUE TITLE
[Bug] 频率限制日志不显示物理位置的问题

### ISSUE THREAD

**Issue by TScci** [chaitin/SafeLine#750]
### 问题描述

升级最新版本（5.0.0）后发现有若干条频率限制日志记录的IP地址不再显示物理位置信息，手动验证可以复现此问题，最早出现问题的记录时间（2024-03-11）是这台机器升级4.4.2的时间点。
![WX20240314-165927@2x](https://github.com/chaitin/SafeLine/assets/47475807/4dcb4695-02d5-477c-8318-ed74b9f2d821)

### 版本号

5.0.0

### 复现方法

1. 更新waf版本至4.4.2及以上
2. 启用“高频访问限制”、“高频攻击限制”
3. http请求模拟高频访问或者高频攻击
4. 查看频率限制日志

### 期望的结果

频率限制日志正确显示IP对应物理地址

**Comment by Lvshujun0918** [comment]
同样的问题

**Comment by TScci** [comment]
#### 使用另一台机器安装雷池验证
* 5.0.0、4.4.1版本存在以上问题

![屏幕截图 2024-03-14 181220](https://github.com/chaitin/SafeLine/assets/47475807/7c9c8812-7cb3-4a4b-8a90-c85295e05a05)

* 降到4.3.3后可以正常显示

![屏幕截图 2024-03-14 182943](https://github.com/chaitin/SafeLine/assets/47475807/66512a31-2037-4f90-bcbb-02866eb9f740)

**Comment by yrluke** [comment]
v5.1.0已修复
