### ISSUE TITLE
[建议] 【防护站点→站点详情】页面的最近访问时间能否放出时分秒

### ISSUE THREAD

**Issue by 18338057952** [chaitin/SafeLine#751]
### 背景与遇到的问题

最近访问的记录基本都是当天的数据，只显示年月日的话，感觉失去了一些意义
![image](https://github.com/chaitin/SafeLine/assets/57310425/8dfe6f7f-895e-48f0-abc2-93fe1d283436)

### 建议的解决方案

建议将最近访问时间格式调整为年月日时分秒，浏览器调试得到的该列表数据，时间是有时分秒的

**Comment by Lorna0** [comment]
显示最近访问时间的目的是，提示用户这个资源是否还有效。如果最近访问时间已经在很多天之前，那么这个资源多半已经不可用了，可以被删除。

显示时分秒好像对资源管理没啥特别大意义。

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
