### ISSUE TITLE
[Bug] 软件升级或者对防护站点进行编辑后，nginx相关配置文件恢复默认，造成网站不能正常访问的问题。

### ISSUE THREAD

**Issue by zdfkk** [chaitin/SafeLine#752]
### 问题描述

Bug1.系统升级到5.0.0，发现对nginx.conf配置文件的更改恢复到了默认，造成有些配置失效。
Bug2.默认情况下，include /etc/nginx/custom_params/backend_XX;  是在  location ^~ / {   内，但是有些网站需要把include /etc/nginx/custom_params/backend_XX; 放到location ^~ / {  的上面。手动放到上面后，如果从界面上对该防护的站点进行编辑，配置文件会恢复默认，造成网站访问错误。

默认配置如图：
![Screenshot 2024-03-14 at 21-48-38 Nginx反向代理](https://github.com/chaitin/SafeLine/assets/163424966/075f54ff-3fa7-4bfe-b011-144b8e4c7fe7)
根据网站需要改为的：
![Screenshot 2024-03-14 at 21-50-08 Nginx反向代理](https://github.com/chaitin/SafeLine/assets/163424966/420a7f94-b899-4ad7-bef7-8d930e765b39)

### 版本号

5.0.0

### 复现方法

按问题描述即可复现

### 期望的结果

1.希望升级先不要恢复nginx.conf默认文件，如果校验有问题再恢复。

2.希望在 location ^~ / { 的上面再默认增加另外一个配置文件。 用户根据自己的需求，选择把自定义配置放在location ^~ / { 外面或者里面的相应配置文件内。

**Comment by yrluke** [comment]
是这样的，如果等到校验时出现问题可能已经导致整个容器挂掉了

**Comment by zdfkk** [comment]
> 是这样的，如果等到校验时出现问题可能已经导致整个容器挂掉了
有没有其他的校验方式，不用nginx本身的，或者容器不挂掉得前提下校验。

还有第二个问题，非常重要：
2.希望在 location ^~ / { 的上面再默认增加另外一个配置文件。 用户根据自己的需求，选择把自定义配置放在location ^~ / { 外面或者里面的相应配置文件内。

这个问题好麻烦，每次升级，或者编辑站点后，就得第一时间手动调整配置文件，否则网站就不能正常访问。

**Comment by zdfkk** [comment]
> 是这样的，如果等到校验时出现问题可能已经导致整个容器挂掉了
有没有其他的校验方式，不用nginx本身的，或者容器不挂掉得前提下校验。

还有第二个问题，非常重要：
2.希望在 location ^~ / { 的上面再默认增加另外一个配置文件。 用户根据自己的需求，选择把自定义配置放在location ^~ / { 外面或者里面的相应配置文件内。

这个问题好麻烦，每次升级，或者编辑站点后，就得第一时间手动调整配置文件，否则网站就不能正常访问。

**Comment by Lorna0** [comment]
> Bug1.系统升级到5.0.0，发现对nginx.conf配置文件的更改恢复到了默认，造成有些配置失效。

nginx.conf 肯定是优先保证控制台界面的操作正常，否则可能造成不可预料的故障。有自定义需求需要在我们特地留出的位置修改，初次之外的部分每次重置是符合预期的。

> Bug2.默认情况下，include /etc/nginx/custom_params/backend_XX; 是在 location ^~ / { 内，但是有些网站需要把include /etc/nginx/custom_params/backend_XX; 放到location ^~ / { 的上面。手动放到上面后，如果从界面上对该防护的站点进行编辑，配置文件会恢复默认，造成网站访问错误。

同上这个是预期的。可以提交一个建议。btw 为啥需要这样修改？有什么差异么

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
