### ISSUE TITLE
[建议] 防护站点拦截请求数量，支持查看具体日志内容

### ISSUE THREAD

**Issue by zdfkk** [chaitin/SafeLine#753]
### 背景与遇到的问题

![图片](https://github.com/chaitin/SafeLine/assets/163424966/4ced9b60-596d-4676-af52-f88390e17b6a)
如图，每个防护站点可以看到拦截的数量，但是如果想要看到指定站点具体拦截了那么请求，哪天拦截了哪些请求，无从下手。从攻击事件里查看，也不能够方便的查看具体站点的拦截情况。

### 建议的解决方案

建议 在图中的拦截数量 做成超链接，点击后就跳到该网站具体的拦截详情，在本页面也可以按照日期，或者攻击类型进行筛选。

**Comment by xbingW** [comment]
最新版可以查询各种规则的拦截日志了
