### ISSUE TITLE
[建议] 将源 IP 获取方式 中Header头部获取更灵活化

### ISSUE THREAD

**Issue by fobole-openthedoor** [chaitin/SafeLine#755]
### 背景与遇到的问题

目前只能指定一个头部，但是我业务系统不同导致有的使用X-Forwarded-For 而有的只能使用指定的头部取得客户IP。

结果就是我不得不部署多个雷池来分别取客户IP。

同时我注意到从X-Forwarded-For取客户IP时，如果X-Forwarded-For值不为单个IP的话只会取最右面的IP，按照惯例应该是取最左位的。

### 建议的解决方案

建议像邻居塔一样可以设置多个Header头部取客户IP并可以设置左取或者右取IP。

**Comment by Lorna0** [comment]
duplicate，可在之前issue中跟进：
* https://github.com/chaitin/SafeLine/issues/301

PS. XFF 取最左位是存在安全问题的，并不是惯例。
