### ISSUE TITLE
[Bug] 调整通用站点配置时 报错TCD Service is AbNormal 或timeout，导致配置修改失败

### ISSUE THREAD

**Issue by chenjunjie45** [chaitin/SafeLine#757]
### 问题描述

safeline-mgt模块报错
`2024/03/16 16:18:45 [warn] 9#9: *2316 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/6/00/0000000006 while reading upstream, client: 172.22.222.1, server: , request: "GET /api/open/publish/server?kind=task HTTP/1.1", upstream: "http://127.0.0.1:8000/api/open/publish/server?kind=task", host: "172.22.222.4:1443"
2024/03/16 16:18:48 [ERROR] tcd website/website_service.go:215 client timeout
2024/03/16 16:18:48 [ERROR] api api/global.go:119 client timeout
2024/03/16 16:33:23 [warn] 9#9: *2802 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/7/00/0000000007 while reading upstream, client: 172.22.222.1, server: , request: "GET /api/open/publish/server?kind=task HTTP/1.1", upstream: "http://127.0.0.1:8000/api/open/publish/server?kind=task", host: "172.22.222.4:1443"
2024/03/16 16:33:28 [ERROR] tcd website/website_service.go:215 client timeout
2024/03/16 16:33:28 [ERROR] api api/global.go:119 client timeout
2024/03/16 16:33:35 [ERROR] tcd website/website_service.go:334 client timeout
2024/03/16 16:33:35 [ERROR] api gin@v1.9.1/context.go:174 client timeout
2024/03/16 16:33:44 [ERROR] tcd website/website_service.go:334 client timeout
2024/03/16 16:33:44 [ERROR] api gin@v1.9.1/context.go:174 client timeout
2024/03/16 16:33:49 [ERROR] tcd website/website_service.go:334 client timeout
2024/03/16 16:33:49 [ERROR] api gin@v1.9.1/context.go:174 client timeout
2024/03/16 16:35:28 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:35:28 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:35:31 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:35:31 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:37:30 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:37:30 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:37:32 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:37:32 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:37:45 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:37:45 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:37:46 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:37:46 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:38:18 [ERROR] service.website api/global.go:217 TCD Service is AbNormal
2024/03/16 16:38:18 [ERROR] api gin@v1.9.1/context.go:174 TCD Service is AbNormal
2024/03/16 16:38:20 [ERROR] service.website api/global.go:217 TCD Service is AbNormal`

### 版本号

5.0.0

### 复现方法

通用配置-其他-站点通用配置，取消或勾选任意一项。还有就是我的站点数量过百了

### 期望的结果

修复

**Comment by yrluke** [comment]
docker ps看看是不是safeline-tengine已经进入重启状态了，如果是，麻烦docker logs -tf safeline-tengine看看报错，有可能
是因为站点数量过多，之后导致的上游服务器域名失效

**Comment by zhimibuwudn** [comment]
同样的问题

**Comment by yrluke** [comment]
> 同样的问题

删掉/etc/resolv.conf里的ipv6地址就好了

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/discussions/689

**Comment by guodong52cc** [comment]
同样的问题，/etc/resolv.conf没有ipv6，docker logs -tf safeline-tengine中错误是这样的：

<img width="952" alt="image" src="https://github.com/chaitin/SafeLine/assets/94731664/8fd7ebe0-3f4f-48fd-b7fa-98c3b2361da9">
