### ISSUE TITLE
[Bug] 反向代理discourse论坛时，论坛无法登录。

### ISSUE THREAD

**Issue by fslongjin** [chaitin/SafeLine#758]
### 问题描述

论坛是discourse的，并且在论坛后台开启了“强制https”选项。反向代理discourse论坛时，论坛无法登录，csrf报错，提示如下：
![image](https://github.com/chaitin/SafeLine/assets/63215266/ef0d78ac-3d2b-4bf4-9033-199fa86feb5a)

discourse要求开启该选项后，nginx反向代理应当传入`X-forwarded-proto https;`

当使用雷池（部署了lets encrypt证书）直接反代到discourse的docker之后，无法登录。

### 版本号

5.0.0

### 复现方法

1. 部署discourse论坛，并且在论坛后台开启了“强制https”选项。
2. 使用雷池反代到论坛的docker容器的http端口
3. 雷池绑定的域名开启https
4. 直接账号密码登录论坛的话，点登录之后，页面刷新，账号没登上。
5. 使用论坛的github登录的话，就会报错![image](https://github.com/chaitin/SafeLine/assets/63215266/ef0d78ac-3d2b-4bf4-9033-199fa86feb5a)

如果在雷池和discourse之间再加一层nginx反代，配置如下，就不会报错。

```

#PROXY-START/

location ^~ /
{
    proxy_pass http://192.168.198.100:10080/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header HTTP_X_FORWARDED_FOR $remote_addr;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;
    #Set Nginx Cache

    set $static_fileaDG9taVa 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
        set $static_fileaDG9taVa 1;
        expires 1m;
    }
    if ( $static_fileaDG9taVa = 0 )
    {
        add_header Cache-Control no-cache;
    }
}
#PROXY-END/
```

### 期望的结果

直接使用雷池反代到目标服务器，论坛能够正常登录。

**Comment by fslongjin** [comment]
也许雷池反代的时候需要加一个header：
```
proxy_set_header X-Forwarded-Proto $scheme;
```
就能解决问题？

**Comment by Lvshujun0918** [comment]
那开启这个选项是否会有帮助？
![image](https://github.com/chaitin/SafeLine/assets/41245552/ef27595c-fa8c-4483-9e12-ecc22e4f8449)

**Comment by fslongjin** [comment]
谢谢！解决了！

> 那开启这个选项是否会有帮助？ ![image](https://private-user-images.githubusercontent.com/41245552/313548854-ef27595c-fa8c-4483-9e12-ecc22e4f8449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzYzNjksIm5iZiI6MTcxMDczNjA2OSwicGF0aCI6Ii80MTI0NTU1Mi8zMTM1NDg4NTQtZWYyNzU5NWMtZmE4Yy00NDgzLTllMTItZWNjMjJlNGY4NDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA0Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZjVjYzdkNWM0ZWU0ODdjZDg3YTZkOGJiMzcxYWMyMGE5NmY4NDNmZDMyNTRjOGE0NzEyYmQxOTcyODk4NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L2WeHB0M5TF8jWBHy9qE1dO-aRCkJfEW2FroBy4XVO0)
