### ISSUE TITLE
[Bug] Let's encrypt每次申请新证书都会创建新的let's encrypt账号？

### ISSUE THREAD

**Issue by fslongjin** [chaitin/SafeLine#759]
### 问题描述

今天一次性添加了10个网站，申请了ssl证书。然后第11个网站的ssl证书申请就报错了：
![image](https://github.com/chaitin/SafeLine/assets/63215266/d626647c-c0dd-40d3-ab63-983192ae13f9)

查看lets encrypt的文档，发现如果只是申请证书的话，完全到不了限制：

https://letsencrypt.org/docs/rate-limits/

但是lets encrypt提示了，如果程序没有正确存储凭证信息，而是多次创建账户，就会触发这个3小时新建10个账户的速率限制。结合报错信息，看样子雷池可能是触发了这个问题：

https://letsencrypt.org/docs/too-many-registrations-for-this-ip/

### 版本号

5.0.0

### 复现方法

一次性添加了10个网站，申请ssl证书。然后第11个网站的ssl证书申请就报错

### 期望的结果

只会创建1个lets encrypt账户，不触发这个速率限制

**Comment by fslongjin** [comment]
使用lets encrypt的certbot来申请（文件验证方式），也不会出现这个问题。


我在想雷池能否直接把这个功能交由certbot来执行？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月21日(周四) 下午3:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chaitin/SafeLine] [Bug] Let's encrypt每次申请新证书都会创建新的let's encrypt账号？ (Issue #759)




 
除非使用dns模式申请，但是雷池不支持

**Comment by xbingW** [comment]
最新版 6.6.0 已修复
