### ISSUE TITLE
[Bug] 连续操作3~5次将攻击IP加入IP组就出现报错

### ISSUE THREAD

**Issue by xautlmx** [chaitin/SafeLine#760]
### 问题描述

# 问题描述
连续操作3~5次将攻击IP加入IP组就出现报错，报错信息如下：
```bash
SyntaxError: Unexpected token '<',"<head><met"... is not valid JSON
```
重新登录WAF后就恢复正常，再操作几次又可以复现。该问题在最新的好几个版本都会出现
![报错截图](https://github.com/chaitin/SafeLine/assets/5676173/084a69e4-d56a-41ba-ac0f-d014e8f8eea8)

### 版本号

5.0.0/4.4.2/4.4.1

### 复现方法

连续操作3~5次将攻击IP加入IP组就出现报错

### 期望的结果

修复此问题

**Comment by xautlmx** [comment]
这问题没人关注吗，都提了2周了。清理过浏览器缓存也是一样

**Comment by yrluke** [comment]
这边并没有复现

**Comment by yrluke** [comment]
能提供一下具体的复现步骤吗，并且是否为轻量服务器

**Comment by xautlmx** [comment]
不是轻量服务器，是正常的公有云云服务器。复现步骤就是在攻击事件页面连续操作3~5次将攻击IP加入IP组就会出现。这边昨天升级到5.2.0后好像暂时没出现了，我再观察使用几天。

**Comment by xautlmx** [comment]
@yrluke 不是轻量服务器，是正常的公有云云服务器。复现步骤就是在攻击事件页面连续操作3~5次将攻击IP加入IP组就会出现。这边昨天升级到5.2.0后好像暂时没出现了，我再观察使用几天。

**Comment by CDU-Ge** [comment]
这个错误是由于人机验证引发的，由于期望接口返回的是json格式数据，但人机验证会拦截请求导致前端解析错误

**Comment by binaryYuki** [comment]
@yrluke 
Hi,

我这边也遇到了相同的问题 并且这个问题最终会导致雷池waf 整个崩溃 回显Connection timed out Error code 522

据我所知 似乎是因为`反代雷池` + `设置了站点速率限制` 两个因素同时满足时会出现这个问题～

**Comment by Lorna0** [comment]
> @yrluke Hi,
> 
> 我这边也遇到了相同的问题 并且这个问题最终会导致雷池waf 整个崩溃 回显Connection timed out Error code 522
> 
> 据我所知 似乎是因为`反代雷池` + `设置了站点速率限制` 两个因素同时满足时会出现这个问题～
> 
> 并且白名单被触发了但是还是被 ban 了
> 
> <img alt="截屏2024-05-23 12 45 11" width="1478" src="https://private-user-images.githubusercontent.com/60097976/333036064-3c29e82a-f454-4140-a73e-367f68187522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTk3MjAsIm5iZiI6MTcxNjQ1OTQyMCwicGF0aCI6Ii82MDA5Nzk3Ni8zMzMwMzYwNjQtM2MyOWU4MmEtZjQ1NC00MTQwLWE3M2UtMzY3ZjY4MTg3NTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEwMTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYjQ3MDZiNDcwNjBkMjUyOTdkMTBlYTMyN2Y3OTc5YTMxYWFiNzMzMDAxNGJiMTA3N2E5NmJjYjgyOGJhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9PGzwXtzY11HZrAkdZgoJlibr_XeX7vqX3AsbKbOzVE">

反代雷池控制台 + 设置速率限制 只会报错 “SyntaxError: Unexpecte”，而且刷新一下就正常了。你说的 “Connection timed out Error code 522” 这个问题没有复现出来

**Comment by Lorna0** [comment]
如果配置的是 `反代雷池控制台的站点` + `设置速率限制` ，触发 `SyntaxError: Unexpected token '<',"<head><met"... is not valid JSON`，这是完全正常的。

这只是因为快速多次的 `加入 IP 组` 操作触发了频率限制，所以接下来的接口被雷池限频，只能获取到人机验证要求，所以接口报错。遇到的话刷新一下页面，通过人机就行了。

另外，雷池控制台本身就带有身份认证，除了管理员之外无人能操作，所以这个页面加 web 防护的意义没有很大，可以不加的。

**Comment by binaryYuki** [comment]
Hi @Lorna0,

感谢回复

我目前是通过关闭频率限制解决了 想问下这个限制不受白名单影响吗 

实测加入白名单之后也会被限制 但是不会出现在 频率限制日志 里面

**Comment by Lorna0** [comment]
> Hi @Lorna0,
> 
> 感谢回复
> 
> 我目前是通过关闭频率限制解决了 想问下这个限制不受白名单影响吗
> 
> 实测加入白名单之后也会被限制 但是不会出现在 频率限制日志 里面

很抱歉这么晚才回复，限频是受到白名单影响的，加入之后就不会被限制。另外，此时仍然会有频率限制日志，只是不会实际生效。

如果你遇到问题，可能是因为：
1. 源 IP 获取方式有误，导致白名单不生效
2. 白名单配置错误，导致没有正确匹配请求
3. 雷池某版本存在故障

考虑到你是没有出现在 频率限制日志 里面，所以我猜测是 1，当然也不排除其他原因。欢迎再创建反馈 issue，这边这个问题就关闭了。

**Comment by binaryYuki** [comment]
> > Hi @Lorna0,
> > 感谢回复
> > 我目前是通过关闭频率限制解决了 想问下这个限制不受白名单影响吗
> > 实测加入白名单之后也会被限制 但是不会出现在 频率限制日志 里面
> 
> 很抱歉这么晚才回复，限频是受到白名单影响的，加入之后就不会被限制。另外，此时仍然会有频率限制日志，只是不会实际生效。
> 
> 如果你遇到问题，可能是因为：
> 
> 1. 源 IP 获取方式有误，导致白名单不生效
> 2. 白名单配置错误，导致没有正确匹配请求
> 3. 雷池某版本存在故障
> 
> 考虑到你是没有出现在 频率限制日志 里面，所以我猜测是 1，当然也不排除其他原因。欢迎再创建反馈 issue，这边这个问题就关闭了。

好的 感谢回复
