### ISSUE TITLE
[建议] 模态窗不应该点击空白处关闭

### ISSUE THREAD

**Issue by ZhiweiWu0425** [chaitin/SafeLine#761]
### 背景与遇到的问题

模态窗口不应该点击窗口外层区域自动关闭当前窗口，尤其是正在编辑规则中，点击外侧甚至不做任何未保存提示的前提下关闭。

### 建议的解决方案

![image](https://github.com/chaitin/SafeLine/assets/89636889/4f271e17-af5e-47cd-a3de-6ce07e076136)
模态窗口的关闭应该在模态窗内的动作按钮操作，例如“关闭”，“取消”，“确定/完成/好”等。点击空白区域可增加模态窗的border闪烁以提醒完成模态窗操作。当然如果更进一步，可以判定模态窗表单是否有编辑，在点击“取消”动作按钮可以提醒“有未保存的内容，是否关闭”

**Comment by jack-tsang** [comment]
模态框这个点击空白页自动关闭确实不太友好，经常编辑到一半，一不小心鼠标点了一下空白处，又得重头填写。

**Comment by xbingW** [comment]
最新版已经修复
