### ISSUE TITLE
[建议] 补充规则应该直接下放到社区版

### ISSUE THREAD

**Issue by freewebcode** [chaitin/SafeLine#763]
### 背景与遇到的问题

我觉得一个waf不应该在最基本的防御上区分免费和付费，这就类似于给杀毒软件病毒库做区分，这样的杀毒软件没人会用吧？

### 建议的解决方案

补充规则应该直接下放到社区版

**Comment by yrluke** [comment]
现在收费的主要是0Day规则的部分，这部分开发成本太高了，免费的话我们会被公司的销售打死。

**Comment by yrluke** [comment]
成本低的部分我们是很愿意免费给大家用的

**Comment by Wink541** [comment]
但是杀毒软件也分免费版和企业版不是嘛

**Comment by hale177** [comment]
兄弟  别想着完全白嫖啊，这玩意一般公司用，又不是toC 个人用 ，所有别想着给公司省钱，反正也不会加薪到你口袋里 ，有需求直接上付费企业版，雷池也可以持续良性发展回馈社区

**Comment by zhuanmentiwen** [comment]
完全开放补充规则不大现实，毕竟免费给大家使用已经不错了。

但个人建议开放给社区版的补充规则增加可以关闭某条规则的功能。。这个补充规则没有办法关闭确实影响网站业务功能。我们也碰到这样的问题了。

**Comment by devhaozi** [comment]
规则不下放可以理解，建议为社区版提供关闭某条规则的功能。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
