### ISSUE TITLE
[建议] 

### ISSUE THREAD

**Issue by ifwwww** [chaitin/SafeLine#764]
### 背景与遇到的问题

Let's encrypt体验上不如直接api获取省事

### 建议的解决方案

能否增加云服务商api获取证书呢?

**Comment by ifwwww** [comment]
最主要的我之前一直用腾讯的api是可以申请泛域名证书的，不必再一个一个申请

**Comment by Lorna0** [comment]
泛域名证书问题可以：
* https://github.com/chaitin/SafeLine/issues/563
