### ISSUE TITLE
[Bug] 自定义页面设计缺陷

### ISSUE THREAD

**Issue by Wink541** [chaitin/SafeLine#765]
### 问题描述

雷池社区版可以通过替换静态文件来实现自定义拦截页面

### 版本号

5.0.0

### 复现方法

1.生成一个自定义拦截的页面
2.在safeline的安装路径下，来到 resources/nginx 路径
3.找到 *_pages 文件夹
4.将生成的自定义页面文件名修改为 *_pages 文件夹内的文件名
5.将生成的文件替换至 *_pages 文件夹内的文件
6.尝试修改 offline_pages 的页面，随后将任意站点设置为维护状态，访问站点即可

### 期望的结果

修复此问题

**Comment by Wink541** [comment]
![1](https://github.com/chaitin/SafeLine/assets/89731663/0b294adb-b845-432c-b328-1501e070e9db)
![2](https://github.com/chaitin/SafeLine/assets/89731663/36a6f981-33ff-4836-bcc8-e080ac8887fc)
![Uploading 3.png…]()

**Comment by Lvshujun0918** [comment]
该方法并不能反应系统缺陷。而且若重新配置，修改的页面会还原
