### ISSUE TITLE
更新到5.0后, 使用域名及Nginx反向代理 ,出现invalid csrf token

### ISSUE THREAD

**Issue by zsinba** [chaitin/SafeLine#769]
### 反馈内容

5.0版本以前是正常的, 因为那之前是不需要用户和密码的.
升级到5.0版本以后, 需要用户名和密码, 使用docker exec safeline-mgt resetadmin生成了用户名和密码. 
使用https://xxxx:9443是好登陆的. 

使用Nginx转发的 https://www.abc.com就无法登陆了, 提示invalid csrf token

<img width="935" alt="image" src="https://github.com/chaitin/SafeLine/assets/890157/a531a7f5-4733-4267-bf75-a9ba34ccd172">

<img width="523" alt="image" src="https://github.com/chaitin/SafeLine/assets/890157/ba534231-fc20-404c-b18c-fa92a4af1870">

<img width="417" alt="image" src="https://github.com/chaitin/SafeLine/assets/890157/002a3ee3-12b4-46bf-b6ee-b145004b0c9c">

使用的是社区版本,非商业版本.
是不是社区版本还需要配置个什么域名信任之类的?

**Comment by zsinba** [comment]
登陆页面出现, 到口令页面,也再出
![Uploading image.png…]()

**Comment by yrluke** [comment]
清理一下浏览器缓存试一下呢

**Comment by zsinba** [comment]
应该是使用了腾讯的CDN的原因, 直接使用IP是可以,转发就不可以了.

未知原因,必现.

**Comment by awesomeYG** [comment]
> 登陆页面出现, 到口令页面,也再出 <img alt="image" width="471" src="https://private-user-images.githubusercontent.com/890157/315268345-faa764cf-a904-440f-a23d-90c72f67f129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjc1OTgsIm5iZiI6MTcxMjAyNzI5OCwicGF0aCI6Ii84OTAxNTcvMzE1MjY4MzQ1LWZhYTc2NGNmLWE5MDQtNDQwZi1hMjNkLTkwYzcyZjY3ZjEyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwMzA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWQxOWFhNGM3NjhiOTcxMWJmY2IwY2Y0MDMyYTNlODRiMjBiM2M4MzBmOWFkNzdmYzNjZGY2ZmY1NWEzNTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YH602q2obFsXTJtALsjn2u4KsECtA-KmaZmv3wzLBDA">

”登录页面出现后还是可以点击登录并且走到口令页面的，只是在口令页面里被这个报错卡住了是吗“

**Comment by zsinba** [comment]
我一直跟着版本更新的,中间没有中断过. 
在有登陆功能后出现的这个问题. 
无法进入口令页面,登陆页面一直会提示无效的csrf令牌; 
我猜不是缓存的问题,至少不是本地浏览器缓存的问题 . 
通过IP正常,通过CDN不正常; 尝试更新CDN,也没正常; 
我猜是登陆页面有什么限制 , 和腾讯CDN有冲突. 

暂没有再关注这个了. 我觉得登陆反而很麻烦.

**Comment by awesomeYG** [comment]
> 我一直跟着版本更新的,中间没有中断过. 在有登陆功能后出现的这个问题. 无法进入口令页面,登陆页面一直会提示无效的csrf令牌; 我猜不是缓存的问题,至少不是本地浏览器缓存的问题 . 通过IP正常,通过CDN不正常; 尝试更新CDN,也没正常; 我猜是登陆页面有什么限制 , 和腾讯CDN有冲突.
> 
> 暂没有再关注这个了. 我觉得登陆反而很麻烦.

![image](https://github.com/chaitin/SafeLine/assets/25377438/dada47da-c4d3-4714-b79c-2d2df64334a8)
兄弟加一下这个企业微信吧，我们开发和你一起看下
