### ISSUE TITLE
站点的 SSL 证书支持直接粘贴

### ISSUE THREAD

**Issue by ylwzbk** [chaitin/SafeLine#77]
防火墙仅有的ssl设置只能通过 上传密钥及证书才能配置
希望增添一个 直接 复制粘贴的  填写设置

场景  我通过面板申请了 域名的ssl证书但没有证书和密钥文件 没有直接填写的选项是极其不便的

**Comment by clqs803** [comment]
+1

**Comment by miaowmint** [comment]
+1 对我来说这个非常重要，不然每次都要上传到腾讯云再下载下来。。。

**Comment by Lorna0** [comment]
> +1 对我来说这个非常重要，不然每次都要上传到腾讯云再下载下来。。。

为啥，本地存个 txt 文件，然后改成证书格式不就行了。
或者随便网上搜一个SSL证书格式转换工具就行了呀。

**Comment by miaowmint** [comment]
> > +1 对我来说这个非常重要，不然每次都要上传到腾讯云再下载下来。。。
> 
> 为啥，本地存个 txt 文件，然后改成证书格式不就行了。 或者随便网上搜一个SSL证书格式转换工具就行了呀。

那不也还是很麻烦吗。。直接复制粘贴多方便。。。

**Comment by clqs803** [comment]
> > > +1 对我来说这个非常重要，不然每次都要上传到腾讯云再下载下来。。。
> > 
> > 
> > 为啥，本地存个 txt 文件，然后改成证书格式不就行了。 或者随便网上搜一个SSL证书格式转换工具就行了呀。
> 
> 那不也还是很麻烦吗。。直接复制粘贴多方便。。。

哈哈，我之前也想说了。。 但是不太好意思，毕竟是白嫖 2333

**Comment by zclaiqcc** [comment]
> > > > +1 对我来说这个非常重要，不然每次都要上传到腾讯云再下载下来。。。
> > > 
> > > 
> > > 为啥，本地存个 txt 文件，然后改成证书格式不就行了。 或者随便网上搜一个SSL证书格式转换工具就行了呀。
> > 
> > 
> > 那不也还是很麻烦吗。。直接复制粘贴多方便。。。
> 
> 哈哈，我之前也想说了。。 但是不太好意思，毕竟是白嫖 2333

没啥不好意思的，大胆说。需求合理、大家都需要就做。放肆点，都是来白嫖的 hhh

**Comment by Lorna0** [comment]
3.10 已支持：
![image](https://github.com/chaitin/SafeLine/assets/56920727/0e283b45-0ace-4367-af82-116e4aea220e)
