### ISSUE TITLE
[建议] 

### ISSUE THREAD

**Issue by yinqiang520** [chaitin/SafeLine#770]
### 背景与遇到的问题

创建站点时,包含过多域名,报错nginx conf reload error: nginx: [warn] could not build optimal server_names hash, you should increase either server_names_hash_max size:512 or server_names_hash_bucket size: 64; ignoring server names hash_bucket size nginx: [wam]couldnot build optimal server names hash,you should increase either server_names hash_max size:512 or server names hash_bucket size:64; ignoring server_names_hash_bucket_size

### 建议的解决方案

默认值server_names_hash_max size:512 or server_names_hash_bucket size: 64 不够用 ,手动修改resources/nginx/nginx.conf后重启容器nginx.conf修改内容被覆盖了,只能通过docker exec safeline-tengine nginx -s reload修改生效  建议解决一下这个问题

**Comment by yrluke** [comment]
社区群聊天记录搜了一下，看上去并不是大多数行为，并且从初衷上来讲，可能确实没有考虑多域名这种情况，很可能还有附带的其他问题，建议拆成两个实例部署吧
