### ISSUE TITLE
[建议]5.x版本的两步验证开关，若干问题合集

### ISSUE THREAD

**Issue by hekang26** [chaitin/SafeLine#771]
### 背景与遇到的问题

雷池waf部署在内网，在没有映射到公网的情况下，完全不需要密码验证

### 建议的解决方案

1.建议给TOTP、密码验证增加开关功能
   默认值开启TOTP即可

2.另外建议增加日志轮询功能，做成一个下拉菜单（只保留1个月、3个月、6个月、12个月）

3.建议增加数据导入导出功能，这样方便运维

**Comment by peng2289** [comment]
希望官方能吧，我现在还没更新到密码版本

**Comment by Lorna0** [comment]
5.0二步验证：
* https://github.com/chaitin/SafeLine/issues/749

日志轮询是指查看访问日志么？如果是的话：
* https://github.com/chaitin/SafeLine/issues/145

数据导入导出：
* https://github.com/chaitin/SafeLine/issues/90

**Comment by Lorna0** [comment]
虽然 github 的默认排序是从新到旧，不过提 issue 之前可以先搜一下是否已经存在，如果已存在，可以直接给 issue 点个👍，我们统计赞数会更容易了解 issue 是否受欢迎。

**Comment by zhuanmentiwen** [comment]
建议：登录方式默认是totp，使用者如果需要可以在后台设置开启账号密码。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
