### ISSUE TITLE
有没有docker compose yaml文件

### ISSUE THREAD

**Issue by AlanWang2333** [chaitin/SafeLine#774]
### 反馈内容

我直接复制一下 在portainer里面就安装了。
![image](https://github.com/chaitin/SafeLine/assets/58912611/c85c8b46-e5a3-4340-b332-75999cde89bf)

我用的脚本显示没有docker compose 组件，我用的软路由我不敢乱安装，我能用potainer是不就代表我有docker compose 
![image](https://github.com/chaitin/SafeLine/assets/58912611/84622acd-ba54-4b14-a777-d4574eff5a10)

**Comment by yrluke** [comment]
https://github.com/chaitin/SafeLine/blob/main/release/latest/compose.yaml

**Comment by AlanWang2333** [comment]
谢谢😊
