### ISSUE TITLE
[建议] 在高频访问处增加永久封禁选项或提供自动加入ip组功能。

### ISSUE THREAD

**Issue by Lie-Kong** [chaitin/SafeLine#775]
### 背景与遇到的问题

网站时常被间歇性目录遍历攻击，且常常来自同一地址，最长封禁仅1天，无法有效防护。

### 建议的解决方案

建议在高频访问处增加永久封禁选项或提供自动加入ip组功能。

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/428
