### ISSUE TITLE
[Bug] 多站防护 通配域名情况下 资源无法被发现的问题

### ISSUE THREAD

**Issue by nAnderYang** [chaitin/SafeLine#777]
### 问题描述

模式:
nignx->waf->backend service

添加站点
*.test1.com 80 10.100.10.200:8080
*.test2.com 80 10.100.10.201:8080

使用x-real-ip head头 穿透真实ip

结果
![image](https://github.com/chaitin/SafeLine/assets/28423384/9cec8939-d002-4f6a-96ca-c55b110b9690)

### 版本号

5.1.0

### 复现方法

docker 部署后仅做以上步骤 即可复现问题。

### 期望的结果

正确发现站点内资源数

**Comment by yrluke** [comment]
我怀疑是exclude掉了资源格式，我这边没有复现
