### ISSUE TITLE
[Bug] wordpress 登录后台地址 使用htpasswd方式弹窗登录会导致无限重定向

### ISSUE THREAD

**Issue by dengrongfei** [chaitin/SafeLine#778]
### 问题描述

如题，在雷池后台已经设置 xxx.com/wp-admin 人机验证按钮，之前在wp那里设置了htpasswd方式弹窗登录方式。发现只要设置了htpasswd就会导致页面白屏无限重定向，取消之后就能显示人机验证按钮。
希望能够修复bug，能让htpasswd方式和雷池人机验证方式共存

### 版本号

3.0

### 复现方法

如题

### 期望的结果

修复

**Comment by dengrongfei** [comment]
版本号升级到最新还是这样

**Comment by yrluke** [comment]
我记得这个地方是因为wp的base url没有配置对，师傅可以手动搜索一下在wp前配置nginx来反代，以完成配置
