### ISSUE TITLE
[建议] 证书增加使用路径导入方式

### ISSUE THREAD

**Issue by vu1nex** [chaitin/SafeLine#782]
### 背景与遇到的问题

证书三个月一次更新，现有方法需要手动进行导入，自带的免费证书功能有限制。

### 建议的解决方案

使用固定的系统目录，或挂载一个docker目录存放证书，检测到证书内容发生变化自动更新。

**Comment by Lvshujun0918** [comment]
赞同

**Comment by Equationzhao** [comment]
+1

**Comment by 1989car** [comment]
+1

**Comment by ws20940548** [comment]
+1

**Comment by Lorna0** [comment]
系统文件目录导入的形式，使用门槛有点高。三个月一次更新的话似乎也是免费证书居多，自带的免费证书功能有哪些限制，可以具体说说或者直接点赞一下之前的 issue 么。

PS. 由于 issue 列表无法判断评论内容，回复 “+1” 其实并不太能体现 issue 的受欢迎程度，反而容易把讨论内容刷下去。建议大家点击 issue 的 👍 来表示支持，感谢。

**Comment by Lvshujun0918** [comment]
比如通过acme.sh可以通过dns自动续签，这样配合系统文件目录导入的形式更加自动化，适配于证书不仅用于雷池，同时用于其他业务系统的情况

**Comment by ws20940548** [comment]
比如我主要是3个域名，我可以用certbot搞一个证书容纳3个域名的泛域名证书，所以我所有的站点仅仅是一个证书，我更新了证书之后，所有站点证书都更新了

**Comment by vu1nex** [comment]
赞同，而且使用“雷池”的个人用户也基本是有linux使用经验的程序员或个人站长，对于“系统文件目录导入的形式”感觉并无什么操作门槛，甚至很方便、简单。

**Comment by Lorna0** [comment]
看起来很大程度上都是泛域名证书的需求，那其实可以先跟进之前这个 issue：
* https://github.com/chaitin/SafeLine/issues/563

至于用户的技术基础，从交流群的提问看还是挺参差的 (´·_ゝ·`) 。确实有很多大佬，但是没基础的更多。

**Comment by Lorna0** [comment]
对这种做到界面上的功能，我们应该还是会优先保证易用易懂。

**Comment by AlliotTech** [comment]
同样有这个需求，写了个小脚本实现了从路径更新证书的需求， 有兴趣的同学可以试试： 
[从指定路径更新雷池WAF证书
](https://www.iots.vip/post/update-safeline-ssl-cert-from-file.html)

**Comment by SupGiant** [comment]
我真的很需要一个从文件导入证书的功能=.=

**Comment by Lvshujun0918** [comment]
> 我真的很需要一个从文件导入证书的功能=.=

可以看 @AlliotTech 的回复!

**Comment by SupGiant** [comment]
> > 我真的很需要一个从文件导入证书的功能=.=
> 
> 可以看 @AlliotTech 的回复!

他的情况不太符合我的需求。得我自己改才行。
并且我担心不是官方的支持，万一以后升级版本了脚本不适用了，就会比较麻烦

我希望官方能够提供支持，这是我目前最大的考虑。。

**Comment by AlliotTech** [comment]
> > > 我真的很需要一个从文件导入证书的功能=.=
> > 
> > 
> > 可以看 @AlliotTech 的回复!
> 
> 他的情况不太符合我的需求。得我自己改才行。 并且我担心不是官方的支持，万一以后升级版本了脚本不适用了，就会比较麻烦
> 
> 我希望官方能够提供支持，这是我目前最大的考虑。。

https://github.com/chaitin/SafeLine/issues/660  官方已经在这个issue回复过了，需要适配太多，因此暂时不会有。       
脚本方式，目前只要提供接口修改证书，都是兼容的。     
我也为此起封装一个python包： https://github.com/chaitin/SafeLine/issues/88#issuecomment-2047766007   
接口有更新会更新到这个包。

**Comment by cmradix** [comment]
> 看起来很大程度上都是泛域名证书的需求，那其实可以先跟进之前这个 issue：
> 
> * [[建议] 支持申请泛域名免费证书 / 支持用 dns 验证方式申请免费证书 #563](https://github.com/chaitin/SafeLine/issues/563)
> 
> 至于用户的技术基础，从交流群的提问看还是挺参差的 (´·_ゝ·`) 。确实有很多大佬，但是没基础的更多。

谷歌正在推进证书的最长有效期从398天减少到90天，因此无论是付费证书还是免费证书，自动化签发已经是必要的了。

不说像其他自动脚本那样一整上百家DNS服务商，就至少把最常用的腾讯百度阿里cloudflare之类的做进去，支持个三五家的解析服务，再把Let's Encrypt、ZerosSL、Buypass、Google Cloud的证书签发做上，先四选一，剩下的日后慢慢排表都成，有总比没有强吧。

**Comment by AlliotTech** [comment]
> > > > 我真的很需要一个从文件导入证书的功能=.=
> > > 
> > > 
> > > 可以看 @AlliotTech 的回复!
> > 
> > 
> > 他的情况不太符合我的需求。得我自己改才行。 并且我担心不是官方的支持，万一以后升级版本了脚本不适用了，就会比较麻烦
> > 我希望官方能够提供支持，这是我目前最大的考虑。。
> 
> #660 官方已经在这个issue回复过了，需要适配太多，因此暂时不会有。 脚本方式，目前只要提供接口修改证书，都是兼容的。 我也为此起封装一个python包： [#88 (comment)](https://github.com/chaitin/SafeLine/issues/88#issuecomment-2047766007) 接口有更新会更新到这个包。

6.2.0的证书接口变了，  python-safeline这边已经对应更新。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion

**Comment by dong4j** [comment]
我使用 1Panel 申请证书, 因为自带证书申请成功后执行脚本, 所以就写了一个 shell 版本的.

```shell
#!/bin/bash

# === 配置信息 ===
BASE_URL="https://ip:port/api"
USERNAME="用户名"
PASSWORD="密码"
# 证书 id
CERT_ID=1
CERT_FILE_PATH="fullchain.pem"
CERT_KEY_PATH="privkey.pem"

# === 函数: 输出错误信息并退出 ===
function error_exit {
    echo "[ERROR] $1"
    exit 1
}

# === 1. 获取 CSRF Token ===
csrf_token=$(curl -k -s "${BASE_URL}/open/auth/csrf" | jq -r '.data.csrf_token') || error_exit "无法获取 CSRF Token"
[ -z "$csrf_token" ] && error_exit "CSRF Token 为空"
echo "[INFO] CSRF Token 获取成功"

# === 2. 获取 JWT Token ===
JWT=$(curl -k -s -X POST "${BASE_URL}/open/auth/login" \
     -H "Content-Type: application/json" \
     -d "{\"username\":\"${USERNAME}\",\"password\":\"${PASSWORD}\",\"csrf_token\":\"${csrf_token}\"}" | jq -r '.data.jwt') || error_exit "无法获取 JWT"
[ -z "$JWT" ] && error_exit "JWT Token 为空"
echo "[INFO] JWT Token 获取成功"

# === 3. 读取证书文件和密钥文件内容 ===
[ -f "$CERT_FILE_PATH" ] || error_exit "证书文件 ${CERT_FILE_PATH} 不存在"
[ -f "$CERT_KEY_PATH" ] || error_exit "密钥文件 ${CERT_KEY_PATH} 不存在"

CERT_CONTENT=$(jq -sRr '.' < "$CERT_FILE_PATH") || error_exit "读取证书文件失败"
KEY_CONTENT=$(jq -sRr '.' < "$CERT_KEY_PATH") || error_exit "读取密钥文件失败"

echo "[INFO] 证书和密钥文件已读取"

# === 4. 更新证书 ===
UPDATE_PAYLOAD=$(jq -n \
    --arg cert "$CERT_CONTENT" \
    --arg key "$KEY_CONTENT" \
    --argjson type 2 \
    --argjson id $CERT_ID \
    '{
      manual: {
        crt: $cert,
        key: $key
      },
      type: $type,
      id: $id
    }')

result=$(curl -k -s -X POST "${BASE_URL}/open/cert" \
     -H "Authorization: Bearer ${JWT}" \
     -H "Content-Type: application/json" \
     -d "$UPDATE_PAYLOAD") || error_exit "证书更新请求失败"

# 解析并判断结果
err=$(echo "$result" | jq -r '.err')
msg=$(echo "$result" | jq -r '.msg')

if [ "$err" == "null" ]; then
    echo "[INFO] 证书更新成功"
else
    echo "[ERROR] 证书更新失败: $msg"
fi
```

修改必要的参数并将此脚本保存到证书推送的本地目录, 命名为: `update_certs.sh`, 然后在 1Panel 中添加脚本内容:

```shell
./update_certs.sh
```

最后重新申请证书就应该能看到相关的日志.
