### ISSUE TITLE
[Bug] 站点防护 通过本地DNS解析至雷池入口 拦截局域网内IP，添加白名单后无效

### ISSUE THREAD

**Issue by q6363269** [chaitin/SafeLine#783]
### 问题描述

使用场景：
使用思源笔记部署，打开页面无异常，当触发思源的内嵌模块-kmind后，通过雷池防护端口的页面无响应，从局域网内访问可正常响应

模式:
docker->waf本机->waf代理作第二端口->局域网web访问

拦截条目
https://{test.com}/api/query/sql
请求数据包URL地址：https://{test.com}/api/system/setUILayout

尝试解决：
1）由于同时监听ipv4和ipv6，发现被拦截的地址是本地网络后，添加ip段为白名单；
2）切换运行模式为“观察模式”

实际测试结果：
通过雷池代理端口访问，响应仍旧异常——页面无内容

![屏幕截图 2024-03-31 184451](https://github.com/chaitin/SafeLine/assets/43720144/485e9f33-2965-4e85-acf3-ec6a55cf8210)

### 版本号

5.0.0

### 复现方法

1、在局域网内，使用docker部署siyuan笔记
2、使用雷池代理该端口，并有效访问后，内嵌组件无法正常加载

### 期望的结果

可通过白名单的方式进行控制，有效加载内嵌组件

**Comment by q6363269** [comment]
![image](https://github.com/chaitin/SafeLine/assets/43720144/233f0965-122f-45f4-b2e3-b3c73e990df4)
![image](https://github.com/chaitin/SafeLine/assets/43720144/18a19903-b5cc-48cb-8679-f52983bdc4e4)

**Comment by yrluke** [comment]
规则内关系是and，规则间是or，师傅这样配置要求同时满足源IP是一个ipv4地址又是一个ipv6地址，所以这个地方没有生效
