### ISSUE TITLE
[建议] 支持统计7天内网站访问情况

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#785]
### 背景与遇到的问题

为了更好的掌握网站访问情况和qps支撑情况，希望能够在统计网站访问情况时显示能够扩大到7日内的数据。感谢！

### 建议的解决方案

建议首页实时 QPS和网站访问情况后面增加一个更多，可以查看以下4个内容的7天内情况：
7日QPS
7日页面浏览(PV)
7日独立访客(UV)
7日独立 IP

**Comment by wjs-529** [comment]
支持

**Comment by xbingW** [comment]
专业版是支持的
