### ISSUE TITLE
[Bug] 筛选器 UI 有时候会错位

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#789]
### 背景与遇到的问题

1.这里的"更多"按钮是否应当和左侧两按钮统一，不被拉长？
![image](https://github.com/chaitin/SafeLine/assets/41245552/98ac6d8c-94a7-4cc1-87dc-e8dfd4b61882)
2.筛选攻击类型时是否可以排除某种攻击类型，即查看全部攻击，但不看比如“黑名单”攻击？
3.在点击更多按钮加入更多筛选选项后，导出按钮及其里面的“专业版”徽章被压缩，应该是**非预期**的，望修复
![image](https://github.com/chaitin/SafeLine/assets/41245552/6d9212ba-dfa0-41ad-8cf4-3dddfbd1b25c)

**Comment by Lorna0** [comment]
1、3 两个 UI 问题我们修复一下。

排除的需求因为需要调整一下交互方案，还没排上期。可以集中到之前这两个 issue 中点赞加速一下：
* https://github.com/chaitin/SafeLine/issues/269
* https://github.com/chaitin/SafeLine/issues/640

**Comment by Lvshujun0918** [comment]
明白，感谢

**Comment by Lvshujun0918** [comment]
这个哪里completed了？

**Comment by Lorna0** [comment]
搞错了，开发中版本修了，公开版本还没修。

**Comment by Lvshujun0918** [comment]
已经解决
