### ISSUE TITLE
[建议] 希望增加泛域名证书自动续签

### ISSUE THREAD

**Issue by xBoomMan** [chaitin/SafeLine#791]
### 背景与遇到的问题

目前我只有一个主域名，我是用acme来续签证书，证书有效期只有90天，雷池续证书签功能仅限于http认证的单域名证书续签。

### 建议的解决方案
期望能够集成acme基于dns验证的证书申请和续签。
_No response_

**Comment by Lorna0** [comment]
有个相同 issue，可以去点个赞：
* https://github.com/chaitin/SafeLine/issues/563
