### ISSUE TITLE
[建议] 默认的账号名可以修改

### ISSUE THREAD

**Issue by faritor** [chaitin/SafeLine#795]
### 背景与遇到的问题

建议将后台登录的账号密码和直接 totp 验证登录，做成二选一的方式，可以自由选择使用哪种，而不是现在强制开启账号密码登录

### 建议的解决方案

后台中可以配置，是否开启账号密码登录，开启后是否开启 totp 二步验证，**且账号可以修改**[是谁想出来的账号不允许修改的，出来挨打！！！]

关闭账号密码登录，totp 为强制开启，开启账号密码，totp 为可选开启

**Comment by Lorna0** [comment]
第一个 duplicate：
* https://github.com/chaitin/SafeLine/issues/749

**Comment by zhuanmentiwen** [comment]
建议：登录方式默认是totp，使用者如果需要可以在后台设置开启账号密码。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
