### ISSUE TITLE
最新的版本的chaitin-waf作为apisix的插件，黑白名单的路径匹配不生效

### ISSUE THREAD

**Issue by liu1004010308** [chaitin/SafeLine#797]
### 反馈内容

嗨，您好，最新的版本的chaitin-waf作为apisix的插件，黑白名单的路径匹配不生效。具体操作如下：
![image](https://github.com/chaitin/SafeLine/assets/45248805/e918693c-80d5-4222-aece-27552e8743b0)
还是能够访问，不生效，如下图：
![image](https://github.com/chaitin/SafeLine/assets/45248805/08be4c06-f744-4f1d-8e0e-1ac19546f3c7)

但是采用独立部署的waf，是可以防护的，为什么呢？

**Comment by liu1004010308** [comment]
除了这个，其他的sql注入等都是生效的

**Comment by liu1004010308** [comment]
![image](https://github.com/chaitin/SafeLine/assets/45248805/b786e070-bcfe-4f3e-a25a-6c472b81a85f)
高频访问也有问题，已经禁用了，但是apisix+chaitin-waf的也能访问，为什么呢？

**Comment by xbingW** [comment]
收到，我们近期排查一下这个问题

**Comment by xbingW** [comment]
新版本 >= 6.0.0 已解决
