### ISSUE TITLE
安装软件建议

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/safeline#8]
当前版本：v1.0.2
安装时候的管理页面端口以及安装目录建议增加下自定义方式。
比如我的9443端口刚好别的应用使用了，导致冲突。
建议在执行 ./safeline-ce.sh 后进行交互选择。

**Comment by luweijun1992** [comment]
且我看容器中内部默认是1443，咋对外换成9443。
刚好9443被我的另外一个容器Portainer给占用了。

**Comment by zclaiqcc** [comment]
其实改成什么都有被占用的可能，感觉还是可编辑会好一些

**Comment by luweijun1992** [comment]
> 其实改成什么都有被占用的可能，感觉还是可编辑会好一些

所以在运行安装脚本的时候进行交互选择，这样会好一点。
且默认也是有一个端口存在，只是在脚本运行的时候可以让用户选择是否修改默认端口。

**Comment by zclaiqcc** [comment]
增加了 [FAQ](https://github.com/chaitin/safeline/blob/main/FAQ.md#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-safeline-%E5%90%8E%E5%8F%B0%E7%AE%A1%E7%90%86%E7%9A%84%E9%BB%98%E8%AE%A4%E7%AB%AF%E5%8F%A3%E6%9C%AC%E6%9C%BA-9443-%E5%B7%B2%E7%BB%8F%E8%A2%AB%E5%88%AB%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8D%A0%E7%94%A8%E4%BA%86)，可以通过手动修改 .env 文件来灵活配置
