### ISSUE TITLE
[Bug] 添加部分域名出错

### ISSUE THREAD

**Issue by YunFenLei** [chaitin/SafeLine#800]
### 问题描述

环境：Ubuntu 22.04 LTS (GNU/Linux 5.15.0-25-generic x86_64)
硬件：24H 32G 256G
带宽：1G
问题描述：
添加域名会出现错误提示如下：
nginx conf reload error: nginx: warnl could not build optimal server names hash, you should increase eitherserver names hash max size: 512 or server names hash bucket size: 64, ignoring server names hash bucket size nginx. wcould not build optimal server names hash, you should increase either server names hash max size: 512 orserver names hash bucket size: 64; ignoring server names hash bucket size
在resources/nginx/nginx.conf添加了    server_names_hash_max size 512，重启镜像还是这样。
##
    # Basic Settings
    ##
    server_names_hash_max size 512;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_requests 1024;
    keepalive_timeout 60;
    types_hash_max_size 4096;
    server_tokens off;
    server_info off;
    server_tag off;
    
    ##
    # SSL Settings
    ##
### 版本号

Version 5.2.0

### 复现方法

出错的域名有：power123.com.cn 类似的。域名已经替换部分字符。
已经添加成功最长的域名有：
nuionpack.com.cn
bxdunservices.com
uiouchaobaotupianku.com
我感觉是域名添加到上限了？
现在新增一个端口都不行了！
![图片](https://github.com/chaitin/SafeLine/assets/16033846/1524fe0a-7ea7-465f-b7bb-a63cc3e9ff78)

### 期望的结果

请及时排查处理。

**Comment by Lvshujun0918** [comment]
试了一下，似乎并未出现问题
![image](https://github.com/chaitin/SafeLine/assets/41245552/eb2e26ce-9ddc-4363-8890-bc6ce7538275)
![image](https://github.com/chaitin/SafeLine/assets/41245552/ab26b9e5-664d-4297-a789-4892edd05bf4)
能否发一下你的域名?

**Comment by Lvshujun0918** [comment]
"重启镜像还是这样。"
你改完后使用'''docker exec safeline-tengine nginx -s reload'''试试看

**Comment by yrluke** [comment]
> ### 问题描述
> 环境：Ubuntu 22.04 LTS (GNU/Linux 5.15.0-25-generic x86_64) 硬件：24H 32G 256G 带宽：1G 问题描述： 添加域名会出现错误提示如下： nginx conf reload error: nginx: warnl could not build optimal server names hash, you should increase eitherserver names hash max size: 512 or server names hash bucket size: 64, ignoring server names hash bucket size nginx. wcould not build optimal server names hash, you should increase either server names hash max size: 512 orserver names hash bucket size: 64; ignoring server names hash bucket size 在resources/nginx/nginx.conf添加了 server_names_hash_max size 512，重启镜像还是这样。
> 
> ```
> # Basic Settings
> ##
> server_names_hash_max size 512;
> sendfile on;
> tcp_nopush on;
> tcp_nodelay on;
> keepalive_requests 1024;
> keepalive_timeout 60;
> types_hash_max_size 4096;
> server_tokens off;
> server_info off;
> server_tag off;
> 
> ##
> # SSL Settings
> ##
> ```
> 
> ### 版本号
> Version 5.2.0
> 
> ### 复现方法
> 出错的域名有：power123.com.cn 类似的。域名已经替换部分字符。 已经添加成功最长的域名有： nuionpack.com.cn bxdunservices.com uiouchaobaotupianku.com 我感觉是域名添加到上限了？ 现在新增一个端口都不行了！ ![图片](https://private-user-images.githubusercontent.com/16033846/319989017-1524fe0a-7ea7-465f-b7bb-a63cc3e9ff78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODAzMTYsIm5iZiI6MTcxMjQ4MDAxNiwicGF0aCI6Ii8xNjAzMzg0Ni8zMTk5ODkwMTctMTUyNGZlMGEtN2VhNy00NjVmLWI3YmItYTYzY2MzZTlmZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA4NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjBhODFlYzIwZDgxOTE2ZDA3MmMwYmIxMWRjODc1N2U5YjE3ZDhlNDA1YzYxNzM1ZDY1ZmNhMjA4MmY2YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MInERXCAmMWln4LZ_LmwVkh1E4bAK0-qOyXCG0Tbggk)
> 
> ### 期望的结果
> 请及时排查处理。

看了一下报错内容，这不已经告诉你为啥报错了，可以按照提示加一下两个配置项

**Comment by Lvshujun0918** [comment]
> > ### 问题描述
> > 环境：Ubuntu 22.04 LTS (GNU/Linux 5.15.0-25-generic x86_64) 硬件：24H 32G 256G 带宽：1G 问题描述： 添加域名会出现错误提示如下： nginx conf reload error: nginx: warnl could not build optimal server names hash, you should increase eitherserver names hash max size: 512 or server names hash bucket size: 64, ignoring server names hash bucket size nginx. wcould not build optimal server names hash, you should increase either server names hash max size: 512 orserver names hash bucket size: 64; ignoring server names hash bucket size 在resources/nginx/nginx.conf添加了 server_names_hash_max size 512，重启镜像还是这样。
> > ```
> > # Basic Settings
> > ##
> > server_names_hash_max size 512;
> > sendfile on;
> > tcp_nopush on;
> > tcp_nodelay on;
> > keepalive_requests 1024;
> > keepalive_timeout 60;
> > types_hash_max_size 4096;
> > server_tokens off;
> > server_info off;
> > server_tag off;
> > 
> > ##
> > # SSL Settings
> > ##
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 版本号
> > Version 5.2.0
> > ### 复现方法
> > 出错的域名有：power123.com.cn 类似的。域名已经替换部分字符。 已经添加成功最长的域名有： nuionpack.com.cn bxdunservices.com uiouchaobaotupianku.com 我感觉是域名添加到上限了？ 现在新增一个端口都不行了！ ![图片](https://private-user-images.githubusercontent.com/16033846/319989017-1524fe0a-7ea7-465f-b7bb-a63cc3e9ff78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODAzMTYsIm5iZiI6MTcxMjQ4MDAxNiwicGF0aCI6Ii8xNjAzMzg0Ni8zMTk5ODkwMTctMTUyNGZlMGEtN2VhNy00NjVmLWI3YmItYTYzY2MzZTlmZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA4NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjBhODFlYzIwZDgxOTE2ZDA3MmMwYmIxMWRjODc1N2U5YjE3ZDhlNDA1YzYxNzM1ZDY1ZmNhMjA4MmY2YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MInERXCAmMWln4LZ_LmwVkh1E4bAK0-qOyXCG0Tbggk)
> > ### 期望的结果
> > 请及时排查处理。
> 
> 看了一下报错内容，这不已经告诉你为啥报错了，可以按照提示加一下两个配置项

他是加了没效果

**Comment by GuaiMiu** [comment]
同样报错，能力有限，坐等解决方法

**Comment by Lvshujun0918** [comment]
> 同样报错，能力有限，坐等解决方法

能否发一下报错的域名?

**Comment by GuaiMiu** [comment]
http块添加：
```
proxy_headers_hash_max_size 51200;
proxy_headers_hash_bucket_size 6400;
```
就解决了

**Comment by GuaiMiu** [comment]
> > 相同报错，能力有限，坐等解决方法
> 
> 能否解决域名错误的问题？

刚解决，应该跟域名关系不大，我在http块添加了`proxy_headers_hash_max_size 51200;
proxy_headers_hash_bucket_size 6400;`就解决了，我添加得域名是git.xxxx.cn 端口88 开启ssl。
