### ISSUE TITLE
[Bug]  nginx无法修改文件上传大小限制

### ISSUE THREAD

**Issue by Jayzhang1995** [chaitin/SafeLine#801]
### 问题描述

在custom_params目录自定义配置，
     client_max_body_size 10G;
     client_body_buffer_size 512m;

重启容器后报错
nginx: [emerg] "client_max_body_size" directive is duplicate in /etc/nginx/custom_params/backend_1:3

### 版本号

Version 5.2.0

### 复现方法

在custom_params目录自定义配置， 
     client_max_body_size 10G;
     client_body_buffer_size 512m;

### 期望的结果

如何修改容器/etc/nginx/nginx.conf里的client_max_body_size 配置

**Comment by Lvshujun0918** [comment]
我测试了一下，并没有问题。你可以贴出你的/etc/nginx/custom_params/backend_1配置

**Comment by Jayzhang1995** [comment]
因为容器里的nginx.conf已经存在了这个配置，所以提示重复的配置，但是我进容器修改这个配置文件也不生效
有三个backend配置，测试都不行

![image](https://github.com/chaitin/SafeLine/assets/24266745/72fead6c-6612-4a32-8e44-c2e1aa422b5e)

**Comment by Lvshujun0918** [comment]
直接修改nginx.conf，在容器外修改，不要进容器

**Comment by Lvshujun0918** [comment]
我这里测试是没有问题的，你修改完以后有没有执行`docker exec safeline-tengine nginx -s reload`来reload？

**Comment by Jayzhang1995** [comment]
> 我这里测试是没有问题的，你修改完以后有没有执行`docker exec safeline-tengine nginx -s reload`来reload？

执行了，容器也重启过 ，上传文件还是报错。
我的访问路径是这样的：
终端：手机app foldersync
文件内容：相册里单个500M左右的视频
WAF代理---》本机cloudreve网盘程序

以前用单纯的nginx代理就是修改了这两个配置生效的，client_max_body_size 10G;
client_body_buffer_size 512m; 现在修改safeline的不行

**Comment by Lvshujun0918** [comment]
![image](https://github.com/chaitin/SafeLine/assets/41245552/063b893b-b102-4ca4-b137-3819fe7361c2)
我这里正好也部署了cloudreve，用网页端上传大文件没有什么问题

**Comment by Lvshujun0918** [comment]
![image](https://github.com/chaitin/SafeLine/assets/41245552/0e9fa49a-0bbb-445a-a500-db0d5c8204d5)
已传完，未发现问题

**Comment by Jayzhang1995** [comment]
> ![image](https://private-user-images.githubusercontent.com/41245552/320253137-0e9fa49a-0bbb-445a-a500-db0d5c8204d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjUyNTcsIm5iZiI6MTcxMjQ2NDk1NywicGF0aCI6Ii80MTI0NTU1Mi8zMjAyNTMxMzctMGU5ZmE0OWEtMGJiYi00NDVhLWE1MDAtZGIwZDVjODIwNGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA0NDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MmJmNWQ5NmRlNmZhZWE5OTRmOWNmYjkzNzNhMGZiNzI3ZmNjMWI4ZTNjMjhiMzA2YmJiYTE4MjA0NTA5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wcpL5cIL6VWlBwwM0eM7tWn1XzJfDAPleouXxKp97EU) 已传完，未发现问题

嗯  cloudreve支持分片功能，看截图里是分成了25M，可能是我手机app不能分片的问题？

**Comment by Lvshujun0918** [comment]
好像有道理，可能分片影响了测试，你试试看，不过照道理是能生效的

**Comment by xbingW** [comment]
还有问题反馈请移步 https://rivers.chaitin.cn/discussion
