### ISSUE TITLE
[建议] 建议在站点页面加一列ID

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#803]
### 背景与遇到的问题

如果我想自定义某个backend的参数，我需要去`/data/safeline/resources/nginx/sites-enabled`文件夹中对应出它的ID，希望能直接显示在界面上
![image](https://github.com/chaitin/SafeLine/assets/41245552/d25563f2-b114-4d17-97b2-69b60dfeb93e)
可以考虑添加在红框处

**Comment by Lorna0** [comment]
自定义 nginx 配置暂时还不是一个很标准的操作。不过短期内有需要的话，可以先通过这两个方式在控制台获取站点 ID：

1. 在站点详情的 URL 中找到站点 ID
![image](https://github.com/chaitin/SafeLine/assets/56920727/f182267a-818c-4fd7-882d-16b54d8c2b59)

2. 在站点列表的 /api/website 接口返回数据中，找到站点 ID：
![image](https://github.com/chaitin/SafeLine/assets/56920727/073630e4-2e9a-43ff-924d-cdd029058d9d)

relate to：
* https://github.com/chaitin/SafeLine/issues/345

**Comment by Lvshujun0918** [comment]
收到，但希望之后能进一步完善自定义参数这块内容！

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
