### ISSUE TITLE
[Bug] luigi 组件报错

### ISSUE THREAD

**Issue by zhxind** [chaitin/SafeLine#804]
### 问题描述

goroutine 1 [running]:
github.com/DeronW/ipcount.Decode({0xc001082000, 0x38645a})
    /go/pkg/mod/github.com/!deron!w/ipcount@v0.4.0/ipcount.go:257 +0x4cd
luigi/lib/db/model.LoadDaily()
    /work/lib/db/model/daily.go:62 +0x1d8
luigi/lib/processor/daily.New(...)
    /work/lib/processor/daily/daily.go:32
main.main()
    /work/cmd/main.go:54 +0x3b7
panic: runtime error: slice bounds out of range [:255] with capacity 16

goroutine 1 [running]:
github.com/DeronW/ipcount.Decode({0xc0010fa000, 0x38645a})
    /go/pkg/mod/github.com/!deron!w/ipcount@v0.4.0/ipcount.go:257 +0x4cd
luigi/lib/db/model.LoadDaily()
    /work/lib/db/model/daily.go:62 +0x1d8
luigi/lib/processor/daily.New(...)
    /work/lib/processor/daily/daily.go:32
main.main()
    /work/cmd/main.go:54 +0x3b7

### 版本号

5.0.0 ~ 5.2.0

### 复现方法

goroutine 1 [running]:
github.com/DeronW/ipcount.Decode({0xc001082000, 0x38645a})
    /go/pkg/mod/github.com/!deron!w/ipcount@v0.4.0/ipcount.go:257 +0x4cd
luigi/lib/db/model.LoadDaily()
    /work/lib/db/model/daily.go:62 +0x1d8
luigi/lib/processor/daily.New(...)
    /work/lib/processor/daily/daily.go:32
main.main()
    /work/cmd/main.go:54 +0x3b7
panic: runtime error: slice bounds out of range [:255] with capacity 16

goroutine 1 [running]:
github.com/DeronW/ipcount.Decode({0xc0010fa000, 0x38645a})
    /go/pkg/mod/github.com/!deron!w/ipcount@v0.4.0/ipcount.go:257 +0x4cd
luigi/lib/db/model.LoadDaily()
    /work/lib/db/model/daily.go:62 +0x1d8
luigi/lib/processor/daily.New(...)
    /work/lib/processor/daily/daily.go:32
main.main()
    /work/cmd/main.go:54 +0x3b7

### 期望的结果

修复错误

**Comment by Lvshujun0918** [comment]
能否描述一下是什么情况下发生的，看日志只能看出来是IP统计出现的问题

**Comment by zhxind** [comment]
看原始日志好像是同一个IP有几十万的攻击拦截记录，除此之外没发现其他的异常情况。报错是凌晨01左右出现，修复方法只能清空luigi的db文件，清理postgresql数据等其他方式都不能恢复正常

**Comment by xbingW** [comment]
新版本 重构了统计模块，已解决此问题
