### ISSUE TITLE
[建议] 异常页面(500)适配手机版

### ISSUE THREAD

**Issue by QYG2297248353** [chaitin/SafeLine#808]
### 背景与遇到的问题

手机版遇到服务器异常时出现500页面不能自适应，显示方式为横向滚动，无法更好的适配手机页面，给用户的感觉就很奇怪。希望适配一下手机版本的异常页面

### 建议的解决方案

给手机单独设计无法访问的页面

**Comment by Lorna0** [comment]
5.6 版本中已适配

**Comment by QYG2297248353** [comment]
试过了，
竖屏，缺失，PC的美感，咋说呢，感觉上很别扭，

**Comment by Lorna0** [comment]
> 试过了， 竖屏，缺失，PC的美感，咋说呢，感觉上很别扭，

可以截个图么，长相应该差不多呀，可能是具体手机型号适配有问题

**Comment by QYG2297248353** [comment]
![img_v3_02b2_5cf20cb4-ad80-4227-81a5-dc45fdf2f25g](https://github.com/chaitin/SafeLine/assets/56836951/4da1c7b4-9820-40cc-97b3-9d17549a29b7)

感官就很奇怪

**Comment by Lorna0** [comment]
是差不多这个样子，没 get 为啥奇怪诶，是行间距的问题么，行间距的话是可以调一调。

> 感官就很奇怪

**Comment by QYG2297248353** [comment]
感官上，因为竖着排下来，就很别扭，一般出现这个页面都是源服务器的问题，PC版屏宽，横着排列，当然没啥问题。这应该属于设计问题，不算程序问题，

我个人感觉，留一个源服务器异常的图标，雷池的图标放大做背景就可以了，源服务器图标下面搞一个网络连接正常

草图-概念图（莫要嘲笑🙈）
![雷池手机版](https://github.com/chaitin/SafeLine/assets/56836951/201626e3-249d-426d-8aa0-a7391cd7c7dd)

**Comment by QYG2297248353** [comment]
更多的还是希望有个设计师设计设计，毕竟雷池整体上的设计比较前卫，PC做的那么好看，手机端也不能落下呀
