### ISSUE TITLE
[Bug] 补充规则无法修改，且防护站点调成观察模式后，补充规则依旧防护。

### ISSUE THREAD

**Issue by xinuo** [chaitin/SafeLine#813]
### 问题描述

1、添加了防护站点之后，即使调成观察模式，但依然受补充规则防护。
然而补充规则又仅限专业版才能修改。
有点死循环。
2、该请求仅仅是传递jdbcurl，但会被 [规则 ID: 65791] jdbc协议调用 所拦截。

### 版本号

5.3.1

### 复现方法

1、添加了防护站点之后，切换模式至 观察
2、提交请求包括以下示例代码：
jdbc:mysql://<machine_name>:<port>/<dbname>; 

### 期望的结果

1、补充规则中的规则，默认开启的规则，能给予权限关闭/改成观察。或受站点管理中的 切换模式 控制。
2、普通的传递jdbcurl不受拦截。

**Comment by Lorna0** [comment]
在 5.6.2 中修复了已知的观察模式下补充规则依然防护的问题，可以验证一下。

**Comment by xinuo** [comment]
> 在 5.6.2 中修复了已知的观察模式下补充规则依然防护的问题，可以验证一下。

依然不行。
操作如下：
1、雷池升级了5.6.2。
2、站点设置成了观察模式。
3、防护配置-》语义分析，批量调整为观察模式。
但是提交请求时候仍然403。查看雷池后台，攻击类型：SSRF
是普通的flinksql、或者包含jdbc:mysql均不行。

**Comment by xbingW** [comment]
目前已定位到其他情况影响到的误拦截问题。明天的版本会修复

**Comment by xinuo** [comment]
更新了版本6.1.2之后，问题解决了。感谢。
