### ISSUE TITLE
[Bug] 添加防护站点后，1Panel、Next-terminal等终端无法访问

### ISSUE THREAD

**Issue by arch3rPro** [chaitin/SafeLine#814]
### 问题描述

Next-terminl和1panel 通过雷池代理访问后，Web端的终端访问、SSH连接、RDP，都是连上了，马上就断开了。
禁用防护模块，依然连不上

### 版本号

5.2.0

### 复现方法

1. 雷池添加防护站点，上游服务器设置为NPS代理服务器，NPS设置域名反代访问内网机器
2. 登录1panel或者Next-terminal，添加内网机器连接
3. 进入终端连接页面，连接成功，但是连完就断

### 期望的结果

可以正常访问终端

**Comment by Lvshujun0918** [comment]
我直接代理1Panel访问正常,需要更多信息

**Comment by arch3rPro** [comment]
反向代理套娃，解决了。 雷池 -> openresty -> NPS   虽然不知道哪的问题，好在能用了
