### ISSUE TITLE
[建议]  身份认证添加二步验证功能

### ISSUE THREAD

**Issue by arch3rPro** [chaitin/SafeLine#815]
### 背景与遇到的问题

身份认证已经有了密码登录功能，是否可以为每个防护站点添加二步验证功能，类似雷池管理页面的二步验证。因为有很多站点，本身是有账号密码登录，但是没有二步验证功能，有被爆破的风险。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
