### ISSUE TITLE
[Bug] 群晖似乎不太支持

### ISSUE THREAD

**Issue by wintsa123** [chaitin/SafeLine#819]
### 问题描述

我尝试使用群晖安装在线版本
第一个问题就是群晖没有自带的lscpu命令，我直接把bash的判断去掉开始安装
第二个问题就是提示我安装在哪，我尝试手动创建文件夹后居然跟我说文件夹已存在，这个bash脚本有点呆。我删除文件夹后执行，到了容器启动的时候提示有目录无法挂载，目录不存在。我看了下github的discussions，似乎还有很多问题，对于群晖部署。

### 版本号

3.0.0

### 复现方法

直接安装

### 期望的结果

希望docker能把多个环境打包成一个容器，然后数据库支持外置选择。
在discussions上看到的问题是db链接timeout，按道理来说docker部署兼容性不应该是最强的吗？

**Comment by wintsa123** [comment]
问题解决了，关键在于在群晖的时候作为bridge链接时，postgrep配置文件没有允许

**Comment by Lorna0** [comment]
relate to 
* https://github.com/chaitin/SafeLine/discussions/818
