### ISSUE TITLE
[Bug]  title和icon获取错误当上游服务器存在多个服务的时候

### ISSUE THREAD

**Issue by cnjack** [chaitin/SafeLine#821]
### 问题描述

当上游服务存在多个站点的时候，或者title和icon会出现错误

### 版本号

5.3.2

### 复现方法

1. 上游服务器设置nginx 并添加多个server_name 配置文件，每个指向到不同的目录，不同目录设置不同的head title和 icon
2. 在雷池WAF配置站点
![image](https://github.com/chaitin/SafeLine/assets/2562093/0b8ac411-4c5b-4b29-b923-090afb5e6943)

![image](https://github.com/chaitin/SafeLine/assets/2562093/21086717-11b1-4209-a2b6-4e8f08f6ef97)

### 期望的结果

当 enable的时候 传递客户端连接的 host 和协议， 携带host访问上游服务并且获取到正确的title和icon

**Comment by cnjack** [comment]
![image](https://github.com/chaitin/SafeLine/assets/2562093/0923bcf1-767e-4ef8-b614-f6507efecd0a)

**Comment by Lvshujun0918** [comment]
确实有这样的问题

**Comment by Lorna0** [comment]
“传递客户端连接的 host 和协议” 这个设置，并不是直接替换 Host 和协议（协议也不可能直接替换），而是指传递 X-Forwarded-Host、 X-Forwarded-Proto，选不选和这个问题没有关系：
![image](https://github.com/chaitin/SafeLine/assets/56920727/93cf6333-d8a3-4122-9b06-2845986c6dd6)

雷池在代理的时候，所用的 host 本身就是客户端的 host，只是在获取用于控制台展示的 title 和 icon 的时候没有这样处理，这个问题会在后续版本中修复。

**Comment by cnjack** [comment]
我以为上游是根据x-Forwarded-Host 来判断访问的是谁 然后忽略host里面的内容,看来我猜测错了. 我还在想如果通过x-Forwarded-Host是不是会很不安全.

**Comment by Lorna0** [comment]
> 我以为上游是根据x-Forwarded-Host 来判断访问的是谁 然后忽略host里面的内容,看来我猜测错了. 我还在想如果通过x-Forwarded-Host是不是会很不安全.

这种都是上游有相关的特殊处理。比如网站要返回一个用户能访问的绝对 url，就得知道客户端用的域名。还有些知道客户端连接的协议，是内部有要求连接必须为 https。总体用得并不多，站点访问起来没问题的话就不用管的。

**Comment by cnjack** [comment]
感谢解惑
