### ISSUE TITLE
safeline-tengine无故关闭

### ISSUE THREAD

**Issue by TuAgT** [chaitin/SafeLine#822]
### 容器日志📔
`
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:49:20.511439625Z"}
{"log":"2024/04/15 16:49:20 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:49:20.512648983Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:49:21.023407148Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:49:21.527194331Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:49:22.040008674Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:49:22.547815771Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:49:23.0597125Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:02.116697585Z"}
{"log":"2024/04/15 16:50:02 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:02.118309271Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:02.617432703Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:03.118520316Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:03.618940418Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:04.129395176Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:04.63015809Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:04.92727831Z"}
{"log":"2024/04/15 16:50:04 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:04.928655156Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:05.431390448Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:05.938699089Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:06.449468292Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:06.958799392Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:07.463963328Z"}
{"log":"2024/04/15 16:50:07 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:07.84789653Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:07.85253717Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:08.356765904Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:08.860008604Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:09.358653973Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:09.86961512Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:10.376419718Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:10.969477Z"}
{"log":"2024/04/15 16:50:10 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:10.971416257Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:11.470455165Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:11.978017717Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:12.486948407Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:12.986814344Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:13.487890344Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:14.47111069Z"}
{"log":"2024/04/15 16:50:14 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:14.472969764Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:14.981599333Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:15.488391319Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:15.995481253Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:16.496062255Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:17.001013486Z"}
{"log":"2024/04/15 16:50:18 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:18.756588554Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:18.763142123Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:19.271388174Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:19.778982131Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:20.289959018Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:20.790288821Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:21.316535263Z"}
{"log":"2024/04/15 16:50:24 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:24.663050165Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:24.668994113Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:25.170405961Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:25.677501553Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:26.182136419Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:26.682777984Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:27.189200458Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:33.747537637Z"}
{"log":"2024/04/15 16:50:33 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:33.748746245Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:34.24849547Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:34.749035411Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:35.252271188Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:35.758206635Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:36.265224566Z"}
{"log":"2024/04/15 16:50:49 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:50:49.196616687Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:49.204357195Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:49.717664487Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:50.227329601Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:50.731528356Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:50:51.23957533Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:50:51.746180788Z"}
{"log":"2024/04/15 16:51:17 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:51:17.525730372Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:51:17.532867109Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:51:18.042599458Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:51:18.551351595Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:51:19.05165578Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:51:19.559830893Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:51:20.06182652Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:52:11.465614118Z"}
{"log":"2024/04/15 16:52:11 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:52:11.467026353Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:52:11.971288769Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:52:12.478956532Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:52:12.990339065Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:52:13.490370085Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:52:13.993001643Z"}
{"log":"2024/04/15 16:53:14 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:53:14.174744366Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:53:14.181286969Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:53:14.689720984Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:53:15.197499291Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:53:15.707689539Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:53:16.217717382Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:53:16.723354746Z"}
{"log":"2024/04/15 16:54:16 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:54:16.864772708Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:54:16.869283615Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:54:17.373512473Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:54:17.882649493Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:54:18.393291205Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:54:18.895870087Z"}
{"log":"nginx: [emerg] still could not bind()\n","stream":"stderr","time":"2024-04-15T16:54:19.405190598Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:55:19.577528573Z"}
{"log":"2024/04/15 16:55:19 [INFO] config/config.go:22 nginx conf path: /etc/nginx/sites-enabled stream: false\n","stream":"stderr","time":"2024-04-15T16:55:19.578833283Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:55:20.079767765Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:55:20.585871785Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:55:21.085949893Z"}
{"log":"nginx: [emerg] bind() to 0.0.0.0:65443 failed (98: Unknown error)\n","stream":"stderr","time":"2024-04-15T16:55:21.588523731Z"}
`

**Comment by yrluke** [comment]
这个应该是因为65443端口被占用了

**Comment by pokebox** [comment]
> 这个应该是因为65443端口被占用了


65443这个端口有什么特别的用处么？

**Comment by zclaiqcc** [comment]
用于 safeline-tengine 自身的 health check
