### ISSUE TITLE
[建议] 希望雷池上面的各种功能能针对单个防护站点

### ISSUE THREAD

**Issue by erduo77** [chaitin/SafeLine#823]
### 背景与遇到的问题

雷池上面的一下功能设置，都是针对全局的，但是上面的各种功能设置都是针对所有防护站点的，但是我不同的站点可以需要不同的黑白名单，或者不同的方式或者源 ip。目前是不能这样的，导致统计和防护就不准确。
![image](https://github.com/chaitin/SafeLine/assets/144216104/978a1550-6c8d-46e3-ab2d-3149859e25e7)
![image](https://github.com/chaitin/SafeLine/assets/144216104/a3bd7dba-f698-4cad-b8ca-2ec0edb8c528)

### 建议的解决方案

建议增加各种设置是针对所有防护站点还是单个站点。

**Comment by Lorna0** [comment]
源 IP 获取方式和强制 HTTPS：
* https://github.com/chaitin/SafeLine/issues/436
* https://github.com/chaitin/SafeLine/issues/241

限频：
* https://github.com/chaitin/SafeLine/issues/209

黑白名单：
* https://github.com/chaitin/SafeLine/issues/347

另外，黑白名单、人机、身份认证现在就可以针对站点设置了，只要加匹配方式 “host” 就行。
看起来比较重要的需求之前都有重复 issue，这个 issue 范围有点大，就先关闭了，师傅可以点赞对应的 issue 进度加快进度。
