### ISSUE TITLE
[建议] 支持Windows系列的端

### ISSUE THREAD

**Issue by tianxiu2b2t** [chaitin/SafeLine#825]
### 背景与遇到的问题

我有一个机器，需要windows环境，但是这个公网目前有业务正在跑

### 建议的解决方案

可以支持windows docker的环境或者是其它等等

**Comment by Lorna0** [comment]
> 我有一个机器，需要windows环境，但是这个公网目前有业务正在跑

没看懂，啥意思？跟雷池支持 windows 的关系是什么

**Comment by gearfox** [comment]
windows上个虚拟机呗

**Comment by yrluke** [comment]
目前windows没办法支持，因为windows不支持docker network 的host模式，如果真的只能用windows，可以手动改成bridge模式，然后映射端口
