### ISSUE TITLE
[建议] 攻击事件和原始日志增加已读和未读的区分

### ISSUE THREAD

**Issue by xautlmx** [chaitin/SafeLine#826]
### 背景与遇到的问题

查看攻击事件和原始日志的时候无法区别哪些攻击日志是新产生的或者哪些攻击日志之前已经查看确认过了。现在只能依赖于原始日志中的攻击类型字段进行简单区别，如果攻击类型是“黑名单”那就说明这条攻击日志的攻击IP已经加入到黑名单了，不是新产生的有攻击行为的攻击IP；如果攻击类型不是“黑名单”，那就说明这条攻击日志的攻击IP还未加入黑名单，要新增封禁。

### 建议的解决方案

对于攻击事件和原始日志，把已经查看过的攻击日志和未查看过的攻击日志进行一定的区别，比如未查看的攻击日志新增个小红点，或者用不同的颜色显示，方便快速准确的查看到新增的攻击日志。

**Comment by Lorna0** [comment]
看你的具体场景，感觉和这个其实是类似需求：
* https://github.com/chaitin/SafeLine/issues/105

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
