### ISSUE TITLE
[Bug] http/2启用时，拦截不生效

### ISSUE THREAD

**Issue by wintsa123** [chaitin/SafeLine#827]
### 问题描述

![7fec8089949d66ae1c8c0d12daf60a9](https://github.com/chaitin/SafeLine/assets/47288630/3653be15-f540-4e5e-a864-186cd6231807)
开启http/2时拦截不生效

### 版本号

2024/4/12号的版本

### 复现方法

使用curl -vv -k -H "Host: <配置防护站点时域名处填的内容>" https://127.0.0.1/webshell.php
root@zwgczx:/# curl -vv -k -H "Host:xxxxxxxxxxxxxx.com" https://127.0.0.1/webshell.php
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /webshell.php HTTP/2
> Host:nexxxxst.xxxxxx.com
> user-agent: curl/7.86.0
> accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 404 
< server: Tengine
< date: Wed, 17 Apr 2024 06:24:52 GMT
< content-type: application/json; charset=utf-8
< content-length: 273
< cross-origin-opener-policy: same-origin
< cross-origin-resource-policy: same-origin
< origin-agent-cluster: ?1
< referrer-policy: no-referrer
< strict-transport-security: max-age=15552000; includeSubDomains
< x-content-type-options: nosniff
提示404，关闭http/2后正常拦截

![image](https://github.com/chaitin/SafeLine/assets/47288630/3c5156b9-fa58-4419-bad8-be22b8d5d124)

### 期望的结果

希望修好这个bug

**Comment by Lvshujun0918** [comment]
![image](https://github.com/chaitin/SafeLine/assets/41245552/83e262d8-34fe-4af4-86f9-8e1d7108ce80)
未复现
(可访问https://cszj.wang/webshell.php自行验证)

**Comment by wintsa123** [comment]
> ![image](https://private-user-images.githubusercontent.com/41245552/323200655-83e262d8-34fe-4af4-86f9-8e1d7108ce80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDQ3OTUsIm5iZiI6MTcxMzQwNDQ5NSwicGF0aCI6Ii80MTI0NTU1Mi8zMjMyMDA2NTUtODNlMjYyZDgtMzRmZS00YWY0LTg2ZjktOGUxZDcxMDhjZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAxNDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OGY2M2FhZTliMTMzNmM1MTIzODk1YjM1Yzk1YTllNTU4NGFkZmUwZmIzYjdiZTFhNzNhMTU3MDNmNDhhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eoE6Mxs-LJK9Wmesj5l7L5A4_chlK5Q6yfKURC625VY) 未复现 (可访问https://cszj.wang/webshell.php自行验证)


我尝试重新启用，似乎正常了，可能之前只是因为nginx的缓存问题
