### ISSUE TITLE
[建议] 建议规则匹配目标中的国家、地区考虑IPv6地址

### ISSUE THREAD

**Issue by baalchina** [chaitin/SafeLine#828]
### 背景与遇到的问题

目前规则中的国家地区似乎只考虑了ipv4地址？对于现在手机移动流量基本都启用ipv6了，很多教育、政府网站也启用v6,如果地区规则不支持v6的话可能效果会很差--->也会有一些误导。
THANKS

### 建议的解决方案

地区规则支持ipv6
或者在旁边注明只支持v4地址也可以，这样不会被误导

**Comment by Lvshujun0918** [comment]
主要是ipv6地址库比较难找

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/612

目前主要是没找到合适的库。
关于规则中的国家地区问题，我们会考虑一下如何进行提示。
