### ISSUE TITLE
[建议] 建议反代规则能更灵活

### ISSUE THREAD

**Issue by baalchina** [chaitin/SafeLine#829]
### 背景与遇到的问题

比如，nginx反代支持websocket，其实配置文件不复杂，但是由于waf用gui替代了命令行，虽然方便，但是却也缺少了自行调整的机会

### 建议的解决方案

1.增加常见的配置选项（最好还是能针对某个具体站点的）
2.或者允许手动调整具体某个站点的nginx配置文件（比如某反代产品，除了可以图形化编辑外，也提供了手动编辑配置文件的地方，如下图）
![image](https://github.com/chaitin/SafeLine/assets/3983019/57c0f70b-5ae1-45af-bbcb-d3d1333f00d4)

**Comment by Lvshujun0918** [comment]
已经可以手动调整了
可以详见https://waf-ce.chaitin.cn/docs/faq/other#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9-nginx-conf

**Comment by Lorna0** [comment]
建议先尝试按官方文档中的 自定义 nginx conf 操作一下。

不满足需求的话，请关注 duplicate issue：
* https://github.com/chaitin/SafeLine/issues/167
