### ISSUE TITLE
[Bug] 规则中IPv6地址显示不正确

### ISSUE THREAD

**Issue by baalchina** [chaitin/SafeLine#830]
### 问题描述

如图，实际上编辑页面是对的，但是显示页面IPv6地址显示不全
![PixPin_2024-04-17_20-43-02](https://github.com/chaitin/SafeLine/assets/3983019/dcb9f906-5cbb-4f09-9a6c-6658e5f22f3b)

### 版本号

Version 5.3.2

### 复现方法

打开防护配置-人机验证，添加一个IPv6地址即可

### 期望的结果

修复显示页面

**Comment by Lorna0** [comment]
5.5 版本中修复
