### ISSUE TITLE
部署站点使用https，使用curl测试没有完成加密协商

### ISSUE THREAD

**Issue by liusancai** [chaitin/SafeLine#832]
### 反馈内容

部署站点后，使用curl测试，发现不能完成正常的tsl协商，使用浏览器提示证书是正常的。
 Connected to gpt.dayoupi.cn (172.16.110.138) port 443
* ALPN: curl offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

**Comment by liusancai** [comment]
自己配置错误

**Comment by xinuo** [comment]
@liusancai 同样遇到这个问题，你最后是怎么配置正确的？

**Comment by liusancai** [comment]
> @liusancai 同样遇到这个问题，你最后是怎么配置正确的？

导入证书的时候有问题，试下文件直接导入，不要使用复制证书内容粘贴的方式。

**Comment by xinuo** [comment]
> > @liusancai 同样遇到这个问题，你最后是怎么配置正确的？
> 
> 导入证书的时候有问题，试下文件直接导入，不要使用复制证书内容粘贴的方式。

好，明白。
