### ISSUE TITLE
[Bug] 升级5.3.3后，之前4.3.3出现的luigiCPU异常占用和QPS显示为0，不记录日志有问题又来了

### ISSUE THREAD

**Issue by fankejing-just** [chaitin/SafeLine#833]
### 问题描述

参看已经关闭的问题 Issue #739

### 版本号

5.3.3

### 复现方法

从5.3.2升级到5.3.3 QPS保持在200左右，大概10-15分钟，LUIGI 开始持续异常占用CPU  QPS不再更新，防护日志不再纪录

### 期望的结果

修复BUG。

**Comment by xbingW** [comment]
方便给一下 cpu 和 heap 数据用于分析吗，发邮箱即可 xiaobing.wang@chaitin.com
```
curl http://127.0.0.1:1086/debug/pprof/profile -o profile.pb.gz
curl http://127.0.0.1:1086/debug/pprof/heap -o heap.pb.gz
```

**Comment by xbingW** [comment]
docker stats 看一下

**Comment by zhuanmentiwen** [comment]
上个版本是逼的重装。。看来5的版本又存在了。

**Comment by xbingW** [comment]
5.6.0 修复了 luigi 特定情况下的内存泄露问题，推荐升级一下再看看

**Comment by xbingW** [comment]
升级到最新的 5.6.0 版本再看下
