### ISSUE TITLE
[Bug] 访问指定目录被301重定向到源站端口的问题

### ISSUE THREAD

**Issue by e9f0accf08912a27** [chaitin/SafeLine#834]
### 问题描述

[其他用户反馈过](https://github.com/chaitin/SafeLine/issues/321)

### 版本号

5.3.3

### 复现方法

比如访问存在的目录https://xxx.com/test 会被重定向并加上源站的端口，例如：https://xxx.com:3541/test
3541为源站端口
![QQ图片20240419112959](https://github.com/chaitin/SafeLine/assets/153253111/10616847-80b2-439a-afe1-7b6e14a5c0a7)

### 期望的结果

期望请求目录https://xxx.com/test重定向到https://xxx.com/test/

**Comment by Lorna0** [comment]
[其他用户反馈过](https://github.com/chaitin/SafeLine/issues/321) 里回复了，这是上游的 nginx 行为，雷池控制不了也解决不了。
![image](https://github.com/chaitin/SafeLine/assets/56920727/601e8e78-4b5d-4288-8edc-f7a43b8339f2)

源问题已转成 discusion 了，评论里粘了个网上的技术文章，师傅尝试配置一下吧：https://github.com/chaitin/SafeLine/discussions/419
