### ISSUE TITLE
家用宽带没80端口好像无法正常使用

### ISSUE THREAD

**Issue by wintsa123** [chaitin/SafeLine#836]
### 反馈内容

![image](https://github.com/chaitin/SafeLine/assets/47288630/0b7ee8a6-bbed-4291-9180-9bf3f1994d97)
先发设置图，家用ddns一般都是通过域名加端口打开的，通过waf的反代，貌似是没监听端口成功？
![image](https://github.com/chaitin/SafeLine/assets/47288630/e609d69d-9a27-45cc-a2b9-de19f2e7f588)
但是我在公司的群晖上，有公网ip和80端口的使用正常

**Comment by Lvshujun0918** [comment]
`netstat -tunlp | grep 30000`看一下输出，另外域名只用保留前面一个即可，应该是不用加端口号的

**Comment by wintsa123** [comment]
解决了，没打开ipv6监听。因为家用是ddns ipv6的，我一直怀疑是反代规则没匹配上或者是bridge网桥监听的端口没监听到。
