### ISSUE TITLE
[建议] 提供社区黑名单IP的详情查询功能

### ISSUE THREAD

**Issue by youxianbo** [chaitin/SafeLine#837]
### 背景与遇到的问题

可以查看某个IP的来源，是他方还是我方添加，添加时间，攻击原因等有利于排查的有用信息，现在只有IP不知道是不是误报，有些一切正常的请求被意外拦截了，看到是黑名单，也不知道是我方添加的还是他方添加的，为什么是在黑名单中

**Comment by yrluke** [comment]
以目前的算法来说，都是大家一起上报的ip，即至少有n （n > 1）个用户上报才会加进去，所以说我们也没办法区分到底是你上报的还是别人上报的

**Comment by Lorna0** [comment]
黑名单的日志，查看日志详情，可以看到具体命中的黑名单名称的：
![image](https://github.com/chaitin/SafeLine/assets/56920727/512b747c-f653-45dc-a53b-9d31cf8d8962)
