### ISSUE TITLE
[Bug] 频率限制 127.0.0.1

### ISSUE THREAD

**Issue by TrumanDu** [chaitin/SafeLine#838]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/16727775/f06231b5-73f5-42cf-a3ec-06b354e9b4a3)

为什么会出现限制127.0.0.1？

![image](https://github.com/chaitin/SafeLine/assets/16727775/130e6c2f-4f85-4316-bba6-d472df277752)

### 版本号

5.3.3

### 复现方法

频率限制

### 期望的结果

不限制本机

**Comment by yrluke** [comment]
是有健康检查吗？如果是健康检查，我的建议是用ip和路径加个白

**Comment by Lvshujun0918** [comment]
把局域网地址加个白名单即可
