### ISSUE TITLE
[Bug] 人机验证问题

### ISSUE THREAD

**Issue by issueser** [chaitin/SafeLine#848]
### 问题描述

failed to load html from: https://challenge.rivers.chaitin.cn/captcha/api/index.html

### 版本号

5.3.3

### 复现方法

正常访问开启人机验证的站点

### 期望的结果

问题已间断出现两天，请问人机验证服务是否故障？
另外除了人机验证和共享威胁情报 IP，社区版在不升级专业版时还有什么功能是需要连接challenge.rivers.chaitin.cn或其他属于雷池的服务？

**Comment by NikoCat233** [comment]
本人今日复现此问题

**Comment by Lorna0** [comment]
> 问题已间断出现两天，请问人机验证服务是否故障？

人机验证服务当时确实存在波动，已经解决。因为 github 我们是定期翻阅，师傅下次如果遇到这样比较紧急的情况，可以现在交流群中 艾特管理员反馈，会响应快一些。

> 另外除了人机验证和共享威胁情报 IP，社区版在不升级专业版时还有什么功能是需要连接challenge.rivers.chaitin.cn或其他属于雷池的服务？

目前最新版还有这些需要访问公网：
* 搜索引擎爬虫 IP 需要访问 https://waf-ce.chaitin.cn/
* 获取左下角的更新提示需要访问 https://waf-ce.chaitin.cn/
* 申请免费证书需要访问 acme 的验证地址
* 获取右上角 “更多工具” 需要访问百川的最新推荐工具列表 https://rivers.chaitin.cn/api/recommend_tools
