### ISSUE TITLE
希望自定义规则中的黑名单可以增加“IP不等于”选项 

### ISSUE THREAD

**Issue by clqs803** [chaitin/safeline#85]
可以用来做敏感URL白名单，谢谢
![Snipaste_2023-05-27_13-35-57](https://github.com/chaitin/safeline/assets/80808022/d7fe65d4-f97b-4bfa-aef7-10318d2ea4f5)

**Comment by zclaiqcc** [comment]
先全拦截，然后单独有一条规则来加白？

**Comment by clqs803** [comment]
> 先全拦截，然后单独有一条规则来加白？

之前试过了，好像是黑名单的优先级太高了  不管用

**Comment by zclaiqcc** [comment]
暂时还没法调整自定义规则的顺序，是按照先后顺序来生效的。所以调换一下创建顺序试试？我理解应该是先创建白名单，然后创建黑名单

**Comment by clqs803** [comment]
> 暂时还没法调整自定义规则的顺序，是按照先后顺序来生效的。所以调换一下创建顺序试试？我理解应该是先创建白名单，然后创建黑名单

好的，感谢 我去试试

**Comment by zclaiqcc** [comment]
V1.7 把白名单都放在黑名单前面执行了，应该很方便处理这种场景了，师傅可以试一下
