### ISSUE TITLE
[Bug] 免费证书编辑时问题

### ISSUE THREAD

**Issue by QYG2297248353** [chaitin/SafeLine#850]
### 问题描述

升级后发现 证书已无法续签，手动申请证书后，新建了一个证书，旧的无法删除，都要手动修改.
今天升级的5.4.0不知道是否解决，但是上一个版本一定没有解决

### 版本号

5.4.0

### 复现方法

证书自动续签

### 期望的结果

修复此功能

**Comment by Lorna0** [comment]
5.6.2 中修复了证书续签的一个问题，可以升级尝试一下

**Comment by QYG2297248353** [comment]
升级过了，后几个版本升级记录都有关于证书续签的修复，早都手动续签完了，应该增加一个手动的一键续签，太麻烦了，申请完，更换，再删掉。

**Comment by Lorna0** [comment]
> 升级过了，后几个版本升级记录都有关于证书续签的修复，早都手动续签完了，应该增加一个手动的一键续签，太麻烦了，申请完，更换，再删掉。

正常情况下系统会自动续签，而且直接编辑当前证书就可以更新站点所用的证书了，不用换了删掉。是出现什么问题了吗

**Comment by QYG2297248353** [comment]
> > 升级过了，后几个版本升级记录都有关于证书续签的修复，早都手动续签完了，应该增加一个手动的一键续签，太麻烦了，申请完，更换，再删掉。
> 
> 正常情况下系统会自动续签，而且直接编辑当前证书就可以更新站点所用的证书了，不用换了删掉。是出现什么问题了吗

不会，我的证书列表会出现两张证书，并不会自动替换，一张是原来快过期的，一张是刚申请的

![image](https://github.com/chaitin/SafeLine/assets/56836951/3be6dfc9-1d94-4f59-bbc3-f289ba595a2d)
![image](https://github.com/chaitin/SafeLine/assets/56836951/dadc4173-dc9f-406e-b7c1-2ede39e71989)

**Comment by Lorna0** [comment]
> ###
> 升级后发现 证书已无法续签，手动申请证书后，新建了一个证书，旧的无法删除，都要手动修改. 今天升级的5.4.0不知道是否解决，但是上一个版本一定没有解决

你是指之前升级的 5.4.0 存在这个问题，还是指上面说的升级过了的 5.6.2 存在这个问题呢

**Comment by QYG2297248353** [comment]
> > 升级后发现 证书已无法续签，手动申请证书后，新建了一个证书，旧的无法删除，都要手动修改. 今天升级的5.4.0不知道是否解决，但是上一个版本一定没有解决
> 
> 你是指之前升级的 5.4.0 存在这个问题，还是指上面说的升级过了的 5.6.2 存在这个问题呢

最新版，我一直在升级，反正至今都是存在此问题

**Comment by Lorna0** [comment]
> > > 升级后发现 证书已无法续签，手动申请证书后，新建了一个证书，旧的无法删除，都要手动修改. 今天升级的5.4.0不知道是否解决，但是上一个版本一定没有解决
> > 
> > 
> > 你是指之前升级的 5.4.0 存在这个问题，还是指上面说的升级过了的 5.6.2 存在这个问题呢
> 
> 最新版，我一直在升级，反正至今都是存在此问题

我们确认一下

**Comment by Lorna0** [comment]
6.1 版本中已修复。

> 建议增加个一键续签按钮，证书过期老麻烦了，

我们会在后台加一个自动续签，如果证书自动续签失败，则会每天都尝试一次续签。

**Comment by QYG2297248353** [comment]
> 6.1 版本中已修复。
> 
> > 建议增加个一键续签按钮，证书过期老麻烦了，
> 
> 我们会在后台加一个自动续签，如果证书自动续签失败，则会每天都尝试一次续签。

不错不错，这个可以
