### ISSUE TITLE
[建议] 原始日志选项中攻击类型增加一个可以全选的功能。

### ISSUE THREAD

**Issue by zhuanmentiwen** [chaitin/SafeLine#851]
### 背景与遇到的问题

攻击事件的原始日志黑名单拦截的日志较多，影响平时对正常业务拦截的查找。而如果想排除黑名单的日志需要手动将所有攻击类型选一遍在去掉黑名单才能不显示。
为了提高对非黑名单共计的研判和查找正常业务被拦截，希望优化一下。

### 建议的解决方案

建议：
1、攻击类型勾选中可以有一个全选的选项，这样可以直接去掉不想看到的攻击类型。
2、或者黑名单拦截能单独给个选项查找这个类型的日志信息。

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/269
