### ISSUE TITLE
[Bug] 更新最新版本5.4.0之后无法添加站点

### ISSUE THREAD

**Issue by dpifox** [chaitin/SafeLine#855]
### 问题描述

![微信图片_20240427230730](https://github.com/chaitin/SafeLine/assets/57759622/7eae4bd5-2c83-4b05-8c35-74479183bc41)
![微信图片_20240427230727](https://github.com/chaitin/SafeLine/assets/57759622/cf5f8cf9-3def-4838-adda-ac22a7791e21)

### 版本号

5.4.0

### 复现方法

更新最新版本
添加站点

### 期望的结果

能正常添加站点

**Comment by yrluke** [comment]
麻烦贴一下safeline-tengine日志

**Comment by yu110y** [comment]
我也与遇到了

**Comment by dpifox** [comment]
> 我也与遇到了，全新重装也是如此

我找他们看了一下，他们说是这个版本新增加了127.0.0.1的网段，你用的不是大厂的服务器的话，可能系统没有自带这个网段，你手动添加一下，然后重启就好了。

**Comment by ton0312** [comment]
我也遇到一样问题，看了那个safeline-tengine日志，好像和ipv6有关系，把服务器ipv6 关闭就好了
