### ISSUE TITLE
[建议] 证书管理新增自定义的名称字段

### ISSUE THREAD

**Issue by wuxier** [chaitin/SafeLine#856]
### 背景与遇到的问题

证书到期更换时，上传证书后，当同一个域名有多个证书时，在站点里选择证书时不能准确选择正确需要替换的证书，只能选择后返回证书管理查看证书正在被那个站点使用

### 建议的解决方案

建议在证书管理新增一个自定义名称选项，可以在站点选择证书时通过自定义名称选择

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
