### ISSUE TITLE
safeline-mario反复重启

### ISSUE THREAD

**Issue by DoyoDia** [chaitin/safeline#86]
似乎是因为mario无法启动导致的网页面板出现错误
![image](https://github.com/chaitin/safeline/assets/79502694/2981ce70-fc0a-44b9-b0c0-897f08af44be)
日志：
[safeline-mario.csv](https://github.com/chaitin/safeline/files/11582574/safeline-mario.csv)
看起来是个空指针错误
compose.yml就是手动安装中提供的
.env的内容如图：
![image](https://github.com/chaitin/safeline/assets/79502694/7508fd63-fcf0-4a67-9acb-9fa08e72c849)

可以帮忙看一下是不是哪儿配置错了吗

**Comment by zclaiqcc** [comment]
看上去不止 safeline-mario 服务有异常，safeline-mgt-api 也没有启动成功。怀疑是之前已经部署过，这次是升级。但是没有在之前的目录下执行升级脚本（相当于重装了）？也看一下 safeline-mgt-api 容器的 log

**Comment by DoyoDia** [comment]
[safeline-mario (1).csv](https://github.com/chaitin/safeline/files/11592564/safeline-mario.1.csv)
[safeline-detector.csv](https://github.com/chaitin/safeline/files/11592565/safeline-detector.csv)
[safeline-postgres.csv](https://github.com/chaitin/safeline/files/11592566/safeline-postgres.csv)
[safeline-mgt-api.csv](https://github.com/chaitin/safeline/files/11592567/safeline-mgt-api.csv)
刚发现.env里的内网前缀和容器实际网络对不上，修改后重新构建mario是不会自动关闭了，但是显示警告。网页还是图一的样子——点什么都返回502
上面是所有有日志的容器的日志

**Comment by zclaiqcc** [comment]
感觉问题还挺综合，不麻烦的话，师傅可以直接重装么 🥲 理论上不需要手动创建文件夹，手动创建之后可能反而会有文件权限问题。

看起来师傅是在内网手动部署，可以参考 https://waf-ce.chaitin.cn/posts/guide_install 这里的「离线安装」。

我理解师傅这边可以尝试：
1. 手动下载 setup.sh 和 compose.yaml 放到同一个目录下，手动把 setup.sh 中一行 curl 注释掉（这行是用于从公网下载 compose.yaml）
2. 手动下载 docker 镜像，docker save & docker load（看起来这一步师傅已经搞定了）
3. 执行上面的 setup.sh 就可以了

**Comment by zclaiqcc** [comment]
以及 SUBNET_PREFIX 我理解是 169.254.0 ？看师傅最开始的图上写的是 169.254.1，不确定是不是手动操作失误了。

**Comment by DoyoDia** [comment]
因为之前在群晖里反复试了不行，所以我跑了个anlpine虚拟机来装雷池waf，原本1.17.0好好地，我看到新版本发布于是执行了升级脚本，第一次疏忽了，直接在根目录执行，第二次才cd进文件夹执行。现在又遇到了题目里的问题，mario现在又在反复重启

log:~/safeline# docker logs safeline-mario
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for plumber, use name as default value"
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for persistence, use name as default value"
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for forward, use name as default value"
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for envelop, use name as default value"
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for detect, use name as default value"
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for stat, use name as default value"
time="2023/06/06 13:38:43" level=debug msg="'type' not found in config for model, use name as default value"
time="2023/06/06 13:38:43" level=warning msg="mgt_server_url is not set, acl policy, plugin state/log and etc will be disabled"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbcac07]

goroutine 112 [running]:
gorm.io/gorm.(*DB).Transaction(0x0, 0xc000b47040, {0x0, 0x0, 0x0})
	/go/pkg/mod/gorm.io/gorm@v1.24.7-0.20230306060331-85eaf9eeda11/finisher_api.go:617 +0x67
git.in.chaitin.net/patronus/safeline-2/mario/server/plumber/stat/summary.(*Service).systemStatistics(0x0?, {0x0, 0xc000892000, 0x0, 0x0, 0x0, 0x0, 0x0, {0x647ec65b, 0x0, ...}, ...})
	/builds/patronus/safeline-ce/mario/server/plumber/stat/summary/service.go:129 +0x165
created by git.in.chaitin.net/patronus/safeline-2/mario/server/plumber/stat/summary.newTotalAccessStatTask.func1
	/builds/patronus/safeline-ce/mario/server/plumber/stat/summary/tasks.go:109 +0xf6
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for plumber, use name as default value"
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for persistence, use name as default value"
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for forward, use name as default value"
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for envelop, use name as default value"
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for detect, use name as default value"
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for stat, use name as default value"
time="2023/06/06 13:39:18" level=debug msg="'type' not found in config for model, use name as default value"
time="2023/06/06 13:39:18" level=warning msg="mgt_server_url is not set, acl policy, plugin state/log and etc will be disabled"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for plumber, use name as default value"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for persistence, use name as default value"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for stat, use name as default value"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for model, use name as default value"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for forward, use name as default value"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for envelop, use name as default value"
time="2023/06/06 13:39:52" level=debug msg="'type' not found in config for detect, use name as default value"
time="2023/06/06 13:39:52" level=warning msg="mgt_server_url is not set, acl policy, plugin state/log and etc will be disabled"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for persistence, use name as default value"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for plumber, use name as default value"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for forward, use name as default value"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for envelop, use name as default value"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for detect, use name as default value"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for stat, use name as default value"
time="2023/06/06 13:40:19" level=debug msg="'type' not found in config for model, use name as default value"
time="2023/06/06 13:40:19" level=warning msg="mgt_server_url is not set, acl policy, plugin state/log and etc will be disabled"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for plumber, use name as default value"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for persistence, use name as default value"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for model, use name as default value"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for forward, use name as default value"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for envelop, use name as default value"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for detect, use name as default value"
time="2023/06/06 13:40:46" level=debug msg="'type' not found in config for stat, use name as default value"
time="2023/06/06 13:40:46" level=warning msg="mgt_server_url is not set, acl policy, plugin state/log and etc will be disabled"

**Comment by DoyoDia** [comment]
13:43的重启之后就好了.....我什么也没做，他就自己好了。WTF？

**Comment by zclaiqcc** [comment]
先关闭了，有类似问题再 Reopen

**Comment by pusidun** [comment]
v1.8.2版本也遇到过一模一样的报错，升级到1.9版本好了

**Comment by freeAhao** [comment]
我这里openwrt上的docker关闭iptables后，开始出现这个异常。

关闭docker iptables是因为docker添加的规则在WAN规则前（filter表FORWARD链），导致所有docker映射的端口直接开放到WAN口上。
