### ISSUE TITLE
[Bug]  5.4 版本在防护配置 如果条件是Host ，如果Host是带有端口的 比如  a.example.com:8080 则保存之后 规则只能显示8080 ，并且规则不会生效

### ISSUE THREAD

**Issue by paddypq** [chaitin/SafeLine#860]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/106520003/a8843922-5e2f-46ea-a0c1-b93703094d87)

![image](https://github.com/chaitin/SafeLine/assets/106520003/43b7d675-d4d8-457c-be0a-42d389cc7675)

### 版本号

5.4.0

### 复现方法

1. 升级到5.4 版本
2. 进入防护设置，设置 黑白名单， 添加黑名单
3. 匹配目标选择host   选择  等于/不等于/模糊匹配 输入  a.example.com:8080 
4. 保存黑名单。 发现页面只能显示冒号之后的端口
5. 进行访问测试发现 黑名单规则没有生效
6. 影响所有的 需要设置host的地方
7. 老版本工作证

### 期望的结果

在防护条件是host的时候， 并且host 有端口的话 需要保留 a.example.com:8080

**Comment by yrluke** [comment]
这个是看上一跳是怎么传进来的，这个地方最近版本没有修改过，麻烦检查一下上一跳配置

**Comment by panp1** [comment]
这个第一有2个问题   1个是UI  保存之后 只显示端口， 第二个就是规则 不生效。   没有上一跳， 这个直接暴露在外面一个公网IP 我试了几种情况   80 443 这种没有端口的 我在host 直接写hostname 是没问题能看到waf 生效有 拦截或者人机校验， 我用非标端口  比如  8080 8888 之类的 我在log 看到拿到的host是 hostname:端口 这边配置hostname:端口 发现没有拦截

**Comment by panp1** [comment]
我碰到同样问题

**Comment by panp1** [comment]
![image](https://github.com/chaitin/SafeLine/assets/107453035/d8d3ed2c-4c37-4c4c-83ad-723967f18aa4) 
在规则设置 HOST 不带端口  指定host  工作正常。 
规则设置里面 HOST 带端口 UI 不正常， 拦截也不正常。 HOST 这边存在问题

**Comment by paddypq** [comment]
貌似在5.51 修好了 可以关了
