### ISSUE TITLE
[Bug]当后端down掉重启可正常访问后，访问页面仍然显示504

### ISSUE THREAD

**Issue by omanikk** [chaitin/SafeLine#864]
### 问题描述

复现如下：后端是一个互联网地址，前面用waf代理，当后端重启后，访问雷池代理的地址仍然是504网关超时，但是直接访问的后端互联网地址一切正常

### 版本号

Version 5.4.0

### 复现方法

复现如下：
1.给后端开一个互联网地址，前面用waf代理，
3.确认访问雷池代理正常后，手动关闭后端，此时雷池显示504
2.给后端重启，访问雷池代理的地址仍然是504网关超时，但是直接访问的后端互联网地址一切正常

### 期望的结果

希望有解决方案或者指出我哪里配置有误

**Comment by yrluke** [comment]
清理一下浏览器缓存试试

**Comment by omanikk** [comment]
你好，不是缓存的问题，我实测
重新启动 safeline-tengine 容器问题即可解决


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chaitin/SafeLine] [Bug]当后端down掉重启可正常访问后，访问页面仍然显示504 (Issue #864)




 
清理一下浏览器缓存试试

**Comment by zclaiqcc** [comment]
是说用 WAF 代理自身的 :9443 管理页面么？可能是 tengine 代理内部的缓存，重启解决了就行
