### ISSUE TITLE
[建议] 支持将源 IP 设置到特定header中，向上游服务器传输

### ISSUE THREAD

**Issue by R0A1NG** [chaitin/SafeLine#865]
### 背景与遇到的问题

将真实客户端IP以自定义header头的形式发送给内网服务器，而不是默认在X-Forwarded-For增加真实IP

**Comment by Lorna0** [comment]
具体背景与遇到的问题？
内网服务器不支持解析么

**Comment by R0A1NG** [comment]
> 具体背景与遇到的问题？ 内网服务器不支持解析么

是的，现在内网的X-Forwarded-For只获取第一个，内网部分位置没法改代码获取IP。最好自定义一个header来单独放真实IP

**Comment by Lorna0** [comment]
临时解决方法：参考官网文档的自定义 nginx conf，在站点的后台 conf 中增加一个 proxy_set_header

**Comment by xbingW** [comment]
最新版 6.9.0 已支持自定义 header
