### ISSUE TITLE
[建议] 关于人机验证用户体验问题

### ISSUE THREAD

**Issue by wwbrave** [chaitin/SafeLine#866]
### 背景与遇到的问题

我们从更新4.4.0开始发现雷池引入了旋转式的人机验证方法，自从更新了之后，我们收到非常多的用户反馈该方法不太友好，难以对其是他们反馈的一个点，还有很多反馈是说他们很难理解旋转的动作怎么做（需要体谅一些年级较大用户群体）。

### 建议的解决方案

是否有可能在日后的版本中增加人机验证方法的选项，给出一些可以选择的验证方法，比如时下比较流行的横向滑块、图中找文字、图中找图等方法。

**Comment by Lorna0** [comment]
人机验证合并交互和非交互的选项，主要是希望降低使用门槛，希望更好理解。目前验证的逻辑是，先自动检查客户端，如果比较正常，就直接通过。如果疑似机器人，就进入旋转图片验证以最终确认。

一般来说出现旋转验证的几率比较低，不到十分之一。师傅能帮忙收集一下经常旋转验证的客户端信息么，我们看看是不是存在误判。

**Comment by wwbrave** [comment]
由于是开放站点，我们也很难联系到客户看到客户的环境，的确如您所说，我们在内部测试时出现旋转验证的几率并不高，但确实有很多客户反馈这个问题。
我们认为，对于相当一部分企业来说，受面向的客户群体影响，旋转这个人机验证的方式可能并不友好，所以才提出这个建议。

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
