### ISSUE TITLE
[Bug] 升级5.5.0后，之前配置的自定义IP组，无法正常编辑

### ISSUE THREAD

**Issue by hope250** [chaitin/SafeLine#871]
### 问题描述

之前配置的自定义IP组，在列表中可以看到有内容。
但是升级5.5.0后，点击编辑按钮，内容区域空空如也，无法编辑。
![2024-05-10_13-49](https://github.com/chaitin/SafeLine/assets/38972222/0fabda13-b60d-4701-a8ec-0e3deb3dde56)
![2024-05-10_13-50](https://github.com/chaitin/SafeLine/assets/38972222/e2610950-4c86-4584-8c74-1c852f6325ef)

### 版本号

5.5.0

### 复现方法

1、之前版本定义的IP组
2、升级5.5.0
3、进入IP组列表，可以看到自定义IP组的内容预览
4、点击编辑，内容区空白

### 期望的结果

正常编辑之前的自定义IP组

**Comment by Lorna0** [comment]
新版本中已修复，可以确认一下
