### ISSUE TITLE
使用雷池提示未备案，但如果使用nginx的反向代理则不会提示备案

### ISSUE THREAD

**Issue by 65658dsf** [chaitin/SafeLine#874]
### 反馈内容

nginx：
![4968fa21ec426b4b2b50388b51508bf](https://github.com/chaitin/SafeLine/assets/78797486/c8d6357b-75af-4af1-af5b-81c7ac376c6f)
雷池：
![4fb2fa389d5cc3bc7ce4f7e5f8d9a5c](https://github.com/chaitin/SafeLine/assets/78797486/735f4bcb-6d49-4254-a141-24245442c665)

**Comment by Lvshujun0918** [comment]
是不是把host头传过去了，nginx.conf里面自己改一下

**Comment by 65658dsf** [comment]
请问一下应该怎么去修改呢？找了一下没找到怎么修改

**Comment by Lorna0** [comment]
备案跟网站服务器的 IP 是有关系的，域名备案之后如果要换服务器，尤其是换服务器运营商的话，多半就要修改，你得看看雷池对应的服务器的情况。

与雷池无关，先 close，有问题可以继续反馈

**Comment by Lorna0** [comment]
![image](https://github.com/chaitin/SafeLine/assets/56920727/56c664b9-78f6-4d8f-b074-4b9784396e89)
