### ISSUE TITLE
[建议] 能否增加屏蔽ASN的方法

### ISSUE THREAD

**Issue by wxhbts** [chaitin/SafeLine#878]
### 背景与遇到的问题

和cloudflare的一样

**Comment by tokpig** [comment]
我也是，我想屏蔽国内的各大云服务商，，，，，可是屏蔽不了

**Comment by Lvshujun0918** [comment]
你只要把asnIP存在IP组里就行了啊

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/222
