### ISSUE TITLE
希望能增加屏蔽国外IP访问功能 / 根据地理位置拦截或人机验证

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#88]
希望能增加屏蔽国外IP访问功能
点个赞，给师傅看看呼声会有多大。

**Comment by imgfile** [comment]
<div class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-u1hwnz" role="dialog" aria-labelledby=":rds:"><h2 class="MuiTypography-root MuiTypography-h6 MuiDialogTitle-root css-1qsqmqc" id=":rds:">编辑黑白名单<button class="MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium css-c58ih4" tabindex="0" type="button"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-1t8mnmp" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="CloseIcon"><path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"></path></svg><span class="MuiTouchRipple-root css-w0pj6f"></span></button></h2><div class="MuiDialogContent-root css-1ty026z"><div class="MuiFormGroup-root MuiFormGroup-row css-1mockef" role="radiogroup"><label class="MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-120kuyh"><span class="MuiButtonBase-root MuiRadio-root MuiRadio-colorPrimary PrivateSwitchBase-root MuiRadio-root MuiRadio-colorPrimary Mui-checked MuiRadio-root MuiRadio-colorPrimary css-rh0wyb"><input class="PrivateSwitchBase-input css-1m9pwf3" name="action" type="radio" value="1" checked=""><span class="css-hyxlzm"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeSmall css-cpa9t9" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="RadioButtonUncheckedIcon"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"></path></svg><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeSmall css-vrv9vb" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="RadioButtonCheckedIcon"><path d="M8.465 8.465C9.37 7.56 10.62 7 12 7C14.76 7 17 9.24 17 12C17 13.38 16.44 14.63 15.535 15.535C14.63 16.44 13.38 17 12 17C9.24 17 7 14.76 7 12C7 10.62 7.56 9.37 8.465 8.465Z"></path></svg></span><span class="MuiTouchRipple-root css-w0pj6f"></span></span><span class="MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-tfjp5k"><div class="MuiBox-root css-70qvj9"><svg class="MuiBox-root css-113evs3" aria-hidden="true"><use xlink:href="#icon-heimingdan"></use></svg>黑名单</div></span></label><label class="MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-1rarljl"><span class="MuiButtonBase-root MuiRadio-root MuiRadio-colorPrimary PrivateSwitchBase-root MuiRadio-root MuiRadio-colorPrimary MuiRadio-root MuiRadio-colorPrimary css-rh0wyb"><input class="PrivateSwitchBase-input css-1m9pwf3" name="action" type="radio" value="0"><span class="css-hyxlzm"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeSmall css-cpa9t9" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="RadioButtonUncheckedIcon"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"></path></svg><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeSmall css-1exsolk" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="RadioButtonCheckedIcon"><path d="M8.465 8.465C9.37 7.56 10.62 7 12 7C14.76 7 17 9.24 17 12C17 13.38 16.44 14.63 15.535 15.535C14.63 16.44 13.38 17 12 17C9.24 17 7 14.76 7 12C7 10.62 7.56 9.37 8.465 8.465Z"></path></svg></span><span class="MuiTouchRipple-root css-w0pj6f"></span></span><span class="MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-tfjp5k"><div class="MuiBox-root css-70qvj9"><svg class="MuiBox-root css-ttovpo" aria-hidden="true"><use xlink:href="#icon-baimingdan"></use></svg>白名单</div></span></label></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiFormControl-fullWidth MuiTextField-root css-1snm6ub"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":re0:" id=":re0:-label">名称<span aria-hidden="true" class="MuiFormLabel-asterisk MuiInputLabel-asterisk css-qyds0d">&thinsp;*</span></label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-sizeSmall css-10banla"><input aria-invalid="false" autocomplete="off" id=":re0:" name="comment" required="" type="text" class="MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1lf96kb" value=""><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>名称&thinsp;*</span></legend></fieldset></div></div><div class="MuiBox-root css-0"><div class="MuiBox-root css-1f5e1yp"><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-mup1iz"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":re5:" id=":re5:-label">匹配目标</label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":re5:-label :re5:" id=":re5:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">源 IP</div><input aria-invalid="false" name="patterns.0.k" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" value="src_ip"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>匹配目标</span></legend></fieldset></div></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-q5mmsf"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":re6:" id=":re6:-label">匹配方式<span aria-hidden="true" class="MuiFormLabel-asterisk MuiInputLabel-asterisk css-qyds0d">&thinsp;*</span></label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":re6:-label :re6:" id=":re6:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">不属于 IP 组</div><input aria-invalid="false" name="patterns.0.op" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" required="" value="not_in"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>匹配方式&thinsp;*</span></legend></fieldset></div></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-1sj49yf"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":re7:" id=":re7:-label">IP 组</label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":re7:-label :re7:" id=":re7:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">中国大陆IP 来自https://github.com/ma</div><input aria-invalid="false" name="patterns.0.v" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" value="1"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>IP 组</span></legend></fieldset></div></div><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-cugvos" tabindex="0" type="button">删除<span class="MuiTouchRipple-root css-w0pj6f"></span></button></div><div class="MuiBox-root css-1f5e1yp"><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-mup1iz"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":re8:" id=":re8:-label">匹配目标</label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":re8:-label :re8:" id=":re8:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">源 IP</div><input aria-invalid="false" name="patterns.1.k" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" value="src_ip"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>匹配目标</span></legend></fieldset></div></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-q5mmsf"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":re9:" id=":re9:-label">匹配方式<span aria-hidden="true" class="MuiFormLabel-asterisk MuiInputLabel-asterisk css-qyds0d">&thinsp;*</span></label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":re9:-label :re9:" id=":re9:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">不属于 IP 组</div><input aria-invalid="false" name="patterns.1.op" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" required="" value="not_in"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>匹配方式&thinsp;*</span></legend></fieldset></div></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-1sj49yf"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":rea:" id=":rea:-label">IP 组</label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":rea:-label :rea:" id=":rea:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">内网IP</div><input aria-invalid="false" name="patterns.1.v" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" value="2"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>IP 组</span></legend></fieldset></div></div><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-cugvos" tabindex="0" type="button">删除<span class="MuiTouchRipple-root css-w0pj6f"></span></button></div><div class="MuiBox-root css-1f5e1yp"><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-mup1iz"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":reb:" id=":reb:-label">匹配目标</label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":reb:-label :reb:" id=":reb:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">源 IP</div><input aria-invalid="false" name="patterns.2.k" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" value="src_ip"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>匹配目标</span></legend></fieldset></div></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-q5mmsf"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":rec:" id=":rec:-label">匹配方式<span aria-hidden="true" class="MuiFormLabel-asterisk MuiInputLabel-asterisk css-qyds0d">&thinsp;*</span></label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":rec:-label :rec:" id=":rec:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">不属于 IP 组</div><input aria-invalid="false" name="patterns.2.op" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" required="" value="not_in"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>匹配方式&thinsp;*</span></legend></fieldset></div></div><div class="MuiFormControl-root MuiFormControl-marginNormal MuiTextField-root css-1sj49yf"><label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeSmall MuiInputLabel-outlined css-q4vc8h" data-shrink="true" for=":red:" id=":red:-label">IP 组</label><div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-7ofojo"><div tabindex="0" role="button" aria-expanded="false" aria-haspopup="listbox" aria-labelledby=":red:-label :red:" id=":red:" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-15bcwz0">我的代理</div><input aria-invalid="false" name="patterns.2.v" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" value="3"><svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSelect-icon MuiSelect-iconOutlined css-1636szt" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowDropDownIcon"><path d="M7 10l5 5 5-5z"></path></svg><fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac"><legend class="css-14lo706"><span>IP 组</span></legend></fieldset></div></div><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-cugvos" tabindex="0" type="button">删除<span class="MuiTouchRipple-root css-w0pj6f"></span></button></div><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1jqca3i" tabindex="0" type="button">添加一个匹配条件<span class="MuiTouchRipple-root css-w0pj6f"></span></button></div></div><div class="MuiDialogActions-root MuiDialogActions-spacing css-ghmz85"><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1jqca3i" tabindex="0" type="button">取消<span class="MuiTouchRipple-root css-w0pj6f"></span></button><button class="MuiButtonBase-root MuiButton-root MuiLoadingButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-root MuiLoadingButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium css-9lfzpi" tabindex="0" type="button" id=":re4:">提交<span class="MuiTouchRipple-root css-w0pj6f"></span></button></div></div>

**Comment by ZTfred** [comment]
这个功能，可以给nginx增加 geoip 的模块实现，看产品会不会给添加了

**Comment by zclaiqcc** [comment]
> 这个功能，可以给nginx增加 geoip 的模块实现，看产品会不会给添加了

还是倾向于在检测引擎实现，转发侧只负责转发就好了，这样解耦一些。当然也有一些统计和服务降级机制相关的考虑。如果是基于 nginx 就可以实现的话，师傅甚至可以尝试自己 DIY 一个 nginx，https://zhuanlan.zhihu.com/p/641116243 ，在 nginx 继承 geoip + lua-t1k，自己搞定转发引擎的部分。美滋滋

**Comment by zhuanmentiwen** [comment]
很多国内站点根本不需要国外访问，我希望能够在黑名单添加中源IP组可以选择：国外IP组，禁止访问。这个组可以自动调取咱内置的IP库国外ip段。。

这样可以有效避免国外ip的攻击，毕竟站点不需要国外访问的应用较多，如有国内特定地区允许访问的，可以自己自定义添加ip组即可。

希望先把这个单独禁止国外ip段的功能先上上，感谢。。

**Comment by zh-mead** [comment]
希望先把这个单独禁止国外ip段的功能先上上，感谢。。

**Comment by hongfs** [comment]
> > 这个功能，可以给nginx增加 geoip 的模块实现，看产品会不会给添加了
> 
> 还是倾向于在检测引擎实现，转发侧只负责转发就好了，这样解耦一些。当然也有一些统计和服务降级机制相关的考虑。如果是基于 nginx 就可以实现的话，师傅甚至可以尝试自己 DIY 一个 nginx，https://zhuanlan.zhihu.com/p/641116243 ，在 nginx 继承 geoip + lua-t1k，自己搞定转发引擎的部分。美滋滋

自己 DIY 一个 nginx 不利于升级吧，如果 nginx 支持 geoip 模块，我们直接在 custom_params 做处理就可以了。

**Comment by jssolo** [comment]
支持

**Comment by williamtsang88** [comment]
这边找到一个国家/地区IP段的数据库，仅供参考：https://www.ipdeny.com/ipblocks/。

**Comment by Mikeliao123** [comment]
可以参考 ：
如何通过openresty 限制国外Ip访问 ：
https://blog.csdn.net/qq_41506710/article/details/135522099
代码如下：
https://gitee.com/xiaoyun461/blocking-external-networks

**Comment by baibaiii** [comment]
请问目前有师傅 实现国外IP触发人机验证吗？
我想实现当 国外IP访问demo.com 触发人机验证，而不是触发黑名单规则。【当host等于demo.com and 源IP不属于IP组 国内IP and 源IP不属于内网IP组】当按照规则写入人机验证规则，会导致国内的IP和内网也触发人机验证。

**Comment by gearfox** [comment]
希望粒度能精确到省份，有些业务真不需要外省访问

**Comment by Lorna0** [comment]
雷池社区版计划在即将推出的专业版（预计 4.4）上支持 ”根据地理位置库进行拦截“。主要原因是目前的地理位置库是商业化的，不容易直接下放到社区版。

社区版的师傅有需要的话，可以通过 黑白名单 -> 添加黑名单 -> 匹配条件选 “源 IP”“不属于 IP 组” 来实现（IP 组内填中国大陆的 IP 段，上面师傅们分享的列表都可以尝试）。因为中国大陆的 IP 段变化小，所以这个方法的准确性还不错，未来我们也会继续探索能否优化社区版上的相关能力。

**Comment by safe1ine** [comment]
4.4.0 版本已支持，考虑到雷池采购外部 IP 库有成本，目前该功能仅对专业版用户开放

**Comment by 20has** [comment]
> 雷池社区版计划在即将推出的专业版（预计 4.4）上支持 ”根据地理位置库进行拦截“。主要原因是目前的地理位置库是商业化的，不容易直接下放到社区版。
> 
> 社区版的师傅有需要的话，可以通过 黑白名单 -> 添加黑名单 -> 匹配条件选 “源 IP”“不属于 IP 组” 来实现（IP 组内填中国大陆的 IP 段，上面师傅们分享的列表都可以尝试）。因为中国大陆的 IP 段变化小，所以这个方法的准确性还不错，未来我们也会继续探索能否优化社区版上的相关能力。

目前来看，中国区的IP组数量大约是5k多点，请问能不能放行IP组订阅手动更新记录为5000条呢？

**Comment by 20has** [comment]
虽然现在也可以切分5个IP组 来作为黑名单来使用，但是就不太好使用订阅更新的功能了。
社区版要是能放开这个记录限制功能就更好了。

**Comment by AlliotTech** [comment]
> > 雷池社区版计划在即将推出的专业版（预计 4.4）上支持 ”根据地理位置库进行拦截“。主要原因是目前的地理位置库是商业化的，不容易直接下放到社区版。
> > 社区版的师傅有需要的话，可以通过 黑白名单 -> 添加黑名单 -> 匹配条件选 “源 IP”“不属于 IP 组” 来实现（IP 组内填中国大陆的 IP 段，上面师傅们分享的列表都可以尝试）。因为中国大陆的 IP 段变化小，所以这个方法的准确性还不错，未来我们也会继续探索能否优化社区版上的相关能力。
> 
> 目前来看，中国区的IP组数量大约是5k多点，请问能不能放行IP组订阅手动更新记录为5000条呢？


使用接口是可以突破这个限制的。

**Comment by 20has** [comment]
> > > 雷池社区版计划在即将推出的专业版（预计 4.4）上支持 ”根据地理位置库进行拦截“。主要原因是目前的地理位置库是商业化的，不容易直接下放到社区版。
> > > 社区版的师傅有需要的话，可以通过 黑白名单 -> 添加黑名单 -> 匹配条件选 “源 IP”“不属于 IP 组” 来实现（IP 组内填中国大陆的 IP 段，上面师傅们分享的列表都可以尝试）。因为中国大陆的 IP 段变化小，所以这个方法的准确性还不错，未来我们也会继续探索能否优化社区版上的相关能力。
> > 
> > 
> > 目前来看，中国区的IP组数量大约是5k多点，请问能不能放行IP组订阅手动更新记录为5000条呢？
> 
> 使用接口是可以突破这个限制的。 参照：[#88 (comment)](https://github.com/chaitin/SafeLine/issues/88#issuecomment-2047766007)

嗯  多谢老哥提醒 我去搭配1panel来调试下这个python脚本试试 
我需求 只需要这个ip组的订阅更新就好了 
https://mirror.ghproxy.com/https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt

**Comment by 20has** [comment]
> > > > 雷池社区版计划在即将推出的专业版（预计 4.4）上支持 ”根据地理位置库进行拦截“。主要原因是目前的地理位置库是商业化的，不容易直接下放到社区版。
> > > > 社区版的师傅有需要的话，可以通过 黑白名单 -> 添加黑名单 -> 匹配条件选 “源 IP”“不属于 IP 组” 来实现（IP 组内填中国大陆的 IP 段，上面师傅们分享的列表都可以尝试）。因为中国大陆的 IP 段变化小，所以这个方法的准确性还不错，未来我们也会继续探索能否优化社区版上的相关能力。
> > > 
> > > 
> > > 目前来看，中国区的IP组数量大约是5k多点，请问能不能放行IP组订阅手动更新记录为5000条呢？
> > 
> > 
> > 使用接口是可以突破这个限制的。 参照：[#88 (comment)](https://github.com/chaitin/SafeLine/issues/88#issuecomment-2047766007)
> 
> 嗯 多谢老哥提醒 我去搭配1panel来调试下这个python脚本试试 我需求 只需要这个ip组的订阅更新就好了 https://mirror.ghproxy.com/https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt

最近的进度再来更新下：  目前手动复制这8k多个IP粘贴到输入框即可！！！

**Comment by charnet1019** [comment]
https://mailfud.org/geoip-legacy/  这边可以下载免费的geo库，如果tengine支持加载这个库的话可以让社区用户自己上传也可以
