### ISSUE TITLE
[Bug] 申请证书报错missing field: hash

### ISSUE THREAD

**Issue by wheat0r** [chaitin/SafeLine#881]
### 问题描述

添加证书 - 申请免费证书
正常填写域名和邮箱并提交后提示missing field: hash
日志显示 `client/task.go:79 acmeRequest missing field: hash`

### 版本号

5.6.0

### 复现方法

添加证书 - 申请免费证书

### 期望的结果

正常完成证书申请，或提供更明确的报错信息。

**Comment by xbingW** [comment]
最新的 5.6.1 已修复
