### ISSUE TITLE
[建议] 出个nginx自定义配置功能吧，目前修改配置有点不是很顺手

### ISSUE THREAD

**Issue by SandmanvrDev** [chaitin/SafeLine#884]
### 背景与遇到的问题

最近需要针对单个站点优化NGinx配置。看了官网的配置示例文档，我承认才疏学浅，难到我了。半猜半就完成了修改。
这个文档写的很笼统，当然应该是给专业人看的，但是八两人看到这个文章，容易晕菜。[帮助示例](https://waf-ce.chaitin.cn/docs/faq/other#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9-nginx-conf)
我看有好多个提建议增加自定义配置添加项[167](https://github.com/chaitin/SafeLine/issues/167)，  #580、#579

### 建议的解决方案

可以借鉴nginx proxy manager的自定义配置功能。也是独立站点，独立配置文件，也能分片合并到配置文件中。

**Comment by yrluke** [comment]
可以在nginx和业务服务器之间加入一个nginx，专门用来处理你的nginx配置

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/167
