### ISSUE TITLE
[建议] 自定义规则（原黑白名单、人机验证）增加匹配目标能选择站点或者源域名匹配

### ISSUE THREAD

**Issue by peng2289** [chaitin/SafeLine#886]
### 背景与遇到的问题

每个站点可能功能不同，限制和规则可能都不一样，比如有些站点不存在特殊文件的比如zip、sql、jsp等，这种我可以进行专项拦截。

### 建议的解决方案

![image](https://github.com/chaitin/SafeLine/assets/18732497/d4380533-a066-4be0-b406-321a3ef65342)
这个匹配目标可以增加站点，然后选择站点，这样就可以进行指定站点规则才生效。
host可能存在篡改的可能

也可以增加源域名的匹配方式也可以，这样也灵活

**Comment by Lorna0** [comment]
篡改 host 是访问不到网站的（除非网站可以允许所有 host 访问），不会产生额外的风险呀。

这个改动主要还是用起来会方便一些，情在已有 issue 中讨论：
* https://github.com/chaitin/SafeLine/issues/347
