### ISSUE TITLE
建议新增个人永久版授权方式

### ISSUE THREAD

**Issue by r0ckychan** [chaitin/SafeLine#888]
### 反馈内容

经过一段时间的使用，感觉safeline确实是一款不错的产品。想着付费升级到专业版，看到每年1799的售价还是有点望而却步。
建议是否可以出一个个人专业版付费分支，功能开放，性能限制，价格适当调整。这样个人用户也可以做出一点点贡献。

**Comment by 5icorgi** [comment]
复议

**Comment by vip10218939** [comment]
复议

**Comment by nonex-code** [comment]
附议

**Comment by devhaozi** [comment]
支持

**Comment by Lorna0** [comment]
雷池社区版目前的体谅，难以支撑个人付费版的开发和售卖，短期内不会考虑。目前我们主要还是侧重企业与小微组织的售卖，个人用户可以继续使用社区版，我们也会继续迭代，感谢大家的支持。

**Comment by r0ckychan** [comment]
希望越来越好，感谢回复

**Comment by tian-sigons** [comment]
附议，nas用户挺多，一般就是软路由架一个雷池防入侵播客和小服务，像是什么节点功能都用不上，要是有个人用户可选救挺好
