### ISSUE TITLE
希望能web界面能增加访问统计（TOP10_IP/TOP_URI）

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#89]
希望能web界面能增加访问统计（TOP10_IP/TOP_URI）

**Comment by Lorna0** [comment]
关联一下 https://github.com/chaitin/safeline/issues/70 ，issue 中大家提到的统计维度有：

攻击类型、访问路径（Url）、目的 IP。

**Comment by chenmy2021** [comment]
建议增加站长页面统计功能

**Comment by xbingW** [comment]
问题建议反馈请移步 https://rivers.chaitin.cn/discussion
