### ISSUE TITLE
[建议] 控制台登录安全问题

### ISSUE THREAD

**Issue by Dream-s-Wang** [chaitin/SafeLine#890]
### 问题描述

登录页面密码明文传输
![image](https://github.com/chaitin/SafeLine/assets/42761641/deb2824f-3bbb-4309-8971-009186edd0ec)

### 版本号

5.6.1

### 复现方法

关闭两步验证后登录

### 期望的结果

在请求中看不到明文的密码

**Comment by Lorna0** [comment]
密码明文传输的风险在于中间人监控流量获取密码。而雷池控制台强制使用 https，不允许关闭，在 https 加密的情况下已经能很大程度避免中间人获取明文内容。你可以用同样办法测试其他系统的登录，大多数都会在本地浏览器中看到明文密码，包括 Github。

有些系统确实会做一些 https 之外的加密，一般是手动 RSA 一下，这其实只是重复了一次 https 做的事情，没有很显著的安全意义。如果确实担心明文风险，最好先把控制台的 https 证书换成自己可信的，然后每次登录前注意证书是否正常。再进一步可以开启两步认证。
