### ISSUE TITLE
[Bug] 目前添加站点之后 切换为观察模式 还是会拦截

### ISSUE THREAD

**Issue by luoye9711** [chaitin/SafeLine#892]
### 问题描述

目前添加站点之后 切换为观察模式 还是会拦截
添加域名设置源站为127.0.0.1:9443，反代雷池之后就出现了
拦截显示为 高频攻击 但是并没有相关的攻击日志在控制台

### 版本号

5.6.2

### 复现方法

添加站点设置源站为127.0.0.1:9443反代雷池，设置为 观察
之后在反代的域名url控制台中添加站点，就会拦截，其他规则尚未测试
拦截显示为 高频攻击 但是并没有相关的攻击日志在控制台
域名/?id=1'union select user(),1,3--，也会拦截（这个拦截有日志attack.type.-6）
运行模式为 观察

### 期望的结果

设置为观察之后就不会在拦截

**Comment by Lorna0** [comment]
没有复现。代理控制台后，观察模式下添加站点正常：

![Uploading image.png…]()

打 payload /?id=1'union select user(),1,3--，未拦截。
需要确认下是否匹配到了这个站点
