### ISSUE TITLE
[建议] 后端是动态域名时无法代理

### ISSUE THREAD

**Issue by ygrdsj** [chaitin/SafeLine#893]
### 背景与遇到的问题

后端是动态域名时，nginx需要配置set $backend=http://xxx.com, proxy_pass $backend才能更新动态域名解析出的IP，现在WAF不能代理类似$backend这样的参数

### 建议的解决方案

希望WAF可以代理到$backend这样的参数

**Comment by Lvshujun0918** [comment]
可以自己到proxy_params里面设置，参见官网文档

**Comment by ygrdsj** [comment]
根据这个方法配置：https://waf-ce.chaitin.cn/docs/faq/other#自定义站点-nginx-conf
1、set $backend=http://xxx.com/; proxy_pass $backend; 都配置到custom_params/backend_XXX，不注释IF_backend_XXX中的proxy_pass，nginx -t报错；
2、set $backend=http://xxx.com/; proxy_pass $backend; 都配置到custom_params/backend_XXX，注释IF_backend_XXX中的proxy_pass，Web控制台报错，无法再修改相关站点的配置；
3、只把 set $backend=http://xxx.com/; 配置到custom_params/backend_XXX，修改IF_backend_XXX中的proxy_pass为proxy_pass $backend;  容器重启或者修改配置后IF_backend_XXX中的proxy_pass会还原成原来的状态
综上均达不到完美代理动态域名的目的

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
