### ISSUE TITLE
[Bug] 雷池更新到最新版本后，添加站点报错

### ISSUE THREAD

**Issue by R0A1NG** [chaitin/SafeLine#895]
### 问题描述

添加任何域名，使用ssl时报错
![image](https://github.com/chaitin/SafeLine/assets/66672984/f3c0fa20-769f-4fa3-9fc1-331fee377031)

### 版本号

5.6.2

### 复现方法

雷池最新版本添加站点

### 期望的结果

报错

**Comment by safe1ine** [comment]
This issue has been resolved in the latest version
