### ISSUE TITLE
管理页面无版本号信息

### ISSUE THREAD

**Issue by luweijun1992** [chaitin/safeline#9]
v1.0.2
如标题，当前管理页面上无版本号信息，建议增加上。
且能够检测是否有新版本发布。

**Comment by zclaiqcc** [comment]
V1.2 已经支持了版本号信息的展示。是否有新版本发布这个还在排期中

**Comment by zclaiqcc** [comment]
V1.4 增加了新版本的提示，V1.5 发布的时候可以关注一下 V1.4 左下角会有气泡提示
