### ISSUE TITLE
[建议] 通过界面进行站点与系统配置的备份与还原

### ISSUE THREAD

**Issue by ezjbc** [chaitin/SafeLine#90]
希望防护站点-站点配置能批量导入导出

**Comment by zclaiqcc** [comment]
了解一下，什么场景下需要用到导入导出功能呢，以及大概是有多少站点呢

**Comment by ezjbc** [comment]
怕哪天服务器崩了，可以导出配置本地备份下。重新部署，可以快速导入上线。

**Comment by D0n9** [comment]
> 怕哪天服务器崩了，可以导出配置本地备份下。重新部署，可以快速导入上线。

配置都在数据库中，备份数据库就行了

**Comment by ezjbc** [comment]
> 直接每日定时备份 ./safeline 文件夹呗？

你肯定是想把这个功能加到企业版去。

**Comment by zclaiqcc** [comment]
企业版已经支持备份还原了，但是我是因为包含一些硬件层面的配置，集群模式的快速同步等复杂场景。纯软件的话，直接整机备份感觉也问题不大？保留最近一天或者七天的备份，出问题直接还原就行。

**Comment by huangyitong** [comment]
导入导出可以添加这个功能，比如我有20个站点 我要快速添加进去的话 可以通过excel导入 就不需要一个一个的添加站点

**Comment by lijian1135** [comment]
+1 非常需要

**Comment by zhuanmentiwen** [comment]
如果先给个站点配置和黑名单的备份也行。。。

**Comment by Lorna0** [comment]
根据讨论内容，合并 #219 的讨论，改为 “站点与系统配置的备份与还原”，那边也有一些讨论可以参考：
* https://github.com/chaitin/SafeLine/issues/219

如果有师傅想要 “站点导入导出”，即 “快速添加站点” 的话，麻烦提个新 issue 单独讨论。

**Comment by xbingW** [comment]
问题反馈建议请移步论坛 https://rivers.chaitin.cn/discussion
