### ISSUE TITLE
[建议] 频率限制日志 支持按时间过滤

### ISSUE THREAD

**Issue by toyops** [chaitin/SafeLine#904]
### 背景与遇到的问题

高频访问限制。这个功能，实际是与站点挂钩，需要分析查看日志时没有站点信息，不知道具体被限制的IP 是哪个站点的。以及有需求需要定位今天过滤了那些IP，某个时间段有哪些IP被限制。

### 建议的解决方案

建议增加站点关联信息，添加时间过滤功能方便查看IP被限制的情况。

**Comment by Lorna0** [comment]
高频访问限制目前不与站点挂钩，是全局统计和限制的。你可能想讨论的是：
* https://github.com/chaitin/SafeLine/issues/209

时间过滤方面，因为目前限制日志列表本身就按时间排序，所以单独增加时间筛选的优先级比较低。如果你有更明确的场景，可以描述一下，收集下社区的意见，反馈的人多的话我们也会优先考虑。

**Comment by toyops** [comment]
> 高频访问限制目前不与站点挂钩，是全局统计和限制的。你可能想讨论的是：
> 
>     * [[建议] 频率限制基于 host 或站点或 URL 进行统计 / 为不同网站配置不同的限频 #209](https://github.com/chaitin/SafeLine/issues/209)
> 
> 
> 时间过滤方面，因为目前限制日志列表本身就按时间排序，所以单独增加时间筛选的优先级比较低。如果你有更明确的场景，可以描述一下，收集下社区的意见，反馈的人多的话我们也会优先考虑。

用户会反馈某个时间段无法访问，我需要去定位查看，没有时间过滤只能一页一页翻。

**Comment by xbingW** [comment]
最新版 6.9.0 已经支持
