### ISSUE TITLE
[建议] 高频访问限制 里面如果能设置限制请求规则就好了，比如：限制某个前缀/user/**或某个后缀*.do。因为现在的很多项目都是前后端分离的，我们可能更想保护后端的接口

### ISSUE THREAD

**Issue by szp6269** [chaitin/SafeLine#909]

**Comment by Lorna0** [comment]
你应该说的是：
* https://github.com/chaitin/SafeLine/issues/209

不过没理解前后端分离跟这个有什么关系，是指类 RESTful API 和前端静态资源分开防护？那可能是这个：
* https://github.com/chaitin/SafeLine/issues/358

可以集中到之前 issue 中点赞和讨论
