### ISSUE TITLE
[建议] 清理数据库日志建议增加周期限制功能

### ISSUE THREAD

**Issue by redzl** [chaitin/SafeLine#910]
### 背景与遇到的问题

目前我们的硬盘空间有限，在postgresql 占用了大量磁盘空间的情况下，我们考虑清除部分日志来腾出空间。但是通过检索文档后发现，只有 “docker exec safeline-mgt cleanlogs“命令可以满足我们的需求，但是这个命令是清除所有数据库日志。

### 建议的解决方案

希望能增加删除X天之前日志的一个功能，比如 docker exec safeline-mgt cleanlogs 7，这里的7代表删除7天之前的日志。

**Comment by Lorna0** [comment]
relate to:
* https://github.com/chaitin/SafeLine/issues/63

**Comment by xbingW** [comment]
最新版 6.9.0 支持清理 30 天日志，还有问题请移步  https://rivers.chaitin.cn/discussion
