### ISSUE TITLE
[Bug] 上游服务器无法正确解析同一Docker网络下的hostname

### ISSUE THREAD

**Issue by manjieqi** [chaitin/SafeLine#911]
### 问题描述

<img width="207" alt="Snipaste_2024-06-05_23-33-34" src="https://github.com/chaitin/SafeLine/assets/40858189/42da76c8-561d-4cfc-9156-20b7630a0d90">

在创建网站容器的时候指定了和雷池WAF相同的docker网络

<img width="507" alt="Snipaste_2024-06-05_23-34-04" src="https://github.com/chaitin/SafeLine/assets/40858189/c386121f-9422-4dee-9977-1aa37884e8ac">

用docker network inspect safeline-ce查看，网站容器已经正确附加

<img width="473" alt="Snipaste_2024-06-05_23-25-42" src="https://github.com/chaitin/SafeLine/assets/40858189/f61e8cc4-a430-44ff-804c-04c7b940d555">

但是配置上游服务器时，网站容器解析出的IP错误

<img width="438" alt="Snipaste_2024-06-05_23-33-21" src="https://github.com/chaitin/SafeLine/assets/40858189/2091adca-743b-47d4-b49b-db205ae9b6c3">

使用inspect查询到的IP则可以正常访问

添加到同一docker网络，把容器名作为主机名，就不需要容器映射宿主机端口（就像上面compose文件里面映射被注释），不知道为什么WAF提示错误。临时的解决方法是，创建容器是同时指定IP，就不需要手动去查，但是还是不方便。

希望解决一下

https://docs.docker.com/network/

### 版本号

Version 6.0.2

### 复现方法

正常安装雷池WAF

`services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    # ports:
    #   - 5230:5230
    volumes:
      - ./data:/var/opt/memos
    environment:
      - TZ=Asia/Shanghai
    networks:
      - safeline-ce
    restart: unless-stopped

networks:
  safeline-ce:
    external: true
`

启动网站容器后配置上游服务器

### 期望的结果

网站容器添加到雷池WAF的Docker网络后，上游服务器配置那里可以直接用容器名加端口

**Comment by Lvshujun0918** [comment]
权宜之计是把docker容器端口映射到127.0.0.1

**Comment by xbingW** [comment]
> 权宜之计是把docker容器端口映射到127.0.0.1

因为 tengine 的 network 是 host 模式，无法解析是正常的。建议采用此方案

**Comment by manjieqi** [comment]
> > 权宜之计是把docker容器端口映射到127.0.0.1
> 
> 因为 tengine 的 network 是 host 模式，无法解析是正常的。建议采用此方案

这就是经常端口占用的问题
