### ISSUE TITLE
[建议] 社区版的“检测引擎性能配置”增加和开放“双线程模式”

### ISSUE THREAD

**Issue by Pingmin** [chaitin/SafeLine#914]
### 背景与遇到的问题

背景：因为目前的机器，就算是最普通的单核 CPU，也一般都支持超线程技术，模拟出两个逻辑处理器（即 vCPU）。

### 建议的解决方案

建议：请考虑在社区版“检测引擎性能配置”中增加并开放“双线程模式”。
谢谢！

**Comment by safe1ine** [comment]
Thank you for your feedback. 
However, this feature will have a great impact on the commercial sales of SafeLine. 
We will not consider it for the time being because we need sufficient income to support the continued development of the community.

**Comment by Pingmin** [comment]
好的，谢谢，对你所说的表示理解。

作为个人最近的试用和比较，在某些方面，这个[南墙 WAF(`uuWAF`)](https://github.com/Safe3/uuWAF)会更适合普通用户……
