### ISSUE TITLE
[建议] 更多的付费模式，个人专业版

### ISSUE THREAD

**Issue by X142150** [chaitin/SafeLine#917]
### 背景与遇到的问题

相比较专业版完善的功能，对于个人开发者，有可能只是用于一些小网站的维护，专业版成本较高

### 建议的解决方案

建议推出一个个人专业版，可以提供推送告警信息以及一些其他的较为基础的专业版功能

**Comment by Lorna0** [comment]
暂时不考虑。参考：
* https://github.com/chaitin/SafeLine/issues/888
