### ISSUE TITLE
Version 6.0.3版本使用部署后无法添加站点，safeline-tengine报错

### ISSUE THREAD

**Issue by liuts** [chaitin/SafeLine#918]
### 反馈内容

系统：centos7.3
环境：docker compose
问题：无法添加站点，safeline-tengine有报错日志

nginx后面有两个//,不知道为什么

`sed: can't read /etc/nginx//sites-enabled/IF_backend_*: No such file or directory
nginx: [emerg] invalid IPv6 address in resolver "[fe80::1%ens33]" in /etc/nginx/nginx.conf:132
sed: can't read /etc/nginx//sites-enabled/IF_backend_*: No such file or directory
nginx: [emerg] invalid IPv6 address in resolver "[fe80::1%ens33]" in /etc/nginx/nginx.conf:132
sed: can't read /etc/nginx//sites-enabled/IF_backend_*: No such file or directory
nginx: [emerg] invalid IPv6 address in resolver "[fe80::1%ens33]" in /etc/nginx/nginx.conf:132
sed: can't read /etc/nginx//sites-enabled/IF_backend_*: No such file or directory
nginx: [emerg] invalid IPv6 address in resolver "[fe80::1%ens33]" in /etc/nginx/nginx.conf:132
`

**Comment by Lorna0** [comment]
https://github.com/chaitin/SafeLine/discussions/689
