### ISSUE TITLE
SSE (Server Sent Events) 不會動了

### ISSUE THREAD

**Issue by git-show** [chaitin/SafeLine#919]
### 反馈内容

升級到最新版發生SSE不動，舊版可行，還請確認。

**Comment by Lorna0** [comment]
哪里到哪里的 SSE？

**Comment by git-show** [comment]
前端的網頁 -> WAF
我是用Esxi後台
升級版本 6 後event沒有反應
還原 5 後 正常反應
前端沒有任何改變

**Comment by Lorna0** [comment]
你是指你的网站上存在一些 SEE 的 API ，经过 6.0 版本的雷池代理之后，这些 SEE 的 API 就不能工作了？

**Comment by git-show** [comment]
是的，還原後就會動了。

**Comment by xbingW** [comment]
能否给一个最小可复现的 demo ？

**Comment by git-show** [comment]
查到原因了，nginx升級後對上游服服器端的header檢查更嚴格，原本不會錯誤的出現錯誤，修正服服器端的Lib後問題解決，謝謝。
