### ISSUE TITLE
traefik代理safeline；访问401

### ISSUE THREAD

**Issue by airseal** [chaitin/SafeLine#922]
### traefik代理访问显示，api401
<img width="1919" alt="image" src="https://github.com/chaitin/SafeLine/assets/47023410/47a0d33f-17ad-4656-96cf-b2b9cfbb611a">
<img width="1919" alt="image" src="https://github.com/chaitin/SafeLine/assets/47023410/c52ff082-0226-4f90-9934-3f80e2340fa5">

### IP:端口访问正常
<img width="1511" alt="image" src="https://github.com/chaitin/SafeLine/assets/47023410/8d2f4de1-16d5-41e9-bed0-a6084cdf8a4f">

###  Traefik日志：

192.168.3.101 - - [11/Jun/2024:14:36:35 +0000] "GET /login HTTP/2.0" 200 1992 "-" "-" 310 "mgt@docker" "https://172.22.222.4:1443" 5ms
192.168.3.101 - - [11/Jun/2024:14:36:36 +0000] "GET /api/open/system/protocol HTTP/2.0" 200 33 "-" "-" 311 "mgt@docker" "https://172.22.222.4:1443" 1ms
192.168.3.101 - - [11/Jun/2024:14:36:36 +0000] "POST /api/open/behaviour HTTP/2.0" 400 559 "-" "-" 313 "mgt@docker" "https://172.22.222.4:1443" 0ms
192.168.3.101 - - [11/Jun/2024:14:36:36 +0000] "GET /api/open/system/authorize HTTP/2.0" 401 59 "-" "-" 315 "mgt@docker" "https://172.22.222.4:1443" 0ms
192.168.3.101 - - [11/Jun/2024:14:36:36 +0000] "GET /api/open/system HTTP/2.0" 401 59 "-" "-" 314 "mgt@docker" "https://172.22.222.4:1443" 0ms
192.168.3.101 - - [11/Jun/2024:14:36:36 +0000] "GET /api/open/auth/csrf HTTP/2.0" 200 51 "-" "-" 312 "mgt@docker" "https://172.22.222.4:1443" 1001ms

**Comment by Lorna0** [comment]
我们不是 traefik 的开发者，不了解 traefik 的具体代理实现，光看日志判断不出来什么原因。可以尝试参考 https://waf-ce.chaitin.cn/docs/faq/config#%E6%8E%92%E6%9F%A5%E6%AD%A5%E9%AA%A4 文档中的操作，测试一下 客户端-Traefik、Traefik-雷池 之间的访问情况和错误日志

**Comment by xbingW** [comment]
更新插件版本再试一下

**Comment by sysiocn** [comment]
好的，1.5插件修复问题了
