### ISSUE TITLE
[建议] 添加站点的时候上游服务器希望能添加多个端口

### ISSUE THREAD

**Issue by apple524** [chaitin/SafeLine#923]
### 背景与遇到的问题

添加站点的时候能添加多个域名和端口，对应的添加上游服务器时只能填写一个端口，如果需要多个端口对应的话目前只能写多条记录，是否能加多个对应的端口。

**Comment by Lorna0** [comment]
什么情况需要添加多个端口呢

**Comment by apple524** [comment]
网站有80端口 443端口还有些手机app的端口，如果有多个应用的话就要些好多条
我在测试怎么在Exchange邮件服务器前加一下雷池，这样也涉及到很多端口，就要写多条

**Comment by Lorna0** [comment]
> 网站有 80 端口 443 端口

只配置一个端口就可以了，上游把 80、443 都配上没有什么意义呀。如果想让网站用户 http 自动跳转到 https，那在雷池上（也就是用户-雷池之间）配就行了。

> 还有些手机app的端口，如果有多个应用的话就要些好多条

不同的应用建议配成不同的站点？如果都配置成一条的话，后续的列表展示、策略管理都会不那么方便。

**Comment by JunTsao** [comment]
> 网站有80端口 443端口还有些手机app的端口，如果有多个应用的话就要些好多条 我在测试怎么在Exchange邮件服务器前加一下雷池，这样也涉及到很多端口，就要写多条

兄弟，exchange服务器测试的怎么样了，有用上吗？

**Comment by apple524** [comment]
> > 网站有80端口 443端口还有些手机app的端口，如果有多个应用的话就要些好多条 我在测试怎么在Exchange邮件服务器前加一下雷池，这样也涉及到很多端口，就要写多条
> 
> 兄弟，exchange服务器测试的怎么样了，有用上吗？

不能用在Exchange上的，这个只是网站防火墙

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
