### ISSUE TITLE
[Bug] resources/chaos 目录不会自动创建

### ISSUE THREAD

**Issue by HADB** [chaitin/SafeLine#927]
### 问题描述

安装报错：
Error response from daemon: Bind mount failed: '/volume3/docker/safeline/resources/chaos' does not exists

### 版本号

2024.6.12 latest

### 复现方法

bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/setup.sh)"

### 期望的结果

安装成功

**Comment by xbingW** [comment]
这个是 docker 负责创建的，建议搜索 docker 相关自动创建失败的问题

**Comment by HADB** [comment]
问题是直接用的你们的 setup.sh 脚本启动的，这完全是黑盒，得在你们脚本内解决吧，其他开源项目的容器启动从来没出现过这个问题。
不过也不重要了，已经放弃了。文档也不是很完善，离“开箱即用”还差点意思。

**Comment by Lorna0** [comment]
setup.sh 脚本是开放的啊，你直接 curl 就能看见完整信息

**Comment by HADB** [comment]
脚本是可以看到，但我理解作为用户，不需要关注脚本内怎么实现，应该开箱即用，需要的挂载的子目录自动建好，文档里也没说需要手动创建 /resources/chaos 目录

**Comment by Lorna0** [comment]
> 脚本是可以看到，但我理解作为用户，不需要关注脚本内怎么实现，应该开箱即用，需要的挂载的子目录自动建好，文档里也没说需要手动创建 /resources/chaos 目录

我只是解释一下你所说的 “这完全是黑盒，得在你们脚本内解决吧”，因为这是个 bash 脚本，不可能黑盒。

这个报错的处理思路上面的师傅也已经大致解释了一下，雷池依赖 docker ，这个文件确实是雷池在程序中让 docker  **自动创建的** ，目前交流群几千个群友这里都创建成功了，还没有其他人反馈这个创建失败的问题。为什么你的 docker 创建失败了，我们也不知道，因为 **docker 不是我们开发的**，只能猜测是 docker 的故障或者在你的环境有什么兼容性问题，所以 “建议搜索 docker 相关自动创建失败的问题”。根据我在谷歌粗略搜索的结果，我猜测可能是群晖 NAS 上的 兼容性问题，我们之前也是有用户在群晖上动手成功部署了雷池的，你也可以直接搜索群晖雷池。

另外，如果你认为都什么都需要项目内自动解决，即使是偶现问题也必须一一排查支持的话，雷池社区版开发组确实没有这个精力，因为社区的其他反馈和我们想做的优化都有很多，真的非常抱歉。如果你是中大型网站、甚至企业组织的话，可以专业版和企业版，因为那边的支持精力更富余，我们可以帮你申请那边的资源来为你排查问题。你可以直接从 [官网](https://waf-ce.chaitin.cn/version) 获取专业版，或者留下联系方式等待企业版的商务对接。也可以直接在微信交流群中联系我们咨询。

很感谢你愿意试用社区版。

**Comment by maodi0614** [comment]
我也是群晖用户出现了同样的问题，我手动部署也失败了。不清楚什么原因，毕竟是社区版，只能自己摸索了。
