### ISSUE TITLE
请问一下如果要在Exchange邮件服务器前部署雷池，需要怎么配置？

### ISSUE THREAD

**Issue by apple524** [chaitin/SafeLine#928]
### 反馈内容

![image](https://github.com/chaitin/SafeLine/assets/44286181/05295274-677a-47b0-b055-3543bc83524b)

可以实现在exchange服务器前面做防护吗？

**Comment by Lorna0** [comment]
雷池是 WAF (web application firewall) 即  **Web 应用防火墙**，暂时不考虑其他协议的防护。不清楚 Exchange 具体使用了哪些服务，你可以测试一下。
