### ISSUE TITLE
[建议] 在站点编辑页面增加开启 OCSP stapling 的选项

### ISSUE THREAD

**Issue by eagleyan888** [chaitin/SafeLine#929]
因为在国内 Let's Encrypt 被DNS污染导致苹果手机访问速度慢，Nginx 可以开启 OCSP 解决此问题（详情请参考 https://cloud.tencent.com/developer/article/1965319 ），但是目前雷池waf不支持在nginx的server这一层增加相应配置。

建议站点编辑页面增加一个checkbox勾选项：开启OCSP stapling ，用户勾选了就在server这一层增加：
        ssl_stapling on;
        ssl_stapling_verify on;

_Originally posted by @eagleyan888 in https://github.com/chaitin/SafeLine/issues/385#issuecomment-2161998816_

**Comment by xbingW** [comment]
目前引擎不支持
