### ISSUE TITLE
希望增加ip访问频率、次数的自定义拦截规则配置

### ISSUE THREAD

**Issue by jklZy1** [chaitin/safeline#93]

**Comment by clqs803** [comment]
希望这个早日实现，手动拉黑IP会漏掉好多没看到的

**Comment by dhfsqxz** [comment]
帮顶
这个功能我认为可以参考阿里云waf的扫描防护
触发基础防护规则多少次或者扫描空目录比例大于多少
直接拉黑ip

**Comment by DeronW** [comment]
> 

这个指的是在线的 “威胁情报源” + 本地的 IP 自动封禁功能组合吗？

**Comment by DeronW** [comment]
> 帮顶 这个功能我认为可以参考阿里云waf的扫描防护 触发基础防护规则多少次或者扫描空目录比例大于多少 直接拉黑ip

这个指的是在线的 “威胁情报源” + 本地的 IP 自动封禁功能组合吗？

**Comment by naocanmonster** [comment]
支持，这个我自己也需要

**Comment by xiaofg** [comment]
现在缺少自定义拦截规则配置很是不方便

**Comment by thj8** [comment]
希望这个早日实现

**Comment by lem0ke** [comment]
帮顶，同希望可以联动威胁情报源

**Comment by Lorna0** [comment]
与 https://github.com/chaitin/safeline/issues/29 重复了，这边先 close，在 29 继续跟进。

**Comment by jinhaozcp** [comment]
希望可以增加对于接口的限频

**Comment by Lorna0** [comment]
> 希望可以增加对于接口的限频

这边是重复 issue，已经 close 了，建议在未关闭的 https://github.com/chaitin/safeline/issues/29 里讨论
