### ISSUE TITLE
[Bug] 文件上传被限制大小，配置的参数无法生效

### ISSUE THREAD

**Issue by wenjing-xin** [chaitin/SafeLine#930]
### 问题描述

文件上传失败，配置不生效
![image](https://github.com/chaitin/SafeLine/assets/130843859/9015a4f0-7d39-4f23-92c1-b737a619849a)

### 版本号

6.0.3

### 复现方法

已经在/data/safeline/resources/nginx/custom_params下相应的配置文件配置了如下参数，
```shell
client_max_body_size 200m;
client_body_buffer_size 100m;
```
之后使用命令 `docker exec safeline-tengine nginx -t、 docker exec safeline-tengine nginx -s reload`也是正常的，为了保证生效，我又重启了docker里的所有容器，但还是不生效，站点控制台说是防火墙 我很不理解

### 期望的结果

文件正常上传，按照我限制的最大容量使用

**Comment by Lorna0** [comment]
无法复现，尝试修改了一下是可以生效的。可以查一下上游是否有其他代理设备有大小限制。

**Comment by Lorna0** [comment]
relate to:
* https://github.com/chaitin/SafeLine/issues/801

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
