### ISSUE TITLE
为什么http无法访问

### ISSUE THREAD

**Issue by LoLoLi666** [chaitin/SafeLine#932]
### 反馈内容

监听了443以及80端口、http无法访问，需要https才可以访问。源站设置了强制HTTPS。站长工具[HTTP状态查询]应该显示301才是的。但是使用了雷池后、站长工具HTTP状态查询的结果是：检测异常,可能是域名未解析或网站无法访问。
之前使用宝塔WAF是可以强制301到HTTPS的、
请问这要怎么处理呢？

**Comment by Lorna0** [comment]
无法复现，建议提供更多信息
