### ISSUE TITLE
[建议] apisix 插件联动支持人机验证

### ISSUE THREAD

**Issue by xiaoxuanyo** [chaitin/SafeLine#933]
### 反馈内容

![image](https://github.com/chaitin/SafeLine/assets/65661595/35bf61f0-4328-40d5-a406-9487c1769ef4)
![image](https://github.com/chaitin/SafeLine/assets/65661595/a87f6833-31c7-4730-9d75-c1299cb2485c)

**Comment by xiaoxuanyo** [comment]
但是改成【直接封禁】的话，可以生效，达到限制后会访问失败：配置成【人机验证】，并且自定义规则中添加了自定义的人机规则，并且规则也显示命中，但是waf依旧允许流量访问上游，而不会进行人机验证，有朋友能帮忙解答下吗

**Comment by Lorna0** [comment]
apisix 和雷池插件部署时，雷池插件会检测流量并通过状态码告诉 apisix 请求是否合法，apisix 则根据状态码进行放行(200)或者拦截(403)。人机验证的状态码是 200，所以放行了。

人机验证目前在 apisix 上不能生效。因为人机需要返回验证页面，而 apisix 联动目前不支持返回页面。需要额外适配，有点麻烦，留着收集意见。

**Comment by safe1ine** [comment]
社区版的联动 SDK 暂时不考虑增加除了基础防护以外的其他能力，如有需要可购买企业版
