### ISSUE TITLE
http

### ISSUE THREAD

**Issue by LoLoLi666** [chaitin/SafeLine#934]
### 反馈内容

就像宝塔waf，http://xx.com去访问，能直接301跳转到https://www.xx.com
而使用雷池WAF后，http://xx.com是无法打开。需要https才会跳转到https://www.xx.com

还有就是360抓取诊断 抓取失败。
错误信息
Unknown SSL protocol error in connection to XX.XX.XX.XX:443
而宝塔WAF是正常的。
请问这些问题需要如何处理？

**Comment by Lorna0** [comment]
网络、dns、设备防火墙，这些出问题了都可能导致代理不了。雷池社区版为保证兼容性，以 docker 容器形态部署，控制不了这些因素。你说的这样的问题跟宝塔 waf 和雷池 waf 没有关系。

另外 “Unknown SSL protocol error” 这个错误太模糊了，判断不出来。麻烦按照官网的技术文档获取一下错误日志吧：https://docs.waf-ce.chaitin.cn/zh/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%8E%92%E6%9F%A5/%E9%85%8D%E7%BD%AE%E9%97%AE%E9%A2%98

另外，既然用了宝塔 waf，我盲猜原因是宝塔的管理面板装的 nginx，它会强制占用 80 端口。如果设备上也有宝塔，那装其他任何家的 waf 都访问不了，必须先去把宝塔上占的 80 给释放了。具体操作可以百度一下。

duplicate：
* https://github.com/chaitin/SafeLine/issues/932
