### ISSUE TITLE
[suggestion] Can I add a upstream domain name to the site configuration?

### ISSUE THREAD

**Issue by cloudsnet** [chaitin/SafeLine#935]
### 背景与遇到的问题

站点配置是否可以增加一个回源域名，解决跨服务器商检测备案的问题

**Comment by Lorna0** [comment]
没理解，为什么要配置回源域名来解决跨服务器商检测备案的问题呢，能否具体说一下

**Comment by cloudsnet** [comment]
waf一般配置在单独服务器，
公司站点部署在不同云服务商上，目前通过Ip访问上游服务器，就会涉及到不同云服务商ipc备案检测的问题
例如：waf在阿里云，真实站点有的在腾讯云，域名备案也在阿里云，waf访问腾讯云站点时就会导致腾讯检测到IPC在腾讯云没有备案，所以就需要有类似cdn一样的设置，回源域名

**Comment by cloudsnet** [comment]
> 不知道大家有没有遇到过配置回源域名的问题呢，能否具体说一下

waf一般配置在单独服务器，
公司站点部署已经在云服务商上，目前通过Ip访问上游服务器，就会在下面不同云服务商ipc备案检测问题，
例如：waf在阿里云，真实站点有在腾讯云，域名备案也在阿里云，waf访问腾讯云站点时会导致腾讯云检测到IPC没有备案，所以就需要有类似的cdn一样的设置，回源域名
