### ISSUE TITLE
在windows的wsl环境中部署失败

### ISSUE THREAD

**Issue by k4n5ha0** [chaitin/SafeLine#937]
### 反馈内容

看过之前的issues没有明确说wsl环境是否能否部署成功。
目前是配置了80端口后，并没有新增监听80端口的容器
win10，wsl2默认安装

**Comment by Lvshujun0918** [comment]
看一眼docker运行情况

**Comment by safe1ine** [comment]
wsl 和真实的 linux 在底层有诸多不同，暂时不考虑支持，谢谢反馈
