### ISSUE TITLE
[建议] 能不能针对不同网站允许采用不同频率限制 

### ISSUE THREAD

**Issue by Tobby-000** [chaitin/SafeLine#938]
### 背景与遇到的问题

我用雷池托管了多个网站，其中一个网站有较多图片资源，导致短时间请求量非常大。而其他网站则没有这个情况，所以如果采用较低的频率限制则有大量图片资源的网站将时常被限制。而采用较高的频率限制则其他网站无法做到更好的防护。

### 建议的解决方案

希望可以在不同网站可以设置不同的高频访问限制策略，以达到不同网站的需求。

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/209
