### ISSUE TITLE
v1.8.1 版本首页统计显示不一致问题

### ISSUE THREAD

**Issue by hale177** [chaitin/safeline#94]
首页 最上面【今日拦截】显示是正确的 ，第一天刚部署上线 
![图片](https://github.com/chaitin/safeline/assets/116779418/3b79ce55-4cef-4d0d-b996-6cdad8173764)

但是首页最下面的【30天拦截情况】  的数据和【30天访问情况】 完全一样，正确应该是累加上面的【今日拦截】30天总和
![图片](https://github.com/chaitin/safeline/assets/116779418/bd0eedf8-0dbc-4d89-b800-95b9cf3b21b0)

**Comment by zclaiqcc** [comment]
已确认是前端显示问题，今天会发布 1.8.2 进行修复

**Comment by zclaiqcc** [comment]
fixed in [v1.8.2](https://github.com/chaitin/safeline/releases/tag/v1.8.2)
