### ISSUE TITLE
[建议] 希望能单独配置每个站点获取ip的方式，全局配置不太方便

### ISSUE THREAD

**Issue by microqs** [chaitin/SafeLine#940]
### 背景与遇到的问题

我司业务可能从不同的CDN或者上层其他waf转发到雷池，传递的源ip的header头可能不同，有的CDN-SRC-IP、x-real-ip、x-forwarded-for ，全局情况下可能没法获取到某些站点的真实来源ip
参考华为云waf的方式
配置代理
![image](https://github.com/chaitin/SafeLine/assets/26514281/7e96da94-4f1a-4c0f-a511-868e57116484)
![image](https://github.com/chaitin/SafeLine/assets/26514281/5d5cb69f-2da5-4e79-beeb-4421ce318513)

下面是阿里云waf
![image](https://github.com/chaitin/SafeLine/assets/26514281/0c01ead4-5130-4e32-adfe-df61406cf1fe)

### 建议的解决方案

默认使用网络连接获取IP，但是可以为某些站点配置ip头

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/436

另外可以优先考虑一下配置 XFF：
![image](https://github.com/chaitin/SafeLine/assets/56920727/36ed1a9e-b03b-4b52-95a8-d481b149f11b)

**Comment by microqs** [comment]
来源太多了，x-forward-for 一般过来都是2个，ip直接被识别为网络连接地址了，没法指定一个统一的

**Comment by Lorna0** [comment]
> 来源太多了，x-forward-for 一般过来都是2个，ip直接被识别为网络连接地址了，没法指定一个统一的

如果 XFF 内确实都是 2 个 ip 的话，可以直接选择 “取 XFF 中上上一级代理的地址”。

btw 企业版是支持每个站点分开配置的。社区版会考虑做，只是我们精力有限，只能参考社区普遍反馈来排期。目前这个问题已经有用户提交了相同的 issue（https://github.com/chaitin/SafeLine/issues/436），且点赞数一直只有 1。师傅想要的话可以集中到之前 issue 中点赞支持一下，这边重复的就关闭了。
