### ISSUE TITLE
升级后删除旧版本失败

### ISSUE THREAD

**Issue by NuanRMxi** [chaitin/SafeLine#945]
### 反馈内容

从6.0.3直接升级到6.1.2后，升级无异常，但是在删除旧版本时出现以下报错：   
>root@VM-4-11-ubuntu:~# docker rmi $(docker images | grep "safeline" | grep "none" | awk '{print $3}')  
>"docker rmi" requires at least 1 argument.  
>See 'docker rmi --help'.  
>  
>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]  
>  
>Remove one or more images

**Comment by Lorna0** [comment]
这个提示是 docker 报出的命令不合法的提示，你可以直接搜一下 docker 相关报错。
