### ISSUE TITLE
[Bug] Badge style issues

### ISSUE THREAD

**Issue by Lvshujun0918** [chaitin/SafeLine#946]
### 问题描述

![image](https://github.com/chaitin/SafeLine/assets/41245552/d66fe758-d31d-416b-b421-9ac0f005f680)
此处文字未居中, 希望调整

### 版本号

6.1.2

### 复现方法

切换到攻击页面即可看见

### 期望的结果

正确的居中或者缩短宽度

**Comment by Lvshujun0918** [comment]
![image](https://github.com/user-attachments/assets/7132d22b-22aa-465d-9d00-fcc62b947dd5)
当前是一宽一窄还是不大对

**Comment by awesomeYG** [comment]
I will change it immediately

**Comment by xbingW** [comment]
Released in 6.4.0
