### ISSUE TITLE
是否支持SSLv3协议？

### ISSUE THREAD

**Issue by carrypann** [chaitin/SafeLine#947]
### 反馈内容

站点开启了HTTPS，遇到客户端固定用SSLv3，我通过修改雷池 nginx.conf，将 SSLv3 添加进ssl_protocols列表中（默认配置没有 SSLv3），出重启后依然不生效，请问雷池 waf 对这一块有什么特殊处理吗？

**Comment by Lorna0** [comment]
5.6.1 版本升级了 nginx，支持 openssl 3.0，对 ssl 的安全要求提高了：https://serverfault.com/questions/1151504/nginx-1-25-3-on-docker-tlsv1-is-not-working

需要修改的话，在这里增加 SECLEVEL=1改为SECLEVEL=0 就可以：
![image](https://github.com/chaitin/SafeLine/assets/56920727/a363cd94-a421-4d84-9b79-a917ae913504)


6.1.2 版本起，默认值会改为 SECLEVEL=0，与之前效果保持一致，方便手动调整。
