### ISSUE TITLE
[建议] 雷池控制台支持绑定域名

### ISSUE THREAD

**Issue by Gavin-TnT** [chaitin/SafeLine#958]
### 背景与遇到的问题

雷池控制台使用ip+端口访问，是否可以绑定自己的域名或域名+端口

### 建议的解决方案

雷池控制台使用ip+端口访问，是否可以绑定自己的域名或域名+端口

**Comment by Lorna0** [comment]
域名是通过 dns、设备 host 来指引的，雷池软件控制不了，你可以在需要的 dns 供应商处配置。

**Comment by Lorna0** [comment]
想要修改控制台默认的 9443 端口的话，可以修改启动时的 docker 配置文件，详情可以查阅官网技术文档。
