### ISSUE TITLE
健康检查的配置可以在后台修改吗

### ISSUE THREAD

**Issue by PuZhiweizuishuai** [chaitin/SafeLine#959]
### 反馈内容

这个健康检查功能每隔一分钟就向上有服务器发送请求，个人感觉有点过于频繁了，对于性能较弱的云主机来说，严重影响服务器性能。每隔一分钟CPU就会占用提高。

![屏幕截图 2024-07-01 000625](https://github.com/chaitin/SafeLine/assets/32362404/f83caff3-bfd9-4b06-98e6-85a22a0dff20)

我本来以为这个功能是通过 `safeline-tengine` 模块实现的，但是我查找了这里面的配置文件，并没有发现这个配置。

![屏幕截图 2024-07-01 000453](https://github.com/chaitin/SafeLine/assets/32362404/3c89dfb9-4c29-4f5f-889c-4b32833ee123)

我尝试注释掉了 `generated` 文件，也没有关闭这个功能

![屏幕截图 2024-07-01 000407](https://github.com/chaitin/SafeLine/assets/32362404/2c75a7ee-ce04-4452-80ac-727c7849373f)

希望后期可以增加自定义健康检查时间或者手动关闭这个功能。

**Comment by Lorna0** [comment]
duplicate：
* https://github.com/chaitin/SafeLine/issues/916

后续会优化，具体可以跟进上面这个重复 issue 的评论。
