### ISSUE TITLE
[Suggestion] challenge based on total requests from all IPs

### ISSUE THREAD

**Issue by 1718666698** [chaitin/SafeLine#960]
### 背景与遇到的问题

在网站访客少的时候不开启人机验证让用户有更好的访问体验

### 建议的解决方案

可以加个根据限定时间内访问量自动开启人机验证功能，在访问量少时自动关闭

**Comment by 1718666698** [comment]
> ### 背景与遇到的问题
> 在网站访客少的时候不开启人机验证让用户有更好的访问体验
> 
> ### 建议的解决方案
> 可以加个根据限定时间内访问量自动开启人机验证功能，在访问量少时自动关闭

**Comment by Lorna0** [comment]
直接 配置限频-人机验证 呢

**Comment by 1718666698** [comment]
那个限频只针对某一ip的访问的，我想要针对全站访问量来统计的

**Comment by Lorna0** [comment]
没想到有啥具体的 case 会需要这个功能诶。人机验证主要是防 bot 用的，确实是针对特定有问题的 IP 比全站开启好点。是出于高峰期性能压力的考虑吗，但是人机验证并不太能缓解服务器性能压力。

**Comment by DR-lin-eng** [comment]
> 没想到有啥具体的 case 会需要这个功能诶。人机验证主要是防 bot 用的，确实是针对特定有问题的 IP 比全站开启好点。是出于高峰期性能压力的考虑吗，但是人机验证并不太能缓解服务器性能压力。

他这个是考虑到平时正常访问量下不会触发人机验证，当被ddos时访问量会激增能自动化拉起人机盾，毕竟谁也不知道什么时候会被ddos攻击，ddos攻击有时候是ip量巨大的大部分ip可能是触发不了cc速率限制的

**Comment by Lorna0** [comment]
Gathering interst. Btw this issue seem to be work for this case:
https://github.com/chaitin/SafeLine/issues/974

**Comment by xbingW** [comment]
可以使用等候室，最新版已支持
