### ISSUE TITLE
[SUGGESTION] Waiting room

### ISSUE THREAD

**Issue by smallxu038** [chaitin/SafeLine#974]
### 背景与遇到的问题

当网站在短时间涌入大量访客，而不得不对访客限流，如果直接进行请求限制将导致访客误以为网站出现问题而离开。

### 建议的解决方案

增加一个等候室Waiting room功能，可以根据cookie跟踪用户，使用等候室来管理访客流量并避免服务器过载延迟，启用虚拟等候空间和排队系统，允许新用户进入等候室，在那里他们可以查看访问应用程序之前的估计等待时间。
在遭到HTTP DDoS时尤其管用。

参考:
https://docs.fortinet.com/document/fortiweb/7.4.3/administration-guide/820851/waiting-room
https://www.cloudflare.com/zh-cn/application-services/products/waiting-room/

**Comment by xbingW** [comment]
最新版已添加
