### ISSUE TITLE
[建议] 源 IP 获取方式自定义header可以设置多个

### ISSUE THREAD

**Issue by muziqiu2** [chaitin/SafeLine#977]
### 背景与遇到的问题

目前网站采用的cdn由多家提供，其中比如百度智能云的cdn，cloudflare及其他。在获取源ip的时候发现源ip的获取方式有些过于单一和限制了，不太适配使用多家cdn的情况，导致目前部分网站无法获取到源ip。
示例：
百度智能云
X-Forwarded-For: 218.27.172.54,123.184.58.61
X-Real-IP: 218.27.172.54
CloudFlare
X-Forwarded-For: 119.189.3.231
CF-Connecting-IP: 119.189.3.231
在这种情况，就无法使用取XFF上一级代理，因为百度智能云的CDN返回的ip将会是节点的而非用户的真实ip。

### 建议的解决方案

建议可以参考宝塔防火墙的设置，在自定义header处设置可以添加多个header，这样的话灵活性可以增加不少，同时可以解决多个站点CDN提供商真实ip获取header不同的的问题。![屏幕截图 2024-07-07 162202.png](https://free-img.400040.xyz/4/2024/07/07/668a50876f93b.png)

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/436
