### ISSUE TITLE
[SUGGESTION] add NOT CIDR in Custom Rules 'Source IP'

### ISSUE THREAD

**Issue by yaencn** [chaitin/SafeLine#980]
### 背景与遇到的问题

在实际使用中，自定义规则黑白名单的IP源中仅有“属于网段”但未有“不属于网段”的匹配方式，这导致如果要需要配置不属于网段的规则，需要先建立一个IP组，然后再选择“不属于IP组”，这样会比较麻烦。
![image](https://github.com/chaitin/SafeLine/assets/20335869/3ae0a8b1-c016-4464-ae70-153d47d264ab)

### 建议的解决方案

在自定义规则黑白名单的IP源中增加“不属于网段”的匹配方式

**Comment by xbingW** [comment]
最新版 6.9.0 已支持
