### ISSUE TITLE
如何把Let's Encrypt 的服务器IP加为白名单

### ISSUE THREAD

**Issue by bfqymmt** [chaitin/SafeLine#981]
### 反馈内容

为国外IP组做了黑名单，禁止国外IP访问。
但是，申请的SSL免费证书时，Let's Encrypt的服务器需要访问域名进行验证。我想把Let's Encrypt的IP加为白名单，但不清楚对方的IP。有没有其他办法，把Let's Encrypt的相关服务器加为白名单呢？通过路径或关键字呢？

![image](https://github.com/chaitin/SafeLine/assets/12575427/10d7111a-ca7c-4f35-ad49-c9d1b0219d09)

**Comment by Lvshujun0918** [comment]
[https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/17](https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/17)
看这里，你可以单独对.well-known目录加白

**Comment by Lvshujun0918** [comment]
[https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/17](https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/17)
看这里，你可以单独对.well-known目录加白
