### ISSUE TITLE
[SUGGESTION] Can the protection site page add search or filter ?

### ISSUE THREAD

**Issue by baalchina** [chaitin/SafeLine#982]
### 背景与遇到的问题

站点比较多的时候，就很难找到具体站点了。可否增加搜索或者筛选，这样可以快速定位到站点并即兴操作。

### 建议的解决方案

![image](https://github.com/chaitin/SafeLine/assets/3983019/d6477efe-4964-49bd-a123-85d46024d5d3)
如图所示...如果同时加上筛选（比如选择站点是否维护，选择防护模式。。。）等等

**Comment by zclaiqcc** [comment]
大概有多少个站点呢？

一般会在什么情况下使用筛选，可以举几个具体的例子么？比如因为经常有一些站点需要下线，所以希望筛选当前维护中的站点；因为有的站点希望经常修改防护策略，希望筛选这些使用不一样的防护策略的站点？

其实感受上来说浏览器的内置搜索功能就已经足够了？

**Comment by Lorna0** [comment]
站点列表没有分页，可以直接用浏览器筛选，暂时不会考虑增加近一步的筛选功能
