### ISSUE TITLE
[Bug] upstream url unsupport underline '_'

### ISSUE THREAD

**Issue by Sndav** [chaitin/SafeLine#985]
### What happened?

upstream域名无法添加下划线

### How we reproduce?

如图
<img width="662" alt="image" src="https://github.com/chaitin/SafeLine/assets/10370671/397504e2-cd61-4ee2-919a-fff4b84056e5">

### Expected behavior

校验通过

**Comment by Lorna0** [comment]
根据 https://cabforum.org/2018/11/12/ballot-sc12-sunset-of-underscores-in-dnsnames/ ，域名里不建议使用下划线。

如果当作 hostname 的话可以考虑。

**Comment by Sndav** [comment]
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/ad07f8b4-6c59-4c6f-8f3a-98dd8cb3236a">

不过还是建议增加一下这个功能

**Comment by Sndav** [comment]
您这个https://cabforum.org/2018/11/12/ballot-sc12-sunset-of-underscores-in-dnsnames/指的是TLS证书中的域名字段，不是dns解析的NAME

**Comment by Lorna0** [comment]
> 您这个[https://cabforum.org/2018/11/12/ballot-sc12-sunset-of-underscores-in-dnsnames/指的是TLS证书中的域名字段，不是dns解析的NAME](https://cabforum.org/2018/11/12/ballot-sc12-sunset-of-underscores-in-dnsnames/%E6%8C%87%E7%9A%84%E6%98%AFTLS%E8%AF%81%E4%B9%A6%E4%B8%AD%E7%9A%84%E5%9F%9F%E5%90%8D%E5%AD%97%E6%AE%B5%EF%BC%8C%E4%B8%8D%E6%98%AFdns%E8%A7%A3%E6%9E%90%E7%9A%84NAME)

没错，我的意思就是指 TLS 证书中的域名字段不建议使用下划线，所以不建议域名使用下划线。因为域名一般都需要证书，否则容易有安全问题。

域名中增加下划线确实是存在一定争议的，协议中允许，但是实际运用中可能存在一些问题。

不过考虑到 upstream 不一定是域名，也可能是 hostname，hostname 的要求就宽松多了，我们有空会改成允许下划线。

**Comment by Lorna0** [comment]
Released in 6.2.3
