### ISSUE TITLE
[Bug] 下载脚本和升级脚本判断能否访问docker hub方法有问题。

### ISSUE THREAD

**Issue by dominicx** [chaitin/SafeLine#989]
### What happened?

两个sh中判断脚本均是如下：
if [ -z "$CDN" ]; then
    if ping -c 1 -W 1 docker.com > /dev/null 2>&1; then
        CDN=0
    else
        CDN=1
        echo "检测到你的网络环境不支持直接访问 Docker Hub， 镜像将从华为云镜像仓库下载"
    fi
fi

对于采用了代理来访问hub.docker.com来说这个办法存在缺陷，建议改成curl或者wget 访问url来判断。

### How we reproduce?

1. ...
2. ...
3. ...

**Comment by safe1ine** [comment]
这种情况还不如直接手动安装。

**Comment by dominicx** [comment]
> 这种情况还不如直接手动安装。

也是。能解决docker hub问题的一般也能手动获取yaml文件安装。
