### ISSUE TITLE
[Bug] proxy ikuai meet 404 error

### ISSUE THREAD

**Issue by Pigeonszz** [chaitin/SafeLine#991]
### What happened?

在外网访问 ikuai 所属二级域名出现空白页面，开启调试工具后发现部分资源404

### How we reproduce?

1. 流量通过IPv6地址路由到 Lucky Web服务监听的88端口，反向代理到雷池WAF
2. 雷池WAF将流量反向代理到 ikuai 

### Expected behavior

所有资源应该显示200 OK 或 304 not modified

### Error log

![内网访问](https://github.com/user-attachments/assets/0aa1c030-69b2-4e49-b697-ec0f07ba468c)
![外网访问](https://github.com/user-attachments/assets/c67d7e04-279c-4f45-abd6-ae628a9cf7de)

**Comment by xbingW** [comment]
6.4.0 已修复
