### ISSUE TITLE
[SUGGESTION] config Rate Limiting by website

### ISSUE THREAD

**Issue by x3155104544** [chaitin/SafeLine#992]
### What would you like to be added or improved?

频率限制功能，如果可以对单个站点进行频率限制就好了！每站点请求频率不一样，设小了容易勿封，设大了，频率小的部点容易被刷。这一点别收费呀(இωஇ )

**Comment by Lorna0** [comment]
duplicate:
* https://github.com/chaitin/SafeLine/issues/209
