### ISSUE TITLE
[Suggestion] 自定义规则可以批量录入IP

### ISSUE THREAD

**Issue by qq280948982** [chaitin/SafeLine#994]
### What would you like to be added or improved?

<img width="601" alt="85f38ce6fc25171a36db1dc585caaf2" src="https://github.com/user-attachments/assets/e9f6e98e-f813-4988-a9e7-6a0bf5eb35d2">

添加自定义规则时，这里的匹配内容目前只能一个一个的录入IP，如果有大量的IP要录入要花费大量的时间，希望能够适配一行批量录入多个IP，多个IP之间用英文逗号分隔就好，填好后自动识别就方便多了

### Why is it needed?

能够节省大量的时间，提高用户体验

**Comment by safe1ine** [comment]
you can use it with ip group, not write ip one by one
