### ISSUE TITLE
[Suggestion] 一些使用下来的建议

### ISSUE THREAD

**Issue by longkey23** [chaitin/SafeLine#996]
### What would you like to be added or improved?

1.使用的IP加入我白名单之后，在使用我的网站还是会被高频限制给限制，影响体验，建议可以出一个针对高频限制的白名单；
2.本地服务器或者国内测试环境有时没有经过审核，或者80、443端口被限制，无法申请证书，建议出一个DNS验证申请证书；
3.waf的nginx代理功能还是有些简陋，建议可以出个可以自定义转发规则的窗口，提供给对nginx有其他需求的场景，在web界面写完的nginx规则，可以同步到服务器里面对应的nginx文件中去。
最后，祝雷池越来越好！祝长亭越来越好！！！

**Comment by Lvshujun0918** [comment]
1.我在使用的时候没有遇到，好像加白后就不受高频限制了。
3.感觉他们想减化降低使用门槛所以一直不加，现在只能在文件里自己改。

**Comment by longkey23** [comment]
加白以后我还是有遇到过高频限制，可能你是正常的网页访问吧，我是有一些服务器和后台同步数据，那些频率相对来说要高一些

**Comment by Lorna0** [comment]
1. 加白后不会进行高频限制。如果出现问题，我猜测是 IP 的获取方式没有配置对，导致没取到正确 IP
2. dns 证书有已存在的重复 issue，可以到对应 issue 下讨论点赞
3. 确实是上面师傅说的情况，我们希望降低使用门槛。另外一个原因是雷池的一些检测防护配置不能随意修改，否则容易冲突造成故障，导致改起来技术要求更高了。我们之后也会尽量再在 web 界面上多提供一些 nginx 代理相关的配置。
